### ISSUE TITLE
scaling heketi api?

### ISSUE THREAD

**Issue by wernergillmer** [heketi/heketi#1007]
Hi

I run a  kubernetes 1.7.0 cluster which get's used by multiple development teams, and one of the applications they frequently deploy is Minio(https://minio.io). I have noticed that sometimes, pvc's get's bounded with in seconds, and other times it can take up to 6-8mins. Looking at my kube-controller-manager logs, it seems it takes a while for the request to reach it. Is the slowness coming from heketi perhaps?
Can I scale out the heketi pod on my cluster? But then what happens with the boltdb it use?

**Comment by phlogistonjohn** [comment]
You can not run multiple instances of heketi against the same heketi db.

Heketi recently added support for request throttling that avoid slowdowns by pushing back on clients that are making many concurrent requests. This is available in the recently released Heketi v8.0.0. Could you please retest your scenario with that version and close the issue if things have improved? Thanks.
