### ISSUE TITLE
Way to map kubernetes PV to glusterfs volumes

### ISSUE THREAD

**Issue by rpalakodeti** [heketi/heketi#1009]
I am trying to map PVs in kubernetes to backend glusterfs volumes. I could not find any way in the API to get that information. It is useful specially when you have lot of pods and want to use backup and restore of data in case of issues.
If this feature is not available, can this feature be added. I was wondering at least during creation of new volume, the glusterfs cluster id, gulterfs volume id, and PV name be logged into a log file for reference.

**Comment by rpalakodeti** [comment]
figured out

**Comment by DanyC97** [comment]
@rpalakodeti you mind posting back so others do know about it ?
