### ISSUE TITLE
Enhancement: No Space with heketi:latest image - change error message

### ISSUE THREAD

**Issue by grantcurell** [heketi/heketi#1016]
I just spent ~5-6 hours trying to figure out why this wasn't working. About the point I was ready to throw my computer in frustration, I realized that what the error "No space" really means is "You need three nodes."

Recommend this error message be updated to something more meaningful to the user like: "It appears you only have two nodes and you need three for this deployment model."

I spent most of that 5-6 hours trying to discern how it was that I didn't have enough space when everything was telling me I had plenty.

**Comment by robertoalcantara** [comment]
I have similar problem but I have 3 nodes on Kubernetes/Heketi deployment. Maybe something else is wrong too despite the bad message.  I read something else volumes <10GB also gives no space error but is not my problem too.

[kubernetes@kma201 heketi]$ heketi-client/bin/heketi-cli topology info
Cluster Id: 202e47ee6fb16766b52818cfa2c219f7
    Volumes:
    Nodes:
        Node Id: 0bc9122d8c0d0658094b3915f9ad9781
        State: online
        Cluster Id: 202e47ee6fb16766b52818cfa2c219f7
        Zone: 1
        Management Hostname: trtknd203.trt7.local
        Storage Hostname: 10.7.123.243
        Devices:
                Id:7d93ee7e8049f7e0c4c3c3d316560f34   Name:/dev/sdb            State:online    Size (GiB):49      Used (GiB):0       Free (GiB):49
                        Bricks:

        Node Id: 6753e4d6ea8b50a7a38ce19b0da15c12
        State: online
        Cluster Id: 202e47ee6fb16766b52818cfa2c219f7
        Zone: 1
        Management Hostname: trtknd201.trt7.local
        Storage Hostname: 10.7.123.241
        Devices:
                Id:8f3ac3d723918803720c28ce3f6f0035   Name:/dev/sdb            State:online    Size (GiB):49      Used (GiB):0       Free (GiB):49
                        Bricks:

        Node Id: b9aea5b5abec423148b367a120cdedd8
        State: online
        Cluster Id: 202e47ee6fb16766b52818cfa2c219f7
        Zone: 1
        Management Hostname: trtknd202.trt7.local
        Storage Hostname: 10.7.123.242
        Devices:
                Id:566ec0db7dc34b8ede41a2ea2c7e85e5   Name:/dev/sdb            State:online    Size (GiB):49      Used (GiB):0       Free (GiB):49
                        Bricks:
[kubernetes@kma201 heketi]$ heketi-client/bin/heketi-cli setup-openshift-heketi-storage
Error: Failed to allocate new volume: No space
[kubernetes@kma201 heketi]$

**Comment by phlogistonjohn** [comment]
Hi @grantcurell , could you retest your scenario with the recently release Heketi v8.0.0 to check if has improved thing for your case? I know we made many changes in that area recently. Thanks.

**Comment by grantcurell** [comment]
hahaha man I had totally forgot about this. I remember that day(s). I appreciate your hitting this back up! Tbh though we ended up using Ceph because it worked immediately with Kubernetes. It has been too long for me to remember the exact error, but I remember we had trouble with the PVCs dropping out of the pods with Gluster. Feel free to close the ticket.

**Comment by phlogistonjohn** [comment]
Thank you for the update. Hope you give gluster a try again some time. Closing issue.
