### ISSUE TITLE
Documentation: Describe volumeType parameter on a Storage Class

### ISSUE THREAD

**Issue by mrwulf** [heketi/heketi#1020]
These are the ones I know about for sure:

- `none` -- No replication of created volumes (still distributed)
- `replicate:2` -- Make 2 replicas instead of the default 3

**Comment by obnoxxx** [comment]
Hi @mrwulf , thanks for filing an issue!

This is the heketi repository. There is no direct relationship to a storage class here. StorageClass is a kubernetes concept. And yes, "replicate:3" etc is a kubernetes specific thing. It is documented here:

https://github.com/kubernetes/examples/blob/master/staging/persistent-volume-provisioning/README.md

Example storage class file:

https://github.com/kubernetes/kubernetes/blob/master/examples/persistent-volume-provisioning/glusterfs/glusterfs-storageclass.yaml

For heketi proper, the api documentation is here:

https://github.com/heketi/heketi/blob/master/doc/api/api.md

also see end-to-end integration in the gluster-kubernetes project: https://github.com/gluster/gluster-kubernetes

**Comment by obnoxxx** [comment]
@mrwulf I hope I have given you enough pointers. I will close this issue. Please reopen if I have misunderstood your request!
