### ISSUE TITLE
HeketiStorageVolumeName hardcoded

### ISSUE THREAD

**Issue by kborup-redhat** [heketi/heketi#1033]
Hey, in the dbvolume.go the name HeketiStorageVolumeName is hardcoded to "heketidbstorage". this causes a problem when you have multiple Openshift Clusters that has to use the same CRS storage. 

Would it be possible to make the volumename as a parameter to the setup, so it would pass trough the cns-installer as well (just for crs) making it  possible to use the same large gluster setup for two or more openshift clusters, all using dynamic provisioning.

**Comment by raghavendra-talur** [comment]
@kborup-redhat I like the idea of not hardcoding the HeketiStorageVolumeName but I don't think that is sufficient to solve your problem. Using two instances of Heketi for the same Gluster setup is not possible.  How would you solve that problem?

**Comment by kborup-redhat** [comment]
generally the names for the volumes could be changed with having a set algorithme per cluster, ie you could say on cluster one volumes should start with 00001 and on cluster 2 00002 as you are using different disks on the gluster servers, the actual storage consumption will be per heketi pod. as heketi does not form the cluster it should be possible, and by having the volume algorithme it would not overlap between two clusters. 

Furthermore this would also help with different storage levels / types as you would be able to run more than one heketi service per cluster for ie bronze / silver / gold type level of storage.

**Comment by phlogistonjohn** [comment]
@kborup-redhat  is this something you still want? If so, could you elaborate more on the use cases you are trying to solve with this behavior?

**Comment by phlogistonjohn** [comment]
Stale issue. Closing.
