### ISSUE TITLE
Provide metrics for consumption by Prometheus

### ISSUE THREAD

**Issue by allen13** [heketi/heketi#1035]
I am currently using this project in my Openshift cluster to monitor CNS/Heketi: https://github.com/CSCfi/heketi-metrics-exporter

While it works great, it would be best to directly integrate it into the heketi server. Since Openshift is moving from hawkular to prometheus soon I assume it will eventually happen.

Is this something on the roadmap? Would a pull request be accepted?

Thanks!

**Comment by phlogistonjohn** [comment]
Hi, that looks pretty cool. I personally don't have experience with Prometheus other than hearing it's name bandied about but I certainly think its worth consideration.

I gave the repo you linked to a look over and it looks interesting. I'm sure a PR would be seriously considered and discussed if one were filed.

**Comment by phlogistonjohn** [comment]
Feature was merged to heketi. New metrics or other changes to the metrics endpoint should be done as individual new issues/prs.
