### ISSUE TITLE
Heketi replication

### ISSUE THREAD

**Issue by osopolare** [heketi/heketi#1040]
Has anyone thought through how to replicate a heketi-managed gluster-backed kubernetes environment from one site to another?

Example:

Site A is active.  Site B is passive.

As volumes are created on Site A is there any way to have the same operations happen on Site B?

Using Glusterfs we can sync data from a Volume 1A to Volume 1B on the other site.  It would be nice if heketi could configure sync as well.

**Comment by phlogistonjohn** [comment]
We have no plans to support gluster geo-replication in Heketi. You can set up geo-rep on volumes that were created by heketi but that is a manual process outside of heketi itself.

Hopefully my answer was satisfactory. I'm closing this issue now. If you feel the issue needs additional discussion please feel free to reopen.
