### ISSUE TITLE
Heketi: Failed to allocate new volume with heketi-cli v5.0.1

### ISSUE THREAD

**Issue by robertoalcantara** [heketi/heketi#1046]
Following https://github.com/heketi/heketi/blob/master/doc/admin/install-kubernetes.md I'm stuck on  setup-openshift-heketi-storage.

I receive "No space" message but do not make sense to me. I found previous issue about old version of cli but i'm on newest.

```
[kubernetes@labkma201 heketi]$ heketi-client/bin/heketi-cli --version
heketi-cli v5.0.1

[kubernetes@labkma201 heketi]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.4+2.0.1.el7", GitCommit:"538ac53c74231a70b7ceca01b8f8d09a735b4ffb", GitTreeState:"\"git", BuildDate:"2017-12-14T22:28:43Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.4+2.0.1.el7", GitCommit:"538ac53c74231a70b7ceca01b8f8d09a735b4ffb", GitTreeState:"\"git", BuildDate:"2017-12-14T22:28:43Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

[kubernetes@labkma201 heketi]$ heketi-client/bin/heketi-cli setup-openshift-heketi-storage
Error: Failed to allocate new volume: No space

[kubernetes@labkma201 heketi]$ heketi-client/bin/heketi-cli topology info

Cluster Id: b41717dc7db01d7659032c59c927674a

    Volumes:

    Nodes:

        Node Id: 2dba3a0739ab43656365237e03be3faf
        State: online
        Cluster Id: b41717dc7db01d7659032c59c927674a
        Zone: 1
        Management Hostname: labknd202.lab7.local
        Storage Hostname: 10.7.123.242
        Devices:
                Id:382fc7c17f6de8b33c0a330ba7581d38   Name:/dev/sdb            State:online    Size (GiB):49      Used (GiB):0       Free (GiB):49
                        Bricks:
                Id:f7d05a4f3f3bc2ac2e56609dc061b7a0   Name:/dev/sdc            State:online    Size (GiB):49      Used (GiB):0       Free (GiB):49
                        Bricks:

        Node Id: 851aae28349da3ecade1119eba703ed7
        State: online
        Cluster Id: b41717dc7db01d7659032c59c927674a
        Zone: 2
        Management Hostname: labknd203.lab7.local
        Storage Hostname: 10.7.123.243
        Devices:
                Id:22c47596300999f551ddb5f3d55a182e   Name:/dev/sdc            State:online    Size (GiB):49      Used (GiB):0       Free (GiB):49
                        Bricks:
                Id:b5e095fe0ec3d911938b0afb813cca87   Name:/dev/sdb            State:online    Size (GiB):49      Used (GiB):0       Free (GiB):49
                        Bricks:

        Node Id: b9974b7448fe199ddc9d5ebb6b3e4359
        State: online
        Cluster Id: b41717dc7db01d7659032c59c927674a
        Zone: 1
        Management Hostname: labknd201.lab7.local
        Storage Hostname: 10.7.123.241
        Devices:
                Id:1ec5ec7062c243746f0c1db94ff11978   Name:/dev/sdc            State:online    Size (GiB):49      Used (GiB):0       Free (GiB):49
                        Bricks:
                Id:e71481414589f8cfe013516026a5b204   Name:/dev/sdb            State:online    Size (GiB):49      Used (GiB):0       Free (GiB):49
                        Bricks:


[kubernetes@labkma201 heketi]$ cat topology-lab.json
{
  "clusters": [
    {
      "nodes": [
        {
          "node": {
            "hostnames": {
              "manage": [
                "labknd201.lab7.local"
              ],
              "storage": [
                "10.7.123.241"
              ]
            },
            "zone": 1
          },
          "devices": [
            "/dev/sdb",
            "/dev/sdc"
          ]
        },
        {
          "node": {
            "hostnames": {
              "manage": [
                "labknd202.lab7.local"
              ],
              "storage": [
                "10.7.123.242"
              ]
            },
            "zone": 1
          },
          "devices": [
            "/dev/sdb",
            "/dev/sdc"
          ]
        },
        {
          "node": {
            "hostnames": {
              "manage": [
                "labknd203.lab7.local"
              ],
              "storage": [
                "10.7.123.243"
              ]
            },
            "zone": 2
          },
          "devices": [
            "/dev/sdb",
            "/dev/sdc"
          ]
        }
      ]
    }
  ]
}
```

Each block device /dev/sdb and /dev/sdc have 50GB. I tried to put all tree nodes on same zone but no difference. I tried "pitfall" procedure on doc but same result.

Someone has a tip to give me ? :-)

**Comment by robertoalcantara** [comment]
Client version 6 release today by @obnoxxx solve this problem.

**Comment by naimabdrahman** [comment]
@robertoalcantara , it's great then but im using version 6 yet still not resolving the error. Could you care to share the steps or action u did to solve it other than upgrade to version 6 ?

**Comment by jgnoonan** [comment]
I am using version 7 and I still have the issue.  I added a new raw drive to add additional space and added it to the topology.  It shows being online but I am still getting these errors.  I used the setflags command and that did not change anything.  Any help would be appreciated.

**Comment by phlogistonjohn** [comment]
Can you please provide the heketi logs generated when you run the volume create? (If long please use a gist/pastebin)

Also providing your updated topology may help. Also, in the future please file a new issue if you see that the issue at hand is closed and you're not 100% its the same.

**Comment by xiaomage008** [comment]
i am using version 7.0.0. When create volume. issue "Minimum brick size limit reached.  Out of space."
occurs.  My topology info is below:
{
    "clusters": [
        {
            "nodes": [
                {
                    "node": {
                        "hostnames": {
                            "manage": [
                                "10.120.187.155"
                            ],
                            "storage": [
                                "10.120.187.155"
                            ]
                        },
                        "zone": 1
                    },
                    "devices": [
                        {
                            "name": "/dev/xvdc",
                            "destroydata": false
                        }
                    ]
                }
            ]
        }
    ]
}
I have only one node. Should 3 nodes needed for heketi at least?

**Comment by nixpanic** [comment]
It would have been better to [open a new issue](https://github.com/heketi/heketi/issues/new), this one is closed.

You can create volumes with `heketi-cli volume create --durability=none --size=...` if you do not have the number of nodes to use replication. Three nodes is the minimal that is recommended for production deployments. In almost all cases you will want your data replicated.
