### ISSUE TITLE
Discover the already created cluster, nodes and their volumes

### ISSUE THREAD

**Issue by MrCirca** [heketi/heketi#1059]
Hello,
Is there a way, heketi discovers clusters nodes and their volumes that have been created manually?

**Comment by phlogistonjohn** [comment]
Unfortunately, no. There is no current way to import an existing cluster's volumes into Heketi. The initial topology is expected to take empty block devices and create new bricks and volumes on top of those.

**Comment by MrCirca** [comment]
Ok thank you!
