### ISSUE TITLE
Add exclusive access to objects

### ISSUE THREAD

**Issue by lpabon** [heketi/heketi#106]
Need to make sure that if someone is expanding a volume, another cannot be deleting it, and so on.

**Comment by lpabon** [comment]
This will require the objects to have state and save that state in the db.

**Comment by obnoxxx** [comment]
@phlogistonjohn hasn't this been fixed meanwhile?

**Comment by phlogistonjohn** [comment]
Barring any unknown bugs I think this logic is in place, yes. We can probably close this issue.

**Comment by phlogistonjohn** [comment]
Anyone who objects, please feel free to reopen this issue and discuss.
