### ISSUE TITLE
Promote latest docker tag to v6 release

### ISSUE THREAD

**Issue by DanyC97** [heketi/heketi#1065]
Now that version 6.0.0 is out will be nice to promote the `latest` docker tag to it.

**Comment by DanyC97** [comment]
@raghavendra-talur any thoughts ?

**Comment by obnoxxx** [comment]
@DanyC97 thanks for reaching out.
I just updated the latest tag to point to version 6 on https://hub.docker.com/r/heketi/heketi/ after the next build has completed it should work. Please reopen if problems persist.
