### ISSUE TITLE
Is it possible to update heketi topology?

### ISSUE THREAD

**Issue by XericZephyr** [heketi/heketi#1066]
For `heketi-cli`, is it possible to update the topology by using `heketi-cli topology load` on an updated topology configuration?

**Comment by XericZephyr** [comment]
More specifically, one of my storage nodes was getting new IP after an accidental reboot. I need to update the IP address for this node.

**Comment by davidedal** [comment]
just rerun the `heketi-cli topology load` and everything should be fine (at least always worked for me).

**Comment by raghavendra-talur** [comment]
If the IP has changed I am afraid it won't be sufficient if you just update heketi topology. Gluster requires that IP of machine remains constant. You will also have to follow procedure to update gluster info files. I will get back to you with more details in a day.

**Comment by XericZephyr** [comment]
Hi, @raghavendra-talur, can you give some pointers on the glusterfs instruction of changing IP?

**Comment by XericZephyr** [comment]
Hi, @davidedal , I found it does not work for me since it says `Found node xxx on cluster xxxx` and it just fails.

**Comment by XericZephyr** [comment]
It seems not possible to delete a failure node when there were bricks on it as well.

**Comment by Duchongming** [comment]
+1

**Comment by phlogistonjohn** [comment]
> For `heketi-cli`, is it possible to update the topology by using `heketi-cli topology load` on an updated topology configuration?

At one point in the project's history I think the intent was to be able to update topology via reloading it. However the topology json structure was not designed in such a way that makes it a 'safe' operation. Thus we do not recommend ever trying to change the topology via topology load. Rather, use the individual commands such as 'device add' or 'node add'.
