### ISSUE TITLE
Server will not start as long as pending operations are present in the db.

### ISSUE THREAD

**Issue by xinzaitiao11** [heketi/heketi#1073]
heketi  boot failure。
The log is as follows：
Heketi v5.0.0-475-gc7e9aae
[heketi] INFO 2018/03/01 02:48:40 Loaded kubernetes executor
[heketi] INFO 2018/03/01 02:48:41 Please refer to the Heketi troubleshooting documentation for more information on how to resolve this issue.
[heketi] ERROR 2018/03/01 02:48:41 /src/github.com/heketi/heketi/apps/glusterfs/app.go:150: Heketi terminated while performing one or more operations. Server will not start as long as pending operations are present in the db.
How do I recover the heketi?

**Comment by wernergillmer** [comment]
have this problem as well

**Comment by xiaomage008** [comment]
Same issue occurred while start Heketi.

**Comment by phlogistonjohn** [comment]
https://github.com/heketi/heketi/blob/master/docs/troubleshooting.md#heketi-refuses-to-start-and-the-log-lines-contain-the-string

The behavior described is documented in the above link along with supported workarounds. Hopefully this is satisfactory.

Additionally, we have plans to make recovery of stale pending operations automatic.

**Comment by phlogistonjohn** [comment]
This is no longer the case with recent heketi releases.
