### ISSUE TITLE
Add more, newer, versions of Go to travis test runs

### ISSUE THREAD

**Issue by phlogistonjohn** [heketi/heketi#1083]
Currently our travis tests are run with Go versions 1.7.5 and 1.8.2. As of this writing Go 1.10 is the newest released version.

According to the [Go release policy](https://golang.org/doc/devel/release.html#policy) none of the versions we're using are supported versions any more. I'm personally perfectly happy testing with older versions but it seems that we should at least add to the versions that we are testing with.

**Comment by phlogistonjohn** [comment]
@Madhu-1
Since you've been testing Heketi with Go 1.10 I thought I would ping you on this issue in case it was something you'd like to attempt.

**Comment by Atul9** [comment]
I would like to take this up.
