### ISSUE TITLE
How to set up a heketi cluster

### ISSUE THREAD

**Issue by sripatib** [heketi/heketi#1112]
### Kind of issue
> Feature request

##In detail##
Hi Team, I am trying to run two heketi nodes in cluster. Is there any such feature or is this possible to keep heketi.db to keep in sync in two different nodes

**Comment by max8899** [comment]
Have the same question.

**Comment by phlogistonjohn** [comment]
AFAIK, the system is not designed to support multiple servers accessing the same db. If you absolutely need to run multiple Heketi instances you need to have them manage separate gluster instances.

If you are using Kubernetes or OpenShift Heketi supports storing its db in a special gluster volume. This way a new Heketi instance can be brought up on a different node quickly with the existing data. This is still not an active-active setup however.

**Comment by phlogistonjohn** [comment]
Hopefully my answer was satisfactory. I'm closing this issue now. If you feel the issue needs additional discussion please feel free to reopen.
