### ISSUE TITLE
roll back of volume expansion is incomplete

### ISSUE THREAD

**Issue by raghavendra-talur** [heketi/heketi#1116]
### Kind of issue

Bug

### Observed behavior
When a executor operation fails for volume expansion, rollback is not performed for add-brick commands and only the bricks are cleaned up.

### Expected/desired behavior
A proper roll back of add-brick has to be performed to bring the state of volume on gluster to what it was before add-brick and then the newly created bricks should be cleaned up.

### Details on how to reproduce (minimal and precise)
Create a volume using heketi. Kill one of the bricks belonging to the volume on a node. Perform volume expansion and check the volume info on heketi and gluster. Both don't match. Gluster shows all bricks(including the newly added ones) while heketi shows only old bricks.

### Information about the environment:
- Heketi version used :  v6.0.0

**Comment by phlogistonjohn** [comment]
@raghavendra-talur given the discussion in PR #1118 and changes to heketi since do you think this is still an issue we need to resolve?

**Comment by phlogistonjohn** [comment]
I'm pretty sure this is resolved by now. Reopen if not please.
