### ISSUE TITLE
How to force delete a dead gluster node from the cluster?

### ISSUE THREAD

**Issue by mjschmidt** [heketi/heketi#1120]
Hi Heketi Crew,

I have gotten GlusterFS running in containers using Heketi and Kubernetes! Wo Right? I have a heketi question though. From inside the heketi container I should be able to run heketi-cli commands on gluster containers. I know that the networking is working because I can make pvcs and heketi cleans them up after I am done with them. The problem comes when I lose a gluster node...

Kubernetes doesn't want to clean up pvcs until all nodes in the gluster cluster are online, so far I have had success bringing back nodes that have gluster containers on them. But what if a node blows up, I would keep accumulating useless persistent volumes (or at least be unable to clean up persistent volumes that I had before, which means I am wasting space).

To avoid this, lets say gluster container 2 blows up. Like the whole node, boom drenched in fire and sadness. Is there a command or set of commands I can run to force delete a gluster node from the gluster cluster so that everything can go back to normal, and I can clean up my persistent volumes that I no longer need.

I look forward to seeing what the answer is. The answer has evaded me for almost 2 weeks now.

**Comment by phlogistonjohn** [comment]
> From inside the heketi container I should be able to run heketi-cli commands on gluster containers. 

Unfortunately, I don't know what you mean by this.

If I understand the rest of your question correctly, I think you just want to remove the node with the heketi-cli. To do this you need to remove the devices on node first, which goes something like:

```sh
# disable the node and its devices
heketi-cli node offline $NODEID
# remove node and devices from use
heketi-cli node remove $NODEID
# delete devices
heketi-cli device delete $DEVID # per-device on the node
# delete node
heketi-cli node delete $NODEID
```

Note that 'device remove' & 'node remove' attempts to relocate any bricks on that device to other devices in the system. So if you have multiple dead nodes, mark them all offline first before trying to remove devices. Once all the bricks are removed from the device you can delete the devices. Once all the devices on the node are gone you can delete the node. I don't know of an automatic way to delete all the devices on the node. Perhaps if someone else on the team knows they can chime in.

One downside to this is if you really don't care about the volumes you're still required to relocate the bricks somewhere else (a new node). If you don't have enough working nodes & space for the new bricks you are currently stuck. AFAIK, there is no way to say "I don't care about these volumes, trash them anyway."

**Comment by mjschmidt** [comment]
So don't worry about the first part the part you provided an answer for is what I care about. All I was saying is that I can kube exec -it into the container to get an instance inside the heketi container to run the heketi cli commands from inside there.

I think I may have ended up stuck because I ran out of space for all of the bricks. Will double check in a bit and get back to this post.

**Comment by mjschmidt** [comment]
How can I see how much space is left in my gluster cluster?

I am having the issue where I set up a gluster cluster in kubernetes, but for some reason one of my pvcs is not binding, and I am getting no logs from kubernetes when I describe the pvc.

What are some troubleshooting steps I can take from the heketi cli?

**Comment by mjschmidt** [comment]
Update: Definitely looks like Heketi is falling asleep or something... it seems to shut down after a while and not come back. Then I delete the heketi pod in kubernetes, it comes back and everything works again for a while. Seems like a bug?

**Comment by phlogistonjohn** [comment]
That sounds wrong. That also sounds like a new issue :-)
Could you please open a new issue with details like what version of hekeit, kubernetes and any relevant logging? Thanks.

**Comment by mjschmidt** [comment]
Going back to this, if a node is down (lets say it blew up) there is no way to relocate the bricks?

Am I missing something here. If a node goes down is there a way to recover the rest of the storage system. The reason I ask is I am currently encountering an error where a node is down and so heketi doesn't want to create new storage since not all of the gluster peers are connected, but I also can't remove the node gracefully and have the bricks "move" since it can't access the node.

**Comment by obnoxxx** [comment]
is this supposed to be open (re-opened)?

I'm a little unsure what's going on.

* Certainly, heketi stopping to work after a while is wrong.
* a node going down - i assume you mean a gluster node going down: you currently need at least 3 nodes up in order to create a replica-3 volume. (Also you need to have all nodes with bricks for a volume up in order to remove that volume.) You should (tm) be able to force the removal of a node that you know won't come back up.

**Comment by zhaolupingnick** [comment]
You can force the deletion of a node with the following command：
    `$ heketi-cli device disable $deviceID `
    `$ heketi-cli volume delete $volumeID`
    `$ heketi-cli device remove $deviceID`
    `$ heketi-cli device delete $deviceID`

**Comment by zhaolupingnick** [comment]
or run this command:
    `$ heketi-cli device delete $deviceID --force-forget`
And you should know it's dangerous!!!
