### ISSUE TITLE
how can i find out which released volume to delete ?

### ISSUE THREAD

**Issue by 13567436138** [heketi/heketi#1126]
kubectl get pv --all-namespaces -o wide
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS     CLAIM                                     STORAGECLASS        REASON    AGE
pvc-11f4fc5e-3233-11e8-a867-001e9098365d   9G         RWX            Retain           Bound      default/pvc-mariadb                       glusterfs-storage             7d
pvc-30be2eb1-3251-11e8-bd3f-002197403677   6G         RWO            Retain           Bound      default/fabric8-docker-registry-storage   glusterfs-storage             6d
pvc-30c6a915-3251-11e8-bd3f-002197403677   3G         RWO            Retain           Bound      default/gogs-data                         glusterfs-storage             6d
pvc-30caf809-3251-11e8-bd3f-002197403677   2G         RWO            Retain           Bound      default/jenkins-jobs                      glusterfs-storage             6d
pvc-30d142b0-3251-11e8-bd3f-002197403677   2G         RWX            Retain           Bound      default/jenkins-mvn-local-repo            glusterfs-storage             6d
pvc-30d72841-3251-11e8-bd3f-002197403677   2G         RWO            Retain           Bound      default/jenkins-workspace                 glusterfs-storage             6d
pvc-30df21cb-3251-11e8-bd3f-002197403677   6G         RWO            Retain           Bound      default/nexus-storage                     glusterfs-storage             6d
pvc-458487a8-3168-11e8-b752-001e9098365d   9G         RWO            Retain           Released   default/jazzy-squirrel-mariadb            glusterfs-storage             8d
pvc-48f28ed9-33d3-11e8-89a1-002197403677   3G         RWX            Retain           Bound      default/gogs-data-v2                      glusterfs-storage             5d
pvc-646ce3c9-3230-11e8-a867-001e9098365d   9G         RWX            Retain           Released   default/pvc-mariadb                       glusterfs-storage             7d
pvc-82c929cf-3168-11e8-b752-001e9098365d   9G         RWO            Retain           Released   default/jazzy-squirrel-redmine            glusterfs-storage             8d
pvc-b6fc6a37-316c-11e8-b752-001e9098365d   9G         RWX            Retain           Released   default/jazzy-squirrel-redmine            glusterfs-storage             8d
pvc-c053371d-317c-11e8-b752-001e9098365d   9G         RWX            Retain           Released   default/pvc-mariadb                       glusterfs-storage             8d

sh-4.4# heketi-cli volume list
Id:3742e9bb6c78522b31594a05751b3543    Cluster:35a6377a7f37d66b29a035b546801e4a    Name:vol_3742e9bb6c78522b31594a05751b3543
Id:3f44b510dd5486e1b4904d949573689b    Cluster:35a6377a7f37d66b29a035b546801e4a    Name:vol_3f44b510dd5486e1b4904d949573689b
Id:4523e16d7564e1cd2462174cda929e28    Cluster:35a6377a7f37d66b29a035b546801e4a    Name:heketidbstorage
Id:4bd8306c3cc24666b471bff5353ebe26    Cluster:35a6377a7f37d66b29a035b546801e4a    Name:vol_4bd8306c3cc24666b471bff5353ebe26
Id:559da1aca1287289097febf67a2c7834    Cluster:35a6377a7f37d66b29a035b546801e4a    Name:vol_559da1aca1287289097febf67a2c7834
Id:5ce4ede82fcc0d1b8a046e03509622a7    Cluster:35a6377a7f37d66b29a035b546801e4a    Name:vol_5ce4ede82fcc0d1b8a046e03509622a7
Id:5f24606be2ea4ce0783c1ed0d1ff0564    Cluster:35a6377a7f37d66b29a035b546801e4a    Name:vol_5f24606be2ea4ce0783c1ed0d1ff0564
Id:678e9bf84ab9c66f80740b900011dfa0    Cluster:35a6377a7f37d66b29a035b546801e4a    Name:vol_678e9bf84ab9c66f80740b900011dfa0
Id:71acafe77742b71e56ea727ecc035d44    Cluster:35a6377a7f37d66b29a035b546801e4a    Name:vol_71acafe77742b71e56ea727ecc035d44
Id:73694ab046bb5e85fc278f57d832b718    Cluster:35a6377a7f37d66b29a035b546801e4a    Name:vol_73694ab046bb5e85fc278f57d832b718
Id:a04002017eb322147b825c9c49b0946c    Cluster:35a6377a7f37d66b29a035b546801e4a    Name:vol_a04002017eb322147b825c9c49b0946c
Id:a77581b03e1fe12ed95f16d96d984533    Cluster:35a6377a7f37d66b29a035b546801e4a    Name:vol_a77581b03e1fe12ed95f16d96d984533
Id:b833bea857f97131c1eae1c5730e91e5    Cluster:35a6377a7f37d66b29a035b546801e4a    Name:vol_b833bea857f97131c1eae1c5730e91e5
Id:e1fca2410e3994f7a65b689bbe1cf3bf    Cluster:35a6377a7f37d66b29a035b546801e4a    Name:vol_e1fca2410e3994f7a65b689bbe1cf3bf
Id:f27bad8ae664afbe6732dfa32fdd2f86    Cluster:35a6377a7f37d66b29a035b546801e4a    Name:vol_f27bad8ae664afbe6732dfa32fdd2f86

how can i match the two command line's output?

**Comment by phlogistonjohn** [comment]
Unfortunately, you can't get the info you want from just those two commands. However, you get what you need by looking at additional metadata on the PVCs. For example you can run `kubectl get pv -o yaml` and examine the output.

Based on the values in the YAML I cooked up the following quick and dirty kubectl command:
```bash

$ kubectl get pv -o 'go-template={{range .items}}name={{.metadata.name}} claimName={{.spec.claimRef.name}} heketiName={{.spec.glusterfs.path}} heketiId={{index .metadata.annotations "gluster.kubernetes.io/heketi-volume-id"}}{{"\n"}}{{end}}'
name=pvc-a43ce01f-383a-11e8-be62-52540011be90 claimName=fred1 heketiName=vol_669bb906cecb640f22c15fcfc70a8b60 heketiId=669bb906cecb640f22c15fcfc70a8b60
name=pvc-b026f65a-383a-11e8-be62-52540011be90 claimName=flubber1 heketiName=vol_baeb9b2644a0f04ad46eb34e58a61615 heketiId=baeb9b2644a0f04ad46eb34e58a61615

```

Be aware that some of the spec and annotation names may vary depeding on what provisioner you are using to access Heketi. So you may need to tweak the command to get exactly what is most useful and convenient for your use case.

I hope this was helpful.

**Comment by 13567436138** [comment]
thanks
