### ISSUE TITLE
how to delete pvc that generated by volumeClaimTemplates

### ISSUE THREAD

**Issue by 13567436138** [heketi/heketi#1135]
[root@node2 ~]# kubectl get pv 
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS    CLAIM                                     STORAGECLASS           REASON    AGE
pvc-11f4fc5e-3233-11e8-a867-001e9098365d   9G         RWX            Retain           Bound     default/pvc-mariadb                       glusterfs-storage                11d
pvc-30be2eb1-3251-11e8-bd3f-002197403677   6G         RWO            Retain           Bound     default/fabric8-docker-registry-storage   glusterfs-storage                10d
pvc-30c6a915-3251-11e8-bd3f-002197403677   3G         RWO            Retain           Bound     default/gogs-data                         glusterfs-storage                10d
pvc-30caf809-3251-11e8-bd3f-002197403677   2G         RWO            Retain           Bound     default/jenkins-jobs                      glusterfs-storage                10d
pvc-30d142b0-3251-11e8-bd3f-002197403677   2G         RWX            Retain           Bound     default/jenkins-mvn-local-repo            glusterfs-storage                10d
pvc-30d72841-3251-11e8-bd3f-002197403677   2G         RWO            Retain           Bound     default/jenkins-workspace                 glusterfs-storage                10d
pvc-30df21cb-3251-11e8-bd3f-002197403677   6G         RWO            Retain           Bound     default/nexus-storage                     glusterfs-storage                10d
pvc-4279ba9f-3ad0-11e8-8dec-001e9098365d   54G        RWX            Retain           Bound     mysql-operator/data-alpaca-0              glusterfs-storage-dv             2h
pvc-48f28ed9-33d3-11e8-89a1-002197403677   3G         RWX            Retain           Bound     default/gogs-data-v2                      glusterfs-storage                8d

here mysql-operator/data-alpaca-0 is generated by volumeClaimTemplates like
volumeClaimTemplates:
  metadata:
      name: mysql
    spec:
      accessModes: [ "ReadWriteMany" ]
      storageClassName: glusterfs-storage-dv
      resources:
        requests:
          storage: 2Gi

but i cannot find it in pvc
[root@node2 ~]# kubectl get pvc
NAME                              STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS        AGE
fabric8-docker-registry-storage   Bound     pvc-30be2eb1-3251-11e8-bd3f-002197403677   6G         RWO            glusterfs-storage   10d
gogs-data                         Bound     pvc-30c6a915-3251-11e8-bd3f-002197403677   3G         RWO            glusterfs-storage   10d
gogs-data-v2                      Bound     pvc-48f28ed9-33d3-11e8-89a1-002197403677   3G         RWX            glusterfs-storage   8d
jenkins-jobs                      Bound     pvc-30caf809-3251-11e8-bd3f-002197403677   2G         RWO            glusterfs-storage   10d
jenkins-mvn-local-repo            Bound     pvc-30d142b0-3251-11e8-bd3f-002197403677   2G         RWX            glusterfs-storage   10d
jenkins-workspace                 Bound     pvc-30d72841-3251-11e8-bd3f-002197403677   2G         RWO            glusterfs-storage   10d
nexus-storage                     Bound     pvc-30df21cb-3251-11e8-bd3f-002197403677   6G         RWO            glusterfs-storage   10d
pvc-mariadb                       Bound     pvc-11f4fc5e-3233-11e8-a867-001e9098365d   9G         RWX            glusterfs-storage   11d

**Comment by obnoxxx** [comment]
What's up with this? Was it created by accident?
