### ISSUE TITLE
 pods

### ISSUE THREAD

**Issue by mighani** [heketi/heketi#1139]
### Kind of issue

> Uncomment only one of these:
> 
> Bug
> Feature request

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): 
- Operating system used: 
- Heketi compiled from sources, as a package (rpm/deb), or container: 
- If container, which container image: 
- Using kubernetes, openshift, or direct install: 
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: 
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom):

**Comment by phlogistonjohn** [comment]
Hi. It looks like you may have filed this issue accidentally, as the only content here is the issue template. Just to avoid this issue lingering in our open issues list I'm going to close this item. However, if you have an issue to report please feel free to open it back up, but please fill in the template with the details of your problem (or file a new issue with details). Thanks.

**Comment by mighani** [comment]
sorry, john. Yes, this was by mistake.
