### ISSUE TITLE
PVC not bound

### ISSUE THREAD

**Issue by hubv** [heketi/heketi#1145]
### Kind of issue

> Uncomment only one of these:
> 
Bug
> Feature request

### Observed behavior
demo-demorabbit-crmq-0 Pending 0 4 minutes - -
PersistentVolumeClaim is not bound: "rabbitmq-demo-demorabbit-crmq-0" (repeated 14 times)

Warning ProvisioningFailed 2m (x62 over 18m) persistentvolume-controller Failed to provision volume with StorageClass "glusterfs-storageclass": create volume error: error creating volume Error calling v.allocBricksInCluster: database is in read-only mode
lots of logs in heketi pod:

[negroni] Started GET /queue/8d0e802c7c681561ab3f67bd834f20ae
[negroni] Completed 200 OK in 126.41Âľs
[sshexec] DEBUG 2018/03/16 09:49:29 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:176: Host: sprintbox-control-storage-03:22 Command: sudo /bin/bash -c 'sed -i.save "/brick_59cfa0e485226df23a59b73d33c92aa9/d" /etc/fstab'
Result:
[sshexec] DEBUG 2018/03/16 09:49:29 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:176: Host: sprintbox-control-storage-01:22 Command: sudo /bin/bash -c 'lvremove -f vg_925bcbfda48272d25f4c5acdbbd8c200/tp_c81b8db35c7684e0cca3b48b2f09ec3e'
Result: Logical volume "brick_c81b8db35c7684e0cca3b48b2f09ec3e" successfully removed
Logical volume "tp_c81b8db35c7684e0cca3b48b2f09ec3e" successfully removed
[negroni] Started GET /queue/77bd6f31ac07a24225d7fab4ef4853f5
[negroni] Completed 200 OK in 91.153Âľs
[sshexec] DEBUG 2018/03/16 09:49:29 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:176: Host: sprintbox-control-storage-03:22 Command: sudo /bin/bash -c 'sed -i.save "/brick_d2bc192f9f4db4634bbe8fd7ed4f24ae/d" /etc/fstab'
Result:
[sshexec] DEBUG 2018/03/16 09:49:29 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:176: Host: sprintbox-control-storage-01:22 Command: sudo /bin/bash -c 'rmdir /var/lib/heketi/mounts/vg_925bcbfda48272d25f4c5acdbbd8c200/brick_fff518f4ebdbcd2ddcd24ab2a841f6c0'
Result:
[negroni] Started GET /queue/62f1bcb4b05bece4fd83ddc014c9dcd4
[negroni] Completed 200 OK in 123.552Âľs
[sshexec] DEBUG 2018/03/16 09:49:29 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:176: Host: sprintbox-control-storage-01:22 Command: sudo /bin/bash -c 'rmdir /var/lib/heketi/mounts/vg_925bcbfda48272d25f4c5acdbbd8c200/brick_f926eb1505a81b23fba3e75db8144250'
Result:
[sshexec] DEBUG 2018/03/16 09:49:30 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:176: Host: sprintbox-control-storage-01:22 Command: sudo /bin/bash -c 'rmdir /var/lib/heketi/mounts/vg_925bcbfda48272d25f4c5acdbbd8c200/brick_c81b8db35c7684e0cca3b48b2f09ec3e'
Result:
[negroni] Started GET /queue/8d0e802c7c681561ab3f67bd834f20ae
[negroni] Completed 200 OK in 104.833Âľs
[sshexec] DEBUG 2018/03/16 09:49:30 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:176: Host: sprintbox-control-storage-01:22 Command: sudo /bin/bash -c 'sed -i.save "/brick_fff518f4ebdbcd2ddcd24ab2a841f6c0/d" /etc/fstab'
Result:
[asynchttp] INFO 2018/03/16 09:49:30 asynchttp.go:129: Completed job 8d0e802c7c681561ab3f67bd834f20ae in 15.171279697s
[heketi] ERROR 2018/03/16 09:49:30 /src/github.com/heketi/heketi/apps/glusterfs/app_volume.go:266: Failed to delete volume 422fa8b1fc5656cacc53a410b6382323: database is in read-only mode
[negroni] Started GET /queue/77bd6f31ac07a24225d7fab4ef4853f5
[negroni] Completed 200 OK in 139.049Âľs
[negroni] Started GET /queue/62f1bcb4b05bece4fd83ddc014c9dcd4
[negroni] Completed 200 OK in 103.128Âľs
[sshexec] DEBUG 2018/03/16 09:49:30 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:176: Host: sprintbox-control-storage-01:22 Command: sudo /bin/bash -c 'sed -i.save "/brick_f926eb1505a81b23fba3e75db8144250/d" /etc/fstab'
Result:
[asynchttp] INFO 2018/03/16 09:49:30 asynchttp.go:129: Completed job 77bd6f31ac07a24225d7fab4ef4853f5 in 15.269208708s
[heketi] ERROR 2018/03/16 09:49:30 /src/github.com/heketi/heketi/apps/glusterfs/app_volume.go:266: Failed to delete volume 12981b673370ce6d4f0f457814e55c4a: database is in read-only mode
[sshexec] DEBUG 2018/03/16 09:49:30 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:176: Host: sprintbox-control-storage-01:22 Command: sudo /bin/bash -c 'sed -i.save "/brick_c81b8db35c7684e0cca3b48b2f09ec3e/d" /etc/fstab'
Result:
[asynchttp] INFO 2018/03/16 09:49:30 asynchttp.go:129: Completed job 62f1bcb4b05bece4fd83ddc014c9dcd4 in 15.334781485s
[heketi] ERROR 2018/03/16 09:49:30 /src/github.com/heketi/heketi/apps/glusterfs/app_volume.go:266: Failed to delete volume a3d64f9bd175845bfe6d3e8e0ecb6dc1: database is in read-only mode
[negroni] Started GET /queue/8d0e802c7c681561ab3f67bd834f20ae
[negroni] Completed 500 Internal Server Error in 278.825Âľs
[negroni] Started GET /queue/77bd6f31ac07a24225d7fab4ef4853f5
[negroni] Completed 500 Internal Server Error in 163.491Âľs
[negroni] Started GET /queue/62f1bcb4b05bece4fd83ddc014c9dcd4
[negroni] Completed 500 Internal Server Error in 146.087Âľs
[negroni] Started DELETE /volumes/12981b673370ce6d4f0f457814e55c4a
[negroni] Completed 202 Accepted in 669.407Âľs
[asynchttp] INFO 2018/03/16 09:49:31 asynchttp.go:125: Started job f1713bf1a39aefbe2fe22c7c9a705cd3
[heketi] INFO 2018/03/16 09:49:31 Destroying volume 12981b673370ce6d4f0f457814e55c4a
[negroni] Started DELETE /volumes/422fa8b1fc5656cacc53a410b6382323
[negroni] Completed 202 Accepted in 1.044803ms
[asynchttp] INFO 2018/03/16 09:49:31 asynchttp.go:125: Started job e90078b978aaa174de47ac264ee96468
[heketi] INFO 2018/03/16 09:49:31 Destroying volume 422fa8b1fc5656cacc53a410b6382323
[negroni] Started GET /queue/f1713bf1a39aefbe2fe22c7c9a705cd3
[negroni] Started GET /queue/e90078b978aaa174de47ac264ee96468
[negroni] Completed 200 OK in 142.823Âľs
[negroni] Completed 200 OK in 215.994Âľs

### Information about the environment:

- Heketi version used :v5.0.1 
- Operating system used: RHEL 7.4
- Heketi compiled from sources, as a package (rpm/deb), or container: container
- If container, which container image: 
- Using kubernetes, openshift, or direct install: kubernetes
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside:inside 
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom):custom

**Comment by phlogistonjohn** [comment]
Hi @hubv, looking at the logs you pasted the error seems to be that your database is read-only. This is frequently due to two few gluster bricks running such that gluster puts the volume in read only mode.

**Comment by phlogistonjohn** [comment]
Stale issue. Closing.
