### ISSUE TITLE
Definitely Heketi:6 getting itself into a bad state

### ISSUE THREAD

**Issue by mjschmidt** [heketi/heketi#1154]
I am putting this at the top, but its really the last thing you should read:
OH MY GOD I DID ALL THIS TRANSCRIBING TO FIND OUT GLUSTERFS DELETED A VOLUME AND HEKETI DIDN'T KEEP TRACK. Frustrated with myself I didn't check this before transcribing first (I did heketi-cli volume list and got that the volume was not cleaned up then did a gluster volume list and saw gluster did in fact clean it up... fuq... why did I transcribe lol forever alone) 

Okay I deployed heketi:6 to our old cluster, the new cluster I was setting up was being done with puppet and there was no way to see if it was a puppet issue or a heketi issue. I have confirmed it is a puppet issue, so lets ignore that for now and we are staying consistent by staying with the old cluster. I deployed heketi:6 successfully with "old" (its not that old) gluster and successfully created a dynamic pvc claim.

However now when I delete the pvc claim the pv is not cleaning up. I bashed into the hekti container and 
Please keep in mind I have to hand transcribe these logs, so I am getting the relevant stuff. and ignoring stuff like whole ids and times
I see the following relevant information from the logs, I deleted open brackets as they are not github friendly and I am transcribing logs:
[negroni] Started DELETE /volumes/4cdaa...
[heketi] INFO 2018/04/25 Loaded simple allocator
[negroni] Completed 202 Accepted in 23.03ms
[asynchttp] Info time and data> Start job d6444r8...
[heketi] INFO 2018/04/25 Started asymc operation: Delete Volume
[negroni] Started GET /queue/d6444r8...
[negroni] Completed 200 OK in 85.9
[kubeexec] DEBUG 2018/04/25 /src/github.com/heketi/heketi/executors/kubeexec/kubexec.go:244: Host: worker7 Pod: glusterfs-vnzql --mode=script snapshot list vol_4cdaa... --xml
Result: ?xml version="1.0" encoding="UTF-8" standalone="yes"?>
cliOutput>
  opRet>0/opRet>
  opErrno>0/opErrno>
  opErrstr/>
   snapList>
        count>0/count>
    /snapList>
/cliOutput>>
[kubeexec] DEBUG 2018/04/25 /src/github.com/heketi/heketi/executors/kubeexec/kubexec.go:244: Host: worker7 Pod: glusterfs-vnzql --Command lvs --options=lv_name, thin_count --separator=:
Result:      LV:#Thins
  vol_data:
  brick_552c...:
  tp_552c...:1
  lv_home:
  lv_home:
  lv_root:
  lv_swap:
  lv_temp:
  lv_usr:
  lv_usr:
  lv_var:
  lv_var:
[kubeexec] DEBUG 2018/04/25 /src/github.com/heketi/heketi/executors/kubeexec/kubexec.go:244: Host: worker5 Pod: glusterfs-2g16b Command: lvs --options=lv_name, thin_count --separator=:
Result:      LV:#Thins
  vol_data:
  brick_b9c6...:
  tp_b9c6..:1
  lv_home:
  lv_home:
  lv_root:
  lv_swap:
  lv_temp:
  lv_usr:
  lv_usr:
  lv_var:
  lv_var:
[kubeexec] DEBUG 2018/04/25 /src/github.com/heketi/heketi/executors/kubeexec/kubexec.go:244: Host: worker4 Pod: glusterfs-pg6ct Command: lvs --options=lv_name, thin_count --separator=:
Result:      LV:#Thins
  vol_data:
  brick_d0d4...:
  tp_d0d4..:1
  lv_home:
  lv_home:
  lv_root:
  lv_swap:
  lv_temp:
  lv_usr:
  lv_usr:
  lv_var:
  lv_var:
[negroni] Started GET /queue/d644...
[negroni] Completed 200 OK in 181ms
[negroni] Started GET /queue/d644...
[negroni] Completed 200 OK in 73ms
[negroni] Started GET /queue/d644...
[negroni] Completed 200 OK in 73ms
[negroni] Started GET /queue/d644...
[negroni] Completed 200 OK in 73ms
[kubeexec] DEBUG 2018/04/25 /src/github.com/heketi/heketi/executors/kubeexec/kubexec.go:244: Host:
worker7 Pod: glusterfs-vnzql  Command: gluster --mode=script volume stop vol_4cdaa... force
[negroni] Started GET /queue/d644...
[negroni] Completed 200 OK in 73ms
Result volume delete: vol_4cdaa...: success
[negroni] Started GET /queue/d644...
[negroni] Completed 200 OK
[kubeexec] DEBUG src/github.com/heketi/heketi/executors/kubeexec/kubexec.go:244: Host: worker7 Pod: glusterfs-vnzql Command: umount /var/lib/heketi/mounts/vg_7a90.../brick_d0d4...
Result: 
[kubeexec] DEBUG src/github.com/heketi/heketi/executors/kubeexec/kubexec.go:244: Host: worker5 Pod: glusterfs-vnzql Command: umount /var/lib/heketi/mounts/vg_548f.../brick_552c...
Result: 
[kubeexec] DEBUG src/github.com/heketi/heketi/executors/kubeexec/kubexec.go:244: Host: worker4 Pod: glusterfs-vnzql Command: umount /var/lib/heketi/mounts/vg_357e.../brick_b9c6...
Result:
[negroni] Started GET /queue/d644
[negroni] Completed 200 OK
[negroni] Started GET /queue/d644
[negroni] Completed 200 OK
[negroni] Started GET /queue/d644
[negroni] Completed 200 OK
[negroni] Started GET /queue/d644
[negroni] Completed 200 OK
[negroni] Started GET /queue/d644
[negroni] Completed 200 OK
[negroni] Started GET /queue/d644
[negroni] Completed 200 OK
**THIS FOR A REALLY LONG TIME UNTIL**
[kubeexec] DEBUG 2018/04/25 src/github.com/heketi/heketi/executors/kubeexec/kubexec.go:244: Host: worker7 Pod: glusterfs-vnzql Command: gluster --mode=script snapshot list vol_4cdaa...
Result: ?xml version:"1.0" encoding="UTF-8" standalone="yes"?>
cli-output>
  opRet>-1/opRet>
  opErrno>30806/opErrno>
  opErrstr>Volume (vol_4cdaa...) does not exist
/cli-output>
Result:     LV:#Thins
  vol_data:
  brick_b9c6...:
  tp_b9c6..:1
  lv_home:
  lv_home:
  lv_root:
  lv_swap:
  lv_temp:
  lv_usr:
  lv_usr:
  lv_var:
  lv_var:
[negroni] Started GET /queue/d644
[negroni] Completed 200 OK
[negroni] Started GET /queue/d644
[negroni] Completed 200 OK
[negroni] Started GET /queue/d644
[negroni] Completed 200 OK
[negroni] Started GET /queue/d644
[negroni] Completed 200 OK
[negroni] Started GET /queue/d644
[negroni] Completed 200 OK
[negroni] Started GET /queue/d644
[negroni] Completed 200 OK
**THIS FOR A REALLY LONG TIME UNTIL END OF FILE**

I tried to make a new pvc to test again and it froze up, never filling the pvc claim, i then deleted that pvc claim and tried to make a second one with a slightly different name just in case that was the problem
None of that worked.
Here are the logs of me trying that:
[negroni] Completed 200 OK
[negroni] Started GET /queue/d644
[negroni] Completed 200 OK
[negroni] Started GET /queue/b6de
[negroni] Completed 200 OK
[negroni] Started GET /queue/2448
[negroni] Completed 200 OK
[negroni] Started GET /queue/d644
[negroni] Completed 200 OK
[negroni] Started GET /queue/b6de
[negroni] Completed 200 OK
[negroni] Started GET /queue/2448
[negroni] Completed 200 OK
[heketi] INFO Loaded simple allocator
[heketi] INFO brick_num: 0
[negroni] Completed
[asynchttp] INFO asynchttp.go: Started job d9bda...
[heketi] INFO started async opertation: Create Volume
[heketi] Creating brick 7133...
[heketi] Creating brick 8f08...
[heketi] Creating brick e9dc...
[negroni] Started GET /queue/d8bda
[negroni] Completed OK
[kubeexec] DEBUG src/github.com/heketi/heketi/executors/kubeexec/kubexec.go:244: Host: worker7 Pod: glusterfs-vnzql Command: mkdir -p /var/lib/heketi/mounts/vg_584f.../brick_8f08...
Result:
[negroni] Started GET /queue/d8bda
[negroni] Completed OK
[kubeexec] DEBUG src/github.com/heketi/heketi/executors/kubeexec/kubexec.go:244: Host: worker7 Pod: glusterfs-vnzql Command: lvcreate --poolmetadatasize 16384K -c 256K -L 3145728K -T vg_548f.../tp8f08... -V 31457287K -n brick_8f08...
Result: Using defult stripesize 64.00 KiB
  Thin pull volume with chunk size 256 Kib can address at most 63.25 Tib of data
  Logical volume "brick_8f08..." created
**I am tired of typing, but the point is that it gets to this point**
[kubeexec] src/github.com/heketi/heketi/executors/kubeexec/kubexec.go:244: Host: worker7 Pod: gluster-vnzql Command: mount -o rw,inode64,nouuid /dev/mapper/vg_548f...
Result: 
[kubeexec]  src/github.com/heketi/heketi/executors/kubeexec/kubexec.go:244: Host: worker7 Pod: gluster-vnzql Command: mkdir /var/lib/heketi/mounts/vg_548f/brick_8f08
Result: 
[kubeexec]  src/github.com/heketi/heketi/executors/kubeexec/kubexec.go:244: Host: worker7 Pod: gluster-vnzql Command: chown :2001 /var/lib/heketi/mounts/vg_548f/brick_8f08
[kubeexec]  src/github.com/heketi/heketi/executors/kubeexec/kubexec.go:244: Host: worker7 Pod: gluster-vnzql Command: chmod 2775 /var/lib/heketi/mounts/vg_548f/brick_8f08
[negroni] Started GET /queue/b6de
[negroni] Completed 200 OK
[negroni] Started GET /queue/2448
[negroni] Completed 200 OK
[negroni] Started GET /queue/d644
[negroni] Started GET /queue/b6de
[negroni] Completed 200 OK
[negroni] Started GET /queue/2448
[negroni] Completed 200 OK
[negroni] Started GET /queue/d644
[negroni] Started GET /queue/b6de
[negroni] Completed 200 OK
[negroni] Started GET /queue/2448
[negroni] Completed 200 OK
[negroni] Started GET /queue/d644
**A LOOP SIMILAR TO THIS for thousands of lines with no further actual action ENDS THE FILE**

**Comment by mjschmidt** [comment]
[Here is the gluster issue for people keeping track of my epic journy](https://github.com/gluster/gluster-kubernetes/issues/434)

**Comment by mjschmidt** [comment]
Here is the part that I think is most relevant to this github issue
```
[kubeexec] DEBUG src/github.com/heketi/heketi/executors/kubeexec/kubexec.go:244: Host: worker7 Pod: glusterfs-vnzql Command: lvcreate --poolmetadatasize 16384K -c 256K -L 3145728K -T vg_548f.../tp8f08... -V 31457287K -n brick_8f08...
Result: Using defult stripesize 64.00 KiB
Thin pull volume with chunk size 256 Kib can address at most 63.25 Tib of data
Logical volume "brick_8f08..." created
I am tired of typing, but the point is that it gets to this point
[kubeexec] src/github.com/heketi/heketi/executors/kubeexec/kubexec.go:244: Host: worker7 Pod: gluster-vnzql Command: mount -o rw,inode64,nouuid /dev/mapper/vg_548f...
Result:
[kubeexec] src/github.com/heketi/heketi/executors/kubeexec/kubexec.go:244: Host: worker7 Pod: gluster-vnzql Command: mkdir /var/lib/heketi/mounts/vg_548f/brick_8f08
Result:
[kubeexec] src/github.com/heketi/heketi/executors/kubeexec/kubexec.go:244: Host: worker7 Pod: gluster-vnzql Command: chown :2001 /var/lib/heketi/mounts/vg_548f/brick_8f08
[kubeexec] src/github.com/heketi/heketi/executors/kubeexec/kubexec.go:244: Host: worker7 Pod: gluster-vnzql Command: chmod 2775 /var/lib/heketi/mounts/vg_548f/brick_8f08
```


So any idea of what could be the issue here? It looks like after it is chmoding, it is not continuing onto the following sudo code I wrote out of what I would expect the next steps to be
```
[cmdexe] INFO Creating volume vol_<id> replica 3
[kubeexec] Debug <statement with the stuff that does the gluster command> to "gluster --mode=script volume create vol_<id> replica 3 <hosts of bricks it is mounting> 
Result: volume create: vol_<id> success: please start volume to access the data"
[kubeexec] <debug statement to the host that has the started volume on it> gluster --mode=script volume start vol_<id> 
Result: volume start: vol_<id>: success
[asynchttp] INFO <stuff here> Completed job <job_id> in ~7 seconds
```

My BEST guess at the problem is that when heketi is in the middle of creating volumes it is not retrying at various points of the process, or checking to see if things its trying to do are done or not?

How to replicate the issue if interested:
Step 1 k8s cluster using heketi and gluster?
Step 2 launch the gk-deploy script found here:
https://github.com/gluster/gluster-kubernetes
Step 3 Start lunching some containers that need pvcs

Stateful-sets seem to cause the most issues?

**Comment by obnoxxx** [comment]
@mjschmidt Apologies, saw this only now... :-(

Need to look through it. In the meantime, maybe @phlogistonjohn , @raghavendra-talur , @jarrpa  have clues...

**Comment by kcao3** [comment]
@mjschmidt Do you still see this issue with Heketi:7 or 8?

**Comment by megian** [comment]
Heketi 8 shows the exact same as older versions.

[negroni] Started DELETE /volumes/c9e77fdfd2ae2272d72b8df64ffada76
[negroni] Completed 404 Not Found in 362.188µs
[negroni] Started DELETE /volumes/7e3d6e1284ac81bb9014c5955ab136b2
[negroni] Completed 404 Not Found in 404.311µs
[negroni] Started DELETE /volumes/9e5e67734c44e358677ecb0e88ffac9f
[negroni] Completed 404 Not Found in 321.539µs
[negroni] Started DELETE /volumes/07a87c929f11f424eee76269d376777d
[negroni] Completed 404 Not Found in 364.454µs

**Comment by phlogistonjohn** [comment]
Hi @megian I'm not quite sure that is the same issue originally reported here. Your snippet contains "404 Not Found" which does not appear elsewhere in this issue or the linked issue in gluster-kubernetes. Could you please file a new issue following the new issue template so that we can try and help debug your situation? Thanks.

**Comment by megian** [comment]
@phlogistonjohn Opened the issue 1367 for the error "404 Not Found"

**Comment by mjschmidt** [comment]
@kcao3 idk I haven't run the stack since I wasn't able to get it to be reliable since there was no error checking to do something like say, time out and retry when it didn't get a response back (from what I could tell it looked like messages may have been getting lost if for some reason it caused a gluster pod to restart)

**Comment by mjschmidt** [comment]
@kcao3 that fun is here  https://github.com/gluster/gluster-kubernetes/issues/434

Ultimately, since I just wanted to use kafka anyway... I went with developing a localPVC tool where I could declairatively use pssh to setup my logical volumes, a short python script that would create (off a template) persistent volume yaml template file and point it at a storage class that I could use the same little py script and different storage class template file to create the storageclass yaml file. So all in all I sort of punted on the whole "on premise storage" solution and decided I would revisit. At this point I am hoping that the operator stuff takes off and someone creates an operator for either local pvcs, or this heketi gluster combo.

**Comment by phlogistonjohn** [comment]
Stale issue. Closing.
