### ISSUE TITLE
Need unit test for SetLogLevel()

### ISSUE THREAD

**Issue by obnoxxx** [heketi/heketi#1158]
### Kind of issue

Technical debt.

### Observed behavior

PR #1156  has shown that we need a unit test for `SetLogLevel()` to test out various corner cases.

**Comment by obnoxxx** [comment]
@phlogistonjohn feel free to assign on to s/o else if you feel like it... :-)

**Comment by phlogistonjohn** [comment]
Stale issue. Closing.
