### ISSUE TITLE
Heketi container complains about read-only filesystem

### ISSUE THREAD

**Issue by devent** [heketi/heketi#1162]
### Kind of issue

Bug

### Observed behavior

```
$ kubectl -n kube-system logs heketi-68f9cd6f6-s6mxf
Setting up heketi database
/var/lib/heketi is read-only
touch: cannot touch '/var/lib/heketi/test': Read-only file system
```

### Expected/desired behavior

Heketi pod should start without errors.

### Details on how to reproduce (minimal and precise)

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    description: Defines how to deploy Heketi
  creationTimestamp: 2018-04-17T09:09:38Z
  generation: 2
  labels:
    glusterfs: heketi-deployment
    heketi: deployment
    robobeerun.com/group: glusterfs-heketi
  name: heketi
  namespace: kube-system
  resourceVersion: "52107"
  selfLink: /apis/extensions/v1beta1/namespaces/kube-system/deployments/heketi
  uid: 0e69ee04-421f-11e8-9ba7-08002749d23a
spec:
  replicas: 1
  selector:
    matchLabels:
      glusterfs: heketi-pod
      heketi: pod
      robobeerun.com/group: glusterfs-heketi
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        glusterfs: heketi-pod
        heketi: pod
        robobeerun.com/group: glusterfs-heketi
      name: heketi
    spec:
      containers:
      - env:
        - name: HEKETI_USER_KEY
          value: Aif1reigei2ooth4
        - name: HEKETI_ADMIN_KEY
          value: cai7jie5vooqu8uF
        - name: HEKETI_EXECUTOR
          value: kubernetes
        - name: HEKETI_FSTAB
          value: /var/lib/heketi/fstab
        - name: HEKETI_SNAPSHOT_LIMIT
          value: "14.0"
        - name: HEKETI_KUBE_GLUSTER_DAEMONSET
          value: "y"
        - name: HEKETI_IGNORE_STALE_OPERATIONS
          value: "true"
        image: heketi/heketi:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /hello
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        name: heketi
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /hello
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 250m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/heketi
          name: db
        - mountPath: /etc/heketi
          name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: heketi-service-account
      serviceAccountName: heketi-service-account
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Equal
      volumes:
      - glusterfs:
          endpoints: heketi-storage-endpoints
          path: heketidbstorage
        name: db
      - name: config
        secret:
          defaultMode: 420
          secretName: heketi-config-secret
```

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): master
- Operating system used: Linux node-0 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux
- Heketi compiled from sources, as a package (rpm/deb), or container: container
- If container, which container image: latest
- Using kubernetes, openshift, or direct install: kubernetes
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: inside
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): gk-deploy

### Other useful information

Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:21:50Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by devent** [comment]
```
$ kubectl -n kube-system exec glusterfs-7j8v4 -- gluster volume info heketidbstorage
 
Volume Name: heketidbstorage
Type: Replicate
Volume ID: b939c7ba-0aae-451a-9eb4-7710cb4794d2
Status: Started
Snapshot Count: 0
Number of Bricks: 1 x 3 = 3
Transport-type: tcp
Bricks:
Brick1: 192.168.56.200:/var/lib/heketi/mounts/vg_310b0139d30076f6d1abc4936ba23107/brick_39cc1493e546b2678a0a43fa95894855/brick
Brick2: 192.168.56.201:/var/lib/heketi/mounts/vg_86ad0622f272946c46b4a109e8c80f00/brick_7e8579213c0b6779624ff23817a28e16/brick
Brick3: 192.168.56.202:/var/lib/heketi/mounts/vg_09f85c5bcb690e8b4d94ec96468e4725/brick_c6a7499257362ff25fa8596b85b8f66b/brick
Options Reconfigured:
transport.address-family: inet
nfs.disable: on
performance.client-io-threads: off
```

**Comment by kornik** [comment]
Also facing this issue.

**Comment by wernergillmer** [comment]
same problem

**Comment by ksemaev** [comment]
same on openshift 3.9

**Comment by vikramkhatri** [comment]
Same problem facing on IBM Cloud Private 2.1.0.3 - which is using Heketi v5.0.0-5-gb005e0f-release-5

**Comment by vikramkhatri** [comment]
@raghavendra-talur - This is similar issue that we are facing. Tried `gluster volume start heketodbstorage force` but still read-only file system and bricks do not start on other nodes.

**Comment by phlogistonjohn** [comment]
@vikramkhatri  It looks like you are asking the same question in more than one issue. Specifically issue #1318 

While it is not a big problem I almost started replying with something similar to what @raghavendra-talur  wrote in the other thread. To avoid duplicating effort it would have been preferable if you just mentioned this issue number in the issue that you filed and the issue tracker would have automatically created a reference between the two.

**Comment by vikramkhatri** [comment]
@phlogistonjohn - Thanks. Yes. I saw this after I opened the issue. I commented here just to connect the two. We discovered that using `gluster volume start heketidbstorage force` did not fix issue as two out of three bricks did not come online. Then, we manually deleted one brick by setting replicas=2 and then deleted another brink using replicas=1. After that Heketi pod came out of `CrashLoopBackOff`. Then we used `heketi-cli` commands to see the volumes and there were many orphan volumes - they were not assigned to a path. This may have happened due to reasons that I do not understand. Basically - I have to drop gluster and heketi deployments, wipe out the disk and start all over again. Do you know if Heketi newer version (we are on 5.x) will have a way to delete these orphaned volumes as we could not figure out anyway,

Thank you for the response but can you please convey to the development that this read-only file system and many orphan volumes are causes of worry.

**Comment by wdbasson** [comment]
same here also after a node restart on OKD v3.11

**Comment by wdbasson** [comment]
Applying [these](https://github.com/openshift/openshift-ansible/pull/10806/commits/d2bdffea98d4770bfda0a25415ecde9e8243e820) changes solved my problem. [These](https://github.com/openshift/openshift-ansible/commit/f2bd499c230b60dd7efa97372efb317bd5495c9f#diff-21b02900b0aa9e6d4b9b771d903e1202) changes seem to have broken it.

Not 100% sure what is happening and why mounting the root dir /dev isn't sufficient, but running `blkid` inside a container after reboot shows that the gluster vg is absent

```
sh-4.2# blkid
/dev/sda1: UUID="e29dbf51-dc08-414b-9eab-e9efcf42e610" TYPE="xfs" 
/dev/sda2: UUID="C1AjnZ-dvGi-NdnQ-aCzk-2UtI-CrMR-XvUDd1" TYPE="LVM2_member" 
/dev/sdb: UUID="40qKT7-0vn3-hBrO-4Tmz-KSRy-KulC-V0qPI2" TYPE="LVM2_member" 
/dev/dm-0: UUID="e166e678-afee-4c44-9c87-38f0213e17e7" TYPE="xfs" 
/dev/dm-1: UUID="be40871b-b601-42f3-a46c-e80510e0a020" TYPE="swap" 
/dev/dm-2: UUID="8beb154d-6f21-40f6-99bc-95e6dd70a05a" TYPE="xfs" 
/dev/dm-7: UUID="43403082-68fb-41da-bfa4-3c6d84777716" TYPE="xfs" 
```
Specifically adding /dev/mapper host path to the gluster daemonset solves the problem:
```
sh-4.2# blkid
/dev/sda1: UUID="e29dbf51-dc08-414b-9eab-e9efcf42e610" TYPE="xfs" 
/dev/sda2: UUID="C1AjnZ-dvGi-NdnQ-aCzk-2UtI-CrMR-XvUDd1" TYPE="LVM2_member" 
/dev/sdb: UUID="40qKT7-0vn3-hBrO-4Tmz-KSRy-KulC-V0qPI2" TYPE="LVM2_member" 
/dev/mapper/centos_sentinel1-root: UUID="e166e678-afee-4c44-9c87-38f0213e17e7" TYPE="xfs" 
/dev/mapper/centos_sentinel1-swap: UUID="be40871b-b601-42f3-a46c-e80510e0a020" TYPE="swap" 
/dev/mapper/centos_sentinel1-home: UUID="8beb154d-6f21-40f6-99bc-95e6dd70a05a" TYPE="xfs" 
/dev/mapper/vg_1a083cb150f95754ae9ac668e0009748-brick_1e74e3b182a596084a5277c107a12651: UUID="43403082-68fb-41da-bfa4-3c6d84777716" TYPE="xfs" 
```

[This](https://github.com/gluster/gluster-kubernetes/issues/499#issuecomment-443191007) discussion lead me to the solution.

**Comment by wdbasson** [comment]
The latest image docker.io/gluster/gluster-centos:latest solves this issue without /dev/mapper host path.

It appears that only my first node was using the latest image (which explains why it could reboot). The other two nodes somehow pulled outdated images.

**Comment by phlogistonjohn** [comment]
Fairly old issue with either resolutions or very old comments. Closing. Please open new issues if you feel you're encountering the same conditions as in this issue.
