### ISSUE TITLE
Create distributed - replicated volume from k8s

### ISSUE THREAD

**Issue by es1o** [heketi/heketi#1175]
### Kind of issue
Bug, FeatureRequest

### Observed behavior
Heketi doesn't create volume if replicate:2 is set and volume size is bigger than free space on each node.

### Expected/desired behavior
Heketi create distributed - replicated volume to provide desired capacity.

### Details on how to reproduce (minimal and precise)
I created new StorageClass in openshift cluster
```
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
parameters:
  resturl: http://heketi-storage-glusterfs.cluster.local
  restuser: admin
  secretName: heketi-storage-admin-secret
  secretNamespace: glusterfs
  volumetype: replicate:2
provisioner: kubernetes.io/glusterfs
metadata:
  name: glusterfs-storage-replica-2
```
I would like to use replica:2 in gluster volumes.
I have 4 nodes with 50GB space each, when I create pvc volume that size is smaller than free space on nodes heketi creates volume with two replicas. When I create volume that size is bigger than one volume space heketi doesn't create volume and I get error:
```Failed to provision volume with StorageClass "glusterfs-storage-replica-2": glusterfs: create volume err: error creating volume No space```

E.g. volume with size 60GB doesn't work. I think in this case heketi should create distributed - replicated or replicated - distributed volume with 4 nodes from cluster with 30GB of data on each.

I initially created similar issue in gluster-kubernetes project: https://github.com/gluster/gluster-kubernetes/issues/473

I saw that creating distributed - replicated volumes are not supported: https://github.com/heketi/heketi/blob/master/docs/api/api.md#create-a-volume

Are you planning to add support for that type of volume in near future?

EDIT:
I checked again and heketi creates volumes only with even distributed number, e.g. 4x2, doesn't creates 3x2. It is the reason that I didn't have space for my volume.

Another problem is heketi creates bricks on one node, e.g.
```
Volume Name: vol_0c2f3c6c95e9c9feee9db9452dd7d94e
Type: Distributed-Replicate
Volume ID: 3f7b6ce8-52b5-4fb9-8f54-f756fce8d66f
Status: Started
Snapshot Count: 0
Number of Bricks: 4 x 2 = 8
Transport-type: tcp
Bricks:
Brick1: ip1:/var/lib/heketi/mounts/vg_2760a16002a30c9490fdbe6cdc7ef2d8/brick_5af9cd515c6596dacc4e209e18a782b0/brick
Brick2: ip2:/var/lib/heketi/mounts/vg_147c8c86c905e70c321b2f5cb8a797b6/brick_28d534bef6f908495db5c1c07be967a8/brick
Brick3: ip1:/var/lib/heketi/mounts/vg_2760a16002a30c9490fdbe6cdc7ef2d8/brick_fad8684f34f9ea38672c561432589003/brick
Brick4: ip2:/var/lib/heketi/mounts/vg_147c8c86c905e70c321b2f5cb8a797b6/brick_aad13ada7f33b807e65a006a364470c0/brick
Brick5: ip4:/var/lib/heketi/mounts/vg_01a5e04d98f91da39297191033dd0fc3/brick_848616153df6a90d5964565f35a59c28/brick
Brick6: 10.53.14.116:/var/lib/heketi/mounts/vg_06a23bacae91d023a8e014eca4dc5a20/brick_2a0e261f8d4b7aaffc7ee67da0030cf2/brick
Brick7:
ip3:/var/lib/heketi/mounts/vg_147c8c86c905e70c321b2f5cb8a797b6/brick_6d48fe285dbad18251e802047e9c8a75/brick
Brick8: ip4:/var/lib/heketi/mounts/vg_01a5e04d98f91da39297191033dd0fc3/brick_193b55933223b7ba3f70449dcd3bee75/brick
Options Reconfigured:
transport.address-family: inet
nfs.disable: on
performance.client-io-threads: off
```
Gluster bricks should be on separate hosts because in some cases duplicated data can be on two bricks that exists on one node.

Looks like heketi uses only 4 hosts, not 6 availible. In this case heketi should throw error because it can't provide correct configuration and I lost redundancy but I don't know about this. I need to check volume directly to see that I doesn't have redundancy, because heketi tells me that everything is ok.

I think heketi should check if desired configuration can be applied to cluster with desired redundancy status.

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): delivered with OpenShift Origin 3.7
- Operating system used: RHEL7
- Heketi compiled from sources, as a package (rpm/deb), or container: container
- If container, which container image: delivered with OpenShift Origin 3.7
- Using kubernetes, openshift, or direct install: openshift
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: inside
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom):  openshift-ansible

**Comment by obnoxxx** [comment]
@es1o Heketi only exposes the so called durability type to the user (API). In this case it is replicate of replica count 2 (default is 3, which is a lot safer). Heketi will figure out the distribution count for itself. It will try to give you as few bricks as possible, so willl try to do replica-2. If no 2 disks on 2 nodes have sufficient free space, then it will try to create more bricks, with a higher distribute count. In this case, the only guarantee heketi gives you is that the bricks of one replica set are ending up on different nodes. Different replica sets can have the same or disjoint or just overlapping sets of nodes. 

Examples:
* If you have 4 nodes with one disks with 50GiB free space each, and you try to create a 60GiB volume (of durability type replicate:2), then you should end up with one brick of 30GiB on each node.
* If you have 2 nodes with 2 disks with 50GiB free each, and you try to create a 60GiB volume of durability type replicate:2, the you should end up with two bricks of 30GiB on each node, where the two replica sets span the two nodes.
* etc ...

If you can not confirm this behavior, we need more details.

**Comment by es1o** [comment]
@obnoxxx 
Hi. I'll try explain my problems:
First problem:
1. I have 6 nodes with 100GB each.
2. I created 300GB volume with replica 2, I expect that heketi create distributed - replicated volume 3x2 with 100GB on each node. Instead heketi doesn't create volume with error: ` Failed to provision volume with StorageClass "glusterfs-storage-replica-2": glusterfs: create volume err: error creating volume No space` because heketi try to create volume 4x2.
Second problem:
1. I have 6 nodes with 100GB each.
2. I created volume 60GB with replica 2.
3. Heketi creates 8 bricks - 30GB each and place two bricks on one node. I lost replica because data is duplicated on bricks and two bricks can be on one machine. When I lost machine I lost data. I think this problem is more important because glusterFS doesn't duplicate brick, it duplicates data. E.g. file A may be duplicated on bricks: brick1 and brick2, file B may be duplicate on brick 2 and brick3. When brick2 and brick3 are on the same node and I lose that node, I'll lose file B.

**Comment by jianzi123** [comment]
@es1o The  "replicate:2" default is Distributed-Replica volume.

**Comment by es1o** [comment]
@jianzi123 Ok, but it is not a clue of problem. Heketi creates two replicas on one node without informing of that. I think that I have replica 2 but with two replicas on one node I don't have true replica. This is a serious issue an may result with data loss when I lost one node or disable it because e.g. I want to replace disks or recreate array.

**Comment by jianzi123** [comment]
@es1o You can see the heketi log to what it do when creating volumes, I think the two bricks in the same node may not replicas.

**Comment by jianzi123** [comment]
@teddyhuang007 I think the type hash or distribute is made by different volumes, could you find volumes in `volume list`. Two bricke in a volume is one copy.

**Comment by jianzi123** [comment]
@teddyhuang007 You are right.

**Comment by es1o** [comment]
@jianzi123 GlusterFS doesn't recognize nodes for replica and distribution.
For example, I have distributed replicated volume with 2 replicas and have 4 bricks A,B,C and D.
These bricks are treat as the same by glusterFS. One file eg. file1 is aplit to two parts f1a and f1b. GlusterFS may save these file as:
f1a on brick A
f1a on brick B
f1b on brick C
f1b on brick D

But for other file, file2 can save
f2a on B
f2a on C
f2b on A
f2b on D

When heketi creates A and B on one node file2 will be safe when node with A and B gone, but you will lost file1. You don't have information about this because heketi reports that volume creation was successfull.

Summarizing, glusterFS doesn't have special brick for replicas and for distribution. Every file may be replicated and dirstibuted in different way.

**Comment by phlogistonjohn** [comment]
Stale issue. Closing.
