### ISSUE TITLE
heketi is not creating volumes when we give very large average file size

### ISSUE THREAD

**Issue by iamniting** [heketi/heketi#1181]
### Kind of issue
Bug

### Observed behavior
Heketi is not creating a volume.

### Expected/desired behavior
It should create volume with minimum (16 mb) arbiter brick size.

### Details on how to reproduce (minimal and precise)
$ heketi-cli volume create --size=10 --gluster-volume-options='user.heketi.arbiter true,user.heketi.average-file-size 1024'

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): 6.0.0-12 
- Operating system used: RHEL
- Heketi compiled from sources, as a package (rpm/deb), or container: Container & RPM 
- If container, which container image: 3.3.1-12
- Using kubernetes, openshift, or direct install: brew
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: inside
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): ansible

### Other useful information

```
Error: Unable to execute command on glusterfs-storage-dz65l: agsize (3072 blocks) too small, need at least 4096 blocks
Usage: mkfs.xfs
/* blocksize */		[-b log=n|size=num]
/* metadata */		[-m crc=0|1,finobt=0|1,uuid=xxx]
/* data subvol */	[-d agcount=n,agsize=n,file,name=xxx,size=num,
			    (sunit=value,swidth=value|su=num,sw=num|noalign),
			    sectlog=n|sectsize=num
/* force overwrite */	[-f]
/* inode size */	[-i log=n|perblock=n|size=num,maxpct=n,attr=0|1|2,
			    projid32bit=0|1]
/* no discard */	[-K]
/* log subvol */	[-l agnum=n,internal,size=num,logdev=xxx,version=n
			    sunit=value|su=num,sectlog=n|sectsize=num,
			    lazy-count=0|1]
/* label */		[-L label (maximum 12 characters)]
/* naming */		[-n log=n|size=num,version=2|ci,ftype=0|1]
/* no-op info only */	[-N]
/* prototype file */	[-p fname]
/* quiet */		[-q]
/* realtime subvol */	[-r extsize=num,size=num,rtdev=xxx]
/* sectorsize */	[-s log=n|size=num]
/* version */		[-V]
			devicename

```

**Comment by obnoxxx** [comment]
Thanks, @iamniting , I am working on a fix for this.
