### ISSUE TITLE
Heketi allows multiple block volume delete operations to be stored in the db

### ISSUE THREAD

**Issue by phlogistonjohn** [heketi/heketi#1189]
### Kind of issue

Bug

### Observed behavior

Running the command `heketi db  delete-pending-entries  --dbfile heketi.db` fails with an Id not found error.
Output:
```
[heketi] INFO 2018/05/18 10:58:12 Found a pending blockvolume delete operation with id: 254a0c640035068533daa41b3689df1f and timestamp: 1526523891
[heketi] INFO 2018/05/18 10:58:12 Deleting blockvolume with id: e5597000021ee2e43ebc7fad016dd84b
[heketi] INFO 2018/05/18 10:58:12 USER ACTION REQUIRED: cleanup blockvolume:blockvol_e5597000021ee2e43ebc7fad016dd84b on hostingvolume:556d36156322929697e91823fb222aed
[heketi] INFO 2018/05/18 10:58:12 
Pending Operation 3 End
[heketi] INFO 2018/05/18 10:58:12 
Pending Operation 4 Start
[heketi] INFO 2018/05/18 10:58:12 Found a pending blockvolume delete operation with id: 2b3faca769a7695194ef7f2840d22d48 and timestamp: 1526524161
[heketi] INFO 2018/05/18 10:58:12 Deleting blockvolume with id: e5597000021ee2e43ebc7fad016dd84b
failed to delete entries with pending attribute: Id not found
```

### Expected/desired behavior

Pending operations get cleaned up OR impossible to get into this state (or both :-)).

### Details on how to reproduce (minimal and precise)

DB dump was provided by a user. I suspect this is trivially reproducible by simply preventing the delete operation from completing while other delete requests are sent to the server.

This can be checked via new tests against the operations code.

### Other useful information
```
    "254a0c640035068533daa41b3689df1f": {
      "Actions": [
        {
          "Change": 7,
          "Delta": null,
          "Id": "e5597000021ee2e43ebc7fad016dd84b"
        }
      ],
      "Id": "254a0c640035068533daa41b3689df1f",
      "Timestamp": 1526523891,
      "Type": 5
    },
    "2b3faca769a7695194ef7f2840d22d48": {
      "Actions": [
        {
          "Change": 7,
          "Delta": null,
          "Id": "e5597000021ee2e43ebc7fad016dd84b"
        }
      ],
      "Id": "2b3faca769a7695194ef7f2840d22d48",
      "Timestamp": 1526524161,
      "Type": 5
    },
```

**Comment by raghavendra-talur** [comment]
@phlogistonjohn I think #1251 would fix this issue, right?

**Comment by phlogistonjohn** [comment]
> I think #1251 would fix this issue, right?

I don't think so. I think the case here is a db that has multiple operations to delete item X. The operations cleanup code has to cope with the fact that the first operation may have already deleted X by the time the 2nd operation is encountered. Alternatively, one could take a two-phase approach where all the items to be cleaned up are collected in a matter that avoids or handles duplicates (a map using IDs as keys for example). That change touches the remove-bricks-with-empty-path code while this would need to modify the delete-pending-operations code.

That all said perhaps that should be a different issue rather than leave this open...

**Comment by obnoxxx** [comment]
I suggest creating a separate issue for cleaning up old dbs with this problem. AFAICT, with #1201 merged, we can not get into this situation any more with new installs.

**Comment by obnoxxx** [comment]
Issue #1363 has been created to treat the cleanup of old dbs in that state.
