### ISSUE TITLE
How does heketi decide if glusterd is running or not?

### ISSUE THREAD

**Issue by mjschmidt** [heketi/heketi#1194]
Heketi currently tells me glusterd is not running, what command is it running to make this determination?

I had glusterd running when I check systemctl status glusterd

and ps aux | grep glusterd return the running process of /user/sbin/glusterd -p /var/run/glusterd.pid --log-level INFO

Is heketi checking service --status-all | grep glusterd? That might explain my problem, but I don't want to explore that route if heketi isn't trying that. It would be nice if Heketi returned the command it was trying to run as part of the error message.

**Comment by phlogistonjohn** [comment]
https://github.com/heketi/heketi/blob/master/executors/cmdexec/peer.go#L72

It will use either SSH or kubernetes transports to run that command on the node. The logging should indicate if it unable to communicate with the node or if the systemctl command returned an error code.

**Comment by obnoxxx** [comment]
if glusterd is not mananged by systemd (e.g. an external gluster, not running on a systemd-based linux, or the admin has configured the system to not use systemd...) then having hard-coded systemd might be a problem :-)

**Comment by obnoxxx** [comment]
@mjschmidt can we get more details?

**Comment by mjschmidt** [comment]
So I did look into this, and it was using the ssh executor in go.

The reason this wasn't working is because I was on a locked down system that doesn't allow new ssh agents to start. So the gluster service was running, but heketi was unable to ssh over to the nodes to actually do anything. The returned error message was "glusterd is not running on <node>" which is why I got mixed up for a while.

**Comment by robdewit** [comment]
> if glusterd is not mananged by systemd (e.g. an external gluster, not running on a systemd-based linux, or the admin has configured the system to not use systemd...) then having hard-coded systemd might be a problem :-)

Maybe too trivial to note, but this is just how I get around this systemctl-dependency now.

```
#!/bin/sh
# this is just a fake /usr/local/sbin/systemctl

if [ "${1}" = "status" ]
then
	ps -C "${2}" -o pid,command 
else
	echo "This is just a mockup systemctl"
	exit 1
fi

```

**Comment by phlogistonjohn** [comment]
Stale issue. Closing.
