### ISSUE TITLE
Volumes Mismatch between heketi DB & Gluster

### ISSUE THREAD

**Issue by Ashishyh** [heketi/heketi#1197]
Hi,

We are have scenario where 1 TB devices added to glusterFS 
Kubectl pvc showing 33
glusterfs volume count is 67
Heketi volume count is 91

We found few volumes listing in heketi DB acutually not reflecting in glusterFS
When tried to delete from heketi-cli giving error 
" heketi-cli volume delete 0dfe076421b963877600
Error: Unable to delete volume vol_0dfe076421b963877600bb1f57e6b755: Unable to execute command on glusterfs-tzmxl: volume delete: vol_0dfe076421b963877600bb1f57e6b755: failed: Volume vol_0dfe076421b963877600bb1f57e6b755 does not exist "

How can we remove the volume entries from Heketi DB need some advice on this

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master):  Heketi v5.0.0-5-gb005e0f-release-5
- Operating system used:  Ubuntu 16.04

- Using kubernetes, openshift, or direct install:  Kubernetes
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside:  GLuster running inside the cluster

**Comment by phlogistonjohn** [comment]
Stale issue. Closing.
