### ISSUE TITLE
Failed to remove device: Unable to replace brick when node lost

### ISSUE THREAD

**Issue by napat1412** [heketi/heketi#1204]
### Kind of issue

> Uncomment only one of these:
> 
> Bug

Feature request

### Observed behavior
I create heketi & glusterfs with gk-deploy. I have 4 gluster nodes 
- n251.service.local device: /dev/sdb  ip: 172.16.0.196
- n252.service.local device: /dev/sdb  ip: 172.16.0.197
- n253.service.local device: /dev/sdb  ip: 172.16.0.198
- n254.service.local device: /dev/sdb  ip: 172.16.0.199
Default gluster volume: heketidbstorage has 3 replicas that locate on node: n251.service.local, n252.service.local, and n253.service.local
I shutdown node: n253.service.local. Then, I remove node: n253.service.local. I ran the following command and got error.

heketi-cli node disable 0e5628f8c6606fb1135ed6562aef3e7d
> Node 0e5628f8c6606fb1135ed6562aef3e7d is now offline

heketi-cli node remove 0e5628f8c6606fb1135ed6562aef3e7d
> Error: Failed to remove device, error: Unable to replace brick 172.16.0.198:/var/lib/heketi/mounts/vg_c98f4ea17953a369af2661a411d7d943/brick_2688be64ca6a68847133f3f9f4f72ed0/brick with 172.16.0.199:/var/lib/heketi/mounts/vg_e1ac2084248d722b7219b7ead42d2d5d/brick_9720fe77e7c727b550d1487fe5612649/brick for volume heketidbstorage

heketi-cli device disable c98f4ea17953a369af2661a411d7d943
> Device c98f4ea17953a369af2661a411d7d943 is now offline

heketi-cli device remove c98f4ea17953a369af2661a411d7d943
> Error: Failed to remove device, error: Unable to replace brick 172.16.0.198:/var/lib/heketi/mounts/vg_c98f4ea17953a369af2661a411d7d943/brick_2688be64ca6a68847133f3f9f4f72ed0/brick with 172.16.0.199:/var/lib/heketi/mounts/vg_e1ac2084248d722b7219b7ead42d2d5d/brick_22d724ee00eeb61c89db34c4d85f758c/brick for volume heketidbstorage

### Expected/desired behavior
I remove node and device successfully and new brick [on new node] is created by the replica data in remain node.

### Details on how to reproduce (minimal and precise)
- create kubernetes cluster v1.10.2: master 1 node, worker 4 node
- deploy heketi & gluster with gk-deploy -g

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): v6.0.0-196-gf31ad28 (docker.io/heketi/heketi:dev)
- Operating system used: CentOS7
- Heketi compiled from sources, as a package (rpm/deb), or container: containner
- If container, which container image: docker.io/gluster/gluster-centos:gluster3u13_centos7
- Using kubernetes, openshift, or direct install: kubernetes
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: inside
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): gk-deploy

### Other useful information
heketi-cli volume info 07db3b9237d2cdfe081f157c916cf001
> heketi-cli volume info 6ce5fa7b0f15978d3a6c7f9ed872d561
Name: heketidbstorage
Size: 2
Volume Id: 6ce5fa7b0f15978d3a6c7f9ed872d561
Cluster Id: 102bae300a1cd9621efd500417979a1d
Mount: 172.16.0.199:heketidbstorage
Mount Options: backup-volfile-servers=172.16.0.196,172.16.0.198
Block: false
Free Size: 0
Block Volumes: []
Durability Type: replicate
Distributed+Replica: 3

heketi-cli topology info

Cluster Id: 102bae300a1cd9621efd500417979a1d

    File:  true
    Block: true

    Volumes:

        Name: heketidbstorage
        Size: 2
        Id: 6ce5fa7b0f15978d3a6c7f9ed872d561
        Cluster Id: 102bae300a1cd9621efd500417979a1d
        Mount: 172.16.0.199:heketidbstorage
        Mount Options: backup-volfile-servers=172.16.0.196,172.16.0.198
        Durability Type: replicate
        Replica: 3
        Snapshot: Disabled

                Bricks:
                        Id: 2688be64ca6a68847133f3f9f4f72ed0
                        Path: /var/lib/heketi/mounts/vg_c98f4ea17953a369af2661a411d7d943/brick_2688be64ca6a68847133f3f9f4f72ed0/brick
                        Size (GiB): 2
                        Node: 0e5628f8c6606fb1135ed6562aef3e7d
                        Device: c98f4ea17953a369af2661a411d7d943

                        Id: 3150b2f314529e61c9446597a5a5f6ed
                        Path: /var/lib/heketi/mounts/vg_7b2dd41ac59eb658f745b7f422203097/brick_3150b2f314529e61c9446597a5a5f6ed/brick
                        Size (GiB): 2
                        Node: 88fc1c9cae4102e78ba122bf1bcf6ef6
                        Device: 7b2dd41ac59eb658f745b7f422203097

                        Id: 9f62fc09d7b748df4318278fe1d9a07f
                        Path: /var/lib/heketi/mounts/vg_da17e1b08579a54c7609077d41db04de/brick_9f62fc09d7b748df4318278fe1d9a07f/brick
                        Size (GiB): 2
                        Node: 3ae63bcd93ddf8201bc7703a98635c0b
                        Device: da17e1b08579a54c7609077d41db04de

    Nodes:

        Node Id: 0e5628f8c6606fb1135ed6562aef3e7d
        State: online
        Cluster Id: 102bae300a1cd9621efd500417979a1d
        Zone: 1
        Management Hostnames: n253.service.local
        Storage Hostnames: 172.16.0.198
        Devices:
                Id:c98f4ea17953a369af2661a411d7d943   Name:/dev/sdb            State:online    Size (GiB):99      Used (GiB):17592186044411Free (GiB):103
                        Bricks:
                                Id:2688be64ca6a68847133f3f9f4f72ed0   Size (GiB):2       Path: /var/lib/heketi/mounts/vg_c98f4ea17953a369af2661a411d7d943/brick_2688be64ca6a68847133f3f9f4f72ed0/brick

        Node Id: 35841846721c59b4f4c4c5b9f5503fb4
        State: offline
        Cluster Id: 102bae300a1cd9621efd500417979a1d
        Zone: 1
        Management Hostnames: n254.service.local
        Storage Hostnames: 172.16.0.199
        Devices:
                Id:e1ac2084248d722b7219b7ead42d2d5d   Name:/dev/sdb            State:online    Size (GiB):99      Used (GiB):0       Free (GiB):99     
                        Bricks:

        Node Id: 3ae63bcd93ddf8201bc7703a98635c0b
        State: online
        Cluster Id: 102bae300a1cd9621efd500417979a1d
        Zone: 1
        Management Hostnames: n252.service.local
        Storage Hostnames: 172.16.0.197
        Devices:
                Id:da17e1b08579a54c7609077d41db04de   Name:/dev/sdb            State:online    Size (GiB):99      Used (GiB):0       Free (GiB):99     
                        Bricks:
                                Id:9f62fc09d7b748df4318278fe1d9a07f   Size (GiB):2       Path: /var/lib/heketi/mounts/vg_da17e1b08579a54c7609077d41db04de/brick_9f62fc09d7b748df4318278fe1d9a07f/brick

        Node Id: 88fc1c9cae4102e78ba122bf1bcf6ef6
        State: online
        Cluster Id: 102bae300a1cd9621efd500417979a1d
        Zone: 1
        Management Hostnames: n251.service.local
        Storage Hostnames: 172.16.0.196
        Devices:
                Id:7b2dd41ac59eb658f745b7f422203097   Name:/dev/sdb            State:online    Size (GiB):99      Used (GiB):2       Free (GiB):97     
                        Bricks:
                                Id:3150b2f314529e61c9446597a5a5f6ed   Size (GiB):2       Path: /var/lib/heketi/mounts/vg_7b2dd41ac59eb658f745b7f422203097/brick_3150b2f314529e61c9446597a5a5f6ed/brick

*Edit#1: change from bug to feature request

**Comment by napat1412** [comment]
Cause of problem is the unclean gluster node.  Sorry about my mistakes.
Now, I have only one question.

Can we use command "heketi-cli device remove" and "heketi-cli node remove" to remove device or node in case of node lost?

**Comment by phlogistonjohn** [comment]
No updates in a few months. Closing. Please reopen if this issue is still relevant to you.

**Comment by gangyi89** [comment]
Hi, I am facing the exact same problem. I think this is a very important recover exercise that should be addressed. Anyone able to advice?

glusterfs version: 7
heketi version: 10.0.0.0

**Comment by iamniting** [comment]
We had a new release a few days back. Pls, use that. It should resolve your problems.
[1] https://github.com/heketi/heketi/tree/v10.1.0
