### ISSUE TITLE
Heketi 6 is corrupting it's own database and refuses to start

### ISSUE THREAD

**Issue by hakanisaksson** [heketi/heketi#1207]
### Kind of issue

Bug

### Observed behavior

Sometimes the pending queue in the heketi database gets corrupted. This has happened twice since upgrading to 6.0.0 (and serveral times in previous versions).
One can observe in the logs that heketi is constantly trying to poll and complete the items in the pending queue, but it will never complete, and any new requests to create volumes will also not complete. After stopping the heketi service and trying to start again, it fails with message:
"Heketi terminated while performing one or more operations. Server will not start as long as pending operations are present in the db."

Using environment variable HEKETI_IGNORE_STALE_OPERATIONS=true has no effect for the startup, it still fails with the above message.

The only way to correct this is to export the database to json and manually edit/delete the pending operations, and then import it again. 

### Expected/desired behavior

heketi should not get stuck in a infinite loop no matter what kind of errors the gluster commands might return while trying to create the volumes.
heketi should be able to start even if there are pending operations, when using HEKETI_IGNORE_STALE_OPERATIONS=true as documented.
It should be possible to delete heketi volumes that no longer exists in gluster, without manually editing the database.

### Details on how to reproduce (minimal and precise)

Not reliably reproducible. Corruption only happens when some host in the gluster cluster fails to perform the volume creation operations properly, but it's not as simple as just shutting down a peer host. Don't know exactly why it fails sometimes, the gluster cluster is operational according to all available tools.

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): 
v6.0.0

- Operating system used: 
Red Hat Enterprise Linux Server release 7.4

- Heketi compiled from sources, as a package (rpm/deb), or container: 
rpm package heketi-6.0.0-1.el7.x86_64 running standalone on a host
- glusterfs-3.12 is running on 3 separate dedicated hosts outside of openshift

### Other useful information

startup messages from journald:

`
Jun 04 14:27:19 std-gluster-01 systemd[1]: Starting Heketi Server...
Jun 04 14:27:19 std-gluster-01 heketi[28339]: Heketi 6.0.0
Jun 04 14:27:19 std-gluster-01 heketi[28339]: [heketi] INFO 2018/06/04 14:27:19 Loaded ssh executor
Jun 04 14:27:20 std-gluster-01 heketi[28339]: [heketi] ERROR 2018/06/04 14:27:20 /src/github.com/heketi/heketi/apps/glusterfs/app.go:150: Heketi terminated while performing one or more operations. Server will not start as long as pending operations are present in the db.
Jun 04 14:27:20 std-gluster-01 heketi[28339]: [heketi] INFO 2018/06/04 14:27:20 Please refer to the Heketi troubleshooting documentation for more information on how to resolve this issue.
Jun 04 14:27:20 std-gluster-01 heketi[28339]: panic: Heketi terminated while performing one or more operations. Server will not start as long as pending operations are present in the db.
Jun 04 14:27:20 std-gluster-01 heketi[28339]: goroutine 1 [running]:
Jun 04 14:27:20 std-gluster-01 heketi[28339]: github.com/heketi/heketi/apps/glusterfs.NewApp(0x2347160, 0xc42017c210, 0x0)
Jun 04 14:27:20 std-gluster-01 heketi[28339]: /builddir/build/BUILD/heketi-6.0.0/src/github.com/heketi/heketi/apps/glusterfs/app.go:154 +0x74b
Jun 04 14:27:20 std-gluster-01 heketi[28339]: main.main()
`
[heketi.db.bad.gz](https://github.com/heketi/heketi/files/2072835/heketi.db.bad.gz)

**Comment by hakanisaksson** [comment]
I notice that the new 7.0.0 version should take care of most of these issues, i.e. the env variable and removing pending operations.

**Comment by raghavendra-talur** [comment]
The remove pending operations command is not performing the job completely. We will fix it soon, meanwhile you will be able to get heketi running by just using the env variable.

**Comment by hakanisaksson** [comment]
Note, happened again, this time on v7.0.0, have been running on that version for about a week.
Logs from heketi in a loop going over the same pending queue entries again and again:
`Jun 20 07:26:29 std-gluster-01 heketi[18128]: [negroni] Completed 200 OK in 475.854µs
Jun 20 07:26:29 std-gluster-01 heketi[18128]: [negroni] Started GET /queue/fec86116aa0f8de3deee964e828c13c4
Jun 20 07:26:29 std-gluster-01 heketi[18128]: [negroni] Completed 200 OK in 123.529µs
Jun 20 07:26:30 std-gluster-01 heketi[18128]: [negroni] Started GET /queue/de4d6f1644531fe6a38d8d9d9299e625
Jun 20 07:26:30 std-gluster-01 heketi[18128]: [negroni] Completed 200 OK in 120.962µs
Jun 20 07:26:30 std-gluster-01 heketi[18128]: [negroni] Started GET /queue/255a07db08f239ee8368d76c15b6bde5
Jun 20 07:26:30 std-gluster-01 heketi[18128]: [negroni] Completed 200 OK in 116.63µs
Jun 20 07:26:30 std-gluster-01 heketi[18128]: [negroni] Started GET /queue/fec86116aa0f8de3deee964e828c13c4
Jun 20 07:26:30 std-gluster-01 heketi[18128]: [negroni] Completed 200 OK in 162.11µs
Jun 20 07:26:31 std-gluster-01 heketi[18128]: [negroni] Started GET /queue/de4d6f1644531fe6a38d8d9d9299e625
Jun 20 07:26:31 std-gluster-01 heketi[18128]: [negroni] Completed 200 OK in 137.587µs
Jun 20 07:26:31 std-gluster-01 heketi[18128]: [negroni] Started GET /queue/255a07db08f239ee8368d76c15b6bde5
Jun 20 07:26:31 std-gluster-01 heketi[18128]: [negroni] Completed 200 OK in 142.516µs
Jun 20 07:26:31 std-gluster-01 heketi[18128]: [negroni] Started GET /queue/fec86116aa0f8de3deee964e828c13c4
Jun 20 07:26:31 std-gluster-01 heketi[18128]: [negroni] Completed 200 OK in 122.828µs
Jun 20 07:26:32 std-gluster-01 heketi[18128]: [negroni] Started GET /queue/de4d6f1644531fe6a38d8d9d9299e625
Jun 20 07:26:32 std-gluster-01 heketi[18128]: [negroni] Completed 200 OK in 146.145µs
Jun 20 07:26:32 std-gluster-01 heketi[18128]: [negroni] Started GET /queue/255a07db08f239ee8368d76c15b6bde5
Jun 20 07:26:32 std-gluster-01 heketi[18128]: [negroni] Completed 200 OK in 125.276µs
Jun 20 07:26:32 std-gluster-01 heketi[18128]: [negroni] Started GET /queue/fec86116aa0f8de3deee964e828c13c4
Jun 20 07:26:32 std-gluster-01 heketi[18128]: [negroni] Completed 200 OK in 117.576µs
Jun 20 07:26:33 std-gluster-01 heketi[18128]: [negroni] Started GET /queue/de4d6f1644531fe6a38d8d9d9299e625
Jun 20 07:26:33 std-gluster-01 heketi[18128]: [negroni] Completed 200 OK in 158.56µs
Jun 20 07:26:33 std-gluster-01 heketi[18128]: [negroni] Started GET /queue/255a07db08f239ee8368d76c15b6bde5
Jun 20 07:26:33 std-gluster-01 heketi[18128]: [negroni] Completed 200 OK in 130.395µs
Jun 20 07:26:33 std-gluster-01 heketi[18128]: [negroni] Started GET /queue/fec86116aa0f8de3deee964e828c13c4
`
Can also confirm that the nifty "heketi db delete-pending-entries" command did not create a database that could be started. Had to clear the pending entries manually as before.

**Comment by ajmulhollan1** [comment]
I've also just had the same issue running on version 7.0.0 where by heketi can't recover from the pending operations problem.

The Env Var has enabled it to keep starting at least, but we need a more permanent fix. 

I also cannot see the `heketi db delete-pending-entries` command that is referred to in the above comment.

**Comment by hakanisaksson** [comment]
@ajmulhollan1 it should be in the heketi binary, try "/usr/bin/heketi db --help"

**Comment by ajmulhollan1** [comment]
Found it @hakanisaksson but I got a further error - not sure if its related to the initial error;

```[heketi] ERROR 2018/06/21 11:55:06 /src/github.com/heketi/heketi/apps/glusterfs/dbcommon.go:173: Unable to open database: open : no such file or directory
Unable to open database: open : no such file or directory```

**Comment by xiaomage008** [comment]
Same issue occurred, any solution for this issue?

**Comment by xiaomage008** [comment]
@ajmulhollan1  Maybe ```https://github.com/heketi/heketi/blob/master/docs/troubleshooting.md``` can help you. According to the instruction link given, my issue fixed.

**Comment by jianzi123** [comment]
@xiaomage008 I would like to ask some questions, 
```
        "735190a22980229faf0a4429d7ec8bcf": {
            "Info": {
                "id": "735190a22980229faf0a4429d7ec8bcf",
                "path": "/var/lib/heketi/mounts/vg_9cad1d13f9d6e900ad05ada612af61bc/brick_735190a22980229faf0a4429d7ec8bcf/brick",
                "device": "9cad1d13f9d6e900ad05ada612af61bc",
                "node": "4a32e1474d22af079aee147c57012104",
                "volume": "640a8b6b1e5364832de7228e3a938997",
                "size": 1048576
            },
            "TpSize": 1048576,
            "PoolMetadataSize": 8192,
            "Pending": {
                "Id": "f96eabc537c5d5229597f69eda614706"
            }
        },
```
To recover the glusterfs, remove "735190a22980229faf0a4429d7ec8bcf" or just remove 
```
            "Pending": {
                "Id": "f96eabc537c5d5229597f69eda614706"
            }
```
Thank you for the help.

**Comment by jianzi123** [comment]
@hakanisaksson I would try it, thanks.

**Comment by phlogistonjohn** [comment]
Stale issue. Closing.
