### ISSUE TITLE
Heketi doesn't remove brick from node

### ISSUE THREAD

**Issue by nelsonfassis** [heketi/heketi#1210]
### Kind of issue

> Uncomment only one of these:
> 
Bug
> Feature request

### Observed behavior
Trying to create new volumes fail, stating:
```
 [heketi] DEBUG 2018/06/05 14:58:11 /src/github.com/heketi/heketi/apps/glusterfs/volume_entry_allocate.go:195: Maximum number of bricks reached
```
Checking bricks on node, I would find multiple bricks and logical volumes on my nodes, while I have only 6 PV created with a x3 replica, meaning, only 18 should exist across my cluster. 

Logical Volumes state I'm using more space than I'm actually using and more bricks than I'm allowed to (where can I find those settings?) and I'm unable to create new volumes, preventing new apps to be created.

### Expected/desired behavior
PVC's removed from my cluster, would delete the PV object, which would also delete the Heketi volume and gluster volume, umount and remove this volume from my /etc/fstab and delete logical volume, recycling the space for new volumes. 

### Details on how to reproduce (minimal and precise)
I have a Heketi installed as a standalone instance on one of my Kubernetes nodes (on Centos, not inside any container/pod/deployment), 4 Glusterfs nodes with one small raw disk on each (40gb each).

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): v6.0.0
- Operating system used: CentOS 7
- Heketi compiled from sources, as a package (rpm/deb), or container: rpm
- If container, which container image: 
- Using kubernetes, openshift, or direct install: Kubernetes to access and create volumes, direct install for both gluster and heketi.
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: Gluster is running in the same node as Kubernetes, but as a service, outside of Kubernetes. 
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): 

### Other useful information
I've have already exported the heketi.db, cleaned old volumes that only exist on heketi (they don't show up on gluster and are not being used by any container, obviously). Didn't fix the issue. 
After doing so, I am not able to load heketi-cli topology info, but I'm still able to list volumes and get info about them. Heketi can still be connected and other than the main issue, I don't think there is anything else wrong. I still have the heketi.db backup wich works fine. with topology info, but shows many volumes that don't exist on gluster.

**Comment by phlogistonjohn** [comment]
No updates in a few months. Closing. Please reopen if this issue is still relevant to you.
