### ISSUE TITLE
Add request/response counts to Prometheus metrics collection

### ISSUE THREAD

**Issue by nixpanic** [heketi/heketi#1211]
### Kind of issue

Feature request

### Observed behavior

The Prometheus metrics provide details about the storage environment, not about the counts of requests, their success/failure rate and maybe even latency.

### Expected/desired behavior

For identifying issues with heketi, it would be very useful to have statistics about the number of request and if they are succeeding. It probably makes sense to collect these details for each operation that the API supports.

### Other useful information

#1068 introduced metrics collection with Prometheus.

From [Online-serving systems](https://prometheus.io/docs/practices/instrumentation/#online-serving-systems) in the Prometheus "guidelines for instrumenting your code":

> An online-serving system is one where a human or another system is expecting an immediate response. For example, most database and HTTP requests fall into this category.
> 
> The key metrics in such a system are the number of performed queries, errors, and latency. The number of in-progress requests can also be useful.

**Comment by phlogistonjohn** [comment]
Stale issue. Closing.
