### ISSUE TITLE
No clusters configured

### ISSUE THREAD

**Issue by chuck54430** [heketi/heketi#1214]
My machine is down,After started the machine,My Heketi can not start.I do not known how to slave it.
```
[root@ecp-master01 heketi]# ./heketi --config=heketi.json
Heketi v6.0.0
[heketi] INFO 2018/06/07 10:18:31 Loaded ssh executor
[heketi] INFO 2018/06/07 10:18:31 Block: New Block Hosting Volume size 500 GB
[heketi] INFO 2018/06/07 10:18:31 GlusterFS Application Loaded
Listening on port 18080
[negroni] Started POST /volumes
[negroni] Started POST /volumes
[heketi] ERROR 2018/06/07 10:18:37 /src/github.com/heketi/heketi/apps/glusterfs/app_volume.go:116: No clusters configured
[negroni] Completed 400 Bad Request in 1.468673ms
[heketi] ERROR 2018/06/07 10:18:37 /src/github.com/heketi/heketi/apps/glusterfs/app_volume.go:116: No clusters configured
[negroni] Completed 400 Bad Request in 1.277745ms
[negroni] Started DELETE /volumes/0bdfac5e1e1c94b4d94939d4fa0106e0
[negroni] Completed 404 Not Found in 147.504µs
[negroni] Started POST /volumes
[negroni] Started POST /volumes
[heketi] **ERROR 2018/06/07 10:18:52 /src/github.com/heketi/heketi/apps/glusterfs/app_volume.go:116: No clusters configured**
[negroni] Completed 400 Bad Request in 487.079µs
[heketi] ERROR 2018/06/07 10:18:52 /src/github.com/heketi/heketi/apps/glusterfs/app_volume.go:116: No clusters configured
[negroni] Completed 400 Bad Request in 441.787µs
```

**Comment by phlogistonjohn** [comment]
This seems like it might mean your database did not persist across reboot. Can you please describe how you've deployed heketi?

When heketi server is stopped you can run `heketi db export` to see the contents of the db exported to json.

**Comment by jianzi123** [comment]
@chuck54430 I have the same problems, have you fix the problem, or you rebuild it.

**Comment by chuck54430** [comment]
I deployed heketi with cmd,  `heketi --configure=XXX`   @phlogistonjohn
I could not fix it,I redeployed it at another three machines. @jianzi123 
Someone say it is likely because the glusterfs is conflict to docker.

**Comment by chuck54430** [comment]
My question was also happened after my machine restarted. My heketi is not running in container,I desploy it in physical machine.Now i desploy heketi&glusterfs in another three physical machines,but i dare not restart machines to test the question.

**Comment by jianzi123** [comment]
That would be terrible, I would like change db file to redis or mysql to realize the high-ability, but out team' target is not in here.

**Comment by jianzi123** [comment]
@chuck54430 I have look through the code, and found that it use the kubernetes secret to save the db; but backup dir is mount by secret and by default is 420; can not op it; so I change the heketi-start.sh change backup dir to /tmp and then it works.

**Comment by phlogistonjohn** [comment]
Based on the discussion here it sounds like you are deploying heketi in a bespoke manner. I strongly suggest looking into the [gluster-kubernetes project](http://github.com/gluster/gluster-kubernetes) which has a predetermined method of persisting the heketi db on a gluster volume.

If you must deploy heketi in a different manner you will have to ensure the db is persisted yourself and that's out of the direct control of the project.

Hopefully, this answer is satisfactory. I will close the issue. If you think additional discussion is needed please feel free to reopen this issue.
