### ISSUE TITLE
space not consumable

### ISSUE THREAD

**Issue by davidkarlsen** [heketi/heketi#1215]
### Kind of issue
bug

### Observed behavior

All space consumed - not able to create volumes, even though there are no volumes (besides the heketidbstorage)

### Expected/desired behavior
Be able to create volumes

### Details on how to reproduce (minimal and precise)
Hard to reproduce I guess, but happened after some node boots.

### Information about the environment:
Used https://github.com/heketi/heketi/blob/master/docs/admin/install-kubernetes.md as guide.

### Other useful information

If only one volume of 2g is in use (for heketi itself). What is the rest of the brick space used for. The bricks are 100G

```
sh-4.4# heketi-cli node list
Id:9ba6c5c77167aa69881bc9aa4b5ae628     Cluster:4ca465f54884c7d8d5ac0b11941e4376
Id:ec489c1dd32bf13b3ccaa24ae896650d     Cluster:4ca465f54884c7d8d5ac0b11941e4376
sh-4.4# heketi-cli node info 9ba6c5c77167aa69881bc9aa4b5ae628
Node Id: 9ba6c5c77167aa69881bc9aa4b5ae628
State: online
Cluster Id: 4ca465f54884c7d8d5ac0b11941e4376
Zone: 1
Management Hostname: app02.lan.davidkarlsen.com
Storage Hostname: 192.168.3.3
Devices:
Id:14e6b3bee2d4dd9874695f552bb71e95   Name:/dev/app02-vg/gluster-standardState:online    Size (GiB):99      Used (GiB):98      Free (GiB):1       Bricks:1       
sh-4.4# heketi-cli node info ec489c1dd32bf13b3ccaa24ae896650d
Node Id: ec489c1dd32bf13b3ccaa24ae896650d
State: online
Cluster Id: 4ca465f54884c7d8d5ac0b11941e4376
Zone: 1
Management Hostname: app04
Storage Hostname: 192.168.3.5
Devices:
Id:d041bb58aa81f9507f4e1611f2ae5bc5   Name:/dev/app04-vg/gluster-standardState:online    Size (GiB):99      Used (GiB):98      Free (GiB):1       Bricks:1       
sh-4.4# 

sh-4.4# heketi-cli volume list
Id:4a5cf9a00892fda99ab9d8ecf315001a    Cluster:4ca465f54884c7d8d5ac0b11941e4376    Name:heketidbstorage
sh-4.4# heketi-cli volume info 4a5cf9a00892fda99ab9d8ecf315001a
Name: heketidbstorage
Size: 2
Volume Id: 4a5cf9a00892fda99ab9d8ecf315001a
Cluster Id: 4ca465f54884c7d8d5ac0b11941e4376
Mount: 192.168.3.3:heketidbstorage
Mount Options: backup-volfile-servers=192.168.3.5
Block: false
Free Size: 0
Block Volumes: []
Durability Type: replicate
Distributed+Replica: 2
sh-4.4# 

topology:

Cluster Id: 4ca465f54884c7d8d5ac0b11941e4376

    File:  true
    Block: true

    Volumes:

        Name: heketidbstorage
        Size: 2
        Id: 4a5cf9a00892fda99ab9d8ecf315001a
        Cluster Id: 4ca465f54884c7d8d5ac0b11941e4376
        Mount: 192.168.3.3:heketidbstorage
        Mount Options: backup-volfile-servers=192.168.3.5
        Durability Type: replicate
        Replica: 2
        Snapshot: Disabled

                Bricks:
                        Id: 0c357d5fb6da1cd0758f3d32f7171796
                        Path: /var/lib/heketi/mounts/vg_14e6b3bee2d4dd9874695f55
2bb71e95/brick_0c357d5fb6da1cd0758f3d32f7171796/brick
                        Size (GiB): 2
                        Node: 9ba6c5c77167aa69881bc9aa4b5ae628
                        Device: 14e6b3bee2d4dd9874695f552bb71e95

                        Id: cf5fbedae71edec6640d326283f91da6
                        Path: /var/lib/heketi/mounts/vg_d041bb58aa81f9507f4e1611
f2ae5bc5/brick_cf5fbedae71edec6640d326283f91da6/brick
                        Size (GiB): 2
                        Node: ec489c1dd32bf13b3ccaa24ae896650d
                        Device: d041bb58aa81f9507f4e1611f2ae5bc5


    Nodes:

        Node Id: 9ba6c5c77167aa69881bc9aa4b5ae628
        State: online
        Cluster Id: 4ca465f54884c7d8d5ac0b11941e4376
        Zone: 1
        Management Hostnames: app02.lan.davidkarlsen.com
        Storage Hostnames: 192.168.3.3
        Devices:
                Id:14e6b3bee2d4dd9874695f552bb71e95   Name:/dev/app02-vg/gluster
-standardState:online    Size (GiB):99      Used (GiB):98      Free (GiB):1     
  
                        Bricks:
                                Id:0c357d5fb6da1cd0758f3d32f7171796   Size (GiB)
:2       Path: /var/lib/heketi/mounts/vg_14e6b3bee2d4dd9874695f552bb71e95/brick_
0c357d5fb6da1cd0758f3d32f7171796/brick

        Node Id: ec489c1dd32bf13b3ccaa24ae896650d
        State: online
        Cluster Id: 4ca465f54884c7d8d5ac0b11941e4376
        Zone: 1
        Management Hostnames: app04
        Storage Hostnames: 192.168.3.5
        Devices:
                Id:d041bb58aa81f9507f4e1611f2ae5bc5   Name:/dev/app04-vg/gluster
-standardState:online    Size (GiB):99      Used (GiB):98      Free (GiB):1     
  
                        Bricks:
                                Id:cf5fbedae71edec6640d326283f91da6   Size (GiB)
:2       Path: /var/lib/heketi/mounts/vg_d041bb58aa81f9507f4e1611f2ae5bc5/brick_
cf5fbedae71edec6640d326283f91da6/brick


heketi-cli volume create --size 10 --replica 2
Error: Failed to allocate new volume: No space

I see this in the gluster logs:
[2018-06-08 08:59:22.954959] W [rpc-clnt.c:1739:rpc_clnt_submit] 0-heketidbstorage-client-0: error returned while attempting to connect to host:(null), port:0


```

**Comment by DanyC97** [comment]
which heketi version are you using ?

**Comment by davidkarlsen** [comment]
heketi --version
Heketi v7.0.0-8-gbe187e4

I did a 
heketi-cli device resync d041bb58aa81f9507f4e1611f2ae5bc5 
heketi-cli device resync 14e6b3bee2d4dd9874695f552bb71e95
and then space was available again.

BUT 
heketi-cli topology info says:

                Id:14e6b3bee2d4dd9874695f552bb71e95   Name:/dev/app02-vg/gluster-standardState:online    Size (GiB):196     Used (GiB):114     Free (GiB):81       <-- 196 G!

root@app02:/var/log/glusterfs# lvscan |grep glus
  ACTIVE            '/dev/app02-vg/gluster-standard' [100.00 GiB] inherit <-- 100G
root@app02:/var/log/glusterfs#

**Comment by arminfelder** [comment]
I have the same issue with to loopback device I use for testing:
`
 Node Id: 845cb94a17a6853d067cd114099225de
        State: online
        Cluster Id: 8df1d63ee0926cc58e260aa6922ee94a
        Zone: 1
        Management Hostnames: server2
        Storage Hostnames: xx.xx.xx.xx
        Devices:
                Id:beabc4d04c55daa7a24cbf55cc17194c   Name:/dev/loop200        State:online    Size (GiB):195     Used (GiB):193     Free (GiB):1       
                        Bricks:

        Node Id: a8ecd8e1f468f49fec61bf593ed3526a
        State: online
        Cluster Id: 8df1d63ee0926cc58e260aa6922ee94a
        Zone: 1
        Management Hostnames: server1
        Storage Hostnames: xx.xx.xx.xx
        Devices:
                Id:8b433e7b514e986597316ec90b51aa6a   Name:/dev/loop200        State:online    Size (GiB):195     Used (GiB):193     Free (GiB):1       
                        Bricks:
`

**Comment by phlogistonjohn** [comment]
@arminfelder If you have storage used but no bricks visible in the topology, one thing you may want to check is if there are still pending operations in the db. These pending bricks will still use space.

You can dump the db via `heketi-cli db dump` and look in the json output for "pendingoperations". If there are pending operations under that key, that may explain why you have used space but no bricks visible.

There were also some bugs recently fixed on master around device resync if you ever ran that command.

**Comment by arminfelder** [comment]
@phlogistonjohn thank you for your fast response!, I cleaned up the heketi db, and fixed an issue with a missing debian package and now it works fine

**Comment by phlogistonjohn** [comment]
It sounds like issue has been resolved for @arminfelder but @davidkarlsen has not responded.
@davidkarlsen, if this discussion was satisfactory for you would you please close this issue? If not, would you please retest with the recently release Heketi v8.0.0?
Thanks.

**Comment by devilmind81** [comment]
which packeges was missing?

**Comment by phlogistonjohn** [comment]
Not much activity for months. Additionally, heketi v9 hase auto-cleanup of stale pending ops so if that caused issues it would be resolved by that release.
