### ISSUE TITLE
Provide alternate modes of block hosting volume creation for block volumes

### ISSUE THREAD

**Issue by raghavendra-talur** [heketi/heketi#1217]
### Kind of issue

Feature request

### Observed behavior
We have one option(auto_create_block_hosting_volume) to enable/disable auto creation of hosting volume and one option(block_hosting_volume_size) to decide the size of the auto created hosting volume. 

### Expected/desired behavior
There should be a way to limit capacity of hosting volume to one blockvolume. I propose the following

Provide another option (something like limit_hosting_volume_to_one_blockvolume) which takes 4 values
a. always (when this is set, block_hosting_volume_size becomes irrelevant)
b. preferred (= default yes but user can override with user.heketi* key in volume options during volume create)
b. allowed (= default no, but user can override with user.heketi* key in volume options during volume create)
c. never

### Other useful information
Internally, it would require that  all blockvolumes that are created in this mode will have a flag that is set on both the blockvolume and the hosting volume to indicate that they are paired.

Snapshots of blockvolumes will be allowed only when the blockvolume is in paired with hosting volume.

Deletion of a paired blockvolume would result in automatic deletion of the hosting volume.

**Comment by obnoxxx** [comment]
Can you detail on the user.heketi options to use?

**Comment by phlogistonjohn** [comment]
Probably never going to happen. Closing
