### ISSUE TITLE
how to scale capacity in cluster

### ISSUE THREAD

**Issue by jianzi123** [heketi/heketi#1219]
When the resources are exhausted, how to expand capacity is very necessary, want to know how to do.
Thank you for any help.

**Comment by phlogistonjohn** [comment]
Heketi supports both device add and node add commands [1]. Depending on the set up of your cluster you can choose to expand storage capacity by adding disks to your existing nodes or expand both storage and cluster peers by adding a new node (with storage attached).

Once capacity has been added to you cluster you can start creating new volumes or expand existing volumes as needed. 

If you have any other questions please feel free to ask but please be specific.

[1] Read the heketi man page for the subcommands `heketi-cli device add` and `heketi-cli node add`.

**Comment by jianzi123** [comment]
@phlogistonjohn  I have got it, thanks.

**Comment by phlogistonjohn** [comment]
Sounds like I answered the original request. Closing issue. If you feel that this issue needs additional discussion please reopen the issue.
