### ISSUE TITLE
Failed volume deletes should be resumable

### ISSUE THREAD

**Issue by phlogistonjohn** [heketi/heketi#1220]
### Kind of issue

Feature request

### Observed behavior

In current heketi master a volume delete can fail if some of the volume delete (and brick delete) steps fail, such as failing to unmount a brick. This leaves the volume in the heketi db.
This means the parts of the failed delete are not forgotten by heketi but we now have a non-functional non-deletable volume in the db. This can be removed by modifying the db and manually removing the components but this is an unpleasant process.

### Expected/desired behavior

Running 'heketi-cli volume delete' on a volume that is already partially deleted can succeed.

### Details on how to reproduce (minimal and precise)

Manually remove a volume from gluster using the command line and then attempt to remove said volume from heketi.

**Comment by hakanisaksson** [comment]
Or simply a "force" delete, that don't care if it was "partially" or fully deleted from gluster...
