### ISSUE TITLE
Provide node tags to filter block host selection

### ISSUE THREAD

**Issue by raghavendra-talur** [heketi/heketi#1221]
### Kind of issue

Feature request

### Observed behavior
On a block volume request we pick nodes == to ha count. 

### Expected/desired behavior
It must be possible to filter out some of the nodes based on node tag. For example, if a node is set to be arbiter node by arbiter only node tag, admin might also chose to keep CPU and RAM resources on the node less just like the Storage resources. In such a setup it might be useful to omit arbiter node if ha count could be satisfied after such an omission.

### Other useful information

This issue is filed to record it somewhere. Not sure if we will get around to bringing this feature in heketi.

**Comment by phlogistonjohn** [comment]
As heketi is now in maintenance mode, and only accepting major bug and security related fixes, we do not expect to implement this change.
