### ISSUE TITLE
Add support for blockvolume on arbiter

### ISSUE THREAD

**Issue by phlogistonjohn** [heketi/heketi#1224]
### Kind of issue
Feature request

### Observed behavior
Heketi does not make it easy to use the features of both a block hosting volume along with arbiter volumes.
Currently, if you allow Heketi to create the block hosting volume for you, you can not get an arbiter volume.

If you try to create a block hosting volume manually with the arbiter feature it will work but if you forget to also specify the group gluster-block in the volume options it will lack many of the desired settings for a block hosting volume (this also applies to a non-arbiter block hosting volume created manually).

### Expected/desired behavior

Heketi can make combining these settings easier. Perhaps by:
a) automatically setting the group when --block is specified (if group is not provided in volume options)
b) supporting volume options in a block volume request

or something along those lines.

**Comment by obnoxxx** [comment]
We could also create a setting for options for block hosting volumes that would be applied both for auto-creation or as default options for manual creation of block hosting volumes.....
