### ISSUE TITLE
volume create request with block flag does not set the block-specific volume options

### ISSUE THREAD

**Issue by obnoxxx** [heketi/heketi#1226]
### Kind of issue

Bug

### Observed behavior

`heketi-cli volume create --size=X --block` does not set the `group gluster-block` volume options.
(Corresponding for the API request.)

### Expected/desired behavior

The cli or api request with the block flag should set the volume options.

### Details on how to reproduce (minimal and precise)

Run `heketi-cli volume create --size=<X> --block`.

### Information about the environment:

- Heketi version used (master): 
- Operating system used: fedora
- Heketi compiled from sources, as a package (rpm/deb), or container: source 
- Using kubernetes, openshift, or direct install: local install with mock translator

**Comment by phlogistonjohn** [comment]
This partially overlaps with #1224

**Comment by obnoxxx** [comment]
@phlogistonjohn writes:
> This partially overlaps with #1224

Not really. If it does, then rather by accident of #1224, imho. ;-) We might want to remove the overlapping part from #1224. This one here is a bug that needs fixing independently of arbiter:

* This one here is a bug that the originally intended application of the "group gluster-block" option is not happening if `--block` is specified with `heketi-cli volume create`. This is not related to arbiter per se.
 
* The other is about making it possible or easy to use arbiter. This has two flavors. One is the autocreation of BHV as arbiter volumes, which is currently impossible. And the second is about the manual creation. The measure suggested in #1224, to `automatically setting the group when --block is specified` is actually there in the code, but another patch undoes the effect. That's the generic bug I spotted, which led me to file this issue.

So, I think we should fix this one, and then the other one might be reduced by one aspect. :-)
