### ISSUE TITLE
heketi-cli volume info should list volume options

### ISSUE THREAD

**Issue by obnoxxx** [heketi/heketi#1228]
### Kind of issue

Feature request

### Observed behavior

`heket-cli volume info` does not list the volume options.

### Expected/desired behavior

It would be useful if `heketi-cli volume info` listed the volume options, e.g. to be able to tell an arbiter volume from a normal replica-3.

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master):  master
- Operating system used: fedora 27
- Heketi compiled from sources, as a package (rpm/deb), or container: from sources 
- Using kubernetes, openshift, or direct install: local install with mock executor

**Comment by phlogistonjohn** [comment]
Probably never going to happen. Closing
