### ISSUE TITLE
Allow more than one ssh connection to glusterfs per host

### ISSUE THREAD

**Issue by ateleshev** [heketi/heketi#1232]
### Kind of issue
Feature request

### Observed behavior
Heketi can use only one ssh connect with each glusterfs host.
What do you think about providing ability for users to configure this property?

```
c = make(chan bool, 1)
change to something like this:
c = make(chan bool, s.config.NumConsPerHost)
```
s.config.NumConsPerHost will be able to configure via environment variable.

> /executors/cmdexec/cmdexec.go#L45
```
func (s *CmdExecutor) AccessConnection(host string) {
	var (
		c  chan bool
		ok bool
	)

	s.Lock.Lock()
	if c, ok = s.Throttlemap[host]; !ok {
		c = make(chan bool, s.config.NumConsPerHost)
		s.Throttlemap[host] = c
	}
	s.Lock.Unlock()

	c <- true
}
```

When we create more than 100 volumes and delete some volumes at the same time the performance on the heketi side becomes terrible.

- average time to create about 20 min
- average time to delete about 50 min

We retested it with 10 ssh connections (s.config.NumConsPerHost = 10)

- average time to create about 20 sec
- average time to delete about 2 min

### Information about the environment:
- Heketi (1 pod): v6.0.0
- Kubernetes (3 nodes): v1.10.4
- GlusterFS (3 pods): v4.0.2
- OS: coreos 1745.7.0

**Comment by mak73kur** [comment]
This was our experience as well, async jobs take too long to complete.
Volume take exponentially longer time to bound, starting with concurrent provision for ~10 volumes 1Gi capacity.

**Comment by phlogistonjohn** [comment]
Stale issue. Closing.
