### ISSUE TITLE
Recreating PVCs sometimes results in the endpoints not being created

### ISSUE THREAD

**Issue by alikhajeh1** [heketi/heketi#1233]
### Kind of issue
Bug

### Observed behavior
Users sometimes need to reset a statefulset's data volumes; they would so something like this:
1. Create a statefulset with a PVC and wait for the PV and pod to be ready.
2. Scale the statefulset to 0, and delete the PVC.
3. As soon as the PVC is deleted, scale the statefulset back to 1, the PVC will be recreated, but the pod sometimes fails to start as it complains about the endpoints not existing. It seems like there might be a race condition, where Heketi is deleting the old endpoint, and the new endpoint fails to create as the old one still exists? 

There are two workarounds:
1. The user can create the endpoint manually.
2. The user needs to wait a few minutes before scaling the statefulset back to 1.

### Expected/desired behavior
The endpoint should be available.

### Details on how to reproduce (minimal and precise)
See above.

### Information about the environment:
- Heketi version used (e.g. v6.0.0 or master): v5
- Operating system used: Centos
- Heketi compiled from sources, as a package (rpm/deb), or container: container
- If container, which container image: heketi/heketi:5
- Using kubernetes, openshift, or direct install: openshift
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: inside
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): openshift-ansible

**Comment by alikhajeh1** [comment]
Anyone else have this issue?

**Comment by RBlaine95** [comment]
I've had this problem occur multiple times in OpenShift Origin 3.9, even when not using a StatefulSet.

Sometimes the endpoint isn't created, other times neither the endpoint nor the service is created.

**Comment by phlogistonjohn** [comment]
@alikhajeh1 this sounds like it could be an issue with the volume provisioner rather than Heketi itself, similar to the suggestion @RBlaine95 made. If you are using OpenShift you can check on the status of the PVC by running `oc describe pvc/mypvc`. If you paste the output of that command into the issue that would help us determine if this is a heketi issue or a provisioner issue. Thanks.

**Comment by phlogistonjohn** [comment]
Issue has been idle for many months. Since I think this is a provisioner issue rather than a Heketi issue I'm going to close this. Please feel free to reopen this issue if you think it requires additional discussion here.
