### ISSUE TITLE
Heketi should find difference between db state and gluster state and log it

### ISSUE THREAD

**Issue by raghavendra-talur** [heketi/heketi#1234]
### Kind of issue
At the very minimum it should log it. Possibly more, we could try to build db using the content.

> Feature request

### Expected/desired behavior
It would make it very easy to debug issues of db going out of sync if this information is available.

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): 
- Operating system used: 
- Heketi compiled from sources, as a package (rpm/deb), or container: 
- If container, which container image: 
- Using kubernetes, openshift, or direct install: 
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: 
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom):

**Comment by phlogistonjohn** [comment]
@raghavendra-talur I agree. At the very least we ought to come up with a rough design and scoping and see how much, if any, we can do for the next milestone.

**Comment by phlogistonjohn** [comment]
@raghavendra-talur do you think the db check / state examine gluster commands cover this issue or is it not covered by this?

**Comment by raghavendra-talur** [comment]
@phlogistonjohn yes, this is the issue filed to track "state examine gluster" commands.
#1474 is part of the work. More needs to be done.

**Comment by phlogistonjohn** [comment]
This is done. If we find things missing from the core commands they should be filed as separate issues. Closing.
