### ISSUE TITLE
Disk symlink not accepted by heketi

### ISSUE THREAD

**Issue by chandidas** [heketi/heketi#1246]
As the device names are not persistence across reboot, I was using symlink of the disk to configure Heketi topology. 

In my setup, both Heketi (version 5) and GlusterFS  (version 3.12.1) runs a Pods. symlink "/dev/disk/by-path/pci-0000:00:10.0-scsi-0:0:1:0" was working perfectly for us. However, now we want to move to latest version of Heketi and it looks like Heketi does not accept this symlink as device configuration. Among all, this is the only symlink ("/dev/disk/by-path/pci-0000:00:10.0-scsi-0:0:1:0") which is available for a raw disk.

I need your help/suggestion here.
 1) What alternative mechanism community is following to provide persistence name of a raw disk into Heketi Topology. 
 2) Ideally validation check is good, but can we skip the validation logic on the disk path

**Comment by phlogistonjohn** [comment]
I think this is due the the colons in the path being rejected by the device path validation.

Would it be possible, as a temporary workaround, to create symlinks without colons? Perhaps via udev rules (host rules should apply to the gluster pods as /dev is mounted inside the container)?

**Comment by nixpanic** [comment]
On Mon, Jul 02, 2018 at 11:22:58AM -0700, John Mulligan wrote:
> I think this is due the the colons in the path being rejected by the
> device path validation.

If that is the cause, using /dev/disk/by-id/... might be an alternative
too.

**Comment by chandidas** [comment]
@nixpanic Almost in all the virtualized environments (vSphere, openstack etc) "by-path" symlink gets created  for 'raw disks' by inbuilt udev rules. However, we see that "by-id" is not available in most of the cases.

@phlogistonjohn Yes. exploring to writing custom udev rules to create symlink for the disk. But, in some environments, we do not get sufficient unique disk attributes to create right rule.
It would be good, if Heketi takes the device name (like ```/dev/sdb```) and create it's own label to uniquely identify the disk across reboot.

We also explored one more workaround by creating 'logical volume' (```lvcreate```) out of the disk and use this as disk in Heketi topology. Want to know communities opinion on this approach.
