### ISSUE TITLE
Does heketi support stripe volume type? Just like gluster stripe volume..stripe volume has a good performance on writing big file.

### ISSUE THREAD

**Issue by ALiBaBa-Jimmy** [heketi/heketi#1252]
### Kind of issue

> Uncomment only one of these:
> 
> Bug
> Feature request

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): 
- Operating system used: 
- Heketi compiled from sources, as a package (rpm/deb), or container: 
- If container, which container image: 
- Using kubernetes, openshift, or direct install: 
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: 
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom):

**Comment by nixpanic** [comment]
The stripe type of volume is not recommended to be used, and has been deprecated within Gluster. The alternative and more stable/functional solution is to use sharding. By enabling the volume option `features.shard` you can use it. See http://blog.gluster.org/introducing-shard-translator/ for more details.

**Comment by phlogistonjohn** [comment]
To add to what @nixpanic wrote, the volume options can be passed through heketi to gluser by specifying them in the storageClass. ([storageClass example](https://www.humblec.com/glusterfs-dynamic-provisioner-set-glusterfs-volume-options-via-storageclass-parameter/))

@ALiBaBa-Jimmy  If this is a sufficient answer for you can we close this issue?

**Comment by phlogistonjohn** [comment]
No reaction from original reporter in over a month. As @nixpanic wrote this is deprecated in gluster and probably not desirable for heketi to support. Closing.
