### ISSUE TITLE
Heketi executors with DenyEscalatingExec admission control 

### ISSUE THREAD

**Issue by chandidas** [heketi/heketi#1254]
Heketi currently support two executor types: kubexec and sshexec. 
In our setup, both GlusterFS (v3.12.1) and Heketi(v5) runs as Pods and Heketi is configured to use kubexec to interact with GlusterFS which runs as privileged pod. Heketi fails to configure glusterfs if we enable ```DenyEscalatingExec``` admission control to deny exec and attach commands to privileged Pods.

Could you suggest any alternative/workaround to this if we want to impose ```DenyEscalatingExec``` admission control.

**Comment by phlogistonjohn** [comment]
Stale issue. Closing.
