### ISSUE TITLE
Add api & command to query operations

### ISSUE THREAD

**Issue by phlogistonjohn** [heketi/heketi#1265]
### Kind of issue

Feature request (quality of life / debugging)

### Observed behavior

It is helpful to know if:
* Heketi is working on any operations
* The db contains any stale operations
* A summary of the operations
* What volumes, bricks, etc are pending

Currently this can only be determined by examining the db dumps.

### Expected/desired behavior

Add APIs and command line commands to:
* Query operations count: total, live and stale
* A command to dump and summarize operations summarizing the kind of operation
* Command line switch such as --show-pending for commands such as 'topology info' and 'volume list' in order to show pending items in addition to finalized ones.

**Comment by obnoxxx** [comment]
This was fixed by PR #1304
