### ISSUE TITLE
Log all Id Not found errors

### ISSUE THREAD

**Issue by raghavendra-talur** [heketi/heketi#1269]
### Kind of issue
When heketi does not find a id in the db, it quits processing. It also does not report back the id which wasn't found.

> Bug

### Observed behavior
Id which wasn't found isn't logged.

### Expected/desired behavior
Id which wasn't found should be logged.

**Comment by phlogistonjohn** [comment]
I discussed this with @ansiwen recently, partially in the context of his errors PR (PR #1348).
Instead of just logging them, we might consider treating Id Not found conditions with an error type. Hypothetically we could do something like:
```golang
type IdNotFoundError struct {
    Type string
    Id string
}

// check for error
if _, ok := err.(IdNotFoundError); ok {
   // return 404...
}
   
```

OR
```golang
type IdNotFoundError interface {
    Source() string
    Id() string
}

type VolumeNotFoundError struct {
   // ...
}

```


We should discuss some more IMO.

**Comment by phlogistonjohn** [comment]
I do not think we will pursue this item. Closing issue. Please reopen if this is still relevant.
