### ISSUE TITLE
Change how sizes of automatically created block hosting volumes are created

### ISSUE THREAD

**Issue by phlogistonjohn** [heketi/heketi#1312]
### Kind of issue

Feature request

### Observed behavior

The changes made in PRs #1287 and #1310 adjust the total usable size of a block hosting volume by reserving some of the raw capacity as overhead. Thus if you create a block hosting volume of 100GiB then a block volume of 100GiB is too large to be hosted in that volume.

### Expected/desired behavior

What I suggest is the behavior around auto creating block hosting volumes is adjusted so that when a value is set for the parameter `block_hosting_volume_size` that it creates a block hosting volume capable of containing a block volume of the specified size. IOW, we'd increase the size of the block hosting volume by the same percentage as that of the reserved overhead. For example, a value of 100 would create  a block hosting volume of 103GiB so that we could store a 100GiB block volume within it.

**Comment by phlogistonjohn** [comment]
@obnoxxx @raghavendra-talur  any opinions? If this is a good idea should we add it to a milestone? If not, we should just close this.

**Comment by obnoxxx** [comment]
I like the idea.
We can try that for release 9, if you agree. If not move it to future, please.

**Comment by obnoxxx** [comment]
This *might* be a "good first issue". Putting the label. It might also rather be a "good second issue" or so... not sure -- @phlogistonjohn feel free to remove that label again... ;-)

**Comment by phlogistonjohn** [comment]
As heketi is now in maintenance mode, and only accepting major bug and security related fixes, we do not expect to implement this change.
