### ISSUE TITLE
Implement expansion for block-volumes

### ISSUE THREAD

**Issue by obnoxxx** [heketi/heketi#1319]
### Kind of issue

Feature request

### Desired behavior

gluster-block can now change (grow) the size of a block-volume:

https://github.com/gluster/gluster-block/pull/63
https://github.com/gluster/gluster-block/commit/cfa7677b1ee064978aa8222928ce05e2ba48e225

This should now be exposed through a block-volume expand functionality in heketi.

**Comment by phlogistonjohn** [comment]
Fixed by PR #1702 and associated PRs. Closing.
