### ISSUE TITLE
Heketi should put a identifier on gluster volumes it creates

### ISSUE THREAD

**Issue by raghavendra-talur** [heketi/heketi#1322]
### Kind of issue
Feature request

### Expected/desired behavior
Heketi should put a marker on gluster volumes that creates by setting a user.heketi.<tag> so that it can be used later for other needs.

**Comment by nixpanic** [comment]
The `user.heketi` meta data could have the `volume_id` that Heketi uses internally, or maybe even a http(s)://<service-name>/volumes/<volume-id> URL?
