### ISSUE TITLE
About disabling snapshots and the names of volumes  

### ISSUE THREAD

**Issue by legalishomo** [heketi/heketi#1327]
**When creating a volume, you want to disable snapshots, and the name of the volume wants to be defined by itself.
  I looked up the document and found no relevant parameters.
  I'm heketi(heketi-cli v7.0.0-129-g4c7d19c) running on kubernetes(kubeadmin GitVersion:"v1.11.2").**

### my glusterfs  class yaml

> apiVersion: storage.k8s.io/v1beta1
> kind: StorageClass
> metadata:
>   name: glusterfs-storage
> provisioner: kubernetes.io/glusterfs
> parameters:
>   resturl: "http://10.244.24.2:8080"
>   restuser: "admin"
>   restuserkey: "LAcGjTrRF4"
>   volumetype: "replicate:3"

### my  gluster pvc yaml

> apiVersion: v1
> kind: PersistentVolumeClaim
> metadata:
>  name: gluster-jenkins
>  annotations:
>    volume.beta.kubernetes.io/storage-class: glusterfs-storage
> spec:
>  accessModes:
>  \- ReadWriteOnce
>  resources:
>    requests:
>      storage: 500Gi 
>  storageClassName: gluster-jenkins

### heketi topology info
 

> Volumes:
> 
> 	Name: vol_5aaf150336634564a37d22cc964dbfe8
> 	Size: 500
> 	Id: 5aaf150336634564a37d22cc964dbfe8
> 	Cluster Id: f067f2e69d07cda40fe11f94e5a17afe
> 	Mount: 192.168.20.159:vol_5aaf150336634564a37d22cc964dbfe8
> 	Mount Options: backup-volfile-servers=192.168.20.157,192.168.20.158
> 	Durability Type: replicate
> 	Replica: 3
> 	Snapshot: Enabled
> 	Snapshot Factor: 1.00
>             ..........
> 	Name: heketidbstorage
> 	Size: 2
> 	Id: ba5603a42544726432d832729cafbbad
> 	Cluster Id: f067f2e69d07cda40fe11f94e5a17afe
> 	Mount: 192.168.20.159:heketidbstorage
> 	Mount Options: backup-volfile-servers=192.168.20.157,192.168.20.158
> 	Durability Type: replicate
> 	Replica: 3
> 	Snapshot: Disabled
>            ....................

**The first volume was created by me. I like the second volume, disable snapshots and define volume names.**

**Comment by nixpanic** [comment]
The Heketi API supports creating volumes with snapshot disabled, but it
seems none of the provisioners expose the option in the StorageClass.

You could create a volume with `heketi-cli` and set the
`--snapshot-factor` to < 1.0.

client/cli/go/cmds/volume.go:
182                 if snapshotFactor > 1.0 {
183                         req.Snapshot.Factor = float32(snapshotFactor)
184                         req.Snapshot.Enable = true
185                 }
186 

But, this might not work as it could be that there is a check for > 1.0
according to the help text:

      --snapshot-factor float
	Optional: Amount of storage to allocate for snapshot support.
	Must be greater 1.0.  For example if a 10TiB volume requires 5TiB of
	snapshot storage, then snapshot-factor would be set to 1.5.  If the
	value is set to 1, then snapshots will consume the storage allocated (default 1)

An option to disable snapshot through the StorageClass can be requested.
The best place would be to do it in this Kubernetes project:
  https://github.com/kubernetes-incubator/external-storage/tree/master/gluster/file

**Comment by phlogistonjohn** [comment]
Custom names are supported by heketi, and is supported by k8s provisioner (but it adds its own stuff). Any other enhancements should be requested in the repos for the provisioner in kubernetes.
Feel free to reopen if you feel more discussion here is needed.
