### ISSUE TITLE
Create an API/CLI to copy and migrate block-volume between block-hosting volumes

### ISSUE THREAD

**Issue by obnoxxx** [heketi/heketi#1330]
### Kind of issue

Feature request

### Problem

Sometimes, you need to move a block volume (BV) from one block-hosting volume (BHV) to a different block hosting volume in order to rearrange space. E.g. free up some space by consolidating all BV  from two BHVs to a single BHV and delete the empty BHV afterwards. Or you might want to create a copy of an existing block volume. Currently there is no way to perform these operations.

### Suggested feature

This suggests to create new operations
```
BlockVolumeMigrate
BlockVolumeCopy
```
and corresponding cli commands
```
heketi-cli block-volume migrate <bv> <bhv>
heketi-cli block-volume copy <bv> <bhv>
```
to implement the desired features.

### Proposed approach

The gluster-block tool can now import existing files into block volumes with a new form of the create command:
```
gluster-block create <bhv>/<bv> storage <filename> ...
```
See patches https://review.gluster.org/#/c/18890/ and https://review.gluster.org/#/c/18891/ as well as the original feature request https://bugzilla.redhat.com/show_bug.cgi?id=1514344.

This feature could be used by new heketi `block-volume migrate` or `block-volume copy` operations. Those would be implemented by first copying the block file from its BHV to a new BHV (or even to a new file on the same BHV in case of a copy operation), and then importing the new file into a block volume with the new gluster-block command.

**Comment by obnoxxx** [comment]
@pkalever fyi, and thanks for collaborating on this! :-)

**Comment by phlogistonjohn** [comment]
I do not think we will pursue this item. Closing issue. Please reopen if this is still relevant.
