### ISSUE TITLE
Enable auth & create a read-only user account for heketi metrics & health

### ISSUE THREAD

**Issue by phlogistonjohn** [heketi/heketi#1331]
### Kind of issue

Feature request

### Observed behavior

Heketi recently gained a /metrics endpoint and may be gaining a more detailed heath/status endpoint soon (more detailed than /hello). 
This issue exists to track the addition of authentication support to this endpoint (and similar) as well as an account to access these endpoints.

### Expected/desired behavior

A new user, such as "metrics" can read from metrics endpoint even with authentication protecting the endpoint enabled.

**Comment by obnoxxx** [comment]
@phlogistonjohn i put it to "future". feel free to move to release 9 if it can / must be done sooner

**Comment by phlogistonjohn** [comment]
Probably never going to happen. Closing
