### ISSUE TITLE
Mismatch in overall bricks size and used disk space

### ISSUE THREAD

**Issue by chandidas** [heketi/heketi#1351]
I'm using Heketi version 7 managing GlusterFS Pod ( v4.0.2) running on a kubernetes cluster .
heketi-cli v7.0.0-5-gc10cbd1-release-7

I see there is mismatch in used disk space with the overall volumes consumed by the bricks on the node.

### Kind of issue

Bug

### Observed behavior
Creating heketi volumes through PVC requests only. Size of the below disk  1023G and overall volume consumed by 4 bricks are 620. But the topology info command shows that the **Used** size is 964.

```
        Devices:
                Id:416683136878fdc55892cf3701fb4989   Name:/dev/disk/gluster-disk3State:online    Size (GiB):1023    Used (GiB):964     Free (GiB):59
                        Bricks:
                                Id:326c1d4f8e67baed4aaf99222b9cd784   Size (GiB):250     Path: /var/lib/heketi/mounts/vg_416683136878fdc55892cf3701fb4989/brick_326c1d4f8e67baed4aaf99222b9cd784/brick
                                Id:36d3009075478939258e5b361d2298ba   Size (GiB):250     Path: /var/lib/heketi/mounts/vg_416683136878fdc55892cf3701fb4989/brick_36d3009075478939258e5b361d2298ba/brick
                                Id:4a01f1cf1aecf2ec53e2a137e84cf00b   Size (GiB):20      Path: /var/lib/heketi/mounts/vg_416683136878fdc55892cf3701fb4989/brick_4a01f1cf1aecf2ec53e2a137e84cf00b/brick
                                Id:c3947e12934839ec2eb8092e16cdba12   Size (GiB):100     Path: /var/lib/heketi/mounts/vg_416683136878fdc55892cf3701fb4989/brick_c3947e12934839ec2eb8092e16cdba12/brick
```

I used device resync command to resync heketi DB with the actual disk. But surprised to see that both **Size** and **Free** amounts are getting bumped up to show the actual free space.

```
# heketi-cli device resync 416683136878fdc55892cf3701fb4989

        Devices:
                Id:416683136878fdc55892cf3701fb4989   Name:/dev/disk/gluster-disk3State:online    Size (GiB):1364    Used (GiB):964     Free (GiB):399
                        Bricks:
                                Id:326c1d4f8e67baed4aaf99222b9cd784   Size (GiB):250     Path: /var/lib/heketi/mounts/vg_416683136878fdc55892cf3701fb4989/brick_326c1d4f8e67baed4aaf99222b9cd784/brick
                                Id:36d3009075478939258e5b361d2298ba   Size (GiB):250     Path: /var/lib/heketi/mounts/vg_416683136878fdc55892cf3701fb4989/brick_36d3009075478939258e5b361d2298ba/brick
                                Id:4a01f1cf1aecf2ec53e2a137e84cf00b   Size (GiB):20      Path: /var/lib/heketi/mounts/vg_416683136878fdc55892cf3701fb4989/brick_4a01f1cf1aecf2ec53e2a137e84cf00b/brick
                                Id:c3947e12934839ec2eb8092e16cdba12   Size (GiB):100     Path: /var/lib/heketi/mounts/vg_416683136878fdc55892cf3701fb4989/brick_c3947e12934839ec2eb8092e16cdba12/brick
```

Could anyone help me understand the meaning of dumped up disk size?

### Expected/desired behavior
When bricks gets deleted the *Used* volume column should get updated and reflect the actual size consumed by the existing bricks. Without this, Heketi fails to accept further volume requests and returns no disk space error.

### Details on how to reproduce (minimal and precise)
Created a custom glustefs installation on three nodes of a K8S cluster.

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master):  7.0.0 (heketi-cli v7.0.0-5-gc10cbd1-release-7)
- Operating system used: "Ubuntu 16.04.3 LTS"
- Heketi compiled from sources, as a package (rpm/deb), or container: container
- If container, which container image: heketi:7 taken from dockerhub
- Using kubernetes, openshift, or direct install: on Kubernetes
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: inside k8s as Pod
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): custom

**Comment by chandidas** [comment]
@raghavendra-talur Any comments on this.

**Comment by phlogistonjohn** [comment]
Hi @chandidas could you please retest this scenario with Heketi v.8.0.0? I can't entirely be sure but this seems like it may have been fixed in our most recent release. Thank you.

**Comment by chandidas** [comment]
@phlogistonjohn Thank you for your suggestion. I see that v8.0.0 has been released. I will try on that too.

Couple of additional points I would like to share.
1) In our setup we have GlusterFS and Heketi Pods sharing the same node where workloads are also running. And we try to create PVC of size as high as 1000G too.
2) Below are the configurations for CPU and Memory resources for GlusterFS and Heketi respectively.
```
gluster:
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"

heketi:
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "1Gi"

```

In our setup, we have seen that GlusterFS Pods gets restarted. 
Do you have any guidelines on the CPU and Memory resource requests and limits?

**Comment by phlogistonjohn** [comment]
The Heketi limits look reasonable enough to me. The memory limits on gluster look small to me but I'm not a gluster expert and it depends very much on your workload and volume count. @raghavendra-talur any additional opinions here?

**Comment by chandidas** [comment]
Thank you @phlogistonjohn.. I wait for @raghavendra-talur suggestion on gluster part.

**Comment by chandidas** [comment]
I have not seen same problems in heketi v8.0.0 image; so closing this issue.
