### ISSUE TITLE
API takes up the disk space while running volume create

### ISSUE THREAD

**Issue by PingPongBalls** [heketi/heketi#1358]
### API takes up the disk space while running "heketi-cli volume create --durability=none --size=50"

> This is what i run:
> heketi-cli volume create --durability=none --size=50
> Error: No space

output of the topology info as follow:

heketi-cli topology info

Cluster Id: 1957c36775a56fcb477720f8db3fb0bf

    File:  true
    Block: true

    Volumes:

    Nodes:

        Node Id: 598b038c9c17af282eabe9c02419f5dc
        State: online
        Cluster Id: 1957c36775a56fcb477720f8db3fb0bf
        Zone: 1
        Management Hostnames: kube-06.xxxxx.internal
        Storage Hostnames: 10.61.**.85
        Devices:
                Id:a0ccb28093a5d709471c5c0b458d2ba3   Name:/dev/xvdf           State:online    Size (GiB):500     Used (GiB):0       Free (GiB):500
                        Bricks:

        Node Id: 8d0cb72c7fc2ee0368f06133e40bb169
        State: online
        Cluster Id: 1957c36775a56fcb477720f8db3fb0bf
        Zone: 1
        Management Hostnames: kube-04.xxxxx.internal
        Storage Hostnames: 10.61.**.145
        Devices:
                Id:acd9010834e5970e5ebc2d57ca432cd8   Name:/dev/xvdf           State:online    Size (GiB):500     Used (GiB):452     Free (GiB):47
                        Bricks:

        Node Id: c06e359ce1fd86e7d7dd9826bac03874
        State: online
        Cluster Id: 1957c36775a56fcb477720f8db3fb0bf
        Zone: 1
        Management Hostnames: kube-05.xxxxx.internal
        Storage Hostnames: 10.61.**.247
        Devices:
                Id:0c23df9168412125b6097ea4d2652144   Name:/dev/xvdf           State:online    Size (GiB):500     Used (GiB):0       Free (GiB):500
                        Bricks:

### Observed behavior
it taked all the disk space, until no space left and throw error

### Expected/desired behavior
Should only take 50G of space

### Information about the environment:

- Heketi version used v7.0.0 
- Operating system used: Redhat Linux 7.5
- Heketi installed from glusterfs41 repo, details as follow:

cat /etc/yum.repos.d/gluster.repo
[gluster41]
name=Gluster 4.1
baseurl=http://mirror.centos.org/centos/7/storage/$basearch/gluster-4.1/
gpgcheck=0
enabled=1

**Comment by phlogistonjohn** [comment]
A couple comments:
* Could you please retry with Heketi v8.0.0 which was recently released and had a large number of bug fixes
* If you *are* able to reproduce the issue with Heketi 8 please capture 
  * the heketi logs during the run of the heketi-cli at debug level
  * A copy of the heketi db in json format; run `heketi-cli db dump > filename`
  ( It may be helpful to put these in a pastebin rather than paste in issue if they are long)
* I don't know know what "Heketi compiled from glusterfs41 repo" means.

**Comment by PingPongBalls** [comment]
i redo all of those binding work again, including glusterfs set up and heketi topology. sees like this time i can go to the next step.

i am assuming the error could be under the gluster part, but i am not sure. 
Just wondering where is the log msg for the heketi server? do we have a bit verbose version of the log available? this is mainly for the future.

the "db dump" now is the working version of heketi, so i guess not much value for that.
