### ISSUE TITLE
ERROR: Unable to start application

### ISSUE THREAD

**Issue by swaroopkundeti** [heketi/heketi#1362]
### Kind of issue
Bug - May be

### Observed behavior
After bootstrapped the cluster with heketi. I purged bootstrap components and deployed heketi, pod does come up at all. 

### Expected/desired behavior
Heketi pod suppose to come up and able to create volumes.

### Details on how to reproduce (minimal and precise)
Followed https://github.com/heketi/heketi/blob/master/docs/admin/install-kubernetes.md
Failed at kubectl create -f heketi-deployment.json

### Information about the environment:
6 node cluster, 3 master and 3 nodes.

- Heketi version used (e.g. v6.0.0 or master): 
v8.0.0-1-g082b556-release-8
- Operating system used: 
Ubuntu 16.04
- Heketi compiled from sources, as a package (rpm/deb), or container: 
Container
- If container, which container image: 
heketi/heketi:latest
- Using kubernetes, openshift, or direct install: 
Kubernetes
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside:  Inside
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom):  custom

### Other useful information
<pre>
 kubectl logs -f heketi-9c9755b75-kxwzx
Setting up heketi database
  File: /var/lib/heketi/heketi.db
  Size: 49152     	Blocks: 96         IO Block: 131072 regular file
Device: d5h/213d	Inode: 13628930924399745142  Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2018-09-18 01:36:29.624570146 +0000
Modify: 2018-09-18 02:49:01.255953783 +0000
Change: 2018-09-18 02:49:01.259953772 +0000
 Birth: -
Heketi v8.0.0-1-g082b556-release-8
ERROR: Unable to start application</pre>

I can mount the same volume and configuration (from heketi repo) the container runs fine using docker  command and I can list volumes, cluster and see topology. But when I do the deployment on kubernetes it is not working.

**Comment by phlogistonjohn** [comment]
Hi @swaroopkundeti that document is not the preferred way to install heketi+gluster. In fact, I'm in the midst of some work to have it be only a pointer to [gluster-kubernetes](http://github.com/gluster/gluster-kubernetes) and retain parts of that document only for design purposes. Could you try deploying with gluster kuberntes instead? 
Thank you.

**Comment by phlogistonjohn** [comment]
If gk-deploy has a problem parsing the topology file then you may actually have an issue in the topology file. I would attempt to understand why the topology file is being rejected, fix the issue and then continue with gk-deploy. Feel free to share your topology file with use here or @ gluster-kubernetes if you think it really is correct but it still rejected by gk-deploy.

**Comment by swaroopkundeti** [comment]
@phlogistonjohn I made a new topology file. I deployed cluster successfully, but I can't create volumes.

**Comment by phlogistonjohn** [comment]
OK, you'll need to provide us with some logging and the exact error message that you get.

**Comment by swaroopkundeti** [comment]
@phlogistonjohn I modified above comment with more information

**Comment by phlogistonjohn** [comment]
As the error message says, heketi does not think there are any nodes online in the cluster. Do you have logging related to the health monitor saying your nodes are down?

**Comment by swaroopkundeti** [comment]
@phlogistonjohn Yes nodes are healthy 

<pre>
sre-k8s-8-4   Ready     node          4d        v1.9.2+coreos.0
sre-k8s-8-5   Ready     node          4d        v1.9.2+coreos.0
sre-k8s-8-6   Ready     node          4d        v1.9.2+coreos.0
</pre>

##Glusters are running fine 
<pre>
glusterfs-5rxws                     1/1       Running   0          19m
glusterfs-h22zk                     1/1       Running   0          19m
glusterfs-pl8mk                     1/1       Running   0          19m
</pre>

## 
<pre>
kubectl exec -i glusterfs-5rxws -- gluster peer status
Number of Peers: 2

Hostname: 172.29.236.243
Uuid: 93f0f916-d7a5-4d42-bb9b-23a74198ccc6
State: Peer in Cluster (Connected)
Other names:
172.29.236.243

Hostname: sre-k8s-8-4
Uuid: 3b0108c7-e605-492b-95fc-b5a5453c6896
State: Peer in Cluster (Connected)
</pre>

**Comment by swaroopkundeti** [comment]
Logs from heketi
<pre>
[kubeexec] ERROR 2018/09/19 20:42:00 /src/github.com/heketi/heketi/executors/kubeexec/kubeexec.go:242: Failed to run command [systemctl status glusterd] on glusterfs-h22zk: Err[unable to upgrade connection: pod does not exist]: Stdout []: Stderr []
[cmdexec] ERROR 2018/09/19 20:42:00 /src/github.com/heketi/heketi/executors/cmdexec/peer.go:76:
[kubeexec] ERROR 2018/09/19 20:42:00 /src/github.com/heketi/heketi/executors/kubeexec/kubeexec.go:242: Failed to run command [systemctl status glusterd] on glusterfs-pl8mk: Err[unable to upgrade connection: pod does not exist]: Stdout []: Stderr []
[cmdexec] ERROR 2018/09/19 20:42:00 /src/github.com/heketi/heketi/executors/cmdexec/peer.go:76:
[heketi] INFO 2018/09/19 20:42:00 Periodic health check status: node 7834a29c11763246244ff6dfc0b7617e up=false
[cmdexec] INFO 2018/09/19 20:42:00 Check Glusterd service status in node sre-k8s-8-6
[kubeexec] ERROR 2018/09/19 20:42:00 /src/github.com/heketi/heketi/executors/kubeexec/kubeexec.go:242: Failed to run command [systemctl status glusterd] on glusterfs-5rxws: Err[error dialing backend: dial tcp 172.29.236.146:10250: getsockopt: connection refused]: Stdout []: Stderr []
</pre>
node: 172.29.236.146 doesn't exits in my cluster at all -- not sure why it is checking gluster status of it.

**Comment by phlogistonjohn** [comment]
The first two error messages are indicating that heketi can't figure out what pods your nodes are associated with. When running in k8s heketi uses the kubernetes apis to exec commands in the pods (just like the kubectl exec command). To do this it looks up the management hostname on kubernetes and uses that to determine what pod to talk to.

The IP address 172.29.236.146  is probably the ip of one of the master nodes, no?

**Comment by swaroopkundeti** [comment]
@phlogistonjohn  Looks like my kubernetes cluster got messed up and it messed up heketi and gluster. I recreated whole cluster and its working as expected. Thank you for coming forward and helping me. I will be closing this issue.
