### ISSUE TITLE
Correctly clean up multiple pending operations to delete item X

### ISSUE THREAD

**Issue by obnoxxx** [heketi/heketi#1363]
### Kind of issue

Feature request or add-on to an old bug-fix ...

### Observed behavior

Previously, before #1201 was merged, heketi could get into the situation where multiple block volume delete operations were accepted, and multiple such pending ops for one object were present in the database. This can now not happen any more, but there might be an old database in this state that needs cleanup. 

### Expected/desired behavior

The operations cleanup code should cope with this situation and correctly clean those multiple pending operations.

### Details on what needs to be done

Taken from https://github.com/heketi/heketi/issues/1189#issuecomment-406282956:

The operations cleanup code has to cope with the fact that the first operation may have already deleted X by the time the 2nd operation is encountered. Alternatively, one could take a two-phase approach where all the items to be cleaned up are collected in a matter that avoids or handles duplicates (a map using IDs as keys for example). That change touches the remove-bricks-with-empty-path code while this would need to modify the delete-pending-operations code.

### Details on how to reproduce (minimal and precise)

See the description of issue #1189 .

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): master
- Operating system used: any
- Heketi compiled from sources, as a package (rpm/deb), or container: any (sources, git)

**Comment by phlogistonjohn** [comment]
As heketi is now in maintenance mode, and only accepting major bug and security related fixes, we do not expect to implement this change.
