### ISSUE TITLE
Heketi DB out of sync with gluster volumes

### ISSUE THREAD

**Issue by megian** [heketi/heketi#1367]
Heketi does report volumes, Gluster already has deleted.

[negroni] Started DELETE /volumes/07a87c929f11f424eee76269d376777d
[negroni] Completed 404 Not Found in 641.963µs
[negroni] Started DELETE /volumes/c9e77fdfd2ae2272d72b8df64ffada76
[negroni] Completed 404 Not Found in 1.807319ms
[negroni] Started DELETE /volumes/7e3d6e1284ac81bb9014c5955ab136b2
[negroni] Completed 404 Not Found in 366.008µs
[negroni] Started DELETE /volumes/9e5e67734c44e358677ecb0e88ffac9f
[negroni] Completed 404 Not Found in 710.605µs

### Kind of issue

Bug

### Observed behavior
The Heketi DB can get out of sync with the real configuration of Gluster. Please provide a sync with Gluster or inform the administrator how to cleanup.

### Expected/desired behavior
Heketi should cleanup inconsistency of configuration issues by them self.

### Details on how to reproduce (minimal and precise)
Delete PVC while Heketi is not running.

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): v8.0.0-1-g082b556-release-8
- Operating system used: Atomic Host 7.1808
- Heketi compiled from sources, as a package (rpm/deb), or container: no
- If container, which container image: docker.io/heketi/heketi
- Using kubernetes, openshift, or direct install: 
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: inside
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): openshift-ansible

### Other useful information

This Heketi DB has been upgraded and is not a fresh installation.

**Comment by vikramkhatri** [comment]
Same issue here:

1. In a constrained environment (which is a best test scenario to test the resiliency of a software) - I created a volume using `heketi-cli volume create --size=2` and it was fine. I can see the volume using `gluster volume list`.

2. I, then, deleted the volume `heketi-cli volume delete vol_e457c59b0662b83bd15127a0195b4e79` and this led to one of Gluster VM to reboot.

3. The `gluster volume list` shows that the volume is deleted but the `heketi-cli volume delete` is stuck forever.

4. After I cancel it, the heketi volume still shows and if I try the delete it again. I get the error.

```
# heketi-cli volume delete e457c59b0662b83bd15127a0195b4e79
Error: Failed to set up volume delete: The target exists, contains other items, or is in use.
```

The heketi database is out of sync now. And, there is no easy process to clean this mess now.

Hence I vote up for the question raised and need some solution.

Environment: CentOS 7.4, Hekti: 8.0 and Gluster : 4.0.2

**Comment by lcrain428** [comment]
similar problem +1

**Comment by born4new** [comment]
We've got the same problem fairly recently biting us in the a**.

Any hope for an import/sync command?

**Comment by oscarmash** [comment]
similar problem +1

**Comment by Goina2018** [comment]
the same problem!!!

**Comment by Goina2018** [comment]
we met the same problem!!!

**Comment by archever** [comment]
similar problem +1

**Comment by phlogistonjohn** [comment]
Any user encountering similar issues should please retry using heketi v9. If you encounter a problem please file *a new issue* with full details.
