### ISSUE TITLE
Possible segfault?

### ISSUE THREAD

**Issue by ansiwen** [heketi/heketi#1368]
https://github.com/heketi/heketi/blob/34c2f62c9afb98af38e5a021a583c6e77d5a6a64/apps/glusterfs/app_block_volume.go#L122-L123

While refactoring I found this code and wonder if this is not a possible segfault? It's still possible that `err != nil` in which case we can't assume anything about `entry`. In this specific case NewBlockVolumeEntryFromId() always initializes `entry`, so the pointer cannot be nil and we are safe, but in general it could be, right? Or is it a strict convention in heketi code, that pointers are never nil? Normally I would consider that a bug because of potential segfault.

**Comment by phlogistonjohn** [comment]
I think it's safe becuase golang shortcuts the or statement (like many languages). The 2nd part after the || will not be executed at all if err == ErrNotFound.
I think that one of the reasons for short-cutting is so you _can_ write code like this.

**Comment by ansiwen** [comment]
Oh sure, I’m fully aware of the conditional evaluation after && and ||, but my point is a different one: just because `err != ErrNotFound` doesn’t necessarily mean that `err == nil`, which means it still could be a different error, and the part after || _would_ be evaluated, and because there was an error it _could_ be `entry == nil`. Not in this specific case, if you check the code of `NewBlockVolumeEntryFromId()`. But I'm talking about the general golang convention of not relying on any returned value, if `err != nil`.

**Comment by phlogistonjohn** [comment]
Ah. Gotcha. Point taken.

**Comment by phlogistonjohn** [comment]
True, but not hit in practice - closing "wontfix".
