### ISSUE TITLE
Identify block devices by a stable UUID, not boot dependent /dev/sdX

### ISSUE THREAD

**Issue by nixpanic** [heketi/heketi#1371]
### Kind of issue

Feature request

### Observed behavior

Some cloud providers do not provide stable paths to disks. The ordering of the detection of disks may change when a Virtual Machine reboots.

### Expected/desired behavior

Heketi should be able to handle disks that are in a different order after initial topology import.

### Details on how to reproduce (minimal and precise)

When disks get added, they are referenced by their device node (`/dev/sdb`). This is practical because users should know which disks are currently connected and dedicated for Heketi's use.

However, the device node gets stored in the database, and this does not need to stay correct. When a VM (or even a physical server) reboots, `/dev/sdb` does not need to be `/dev/sdb` again. The name of the device-node may change, it could be `/dev/sde` depending on the number of disks attached to the system.

This is not a problem for the tools that are used. Normally `/etc/fstab` contains UUID's of the formatted filesystems or LVM devices.  LVM writes its own header to the disks, and detects the layout of physical volumes, volume groups and logical volumes that way.

In order to have Heketi display the correct device-node after a reboot, the database should not contain (or trust) the device-node that is stored. Instead of storing the device-node, it is better to store the UUID that `pvcreate` writes in the LVM-header on the disk. This UUID can also be used through `/dev/disk/by-uuid/...`.

**Comment by phlogistonjohn** [comment]
I'm generally +1 on storing the device pv's UUID. However, I'm not sure if we should forget about the device path. On systems where the device path _is_ constant it makes sense to refer to the device as that's what users are used to working with. We should just be aware that it's possibly not the source of truth for anything past the pvcreate call.

**Comment by nixpanic** [comment]
We can not assume the device-node is consistent anywhere. In case a user adds or removes a disk, the order may change after a reboot. It can cause users to incorrectly `wipefs` devices that they expect to remove next.

Displaying the correct device-node *is* important for users. But it should get detected based on the UUID of the LVM/PV after the host/pod restarted (and after a Heketi restart).

**Comment by phlogistonjohn** [comment]
Hmm, that means something like a topology info command would have to exec commands on the nodes and that seems suboptimal to me.

**Comment by nixpanic** [comment]
Yes, or maybe gather the device-names once after the health-check is successful for a node and cache them afterwards?
