### ISSUE TITLE
Error: Failed to allocate new volume: No space (openshift)

### ISSUE THREAD

**Issue by imranrazakhan** [heketi/heketi#1375]
### Kind of issue
> Feature request

### Observed behavior
One node cluster is not getting create with 
`heketi-cli setup-openshift-heketi-storage`

### Expected/desired behavior
There should be option to create one node cluster in openshift for testing purpose, it can be done with 
`heketi-cli volume create --durability=none --size=1`
but openshift run 
`"oc", "--config=/tmp/openshift-glusterfs-ansible-PuHRNV/admin.kubeconfig", "rsh", "--namespace=glusterfs", "deploy-heketi-storage-1-dhbfv", "heketi-cli", "-s", "http://localhost:8080", "--user", "admin", "--secret", "BwyRN5bSXW+OnUe1ulU3rVtwt0ISOXRqamO1rw2VVms=", "setup-openshift-heketi-storage", "--image", "docker.io/heketi/heketi:latest", "--listfile", "/tmp/heketi-storage.json"`

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master):  **OpenShift 3.10**
- Operating system used:  **CentOS**
- Heketi compiled from sources, as a package (rpm/deb), or container:  **Container**
- If container, which container image:  **docker.io/heketi/heketi:latest**
- Using kubernetes, openshift, or direct install:  **Openshift**
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside:  **outside**
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom):  **openshift-ansible**

### Other useful information

I have install glusterfs on one node and now configuring it from openshift, but it got fail on following place

Openshift 3.10 (OKD) on CentOS with glusterfs

I changed my inventory file like below

    openshift_storage_glusterfs_is_native=false
    openshift_storage_glusterfs_storageclass=true
    openshift_storage_glusterfs_heketi_is_native=true
    openshift_storage_glusterfs_heketi_executor=ssh
    openshift_storage_glusterfs_heketi_ssh_port=22
    openshift_storage_glusterfs_heketi_ssh_user=root
    openshift_storage_glusterfs_heketi_ssh_sudo=false
    openshift_storage_glusterfs_heketi_ssh_keyfile="/root/.ssh/id_rsa"

Following error while installing one node glusterfs. I have 80GB disk and before starting installation i run wipefs -a

    TASK [openshift_storage_glusterfs : Create heketi DB volume] 
     ************************************************************
    fatal: [MY001.local]: FAILED! =>
    {  
       "changed":true,
       "cmd":[  
          "oc",
          "--config=/tmp/openshift-glusterfs-ansible-PuHRNV/admin.kubeconfig",
          "rsh",
          "--namespace=glusterfs",
          "deploy-heketi-storage-1-dhbfv",
          "heketi-cli",
          "-s",
          "http://localhost:8080",
          "--user",
          "admin",
          "--secret",
          "BwyRN5bSXW+OnUe1ulU3rVtwt0ISOXRqamO1rw2VVms=",
          "setup-openshift-heketi-storage",
          "--image",
          "docker.io/heketi/heketi:latest",
          "--listfile",
          "/tmp/heketi-storage.json"
       ],
       "delta":"0:00:00.429962",
       "end":"2018-09-27 19:27:05.455025",
       "msg":"non-zero return code",
       "rc":255,
       "start":"2018-09-27 19:27:05.025063",
       "stderr":"Error: Failed to allocate new volume: No space\ncommand terminated with exit code 255",
       "stderr_lines":[  
          "Error: Failed to allocate new volume: No space",
          "command terminated with exit code 255"
       ],
       "stdout":"",
       "stdout_lines":[  
    
       ]
    }

While searching i found that this issue is due to one node and this behaviour can be override with below command, But how we can override this in heketi-cli as its directly calling while installing openshift?

    heketi-cli volume create --durability=none --size=1

Can following command override

    heketi-cli setup-openshift-heketi-storage

**Comment by phlogistonjohn** [comment]
Heketi has --durability and --replica options on the setup-openshift-heketi-storage subcommand. However, I don't know openshift-ansible well enough to say if these extra options are controllable via the playbooks. @jarrpa any thoughts?

**Comment by jarrpa** [comment]
They are not directly available, users would need to edit the ansible directly to use them. And given where OCP 3.11 and 4.0 are headed, I can pretty much guarantee this won't change.

**Comment by phlogistonjohn** [comment]
Thank you. So it seems like @imranrazakhan needs to either hack the playbooks or use something like gk-deploy from gluster-kubernetes (which has a single node option IIRC)?

**Comment by imranrazakhan** [comment]
@phlogistonjohn thanks for updates i am able to run by adding --durability none in following ansible script

`openshift-ansible/roles/openshift_storage_glusterfs/tasks/heketi_init_db.yml`

```
- name: Create heketi DB volume
  command: "{{ glusterfs_heketi_client }} setup-openshift-heketi-storage --image {{ glusterfs_heketi_image }} --listfile /tmp/heketi-storage.json **--durability none**"
  register: setup_storage
```

**Comment by phlogistonjohn** [comment]
Great to hear! It's admittedly hacky but is it sufficient to close this issue?

**Comment by imranrazakhan** [comment]
Yes we can close issue.

**Comment by tripletrk** [comment]
I am having the same issue doing a fresh OKD 3.11 deployment, even after I appended the "--durability none" to the heketi_init_db.yml role.
Login to the deploy_heketi_storage pod and run this command directly does succeed.  
`$ oc rsh deploy-heketi-storage-1-2r79x 
sh-4.4$ heketi-cli -s http://localhost:8080 --user admin --secret xseAR3v7glVV+TYtYejaTutcUQBTSBvF001rbPkrfJk= setup-openshift-heketi-storage --image docker.io/heketi/heketi:latest --listfile /tmp/heketi-storage.json --durability none
Saving /tmp/heketi-storage.json`
This's been driving me nuts for days...
