### ISSUE TITLE
HEKETI service IP changes

### ISSUE THREAD

**Issue by dimthe** [heketi/heketi#1377]
/bug

hello 

i have a glusterfs running in kubernetes with no problems . Heketi is managing the glustersfs but there have been 3 times so far where the heketi service ip has changed by itself. How is this possible ? Heketi pod has not been deleted so this would explain the ip change 
is there a fix for this ?

**Comment by phlogistonjohn** [comment]
Heketi is not responsible for its own IP address, so I don't think anything in the server itself is making this change. I would closely monitor the state of the pod & the related services. Sorry I can't be more helpful but this certainly feels something k8s is in control of, not Heketi the daemon.

**Comment by howels** [comment]
Ideally the Heketi service DNS name would be used by a StorageClass. See the issue I raised here for a fix allowing the use of DNS names for StorageClass entries: https://github.com/kubernetes-incubator/kubespray/issues/3177
