### ISSUE TITLE
Heketi should use Semantic Versioning (SemVer)

### ISSUE THREAD

**Issue by davivcgarcia** [heketi/heketi#1388]
### Kind of issue

Is Heketi using Semantic Versioning (SemVer)? The ideia is to have MAJOR.MINOR.PATCH where:

MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards-compatible manner, and
PATCH version when you make backwards-compatible bug fixes.

### Observed behavior

Current releases:

v8.0.0
v7.0.0
v6.0.0
v5.0.1
v5.0.0
v4.0.0
v3.1.0
v3.0.0
v2.1.0-dev
v2.0.6

### Expected/desired behavior

Less MAJOR changes, more MINOR.PATCH changes.

**Comment by phlogistonjohn** [comment]
The team does not plan on changing the versioning scheme heketi uses. Thank you for the suggestion.
