### ISSUE TITLE
mismatch between heketi volume list and gluster volume list

### ISSUE THREAD

**Issue by imranrazakhan** [heketi/heketi#1391]
### Kind of issue

> Uncomment only one of these:
> Bug

### Observed behavior
I have installed glusterfs-server, heketi and heketi-client on one server and through openshift i created volumes but both commands have different output on same server

```
# heketi-cli volume list
Id:740af71a4fc3c17e58ed646057fe51f1    Cluster:84660f06394d0169e92b174ebeb32a5a    Name:youvol
Id:da33ed8c6e4dae814201da13a8c8baab    Cluster:84660f06394d0169e92b174ebeb32a5a    Name:vol_da33ed8c6e4dae814201da13a8c8baab
Id:dd0cbdc724052b59748f668929fda89c    Cluster:84660f06394d0169e92b174ebeb32a5a    Name:vol_dd0cbdc724052b59748f668929fda89c
```

```
# gluster volume list
No volumes present in cluster
```

### Expected/desired behavior
Both should list same volume

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): 

```
# heketi --version
Heketi 7.0.0
# heketi-cli --version
heketi-cli 7.0.0
# gluster --version
glusterfs 4.1.5
```
- Operating system used: CentOS
- Heketi compiled from sources, as a package (rpm/deb), or container: rpm
- If container, which container image: 
- Using kubernetes, openshift, or direct install: openshift
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: 
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom):

**Comment by hgye** [comment]
Why this issue closed, I had same problem?
Howto solve it?

**Comment by hgye** [comment]
I got it.

Need change executor from mock -> ssh/k8s
"executor": "mock",
