### ISSUE TITLE
heketidbstorage not mounted on reboot, empty dir used instead and blank db is created.

### ISSUE THREAD

**Issue by howels** [heketi/heketi#1403]
Heketi mounts empty directory instead of the DB PV, then creates a blank DB. This appears to occur when a node is rebooted. The DB still exists on the PV, but as Heketi is no longer seeing the DB then future attempts to create, mount or delete volumes all fail. This leads to a condition where restarting the Heketi pod will also fail to mount the volume and the service is deadlocked.

### Kind of issue

Bug

### Observed behavior

HeketiDbStorage is mounted as an empty dir and a blank DB is created instead of the actual DB being used.

### Expected/desired behavior

If PV mount fails then the Pod should not be scheduled. The Heketi Pod should only start when heketidbstorage is available and mounted.

### Details on how to reproduce (minimal and precise)

Unfortunately this appears to occur randomly on some node reboots. The issue is hard to reproduce but appears to be a timing issue. Nonetheless Pods should not be scheduled with unavailable mounts.

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): 
4.1
- Operating system used: 
CentOS 7.5
- Heketi compiled from sources, as a package (rpm/deb), or container: 
Deployed with latest gk-deploy
- If container, which container image: 
Latest gk-deploy
- Using kubernetes, openshift, or direct install: 
Kubbernetes
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: 
Inside
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): 
gk-deploy

**Comment by phlogistonjohn** [comment]
This sounds like an issue with the way you have heketi deployed as heketi is not responsible for mounting any persistent storage. You have to configure it with a path to the db but that is all. Any mounting needs to be done outside heketi.
If this appears to be an issue with gk-deploy please create a new issue in the gluster-kubernetes repo. Thanks.
