### ISSUE TITLE
heketi.json is added manually in the Dockerfile 

### ISSUE THREAD

**Issue by SaravanaStorageNetwork** [heketi/heketi#1406]
### Kind of issue

 Bug 

I am referring the below Dockerfile as the heketi upstream Dockerfile.
https://github.com/heketi/heketi/blob/master/extras/docker/centos/Dockerfile#L13

As you can see heketi.json is added manually here. 
When heketi is installed it will automatically brings in heketi.json - and it is the recent one from the rpm.

Any specific reason to overwrite the heketi.json ?  Keeping two different heketi.json is error prone and recent changes in heketi.json(from rpm) may be missed.

**Comment by SaravanaStorageNetwork** [comment]
@raghavendra-talur @obnoxxx @phlogistonjohn  Please check

**Comment by phlogistonjohn** [comment]
Yes, this seems odd but I don't know who's consuming this particular Dockerfile. It was added to support centos storage sig I believe. However, I think most users that aren't using custom builds get the heketi container from dockerhub which relies on extras/docker/fromsource.

That said, we should certainly try to resolve any issues with this particular Dockerfile.

**Comment by SaravanaStorageNetwork** [comment]
@phlogistonjohn  - the Dockerfile mentioned in this  issue exists here too - https://github.com/heketi/heketi/blob/master/extras/docker/fromsource/Dockerfile#L35 -  

( and the same change is carry forwarded in downstream.)
I am not sure why heketi.json is added manually . It should be avoided as we will have diverge files in rpm vs manual addition.

**Comment by nixpanic** [comment]
I do not know why there is a modified `heketi.json` in the container images. It should probably be removed and picked from the main source tree instead. It will also need an update in the [prepare-build.sh](https://github.com/heketi/heketi/blob/master/extras/docker/centos/prepare-build.sh) script.

**Comment by SaravanaStorageNetwork** [comment]
> I do not know why there is a modified `heketi.json` in the container images. It should probably be removed and picked from the main source tree instead. It will also need an update in the [prepare-build.sh](https://github.com/heketi/heketi/blob/master/extras/docker/centos/prepare-build.sh) script.

Yes.

Any idea what is the official upstream Dockerfile for heketi ? There seems to be too many lying around.
You can see one here too: [heketi dockerfile](
https://hub.docker.com/r/heketi/heketi/~/dockerfile/)

**Comment by nixpanic** [comment]
> Any idea what is the official upstream Dockerfile for heketi ? There seems to be too many lying around.
> You can see one here too: [heketi dockerfile](
> https://hub.docker.com/r/heketi/heketi/~/dockerfile/)

That file should come from
https://github.com/heketi/heketi/blob/master/extras/docker/fromsource/Dockerfile
and when the original changes, the Docker Hub file should change after
the container image was build.

The 'official' upstream Dockerfiles would be included in this
repository. But there may be others in case Heketi is delivered as part
of a Kubernetes or OpenShift distribution. 'Upstream' can be a little
ambiguous.

**Comment by phlogistonjohn** [comment]
The current maintenance team does not plan on changing this. Closing. Please reopen if this issue is still relevant to you.
