### ISSUE TITLE
Add a more complete /healthz endpoint to heketi

### ISSUE THREAD

**Issue by phlogistonjohn** [heketi/heketi#1412]
### Kind of issue

Feature request

### Observed behavior

The /hello endpoint is simple and works well for a quick curl test but says nothing else about the internal state of the server.

### Expected/desired behavior

Provide a /healthz endpoint that follows common conventions and is able to report on more about the internal state of the server.

**Comment by phlogistonjohn** [comment]
Potential checks:
* Check that executor has been able to communicate with nodes in some timeframe
* Check that heketi can write to the db

**Comment by Madhu-1** [comment]
@phlogistonjohn have you started working on this?

**Comment by phlogistonjohn** [comment]
No, feel free to begin working on this if you are interested. Let's discuss any design details here in the issue around what the API/response body will look like.

**Comment by Madhu-1** [comment]
@phlogistonjohn, sure I will take this up.  I will update API and response body pseudo code

**Comment by mykaul** [comment]
Status?

**Comment by phlogistonjohn** [comment]
Probably never going to happen. Closing
