### ISSUE TITLE
heketi using https:// in storageclass

### ISSUE THREAD

**Issue by Kydybets** [heketi/heketi#1416]
Hi All,
I have Openshift cluster 3.10
 Used ansible playbook to deploy GlusterFS (container-native storage).
So, if I didn't edit StorageClass to use internal traffic(http://<service-name>.<namespace>.svc.cluster.local:8080), 
I will got an error in openshift console, x.509, the certificate signed by the unknown authority.
if Igo in the browser using the route from the heketi service, I got "Required authorization token not found".

The question is it this normal that after running playbooks we got https, but didn't find any examples in the documentation about.
I understand that normally all the traffic should go inside of cluster and don't go outside of it.

**Comment by Kydybets** [comment]
but as for Heketi route, it can be resolved with https://<heketi-storage-route>/hello is available. 
looking for someone who can explain me how things should goes.

**Comment by phlogistonjohn** [comment]
Stale issue. Closing.
