### ISSUE TITLE
Deployment on k8s fails. 

### ISSUE THREAD

**Issue by smirnov-mi** [heketi/heketi#1420]
### Kind of issue

> Uncomment only one of these:
> 
Bug
> Feature request

### Observed behavior

there is no such file as deploy-heketi-deployment.json anymore. Deploying the heketi-deployment.json creates glusterfs-hp*** pods, but not the heketi
 

### Expected/desired behavior

I would expect the heketi pod created as well.

### Details on how to reproduce (minimal and precise)

just follow the installation instructions for kubernetes. Label the nodes, and run
kubectl create -f  heketi-deployment.json

secret "heketi-db-backup" created
service "heketi" created
deployment "heketi" created

But no heketi pod is running or pending or whatever.

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master):  trying to install the current version from github.
- Operating system used: Ubuntu 16.0.4
- Heketi compiled from sources, as a package (rpm/deb), or container: github
- If container, which container image: 
- Using kubernetes, openshift, or direct install: kubernetes
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: 
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom):  hetzner-kube

### Other useful information

maybe the installation instructions are outdated,  I'm new in GlusterFS/Heketi

**Comment by smirnov-mi** [comment]
The how-to is missing a "create sa" part.  
i.e. kubectl. create -f heketi-service-account.json

But after I did it, I endet up here:

Events:
Type Reason Age From Message
---- ------ ---- ---- -------
Normal Scheduled 25m default-scheduler Successfully assigned heketi-7898db85dd-lb7vg to max1-worker-01
Normal SuccessfulMountVolume 25m kubelet, max1-worker-01 MountVolume.SetUp succeeded for volume "heketi-service-account-token-5vzpc" 
Normal SuccessfulMountVolume 25m kubelet, max1-worker-01 MountVolume.SetUp succeeded for volume "heketi-db-secret" 
Warning FailedMount 25m (x3 over 25m) kubelet, max1-worker-01 MountVolume.SetUp failed for volume "config" : secrets "heketi-config-secret" not found
Warning FailedMount 21s (x7146 over 25m) kubelet, max1-worker-01 MountVolume.NewMounter initialization failed for volume "db" : endpoints "heketi-storage-endpoints" not found

**Comment by srinathkotu** [comment]
@smirnov-mi use the gk-deploy script to deploy the heketi pods, from my long tests i found that is the best way to configure/setup heketi on K8s

**Comment by raghavendra-talur** [comment]
@smirnov-mi The setup guide to refer to is https://github.com/gluster/gluster-kubernetes/blob/master/docs/setup-guide.md

And as part of the process when you run the gk-deploy script the serviceaccount get created.

Let us know if we can close this issue.

**Comment by phlogistonjohn** [comment]
No response for a couple of months. Closing.

**Comment by smirnov-mi** [comment]
Yep. Sorry, can’t verify. 
Moved away from Heketi
