### ISSUE TITLE
Investigate changing gluster cli timeout value

### ISSUE THREAD

**Issue by phlogistonjohn** [heketi/heketi#1426]
### Kind of issue

Feature request

### Expected/desired behavior

Because heketi is ansync by nature and commands are not being monitored by humans the timeout used for gluster (cli) commands to talk wiith glusterd by default may be more useful with a larger value when run by heketi.

**Comment by atinmu** [comment]
Quick question : (I like this from simplicity part) When glusterd is not able to process requests at a rate at which heketi is receiving and forwarding the same, how this back pressure is handled at heketi layer? Does heketi starts rejecting requests after a certain threshold

**Comment by obnoxxx** [comment]
@atinmu writes:
> Quick question : (I like this from simplicity part) When glusterd is not able to process requests at a rate at which heketi is receiving and forwarding the same, how this back pressure is handled at heketi layer? Does heketi starts rejecting requests after a certain threshold

Yes, the throttling feature in heketi lets heketi reject new requests when a configurable number of allowed concurrent (in-flight) operation are active (defaulting to 8). Operation here means high-level heketi (API) operation  like volume create, volume delete, etc... If we keep the gluster cli command running long, then for the time it's running the corresponding operation that this cli command is part of will be in flight, so if there are 8 waiting gluster cli commands, then heketi will start rejecting additional requests until they are done, and as a consequence, it will not send additional requests to glusterd until this is solved.
