### ISSUE TITLE
More metrics

### ISSUE THREAD

**Issue by kolesoffac** [heketi/heketi#1429]
### Kind of issue

Feature request

### Expected/desired behavior

Add please next section from api:
- Cluster Information
- List Clusters
- Node Information
- Device Information
- Volume Information

to increase the information content.

Thanks

**Comment by phlogistonjohn** [comment]
Unfortunately, this issue is a bit too vague to be actionable we certainly plan on adding more metrics in the future but I can't see a way to ever call this issue done. Please feel free to reopen if additional discussion is required.
