### ISSUE TITLE
Builds failing at prebuild step for registry.centos.org/gluster/storagesig-heketi:testing

### ISSUE THREAD

**Issue by bamachrn** [heketi/heketi#1432]
### Kind of issue

Bug

### Observed behavior

[centos] Running prebuild shell script
+ sh ./prepare-build.sh
cp: cannot stat './../fromsource/heketi.json': No such file or directory

Source repo is not getting ready to build, as a result builds are failing.

### Expected/desired behavior

prebuild script should pass to get the repo ready to build the image.

### Details on how to reproduce (minimal and precise)

this builds are running from the container-index entry:
https://github.com/CentOS/container-index/blob/master/index.d/gluster.yaml#L13-L25

```
 - id: 2
    app-id: gluster
    job-id: storagesig-heketi
    git-url: https://github.com/heketi/heketi
    git-branch: master
    git-path: extras/docker/centos
    target-file: Dockerfile.testing
    desired-tag: testing
    notify-email: heketi-devel@gluster.org
    build-context: ./
    prebuild-script: ./prepare-build.sh
    prebuild-context: extras/docker/centos
    depends-on: centos/centos:latest
```

### Information about the environment:

building the image in CentOS Community Container Pipeline service

**Comment by phlogistonjohn** [comment]
Stale issue. Closing.
