### ISSUE TITLE
Problem accessing devices on Gluster Nodes - does it work if the volume are encrypted via luks?

### ISSUE THREAD

**Issue by stevef1uk** [heketi/heketi#1437]
Hi,

I am a newbie to setting up Heketi and having run the topology load --json=heketi-config/topology.json
command  I am receiving the following errors:

Adding device /dev/sdb ... Unable to add device: Can't open /dev/sdb exclusively.  Mounted filesystem?

Expected behaviour is that the command completes without error.

### Details on how to reproduce (minimal and precise)
Set-up as per: https://github.com/mike-trewartha/gce-gluster-heketi-gke
Key difference is using cryptsetup luksOpen /dev/sdb  gvol1  to encrypt the volumes on the Gluster nodes. 

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): v8.0.0
- Operating system used: CoreOs 3.10.0-514.21.2.el7.x86_64 #1 SMP Tue Jun 20 12:24:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Heketi compiled from sources
direct install: 
gluster running as 3 identical nodes on GCP

### Other useful information
I have been following the helpful tutorial here: https://github.com/mike-trewartha/gce-gluster-heketi-gke I changed zones to Europe though.

The other change I have made is to use cryptsetup luksOpen /dev/sdb  gvol1  to encrypt the volumes. I am guessing this is the problem. I was hoping I could create a Gluster volume using Linux encrypted storage.

**Comment by phlogistonjohn** [comment]
> The other change I have made is to use cryptsetup luksOpen /dev/sdb gvol1 to encrypt the volumes. I am guessing this is the problem. I was hoping I could create a Gluster volume using Linux encrypted storage.

I would bet you are right. I think what you need to do is to point heketi at the block device that is the output of the LUKS encryption. Using my laptop as an example I have `/dev/nvme0n1p2` being used as the "input" to LUKS, I am assuming this is equivalent to your /dev/sdb. Then my lvm and file systems point at /dev/mapper/luks-08635e02-5eca-47f9-e6bf-6e72e13e0b31. There is also a /dev/disk/by-id/dm-uuid-CRYPT-LUKS1-08635e025eca47f9b6bf6e7251350b31-luks-08635e02-5eca-47f9-e6bf-6e72e13e0b31

I would suggest providing either of these to the topology file and seeing how that goes.

As a side note, I quckly skimmed the guide you linked to and it looked to me like it was deploying heketi by-hand outside of any pods. I *strongly* suggest deploying heketi using something like http://github.com/gluster/gluster-kubernetes 
This method avoids a lot of potential errors in deployment as well as giving you an HA heketi (by use of k8s and gluster).

**Comment by stevef1uk** [comment]
John thanks for the steer. I do indeed intend to deploy heketi on kubernetes, but I first wanted to access a Gluster cluster not deployed on Kubernetes as if one uses GKE I am not sure how Gluster would be be deployed on nodes one has no direct access to?  I know this works on a home server set-up as my grown-up son did it for me and it appears to work a treat. Being able to deploy Cassandra using Helm and have the persistent volumes automagically created for me using gluster was great. Obviously, before I could propose this approach for real production use cases I need a lot more comfort and to better understand how to do this so I wanted to learn by taking 'baby steps' first ;-)

**Comment by phlogistonjohn** [comment]
Glad I could be of help.
There's no issue with having heketi in a pod managing gluster. We usually call this the "independent" mode and it simply means that heketi must be configured for SSH access into the the gluster nodes.
No issues with learning the components first! I just wanted to mention that resource is available and may help reduce the number of manual steps that you'd need to perform.

**Comment by phlogistonjohn** [comment]
Issue has been idle for a few months. Closing.
