### ISSUE TITLE
Heketi systemd unit file typo

### ISSUE THREAD

**Issue by adeleglise** [heketi/heketi#1438]
### Kind of issue
Bug
### Observed behavior
Heketi fails to start via heketi.service systemd unit

### Expected/desired behavior
Heketi starts correctly

### Details on how to reproduce (minimal and precise)
Install heketi from repo on CentOS 7.
Configure heketi in /etc/heketi/config.json file
Try to start heketi via systemd
Observe error :
```
heketi: Error: unknown shorthand flag: 'c' in -config=/etc/heketi/heketi.json
```
Observe the typo in `/usr/lib/systemd/system/heketi.service` :

```
...
ExecStart=/usr/bin/heketi -config=/etc/heketi/heketi.json
...
```

Should be :

```
...
ExecStart=/usr/bin/heketi --config=/etc/heketi/heketi.json
...
```

### Information about the environment:

- Heketi version used v 7.0.0
- Operating system used:  CentOS Linux release 7.5.1804
- Heketi compiled from sources, as a package (rpm/deb), or container: heketi as package

**Comment by nixpanic** [comment]
Could you try to use heketi-8 on CentOS? That is in the
centos-gluster*-test repository of the Storage SIG. You should be able
to update your version with this command:

    # yum --enablerepo='centos-gluster*-test' update heketi

If you can confirm that this version of Heketi works for you, I'll mark
the package as stable and it will be pushed to the CentOS mirrors soon.

Thanks!

**Comment by adeleglise** [comment]
I can't test it right now. 
I'll keep you updated as soon as I can test it.

**Comment by adeleglise** [comment]
Hello,
I can confirm that with the heketi-8 version, everything is working as intended.
The systemd file is correct, and heketi works like a charm.

Thanks.

**Comment by nixpanic** [comment]
Thanks for testing! When the CentOS team pushes the next batch of packages to the mirrors heketi-8.0.0-1.el7 will be included as well. This will happen only after CentOS 7.6.18xy is released though.

Please close this issue if you're happy with that.

**Comment by adeleglise** [comment]
I'm totally happy with that !
