### ISSUE TITLE
Simultaneous operations don't terminate old glusterfs processes

### ISSUE THREAD

**Issue by aliscott** [heketi/heketi#1439]
### Kind of issue

Bug

### Observed behavior

When performing multiple simulataneous operations (volume create and volume delete), old `glusterfs` processes are not always terminated on the nodes. This can quickly result in many `glusterfs` processes running and utilising a lot of CPU.

Old glusterfs processes will also spam the `glustershd.log` with warnings since they are referencing volumes that have been deleted:
```
[2018-11-18 03:45:02.542042] W [rpc-clnt.c:1753:rpc_clnt_submit] 20-vol_08694cf3932475d95664f55d03966dc7-client-1: error returned while attempting to connect to host:(null), port:0
[2018-11-18 03:45:02.542106] W [rpc-clnt.c:1753:rpc_clnt_submit] 20-vol_08694cf3932475d95664f55d03966dc7-client-0: error returned while attempting to connect to host:(null), port:0
[2018-11-18 03:45:02.542654] W [rpc-clnt.c:1753:rpc_clnt_submit] 20-vol_08694cf3932475d95664f55d03966dc7-client-1: error returned while attempting to connect to host:(null), port:0
[2018-11-18 03:45:02.542761] W [rpc-clnt.c:1753:rpc_clnt_submit] 20-vol_08694cf3932475d95664f55d03966dc7-client-0: error returned while attempting to connect to host:(null), port:0
```

### Expected/desired behavior

After running simultaneous operations there should only be a single glusterfs process running on each node.

### Details on how to reproduce (minimal and precise)

1. Create multiple volumes and then delete them in parallel. I've been using OKD's client `oc -n namespace delete pvc vol1 vol2 vol3`.

2. Wait a few seconds until all volumes have been deleted

3. Check the number of `glusterfs` processes on each node (`ps ax | grep "/usr/sbin/glusterfs "`)

**NOTE:** This is not reproducible when `max_inflight_operations` is set to 1.

### Information about the environment:

Heketi version:
```
Heketi v8.0.0-1-g082b556-release-8
```

Image version:
```
docker.io/heketi/heketi@sha256:9eefe87d0047ad81b300fa992877f88e423750fa1bb91f392c6dd0b77ea16bdd
```

GlusterFS (running in OKD cluster) version:
```
glusterfs 4.1.4
```

**Comment by alikhajeh1** [comment]
Any update on this?

**Comment by dswebbthg** [comment]
just wanted to add that I'm also hitting this issue on gluster 5.2.1.  If I delete a large number of volumes in parallel I get number of orphaned glustershd's consuming cpu.

**Comment by dkazhdan1** [comment]
i am wondering if this has been fixed yet? thanks

**Comment by phlogistonjohn** [comment]
Honestly, this strikes me as an issue beyond heketi. Has anyone reported this to gluster?
I would not expect all glusterfsd processes to terminate because typically heketi is combined with brick-mux in gluster. I don't think heketi should be "looking over the shoulder" of glusterd to make sure it manages the processes and volume state correctly.

Please reopen if you disagree and would like to discuss further.

**Comment by dkazhdan1** [comment]
Hi John
Thanks for looking into this
it appears however that the brick multiplexing is off for the volumes created by heketi

gluster vol get vol_f3c3ce57647d78d54bec5fd8359a594f all|grep multi

**Comment by phlogistonjohn** [comment]
Generally heketi doesn't control brick multiplexing directly. IIRC it's on by default if you use gluster in containers but it needs to be configured if gluster is installed on nodes directly.
