### ISSUE TITLE
Unable to export heketi db

### ISSUE THREAD

**Issue by SaravanaStorageNetwork** [heketi/heketi#1440]
### Kind of issue

 
 Bug

### Observed behavior
Unable to export heketi db

[root@crs-glusterfs-node3 heketi]# heketi db export --dbfile=/var/lib/heketi/heketi.db  --jsonfile=/tmp/heketi.json   
[heketi] ERROR 2018/11/27 05:08:23 /src/github.com/heketi/heketi/apps/glusterfs/dbcommon.go:189: Unable to open database: timeout
failed to dump db: Unable to open database: timeout
[root@crs-glusterfs-node3 heketi]# 

[root@crs-glusterfs-node3 heketi]# heketi --version 
Heketi 8.0.0

[root@crs-glusterfs-node3 heketi]# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.6 (Maipo)

[root@crs-glusterfs-node3 heketi]# rpm -qa | grep heketi 
heketi-client-8.0.0-1.el7rhgs.x86_64
heketi-8.0.0-1.el7rhgs.x86_64
[root@crs-glusterfs-node3 heketi]# 

ls -l /var/lib/heketi/heketi.db 
-rw-r--r--. 1 heketi heketi 131072 Nov 23 04:27 /var/lib/heketi/heketi.db

### Expected/desired behavior
should be able to export.

### Information about the environment:

heketi rpm - standalone environment -

**Comment by nixpanic** [comment]
Did you stop the heketi pod/service? I do not think it is possible to export the db when an active heketi service is reading/writing to it.

**Comment by SaravanaStorageNetwork** [comment]
@nixpanic  But I am just exporting the db. Is the db locked from reading by any other application ?  

I am not sure whether heketi was running, when I tried this command.I will try once again after stopping the heketi service.

**Comment by phlogistonjohn** [comment]
Please do retry after stopping heketi. It's most likely to be that. The DB can only be exported when heketi is stopped to make sure we get a 100% consistent view of the contents (it partially has to do with the way boltdb works).
For debugging / diagnostic purposes you can use `heketi-cli db dump` but you should not use this for db editing purposes.

**Comment by phlogistonjohn** [comment]
I'm like 99.9% sure that the last comment was accurate. Closing. Please reopen if needed.
