### ISSUE TITLE
Out of space No space

### ISSUE THREAD

**Issue by marlon617** [heketi/heketi#1443]
### Kind of issue

> Uncomment only one of these:
> 
> Bug
> Feature request

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): 
- Operating system used: 
- Heketi compiled from sources, as a package (rpm/deb), or container: 
- If container, which container image: 
- Using kubernetes, openshift, or direct install: 
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: 
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): 

### Other useful information

[heketi] INFO 2018/11/28 10:15:27 Periodic health check status: node e03ab0aa32363e2faf37a71ee48fce6f up=true
[heketi] INFO 2018/11/28 10:15:27 Cleaned 0 nodes from health cache
[negroni] Started POST /volumes
[heketi] INFO 2018/11/28 10:16:13 Allocating brick set #0
[heketi] ERROR 2018/11/28 10:16:13 heketi/apps/glusterfs/volume_entry_allocate.go:37:glusterfs.(*VolumeEntry).allocBricksInCluster: Minimum brick size limit reached.  Out of space.
[heketi] ERROR 2018/11/28 10:16:13 heketi/apps/glusterfs/operations_manage.go:89:glusterfs.AsyncHttpOperation: Create Volume Build Failed: No space
[negroni] Completed 500 Internal Server Error in 3.141383ms

# cat storageclass-gluster-heketi.yaml 
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gluster-heketi
  namespace: default
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://10.202.71.40:8080"
  restauthenabled: "false"

# heketi-cli topology info                    

Cluster Id: 368a884874740f153259bc570a237d46

    Volumes:

    Nodes:

        Node Id: 7863fd797aab2780c964f18441d7bf31
        State: online
        Cluster Id: 368a884874740f153259bc570a237d46
        Zone: 1
        Management Hostname: 10.0.2.102
        Storage Hostname: 10.0.2.102
        Devices:
                Id:1423e7ba18ad4b5188638b27b5d9cf17   Name:/dev/sdb            State:online    Size (GiB):9       Used (GiB):9       Free (GiB):0       
                        Bricks:
                                Id:29e74d76f6c85eba07787a8227b3136b   Size (GiB):1       Path: /var/lib/heketi/mounts/vg_1423e7ba18ad4b5188638b27b5d9cf17/brick_29e74d76f6c85eba07787a8227b3136b/brick
                                Id:2d20d557f587768807f7e637308f5aa4   Size (GiB):1       Path: /var/lib/heketi/mounts/vg_1423e7ba18ad4b5188638b27b5d9cf17/brick_2d20d557f587768807f7e637308f5aa4/brick
                                Id:31939fed02295d73925354b193d3778e   Size (GiB):1       Path: /var/lib/heketi/mounts/vg_1423e7ba18ad4b5188638b27b5d9cf17/brick_31939fed02295d73925354b193d3778e/brick
                                Id:3aaaf4fd0740d94f85eb32b24d17214b   Size (GiB):1       Path: /var/lib/heketi/mounts/vg_1423e7ba18ad4b5188638b27b5d9cf17/brick_3aaaf4fd0740d94f85eb32b24d17214b/brick
                                Id:8cc86ee52c5cce4bd0c80fd143056626   Size (GiB):1       Path: /var/lib/heketi/mounts/vg_1423e7ba18ad4b5188638b27b5d9cf17/brick_8cc86ee52c5cce4bd0c80fd143056626/brick
                                Id:9ace0306f48880dfe23fdc1a937b6db1   Size (GiB):1       Path: /var/lib/heketi/mounts/vg_1423e7ba18ad4b5188638b27b5d9cf17/brick_9ace0306f48880dfe23fdc1a937b6db1/brick
                                Id:c8dd0cb69d90f2a21e125acbff0328c2   Size (GiB):1       Path: /var/lib/heketi/mounts/vg_1423e7ba18ad4b5188638b27b5d9cf17/brick_c8dd0cb69d90f2a21e125acbff0328c2/brick
                                Id:c9936ae39acc28c659115af9e6d6e565   Size (GiB):1       Path: /var/lib/heketi/mounts/vg_1423e7ba18ad4b5188638b27b5d9cf17/brick_c9936ae39acc28c659115af9e6d6e565/brick
                                Id:eff533a8dfabf99a4244bfeb0f518343   Size (GiB):1       Path: /var/lib/heketi/mounts/vg_1423e7ba18ad4b5188638b27b5d9cf17/brick_eff533a8dfabf99a4244bfeb0f518343/brick

        Node Id: a9a23a2bb112e4371181bfac6d8ca597
        State: online
        Cluster Id: 368a884874740f153259bc570a237d46
        Zone: 1
        Management Hostname: 10.0.2.103
        Storage Hostname: 10.0.2.103
        Devices:
                Id:6cda5679aabe6156957544b3ff471273   Name:/dev/sdb            State:online    Size (GiB):9       Used (GiB):9       Free (GiB):0       
                        Bricks:
                                Id:15adb218c5c0c2d0b20d80beadec29fb   Size (GiB):1       Path: /var/lib/heketi/mounts/vg_6cda5679aabe6156957544b3ff471273/brick_15adb218c5c0c2d0b20d80beadec29fb/brick
                                Id:3eed734a73214668cdca6310634c1ab7   Size (GiB):1       Path: /var/lib/heketi/mounts/vg_6cda5679aabe6156957544b3ff471273/brick_3eed734a73214668cdca6310634c1ab7/brick
                                Id:643bd7f5382c7f40e1270da198ed8b32   Size (GiB):1       Path: /var/lib/heketi/mounts/vg_6cda5679aabe6156957544b3ff471273/brick_643bd7f5382c7f40e1270da198ed8b32/brick
                                Id:78095244490b3429b76e51f5dd499cc2   Size (GiB):1       Path: /var/lib/heketi/mounts/vg_6cda5679aabe6156957544b3ff471273/brick_78095244490b3429b76e51f5dd499cc2/brick
                                Id:85907a577872d5649cd8360eafb599a6   Size (GiB):1       Path: /var/lib/heketi/mounts/vg_6cda5679aabe6156957544b3ff471273/brick_85907a577872d5649cd8360eafb599a6/brick
                                Id:8d2bfeed79b0440486978c8f8c999be5   Size (GiB):1       Path: /var/lib/heketi/mounts/vg_6cda5679aabe6156957544b3ff471273/brick_8d2bfeed79b0440486978c8f8c999be5/brick
                                Id:a2751e1638f2c75fdf07169e91a104fb   Size (GiB):1       Path: /var/lib/heketi/mounts/vg_6cda5679aabe6156957544b3ff471273/brick_a2751e1638f2c75fdf07169e91a104fb/brick
                                Id:b0a2ef2cf57d2861fc5b613ae01a6459   Size (GiB):1       Path: /var/lib/heketi/mounts/vg_6cda5679aabe6156957544b3ff471273/brick_b0a2ef2cf57d2861fc5b613ae01a6459/brick
                                Id:eb825ec94696eda974e44d3d209d5baa   Size (GiB):1       Path: /var/lib/heketi/mounts/vg_6cda5679aabe6156957544b3ff471273/brick_eb825ec94696eda974e44d3d209d5baa/brick

        Node Id: e03ab0aa32363e2faf37a71ee48fce6f
        State: online
        Cluster Id: 368a884874740f153259bc570a237d46
        Zone: 1
        Management Hostname: 10.0.2.104
        Storage Hostname: 10.0.2.104
        Devices:
                Id:a1efcd412747340a00bae643c0b3a22e   Name:/dev/sdb            State:online    Size (GiB):9       Used (GiB):9       Free (GiB):0       
                        Bricks:
                                Id:0727d7b7ddead45a300f54c5b2f1201c   Size (GiB):1       Path: /var/lib/heketi/mounts/vg_a1efcd412747340a00bae643c0b3a22e/brick_0727d7b7ddead45a300f54c5b2f1201c/brick
                                Id:15eaa84e9eba9e1fa32131edff73dde3   Size (GiB):1       Path: /var/lib/heketi/mounts/vg_a1efcd412747340a00bae643c0b3a22e/brick_15eaa84e9eba9e1fa32131edff73dde3/brick
                                Id:2dedd9602911eb9ab286d07c0b07fd95   Size (GiB):1       Path: /var/lib/heketi/mounts/vg_a1efcd412747340a00bae643c0b3a22e/brick_2dedd9602911eb9ab286d07c0b07fd95/brick
                                Id:306a02d00be15fd80e4f17a2a0abd010   Size (GiB):1       Path: /var/lib/heketi/mounts/vg_a1efcd412747340a00bae643c0b3a22e/brick_306a02d00be15fd80e4f17a2a0abd010/brick
                                Id:8578f1905faef194410d0f933cfe60dd   Size (GiB):1       Path: /var/lib/heketi/mounts/vg_a1efcd412747340a00bae643c0b3a22e/brick_8578f1905faef194410d0f933cfe60dd/brick
                                Id:8cf088d33f1bf692e03e9ad330583838   Size (GiB):1       Path: /var/lib/heketi/mounts/vg_a1efcd412747340a00bae643c0b3a22e/brick_8cf088d33f1bf692e03e9ad330583838/brick
                                Id:a6bb062f091730d43b1b416d08f3dad3   Size (GiB):1       Path: /var/lib/heketi/mounts/vg_a1efcd412747340a00bae643c0b3a22e/brick_a6bb062f091730d43b1b416d08f3dad3/brick
                                Id:df95df5b1b808770e69d144b48b6e337   Size (GiB):1       Path: /var/lib/heketi/mounts/vg_a1efcd412747340a00bae643c0b3a22e/brick_df95df5b1b808770e69d144b48b6e337/brick
                                Id:e3a7deb4738efbec0836e81a38213716   Size (GiB):1       Path: /var/lib/heketi/mounts/vg_a1efcd412747340a00bae643c0b3a22e/brick_e3a7deb4738efbec0836e81a38213716/brick

# heketi-cli volume create --size=1 --name=test-volume1
Error: Failed to allocate new volume: No space

**Comment by Madhu-1** [comment]
> Id:1423e7ba18ad4b5188638b27b5d9cf17   Name:/dev/sdb            State:online    Size (GiB):9       Used (GiB):9       Free (GiB):0      

looks like there is no space available in the device to create more volumes

**Comment by marlon617** [comment]
你好，我有三个节点，每个节点的/dev/sdb空间为10g。
# heketi-cli topology info

Cluster Id: d584e2ab6b127afe57803abacaa54fee

    Volumes:

    Nodes:

        Node Id: 1f2dc9f73e8e4663a08f60ef2bef5a19
        State: online
        Cluster Id: d584e2ab6b127afe57803abacaa54fee
        Zone: 1
        Management Hostname: 10.0.2.102
        Storage Hostname: 10.0.2.102
        Devices:
                Id:c260aa500ec952004669adcf40d63261   Name:/dev/sdb            State:online    Size (GiB):9       Used (GiB):0       Free (GiB):9       
                        Bricks:

        Node Id: 3465711072a7e94e60ea49a47989b88a
        State: online
        Cluster Id: d584e2ab6b127afe57803abacaa54fee
        Zone: 1
        Management Hostname: 10.0.2.103
        Storage Hostname: 10.0.2.103
        Devices:
                Id:a02c0d6414fa888d357cfe5bb1e48dac   Name:/dev/sdb            State:online    Size (GiB):9       Used (GiB):0       Free (GiB):9       
                        Bricks:

        Node Id: 64656f7cbacf64623e05084b88afb84b
        State: online
        Cluster Id: d584e2ab6b127afe57803abacaa54fee
        Zone: 1
        Management Hostname: 10.0.2.104
        Storage Hostname: 10.0.2.104
        Devices:
                Id:a3801cee7b3bdb3dd51a21befe62251f   Name:/dev/sdb            State:online    Size (GiB):9       Used (GiB):0       Free (GiB):9       
                        Bricks:

执行完以下命令
# cat storageclass-gluster-heketi.yaml 
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gluster-heketi
  namespace: default
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://10.202.71.42:8080"
  restauthenabled: "false"


执行完pvc-gluster-heketi.yaml ，查看日志就出现如下错误
# cat pvc-gluster-heketi.yaml 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-gluster-heketi
  namespace: default
spec:
  storageClassName: gluster-heketi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

[heketi] ERROR 2018/11/29 02:02:44 heketi/apps/glusterfs/volume_entry_allocate.go:37:glusterfs.(*VolumeEntry).allocBricksInCluster: Minimum brick size limit reached.  Out of space.
[heketi] ERROR 2018/11/29 02:02:44 heketi/apps/glusterfs/operations_manage.go:89:glusterfs.AsyncHttpOperation: Create Volume Build Failed: No space
[negroni] Completed 500 Internal Server Error in 3.13228ms

是因为/dev/sdb空间不够吗？

**Comment by phlogistonjohn** [comment]
Not enough info for us to debug further and this issue has been idle for a while. Please retest with Heketi version 9 when it is released in the next couple of weeks and if the issue persists feel free to reopen this issue.

**Comment by lucian521** [comment]
@marlon617  我也同样问题， 请问你解决了吗？  能给发一下最后的解决方案吗？
