### ISSUE TITLE
device remove doesn't re-balance bricks

### ISSUE THREAD

**Issue by Rikbruggink** [heketi/heketi#1451]
### Kind of issue

 Bug

### Observed behavior
heketi cli doesn't re-balance bricks from device to be replaced

### Expected/desired behavior

allow for failed/offline removal of devices

### Details on how to reproduce (minimal and precise)

heketi-cli disable $id
heketi-cli remove $id
heketi-cli delete

### Information about the environment:

- Heketi version used:
 7 and 8
- Heketi compiled from sources, as a package (rpm/deb), or container: 
container
- If container, which container image: 
7 and 8

- Using kubernetes, openshift, or direct install:
openshift

- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: 
inside openshift

- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): 

openshift-ansible 

### Other useful information

initial deployed as heketi 5 but for more management db/device features upgraded to 7 and 8.
When the device is put in offline state it cant be removed because its not in a failed state.
When manually put in a failed state the device re-balance does nothing

### Debug log from delete-pending

[root@289e5ade4e01 heketi]# heketi db delete-pending-entries --dbfile heketi.db --debug
[heketi] INFO 2018/12/05 09:39:48 traversing through pending ops bucket to delete pending entries
[heketi] DEBUG 2018/12/05 09:39:48 /src/github.com/heketi/heketi/apps/glusterfs/db_operations.go:630: pendingops bucket
[heketi] INFO 2018/12/05 09:39:48
Pending Operation 1 Start
[heketi] INFO 2018/12/05 09:39:48 Found a pending device remove operation with id: dadc214b9c92b312f67b6dfd8bc16d2a and timestamp: 1544001640
[heketi] DEBUG 2018/12/05 09:39:48 /src/github.com/heketi/heketi/apps/glusterfs/db_operations.go:566: Found a pending remove device change with id: f8ad6aa027c39095865f27a3ea0ded55
[heketi] INFO 2018/12/05 09:39:48 Deleting device with id: f8ad6aa027c39095865f27a3ea0ded55
[heketi] INFO 2018/12/05 09:39:48 deviceEntry &{Entry:{State:offline} Info:{Device:{Name:/dev/sdc Tags:map[]} Storage:{Total:1453101056 Free:1073606656 Used:379494400} Id:f8ad6aa027c39095865f27a3ea0ded55} Bricks:[4b0180dd60c183eb121f45db9fb19f9e 4c366e0b68a75b8994ff99af3caca96d 4d6b76c49bbffd41bcb3a5f973e466ad 4fa2ba9c476e02337f089c01e6441397 54743cfa35c39e1c46a3f6cbbc972fef 587d41a361d28517c9d8893aa04fc76f 58a89ef1cb8d7f54d853791961d4875d 5a9fe247b43aded0bd205736f2dca24c 5af402288a0db685d4e4c92928a3ae6e 5bba58657910cdb96d27c81e0b52db64 5f8c83e0684f9094c0b4bfebeb96e587 5fae25e666dca9e7e632e09d1e72a230 65b5e25259a55af79ee19c054d1ad4df 7750dea6368fe8ea2a51b74f9a5c0f16 7bdd07d748cbc03cdc14f87d850efa88 7e8fd265161e1147f7dea8d4dc72a1f1 8289d4bd905cf8655a368714a7c457a9 89c72de497eea7e9469b82ebedeb0c48 8a73fb488f282b7503da52d4549d83b1 90413a37887eb55a2c669c931d3efc1f 90acc4dd898e8c7dd4d479cabbc24a26 93920e788690be4aa897b6f2ccf69819 956aed2c02b359260b707c7df9e0957b 9849ec34133e39b6d858c401d9597010 a0260054f073c91ec3258116b18ea42a a0be490aeabccbc40937683ef3fc3865 a2e6b1cec843386d8a69275f6274751c b3c2d78f14f56c0c837966319b464e29 b66f0a1a1e1ed356d3c1f342d2df1be9 b8e817c6eb043ad26e81cdd782aa308f bf4c2b3d9949997b0d2395ef79eba9f1 c06e5ffffc273c88556a1442c4f1409c c0fe386e73799a58c3269f495717b013 c656eaca7a3bc64aa28f3a796de78345 cbf94d797b71aaa05244af51420a83c9 ced5d968835868b28006b374474c479d da42410ed883fda2558008b7fc18340c daa707b039f8c9cc73e8d5455acf0b23 dc317facb268782ac2be50b1ed8eb17d dd6328d4f63c33badcff83b42a745ba9 df24f918295f540accaf410c43e54493 e25b00c27537bfd808e8c126e70c58a8 e484df95a6f1d089305a648a7dab8eb1 e8a7811e31d4dcc70af502ea6cbf94e2 e9f8c53840f3c6545e9c60b8180492e6 ea4c6bd550570db311fe18df99577c7a ed2041c5068677876405f6e92bab6aa5 f23bbaa45bd03dd2c148afc7f8c2cbc9 f439737a58cf8a87beb5f4a38d654214] NodeId:c0401dfa73c1cc67b8d2de0a50387c6b ExtentSize:4096}
[heketi] INFO 2018/12/05 09:39:48 USER ACTION REQUIRED: cleanup device:/dev/sdc on node:c0401dfa73c1cc67b8d2de0a50387c6b
[heketi] ERROR 2018/12/05 09:39:48 /src/github.com/heketi/heketi/apps/glusterfs/device_entry.go:168: device: f8ad6aa027c39095865f27a3ea0ded55 is not in failed state

**Comment by raghavendra-talur** [comment]
@Rikbruggink I don't think I understand the problem stated here fully yet.

1. The idea behind the device disable, device remove, device delete approach is this: heketi stops using the device for new bricks once disabled, it moves the bricks on the device to some other device when it is removed and device delete makes heketi forget the device forever. We don't have rebalance involved here because the device remove process is allowed once for bricks that are part of a replica volume. When we replace a brick from one device to another, we depend on gluster's replication system in AFR to copy the data back into the brick.

2. Also, I see that you have provided the output `heketi db delete-pending-entries --dbfile heketi.db --debug` command. It is not related to the above problem and we discourage the use of the command as it is buggy in some cases. We have removed the command in latest releases of heketi. 

Please tell us what your understanding of "rebalance" is and provide output `heketi-cli db dump` (with masking of private data if required) for us to provide next steps.

**Comment by phlogistonjohn** [comment]
No updates in a few months. Closing. Please reopen if this issue is still relevant to you.
