### ISSUE TITLE
Help needed to configure tls certs in heketi

### ISSUE THREAD

**Issue by chandidas** [heketi/heketi#1467]
In my Kubernetes I am trying to configure heketi with tls certs so that the interface between K8S controller-manager and Heketi is secured and heketi exposes https.

I mainly followed https://github.com/heketi/heketi/pull/1108/files PR to configure Heketi with self-signed certificates and Key. With the changes Heketi Pod has come up and "hello heketi" works with https.

However, the creation of a PVC is failing with the following message : *“x509: certificate signed by unknown authority”* and *“x509: cannot validate certificate for 10.0.xx.xx because it doesn’t contain any IP SANs”*. The heketi pod logs indicated a "TLS session error". I am having kubernetes version 1.11 in my setup and Heketi Pod version is v8.0.0

If anyone has configure tls certs to enable https in heketi in a Kubernetes cluster, could you please share if I need to make any other changes in Heketi and in K8S controller side. 

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): v8.0.0
- Operating system used: Ubuntu
- Heketi compiled from sources, as a package (rpm/deb), or container: Container
- If container, which container image: Taken from Dockerhub 
- Using kubernetes, openshift, or direct install: Kubernetes
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: Inside K8S
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): Other

**Comment by luckyfengyong** [comment]
@chandidas Hekiti golang CLI supports `NewClientTLS()` with `ClientTLSOptions`  (https://github.com/heketi/heketi/blob/v8.0.0/client/api/go-client/client.go#L105). To skip verification of server cert, caller just need specify `InsecureSkipVerify: true`. 

However it seems K8s glusterfs plugin does not call `NewClientTLS()` but `NewClient()`. You could submit PR to K8S to enhance glusterfs plugin to support TLS option.

**Comment by phlogistonjohn** [comment]
Indeed. This is quite out of the control of the heketi developers.

**Comment by amgads** [comment]
was it addressed by k8s? or heketi?

**Comment by amgads** [comment]
@luckyfengyong 
"specify InsecureSkipVerify: true" -- where is that done in the heketi.json file? same section as "enable_tls": true"

**Comment by amgads** [comment]
Tried adding the "InsecureSkipVerify": true,   to the heketi.json file and got the same error

  Warning  ProvisioningFailed  7s (x6 over 74s)  persistentvolume-controller  Failed to provision volume with StorageClass "glusterfs-storageclass-arbiter": failed to create volume: failed to create volume: Post https://10.254.0.101:8080/volumes: x509: certificate signed by unknown authority
---------
  "port": "8080",
  "use_auth": true,
  "enable_tls": true,
  "cert_file": "/etc/heketi/node.cert",
  "key_file": "/etc/heketi/node.key",
  "InsecureSkipVerify": true,
