### ISSUE TITLE
Publishing ARM images to Dockerhub

### ISSUE THREAD

**Issue by ljfranklin** [heketi/heketi#1470]
Looks like about a year ago y'all published the [heketi/heketi-rpi image](https://hub.docker.com/r/heketi/heketi-rpi/tags) to Dockerhub, but it hasn't seen any updates since. And it still looks like you have the cross-platform Dockerfile and scripts [here](https://github.com/heketi/heketi/blob/master/extras/docker/rpi/Dockerfile). Would it be possible to re-add the building and pushing of the ARM image back into your release process?

**Comment by phlogistonjohn** [comment]
Certainly, but none of the current active Heketi devs are working routinely with arm or raspberry pi. Volunteers interested in this topic would be welcome.

**Comment by ljfranklin** [comment]
@phlogistonjohn Maybe I'm misunderstanding, but I think you can build the ARM image from an x86_64 machine since [this Dockerfile](https://github.com/heketi/heketi/blob/master/extras/docker/rpi/Dockerfile#L2) uses one of the resin cross-platform images as a base. The [Overview](https://github.com/heketi/heketi/tree/master/extras/docker/rpi#overview) doc in that directory says as much: "Dockerfile and helper build script to build a Heketi container for Raspberry Pi from an x86_64 machine". I understand that testing may not be possible on an actual raspberry pi but I'd be happy with just getting the image pushed as part of the current release process. Could even add a disclaimer that the ARM image is provided "as-is" or similar.

**Comment by phlogistonjohn** [comment]
Right, it's not so much a technological issue as time management one. :-)
I have looked at that directory/script and it looks rather clunky and manual and not something we can just set it up and get running. If you are interested in helping maintain an updated version of the raspi build that would excellent and I think we'd certainly be interested in working with you on that.
I think the first steps would to be to enhance the build process such that the only external need to build that would be a Dockerfile. In other words, if we can get a fully containerized build process like we have for extras/docker/fromsource/.
I assume it ought to be possible to set up a build container that builds on x86 but generates the arm binaries and an arm based final image. If we can do that we can simply point a container registry at the right place and use the standard automation, and end the need for custom scripts.

**Comment by phlogistonjohn** [comment]
Stale issue. Closing.
