### ISSUE TITLE
Reported size by cloned volume from expanded one is half of its source 

### ISSUE THREAD

**Issue by labazza** [heketi/heketi#1471]
### Kind of issue

> Uncomment only one of these:
> 
> Bug

### Observed behavior
- Vol_A is created with size 50GB
- Vol_A is expanded by other 50GB so it's now in total 100GB
- Vol_A is cloned to Vol_B
- Vol_B is mounted, it contains the same files as Vol_A however df it's reporting 50GB, also used space is it's half
### Expected/desired behavior
Correct space usage being reported

### Details on how to reproduce (minimal and precise)
- create, expand, clone the volume

### Information about the environment:

- Heketi version used 8.0.0: 
- Operating system used: Centos 7.5.1804
- Heketi compiled from sources, as a package (rpm/deb), or container: rpm
- If container, which container image: 
- Using kubernetes, openshift, or direct install: direct install
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: 
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): 

### Other useful information
probably it's not something related to heketi itself but:
- could it be avoided with [feature request ](https://github.com/heketi/heketi/issues/783)?
- couldn't find documentation about the clone process under the hoods

**Comment by phlogistonjohn** [comment]
Stale issue. Closing.
