### ISSUE TITLE
Running device delete returns an error that a device is not in failed state, but deletes the device anyway

### ISSUE THREAD

**Issue by phlogistonjohn** [heketi/heketi#1478]
### Kind of issue

Bug

### Observed behavior

Running the "device delete" subcommand on an empty, but non-disabled device first prints an error message indicating that the device is "not in failed state" which implies the device can't be deleted at this time. However, on the back end the command has already run the vgremove command and if the command is run a 2nd time it errors out running the vgremove command again.

Combined server logs and commands below:
```
$ ./heketi-cli device delete 6108d71d8b0bea
8f1f27ae8d53f69d87
[heketi] INFO 2019/01/03 13:48:41 Deleting device 6108d71d8b0bea8f1f27ae8d53f69d87 on
 node 88891699f3de4a84eb8bf696e648c15f
[negroni] 2019-01-03T13:48:41-05:00 | 202 |      242.051µs | localhost:8080 | DELETE 
/devices/6108d71d8b0bea8f1f27ae8d53f69d87   
[asynchttp] INFO 2019/01/03 13:48:41 asynchttp.go:288: Started job fd87e308cee065fa7d
61d0323afcc2a3
[negroni] 2019-01-03T13:48:41-05:00 | 200 |      12.383µs | localhost:8080 | GET /que
ue/fd87e308cee065fa7d61d0323afcc2a3
[cmdexec] DEBUG 2019/01/03 13:48:42 heketi/pkg/remoteexec/ssh/ssh.go:187:ssh.(*SshExec).ExecCommands: Ran command [/bin/bash -c 'sudo vgremove -qq vg_6108d71d8b0bea8f1f27ae8d53f69d87'] on 192.168.10.100:22: Stdout []: Stderr []
[cmdexec] DEBUG 2019/01/03 13:48:42 heketi/pkg/remoteexec/ssh/ssh.go:187:ssh.(*SshExec).ExecCommands: Ran command [/bin/bash -c 'sudo pvremove -qq '/dev/vdd''] on 192.168.10.100:22: Stdout []: Stderr []
[cmdexec] ERROR 2019/01/03 13:48:42 heketi/pkg/remoteexec/ssh/ssh.go:191:ssh.(*SshExec).ExecCommands: Failed to run command [/bin/bash -c 'sudo ls /var/lib/heketi/mounts/vg_6108d71d8b0bea8f1f27ae8d53f69d87'] on 192.168.10.100:22: Err[Process exited with status 2]: Stdout []: Stderr [ls: cannot access /var/lib/heketi/mounts/vg_6108d71d8b0bea8f1f27ae8d53f69d87: No such file or directory
]
[heketi] ERROR 2019/01/03 13:48:42 heketi/apps/glusterfs/device_entry.go:169:glusterfs.(*DeviceEntry).Delete: device: 6108d71d8b0bea8f1f27ae8d53f69d87 is not in failed state
[heketi] ERROR 2019/01/03 13:48:42 heketi/apps/glusterfs/app_device.go:286:glusterfs.(*App).DeviceDelete.func2.1: device: 6108d71d8b0bea8f1f27ae8d53f69d87 is not in failed state
[asynchttp] INFO 2019/01/03 13:48:42 asynchttp.go:292: Completed job fd87e308cee065fa7d61d0323afcc2a3 in 587.894874ms
[negroni] 2019-01-03T13:48:42-05:00 | 500 |      126.145µs | localhost:8080 | GET /queue/fd87e308cee065fa7d61d0323afcc2a3 
Error: device: 6108d71d8b0bea8f1f27ae8d53f69d87 is not in failed state

$ ./heketi-cli device delete 6108d71d8b0bea8f1f27ae8d53f69d87
[heketi] INFO 2019/01/03 13:48:46 Deleting device 6108d71d8b0bea8f1f27ae8d53f69d87 on node 88891699f3de4a84eb8bf696e648c15f
[negroni] 2019-01-03T13:48:46-05:00 | 202 |      234.001µs | localhost:8080 | DELETE /devices/6108d71d8b0bea8f1f27ae8d53f69d87 
[asynchttp] INFO 2019/01/03 13:48:46 asynchttp.go:288: Started job 4f2d6acbc333bb78145aa86e7a9c47ba
[negroni] 2019-01-03T13:48:46-05:00 | 200 |      14.546µs | localhost:8080 | GET /queue/4f2d6acbc333bb78145aa86e7a9c47ba 
[cmdexec] ERROR 2019/01/03 13:48:46 heketi/pkg/remoteexec/ssh/ssh.go:191:ssh.(*SshExec).ExecCommands: Failed to run command [/bin/bash -c 'sudo vgremove -qq vg_6108d71d8b0bea8f1f27ae8d53f69d87'] on 192.168.10.100:22: Err[Process exited with status 5]: Stdout []: Stderr [  Volume group "vg_6108d71d8b0bea8f1f27ae8d53f69d87" not found
  Cannot process volume group vg_6108d71d8b0bea8f1f27ae8d53f69d87
]
[cmdexec] ERROR 2019/01/03 13:48:46 heketi/executors/cmdexec/device.go:159:cmdexec.(*CmdExecutor).removeDevice: Failed to delete device /dev/vdd with id 6108d71d8b0bea8f1f27ae8d53f69d87 on host 192.168.10.100:   Volume group "vg_6108d71d8b0bea8f1f27ae8d53f69d87" not found
  Cannot process volume group vg_6108d71d8b0bea8f1f27ae8d53f69d87
[asynchttp] INFO 2019/01/03 13:48:46 asynchttp.go:292: Completed job 4f2d6acbc333bb78145aa86e7a9c47ba in 267.11195ms
[negroni] 2019-01-03T13:48:47-05:00 | 500 |      108.359µs | localhost:8080 | GET /queue/4f2d6acbc333bb78145aa86e7a9c47ba
Error: Failed to delete device /dev/vdd with id 6108d71d8b0bea8f1f27ae8d53f69d87 on host 192.168.10.100:   Volume group "vg_6108d71d8b0bea8f1f27ae8d53f69d87" not found
  Cannot process volume group vg_6108d71d8b0bea8f1f27ae8d53f69d87

```

### Expected/desired behavior

If all devices should be failed/removed first the command should *not* make any changes on the backend before checking the state of the heketi db. 

### Details on how to reproduce (minimal and precise)

Run `heketi-cli device delete <id>` twice on an device empty of bricks.

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): master
- Heketi compiled from sources, as a package (rpm/deb), or container: source

**Comment by phlogistonjohn** [comment]
The fix for this issue ought to be fairly straight forward. There are checks in DeviceEntry.Delete that should be performed before the executor is called (it checks for device state and if the device has bricks), but the api endpoint in app_device.go only checks one of those conditions.
I would move the checks in Delete to a new CheckDelete function and call that function from both App.DeviceDelete and DeviceEntry.Delete.

**Comment by phlogistonjohn** [comment]
@Madhu-1 PTAL. A brief strategy for resolving this issue is posted above.

**Comment by Madhu-1** [comment]
@phlogistonjohn how to add the test case for the above changes?
* add device
* delete device if the device is not in failed mode
* add bricks 
* set device to failed state (but can we set the device state to fail if it contains bricks)?
* delete device when it contains bricks.

**Comment by phlogistonjohn** [comment]
> @phlogistonjohn how to add the test case for the above changes?
> 
>     * add device
> 

Generally, the test setup code handles that for you, but if you want explicit control of this you can either remove and re-add a device (its fine to just grab one at random).

>     * delete device if the device is not in failed mode
> 

For this case just ensure the device is not in the failed state and just call delete. Then assert that the underlying vg is still on the node.

>     * add bricks
> 
>     * set device to failed state (but can we set the device state to fail if it contains bricks)?
> 

Use the SetState api call (look in the teardown function for examples). You can set the device to failed if it contains bricks, but this will trigger an evacuation of the bricks from the device.

>     * delete device when it contains bricks.

That's tricky. Normally setting the device to failed (heketi-cli device remove) will remove all bricks from the device. You could try to make that fail by using the new error injection executor but that may just end up being more work than its worth.
You may simply choose to do both unit and functional tests rather than trying to cover all conditions in the functional test.

**Comment by phlogistonjohn** [comment]
@Madhu-1 any progress? I'd like to make this part of the v9 milestone and that decision will be easier if you've got any stuff wrt this issue.

**Comment by Madhu-1** [comment]
@phlogistonjohn i am not able to Figure out how to add testcases for this one, for me it may take more time, would you like to send a patch for this?
