### ISSUE TITLE
Device resync results in usage values that don't fully match size used by bricks

### ISSUE THREAD

**Issue by phlogistonjohn** [heketi/heketi#1484]
### Kind of issue
Bug

### Observed behavior

The free size values returned by LVM do not exactly match the free size values calculated by heketi when it is placing/saving bricks. This issue does not appear if you only ever create and delete volumes via the heketi operations. However, if you run the "device resync" sub-command it will take new total and free size values from the VG information provided by LVM.

We recently observed that LVM appears to be returning free size values smaller than what heketi assumes. We suspect this may have something to do with the "lvol0_pmspare" items, but more research is needed.

Regardless of the cause, running device resync may cause tools such as our internal consistency checks / dbconsistency.py tool to report that the sum of the sizes of the bricks do not match the used size of the device, leading to confusion.

For devices that are not near full this should not be a major issue but for devices that are near full it might lead heketi to make suboptimal placement choices.

### Expected/desired behavior

Heketi internal counters should not contradict the values provided by LVM. If we need to keep counters we either need to keep them in sync with the LVM results or correct heketi's internal calculation to interoperate better with LVM.

### Details on how to reproduce (minimal and precise)

* Create volumes on a set of devices
* Check db is consistent wrt brick sizes and overall device used size
* Run device resync
* Check db is consistent wrt brick sizes and overall device used size - expected to not match

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): master
- LVM version: lvm2-2.02.180-10.el7_6.2.x86_64
- Linux kernel version: 3.10.0-957.1.3.el7.x86_64

**Comment by wangyp0701** [comment]
I have this problem.

[root@node-1 glusterfs-hekiti]# heketi-cli db check
{
    "clusters": {
        "total": 1,
        "pending": 0,
        "ok": 1,
        "notok": 0,
        "inconsistencies": null
    },
    "volumes": {
        "total": 7,
        "pending": 0,
        "ok": 7,
        "notok": 0,
        "inconsistencies": null
    },
    "bricks": {
        "total": 21,
        "pending": 0,
        "ok": 21,
        "notok": 0,
        "inconsistencies": null
    },
    "nodes": {
        "total": 3,
        "pending": 0,
        "ok": 3,
        "notok": 0,
        "inconsistencies": null
    },
    "devices": {
        "total": 3,
        "pending": 0,
        "ok": 0,
        "notok": 3,
        "inconsistencies": [
            "Device 806c5e4e2825228ba628f4cdabba6496 size values differ Used(17960960) != aggregateBricksSize(17932288)",
            "Device c00780f4a8c58fe23d062157ee570b7e size values differ Used(17960960) != aggregateBricksSize(17932288)",
            "Device f5a8d3ffacbb0447f7a341f41454b1de size values differ Used(17960960) != aggregateBricksSize(17932288)"
        ]
    },
    "blockvolumes": {
        "total": 0,
        "pending": 0,
        "ok": 0,
        "notok": 0,
        "inconsistencies": null
    },
    "dbattributes": {
        "total": 0,
        "pending": 0,
        "ok": 0,
        "notok": 0,
        "inconsistencies": null
    },
    "pendingoperations": {
        "total": 0,
        "pending": 0,
        "ok": 0,
        "notok": 0,
        "inconsistencies": null
    },
    "totalinconsistencies": 3
}

**Comment by phlogistonjohn** [comment]
As heketi is now in maintenance mode, and only accepting major bug and security related fixes, we do not expect to implement this change.

**Comment by pbodam** [comment]
anybody have solution to this issue  ?
