### ISSUE TITLE
Incorrect Readme

### ISSUE THREAD

**Issue by kesterriley** [heketi/heketi#1485]
### Kind of issue

> Uncomment only one of these:
> 
 Bug
> Feature request

### Observed behavior

The readme file in heketi/extras/kubernetes/ says to run 

kubectl create -f deploy-heketi-deployment.json

However I can not find that file in the directory.

I assume it should be this file heketi-deployment.json ?

### Expected/desired behavior

The correct information in the Readme

### Details on how to reproduce (minimal and precise)

view the readme file and look in the folder that is cloned from git

**Comment by phlogistonjohn** [comment]
Please look into using something such as [gluster-kubernetes](https://github.com/gluster/gluster-containers) for deployment rather than doing it manually. I didn't even know this readme existed and it is old and out of date.
