### ISSUE TITLE
how can I use heketi to mount existed data or files in gluster?

### ISSUE THREAD

**Issue by arrowfeng** [heketi/heketi#1490]
I have some existed data on one host, now I want transport these data to another host that installed heketi+gluster , then mount in kubernetes. 
what should I do?

**Comment by phlogistonjohn** [comment]
Based on this description, I think you probably just need to copy the data in question into a new volume that you create using a PVC (or heketi cli). You might perform the copy manually using something like rsync or scp or you could create a k8s job to mount the PV and perform the copy using those same tools.

If you're looking for something more fancy, like geo-replication, than that's not something heketi directly supports today. You'd have to set up the gluster parts manually and that's not something I have any personal experience with so I'm afraid I can't help much there.

**Comment by arrowfeng** [comment]
I got it， thank you！
