### ISSUE TITLE
Wrongly report "Minimum brick size limit reached", report "No space" is better

### ISSUE THREAD

**Issue by Wade201801** [heketi/heketi#1494]
### Kind of issue

> Uncomment only one of these:
> 
Bug
> Feature request

### Observed behavior
1. mount glusterfs volume 2G;
2. deploy pod using glusterfs  space 1G
3. resize pod's pvc from 1G to 2G.  heketi log shows error “Minimum brick size limit reached.  Out of space.”
```
[heketi] DEBUG 2019/01/16 07:38:49 /src/github.com/heketi/heketi/apps/glusterfs/app_volume.go:284: In VolumeExpand
[heketi] DEBUG 2019/01/16 07:38:49 /src/github.com/heketi/heketi/apps/glusterfs/app_volume.go:295: Msg: {1}
[heketi] DEBUG 2019/01/16 07:38:49 /src/github.com/heketi/heketi/apps/glusterfs/app_volume.go:307: Size: 1
[negroni] Completed 202 Accepted in 7.501442ms
[asynchttp] INFO 2019/01/16 07:38:49 asynchttp.go:125: Started job a29133f99b0e4731321ee84abbf35cd5
[heketi] INFO 2019/01/16 07:38:49 Expanding volume b8d056d46a7120e7d8d4da98f813d23a
[heketi] DEBUG 2019/01/16 07:38:49 /src/github.com/heketi/heketi/apps/glusterfs/volume_entry_allocate.go:44: brick_size = 1048576
[heketi] DEBUG 2019/01/16 07:38:49 /src/github.com/heketi/heketi/apps/glusterfs/volume_entry_allocate.go:45: sets = 1
[heketi] DEBUG 2019/01/16 07:38:49 /src/github.com/heketi/heketi/apps/glusterfs/volume_entry_allocate.go:46: num_bricks = 2[heketi] INFO 2019/01/16 07:38:49 brick_num: 0
[heketi] DEBUG 2019/01/16 07:38:49 /src/github.com/heketi/heketi/apps/glusterfs/volume_entry_allocate.go:398: 0 / 2[heketi] DEBUG 2019/01/16 07:38:49 /src/github.com/heketi/heketi/apps/glusterfs/device_entry.go:411: device 1b442fcb1cd6cd4fad9977c490f31f1b[905216] > required size [1056768] ?
[heketi] DEBUG 2019/01/16 07:38:49 /src/github.com/heketi/heketi/apps/glusterfs/device_entry.go:411: device d9788e484c7ff3211d775d79280cf67b[1961984] > required size [1056768] ?
[negroni] Started GET /queue/a29133f99b0e4731321ee84abbf35cd5[negroni] Completed 200 OK in 1.042476ms
[heketi] DEBUG 2019/01/16 07:38:49 /src/github.com/heketi/heketi/apps/glusterfs/volume_entry_allocate.go:398: 1 / 2[heketi] DEBUG 2019/01/16 07:38:49 /src/github.com/heketi/heketi/apps/glusterfs/device_entry.go:411: device 55aa1bb7da9214020f92d9ea1ac47346[905216] > required size [1056768] ?
[heketi] DEBUG 2019/01/16 07:38:49 /src/github.com/heketi/heketi/apps/glusterfs/volume_entry_allocate.go:365: Error detected.  Cleaning up volume b8d056d46a7120e7d8d4da98f813d23a: Len(1) 
[heketi] DEBUG 2019/01/16 07:38:49 /src/github.com/heketi/heketi/apps/glusterfs/volume_entry_allocate.go:57: No space, re-trying with smaller brick size
[heketi] ERROR 2019/01/16 07:38:49 /src/github.com/heketi/heketi/apps/glusterfs/volume_entry_allocate.go:38: Minimum brick size limit reached.  Out of space.
[heketi] ERROR 2019/01/16 07:38:49 /src/github.com/heketi/heketi/apps/glusterfs/app_volume.go:335: Failed to expand volume b8d056d46a7120e7d8d4da98f813d23a
[asynchttp] INFO 2019/01/16 07:38:49 asynchttp.go:129: Completed job a29133f99b0e4731321ee84abbf35cd5 in 41.962835ms
[negroni] Started GET /queue/a29133f99b0e4731321ee84abbf35cd5
[negroni] Completed 500 Internal Server Error in 140.394µs
```

### Expected/desired behavior
apps/glusterfs/volume_entry_allocate.go line 55
when brick size is already reach BrickMinSize, should not re-try because this will gave user imprecise error msg.

### Details on how to reproduce (minimal and precise)
1. mount glusterfs volume 2G;
2. deploy pod using glusterfs  space 1G
3. resize pod's pvc from 1G to 2G. 

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master):  v7.0.0
- Operating system used: Red Hat Enterprise Linux Server release 7.5 (Maipo)
- Heketi compiled from sources, as a package (rpm/deb), or container: container
- If container, which container image:  build heketi ourself, dockerfile is
FROM bcmt-base:latest

RUN mkdir -p /heketi-v7.0.0 && yum --setopt=tsflags=nodocs -y install util-linux && \
    rm -rf /var/cache/yum

COPY heketi/* /usr/bin/
COPY heketi-v7.0.0/heketi/* /heketi-v7.0.0/
COPY heketi*.sh /

CMD /heketi_start.sh
- Using kubernetes, openshift, or direct install:  kubernetes
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: inside
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): custom

**Comment by phlogistonjohn** [comment]
Just to confirm this was a volume expansion use case, and the issue you have is that the error message is something like "Minimum brick size limit reached.  Out of space." instead of "No Space"?

**Comment by Wade201801** [comment]
> 
> 
> Just to confirm this was a volume expansion use case, and the issue you have is that the error message is something like "Minimum brick size limit reached. Out of space." instead of "No Space"?

Yes, I think "No Space" error message is better for this case. Since  "Minimum brick size limit reached. Out of space." mislead me to a wrong debug way, but actually it's "No Space".

**Comment by Wade201801** [comment]
> 
> 
> Just to confirm this was a volume expansion use case, and the issue you have is that the error message is something like "Minimum brick size limit reached. Out of space." instead of "No Space"?

And until I set log level of heketi to debug, I found there's actually "No Space" error.

**Comment by phlogistonjohn** [comment]
We do not plan on making this change. Closing issue. Please reopen if this issue is still relevant to you.
