### ISSUE TITLE
 Why is my hard drive capacity reduced by half?

### ISSUE THREAD

**Issue by arrowfeng** [heketi/heketi#1499]
this is my topology：
--------------------------------
```
{                                                  
  "clusters": [                                   
     {                                            
         "nodes": [                               
            {                                     
                "node": {                         
                   "hostnames":{                  
                       "manage": [                
                               "192.168.88.133"   
                       ],                         
                       "storage": [               
                               "192.168.88.133"   
                       ]                          
                   },                             
                   "zone": 1                      
                },                                
               "devices": [                       
                       "/dev/sdb"                 
               ]                                  
            },                                    
            {                                     
                "node": {                         
                   "hostnames":{                  
                       "manage": [                
                               "192.168.88.134"   
                       ],                         
                       "storage": [               
                               "192.168.88.134"   
                       ]                          
                   },                             
                   "zone": 1                      
                },                                
               "devices": [                       
                       "/dev/sdb"                 
               ]                                  
            }                                     
         ]                                        
       }                                          
  ]                                               
  }
```
----------------------------------
every hard disk have 1T ,then i exec  “heketi-cli topology load --json=topology_demo.json”，my disk reduce by half.why ?
![image](https://user-images.githubusercontent.com/20623365/51316742-89249680-1a90-11e9-84c1-949b04c6023e.png)

**Comment by nixpanic** [comment]
That is very strange. What is the output of 'lsblk'?

**Comment by arrowfeng** [comment]
> That is very strange. What is the output of 'lsblk'?
this
![image](https://user-images.githubusercontent.com/20623365/51361921-8f585880-1b0c-11e9-8796-92abfaf63c96.png)

**Comment by phlogistonjohn** [comment]
Hi @arrowfeng, could you please confirm that you've configured heketi with an executor such as sshexec or kubeexec and that you're not using the "mock" executor? This parameter is "executor" in the "glusterfs" section in the config json file.
I ask because 500GB just so happens to be the size of all devices returned by the mock executor so that's a bit suspicious.

**Comment by arrowfeng** [comment]
> Hi @arrowfeng, could you please confirm that you've configured heketi with an executor such as sshexec or kubeexec and that you're not using the "mock" executor? This parameter is "executor" in the "glusterfs" section in the config json file.
> I ask because 500GB just so happens to be the size of all devices returned by the mock executor so that's a bit suspicious.

Hello,this is my configuration...
![image](https://user-images.githubusercontent.com/20623365/51420966-b11c1300-1bd2-11e9-9d61-14d33efef000.png)

when I set  capacity of the hard disk is 100Gb, it display 50Gb...

**Comment by phlogistonjohn** [comment]
As I suspected you have the "mock" executor loaded. You can't use the "mock" executor with a real cluster, it does nothing and gives back fake results for testing purposes.
You need to configure heketi with either the "ssh" or "kubernetes" executors to actually use the storage on your systems.
If you are using heketi with kubernetes I strongly suggest deploying everything with [gluster-kubernetes](https://github.com/gluster/gluster-kubernetes), especially if you've never configured heketi before.
If you're not running kubernetes or you feel you absolutely must run heketi standalone you need to carefully configure it to match your environment.

**Comment by nixpanic** [comment]
@arrowfeng what is the status of this issue? I think John have you a quite complete reply. Has that been sufficient for you to continue? If so, please close this issue.

**Comment by phlogistonjohn** [comment]
Closing issue. Please reopen if needed.
