### ISSUE TITLE
heketi replica:3 limit

### ISSUE THREAD

**Issue by aigars-github** [heketi/heketi#1524]
### Kind of issue
 Feature request

### Observed behavior
When specifying replica count more than 3 heketi-cli gives an error "Invalid replica value"

### Expected/desired behavior
Create 4-way (or more) replicated volume

### Details on how to reproduce (minimal and precise)
heket-cli volume create --replica=4 --size=100

### Information about the environment:
Single Openshift instance distributed over two data-centers with multiple redundant gluster nodes in each data-center

### Other useful information
The limit (3) is hardcoded in app_volume.go and wondering what would happen if it increased?

**Comment by phlogistonjohn** [comment]
We could certainly look into it, but I'm curious as to why you feel that three is not a sufficient number of replicas.

**Comment by mgm3232** [comment]
For example when you have a four nodes gluster on two sites configuration (two nodes per site) and you want to create a gluster spread on the four nodes that is going to hold a total site failure.

**Comment by abessifi** [comment]
What is the best configuration/architecture to replicate data with Gluster and Heketi across two sites and be able to handle failover and failback ? is it just to have 4-way replication with 4 nodes (two per site) ? If we lose a site the quorum can be maintained in the other site ?

**Comment by mgm3232** [comment]
I know is is not the best way, but one could simply force the volumes to go RW and still have two replicas, not just one (in the case of 3 replicas with 2 in a site and 1 in other, and the first site would go down)

**Comment by wlkisaki** [comment]
We have the same problem as @mgm3232.
I looked into the code and I changed it to a higher number. After compilation and re-installation the server is happy to accept a higher number than 3. Gluster doesn't seem to have any problems and overall the setup works fine in our test-environment.
So, what would be the issue to just make this a higher number or even make it configurable?

**Comment by imranrazakhan** [comment]
I tried to install from OpenShift and Heketi is complaining about replica:4, is this upper limit or will it work for replica:6?

**Comment by phlogistonjohn** [comment]
Probably never going to happen. Someone outside the current team would need to take this up if there is a demand for it. Closing this issue, reopen if there's demand but it will probably just go stale again.

**Comment by zerols** [comment]
If i use replicated only Less than 3?   If use replicated 3 and shutdown 2 of 3 node, create pvc use storageclass can work normal?
