### ISSUE TITLE
Unable to start 32bits apps over Heketi Dynamic Storage Kubernetes

### ISSUE THREAD

**Issue by yoliander** [heketi/heketi#1525]
### Kind of issue

> Uncomment only one of these:
> 
Bug
> Feature request

### Observed behavior
When I install oracle-client 32 bits over a local fs (ext4) this works correctly, but when I install over a heketi provisioned dynamic storage in kubernetes, oracle client fail...

### Details on how to reproduce (minimal and precise)

* Install 32bit oracle client in a PVC provided by heketi
* Try to run tnsping ( fail )

* Install 32bit oracle client in local fs (ext4) 
* Try to run tnsping ( it works)

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master):  v8.0.0
- Operating system used: Oracle Linux Server release 7.6
- Heketi compiled from sources, as a package (rpm/deb), or container: Sources 
- If container, which container image: 
- Using kubernetes, openshift, or direct install: Kubernetes
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: Gluster is inside kubernetes, but like nodes, not like PODs
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): gk-deploy

### Other useful information

I find a lot of information about that.

I think this is because Heketi create the devices by default with XFS and inode64 enabled in Gluster.

More info:

https://support.oracle.com/epmos/faces/DocumentDisplay?_afrLoop=472996614945942&parent=EXTERNAL_SEARCH&sourceId=PROBLEM&id=2333923.1&_afrWindowMode=0&_adf.ctrl-state=12zephgirh_4

Resume of the doc:

This may be the result of changing the default file system of Red Hat Enterprise Linux 7 or Oracle Linux 7 from ext4 to XFS.  Since XFS manages files with inode numbers of 64 bits in length, software that does not support them may not operate properly.  Some system calls, such as 32-bit stat () and readdir (), can only handle inode numbers less than 2 to the power of 32.  However, in XFS, the inode number of the file may exceed 2 32 powers.  If the inode number of the target file exceeds 2 32, stat () or readdir () will result in an error.  Software using these system calls will be affected.

Therefore, prepare the environment of the following file system in order to do 32 bit Oracle client.
· Mount XFS with -o inode32
· Mounted with ext4

**Comment by nixpanic** [comment]
Wow, there is still software that can not handle 64-bit inodes!? This is very surprising as there are (since **many** years) updated syscalls on 32-bit architectures that make this possible without requiring changes to the filesystem.

This is not really a Heketi issue, but more of a configuration option for Gluster itself. From `man mount.glusterfs`:

```
       enable-ino32=BOOL
              Use  32-bit  inodes  when mounting to workaround broken applica‐
              tions that don't support 64-bit inodes
```

You can change the mount options for a PVC by editing the PV and adding `enable-ino32` made it work:

```
$ kubectl get pvc/check-mount-options
NAME                  STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
check-mount-options   Bound     pvc-99b8cd23-368a-11e9-b1ed-90d2c40533a9   1Gi        RWX            glusterfile    2m
$ kubectl edit pv/pvc-99b8cd23-368a-11e9-b1ed-90d2c40533a9
...
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    ...
    volume.beta.kubernetes.io/mount-options: auto_unmount,enable-ino32
  ...
```

After

1. deleting the pod that consumes the PVC
1. confirming kubelet unmounts the PV on the node where the pod was running
1. and starting the pod

check the node where the pod gets started, and the `glusterfs` process responsible for the mounting should now have `--enable-ino32` on the commandline (check with `ps ax | grep -w ino32`).

You can also add `enable-ino32` to the `mountOptions` in the StorageClass as shown in the [kubernetes docs](https://kubernetes.io/docs/concepts/storage/storage-classes/#the-storageclass-resource).

**Comment by yoliander** [comment]
Thx Nix

> $ kubectl get pvc/check-mount-options
NAME                  STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
check-mount-options   Bound     pvc-99b8cd23-368a-11e9-b1ed-90d2c40533a9   1Gi        RWX            glusterfile    2m
$ kubectl edit pv/pvc-99b8cd23-368a-11e9-b1ed-90d2c40533a9
...
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    ...
    volume.beta.kubernetes.io/mount-options: auto_unmount,enable-ino32
  

 ...

This works for me ;P

**Comment by yoliander** [comment]
Thx Nix.

That works for me ;P

**Comment by phlogistonjohn** [comment]
Good to hear it worked for you. Since it sounds like the question was fully answered I'm closing the issue. Feel free to re-open it if you have any followup questions.

**Comment by yoliander** [comment]
Hi again, and sorry for re-open the issue, but i'm having problems with the mount options:

This is my Storage Class:

```
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  creationTimestamp: "2019-02-22T15:28:38Z"
  name: gluster-heketi-training
  resourceVersion: "7897491"
  selfLink: /apis/storage.k8s.io/v1/storageclasses/gluster-heketi-training
  uid: 86dc9425-36b6-11e9-9966-0a580aed162d
mountOptions:
- enable-ino32
parameters:
  resturl: http://heketi:1234
provisioner: kubernetes.io/glusterfs
reclaimPolicy: Delete
volumeBindingMode: Immediate

```

And this is my pvc:

``` 
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    Description: 'Gluster-Internal: Dynamically provisioned PV'
    gluster.kubernetes.io/heketi-volume-id: 1a1de39c6143ff6951e24d544cb4fcfe
    gluster.org/type: file
    kubernetes.io/createdby: heketi-dynamic-provisioner
    pv.beta.kubernetes.io/gid: "2009"
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/provisioned-by: kubernetes.io/glusterfs
    volume.beta.kubernetes.io/mount-options: auto_unmount
  creationTimestamp: "2019-03-06T17:09:58Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: pvc-a76f53b7-4032-11e9-a751-0a580aed162d
  resourceVersion: "10890646"
  selfLink: /api/v1/persistentvolumes/pvc-a76f53b7-4032-11e9-a751-0a580aed162d
  uid: abbd5441-4032-11e9-a751-0a580aed162d
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 20Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: training-fs-claim
    namespace: default
    resourceVersion: "10890613"
    uid: a76f53b7-4032-11e9-a751-0a580aed162d
  glusterfs:
    endpoints: glusterfs-dynamic-training-fs-claim
    path: vol_1a1de39c6143ff6951e24d544cb4fcfe
  mountOptions:
  - enable-ino32
  persistentVolumeReclaimPolicy: Delete
  storageClassName: gluster-heketi-training
```

I put the mount options in the storage class and pvc yaml.

But the PV is still created without mountOptions.

do I need edit the PV every time I request a PVC ?

**Comment by yoliander** [comment]
@nixpanic 
@phlogistonjohn 

Could you help me with this please?

**Comment by phlogistonjohn** [comment]
To verify, you are saying that mount options works if you edit the pv but not for new PVs created via PVC even if you put it in the storageclass?

**Comment by yoliander** [comment]
> To verify, you are saying that mount options works if you edit the pv but not for new PVs created via PVC even if you put it in the storageclass?

yes, that is !

**Comment by phlogistonjohn** [comment]
I gave the glusterfs support in k8s a quick look over and it seems as if the PV should get a copy of the mountoptions from the storageclass (line looks like: `pv.Spec.MountOptions = p.options.MountOptions`).
So I'm not sure where things could be going wrong for you.
@humblec, you are a lot more familiar with k8s side of things than I am. Any thoughts?

**Comment by yoliander** [comment]
This is my storageclass.yaml


```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gluster-heketi-training
provisioner: kubernetes.io/glusterfs
reclaimPolicy: Delete
mountOptions:
  - enable-ino32
parameters:
  resturl: "http://192.168.6.2:33221"
allowVolumeExpansion: true
```

And this is my pvc.yaml

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: training-fs-claim
  labels:
    environment: training
    # siebel-service: batch
  annotations:
   volume.beta.kubernetes.io/storage-class: gluster-heketi
   volume.beta.kubernetes.io/mount-options: auto_unmount,enable-ino32
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
```

**Comment by yoliander** [comment]
I have GlusterFS server and Client version: 3.12

**Comment by nixpanic** [comment]
Are you using the glusterfs file provisioner from the https://github.com/kubernetes-incubator/external-storage/tree/master/gluster/file ? It seems that the external provisioner still sets the annotation for the mount options in the PVC. I think that provisioner needs an update to accept mount options from the StorageClass (@humblec ?).

You should be able to use the built-in provisioner from Kubernetes, I expect it to work with that one. Use `provisioner: kubernetes.io/glusterfs` in the StorageClass for that.

**Comment by yoliander** [comment]
Yeah @nixpanic  I'm using `provisioner: kubernetes.io/glusterfs` in my storage class, but it doesn't work.

> This is my storageclass.yaml
> 
> ```
> apiVersion: storage.k8s.io/v1
> kind: StorageClass
> metadata:
>   name: gluster-heketi-training
> provisioner: kubernetes.io/glusterfs
> reclaimPolicy: Delete
> mountOptions:
>   - enable-ino32
> parameters:
>   resturl: "http://192.168.6.2:33221"
> allowVolumeExpansion: true
> ```

**Comment by phlogistonjohn** [comment]
Since this isusse has stalled out I am going to suggest yout to file an issue with kube/ the provisioner's repo as transferring the mount option from the SC to the PV is beyond the scope of heketi but should be part of the provisioner's responsibility.

**Comment by nixpanic** [comment]
Indeed, I agree with that. This is a problem that should probably be reported at https://github.com/kubernetes-incubator/external-storage instead of Heketi.

**Comment by phlogistonjohn** [comment]
@yoliander It's been a while since this issue was updated. Are you OK if we close this as it is pretty clear this is a kubernetes/provisioner issue rather than a Heketi issue?

**Comment by phlogistonjohn** [comment]
Discussion petered out. Closing.
