### ISSUE TITLE
Add Heketi python client library 4.0.0 to Pypi because there is only a 3.0.0 version

### ISSUE THREAD

**Issue by Quadric** [heketi/heketi#1532]
On Pypi the latest library version of python client is 3.0.0  - https://pypi.org/project/heketi/ - but there is already a 4.0.0 version in the source code.

So please upload the latest version to Pypi :)

**Comment by phlogistonjohn** [comment]
None of the current maintainers own the entry on pypi nor do we plan to try and determine the owner of the entry or take ownership.
