### ISSUE TITLE
volume delete fails when host prefix ends with a trailing /

### ISSUE THREAD

**Issue by fkpwolf** [heketi/heketi#1538]
```
fans-iMac:bin fan$ ./heketi-cli --server http://192.168.51.187:8080/ volume info eab0e046b9cdb9a07572d18549be64f2
Name: vol_eab0e046b9cdb9a07572d18549be64f2
Size: 8
Volume Id: eab0e046b9cdb9a07572d18549be64f2
Cluster Id: 596da7375a1ea5cedd395289cf1f2074
Mount: 192.168.51.130:vol_eab0e046b9cdb9a07572d18549be64f2
Mount Options: backup-volfile-servers=192.168.51.187
Block: false
Free Size: 0
Reserved Size: 0
Block Hosting Restriction: (none)
Block Volumes: []
Durability Type: replicate
Distributed+Replica: 2
Snapshot Factor: 1.00
fans-iMac:bin fan$ ./heketi-cli --server http://192.168.51.187:8080/ volume delete eab0e046b9cdb9a07572d18549be64f2
Error: {"size":8,"name":"vol_eab0e046b9cdb9a07572d18549be64f2","durability":{"type":"replicate","replicate":{"replica":2},"disperse":{}},"snapshot":{"enable":true,"factor":1},"id":"eab0e046b9cdb9a07572d18549be64f2","cluster":"596da7375a1ea5cedd395289cf1f2074","mount":{"glusterfs":{"hosts":["192.168.51.130","192.168.51.187"],"device":"192.168.51.130:vol_eab0e046b9cdb9a07572d18549be64f2","options":{"backup-volfile-servers":"192.168.51.187"}}},"blockinfo":{},"bricks":[{"id":"571cf55e4388ca20d1743ea14c04f44d","path":"/var/lib/heketi/mounts/vg_479769750407fdd6b9a8be8ae0f48681/brick_571cf55e4388ca20d1743ea14c04f44d/brick","device":"479769750407fdd6b9a8be8ae0f48681","node":"19ba7b7aeb6f96828e0ccc8d03e8177f","volume":"eab0e046b9cdb9a07572d18549be64f2","size":8388608},{"id":"f35db61771703fe437d2f01408650611","path":"/var/lib/heketi/mounts/vg_5765045a1cd93d47a496756e9e546834/brick_f35db61771703fe437d2f01408650611/brick","device":"5765045a1cd93d47a496756e9e546834","node":"6e53c7de2b935a71e9f16a37d2ff40a1","volume":"eab0e046b9cdb9a07572d18549be64f2","size":8388608}]}
```
The strange part is that delete command didn't give any failed reason. heketi server log is also normal. Heketi version is 8.0.0.

**Comment by phlogistonjohn** [comment]
That's very odd indeed. The "error" body looks like volume "info" json. Are you using the same version of heketi for both the server and command line (heketi-cli)?  What environment is the server running in?  Even if the logs look normal it might be worth capturing a snippet from when the delete command is being run so we can look over the requests.

**Comment by fkpwolf** [comment]
Yes, I keep deleting volume and find log in server end:
```
[negroni] Started GET /volumes/eab0e046b9cdb9a07572d18549be64f2
[negroni] Completed 200 OK in 7.859711ms
[negroni] Started GET /volumes/eab0e046b9cdb9a07572d18549be64f2
[negroni] Completed 200 OK in 5.520334ms
[negroni] Started GET /volumes/eab0e046b9cdb9a07572d18549be64f2
[negroni] Completed 200 OK in 3.58496ms
```
"delete" command was treated as "info" command? 😱

Heketi and glusterfs all run on Odroid arm cluster. 2 nodes.

When server do `Starting Node Health Status refresh`, there is error:
```
Jan 21 01:08:56 odroid-1 systemd[1]: Starting LSB: Gluster File System service for volume management...
Jan 21 01:08:56 odroid-1 glusterd[434]:  * Starting glusterd service glusterd
Jan 21 01:09:01 odroid-1 glusterd[434]:    ...done.
Jan 21 01:09:01 odroid-1 systemd[1]: Started LSB: Gluster File System service for volume management.
Feb 20 00:52:33 odroid-1 glustershd[18218]: [2019-02-20 00:52:33.117822] C [rpc-clnt-ping.c:166:rpc_clnt_ping_timer_expired] 0-vol_6329828e2602ee2696d55a7538c61bdf-client-0: server 192.168.51.130:49154 has not responded in the last 42 seconds, disconnecting.
Feb 20 00:52:35 odroid-1 glustershd[18218]: [2019-02-20 00:52:35.172905] C [rpc-clnt-ping.c:166:rpc_clnt_ping_timer_expired] 0-vol_eab0e046b9cdb9a07572d18549be64f2-client-1: server 192.168.51.130:49152 has not responded in the last 42 seconds, disconnecting.
[heketi] INFO 2019/02/28 01:20:52 Periodic health check status: node 6e53c7de2b935a71e9f16a37d2ff40a1 up=true
[heketi] INFO 2019/02/28 01:20:52 Cleaned 0 nodes from health cache
```
I am not sure if this related with the `volume delete` issue.

**Comment by phlogistonjohn** [comment]
> Yes, I keep deleting volume and find log in server end:
> 
> ```
> [negroni] Started GET /volumes/eab0e046b9cdb9a07572d18549be64f2
> [negroni] Completed 200 OK in 7.859711ms
> [negroni] Started GET /volumes/eab0e046b9cdb9a07572d18549be64f2
> [negroni] Completed 200 OK in 5.520334ms
> [negroni] Started GET /volumes/eab0e046b9cdb9a07572d18549be64f2
> [negroni] Completed 200 OK in 3.58496ms
> ```
> 
> "delete" command was treated as "info" command? scream
> 

Wow. If that's the case that is very weird indeed. If I was debugging this myself, my next step would be to run something like `tcpdump` to verify that the http requests coming from heketi-cli include DELETEs. I'd also check for any proxies in between the client and the server that could be changing or filtering requests.

If we verify that the client (heketi-cli) is sending DELETEs we need to figure out why they don't reach the server. If the client isn't sending DELETEs that sounds like a bug in the client and we'll have to figure out what is triggering this behavior.

> Heketi and glusterfs all run on Odroid arm cluster. 2 nodes.
> 
> When server do `Starting Node Health Status refresh`, there is error:
> 
> ```
> Jan 21 01:08:56 odroid-1 systemd[1]: Starting LSB: Gluster File System service for volume management...
> Jan 21 01:08:56 odroid-1 glusterd[434]:  * Starting glusterd service glusterd
> Jan 21 01:09:01 odroid-1 glusterd[434]:    ...done.
> Jan 21 01:09:01 odroid-1 systemd[1]: Started LSB: Gluster File System service for volume management.
> Feb 20 00:52:33 odroid-1 glustershd[18218]: [2019-02-20 00:52:33.117822] C [rpc-clnt-ping.c:166:rpc_clnt_ping_timer_expired] 0-vol_6329828e2602ee2696d55a7538c61bdf-client-0: server 192.168.51.130:49154 has not responded in the last 42 seconds, disconnecting.
> Feb 20 00:52:35 odroid-1 glustershd[18218]: [2019-02-20 00:52:35.172905] C [rpc-clnt-ping.c:166:rpc_clnt_ping_timer_expired] 0-vol_eab0e046b9cdb9a07572d18549be64f2-client-1: server 192.168.51.130:49152 has not responded in the last 42 seconds, disconnecting.
> [heketi] INFO 2019/02/28 01:20:52 Periodic health check status: node 6e53c7de2b935a71e9f16a37d2ff40a1 up=true
> [heketi] INFO 2019/02/28 01:20:52 Cleaned 0 nodes from health cache
> ```
> 
> I am not sure if this related with the `volume delete` issue.

I don't think so. That's something in the gluster self-heal daemon timing out. I'm not sure its even a problem in gluster but it's not directly related to anything heketi is doing.

**Comment by fkpwolf** [comment]
I use Postman as request inspect and found the request is DEL indeed. 
<img width="939" alt="2019-03-03 3 22 54" src="https://user-images.githubusercontent.com/226552/53692309-47457a80-3dc8-11e9-950e-d6004b099b0e.png">

I tested to deploy a stateful app in k8s and it will create a new PV. Use `heketi-cli` to delete it and got same error. Delete PVC and at last the new volume was deleted successfully.

**Comment by phlogistonjohn** [comment]
I'm nearly out of ideas. Does the heketi-cli command line behave the same way if the delete command is run from inside the heketi pod?

**Comment by fkpwolf** [comment]
<img width="1131" alt="2019-03-05 2 36 37" src="https://user-images.githubusercontent.com/226552/53785628-27db5880-3f54-11e9-977c-88c71e9f6c5b.png">

The root cause is my parameter `--server http://192.168.51.187:8080/` has an additional slash in end. This lead to 301 response but for safe  [consideration](https://github.com/golang/go/issues/13994), golang http will convert it into GET.

I checked code for deleting part:
https://github.com/heketi/heketi/blob/f62815fdc1232198a736b45c813b7415a1cc5da3/client/api/go-client/volume.go#L255-L262
Does it make sense to use better url conjunction, or just let user take care of command parameter?

**Comment by phlogistonjohn** [comment]
Hah. Really? That's pretty interesting... I had no idea the library did that. I'd personally certainly be open to better methods for url construction.
So I assume the workaround for now is to eliminate the trailing slash. We can leave this issue open for improvements like you suggested.

**Comment by phlogistonjohn** [comment]
As heketi is now in maintenance mode, and only accepting major bug and security related fixes, we do not expect to implement this change.
