### ISSUE TITLE
delete_unowned_bricks.sh should provide more information

### ISSUE THREAD

**Issue by raghavendra-talur** [heketi/heketi#1546]
### Kind of issue

Feature request

### Observed behavior
When the script is run in summarize mode, it shows the count of bricks in  fstab, lvs, gluster volume info and mount and does not provide any information if the counts don't match.

### Expected/desired behavior
When the count does not match for all 4, it should provide information about the difference and also possible commands to clean up.

**Comment by phlogistonjohn** [comment]
I'm triaging issues. Due to the age of this issue and the activity level in heketi I think it best to close this issue.
