### ISSUE TITLE
Don't perform operations on heterogeneous clusters

### ISSUE THREAD

**Issue by raghavendra-talur** [heketi/heketi#1547]
### Kind of issue

Feature request

### Observed behavior
When a cluster has glusterd of different versions, it is recommended that no volume operations are performed. Heketi does not check for the glusterd versions when performing operations.

### Expected/desired behavior
Provide an option to automatically stop operations by detecting the versions of glusterd. 

One possible way to do it:
As part of node monitoring, heketi can check for glusterd version along with glusterd status. If the versions match for all Nodes in a Cluster then everything is fine. If the versions are not all the same, then tag the cluster as offline.

**Comment by phlogistonjohn** [comment]
Do you think the glusterd status probes and heath status cache would be good places to handle this?

**Comment by phlogistonjohn** [comment]
@raghavendra-talur do you think this is worth pursuing? I don't. I think we should close this.

**Comment by phlogistonjohn** [comment]
Probably never going to happen. Closing
