### ISSUE TITLE
The first node in the topology file always create a new cluster

### ISSUE THREAD

**Issue by likunbyl** [heketi/heketi#1553]
### Kind of issue
 Bug

### Observed behavior
I'm doing some testing with my newly installed Glusterfs cluster,  managed by Heketi.

My heketi-topology.json is like the following:
```
{
    "clusters": [
        {
            "nodes": [
                {
                    "node": {
                        "hostnames": {
                            "manage": [
                                "aa10.prod.test.com" 
                            ],
                            "storage": [
                                "10.1.1.13"
                            ]
                        },
                        "zone": 1
                    },
                    "devices": [
                        {
                            "name": "/dev/sdb",
                            "destroydata": true
                        },
                        {
                            "name": "/dev/sdc",
                            "destroydata": true
                        }
                    ]
                },
                {
                    "node": {
                        "hostnames": {
                            "manage": [
                                "ab10.prod.test.com"
                            ],
                            "storage": [
                                "10.1.1.23"
                            ]
                        },
                        "zone": 2
                    },
                    "devices": [
                        {
                            "name": "/dev/sdb",
                            "destroydata": true
                        },
                        {
                            "name": "/dev/sdc",
                            "destroydata": true
                        }
                    ]
                },
                {
                    "node": {
                        "hostnames": {
                            "manage": [
                                "ac10.prod.test.com" 
                            ],
                            "storage": [
                                "10.1.1.33"
                            ]
                        },
                        "zone": 3
                    },
                    "devices": [
                        {
                            "name": "/dev/sdb",
                            "destroydata": true
                        },
                        {
                            "name": "/dev/sdc",
                            "destroydata": true
                        }
                    ]
                },
                {
                    "node": {
                        "hostnames": {
                            "manage": [
                                "ad10.prod.test.com"
                            ],  
                            "storage": [
                                "10.1.1.43"
                            ]   
                        },  
                        "zone": 4
                    },  
                    "devices": [
                        {
                            "name": "/dev/sdb",
                            "destroydata": true
                        },  
                        {
                            "name": "/dev/sdc",
                            "destroydata": true
                        }   
                    ]   
                }   
            ]
        }
    ]
}
```

Then I build a cluster with this topology, all is fine:
```
# heketi-cli cluster info 1fe0ada4a9190561520b7ce49c823c50
Cluster id: 1fe0ada4a9190561520b7ce49c823c50
Nodes:
0be0857c8dad2cd28c686675b7bcaf32
4f180af88de2508cdea7b39e6fb9dc4e
cc3862feb55a0081c048422bb7f73aee
e411300312853793b0abb2ef9ad3b8d7
Volumes:
6f1fcba11453080189f53403ca47b154
eab29acacddb55272fbbe1499ae979fa
ff4ff3137c928c9448dbf5e0064d47bf
Block: true

File: true
```

Then I delete the node aa10.prod.test.com, and try to add it back to the cluster:  
```
# heketi-cli topology load --json=/etc/heketi/heketi-topology.json 
Creating cluster ... ID: 0d7b4914930c4904b0ec536526e6d9a3
        Allowing file volumes on cluster.
        Allowing block volumes on cluster.
        Creating node aa10.prod.test.com ... ID: c88e709a165b5428cb9ceaf245e946cf
                Adding device /dev/sdb ... ^C
```

Obviously, Heketi create a new cluster,  instead of adding the node to the original cluster.

### Expected/desired behavior
Heketi add the deleted node to the original cluster.

### Details on how to reproduce (minimal and precise)
1. Create a gluster cluster, and use Heketi to manage it.
2. Create topology with a topology json file.
3. Delete the node that happen to be the first node in the topology json file.
4. Add the node back to the topology with command `heketi-cli topology load --json=topology-file`

### Information about the environment:

- Heketi version used :   v8.0.0-58-g5e562bf
- Operating system used: coreos 1298.5.0
- Container image:  based on dockerhub image gluster/gluster-centos:gluster3u8_centos7
- Using kubernetes: Kubernetes v1.9.11
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: inside
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): custom

**Comment by phlogistonjohn** [comment]
I strongly encourage people to only use topology load feature to initialize a cluster. The issue is that the topology json lacks any useful identifying information to help heketi differentiate between the content of the db and the topology file reliably. Instead I suggest using the heketi-cli's node add and device add commands directly when modifying an existing cluster.

**Comment by likunbyl** [comment]
Thank you，it's a good advice.  But it  is a bug that needs fix, isn't it ?

Also, If that's an official recommendation, I suggest to update  the [maintenance document](https://github.com/heketi/heketi/blob/master/docs/admin/maintenance.md) .

**Comment by phlogistonjohn** [comment]
> Thank you，it's a good advice. But it is a bug that needs fix, isn't it ?
> 

It's not a high priority for the current heketi maintainers. That said we'd certainly consider changes in this area if someone were to contribute them.

> Also, If that's an official recommendation, I suggest to update the [maintenance document](https://github.com/heketi/heketi/blob/master/docs/admin/maintenance.md) .

Good point, thank you!
