### ISSUE TITLE
Heketi on s390x: No online storage devices in cluster error

### ISSUE THREAD

**Issue by AnitaNayak** [heketi/heketi#1573]
Deployed Heketi on s390x Ubuntu 18.04. Though the disk is online, heketi pod is throwing below error:
```
[heketi] ERROR 2019/04/09 17:07:43 /src/github.com/heketi/heketi/apps/glusterfs/volume_entry_allocate.go:60: No online storage devices in cluster
[heketi] ERROR 2019/04/09 17:07:43 /src/github.com/heketi/heketi/apps/glusterfs/operations_manage.go:89: Create Volume Build Failed: No online storage devices in cluster
```
disk given was : `/dev/disk/by-path/ccw-0.0.0108`
`lsdad`
0.0.0108   n/f         dasdi     94:32   ECKD
```
chccwdev -e 0.0.0108
WARNING: Device[0.0.0108] is already  online
Done
```
which utility/tool it runs to check if the disk is online or offline.

**Comment by phlogistonjohn** [comment]
Did you add the node and device in heketi? This error is typically thrown if the cluster is not configured or if heketi can't detect a sufficient number of items. Detection is done by checking for the state of the glusterd service on the nodes/pods.
This state is never pulled from the device state of the underlying disk or hardware device.
Providing more logging or `heketi-cli topology info` output might help.

**Comment by AnitaNayak** [comment]
The issue got resolved. I was giving the disk path differently. After giving with proper symlink, its working fine. Thank you. Closing the issue.
