### ISSUE TITLE
Node (peer) cannot be deleted from glusterfs 6.0

### ISSUE THREAD

**Issue by ateleshev** [heketi/heketi#1576]
In glusterfs 6.0 was added interactive confirmation for peer detaching from pool. After that in heketi logs we can see error bellow:
```
[cmdexec] DEBUG 2019/04/11 09:52:10 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: sds-agent-regular-server41.kube-system.svc.cluster.local:2222 Command: /bin/bash -c 'sudo gluster peer detach sds-agent-regular-server32.kube-system.svc.cluster.local'
Result: All clients mounted through the peer which is getting detached need to be remounted using one of the other active peers in the trusted storage pool to ensure client gets notification on any changes done on the gluster configuration and if the same has been done do you want to proceed? (y/n) gluster cli read error
Invalid input, please enter y/n
```
After some time, node will be deleted from heketi, but peer will stay connected in glusterfs.

Glusterfs CLI hasn't any options to specify auto confirmation.
It can be done by:
```
echo y | gluster peer detach sds-agent-regular-server32.kube-system.svc.cluster.local
```

### Kind of issue
Bug

### Details on how to reproduce (minimal and precise)
- Setup 3 nodes glusterfs 6.0 cluster
- Delete one node

### Information about the environment:
- Heketi version used (e.g. v6.0.0 or master):  v8.0.0
- Operating system used:  Container Linux by CoreOS 1911.4.0 (Rhyolite)
- Heketi compiled from sources, as a package (rpm/deb), or container: from sources
- If container, which container image: 
- Using kubernetes, openshift, or direct install: kubernetes
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside:  gluster running inside kubernetes
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): custom

### Other useful information
glusterfs 6.0

**Comment by MaksymTrykur** [comment]
Relevant commit in glusterfs https://github.com/gluster/glusterfs/commit/185106a574646bdc2d4ec50756c52db61ad14d98

**Comment by phlogistonjohn** [comment]
@ateleshev can you please test this with heketi v9? In heketi changes were made to make the gluster command line generation more generic and the `--mode=script` parameter should now be passed to the peer detach command, which ought to fix the problem (in theory). 
Thanks!

**Comment by ateleshev** [comment]
@phlogistonjohn Thank you for information, command works fine in script mode (```--mode=script```). I will check it with heketi 9.
```
root@sds-agent-d2xq4:/# gluster --mode=script peer detach sds-agent-system-server46.kube-system.svc.cluster.local
peer detach: success
```
