### ISSUE TITLE
Upgrade heketi v8.0.0 to v9.0.0

### ISSUE THREAD

**Issue by Webgardener** [heketi/heketi#1578]
Hello,

I am looking for a way to upgrade heketi from v8 to v9. 

I dit the following tasks:

Create a backup of heketi.db

then
```
kubectl -n kube-system delete deploy heketi
kubectl -n kube-system delete secret heketi-config-secret
kubectl -n kube-system delete sa heketi-service-account
kubectl -n kube-system delete svc heketi
```
and 
`./gk-deploy -v -y -g --namespace kube-system -l /var/tmp/gk-deploy-exec.log`

I get the error: `Adding device /dev/cinder/gluster ... Unable to add device: Can't open /dev/sdb exclusively.  Mounted filesystem?`
The error seems "normal" regarding  https://github.com/gluster/gluster-kubernetes/issues/472. 

> Heketi requires empty block devices and will not work if you've already created lvm pvs or filesystem,  etc.

Help welcome!

**Comment by phlogistonjohn** [comment]
So, redeploying heketi is not what you need to do. I wouldn't have recommended deleting the deployment for instance. AFAIK there is no way to redeploy a new heketi instance using gk-deploy, you can only deploy a "new cluster".

If you only deleted the deployment, secret, etc. from a test cluster you should simply be able to change the "image" from witihin the pod spec of the "deploy" to use heketi/9.
If the deploy and secret, etc. are really gone you'll probably need to recreate them by hand, using the templates from gk-deploy.

**Comment by Webgardener** [comment]
Thank you. I am still struggling with the upgrade.

1. Replaced heketi:8 by heketi:9 in heketi-deployment.yaml
2. `kubectl replace -f heketi-deployment.yaml`

```
[root@twe-master-1]# kubectl -n kube-system logs pod/heketi-8696d65b4b-qpnmj
Setting up heketi database
  File: /var/lib/heketi/heketi.db
  Size: 49152           Blocks: 96         IO Block: 131072 regular file
Device: 6ch/108d        Inode: 10403977707514940087  Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2019-04-15 11:51:25.491195601 +0000
Modify: 2019-04-15 11:51:31.198189825 +0000
Change: 2019-04-15 11:51:31.205189818 +0000
 Birth: -
Heketi v9.0.0-1-g57a5f356-release-9
ERROR: Unable to start application: invalid executor: ${HEKETI_EXECUTOR}
```
On the other hand, the upgrade was successfull  by replacing the heketi image using `kubectl -n kube-system edit deploy heketi`. But there is no chance I'll be able to do that on a production environment...

**Comment by Webgardener** [comment]
I finally found a way, modifying properly the heketi-deployment.yaml file (including the variables ${} )
