### ISSUE TITLE
How to distributed bricks of volume across all nodes

### ISSUE THREAD

**Issue by srinathkotu** [heketi/heketi#1580]
### Kind of issue

Bug

### Observed behavior
Providing 4 VMs with six 1TB disks on each of them and creating volumes giving volume type as `replicate` does not create distributed striped replicated volumes.

```{
  "clusters": [
    {
      "nodes": [
        {
          "node": {
            "hostnames": {
              "manage": [
                "node1.abc.net"
              ],
              "storage": [
                "100.99.66.11"
              ]
            },
            "zone": 1
          },
          "devices": [
            "/dev/sd1",
            "/dev/sd2",
            "/dev/sd3",
            "/dev/sd4",
            "/dev/sd5",
            "/dev/sd6"
          ]
        },
        {
          "node": {
            "hostnames": {
              "manage": [
                "node2.abc.net"
              ],
              "storage": [
                "100.99.67.11"
              ]
            },
            "zone": 2
          },
          "devices": [
            "/dev/sd1",
            "/dev/sd2",
            "/dev/sd3",
            "/dev/sd4",
            "/dev/sd5",
            "/dev/sd6"
          ]
        },
        {
          "node": {
            "hostnames": {
              "manage": [
                "node3.abc.net"
              ],
              "storage": [
                "100.99.66.18"
              ]
            },
            "zone": 1
          },
          "devices": [
            "/dev/sd1",
            "/dev/sd2",
            "/dev/sd3",
            "/dev/sd4",
            "/dev/sd5",
            "/dev/sd6"
          ]
        },
        {
          "node": {
            "hostnames": {
              "manage": [
                "node4.abc.net"
              ],
              "storage": [
                "100.99.65.180"
              ]
            },
            "zone": 2
          },
          "devices": [
            "/dev/sd1",
            "/dev/sd2",
            "/dev/sd3",
            "/dev/sd4",
            "/dev/sd5",
            "/dev/sd6"
          ]
        },
        {
          "node": {
            "hostnames": {
              "manage": [
                "arbiter1.abc.net"
              ],
              "storage": [
                "100.99.65.55"
              ]
            },
            "zone": 1,
            "tags": {
               "arbiter": "required"
             }
          },
          "devices": [
            "/dev/sd1"
          ]
        }
      ]
    }
  ]
}```

### Expected/desired behavior
distributed striped replicated volumes to be created

### Details on how to reproduce (minimal and precise)
use the above topology to setup and configure the block devices and create a volume.

### Information about the environment:

- Heketi version: v8.0.0 
- Operating system used: running as pod on Kubernetes
- Heketi from container
- If container, which container image: heketi/heketi:8
- Using kubernetes, openshift, or direct install: direct install 
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: outside kubernetes
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): gk-deploy


### Other useful information

**Comment by srinathkotu** [comment]
i understand now that "striped" volume types are deprecated in glusterfs but shouldn't it be possible to create/configure a striped volume via heketi (without using the 'stripe' option in gluster command line)?

**Comment by phlogistonjohn** [comment]
Heketi will not add new support for any volume type that is deprecated in gluster. You can try and force a volume to be distributed by messing with the MaxBrickSize in the config or expanding a volume manually, or you can choose to try disperse (EC) volumes.

Is this sufficient? Can we close this issue?

**Comment by srinathkotu** [comment]
@phlogistonjohn i did read and understood that volume types of 'Distributed Striped Replicated' is deprecated on glusterfs. Now i am wondering if is there a way to setup/create striped configuration on 'Distributed Replicated' volumes, like is there a way to tell heketi that i want the volume to be distributed across specific set of replicated nodes?
For example, if i want the volume bricks that are created using the topology that i have mentioned in the following replica sets: 
node1 - node2 - arbiter
node3 - node4 - arbiter

**Comment by srinathkotu** [comment]
basically my question is how would i be able to tell heketi to distribute the bricks of a volume across all the available nodes.

**Comment by raghavendra-talur** [comment]
@srinathkotu 

Striped volumes in gluster were configured similar to how Raid 0 works. That is deprecated now.

From your updated requirement, I don't think you need stripe.

I see that you have 3 nodes in zone 1
node1, node3, arbiter1

and have 2 nodes in zone 2
node 2 and node 4

If you create a volume using the following cli

`
$ heketi-cli volume create --size=1 --gluster-volume-options='user.heketi.arbiter true,user.heketi.zone-checking strict'
`
You are guaranteed to get 1 brick on aribiter1(the arbiter brick). 1 brick on either node 1 or node 3 and 1 brick on either node 2 or node 4.

**Comment by phlogistonjohn** [comment]
No updates in a few months. Closing. Please reopen if this issue is still relevant to you.
