### ISSUE TITLE
[question] Create possible documentation of compatible GlusterFS versions?

### ISSUE THREAD

**Issue by junkiebev** [heketi/heketi#1581]
Is there a list of compatible Gluster/heketi versions anywhere in the documentation?

I'm running heketi version 9 (in a docker container) and gluster version 6 and having some issues which I'm trying to sort out. I have searched for documentation which states they are compatible and can't find anything of the sort.

Is there a version compatibility matrix somewhere that I'm missing?

**Comment by raghavendra-talur** [comment]
There is no such documentation. I will work on one.

But we did not create a doc as there is no hard requirement from heketi on gluster. Only case that I can think of:

heketi requires gluster-block and gluster-block group option in gluster container for it to be able to create blockvolumes.

**Comment by raghavendra-talur** [comment]
@junkiebev What errors do you see with Gluster version 6?

**Comment by junkiebev** [comment]
re: the error - I'm an idiot.

https://github.com/heketi/heketi/issues/1399#issuecomment-484538359

Docs explicitly stating compatibility would still be useful :p

**Comment by phlogistonjohn** [comment]
At this time the current maintainers have no plan on creating this list. Closing. Please reopen and consider contributing to create this list if this is still relevant to you.

**Comment by kanadaj** [comment]
@phlogistonjohn I'm getting errors while using heketi:latest on a host system running glusterfs 3.12, citing invalid utype. The Heketi container uses glusterfs 7.1; on Centos yum installs gluster-fuse with 3.12 and is recommended by the openshift docs. Might be a good time to add a compatibility list
