### ISSUE TITLE
I restart a kubernetes node and after the glusterfs pod stop

### ISSUE THREAD

**Issue by magikcypress** [heketi/heketi#1582]
Hello,

When I restart a kubernetes node and after the glusterfs pod stop. I have the following message and I can not restart the pod properly.

>  Warning  Unhealthy  3m (x26 over 12m)  kubelet, kube3  Readiness probe failed: ● glusterd.service - GlusterFS, a clustered file-system server
>    Loaded: loaded (/usr/lib/systemd/system/glusterd.service; enabled; vendor preset: disabled)
>    Active: inactive (dead)

Do you know how to fix this problem?

Thanks,

Cyp

**Comment by phlogistonjohn** [comment]
I'm not clear if you're experiencing this readiness probe failure before or after the node restart.
Is this happening before the node restarts and is interfering with clean restart, or is this occurring after the node has restarted?

FYI this probably isn't the optimal place to report this issue but we'll help as much as we can. It would help if we knew how you deployed your gluster pods.

**Comment by raghavendra-talur** [comment]
@magikcypress In addition to what @phlogistonjohn requested, please exec into the container and provide a full listing of processes using a command like "ps aux" when the pod is stopping the node from restart.

**Comment by magikcypress** [comment]
Hello,

Thanks for you response.

I deployed my gluster pod with a heketi json file and I work fine. I want to try restart my node for the test.

This readiness probe failure display after the node restart. If I check the process on my node, I see the glusterd process is started.

```
$ ps auxf
root       516  0.2  0.2 577384 17280 ?        Ssl  Apr21  15:54 /usr/sbin/glusterd -p /var/run/glusterd.pid --log-level INFO
root      1300  0.0  0.0  47280   872 ?        Ss   Apr21   0:00 /usr/sbin/glusterfs --log-level=ERROR --log-file=/var/lib/kubelet/plugins/kubernetes.io/glusterfs/pvc-85e6f727-5f9d-11e9-b0e3-06df39f002ac
...
```

The process started on a gluster pod

```
$ ps auxf
root        90  0.0  0.0  13432  3208 pts/1    Ss   16:08   0:00 /bin/bash
root       107  0.0  0.0  53352  3812 pts/1    R+   16:08   0:00  \_ ps auxf
root         1  1.7  0.0  43192  5028 ?        Ss   16:07   0:00 /usr/sbin/init
root        28  0.0  0.1  62152  8348 ?        Ss   16:07   0:00 /usr/sbin/lvm vgchange --monitor y --ignoreskippedcluster
root        30  0.5  0.0  39092  6512 ?        Ss   16:07   0:00 /usr/lib/systemd/systemd-journald
root        41  0.0  0.0  24272  3036 ?        Ss   16:07   0:00 /usr/sbin/crond -n
root        48  0.0  0.0  93084  3012 ?        Ssl  16:07   0:00 /usr/sbin/gssproxy -D
root        52  0.0  0.0  13292  3040 ?        Ss   16:07   0:00 /bin/bash /usr/sbin/gluster-setup.sh
root        89  0.0  0.1  62152  8240 ?        S    16:07   0:00  \_ pvscan
root        84  0.0  0.0 112868  7672 ?        Ss   16:07   0:00 /usr/sbin/sshd -D
```

I thought the glusterd process on the node could prevent glusterd from running on the pod, but no.

If I run the glusterd on the pod, it will not start and I have no log for explain this restart problem.

```
$ systemctl start glusterd
Warning! D-Bus connection terminated.
Failed to wait for response: Connection reset by peer
```

Thanks,

Cyp

**Comment by raghavendra-talur** [comment]
@magikcypress  I see two issues

1. we do not support running glusterd on node if it is *also* running the gluster pod. The reason is that gluster pod runs in `host-networking` mode and uses the same IP as node.
2. In the pod, I see that you have pvscan and vgchange commands still running. These commands are run in the gluster-setup.sh script and are prerequisite for starting glusterd in the pod. Sometimes they take time to complete their operation.

So, disable the glusterd service on the node and try again.

**Comment by magikcypress** [comment]
Hello,

Ok, I have a solution to fix this problem. After reboot a gluster pod, pvscan started and failed with this message.

```
WARNING: Failed to connect to lvmetad. Falling back to device scanning.
  WARNING: Device /dev/xvda2 not initialized in udev database even after waiting 10000000 microseconds.
  WARNING: Device /dev/xvdb1 not initialized in udev database even after waiting 10000000 microseconds.
  WARNING: Device /dev/xvdc not initialized in udev database even after waiting 10000000 microseconds.
  WARNING: Device /dev/xvdd not initialized in udev database even after waiting 10000000 microseconds.
  WARNING: Device /dev/xvdf not initialized in udev database even after waiting 10000000 microseconds.
```

I killed a gluster-setup script and a gluster pod is running now.

```
root        52  0.0  0.0  13292  3040 ?        Ss   16:07   0:00 /bin/bash /usr/sbin/gluster-setup.sh
root        89  0.0  0.1  62152  8240 ?        S    16:07   0:00  \_ pvscan
```

@phlogistonjohn You right, "this probably isn't the optimal place to report this issue" ;)

Thanks

**Comment by raghavendra-talur** [comment]
@magikcypress Killing the gluster-setup is not the right workaround.

It appears you are either using old templates or old image.
Please ensure your gluster templates are up to date.

Here is the link to the template
https://github.com/gluster/gluster-kubernetes/blob/master/deploy/kube-templates/glusterfs-daemonset.yaml

**Comment by magikcypress** [comment]
@raghavendra-talur Ok, there is a confuse deploy template on this 2 repos (Heketi/gluster-kubernetes).

I use this template 
https://github.com/heketi/heketi/blob/master/extras/kubernetes/glusterfs-daemonset.json

And I understand, Heketi is not a good repos for the deployment ?

**Comment by raghavendra-talur** [comment]
@magikcypress yes, this repo is only for heketi development. For all the deployment resources refer to gluster kubernetes repo.

**Comment by magikcypress** [comment]
@raghavendra-talur Ok thanks. I reinstall again ;)

**Comment by magikcypress** [comment]
It's work fine ! 

I moved a glusterd.service file, because glusterd is started on the worker node after reboot, a gluster pod goes wrong. I'm not sure is a good practice but It's work, and the gluster pod restart correctly.

`sudo mv /lib/systemd/system/glusterd.service .`

Thanks again for you help,

Cyp

**Comment by phlogistonjohn** [comment]
Sounds like everything was resolved. Feel free to repoen this issue if I was wrong.
