### ISSUE TITLE
Failed to create block volume: Bad file descriptor 

### ISSUE THREAD

**Issue by freakssy** [heketi/heketi#1584]
Hi,

I'm trying to create a block volume and I'm stuck:

` ± hci volume info 75864ddf400d1dd34649101241f8e63b`
Name: vol_75864ddf400d1dd34649101241f8e63b
Size: 400
Volume Id: 75864ddf400d1dd34649101241f8e63b
Cluster Id: d7a3113f6441299e82c63c77aa6e0061
Mount: 10.59.1.18:vol_75864ddf400d1dd34649101241f8e63b
Mount Options: backup-volfile-servers=10.59.1.16,10.59.1.17
Block: true
Free Size: 212
Reserved Size: 8
Block Hosting Restriction: (none)
Block Volumes: [0ee502297492d19cb1479895ee37c4f4 82fd7432faf467de3c8a515ee245465e bcbd3535ac86f43ce38a766b2e7aee96]
Durability Type: replicate
Distributed+Replica: 3

`± hci blockvolume create --size=60`
Error: Failed to create block volume: failed to configure on 10.59.1.16 : Bad file descriptor
failed to configure on 10.59.1.17 : Bad file descriptor

Here are logs heketi:

[heketi] DEBUG 2019/04/30 07:39:48 heketi/apps/glusterfs/block_volume_entry_create.go:105:glusterfs.(*BlockVolumeEntry).createBlockVolumeRequest: Using executor host [oso-glusterfs-infra-59c]
[negroni] 2019-04-30T07:39:49Z \| 200 \| 	 206.452µs \| heketi-infra-storage-infra-storage.internal.c1-ocp-ef.edelia.net \| GET /queue/b6c161225f6c34a91291c2b97e026490
[kubeexec] ERROR 2019/04/30 07:39:51 heketi/pkg/remoteexec/kube/exec.go:85:kube.ExecCommands: Failed to run command [gluster-block create vol_75864ddf400d1dd34649101241f8e63b/blockvol_23c4030529c11cbe36905479809d1e66 ha 3 auth disable prealloc full 10.59.1.18,10.59.1.16,10.59.1.17 60GiB --json] on [pod:glusterfs-infra-storage-6f4vm c:glusterfs ns:infra-storage (from host:oso-glusterfs-infra-59c selector:glusterfs-node)]: Err[command terminated with exit code 255]: Stdout [{ "RESULT": "FAIL", "errCode": 255, "errMsg": "failed to configure on 10.59.1.16 : Bad file descriptor\nfailed to configure on 10.59.1.17 : Bad file descriptor" }
[cmdexec] ERROR 2019/04/30 07:39:51 heketi/executors/cmdexec/block_volume.go:92:cmdexec.(*CmdExecutor).BlockVolumeCreate: Failed to create block volume: failed to configure on 10.59.1.16 : Bad file descriptor
[heketi] ERROR 2019/04/30 07:39:51 heketi/apps/glusterfs/operations_block_volume.go:215:glusterfs.(*BlockVolumeCreateOperation).Exec: Error executing create block volume: Failed to create block volume: failed to configure on 10.59.1.16 : Bad file descriptor
failed to configure on 10.59.1.17 : Bad file descriptor
[heketi] ERROR 2019/04/30 07:39:51 heketi/apps/glusterfs/operations_manage.go:158:glusterfs.runOperationAfterBuild: Create Block Volume Failed: Failed to create block volume: failed to configure on 10.59.1.16 : Bad file descriptor
failed to configure on 10.59.1.17 : Bad file descriptor

Information about the environment:

    heketi --version
    Heketi v9.0.0-1-g57a5f356-release-9
    Operating system used: cat /etc/redhat-release
    Fedora release 27 (Twenty Seven)
    If container, which container image:
    docker.io/heketi/heketi latest 3ad9ca98f56c 3 weeks ago 386 MB
    Using kubernetes, openshift, or direct install: Openshift 3.11
    If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: Inside
    If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): openshift-ansible

Thank you!

**Comment by phlogistonjohn** [comment]
So, that error is coming from the gluster-block layer and will probably occur with or without heketi. What I'd do next is a) manually create a block hosting volume* for testing b) manually try to create block volumes using the gluster-block command line tool (run from the gluster nodes/pods). You can use the command heketi runs, seen in the logging output above, as an example for creating block volumes.

If you continue to hit errors I'd then use the logging from gluster-blockd and tcmu runner to debug as well as possibly contacting the [gluster bock](https://github.com/gluster/gluster-block) team for additional help.

* To manually create a block hosting volume, create a volume using the heketi-cli with the --block flag. Once you've debugged the issue I recommend deleting any block volumes created in this BHV manually and then use heketi to remove the BHV itself.

**Comment by freakssy** [comment]
Thanks for help.
It works now.
I have some pods with process
