### ISSUE TITLE
Disable performance translators for heketidbstorage

### ISSUE THREAD

**Issue by phlogistonjohn** [heketi/heketi#1591]
### Kind of issue

Feature request

### Observed behavior

Periodically we get reports of corrupt boltdb files in the wild. This generally shouldn't happen as bolt is a fairly simple db format and has been stable (ossified if you prefer) for a while now. One area of risk that concerns us (speaking for myself and @raghavendra-talur) is that there could be some issue in the common configuration where the boltdb file resides on a glusterfs volume. In order to reduce the risk and still retain the benefits of keeping a db on gluster we are considering disabling glusterfs (performance) translators for the heketidbstorage volume.
This may be optional, design pending.

**Comment by phlogistonjohn** [comment]
Issue #1378 may be an instance of this.

**Comment by phlogistonjohn** [comment]
Issue #1369 may be an instance of this.

**Comment by raghavendra-talur** [comment]
I think we should disable all the performance xlators. 

performance.quick-read=off
performance.read-ahead=off
performance.io-cache=off
performance.stat-prefetch=off
performance.open-behind=off
performance.readdir-ahead=off
performance.strict-o-direct=on

**Comment by nixpanic** [comment]
These are all part of the option group [db-workload](https://github.com/gluster/glusterfs/blob/master/extras/group-db-workload).

**Comment by phlogistonjohn** [comment]
@raghavendra-talur @nixpanic which option do you feel fits heketi's use case better, directly controling the xlators or using the option group? The heketi db is certainly "a database" but I also wonder if we don't want granular control of heketidbstorage. Looking for opinions...

**Comment by phlogistonjohn** [comment]
@raghavendra-talur @nixpanic which option do you feel fits heketi's use case better, directly controling the xlators or using the option group? The heketi db is certainly "a database" but I also wonder if we don't want granular control of heketidbstorage. Looking for opinions...

**Comment by phlogistonjohn** [comment]
I also wonder if that group is available in all the versions of gluster heketi interoperates with?

**Comment by nixpanic** [comment]
The group does not seem to be available in GlusterFS 4.1, currently the oldest still maintained release. My preference would go to using the db-workload options group, but not having it in 4.1 makes that a no-go. Duplicating (and watching for changes in) the group is something I don't like, but I guess it will be the only way for now.

**Comment by phlogistonjohn** [comment]
Fixed by #1642
