### ISSUE TITLE
Unable to deploy heketi when using an rsa-key 

### ISSUE THREAD

**Issue by zergar** [heketi/heketi#1592]
### Kind of issue

Bug

### Observed behavior
When following this guide (https://docs.openshift.com/container-platform/3.5/install_config/storage_examples/dedicated_gluster_dynamic_example.html) for creating a glusterfs-cluster with heketi, starting heketi fails with the following logs:

```
May 13 15:44:23 gfs1.localdomain audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=heketi comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
May 13 15:44:23 gfs1.localdomain audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=heketi comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
May 13 15:44:23 gfs1.localdomain systemd[1]: Stopped Heketi Server.
May 13 15:44:23 gfs1.localdomain systemd[1]: heketi.service: Scheduled restart job, restart counter is at 4.
May 13 15:44:23 gfs1.localdomain systemd[1]: heketi.service: Service RestartSec=100ms expired, scheduling restart.
May 13 15:44:23 gfs1.localdomain systemd[1]: heketi.service: Failed with result 'exit-code'.
May 13 15:44:23 gfs1.localdomain systemd[1]: heketi.service: Main process exited, code=exited, status=1/FAILURE
May 13 15:44:23 gfs1.localdomain audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=heketi comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
May 13 15:44:23 gfs1.localdomain heketi[2004]: ERROR: Unable to start application: Unable to read private key file
May 13 15:44:23 gfs1.localdomain heketi[2004]: [heketi] ERROR 2019/05/13 15:44:23 heketi/apps/glusterfs/app.go:158:glusterfs.(*App).setup: Unable to read private key file
May 13 15:44:23 gfs1.localdomain heketi[2004]: [cmdexec] ERROR 2019/05/13 15:44:23 heketi/executors/sshexec/sshexec.go:126:sshexec.NewSshExecutor: Unable to read private key file
May 13 15:44:23 gfs1.localdomain heketi[2004]: [cmdexec] ERROR 2019/05/13 15:44:23 heketi/pkg/remoteexec/ssh/ssh.go:87:ssh.NewSshExecWithKeyFile: Unable to get keyfile: ssh: unhandled key type
May 13 15:44:23 gfs1.localdomain heketi[2004]: Heketi 9.0.0
May 13 15:44:23 gfs1.localdomain audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=heketi comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
May 13 15:44:23 gfs1.localdomain systemd[1]: Started Heketi Server.
```

This behavior only occurs when trying to load a rsa-key, I've tried an ed25519-key afterwards and it works fine.

### Expected/desired behavior

heketi is able to use rsa-ssh-keys.

### Details on how to reproduce (minimal and precise)
Follow this guide (https://docs.openshift.com/container-platform/3.5/install_config/storage_examples/dedicated_gluster_dynamic_example.html) to step 4 of installation.

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): 8.0.0 as well as 9.0.0 (logs from 9.0.0)
- Operating system used: Fedora 30
- Heketi compiled from sources, as a package (rpm/deb), or container: rpm
- If container, which container image: -
- Using kubernetes, openshift, or direct install: direct install
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: -
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): -

### Other useful information

This might be an error in go's x/crypto (that's where the most precise error-message is from), but I don't know enough about go to really dive deeper. This might also be a very specific issue, although a clean installation of Fedora was done hours before this issue occurred.

**Comment by nixpanic** [comment]
Possibly the `Unable to get keyfile: ssh: unhandled key type` indicates that `x/crypto` does not understand the format of the private key. Could you try to convert (with `ssh-keygen`) the RSA key to the PEM format? `x/crypto` is expected to understand that format, also for RSA keys.

```
     -m key_format
             Specify a key format for key generation, the -i (import), -e
             (export) conversion options, and the -p change passphrase opera‐
             tion.  The latter may be used to convert between OpenSSH private
             key and PEM private key formats.  The supported key formats are:
             “RFC4716” (RFC 4716/SSH2 public or private key), “PKCS8” (PEM
             PKCS8 public key) or “PEM” (PEM public key).  The default conver‐
             sion format is “RFC4716”.  Setting a format of “PEM” when gener‐
             ating or updating a supported private key type will cause the key
             to be stored in the legacy PEM private key format.
```

**Comment by phlogistonjohn** [comment]
Could you also please paste the first line (not the whole key) so we can see what the "---- BLAH ----" text says? I have trouble keeping track of all these key formats and often just fall back to checking those header lines.

**Comment by zergar** [comment]
The head-row of the non-working RSA key is `-----BEGIN OPENSSH PRIVATE KEY-----` which looks identical to the ed25519-head-row (`-----BEGIN OPENSSH PRIVATE KEY-----`). I assume that the type of the key is encoded into the key itself.

After creating a new key with forcing the PEM-Key-Format (head-row `-----BEGIN RSA PRIVATE KEY-----`) heketi starts without any problem. So I guess this is more an issue with the manual and default configuration of ssh-keygen in Fedora in conjunction with heketi than with heketi itself or x/crypto, although I would appreciate more meaningful error messages.

Anyhow, thanks for the help with figuring this out. I hope it will help someone running into the same issue in the future.

**Comment by shinuza** [comment]
The key needs to be created with `-m PEM` flag if you use a version of OpenSSH >= 7.8.

See [here](https://www.openssh.com/txt/release-7.8) for me details.

**Comment by phlogistonjohn** [comment]
As heketi is now in maintenance mode, and only accepting major bug and security related fixes, we do not expect to implement this change.
