### ISSUE TITLE
Heketi on s390x: Provisioning of pvc takes long time compared to x86. When creating bulk pvc, looks like it hangs.

### ISSUE THREAD

**Issue by AnitaNayak** [heketi/heketi#1595]
Heketi on s390x: Provisioning of pvc takes long time almost three times compared to x86. 
When creating bulk pvc, looks like it hangs. It does not provision for a long time.

Heketi is running in a container. 
```
glusterfs-blk-pvc-1                         Bound     pvc-6a71cd87-78d4-11e9-9479-fa163e64f89c   2Gi        RWO            glusterfs                  24m
glusterfs-blk-pvc-10                        Pending                                                                        glusterfs                  15m
glusterfs-blk-pvc-2                         Bound     pvc-caa1537d-78d4-11e9-9479-fa163e64f89c   1Gi        RWO            glusterfs                  21m
glusterfs-blk-pvc-3                         Bound     pvc-1df2073b-78d5-11e9-9479-fa163e64f89c   5Gi        RWO            glusterfs                  19m
glusterfs-blk-pvc-4                         Pending                                                                        glusterfs                  16m
glusterfs-blk-pvc-5                         Pending                                                                        glusterfs                  16m
glusterfs-blk-pvc-6                         Pending                                                                        glusterfs                  16m
glusterfs-blk-pvc-7                         Pending                                                                        glusterfs                  16m
glusterfs-blk-pvc-8                         Pending                                                                        glusterfs                  16m
glusterfs-blk-pvc-9                         Pending                                                                        glusterfs                  16m
root@uma-rc:~/gfs-cli# while true; do kubectl get pvc -n kube-system | grep glusterfs-blk-pvc; echo " "; sleep 5; done
glusterfs-blk-pvc-1                         Bound    pvc-6a71cd87-78d4-11e9-9479-fa163e64f89c   2Gi        RWO            glusterfs                  30m
glusterfs-blk-pvc-10                        Bound    pvc-93893dfc-78d5-11e9-9479-fa163e64f89c   1Gi        RWO            glusterfs                  22m
glusterfs-blk-pvc-2                         Bound    pvc-caa1537d-78d4-11e9-9479-fa163e64f89c   1Gi        RWO            glusterfs                  27m
glusterfs-blk-pvc-3                         Bound    pvc-1df2073b-78d5-11e9-9479-fa163e64f89c   5Gi        RWO            glusterfs                  25m
glusterfs-blk-pvc-4                         Bound    pvc-8e9a62de-78d5-11e9-9479-fa163e64f89c   1Gi        RWO            glusterfs                  22m
glusterfs-blk-pvc-5                         Bound    pvc-8f5eba0e-78d5-11e9-9479-fa163e64f89c   1Gi        RWO            glusterfs                  22m
glusterfs-blk-pvc-6                         Bound    pvc-902623ed-78d5-11e9-9479-fa163e64f89c   1Gi        RWO            glusterfs                  22m
glusterfs-blk-pvc-7                         Bound    pvc-91201a74-78d5-11e9-9479-fa163e64f89c   1Gi        RWO            glusterfs                  22m
glusterfs-blk-pvc-8                         Bound    pvc-91e65702-78d5-11e9-9479-fa163e64f89c   1Gi        RWO            glusterfs                  22m
glusterfs-blk-pvc-9                         Bound    pvc-92b99330-78d5-11e9-9479-fa163e64f89c   1Gi        RWO            glusterfs                  22m
```
Any idea why this behavior? Performance wise its very slow.

**Comment by phlogistonjohn** [comment]
Not without more information. I'd check if any of the underlying commands that heketi runs while creating volumes differs much between systems.
You can use the log to extract the lvcreate,mkfs.xfs,etc commands and run them by hand timing each one. Run the same commands (adapting for differing vg names of course) on both systems to compare. Alternately, you can also try to check the performance of the heketi binaries by running test setups with the mock executor. 

You also didn't mention what version of heketi you're running or which executor you're using.

**Comment by AnitaNayak** [comment]
It is heketi 8.0.0. I collected the logs with debug. What I observed, starting from getting the job, mkdir , lvcreate, mkfs, mount and all are getting over in a very short span. But between first mkdir and lvcreate there is a huge waiting time, where its just checking the job status [ correct me if I am wrong]. sometimes a pvc request gets completed in 70sec and sometimes takes nearly 2 m. 
Attaching the log for your reference. 
[heketi-job-logs.docx](https://github.com/heketi/heketi/files/3194110/heketi-job-logs.docx)
Not sure why there is a long waiting between mkdir and lvcreate by kube executors.

**Comment by AnitaNayak** [comment]
Can anyone have a look at this issue? This is critical for us to improve the heketi performance...

**Comment by AnitaNayak** [comment]
Hi @phlogistonjohn , could you please have a look at the log that I attached https://github.com/heketi/heketi/issues/1595#issuecomment-493677896. 
1. On individual systems, if I ran `lvcreate`, `mkdir -p` , etc are very fast. 
2. The equivalent command from remote node I tried is `ssh -t root@<node1> mkdir -p ...`, `ssh -t root@<node2> mkdir -p ...`. Those commands are fast.
3. When running commands from heketi container through `heketi-cli`, its taking time to add disk. 
4. What is the equivalent command same as ran by `kubeexec.go` for `mkdir -p` which will go through heketi and the network.
Thank you. Please give any other suggestions.

**Comment by AnitaNayak** [comment]
Can anyone correct me:

The process that runs `kubeexec.go` is taking more time to perform few operations on s390x. In the mean time [negroni] checks/polls the job queue, for which we get continuously below messages
```
[negroni] Started GET /queue/a1213d92261967511e62059d283891b8
[negroni] Completed 200 OK in 237.606µs
[negroni] Started GET /queue/a1213d92261967511e62059d283891b8
[negroni] Completed 200 OK in 220.342µs
```
The Ops that are being done by heketi `kubeexec.go` such as `pvcreate`, `vgcreate`, mkdir -p`, `lvcreate`, ... are just done by heketi through k8s? I mean there is no involvement of glusterfs while performing the above said Ops. 

can anyone suggest if it is an issue with heketi or k8s (mean where should I debug the issue)? 
Tested on several s390x environments, but the performance is not improved much. 

Even observed while building `heketi`,  the complete `k8s.io/kubernetes` taking long time to fetch... 
There are other opensource packages being used along with go and glide. Can any of the open source package may impact the performance on s390x ( in that case we can relook that package). 

Thank you...

**Comment by phlogistonjohn** [comment]
Heketi's kubeexec feature uses componets of k8s that work similar to how 'kubectl exec' functions. It was possibly even the same at one point, but I haven't looked into kubectl itself lately.

Not knowing much about s390x architecture I don't know why these calls would differ much across different architectures. Most of the time spent in these functions not running the commands ought to be network bound, and thus io bound not cpu bound.

In your previous comment you write that commands are "very fast" but this is rather subjective. Timings would be a lot more concrete.

Perhaps we can create some sort of benchmark by which you can better measure where the slowdown comes from. First, record the steps heketi uses to create a volume by creating a volume and extracting the commands from the log.
* Scenario A: Run each command by hand prefixed with `time` to measure the runtime of just the commands only
Ignoring parallelism for a moment, the difference between sum of these timings would demonstrate what overhead the execution layer is applying to the
* Scenario B: write a shell script that does the above steps but via `kubectl exec` rather than directly. Time this script to see what kind of overhead the remote execution adds
* Scenario C: re-run the volume create with heketi if the overall time to complete B differs significantly from C then there may be a bug or suboptimal path in heketi.

You are also certainly welcome to trying to rebuild with a newer version of k8s libraries. The one we use is rather old, you can refer to our PRs list for other efforts to improve this. Please note however, that the time to fetch the libraries using git (from within glide) is unlikely to have any bearing on the runtime performance of the libraries or how we call them.

**Comment by AnitaNayak** [comment]
Able to resolve the issue. My bad that I was not checking glusterfs log when pvcreate, lvcreate was happening (just focusing on heketi logs). Actually glusterfs was taking long time and issue was with device mapper version. Followed x86 device mapper downgrade step, which resolved the issue.

**Comment by AnitaNayak** [comment]
Thank you @phlogistonjohn for your guidance.
