### ISSUE TITLE
heketi should provide a replace brick command

### ISSUE THREAD

**Issue by raghavendra-talur** [heketi/heketi#1596]
### Kind of issue

> Uncomment only one of these:
Feature request

### Observed behavior
We don't have a mechanism in heketi to replace a particular brick. The granularity for removal/replacement is device or a node.

### Expected/desired behavior
We should have a replace brick command.

**Comment by sbias** [comment]
maybe related to pr https://github.com/heketi/heketi/pull/1656 ?
