### ISSUE TITLE
Give the possibility to set $volname ctime off at creation

### ISSUE THREAD

**Issue by gioppoluca** [heketi/heketi#1601]
### Kind of issue

Feature request

### Observed behavior
New release of gluster present strange behaviour when client is older than server version:
https://github.com/gluster/glusterfs/issues/658

Client is kubernetes that create volumes through storage class, and than cannot mount the newy creted volume due to bug in gluster

### Expected/desired behavior
Proposed gluster's workaround is to set ctime at off, but since the operation is done automatically by storage class of kubernetes the workaround is useless, unless Heketi implements a volume property that kubernetes can send along other properties to set the volume ctime

### Details on how to reproduce (minimal and precise)
have a 13.x version of kubernetes trying to dynamically create and mount a volume on a pod using a storage class.

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): 
- Operating system used: CentOS 7.6
- Heketi compiled from sources, as a package (rpm/deb), or container: rpm
- If container, which container image: 
- Using kubernetes, openshift, or direct install: Kubernetes independent from gluster (not installed in kubernetes
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: outside
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): rancher

### Other useful information
See gluster git issue mentioned for more details

**Comment by phlogistonjohn** [comment]
Have you investigated the volume options feature(s) that heketi provides?
Take a look at the `--gluster-volume-options` cli switch, the `HEKETI_PRE_REQUEST_VOLUME_OPTIONS` and `HEKETI_POST_REQUEST_VOLUME_OPTIONS` environment variables, as well as the volume options support in the glusterfs storage class in k8s (assuming you are using storage classes).

**Comment by gioppoluca** [comment]
> Have you investigated the volume options feature(s) that heketi provides?
> Take a look at the `--gluster-volume-options` cli switch, the `HEKETI_PRE_REQUEST_VOLUME_OPTIONS` and `HEKETI_POST_REQUEST_VOLUME_OPTIONS` environment variables, as well as the volume options support in the glusterfs storage class in k8s (assuming you are using storage classes).

I have looked at storage classes (that is ths things that is used) and there is no way to add the option (or so it seems), but also heketi REST API ( that should be the thing used by the storage class to do its job) does not seems to document any other volume options besides the volumetype.
I've seen the CLI code and there there is a more general option for volume_options but little doc here.
Little doc also in the HEKETI_POST/PRE_REQUEST_VOLUME_OPTIONS, found no example on how to use it.
Any hint on this?
Thanks

**Comment by phlogistonjohn** [comment]
Sorry for the delayed response. It's just an environment variable that works pretty much like the storage class only it applies globally to all volumes being created. Syntax should be the same IIRC.
"pre" options apply before the options from the storage class and thus can be overidden by the content of the sc. "post" options apply after the storage class and can override the options present in the storage class.
Please try it out and let us know if this works for you.

**Comment by ymartin59** [comment]
Hello. I am interested in adding "discard" file system option to xfs to ensure underlying VDO de-allocate blocks when files are deleted from glusterfs.
Is there an way to do it - like custom profile options passed to mkfs command?
Thank you in advance for your help.

**Comment by ymartin59** [comment]
OK I have found the answer on my own:
- mkfs command does not support custom options: https://github.com/heketi/heketi/blob/6e94431db9ecad18d5827060fe1c562d30e5d15c/executors/cmdexec/brick.go#L62
- mount command does not support custom options: https://github.com/heketi/heketi/blob/6e94431db9ecad18d5827060fe1c562d30e5d15c/executors/cmdexec/brick.go#L105

Would it make sense to implement configurable "brick format class", users may customize with mkfs/mount options?

**Comment by raghavendra-talur** [comment]
@ymartin59 Would you be interested in implementing the "brick format class"? It is certainly a good feature add from the community.

**Comment by hahnn** [comment]
Hi guys,

Just my 2 cents here.

I would propose the following:

Update the devices endpoint to support two more configurable options:
**Before:**
`{
    "node": "714c510140c20e808002f2b074bc0c50",
    "name": "/dev/sdb",
    "tags": {
        "serial_number": "a109-84338af8e43-48dd9d43-919231"
    }
}`

**After:**
`{
    "node": "714c510140c20e808002f2b074bc0c50",
    "name": "/dev/sdb",
    "fstype": "xfs",
    "mountopts": "discard,nodiratime,x-systemd.requires=vdo.service",
    "tags": {
        "serial_number": "a109-84338af8e43-48dd9d43-919231"
    }
}`

fstype could be any Linux OS supported filesystem like "XFS", "EXT4", ...
mountopts could be any supported options for the configured fstype.

I would allow those options in the nodes endpoint as well to simply create a default configuration in case fstype and/or mountopts are not specified in the devices endpoint.

mountopts would be really important to have.
fstype would be nice to have but not priority (at least for me).

What do you think about those suggestions?

Regards.

**Comment by phlogistonjohn** [comment]
Probably never going to happen. We'd need a contributor from outside the current maintencae team to step up. Closing this, reopen if demand is high enough but please understand the issue will probably just go stale again.
