### ISSUE TITLE
Can't add new nodes on existing cluster

### ISSUE THREAD

**Issue by cduverne** [heketi/heketi#1603]
### Kind of issue
Bug

### Observed behavior
When trying to add a new node, I tried to : 

- Update topology.json and re-run "gk-deploy -g"
-> Result : Nothing happens

- Update topology and load it with "heketi-cli topology load..."
-> Result : Heketi tries to call the nodes, but fails with a timeout.

### Expected/desired behavior

Add new nodes in existing cluster

### Details on how to reproduce (minimal and precise)

Add a node in topology.json
Run gk-deploy -g or heketi-cli topology load

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): heketi-cli v9.0.0
- Operating system used: Centos 
- Heketi compiled from sources, as a package (rpm/deb), or container: Used gk-deploy to deploy in Kubernetes and Rancher 
- Using kubernetes, openshift, or direct install: Kubernetes
- If kubernetes, is gluster running inside kubernetes or outside: Inside
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): gk-deploy

### Other useful information
What IP / hostname should be used when using heketi cli from within Kubernetes ?

**Comment by phlogistonjohn** [comment]
I don't think adding a new node via gk-deploy works.

As for adding nodes by using "topology load" it can work, in theory, but it's so terribly flaky I've never recommended it since I started working with Heketi. I recommend using the `heketi-cli node add ...` and `heketi-cli device add ...` commands directly.

If those commands fail to work please update this report with corresponding sections of the heketi.log.

**Comment by cduverne** [comment]
I'm not sure what should the exact process be.

I added the label "storagemode=glusterfs" on 2 new nodes. 
The DaemonSet automatically deployed glusterfs pods, which aren't responding...

What did I do wrong ?

**Comment by phlogistonjohn** [comment]
If I were debugging it I would first ensure that the pods got started. Assuming so I'd try to exec into the pods and check out the environment. The glusterfs pods run an internal systemd instance and so you can check for failures of services with commands such as 'systemctl status'
Look at the heketi logs and see exactly what error messages are being generated. Try to see if heketi can resolve the management hostname to the name of the pod or if there are other connection errors.

**Comment by phlogistonjohn** [comment]
No updates in a few months. Closing. Please reopen if this is still relevant to you.
