### ISSUE TITLE
New Rest based executor

### ISSUE THREAD

**Issue by sudheerit11** [heketi/heketi#1609]
Heketi have ssh based executor, but when due to firewall/security reasons such ssh user with sudo access can not be created.  
In that case having a **REST API based executor** would be beneficial. 
On each server, user can have a http server which will respond to req.

client Req :
```text
{
 commands []string // list of commands
 cmdTimeOut int // cmd time out defined while starting heketi server.
}
```

Server Resp:

```text
{
cmd1: {
  STDERR string
  STDOUT string
  ExitStatus int
 },
cmd2: {...}
}
```

Heketi RestExec Config:
```text
  "restexec": {
      "port": "3000",
      "insecure": false,
      "cert" : "/path/to/crt.file",
      "fstab": "/etc/fstab",
      "gluster_cli_timeout": 30,
      "pv_data_alignment": "Optional: Specify PV data alignment size. Default is 256K",
      "vg_physicalextentsize": "Optional: Specify VG physical extent size. Default is 4MB",
      "lv_chunksize": "Optional: Specify LV chunksize. Default is 256K",
      "backup_lvm_metadata": false,
      "debug_umount_failures": true
    }
```

### Kind of issue
> Feature request

**Comment by phlogistonjohn** [comment]
We'd certainly be open to that, however the rest endpoint on the nodes/pods will certainly have some security concerns and you'd have to take care that this can not be abused. SSH (and kubeexec) have the advantage of having existing mature security models.

I look forward to any prototype that you'd like to present!

**Comment by sudheerit11** [comment]
Thanks for suggestion. Sure I will come back with a prototype.

**Comment by phlogistonjohn** [comment]
@sudheerit11 its been nearly six months since you filed this issue. If you still plan on submitting a prototype please feel free to reopen this issue. But since its been so long I am assuming you're no longer working on this and the current team has no intent on picking this up. Thank you.
