### ISSUE TITLE
Heketi must provide new brick on brick failure

### ISSUE THREAD

**Issue by lpabon** [heketi/heketi#161]
When a brick/device fails, the admin should not remove it by hand.  Instead admin should inform heketi of the failed brick and assign a new brick from the cluster.

**Comment by obnoxxx** [comment]
@lpabon FYI: @raghavendra-talur and @MohamedAshiqrh are working on the replace disk feature. There is already an incomplete WIP patch ( https://github.com/raghavendra-talur/heketi/commit/d01d56bfa6b20bd382b87602c0852dd94b2e721a ). Just saying in order to prevent duplication of effort....

**Comment by obnoxxx** [comment]
@lpabon Note that I ususally wouldn't post other people's incomplete patches, but here I did it in order to show that someone has already gone a good part of the way.... @MohamedAshiqrh maybe you could comment on the progress.

**Comment by MohamedAshiqrh** [comment]
https://github.com/heketi/heketi/pull/676

Will update the PR.

**Comment by raghavendra-talur** [comment]
Can we consider that #710 closes this?

**Comment by MohamedAshiqrh** [comment]
@lpabon @obnoxxx  Is there anything pending for this issue?
