### ISSUE TITLE
Evolution: Document arbiter size calculation

### ISSUE THREAD

**Issue by src386** [heketi/heketi#1610]
I was confused by [Red Hat Gluster documentation](https://access.redhat.com/documentation/en-us/red_hat_gluster_storage/3.3/html/administration_guide/creating_arbitrated_replicated_volumes#sect-Arbiter_Requirements):

> minimum arbiter brick size = 4 KB * ( size in KB of largest data brick in volume or replica set / average file size in KB)

I know this is a Gluster documentation, not Heketi. But [Heketi Arbiter documentation](https://github.com/heketi/heketi/blob/master/docs/admin/arbiter.md) says:

> Note: The Arbiter brick size is only directly proportional to the data brick size.

So I assumed Heketi applies the Red Hat formula, but according to [apps/glusterfs/placer_arbiter.go](https://github.com/heketi/heketi/blob/master/apps/glusterfs/placer_arbiter.go#L401) it seems that the ```4 KB *``` multiplier is omitted.

When I create a 1GB volume using Heketi and 8 KB average file size, the Arbiter size should be 500M according to Red Hat, but it is actually 125M. This confirms that the ```4 KB *``` multiplier is omitted.

Adding the proper formula in Heketi's documentation might be interesting for Arbiter size estimation.

**Comment by phlogistonjohn** [comment]
The current maintainers have no plans to do this. Please reopen and submit a PR if this is still important to you.
