### ISSUE TITLE
Issue on heketi cluster: No online storage devices in cluster

### ISSUE THREAD

**Issue by mcon-hubject-github** [heketi/heketi#1611]
### Kind of issue
My heketi server and gluster server had been rebooted because of patch, but after that i met the similar issue with "No clusters configured". https://github.com/heketi/heketi/issues/1214. 

Then i stop the heketi,  backup the /var/lib/heketi/heketi.db, and remove the heketi.db, restart the heketi, load the topology again. But the device had been used, and can't be initialized again, if force to initialize, the data will be lost.

 ```
heketi-cli topology load --json heketi-topology.json
        Found node 172.19.25.78 on cluster 73a77b4e941d05046c39a2659d8c824a
                Adding device /dev/sdb ... Unable to add device: Can't initialize physical volume "/dev/sdb" of volume group "vg_4c67f436b83ad1858b11303acc3eb690" without -ff
  /dev/sdb: physical volume not initialized.
        Found node 172.19.25.79 on cluster 73a77b4e941d05046c39a2659d8c824a
                Adding device /dev/sdb ... Unable to add device: Can't initialize physical volume "/dev/sdb" of volume group "vg_6bba69f8ad69e23707ad01f0507ceefa" without -ff
  /dev/sdb: physical volume not initialized.
        Found node 172.19.25.80 on cluster 73a77b4e941d05046c39a2659d8c824a
                Adding device /dev/sdb ... Unable to add device: Can't initialize physical volume "/dev/sdb" of volume group "vg_d961515942cbe98557d47cbb7a0c9d8f" without -ff
  /dev/sdb: physical volume not initialized.
```

Now the heketi can list the cluster and nodes, but not the devices.

```
heketi-cli topology info
Cluster Id: 73a77b4e941d05046c39a2659d8c824a

    File:  true
    Block: true

    Volumes:

    Nodes:

        Node Id: 48aa5ff61123d093598b7a7112ded241
        State: online
        Cluster Id: 73a77b4e941d05046c39a2659d8c824a
        Zone: 1
        Management Hostnames: 172.19.25.78
        Storage Hostnames: 172.19.25.78
        Devices:

        Node Id: 53fd7d9240de1c7ef2f11e130f2d9a59
        State: online
        Cluster Id: 73a77b4e941d05046c39a2659d8c824a
        Zone: 3
        Management Hostnames: 172.19.25.80
        Storage Hostnames: 172.19.25.80
        Devices:

        Node Id: 578b8ad7fb6711d8238528c74709ca06
        State: online
        Cluster Id: 73a77b4e941d05046c39a2659d8c824a
        Zone: 2
        Management Hostnames: 172.19.25.79
        Storage Hostnames: 172.19.25.79
        Devices:
```

When create an new volume, it will trigger an error like:

```
heketi-cli volume create --size=1
Error: Failed to allocate new volume: Unable to create volume on any cluster:
Cluster 2623e2b4569201343c5f5f8f5cafbca2: No online storage devices in cluster
Cluster 73a77b4e941d05046c39a2659d8c824a: No online storage devices in cluster

```
Anyone can advise how to resolve this issue? Thanks in advance.

> Uncomment only one of these:
> 
> Bug
> Feature request

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): 
- Operating system used: 
- Heketi compiled from sources, as a package (rpm/deb), or container: 
- If container, which container image: 
- Using kubernetes, openshift, or direct install: 
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: 
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom):

**Comment by phlogistonjohn** [comment]
> ### Kind of issue
> 
> My heketi server and gluster server had been rebooted because of patch, but after that i met the similar issue with "No clusters configured". #1214.
> 
> Then i stop the heketi, backup the /var/lib/heketi/heketi.db, and remove the heketi.db, restart the heketi, load the topology again. But the device had been used, and can't be initialized again, if force to initialize, the data will be lost.

This is probably not a good way to resolve your problem. Trying to load the topology twice is extremely unlikely to solve any problems as you've discovered. 

> 
> [...snip...]
> 
> When create an new volume, it will trigger an error like:
> 
> ```
> heketi-cli volume create --size=1
> Error: Failed to allocate new volume: Unable to create volume on any cluster:
> Cluster 2623e2b4569201343c5f5f8f5cafbca2: No online storage devices in cluster
> Cluster 73a77b4e941d05046c39a2659d8c824a: No online storage devices in cluster
> ```
> 
> Anyone can advise how to resolve this issue? Thanks in advance.
> 


Since it sounds like you backed up the original db you should first try to export the database. Use `heketi db export --dbfile PATH --jsonfile PATH2` to see if the db is working well enough to export to json.

If that works use the script found in `extras/tools/dbconsistency.py` to check the db for consistency. You may find that it is no longer consistent given the original error you reported. If the db can not be exported to JSON that may mean the db is corrupted. If that's the case the recovery will be more difficult. Heketi does not have a way to "reload" the state from gluster. You could try recreating the content of the db by hand by editing json but that is not easy. Alternatively, you could simply try to back up your existing volumes and create a new heketi and gluster cluster.

One last question: are you using a heketidbstorage volume on gluster? If so did all your gluster nodes go down at the same time due to this reboot?
If so that might explain why the db content is invalid. The db damage should not happen, but in general you should take care never to stop all your gluster nodes at once. Gluster nodes should be stopped one at a time and you should check gluster self-heal status, ensuring no volumes are still being healed, before rebooting the next node.

**Comment by davideng** [comment]
@phlogistonjohn Thanks you for your response! 

I did an db export and use dbconsistency.py to check the consistency, but still can't get the volumes, bricks, and devices information as you can see as below.

```
heketi db export --dbfile heketi.db.2019-06-17 --jsonfile heketi.json
DB exported to heketi.json
```

```
python dbconsistency.py /var/lib/heketi/heketi.json
        Clusters:     2
         Devices:     0
          Bricks:     0
         Volumes:     0
    Blockvolumes:     0
         Pending:     0

```
I would like to try recreating the content of the db by hand by editing json, but don't know the device id, volume id these kind of information. 

"back up your existing volumes and create a new heketi and gluster cluster." maybe the last way to think about. As there are some applications are using these volumes, even if copy the volume data and create new volume, it is still need to find an way to restore the data to the new volumes.

> are you using a heketidbstorage volume on gluster? If so did all your gluster nodes go down at the same time due to this reboot?

No, we are not using a heketidbstorage volume. 
I also think the heketi db lost the volume information is because of the incorrect reboot way. (But in another way, the heketi cluster should be more robust.)
Yes, the volumes on gluster clusters are normal, the only problem is heketi can't get the volume information from the gluster.

```
lsblk
NAME                                                                              MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda                                                                                 8:0    0   30G  0 disk
├─sda1                                                                              8:1    0    1G  0 part /boot
└─sda2                                                                              8:2    0   29G  0 part
  ├─centos-root                                                                   253:0    0   26G  0 lvm  /
  └─centos-swap                                                                   253:1    0    3G  0 lvm  [SWAP]
sdb                                                                                 8:16   0  150G  0 disk
├─vg_4c67f436b83ad1858b11303acc3eb690-tp_f87dd1bc8c0450c73c3bff593f15b8eb_tmeta   253:2    0   12M  0 lvm
│ └─vg_4c67f436b83ad1858b11303acc3eb690-tp_f87dd1bc8c0450c73c3bff593f15b8eb-tpool 253:4    0    2G  0 lvm
│   ├─vg_4c67f436b83ad1858b11303acc3eb690-tp_f87dd1bc8c0450c73c3bff593f15b8eb     253:5    0    2G  0 lvm
│   └─vg_4c67f436b83ad1858b11303acc3eb690-brick_a17aacea49a3badb63919d87b49c4678  253:6    0    2G  0 lvm  /var/lib/heketi/mount
```

```
gluster volume list
vol_0a4a1955690af494db208eb460c49bed
vol_3e001ffd4d5b2bacf93a68a3e535b847
vol_4e257d81185862aa83f1ddcc4085ffb4
vol_7e63133959a6ee278b94d1ab4b4ef9cd

```

@phlogistonjohn Do you have any good ideas, many thanks?

**Comment by phlogistonjohn** [comment]
> @phlogistonjohn Thanks you for your response!
> 
> **Respond you via another account.**
> I did an db export and use dbconsistency.py to check the consistency, but still can't get the volumes, bricks, and devices information as you can see as below.
> 
> ```
> heketi db export --dbfile heketi.db.2019-06-17 --jsonfile heketi.json
> DB exported to heketi.json
> ```
> 
> ```
> python dbconsistency.py /var/lib/heketi/heketi.json
>         Clusters:     2
>          Devices:     0
>           Bricks:     0
>          Volumes:     0
>     Blockvolumes:     0
>          Pending:     0
> ```
> 

This doesn't look like a complete database. I assume this is an export of the current heketi.db. It would probably be better to do this with the heketi db that was backed up before you tried to reload the topology. 


> I would like to try recreating the content of the db by hand by editing json, but don't know the device id, volume id these kind of information.
> 
> "back up your existing volumes and create a new heketi and gluster cluster." maybe the last way to think about. As there are some applications are using these volumes, even if copy the volume data and create new volume, it is still need to find an way to restore the data to the new volumes.
> 

True. I would also treat that as a last resort.

> > are you using a heketidbstorage volume on gluster? If so did all your gluster nodes go down at the same time due to this reboot?
> 
> No, we are not using a heketidbstorage volume.
> I also think the heketi db lost the volume information is because of the incorrect reboot way. (But in another way, the heketi cluster should be more robust.)

Yes, but I've never seen a corruption using a local filesystem. What filesystem are you using?

> Yes, the volumes on gluster clusters are normal, the only problem is heketi can't get the volume information from the gluster.
> 
> ```
> lsblk
> NAME                                                                              MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
> sda                                                                                 8:0    0   30G  0 disk
> ├─sda1                                                                              8:1    0    1G  0 part /boot
> └─sda2                                                                              8:2    0   29G  0 part
>   ├─centos-root                                                                   253:0    0   26G  0 lvm  /
>   └─centos-swap                                                                   253:1    0    3G  0 lvm  [SWAP]
> sdb                                                                                 8:16   0  150G  0 disk
> ├─vg_4c67f436b83ad1858b11303acc3eb690-tp_f87dd1bc8c0450c73c3bff593f15b8eb_tmeta   253:2    0   12M  0 lvm
> │ └─vg_4c67f436b83ad1858b11303acc3eb690-tp_f87dd1bc8c0450c73c3bff593f15b8eb-tpool 253:4    0    2G  0 lvm
> │   ├─vg_4c67f436b83ad1858b11303acc3eb690-tp_f87dd1bc8c0450c73c3bff593f15b8eb     253:5    0    2G  0 lvm
> │   └─vg_4c67f436b83ad1858b11303acc3eb690-brick_a17aacea49a3badb63919d87b49c4678  253:6    0    2G  0 lvm  /var/lib/heketi/mount
> ```
> 
> ```
> gluster volume list
> vol_0a4a1955690af494db208eb460c49bed
> vol_3e001ffd4d5b2bacf93a68a3e535b847
> vol_4e257d81185862aa83f1ddcc4085ffb4
> vol_7e63133959a6ee278b94d1ab4b4ef9cd
> ```

Unfortunately for cases like this heketi does not actively rely on gluster for it's state. Rather, it relies on the db. We have created tools to help compare and check the local state against gluster but there is currently no mechanism for importing or synchronizing state from gluster.


> 
> @phlogistonjohn Do you have any good ideas, many thanks?

**Comment by davideng** [comment]
> This doesn't look like a complete database. I assume this is an export of the current heketi.db. It would probably be better to do this with the heketi db that was backed up before you tried to reload the topology.

**It's a great pity. We don't backup the heketi db before reload the topology. Obviously, that's the most possible way to fix this issue.**


> Yes, but I've never seen a corruption using a local filesystem. What filesystem are you using?

We are using the xfs filesystem.

> Unfortunately for cases like this heketi does not actively rely on gluster for it's state. Rather, it relies on the db. We have created tools to help compare and check the local state against gluster but there is currently no mechanism for importing or synchronizing state from gluster.

Thanks for your support and contribution! We hope the mechanism to synchronize state from gluster will come soon, and also for heketi.db this so important file should be versioned.  Even if the heketi lost connection with gluster cluster, the heketi.db can keep the last correct state, after it reconnect to gluster,  sync the latest state from gluster. (these are just my personal ideas, may not be very accurate)

Anyway, I will discuss with my colleages to see if we have to take the last resort to create new volumes/devices. Thank you. @phlogistonjohn

**Comment by mcon-hubject-github** [comment]
Luckily, as the volume on gluster cluster is still there, then we can collect the volume and device information from gluster nodes, and add the volume and device entries in heketi.json file that being exported from heketi.db. Re-import the new created heketi.json and restore the heketi database. It works. 

heketi db export --dbfile heketi.db --jsonfile heketi.json
heketi db import --dbfile heketi.db --jsonfile heketi.json

> try recreating the content of the db by hand by editing json but that is not easy

@phlogistonjohn Thanks again.
