### ISSUE TITLE
how to create glusterfs in OSE with single node and single replication  through ansible-playbook

### ISSUE THREAD

**Issue by ihsanpr88** [heketi/heketi#1619]
### Kind of issue

> Uncomment only one of these:
> 
> Bug
> Feature request

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): 
- Operating system used: 
- Heketi compiled from sources, as a package (rpm/deb), or container: 
- If container, which container image: 
- Using kubernetes, openshift, or direct install: 
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: 
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom):

**Comment by ihsanpr88** [comment]
after editing below node getting configuring, but failing while running task "Create heketi DB volume"

/usr/share/ansible/openshift-ansible/playbooks/openshift-glusterfs/private/roles/openshift_storage_glusterfs/tasks/glusterfs_deploy.yml

from
- assert:
    that: "glusterfs_nodes | count >= 3"
to
- assert:
    that: "glusterfs_nodes | count >= 1"

**Comment by phlogistonjohn** [comment]
Could you please file this in the openshift-ansible tracker? The heketi project is not responsible for the functionality of openshift-ansible.
