### ISSUE TITLE
Heketi dont report properly of Node status

### ISSUE THREAD

**Issue by ZrytyADHD** [heketi/heketi#1634]
Heketi v9.0
Gluster  v6.4

Hello,
I have a roblem with heketi in Openshift.
After creating Cluster from 3 servers and testing some tasks on it i got some problems:
- cant replace node  - trying to remove it but got Error:
Error: Failed to remove device, error: No Replacement was found for resource requested to be removed
- cant remove the device because:
Error: device: 84be53297716edb82e66625cd880443a is not in failed state
-new node don't show anything except:
Node Id: 4a9afa1b4da3b3b3c8a43800da4d77e9
	State: online
	Cluster Id: 982fbe1c0231a71cb57fe27ef6ea6e7e
	Zone: 1
	Management Hostnames: <host name>
	Storage Hostnames: <Ip address>
	Devices:

My question is:
1,How to change node status to failed to test replacement (its very important to me)?
2. How to delete device or node
3. Why heketi don't refresh status of nodes - i delete disk from server for test but it still show online ??

**Comment by phlogistonjohn** [comment]
> Heketi v9.0
> Gluster v6.4
> 
> Hello,
> I have a roblem with heketi in Openshift.
> After creating Cluster from 3 servers and testing some tasks on it i got some problems:
> 
>     * cant replace node  - trying to remove it but got Error:
>       Error: Failed to remove device, error: No Replacement was found for resource requested to be removed
> 
>     * cant remove the device because:
>       Error: device: 84be53297716edb82e66625cd880443a is not in failed state
>       -new node don't show anything except:
>       Node Id: 4a9afa1b4da3b3b3c8a43800da4d77e9
>       State: online
>       Cluster Id: 982fbe1c0231a71cb57fe27ef6ea6e7e
>       Zone: 1
>       Management Hostnames: 
>       Storage Hostnames: 
>       Devices:
> 
> 
> My question is:
> 1,How to change node status to failed to test replacement (its very important to me)?

`heketi-cli node disable <NODEID>`
You can also disable devices with `heketi-cli device disable <DEVICEID>`
Note that for historical reasons a "failed" device and an "offline" device are the same thing.


> 2. How to delete device or node

You must first put the node or device in the offline state as above. Then you need to run either `heketi-cli node remove ...` or `heketi-cli device remove ...` so that the node/device no longer hosts any bricks. Once done you can run `heketi-cli device delete ...` and `heketi-cli node delete`.



> 3. Why heketi don't refresh status of nodes - i delete disk from server for test but it still show online ??

This is a common source of confusion. This "online" and "offline" is an administrator defined "state" not the status of a device. Heketi does not probe for device availiaibity so the only way it know if a device is failed (offline) is if you tell it so.
Heketi does have an internal check for the status of nodes but it doesn't (currently) expose that in the node/topology info command output.

**Comment by ZrytyADHD** [comment]
Hello, thanks for long and quick response for my problem
I miss something writing first post i have a 4 noes.
I add one using trhis command:
` oc rsh heketi-storage-2-cl992 heketi-cli -s http://localhost:8080 --user admin --secret <my secret>= node add --zone=1 --cluster=982fbe1c0231a71cb57fe27ef6ea6e7e --management-host-name=svlnopsh10p.ptu.pl --storage-host-name=10.0.3.79
`
And here you I think "I should shot my self 🗡 " 
What i forget ? 
I forget to add device from new node using 
`oc rsh heketi-storage-2-vlxwn heketi-cli -s http://localhost:8080 --user admin --secret <my secret> device add  --name=/dev/sdc --node=4a9afa1b4da3b3b3c8a43800da4d77e9
`
This is why i can't remove old device and node. 
Maybe this will be usefull for somebody else in future

**Comment by phlogistonjohn** [comment]
In theory I would expect the force forget option to do what you want. Can you capture heketi logs starting right before you run the device remove command until the command completes (success or failure)? Thanks.

**Comment by ZrytyADHD** [comment]
Hi,
With the error above nothing help so
i do some other test with my setup and make some node replacing etc. and face another problem.

Problem show when I try to reproduce some errors in example 
Complete server crash wtihout option to recover it.

 After power off my server which is one of my node I:
a. add new node for replace failed
b. add new device
c. disable failed node which is power off
d. try to remove it to go to nex step but got error:
`Error: The target exists, contains other items, or is in use.
command terminated with exit code 255`
Its show on heketi 8 and 9 check both. Also deploy again heketi pod etc start restart services without success.

**Comment by ZrytyADHD** [comment]
Can any one help with this issue ?

**Comment by phlogistonjohn** [comment]
Stale issue. Closing. Please reopen if you are still experiencing this problem.
