### ISSUE TITLE
Heketi error deleting node:  Error: The target exists, contains other items, or is in use.

### ISSUE THREAD

**Issue by ZrytyADHD** [heketi/heketi#1635]
Hey,
i have a problem one of my nodes are dead and can't recover it.
I try to remove it and delte but i got error:
`Error: The target exists, contains other items, or is in use.`
even when i use `--force -forget`
can anyone provie me a information how to resolve this.

**Comment by phlogistonjohn** [comment]
That sounds like you might already have an operation in progress for that device. What does `heketi-cli server operations info` report?

**Comment by ZrytyADHD** [comment]
Yes it's can be i also try to dump database to json file delete pending operations and import it.
Problem shows when i shutdown one of the nodes simulating error and try to replace.
I make:
-shutdown node to simulate error
- disable node using heketi
-try to remove node got error 255 
- try to remove it using force forget - got error Error: The target exists, contains other items, or is in use.

There is an option in heketi to remove "dead" unrecoverable node and add new one ?

**Comment by ZrytyADHD** [comment]
I got a report 
Total: 1
  In-Flight: 0
  New: 0
  Failed: 0
  Stale: 1

**Comment by ZrytyADHD** [comment]
Hey can any one help me with this ?

**Comment by phlogistonjohn** [comment]
Stale issue. Closing. Please reopen if you are still experiencing this problem.
