### ISSUE TITLE
heketi pod does not start. invalid page type: 12: 10

### ISSUE THREAD

**Issue by 0asp0** [heketi/heketi#1636]
Hi,

I deployed glusterfs and heketi in my kubernetes gluster as pods.
Everything was working a while ago, but now hekti pod will not start.

### Kind of issue
Bug

### Observed behavior
cannot start heketi pod. Getting following error:

```
Setting up heketi database
  File: /var/lib/heketi/heketi.db
  Size: 131072          Blocks: 256        IO Block: 131072 regular file
Device: aeh/174d        Inode: 12055206076560510041  Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2019-07-24 13:40:55.061118003 +0000
Modify: 2019-08-04 17:08:37.087508351 +0000
Change: 2019-08-04 17:08:37.093508351 +0000
 Birth: -
Heketi v9.0.0
[heketi] INFO 2019/08/06 14:30:31 Loaded kubernetes executor
ERROR: Unable to start application: invalid page type: 12: 10
```

### Expected/desired behavior
pod will start without issues

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): v9.0.0
- Operating system used: kubernetes @ docker @ centos7.6
- Heketi compiled from sources, as a package (rpm/deb), or container: 
- If container, which container image:  heketi/heketi:dev
- Using kubernetes, openshift, or direct install: 
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: inside kubernetes
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): 
gk-deploy

**Comment by CassandraWin** [comment]
Hi, 
did you manage to solve your problem? I have a similar issue. The only difference is:
``` ERROR: Unable to start application: invalid page type: 18: 10```
Thanks in advance,

**Comment by kannanvr** [comment]
Hi All,
   How to solve this issue ?
I am also getting the similar issue 
```
Setting up heketi database
  File: /var/lib/heketi/heketi.db
  Size: 262144          Blocks: 312        IO Block: 131072 regular file
Device: 9fh/159d        Inode: 12805562992574114863  Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2019-11-28 11:43:39.170849724 +0000
Modify: 2020-01-05 11:17:59.594593332 +0000
Change: 2020-01-05 11:17:59.594593332 +0000
 Birth: -
Heketi v9.0.0-1-g57a5f356-release-9
[heketi] INFO 2020/01/29 06:25:07 Loaded kubernetes executor
ERROR: Unable to start application: invalid page type: 2: 10
```
I could not even export the DB into file...

**Comment by phlogistonjohn** [comment]
Bolt db level corruption. There's nothing heketi can do to recover from this situation. If this is still a problem I recommend trying to scrape the relevant data from the corrupted db and create a new db with the data (from json). I have done it so I know it can be done, however it is challenging and I can offer no specific assistance at this time.
Closing as "cantfix".
