### ISSUE TITLE
Multi-tier storage using tag matching

### ISSUE THREAD

**Issue by TadasVainutis** [heketi/heketi#1637]
Heketi v9.0.0
Gluster v6.5

### Problem 
Hello, I have 3 vm with 2 disk’s on every virtual machine, one disk is hdd and another is ssd. Is it possible to create multitier storage, for example some user will be using only hdd and some will be using only ssd. I created tags on every device (ssd devices have “tier: gold” and hdd devices have “tier: silver”), but when I create volume with heketi-cli with command ( heketi-cli volume create --size=4 --gluster-volume-options 'user.heketi.device-tag-match tier=gold')  bricks are not created on the right device. 

### Expected behavior
```
1 Node : server1
   Devices:
      hdd-device
          Bricks: 
      ssd-device
         Bricks: NEW_BRICK_ID – Size (GiB): 4

2 Node : server2
   Devices:
      hdd-device
          Bricks: 
      ssd-device
          Bricks: NEW_BRICK_ID – Size (GiB): 4

3 Node : server3
   Devices:
      hdd-device
          Bricks: 
      ssd-device
          Bricks: NEW_BRICK_ID – Size (GiB): 4
```
### Current behavior
```
1 Node : server1
   Devices:
      hdd-device
         Bricks: NEW_BRICK_ID – Size (GiB): 4
      ssd-device
         Bricks: 

2 Node : server2
   Devices:
      hdd-device
         Bricks: NEW_BRICK_ID – Size (GiB): 4
      ssd-device
         Bricks: 

3 Node : server3
   Devices:
      hdd-device
         Bricks: 
      ssd-device
         Bricks: NEW_BRICK_ID – Size (GiB): 4
```
### Questions
Is “Tag Matching” supported in heketi v9.0.0? If yes, why I get this weird behavior?

**Comment by phlogistonjohn** [comment]
Sorry if it wasn't clear from the context but the design docs are not all implemented. In this case the tag matching design has not been even started yet.

**Comment by TadasVainutis** [comment]
My bad I misunderstood docs. Sorry. So for now solution for this problem is to create different Gluster TSP for different type of disks?

**Comment by phlogistonjohn** [comment]
Yes. That is the case if you need the separation now rather than sometime after the feature has been developed.

**Comment by TadasVainutis** [comment]
Thank you :)
