### ISSUE TITLE
how to recover heketi.db 

### ISSUE THREAD

**Issue by siriuswinds** [heketi/heketi#1641]
i'm using heketi in kubernetes 1.15.3，and not storage heketi.db in glusterfs volumes，while my heketi pod instance shutdown, i lost cluster info, and the heketi.db is empty.

how could i recover the heketi.db from gluster daemons.

i found there is a secret holds heketi.db.gz, am i should restore it to the directory? 

are there any heketi-cli commands could used to do that ?

**Comment by siriuswinds** [comment]
> If you don't put the heketi db on some kind of persistent storage the content will be lost every time the pod is stopped. The typical way to accomplish that is to to use the glusterfs volume. If you can't do that you need to provide your own persistent storage some way. There's also a feature to pack the db into a secret IIRC but I've never used it and can't help setting it up. I also don't think its very "crash safe".

thanks!
i am now looking for a method to rebuild  or recover it first, next i should persist it to my storage

**Comment by daclarke** [comment]
@siriuswinds were you able to rebuild heketi.db from gluster?

**Comment by siriuswinds** [comment]
first, get a heketi json format from another heketi server  , you can get it  using  mock executor (in /etc/heketi/heketi.json) 


heketi db export jsonfile=xxx dbfile=/var/lib/heketi/heketi.db


then , get all volume info from gluster server


gluster volume info


/var/lib/heketi/ on every node 


lsblk or lvdisplay get all  brick (lvm info)


edit json file with your gluster volume info and brick(lvm) info , then import the josn to create a new db 


heketi db import jsonfile=xxx dbfile=new.db


replace /var/lib/heketi/heketi.db with new.db


------------------ 原始邮件 ------------------
发件人: "daclarke"<notifications@github.com>;
发送时间: 2019年9月4日(星期三) 凌晨0:49
收件人: "heketi/heketi"<heketi@noreply.github.com>;
抄送: "杨憬"<9526121@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [heketi/heketi] how to recover heketi.db  (#1641)




@siriuswinds were you able to rebuild heketi.db from gluster?
