### ISSUE TITLE
Error: Failed to allocate new volume: No space

### ISSUE THREAD

**Issue by Roninchen** [heketi/heketi#1643]
when kubectl apply -f glusterfs-storage-class.yaml:

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: glusterfs-storage-class
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://172.18.64.41:30009"
  restauthenabled: "false"
return:
Error: Failed to allocate new volume: No space

then heketi-cli volume create --size=1 in heketi  container it return the same error:
Error: Failed to allocate new volume: No space

but run  heketi-cli volume create --durability=none --size=1 is worked,
what's wrong

**Comment by nixpanic** [comment]
How many storage servers/pods and disks do you have? By default heketi creates replicate-3 volumes, so a minimal of three servers (and enough free space per server) needs to be available.

**Comment by Roninchen** [comment]
three glusterfs  node,each node hava 8GB free space

**Comment by Roninchen** [comment]
> How many storage servers/pods and disks do you have? By default heketi creates replicate-3 volumes, so a minimal of three servers (and enough free space per server) needs to be available.

three glusterfs node,each node hava 8GB free space

**Comment by imranrazakhan** [comment]
@Roninchen if you have three node then no need to test with durability=none. Have you run `heketi-cli volume create` without durability=none option?

**Comment by phlogistonjohn** [comment]
Not enough details to debug. Closing issue. Please reopen if this is still relevant to you.
