### ISSUE TITLE
How to delete a device with bricks in a volume setting durability type: none?

### ISSUE THREAD

**Issue by ppaanngggg** [heketi/heketi#1646]
### Observed behavior

I created a volume with durability type: none.
Then I want to delete a device, I have remove bricks of this device by gluster
and disable it. When I do `heketictl device remove 3fb57b33f28c30912cb59ba9815c0680`,
it shows `Error: Failed to remove device, error: replace brick is not supported for volume durability type none`.

so, how can I delete this device safely?

### Expected/desired behavior

I think heketi can umount and delete bricks, and then delete this device.

Or I can delete a brick manully.

### Information about the environment:

- Heketi version: 9 
- Operating system used: ubuntu 16.04
- glusterfs: 5.6
- kubernetes: 1.14

**Comment by phlogistonjohn** [comment]
You must delete the volume first. If you have content on any volumes you want to preserve you need to create a new volume(s) (on a different device!) and copy that data to the new volume and then delete the single-brick volume(s) with a brick on that device.
Also, there's no such command as heketictl as far as I know. ;-)

**Comment by ppaanngggg** [comment]
I think it's OK to remove-brick from gluster volume, and then umount and delete lvm. 

I wonder why heketi doesn't support such operation?

**Comment by phlogistonjohn** [comment]
Honestly, durability-none is a very niche use case because most users want replicated data. Since this is so niche imo I do not think the current maintenance team will try improve this behavior. Thus I am going to close this issue. Please reopen if this issue is still relevant to you.
