### ISSUE TITLE
Exapnd volume's number bricks with arbiter option

### ISSUE THREAD

**Issue by amgads** [heketi/heketi#1647]
> Feature request

### Observed behavior
I can expand a volume from 2 replicas to 3 bricks (with anrbiter) using the gluster CLI. 
I don't know of a way to do it with heketi

Is there such a way? if not this is a very needed viable option to add to be compatible with Gluster CLI.

### Information about the environment:

- Heketi version used: v9.0.0 
- Operating system used: Linux
- Heketi compiled from sources, as a package (rpm/deb), or container: tar file 
- If container, which container image: own image
- Using kubernetes, openshift, or direct install: kubernetes
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: inside 
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): k8s deployment

**Comment by amgads** [comment]
Any response?

**Comment by phlogistonjohn** [comment]
Sorry but this is not a feature of heketi. You can request this as an enhancement, however it is unlikely that the current team would implement this. Outside contributions would be considered.

**Comment by amgads** [comment]
Thanks John. I already requested the enhancement in my first comment.
Certainly we could try to contribute. Would you mind provide me with pointers to:

1) How to build the heketi product (documented steps)
2) What files would address such an enhancement to take a look and try to proto-type

Regards

**Comment by phlogistonjohn** [comment]
Probably never going to happen. Closing

**Comment by amgads** [comment]
Which part never going to happen -- the feature?? 
any pointers (2)

**Comment by phlogistonjohn** [comment]
> Which part never going to happen -- the feature??
> any pointers (2)

Correct, the feature. If you're interested in contributing something like that yourself, that's fine, reopen this issue, but you are definitely going to need to ramp up mostly on your own. I personally don't have a lot of time for heketi these days.

**Comment by amgads** [comment]
Thanks John – would you kindly mind provide me a head-start with pointers to heketi’s code where the replica’s are defined?
