### ISSUE TITLE
We dodn't install "findutils" on the docker image

### ISSUE THREAD

**Issue by Cyreex** [heketi/heketi#1660]
### Kind of issue

Bug

### Observed behavior
We use "**find**" in the [https://github.com/heketi/heketi/blob/master/extras/container/heketi-start.sh](https://github.com/heketi/heketi/blob/master/extras/container/heketi-start.sh), but we don't install "**findutils**" on the docker image [https://hub.docker.com/r/heketi/heketi/dockerfile](https://hub.docker.com/r/heketi/heketi/dockerfile)

### Details on how to reproduce (minimal and precise)
If we try to restore the Heketi database from backup, we get an error:
```
Setting up heketi database
 File: /var/lib/heketi/heketi.db
 Size: 278528          Blocks: 544        IO Block: 131072 regular file
Device: 20001eh/2097182d        Inode: 12816440542983960180  Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2019-10-09 12:48:57.674708024 +0000
Modify: 2019-10-09 12:50:37.374198944 +0000
Change: 2019-10-09 12:50:37.374198944 +0000
Birth: -
DB exported to -
/usr/bin/heketi-start.sh: line 43: find: command not found
/usr/bin/heketi-start.sh: line 74: find: command not found
```
### Other useful information

We need to change the line in the Dockerfile:
```
    dnf -y install glide golang git make mercurial findutils && \
```

**Comment by phlogistonjohn** [comment]
This change was implemented on master already in #1652
You may be using one of the released images, if you could please test on master and see if that fixes the issue for you.
