### ISSUE TITLE
Error: Failed to allocate new volume: No space with heketi-cli

### ISSUE THREAD

**Issue by SergeyMuha** [heketi/heketi#1661]
### Observed behavior
heketi-cli node info 50b29c18bce9790778103f73f71df86a
Node Id: 50b29c18bce9790778103f73f71df86a
State: online
Cluster Id: 1f7385d4ad9820a05ff6fb709ac2831a
Zone: 1
Management Hostname: 
Storage Hostname: 
Devices:
Id:21a4e52059905bec722ef4b31aeb2ab1   Name:/dev/mapper/gfs-gfs1State:online    Size (GiB):0       Used (GiB):0       Free (GiB):0       Bricks:0  

heketi-cli volume create --durability=none --size=1
Error: Failed to allocate new volume: No space

### Expected/desired behavior
Bricks should be
heketi-cli volume create --durability=none --size=1 should work

### Information about the environment:
Three aws nodes with ebs volumes, with LMV 
NAME                    MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
xvda                    202:0    0   20G  0 disk 
|-xvda1                 202:1    0  476M  0 part /boot
`-xvda2                 202:2    0 19.5G  0 part 
  |-VolGroup00-rootVol  253:0    0    4G  0 lvm  /
  |-VolGroup00-swapVol  253:1    0    2G  0 lvm  [SWAP]
  |-VolGroup00-homeVol  253:2    0    1G  0 lvm  /home
  |-VolGroup00-varVol   253:3    0    2G  0 lvm  /var
  |-VolGroup00-logVol   253:4    0    2G  0 lvm  /var/log
  `-VolGroup00-auditVol 253:5    0  8.5G  0 lvm  /var/log/audit
xvdb                    202:16   0   10G  0 disk 
`-xvdb1                 202:17   0   10G  0 part 
  `-gfs-gfs1            253:6    0    1G  0 lvm  

- Operating system used:  Centos for GlusterFS
- Using kubernetes, openshift, or direct install: kubernetes
gk-deploy with dedicated servers for GlusterFS

**Comment by phlogistonjohn** [comment]
If I'm reading this correctly the size of the device posted here is zero GB:
Id:21a4e52059905bec722ef4b31aeb2ab1 Name:/dev/mapper/gfs-gfs1State:online Size (GiB):0 Used (GiB):0 Free (GiB):0 Bricks:0
This is unusual and probably related to the reason you cannot allocate a brick. Is this the only storage device heketi is tracking?

**Comment by SergeyMuha** [comment]
I have cluster with three nodes
:~/gluster-kubernetes/deploy$ heketi-cli topology info

Cluster Id: 1f7385d4ad9820a05ff6fb709ac2831a

    File:  true
    Block: true

    Volumes:

    Nodes:

	Node Id: 50b29c18bce9790778103f73f71df86a
	State: online
	Cluster Id: 1f7385d4ad9820a05ff6fb709ac2831a
	Zone: 1
	Management Hostnames: ip-1-58.ec2.internal
	Storage Hostnames: 
	Devices:
		Id:21a4e52059905bec722ef4b31aeb2ab1   Name:/dev/mapper/gfs-gfs1State:online    Size (GiB):0       Used (GiB):0       Free (GiB):0       
			Bricks:

	Node Id: 7be6a22e0a0a7a9f7d2c6abfaad92c4e
	State: online
	Cluster Id: 1f7385d4ad9820a05ff6fb709ac2831a
	Zone: 1
	Management Hostnames: ip-1722.internal
	Storage Hostnames: 1
	Devices:
		Id:61ad8c1612690375c3d3ee0ef57ae07f   Name:/dev/mapper/gfs-gfs1State:online    Size (GiB):0       Used (GiB):0       Free (GiB):0       
			Bricks:

	Node Id: 85bd50daeffaff934fd0692beaedb852
	State: online
	Cluster Id: 1f7385d4ad9820a05ff6fb709ac2831a
	Zone: 1
	Management Hostnames: ip2.internal
	Storage Hostnames: 1
	Devices:
		Id:ca4dd68606e34b691ef57fd92165a034   Name:/dev/mapper/gfs-gfs1State:online    Size (GiB):0       Used (GiB):0       Free (GiB):0       
			Bricks:

**Comment by SergeyMuha** [comment]
I have attached 100G EBS, created LVM and mounted
[maintuser@ip- ~]$ df -h
Filesystem                       Size  Used Avail Use% Mounted on
/dev/mapper/VolGroup00-rootVol   3.9G  1.5G  2.2G  40% /
devtmpfs                         470M     0  470M   0% /dev
tmpfs                            495M     0  495M   0% /dev/shm
tmpfs                            495M  516K  495M   1% /run
tmpfs                            495M     0  495M   0% /sys/fs/cgroup
tmpfs                            495M   12K  495M   1% /tmp
/dev/mapper/VolGroup00-varVol    2.0G  114M  1.7G   7% /var
/dev/xvda1                       453M  123M  304M  29% /boot
/dev/mapper/VolGroup00-homeVol   976M  2.6M  907M   1% /home
/dev/mapper/VolGroup00-logVol    2.0G   23M  1.8G   2% /var/log
/dev/mapper/VolGroup00-auditVol  8.3G   41M  7.8G   1% /var/log/audit
tmpfs                             99M     0   99M   0% /run/user/1000
/dev/mapper/gfs-gfs1              99G   33M   99G   1% /data/brick1
[maintuser@ip- ~]$ lsblk 
NAME                    MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
xvda                    202:0    0   20G  0 disk 
|-xvda1                 202:1    0  476M  0 part /boot
`-xvda2                 202:2    0 19.5G  0 part 
  |-VolGroup00-rootVol  253:0    0    4G  0 lvm  /
  |-VolGroup00-swapVol  253:1    0    2G  0 lvm  [SWAP]
  |-VolGroup00-homeVol  253:2    0    1G  0 lvm  /home
  |-VolGroup00-varVol   253:3    0    2G  0 lvm  /var
  |-VolGroup00-logVol   253:4    0    2G  0 lvm  /var/log
  `-VolGroup00-auditVol 253:5    0  8.5G  0 lvm  /var/log/audit
xvdb                    202:16   0  100G  0 disk 
`-xvdb1                 202:17   0  100G  0 part 
  `-gfs-gfs1            253:6    0   99G  0 lvm  /data/brick1

But still don't see any bricks
	Node Id: 066fa6fca1687da61002b86b79a1456f
	State: online
	Cluster Id: b84dc45cac24a23b0687e7e7ce24fad9
	Zone: 1
	Management Hostnames: ip
	Devices:
		Id:b274a2b9bd27e6f8ba5d85a7b00e3409   Name:/dev/mapper/gfs-gfs1State:online    Size (GiB):0       Used (GiB):0       Free (GiB):0       
			Bricks:

	Node Id: 44d0b4eb85cee6b09d12a0ce14290a3b
	State: online
	Cluster Id: b84dc45cac24a23b0687e7e7ce24fad9
	Zone: 1
	Management Hostnames: i
	Devices:
		Id:ba74b35fb09b39c1e9a874cc268d2258   Name:/dev/mapper/gfs-gfs1State:online    Size (GiB):0       Used (GiB):0       Free (GiB):0       
			Bricks:

	Node Id: c06a4e925ed576cf05dfca653c8637ff
	State: online
	Cluster Id: b84dc45cac24a23b0687e7e7ce24fad9
	Zone: 1
	Management Hostnames: 
	Devices:
		Id:dd0d964067c67627642ea2a6bba402de   Name:/dev/mapper/gfs-gfs1State:online    Size (GiB):0       Used (GiB):0       Free (GiB):0       
			Bricks:

**Comment by SergeyMuha** [comment]
also I have tried to remove node and device without luck
ubuntu@ip-1:~/gluster-kubernetes/deploy$ heketi-cli  node list
Id:066fa6fca1687da61002b86b79a1456f	Cluster:b84dc45cac24a23b0687e7e7ce24fad9
Id:44d0b4eb85cee6b09d12a0ce14290a3b	Cluster:b84dc45cac24a23b0687e7e7ce24fad9
Id:c06a4e925ed576cf05dfca653c8637ff	Cluster:b84dc45cac24a23b0687e7e7ce24fad9
ubuntu@ip-11:~/gluster-kubernetes/deploy$ heketi-cli  node remove 066fa6fca1687da61002b86b79a1456f
Node 066fa6fca1687da61002b86b79a1456f is now removed
ubuntu@ip-1:~/gluster-kubernetes/deploy$ heketi-cli  node list
Id:066fa6fca1687da61002b86b79a1456f	Cluster:b84dc45cac24a23b0687e7e7ce24fad9
Id:44d0b4eb85cee6b09d12a0ce14290a3b	Cluster:b84dc45cac24a23b0687e7e7ce24fad9
Id:c06a4e925ed576cf05dfca653c8637ff	Cluster:b84dc45cac24a23b0687e7e7ce24fad9

**Comment by SergeyMuha** [comment]
All nodes formatted equally but I get this error when run 

./gk-deploy -s heketi_key --user-key PASSWORD --admin-key PASSWORD  topology.json

Creating node ip-c2.internal ... ID: bb83feb0d22dc9c42ab1067966d18192
Adding device /dev/mapper/gfs-gfs1 ... OK
Creating node ip-1.ec2.internal ... ID: e8c0ac6827bb0e800c4a3db705787d61
Adding device /dev/mapper/gfs-gfs1 ... Unable to add device: Initializing device /dev/mapper/gfs-gfs1 failed (aleady contains Physical Volume t5KINt-mscx-jsm8-Axc0-6C1d-S2In-SgczRT):   Can't initialize physical volume "/dev/mapper/gfs-gfs1" of volume group "vg_b274a2b9bd27e6f8ba5d85a7b00e3409" without -ff
/dev/mapper/gfs-gfs1: physical volume not initialized.
Creating node ip-c2.internal ... ID: 47dab4236e95e657be28a53d0758670a
Adding device /dev/mapper/gfs-gfs1 ... Unable to add device: Initializing device /dev/mapper/gfs-gfs1 failed (aleady contains Physical Volume nX1DvQ-qkUr-gOhR-n1Pe-4EfW-BmEH-Cfa8fa):   Can't initialize physical volume "/dev/mapper/gfs-gfs1" of volume group "vg_dd0d964067c67627642ea2a6bba402de" without -ff
/dev/mapper/gfs-gfs1: physical volume not initialized.
