### ISSUE TITLE
heketi-start.sh - bugs - race condition caused by archive_db() and invalid secret.

### ISSUE THREAD

**Issue by hetii** [heketi/heketi#1662]
Hi I discover two bugs in heketi-start.sh script.

First occur when archive_db() functions is called before [this condition](https://github.com/heketi/heketi/blob/87979585bef60f92cd8cd4e07a209b38c54e63d1/extras/container/heketi-start.sh#L159). The reason is cause by [this](https://github.com/heketi/heketi/blob/87979585bef60f92cd8cd4e07a209b38c54e63d1/extras/container/heketi-start.sh#L38) db export.

The second issue is about wrong secret made by [this](https://github.com/heketi/heketi/blob/87979585bef60f92cd8cd4e07a209b38c54e63d1/extras/container/heketi-start.sh#L170) line. Finally for the secret double `'` are added and made it invalid.

Best Regards.

**Comment by phlogistonjohn** [comment]
Thanks for the report...

> Hi I discover two bugs in heketi-start.sh script.
> 
> First occur when archive_db() functions is called before [this condition](https://github.com/heketi/heketi/blob/87979585bef60f92cd8cd4e07a209b38c54e63d1/extras/container/heketi-start.sh#L159). The reason is cause by [this](https://github.com/heketi/heketi/blob/87979585bef60f92cd8cd4e07a209b38c54e63d1/extras/container/heketi-start.sh#L38) db export.
> 

I find your statement to be too terse to understand. Can you please elaborate with how you see these lines interacting incorrectly as well as the exact error condition created? I see no code path where archive_db will be called if the heketi.db files does not already exist.


> The second issue is about wrong secret made by [this](https://github.com/heketi/heketi/blob/87979585bef60f92cd8cd4e07a209b38c54e63d1/extras/container/heketi-start.sh#L170) line. Finally for the secret double `'` are added and made it invalid.

Thank you I see the issue you mention here. This code block is special and was created for testing on stuff like minikube and is rarely executed. Can you please create a PR for the removal of the incorrect single quotes?

**Comment by hetii** [comment]
The first issue is caused by line:
`if ! "$HEKETI_BIN" db export --dbfile "${HEKETI_PATH}/heketi.db" --jsonfile - >/dev/null ; then`.
Main reason  is in "db export" because it will create non empty db with some size, even when not exist at the begging, so the condition where you use the `stat` command will never me true.

About second question I can prepare proper MR, and this case is not so rare if you use it as a bootstrap code for clean setup.

Best Regards.

**Comment by phlogistonjohn** [comment]
Thanks @hetii that behavior by heketi export subcommand is certainly incorrect and we should fix that.

**Comment by phlogistonjohn** [comment]
As heketi is now in maintenance mode, and only accepting major bug and security related fixes, we do not expect to implement this change.
