### ISSUE TITLE
Error: Unable to get topology information: Invalid JWT token: Token missing iss claim

### ISSUE THREAD

**Issue by faridy95** [heketi/heketi#1663]
### Kind of issue

> Uncomment only one of these:
> 
> Bug
> Feature request

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): 
- Operating system used: 
- Heketi compiled from sources, as a package (rpm/deb), or container: 
- If container, which container image: 
- Using kubernetes, openshift, or direct install: 
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: 
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom):

**Comment by phlogistonjohn** [comment]
You've provided no details about your situation beyond that it is JWT related. I suggest checking that you've provided the correct authentication params from client to server and then if you still have issues you can reopen this issue with details provided.

**Comment by faridy95** [comment]
How can i configure authentification , if i use heteki-cli il have his error

**Comment by ratibor78** [comment]
Same problem, after configuring Heketi with heketi/extras/kubernetes daemonset I try to run simple heketi-cli commands and get

Error: Invalid JWT token: Token missing iss claim

I have done this setups multiple time before and all was OK, also I can see that auth was disabled in heketi.json file for this Kubernetes deployment

{
  "_port_comment": "Heketi Server Port Number",
  "port": "8080",

  "_use_auth": "Enable JWT authorization. Please enable for deployment",
  "use_auth": false,

**Comment by manisha-tanwar** [comment]
Hi @ratibor78 Did `"use_auth": true`, worked for you? I'm also facing same issue.

**Comment by phlogistonjohn** [comment]
For posterity, recent versions of heketi do not make use of the "use_auth" key in any configuration files. It was too easy for people to deploy heketi with the intent to use authentication and yet fail to actually have auth enabled. See PR #1599 for details.

There is only one way to turn off auth in heketi. I will not elaborate it here as I do not wish to encourage it's use. It's primarily still available for heketi's own test suite. Even with auth enabled by default heketi's poor support for authn/authz and it's lack of good out-of-the-box support for https are two main reasons why I don't recommend heketi for any new installations.

**Comment by manisha-tanwar** [comment]
Thanks for the response @phlogistonjohn I'm able run heketi-cli and everything working as expected but when I try to follow this https://github.com/heketi/heketi/blob/master/docs/api/api.md#python-example I get below error:
```
curl -sk -H "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJhZG1pbiIsImlhdCI6MTYyMDM4MjgzMCwiZXhwIjoxNjIwMzgzMTMwLCJxc2giOiJjMTYyYWNjOTAyNDI3MjEyMGJhY2ZmZjc3MDljOTMyY2MyNTIzMzdkMGEzMGZhMTViMDI1MDEwMDY2NjYyYmVhIn0.-z9AmbFdau4tkzzAqQbHXx4caGV6ZcUtvNiI8t9OqNc" https://heketi.io.local
Invalid qsh claim in token
```

**Comment by manisha-tanwar** [comment]
I'm able to decode it using `jwt.decode(jw_en,'SECRET')` or using https://jwt.io/. But can't use that in API call.

**Comment by phlogistonjohn** [comment]
Can you take this to a *new* issue please? My guess is that the example is probably wrong. But let's avoid continuing to work in a closed issue. Thanks!
