### ISSUE TITLE
Kubernetes setup: "Error: Invalid JWT token: Token missing iss claim "

### ISSUE THREAD

**Issue by ratibor78** [heketi/heketi#1664]
Hi there. I start getting a problem, after configuring Heketi with heketi/extras/kubernetes  

When I try to run simple heketi-cli commands I get

### Error: Invalid JWT token: Token missing iss claim

I have done this setups multiple time before and all was OK, also I can see that auth was still disabled in heketi.json file for this Kubernetes deployment:
```
{
"_port_comment": "Heketi Server Port Number",
"port": "8080",

"_use_auth": "Enable JWT authorization. Please enable for deployment",
"use_auth": false,
```

Do I need any kind of authorization now for the heketi-cli ?

**Comment by deadmandrive** [comment]
got the same problem. Do anyone solved this problem?

**Comment by ratibor78** [comment]
For me, it looks like Heketi was upgraded to some new version, and we start getting new docker image for the Kubernetes deployment, but maybe we also need to change deployment or add any extra configuration in to it ?

**Comment by deadmandrive** [comment]
maybe we try on older version?

**Comment by deadmandrive** [comment]
Hey @ratibor78 I use the old version heketi/heketi:6 and it working now. you should try.

**Comment by ratibor78** [comment]
hah, that what I mean yeah :) I'll also fix the deployment now. Thanks

**Comment by phlogistonjohn** [comment]
Downgrading heketi version after running a new version is not a safe operation. Every time heketi is released with a new version heketi upgrades the db content automatically as needed. Old versions of heketi do not understand these new structures in the db and thus may lead to errors or even invalid dbs. If you do this and the system fails to work correctly afterward we won't be able to help with subsequent issues.

Some of you may be running into the fact that heketi now *requires* authentication by default.  See  #1599. It is highly recommended to make use of the authentication. However, if you absolutely require to run without auth please the the linked PR for a server cli option to turn in off.

**Comment by phlogistonjohn** [comment]
I'll also note that if you're hitting this unexpectedly you're probably running heketi images from the dev tag (aka master branch).  I'm 99% sure we haven't made an official release with this change yet.
If you're running dev/master you should be prepared for behavior changes from time to time. If you don't want this please switch to using a release tag upon our next release.

**Comment by ratibor78** [comment]
@phlogistonjohn Hi, yep you're right as I can see deployments from the git repository have a dev image:

```
"containers": [
              {
                "image": "heketi/heketi:dev",
                "imagePullPolicy": "Always",
                "name": "deploy-heketi",

```
Thanks for the deep anwer, what the latest stable release version that I can use ? 

Thanks a lot.

**Comment by ratibor78** [comment]
@phlogistonjohn Thanks once more for the quick response, I try the latest 9 Heketi version, and it works fine. We can close this issue. 

```
"spec": {
            "serviceAccountName": "heketi-service-account",
            "containers": [
              {
                "image": "heketi/heketi:9",
                "imagePullPolicy": "Always",
                "name": "deploy-heketi",
                "env": [

```

Also @deadmandrive you no need to use 6 old version, you can try the latest. It works for me.

**Comment by ratnakarreddyg** [comment]
# heketi-cli node info 0eb1a3bd26164a3d19f67bab88c37532
Error: Invalid JWT token: Token missing iss claim
# 

I was getting above error and it fixed after executing below export commands.
 
# export HEKETI_CLI_SERVER=http://gluster01:8080
# export HEKETI_CLI_USER=admin
# export HEKETI_CLI_KEY=PASSWORD

#  heketi-cli node list
Id:0eb1a3bd26164a39f67bab88c37532     Cluster:0aae532661dfe3f6b5d45e43742449
Id:25c2d7785cb9a180ad91e61924502a     Cluster:0aae532661dfe3f6b5d45e43742449
Id:4858bf2c3c391de6c95410a65a889f     Cluster:0aae532661dfe3f6b5d45e433742449
#

**Comment by fkpwolf** [comment]
just use
```
./heketi --config=heketi.json --disable-auth=true
```

**Comment by phlogistonjohn** [comment]
@fkpwolf I'd caution against using that option in production. Depending on your settings a heketi instance with no auth can leave your systems in a vulnerable position, thus the change. It's better to set up auth tokens when you upgrade. If you absolutely have to, you could use that option temporarily to transition from an old version to a new one, but I would not suggest leaving in place for very long.

On top of that, this is a fairly old issue you're commenting on. I would guess that you hit something similar, found this issue and also found that option and hoped this would be helpful to others. I sympathize, but as per note above, I feel that I need to warn people of the risks of that approach. I hope you understand.

If you want to further discuss processes/options for the new always-authenticating behavior I recommend starting a new issue. Thanks.

**Comment by anisha24** [comment]
> ```
> Error: Invalid JWT token: Token missing iss claim
> # 
> 
> I was getting above error and it fixed after executing below export commands.
>  
> # export HEKETI_CLI_SERVER=http://gluster01:8080
> # export HEKETI_CLI_USER=admin
> # export HEKETI_CLI_KEY=PASSWORD
> 
> #  heketi-cli node list
> Id:0eb1a3bd26164a39f67bab88c37532     Cluster:0aae532661dfe3f6b5d45e43742449
> Id:25c2d7785cb9a180ad91e61924502a     Cluster:0aae532661dfe3f6b5d45e43742449
> Id:4858bf2c3c391de6c95410a65a889f     Cluster:0aae532661dfe3f6b5d45e433742449
> #```
> ```

This is what worked for me. I checked the heketi user name and key from the heketi.json file and applied them here. Works like a charm after that

**Comment by zhucan** [comment]
> ```
> Error: Invalid JWT token: Token missing iss claim
> # 
> 
> I was getting above error and it fixed after executing below export commands.
>  
> # export HEKETI_CLI_SERVER=http://gluster01:8080
> # export HEKETI_CLI_USER=admin
> # export HEKETI_CLI_KEY=PASSWORD
> 
> #  heketi-cli node list
> Id:0eb1a3bd26164a39f67bab88c37532     Cluster:0aae532661dfe3f6b5d45e43742449
> Id:25c2d7785cb9a180ad91e61924502a     Cluster:0aae532661dfe3f6b5d45e43742449
> Id:4858bf2c3c391de6c95410a65a889f     Cluster:0aae532661dfe3f6b5d45e433742449
> #```
> ```
 where can I get the USER and KEY?  in the heketi.json?
