### ISSUE TITLE
Device is not properly aligned on RAID 5

### ISSUE THREAD

**Issue by bmalynovytch** [heketi/heketi#1665]
### Kind of issue
> Bug

### Observed behavior
Error `device is not properly aligned`
```
[cmdexec] ERROR 2019/10/18 13:37:43 heketi/pkg/remoteexec/ssh/ssh.go:176:ssh.(*SshExec).ExecCommands: Failed to run command [/bin/bash -c 'sudo mkfs.xfs -i size=512 -n size=8192 /dev/mapper/vg_d308ebeb831ad0ea65f896424fc9dd04-brick_4e25ac793d61134f49e546990edde712'] on 10.10.127.12:22: Err[Process exited with status 1]: Stdout []: Stderr [warning: device is not properly aligned /dev/mapper/vg_d308ebeb831ad0ea65f896424fc9dd04-brick_4e25ac793d61134f49e546990edde712
Use -f to force usage of a misaligned device
]
```
### Expected/desired behavior
Alignment should be handled automatically, or documented.
I've tested tons of settings trying to find out the good alignment with no success.

### Details on how to reproduce (minimal and precise)
- Configure RAID 5 storage with mdadm
- Install Heketi
- Configure Heketi (see `/etc/heketi/heketi.json`
- Request a new volume through API (done with Kubernetes PVC)
=> Fail

### Information about the environment:

- Heketi version used : v9.0.0
- Operating system used: CentOS 7.7.1908
- Heketi compiled as a package: amd64 package
- Using Heketi & GlusterFS baremetal and Kubernetes as client with a StorageClass

### Other useful information

`/etc/heketi/heketi.json` :
```
{
  "port": "8090",
  "use_auth": true,
  "jwt": {
    "admin": {
      "key": "SuperSecretAdminPassword"
    },
    "user": {
      "key": "SuperSecretUserPassword"
    }
  },
  "glusterfs": {
    "executor": "ssh",
    "sshexec": {
      "keyfile": "/var/lib/heketi/.ssh/id_rsa-heketi",
      "user": "heketi",
      "sudo": true
    },
    "db": "/var/lib/heketi/heketi.db",
    "loglevel": "info"
  }
}
```
`/etc/heketi/heketi-topology.json` :
```
{
  "clusters": [
    {
      "nodes": [
        {
          "node": {
            "hostnames": {
              "manage": [
                "10.10.127.10"
              ],
              "storage": [
                "10.10.127.10"
              ]
            },
            "zone": 1
          },
          "devices": [
            {
              "name": "/dev/md2",
              "destroydata": false
            }
          ]
        },
        {
          "node": {
            "hostnames": {
              "manage": [
                "10.10.127.11"
              ],
              "storage": [
                "10.10.127.11"
              ]
            },
            "zone": 2
          },
          "devices": [
            {
              "name": "/dev/md2",
              "destroydata": false
            }
          ]
        },
        {
          "node": {
            "hostnames": {
              "manage": [
                "10.10.127.12"
              ],
              "storage": [
                "10.10.127.12"
              ]
            },
            "zone": 3
          },
          "devices": [
            {
              "name": "/dev/md2",
              "destroydata": false
            }
          ]
        }
      ]
    }
  ]
}
```
`mdadm --misc -D /dev/md2`:
```
/dev/md2:
           Version : 1.2
     Creation Time : Mon Oct 14 07:29:38 2019
        Raid Level : raid5
        Array Size : 457828352 (436.62 GiB 468.82 GB)
     Used Dev Size : 228914176 (218.31 GiB 234.41 GB)
      Raid Devices : 3
     Total Devices : 3
       Persistence : Superblock is persistent

     Intent Bitmap : Internal

       Update Time : Fri Oct 18 14:49:51 2019
             State : clean
    Active Devices : 3
   Working Devices : 3
    Failed Devices : 0
     Spare Devices : 0

            Layout : left-symmetric
        Chunk Size : 512K

Consistency Policy : bitmap

              Name : 2
              UUID : 3689ad0c:74994f0b:db1dec66:1da55ff2
            Events : 844

    Number   Major   Minor   RaidDevice State
       0       8        1        0      active sync   /dev/sda1
       1       8       17        1      active sync   /dev/sdb1
       3       8       33        2      active sync   /dev/sdc1
```

Probably related to #876 and #668

**Comment by bmalynovytch** [comment]
To simplify, whats happens is that Heketi handles properly the LVM stack (creates PV, VG and LVs) and fails complaining about data alignment when formatting with XFS.

**Comment by bmalynovytch** [comment]
With the same servers, just changing RAID 5 to RAID 1 (3 disks) makes Heketi happy again.

**Comment by bmalynovytch** [comment]
I seem to have found why `mkfs.xfs` complains about alignment.

With RAID 5:
```
# blkid -i /dev/md2
DEVNAME=/dev/md2
MINIMUM_IO_SIZE=524288
OPTIMAL_IO_SIZE=1048576
PHYSICAL_SECTOR_SIZE=512
LOGICAL_SECTOR_SIZE=512
```

With RAID 1:
```
# blkid -i /dev/md2
DEVNAME=/dev/md2
MINIMUM_IO_SIZE=512
PHYSICAL_SECTOR_SIZE=512
LOGICAL_SECTOR_SIZE=512
```

What this suggests is that Heketi by default creates the LVM PV, without respecting the `minimum_io_size`, setting the `dataalignement` to a default value of 256k.
As 256k is a multiple of 512 (`minimum_io_size` of the RAID 1 block device), it works fine, but as the default `minimum_io_size` of the RAID 5 is 512k, 256k of `dataalignment` is then too small and needs to be raised to at least 512k or any value multiple of 512k.

I'll adjust the value of `dataalignment` in my environments, but I suggest Heketi checks before creating the PV that the provided `dataalignment` setting (or the default) won't break the XFS formatting.
Maybe should the value used by Heketi set to `max(MINIMUM_IO_SIZE, <provided dataalignment setting>)` and check that the value is a multiple of `MINIMUM_IO_SIZE`.

**Comment by bmalynovytch** [comment]
Quickfix:
`pvcreate --metadatasize=128M --dataalignment=$(( $(blkid -i /dev/md2 | grep MINIMUM_IO_SIZE | cut -d= -f2) < 262144 ? 262144 : $(blkid -i /dev/md2 | grep MINIMUM_IO_SIZE | cut -d= -f2) )) /dev/md2`

**Comment by nAnderYang** [comment]
mdadm create raid0 disk array ，the error is the same as above....
`[kubeexec] ERROR 2020/11/07 09:10:28 heketi/pkg/remoteexec/log/commandlog.go:56:log.(*CommandLogger).Error: Failed to run command [mkfs.xfs -i size=512 -n size=8192 /dev/mapper/vg_0048cb265d95be1109179d37fbcceae9-brick_c028b35bf958e3384472f13267049008] on [pod:glusterfs-2r6b2 c:glusterfs ns:glusterfs (from host:eruit-mn-02 selector:glusterfs-node)]: Err[command terminated with exit code 1]: Stdout []: Stderr [warning: device is not properly aligned /dev/mapper/vg_0048cb265d95be1109179d37fbcceae9-brick_c028b35bf958e3384472f13267049008
Use -f to force usage of a misaligned device
]
`

CentOS7.8.2003
kubernetes v1.18.8
heketi-cli v10.0.0-22

**Comment by phlogistonjohn** [comment]
As heketi is now in maintenance mode, and only accepting major bug and security related fixes, we do not expect to implement this change.
