### ISSUE TITLE
heketi - support for volume network ping timeout settings.

### ISSUE THREAD

**Issue by hetii** [heketi/heketi#1667]
Hi.
According issue described [here](https://thornelabs.net/posts/change-gluster-volume-connection-timeout-for-glusterfs-native-client.html) or [here](https://serverfault.com/questions/619355/how-to-lower-gluster-fs-down-peer-timeout-reduce-down-peer-impact) is it possible from kubernetes/heketi perspective set network ping timeout for volumes, for eg. by some annotation?

**Comment by phlogistonjohn** [comment]
Any volume option can be stored in the storage class (k8s) or passed in at volume creation by the heketi cli. 

Note that heketi can only set these at volume create time, but if you change them on gluster directly heketi won't mess with them.

**Comment by phlogistonjohn** [comment]
Stale issue. Closing. Please reopen if you are still experiencing this problem.
