### ISSUE TITLE
We have a volume in Gluster, but we can't see this volume in Heketi after restoring the Heketi DB from backup

### ISSUE THREAD

**Issue by Cyreex** [heketi/heketi#1670]
### Kind of issue

Question

### Observed behavior

We have a volume in Gluster, but we can't manage this volume from Heketi.

### Expected/desired behavior

How can we add this volume to Heketi? 

### Details on how to reproduce (minimal and precise)

1. Create Heketi DB backup
2. Create a volume in Heketi (heketi-cli volume create ...)
3. Restore Heketi DB from backup

### Information about the environment:

- Heketi version: v9.0.0: 
- Operating system used: Fedora release 27
- Heketi compiled from: container
- Container image: heketi/heketi:latest
- Using: kubernetes
- Gluster running inside kubernetes

**Comment by phlogistonjohn** [comment]
There's no supported way in heketi to add the volume back into the heketi db state.
If you want to you can try stopping heketi and exporting the db to JSON and altering the JSON to add the volume and bricks needed to the db. Unfortunately, this is not a documented procedure and you'd be on your own to make the edits.
It might be simpler to simply create a new volume of the same size, migrate the contents over and then delete the "missing" volume and bricks directly from gluster + lvm.
