### ISSUE TITLE
Heketi - FailedMount

### ISSUE THREAD

**Issue by ZrytyADHD** [heketi/heketi#1671]
Hi, 
I have an issue with heketi.
Yesterday i have a network crash in my openshift cluster and after that heketi can't restore container hanging in `Container creating` state. 
When i use describe pod command i getting this:
`  Normal   Scheduled    12s                default-scheduler               Successfully assigned app-storage/heketi-storage-1-gf48g to server9`
`  Warning  FailedMount  5s (x25 over 12s)  kubelet, server9  MountVolume.NewMounter initialization failed for volume "db" : endpoints "heketi-db-storage-endpoints" not found`

Also i cant reach any PV or create PVC. Can any one know how to resolve this issue ?

**Comment by phlogistonjohn** [comment]
Stale issue. Closing. Please reopen if you are still experiencing this problem.
