### ISSUE TITLE
Heketi doesn't separate cli output - heketi-cli node info

### ISSUE THREAD

**Issue by amgads** [heketi/heketi#1672]
### Kind of issue

> Uncomment only one of these:
> Bug
Heketi doesn't separate cli output - heketi-cli node info

### Observed behavior

When running "heketi-cli node info" with a long device name, no space between the device name and the next field "State:". It's not clear if heketi code is missing a space or the field is fixed so if the device name is long enough it missed part of it.

Th output is used to covert from id to name and vice versa

heketi-cli node info output
=================
Node Id: 9d6f525461398e0c8713570143da41c0
 State: online
 Cluster Id: 06f884a672b0b95066c4be5e630bf8f7
 Zone: 1
 Management Hostname: lilian-worker-0
 Storage Hostname: 172.16.4.19
 Devices:
 Id:edca7994df74e5d056bd9b317e9e2b60   Name:/dev/disk/by-id/virtio-2ee41b10-b059-4a37-aState: online    Size (GiB):2       Used (GiB):0       Free (GiB):2       Bricks:0

### Expected/desired behavior (there should be a space or tab between the device name and next field "State: "
Devices:
 Id:edca7994df74e5d056bd9b317e9e2b60   Name:/dev/disk/by-id/virtio-2ee41b10-b059-4a37-a State: online    Size (GiB):2       Used (GiB):0       Free (GiB):2       Bricks:0

### Details on how to reproduce (minimal and precise)
use device name with long id

### Information about the environment:

- Heketi v9.0.0
- Operating system used: linux
- Heketi compiled from sources, as a package (rpm/deb), or container: 
- If container, which container image:  own
- Using kubernetes, openshift, or direct install: Kubernetes
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: inside

**Comment by phlogistonjohn** [comment]
I think this is fixed on master but am not 100% sure. If you can, please test this on master or just wait until we create the next release and try again on that release.

**Comment by amgads** [comment]
Thanks John. Can you confirm if it's a missed space before the "State:"or a fixed length problem where device can be missing displaying some characters?

**Comment by phlogistonjohn** [comment]
I don't know, your best bet is probably to check the source code.
If you're concerned about missing info due to formatting failures you're probably better off checking the api directly or using the --json switch on heketi cli. It might be a tad harder to read if you're eyeballing it but you can always to for format it nicer with something like jq.

**Comment by kadern0** [comment]
This has been fixed:
```
Devices:
Id:1b93b2bcd35449003177d9ec733dddb8   Name:/dev/sdc            State:online    Size (GiB):99      Used (GiB):93      Free (GiB):6       
Id:af133ec336aab73f4b55993bfb2e8aac   Name:/dev/sdd            State:online    Size (GiB):599     Used (GiB):78      Free (GiB):521     
```

**Comment by phlogistonjohn** [comment]
If the reported issue was fixed by side effect of something else, great. Otherwise heketi is in maintenance mode and this would be a wontfix. Therefore I'm closing this issue.
