### ISSUE TITLE
Can't create volume - "Running as a non-root user"

### ISSUE THREAD

**Issue by holmesb** [heketi/heketi#1674]
We are running heketi as sudo:
`heketi@storage01:~$ sudo -E /usr/local/bin/heketi --config=/etc/heketi/heketi.json`

When we try to create a volume:
`heketi@storage01:~$ sudo -E heketi-cli volume create --durability=none --size=1`

We see error:
`[cmdexec] ERROR 2019/11/08 14:58:05 heketi/pkg/remoteexec/ssh/ssh.go:176:ssh.(*SshExec).ExecCommands: Failed to run command [/bin/bash -c 'lvcreate -qq --autobackup=n --poolmetadatasize 8192K --chunksize 256K --size 1048576K --thin vg_1eaac870bd7790a2325311443ef77824/tp_e460f302cd5ca22f3f97cb73d2d28952 --virtualsize 1048576K --name brick_d98645fff91e19e6f08daaa2e02e5490'] on storage01:22: Err[Process exited with status 5]: Stdout []: Stderr [  WARNING: Running as a non-root user. Functionality may be unavailable.
/run/lvm/lvmetad.socket: access failed: Permission denied
`

In sudoers, heketi user has:
`heketi ALL=(ALL:ALL) NOPASSWD: ALL`

Any ideas?  Many thanks

### Information about the environment:

- Heketi version used: v9.0.0
- Operating system used: Ubuntu 18.04
- Heketi compiled from sources, as a package (rpm/deb), or container: binary download
- Using kubernetes, openshift, or direct install: direct install

**Comment by phlogistonjohn** [comment]
You seem to be confused about how heketi works. Heketi does not execute any commands as children of the server (or client) process but rather runs commands on nodes or pods over the network. It is those commands that need privileges. The SSH executor has an option to make heketi automatically prefix the commands with 'sudo' this option is [documented](/heketi/heketi/blob/master/docs/admin/server.md) under the "sshexec" section as simply "sudo".
Try setting that option and do not run the heketi server or cli with sudo.

**Comment by holmesb** [comment]
Hi @phlogistonjohn 
Heketi doesn't seem to like this option:
`heketi@storage01:~$ sudo -E /usr/local/bin/heketi --version
Heketi v9.0.0
heketi@storage01:~$ cat /etc/heketi/heketi.json |grep -C10 sshexec
    }
  },

  "_glusterfs_comment": "GlusterFS Configuration",
  "glusterfs": {
    "_executor_comment": [
      "Execute plugin. Possible choices: mock, ssh",
      "mock: This setting is used for testing and development.",
      "      It will not send commands to any node.",
      "ssh:  This setting will notify Heketi to ssh to the nodes.",
      "      It will need the values in sshexec to be configured.",
      "kubernetes: Communicate with GlusterFS containers over",
      "            Kubernetes exec api."
    ],
    "executor": "ssh",

    "_sshexec_comment": "SSH username and private key file information",
    "sshexec": {
      "keyfile": "/etc/heketi/heketi_key",
      "user": "heketi",
      "port": "22",
      "sudo": "true",
      "fstab": "/etc/fstab"
    },

    "_kubeexec_comment": "Kubernetes configuration",
    "kubeexec": {
      "host" :"https://kubernetes.host:8443",
heketi@storage01:~$ sudo -E /usr/local/bin/heketi --config=/etc/heketi/heketi.json
Heketi v9.0.0
ERROR: Unable to parse configuration: json: cannot unmarshal string into Go struct field SshConfig.sudo of type bool`

**Comment by holmesb** [comment]
Thanks @phlogistonjohn, adding the sudo parameter to sshexec section fixed.  Onto the next error now.
