### ISSUE TITLE
need : expand a volume using lvm resize

### ISSUE THREAD

**Issue by yjbdsky** [heketi/heketi#1683]
expand volume 1G to 2G,, but i can not Write a file larger than 1G
`dd if=/dev/zero of=/mount/path/glusterfs/volume bs=1M count=2000`
an error happend No space left on device  on write 1G data

**Comment by phlogistonjohn** [comment]
I do not think this is something the current maintenance team will pursue. Heketi can already expand a volume using the 'heketi-cli volume expand' feature. I will leave this open for a bit in case you or some else wants to investigate this.

**Comment by phlogistonjohn** [comment]
Probably never going to happen. Closing
