### ISSUE TITLE
Please confirm license for "utils"

### ISSUE THREAD

**Issue by markxnelson** [heketi/heketi#1684]
Hi, could you please confirm what license applies to the "utils" repo.  The readme says Apache License 2.0 but points to this file https://github.com/heketi/heketi/blob/master/LICENSE which seems to say that utils would be under a dual license of LGPLv3+ or GPLv2.
Thank you in advance for confirming, and thanks for your work to create/maintain this. :)

**Comment by phlogistonjohn** [comment]
The license preambles at the top of the files should have precedence over  any general statements.
Files in pkg/utils are typically dual licensed LGPL 3 and Apache 2.

We intend for the api code and the helper libs that support the api packages to be usable in other code bases (such as k8s) and thus this dual license. That does not apply to all of the server code however.

**Comment by markxnelson** [comment]
Thank you very much for your prompt response.
