### ISSUE TITLE
GlusterFS Volume Creation Suggestion

### ISSUE THREAD

**Issue by imranrazakhan** [heketi/heketi#1688]
### Kind of issue
Query

I have to deploy multiple Openshift Clusters from 3 nodes to 10 nodes. For 3 nodes i am creating volumes as replicated(which is default option).

But for 4 and above it doesn't look nice to create replicated volume, so each node has 300GB disk and replicating it to 10 nodes is not optimal. I am looking for formula to use like 

    For 4 nodes create volume as disperse:2:1
    For 5 nodes create volume as disperse:?:?
    For 6 nodes create volume as disperse:?:?
    For 7 nodes create volume as disperse:?:?
    For 8 nodes create volume as disperse:?:?
    For 9 nodes create volume as disperse:?:?
    For 10 nodes create volume as disperse:?:?

in openshift ansible
`openshift_storage_glusterfs_storageclass_volume_type=disperse:?:?`

**Environment:**
I will use these volumes for MYSQL 5.7.28 and Each Server has 300GB disk, Out of 300GB i will create volume with size of 250GB for MYSQL.

    OpenShift 3.11 version

    # gluster --version
    glusterfs 6.1

PS: i have no background of storage, so excuse if i am missing some obvious point i tried to search on google but couldn't extract required info.

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): 7.0.0
- Operating system used: CentOS
- Using kubernetes, openshift, or direct install: openshift OKD 3.11
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: outside
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): openshift-ansible

**Comment by phlogistonjohn** [comment]
Honestly, I don't know of anyone else using heketi with disperse/ec on gluster. I personally do not have the ability to support that mode. I'm afraid you are basically on your own wrt this topic, sorry.
