### ISSUE TITLE
Heketi pod in CrashLoopBackOff status: Unable to start application

### ISSUE THREAD

**Issue by CassandraWin** [heketi/heketi#1690]
### Heketi remains in CrashLoopbackOff status
Bug

### Observed behavior

> [root@fra-vka-testl2 ~]# kubectl logs pods/heketi-8d85f8d-g96fq -n kube-system
Setting up heketi database
  File: /var/lib/heketi/heketi.db
  Size: 262144          Blocks: 296        IO Block: 131072 regular file
Device: c8h/200d        Inode: 12847849052084580490  Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-01-09 17:44:46.722449960 +0000
Modify: 2020-01-24 00:03:20.084589416 +0000
Change: 2020-01-24 00:03:20.084589416 +0000
 Birth: -
Heketi v9.0.0-1-g57a5f356-release-9
[heketi] INFO 2020/01/24 11:12:11 Loaded kubernetes executor
ERROR: Unable to start application: invalid page type: 18: 10

### Information about the environment:

- Heketi version used: v9.0.0
- Operating system used: 
- Heketi container: heketi:9.0.0
- kubernetes deployed using Ansible HyperKube
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: 
- kubernetes with glusterfs deployed using gk-deploy

### Other useful information
```
[root@fra-vka-testl3 ~]# kubectl exec pods/glusterfs-dct5w -n kube-system -- gluster vol info heketidbstorage

Volume Name: heketidbstorage
Type: Replicate
Volume ID: 7065d510-4a9c-4439-8be2-670c9d8d27c5
Status: Started
Snapshot Count: 0
Number of Bricks: 1 x 3 = 3
Transport-type: tcp
Bricks:
Brick1: 192.168.219.77:/var/lib/heketi/mounts/vg_4d64da775e01ffded8fe3befdb445251/brick_cc952216aded9d1d1c82a79628557cf4/brick
Brick2: 192.168.219.82:/var/lib/heketi/mounts/vg_f4f5d03291387934a238e19fb52944da/brick_f50d3641752fd46b6e198efbda7fc85c/brick
Brick3: 192.168.219.81:/var/lib/heketi/mounts/vg_dc1bf3dd126e5c6876f76ce10f1817f4/brick_0494fabe22cc2bf43cb07b9f2cf1d5c9/brick
Options Reconfigured:
user.heketi.id: 95a809b4b9c1f0dbed4499c4ec513947
user.heketi.dbstoragelevel: 1
performance.readdir-ahead: off
performance.io-cache: off
performance.read-ahead: off
performance.strict-o-direct: on
performance.quick-read: off
performance.open-behind: off
performance.write-behind: off
performance.stat-prefetch: off
transport.address-family: inet
nfs.disable: on
performance.client-io-threads: off
```
```
[root@fra-vka-testl3 ~]# kubectl exec pods/glusterfs-dct5w -n kube-system -- gluster vol status heketidbstorage
Status of volume: heketidbstorage
Gluster process                             TCP Port  RDMA Port  Online  Pid
------------------------------------------------------------------------------
Brick 192.168.219.77:/var/lib/heketi/mounts
/vg_4d64da775e01ffded8fe3befdb445251/brick_
cc952216aded9d1d1c82a79628557cf4/brick      49152     0          Y       135
Brick 192.168.219.82:/var/lib/heketi/mounts
/vg_f4f5d03291387934a238e19fb52944da/brick_
f50d3641752fd46b6e198efbda7fc85c/brick      49161     0          Y       135
Brick 192.168.219.81:/var/lib/heketi/mounts
/vg_dc1bf3dd126e5c6876f76ce10f1817f4/brick_
0494fabe22cc2bf43cb07b9f2cf1d5c9/brick      49152     0          Y       135
Self-heal Daemon on localhost               N/A       N/A        Y       267
Self-heal Daemon on 192.168.219.77          N/A       N/A        Y       267
Self-heal Daemon on 192.168.219.82          N/A       N/A        Y       267

Task Status of Volume heketidbstorage
------------------------------------------------------------------------------
There are no active volume tasks
```
Thanks in advance for your help.

**Comment by phlogistonjohn** [comment]
That error usually corresponds to a corrupted bolt db file. You can try to try and recover the contents of the db using boltdb tools or if you have been running a newish container build you can check if the archive directory has db backups in it.

**Comment by CassandraWin** [comment]
Thanks for your fast answer. Can you please tell me more on how to recover the content of the db using boltdb tool?

Best regards,

**Comment by phlogistonjohn** [comment]
Bolt db level corruption. There's nothing heketi can do to recover from this situation. If this is still a problem I recommend trying to scrape the relevant data from the corrupted db and create a new db with the data (from json). I have done it so I know it can be done, however it is challenging and I can offer no specific assistance at this time.
Closing as "cantfix".

**Comment by lixiaopengxiya** [comment]
> 螺栓数据库级别损坏。heketi无法采取任何措施从这种情况中恢复过来。如果仍然存在问题，我建议尝试从损坏的数据库中抓取相关数据，并使用该数据（来自json）创建一个新的数据库。我已经做到了，所以我知道可以做到，但是这是一个挑战，目前我无法提供任何具体帮助。
> 以“ cantfix”结束。

I want to know how this problem happened. Can I repeat it and take preventive measures

**Comment by iamniting** [comment]
There are no specific reproducer to reproduce it. I think bolt db is specific place for this question.
