### ISSUE TITLE
Mount failed:E [glusterfsd.c:795:gf_remember_backup_volfile_server] 0-glusterfs: failed to set volfile server: File exists

### ISSUE THREAD

**Issue by minhnnhat** [heketi/heketi#1696]
Hi all, i am facing some trouble when following this tutorial below: 
https://medium.com/searce/glusterfs-dynamic-provisioning-using-heketi-as-external-storage-with-gke-bd9af17434e5
Everything work fine until i create NFS provisioner using that glusterfs storageclass.
PVC is bound but the pods is pending at containercreating state with the following error :

MountVolume.SetUp failed for volume "pvc-c5467b40-89d9-481a-ba71-3e04d3c967de" : mount failed: mount failed: exit status 1 Mounting command: mount Mounting arguments: -t glusterfs -o auto_unmount,backup-volfile-servers=x.x.x.168:x.X.x.169:x.x.x.171,log-file=/var/lib/kubelet/plugins/kubernetes.io/glusterfs/pvc-c5467b40-89d9-481a-ba71-3e04d3c967de/nfs-provisioner-0-glusterfs.log,log-level=ERROR x.X.x.171:vol_41c950a0380cb8f7ed10e4e16a25274a /var/lib/kubelet/pods/2fd2b171-cc90-4e9c-84fe-65208fc60790/volumes/kubernetes.io~glusterfs/pvc-c5467b40-89d9-481a-ba71-3e04d3c967de Output: [2020-02-10 02:24:35.257276] E [glusterfsd.c:795:gf_remember_backup_volfile_server] 0-glusterfs: failed to set volfile server: File exists Mount failed. Please check the log file for more details. , the following error information was pulled from the glusterfs log to help diagnose this issue: /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7f212f166d0f] ---------

About the environment:
Heketi version v8.0.0
Rancher: 2.3.5
Kubernetes: v1.17.2
Glusterfs: 7.2

Thank for your help !!!

**Comment by phlogistonjohn** [comment]
heketi does not work with an NFS provisioner. It works with the glusterfs provisioner.
Nor do we directly work on any of the provisioners. I'm afraid you're on your own with this one, sorry.
