### ISSUE TITLE
outdated manifest files

### ISSUE THREAD

**Issue by n-able-consulting** [heketi/heketi#1697]
The manifest files under heketi/extras/kubernetes are outdated.
1) Since kubernetes 1.16 some API-Object versions are deprecated:
    a) glusterfs-daemonset.json daemonset apiVersion must become apps/v1
    b) heketi-deployment.json deployment apiVersion must become apps/v1
    c) heketi-bootstrap.json deployment apiVersion must become apps/v1
2) Docker hub glusterfs images are updated to version 7.1, these work not wel with heketi. All sorts of problems occure, when trying to make it work... Solution refert back to older image version.
    a) glusterfs-daemonset.json daemonset image must become gluster/gluster-centos:gluster4u1_centos7

**Comment by phlogistonjohn** [comment]
Those files are just examples and are not meant to be used for "real" deployments. Some users use gluster-kubernetes, but unfortunately that project seems unmaintained now. Others have successfully used openshift-ansible (on openshift of course).
We'd welcome contributions in this area but I'm afraid we don't have the resources to work on that stuff ourselves at this time.

**Comment by n-able-consulting** [comment]
He john, your response is quit defensive. I use those manifest as bases for
an automated deployment, working in all versions of k8s. If you take my
suggestions the manifests will be up to spec.
Otherwise i suggest remove the k8s manifests from your source tree as they
are obsolete.
With kind regards,
Ruben visser

Op za 14 mrt. 2020 20:06 schreef John Mulligan <notifications@github.com>:

**Comment by henri9813** [comment]
Hello, 

If they are only "examples", why do you keep them on the repo ? 

Can you please just update them to use the latest kubernetes compatibility ?

Best regards,
Henri
