### ISSUE TITLE
Create RPM for deployment

### ISSUE THREAD

**Issue by lpabon** [heketi/heketi#17]
Currently Heketi uses a simple Makefile to create a tar.gz distribution since it is written in Go.  We may need to support an RPM so that it is installed with systemd support.

**Comment by lpabon** [comment]
According to [Fedora Golang Packaging](https://fedoraproject.org/wiki/PackagingDrafts/Go) all the dependencies must have their own repo for the build process.

I will first determine which dependencies need repos and which do not for Release 1

**Comment by lpabon** [comment]
The following repo dependencies must be create:
### Release 1
* golang-golang-x-crypto
* golang-github-lpabon-godbc
* golang-github-auth0-go-jwt-middleware
* golang-github-codegangsta-negroni
* golang-github-dgrijalva-jwt-go

### Release 2
Release 2 also needs the following:

* golang-github-heketi-tests
* golang-github-heketi-rest
* golang-github-heketi-utils

**Comment by lpabon** [comment]
There is this really cool tool called [gofed](https://github.com/gofed/gofed) highlighted in the Fedora document.  I used it to start the spec file.  It also points out which dependencies are not part of Fedora:

```shell
$ gofed github2spec -p heketi -r heketi \
   --commit 7d2a7830f0c793ae8151c119ea41b3e8f0148c60 -f

Repo URL: github.com/heketi/heketi
Commit: 7d2a7830f0c793ae8151c119ea41b3e8f0148c60
Name: golang-github-heketi-heketi

(1/4) Checking if the package already exists in PkgDB
(2/4) Downloading tarball
(3/4) Generating spec file
(4/4) Discovering golang dependencies
Class: github.com/auth0/go-jwt-middleware (golang-github-auth0-go-jwt-middleware) PkgDB=False
Class: github.com/boltdb/bolt (golang-github-boltdb-bolt) PkgDB=True
Class: github.com/codegangsta/negroni (golang-github-codegangsta-negroni) PkgDB=False
Class: github.com/dgrijalva/jwt-go (golang-github-dgrijalva-jwt-go) PkgDB=False
Class: github.com/gorilla/context (golang-github-gorilla-context) PkgDB=True
Class: github.com/gorilla/mux (golang-github-gorilla-mux) PkgDB=True
Class: github.com/lpabon/godbc (golang-github-lpabon-godbc) PkgDB=False
Class: golang.org/x/crypto (golang-github-golang-crypto) PkgDB=False

Spec file golang-github-heketi-heketi.spec at /home/lpabon/git/fedora/heketi/golang-github-heketi-heketi/fedora/golang-github-heketi-heketi
```

**Comment by lpabon** [comment]
Gofed tool is making things **much** easier.  I did find an issue and provided a patch here: https://github.com/gofed/gofed/issues/60

**Comment by lpabon** [comment]
Need to create 5 spec files for dependencies and one for Heketi. (see comments above).

* Negroni spec file uploaded to Fedora: https://bugzilla.redhat.com/show_bug.cgi?id=1271684

**Comment by lpabon** [comment]
* Dgrijalva-Jwt-Go spec file uploaded to Fedora: https://bugzilla.redhat.com/show_bug.cgi?id=1271708

**Comment by lpabon** [comment]
* Godbc file uploaded to Fedora: https://bugzilla.redhat.com/show_bug.cgi?id=1271805

**Comment by lpabon** [comment]
There seems to be some confusion on how to satisfy `golang/x/crypto` dependency in Fedora.  I sent a message to the package maintainer to see if they could answer my questions.

**Comment by ingvagabund** [comment]
negroni and godbc approved, jwt-go already created [1]

[1] https://admin.fedoraproject.org/pkgdb/package/golang-github-dgrijalva-jwt-go/

**Comment by lpabon** [comment]
Sweet!

**Comment by lpabon** [comment]
@ingvagabund Do you mind taking a look at another dependency spec file I will be submitting?  The project spec file is [golang-auth0-go-jwt-middleware.spec](https://github.com/lpabon/heketi-rpm/blob/master/golang-github-auth0-go-jwt-middleware/fedora/golang-github-auth0-go-jwt-middleware/golang-github-auth0-go-jwt-middleware.spec) .  The issue I found while setting up this spec file is that they have a bug (actually quite a few) in their unit test.  So I removed the unit test package from this spec file.

Do you think that is ok?

**Comment by ingvagabund** [comment]
unit-test subpackage is optional. Even if the tests do not pass, it is good to provide the package. Just disable test (setting with_check to 0). It can be used for monitoring of actual state of the package. Once CI environment is finished, all unit-test* subpackage get installed and all tests get run. As a result you will get a list of tests that does not pass.

**Comment by ingvagabund** [comment]
Can you create a review for it? I will check it out :).

**Comment by lpabon** [comment]
@ingvagabund Great! I will set it up and do that.

**Comment by lpabon** [comment]
@ingvagabund Auth0 Middleware for Fedora: https://bugzilla.redhat.com/show_bug.cgi?id=1272116

**Comment by lpabon** [comment]
Heketi RPM review: https://bugzilla.redhat.com/show_bug.cgi?id=1272248

**FINALLY**

**Comment by lpabon** [comment]
@heketi/qe RPMs

**Comment by lpabon** [comment]
Submitted to Fedora to create packages for these rpms

**Comment by lpabon** [comment]
Heketi RPMs are now available for EPEL and Fedora 22+
