### ISSUE TITLE
stale operations cleanup fails

### ISSUE THREAD

**Issue by amgads** [heketi/heketi#1708]
### Kind of issue
After creating a bulk volumes ~73, lots of operations are staled inside heketi container
Tried to cleanup using
heketi-cli   ---> got the following error
bash-4.2# heketi_cli.py server operations cleanup
Error: Get http://10.254.0.101:8080/queue/4e2848797e82e96ad1af7e0db023ea39: dial tcp 10.254.0.101:8080: getsockopt: connection refused

heketi_cli.py is a wrapper around heketi-cli with server, user, secret set

```
bash-4.2# heketi_cli.py server operations list
Id:010bde74f6a12ef1e8429e47acc1fc6f  Type:create-volume  Status:stale 
Id:0bb48e556cee6ece1e869700fd9681bc  Type:create-volume  Status:stale 
Id:14c985b37157d34079fa6eb32c7a2d7f  Type:create-volume  Status:stale 
Id:18de5da8200c74f556c8127e1a1dbbeb  Type:create-volume  Status:stale 
Id:1b604f6ad92ded284e87cac46d1f63e4  Type:create-volume  Status:stale in-flight
Id:1d099857d0de5a5fe33dc27d359471e9  Type:create-volume  Status:stale 
Id:23a2c209350892da197281fb06e20a71  Type:create-volume  Status:stale 
Id:2baadc115c037628d9fadc8193c95556  Type:create-volume  Status:stale 
Id:2d44fa617e97b5d0b2c27ca130b5dad2  Type:create-volume  Status:stale 
Id:2fcab78ec4d095e465bd2616b11aafad  Type:create-volume  Status:stale 
Id:452e889f1b6e0f8c78b7ca6424aa15bb  Type:create-volume  Status:stale 
Id:493d520f70a7e051b8a545dc9c5e78d1  Type:create-volume  Status:stale 
Id:4948915ffaabaf99baa50d875a0bf817  Type:create-volume  Status:stale 
Id:4ad0b1636f0d2c153fd8ed0677a4fc4a  Type:delete-volume  Status:stale 
Id:576064419e03b6d20f1315790ae681de  Type:create-volume  Status:stale 
Id:62fa581366b99ff9d6f7b86a3c21cbb6  Type:create-volume  Status:stale 
Id:67cf25e599af2bc00aa3bed5b161186b  Type:create-volume  Status:stale 
Id:698aefb6df7f72fffc51f79eb10a0c6a  Type:create-volume  Status:stale 
Id:76ac0e74e23d153e0a6f98c9df3c2796  Type:create-volume  Status:stale 
Id:794ff955dfcb44db31bd3372bfaad546  Type:create-volume  Status:stale 
Id:7ae503aa40cc88975c08e7c166f5f378  Type:create-volume  Status:stale 
Id:819369ae89f27cb695ba5ac190738d08  Type:create-volume  Status:stale 
Id:876841b6cebfa23625e2f8b7ed4018a2  Type:create-volume  Status:stale 
Id:8ff3b6b4f7a5c4efd9bf26ba660c74c5  Type:create-volume  Status:stale 
Id:91170196107a0049f7fd04031c0e1c6d  Type:create-volume  Status:stale 
Id:9499cdff630850e3f818ae28284ae07e  Type:create-volume  Status:stale 
Id:9c843c3fb7c613bf987b67fdc6880d1a  Type:create-volume  Status:stale 
Id:a4d5909151b9a053094ab94a1e34a519  Type:create-volume  Status:stale 
Id:a6881e4bf9da6567972e5cc7e4fcac92  Type:create-volume  Status:stale 
Id:a8a2de8a972f47e0b4fcf8993b3a5f2d  Type:create-volume  Status:stale 
Id:ab9dde238406c9300ff013253aa589e4  Type:create-volume  Status:stale 
Id:acc93715ed82f30714fcfcf28f1d6f27  Type:delete-volume  Status:stale 
Id:b0bad74d6ec16db469f9f5c0e74912a7  Type:create-volume  Status:stale 
Id:b0c656bd34fc02c9431902fde48a2772  Type:create-volume  Status:stale 
Id:b8d61b1968beb460ec679db0b756744c  Type:create-volume  Status:stale 
Id:bd7966510379a70e868a70008f471b78  Type:create-volume  Status:stale 
Id:bd925df96ca8f5ae7b48ca80b13e2182  Type:create-volume  Status:stale 
Id:c2fc79a3d32d949b830a17d8373a24e3  Type:create-volume  Status:stale 
Id:ce24451da26b9440fd0fb5c5396b87dc  Type:create-volume  Status:stale 
Id:d0213794e4779cccc59a96e4b55e3d0d  Type:create-volume  Status:stale 
Id:d17914d148a4be61be0d516cb811db97  Type:create-volume  Status:stale 
Id:da5ebc5a79f01f356b7d8e27c083e0d9  Type:create-volume  Status:stale 
```

The heketi.json looks like this

```
{
  "port": "8080",
  "use_auth": true,

  "jwt": {
    "admin": {
      "key": "QuUD5RJI"
    },
    "user": {
      "key": "bmjtzFXA"
    }
  },

  "glusterfs": {
    "executor": "ssh",
    "sshexec": {
      "keyfile": "/etc/heketi/gluster_user_private_key",
      "user": "gluster-user",
      "port": "22",
      "fstab": "/etc/fstab",
      "sudo": true
    },

    "max_inflight_operations": 64,
    "operation_retry_limits": { "volume_create": 8 },
    "db": "/var/lib/heketi/heketi.db",
    "loglevel" : "warning"
  }
}
```

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): v9.0.0
- Operating system used: Linux
- Heketi compiled from sources, as a package (rpm/deb), or container:  Container using tar file
- If container, which container image: 
- Using kubernetes, openshift, or direct install: K8S
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: inside
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom):

**Comment by phlogistonjohn** [comment]
The fact that you are seeing a `connection refused` when running `server operations cleanup` makes me wonder if the server is panicking for some reason.
I think we will need heketi logs to debug further. I recommend putting the logs at https://paste.centos.org/ or uploading the log contents somewhere.

**Comment by amgads** [comment]
Thanks John - I uploaded the heketi log to paste.centos.org -- file name "heketi_log_for_cleanup_failure" by amgads.  One thing I found one of the gluster nodes had glustershd down and when booted -- it came up. The number of stale operations decreased, but still the remaining couldn't cleanup -- thanks for your support

**Comment by phlogistonjohn** [comment]
>  paste.centos.org

That's not typically how a pastebin works. Generally you paste your content and then provide a url here. For example I just created a test paste like so: https://paste.centos.org/view/8d262c38
In addition the pastes at paste.centos.org expire in a day so since I was not working on heketi for the last few days the paste would likely have expired anyway.

Can you please try again?

**Comment by amgads** [comment]
Thanks John

At https://paste.centos.org there’s an option “Create Shorturl - Create a shorter url that redirects to your paste?”
But it’s not allowing me to choose it.

Also tried the command line

# curl -d private=1 -d name=Amgad --data-urlencode text@/u/amgad/heketi.txt<mailto:text@/u/amgad/heketi.txt> https://paste.centos.org/api/create
Warning: Couldn't read data from file "text@/u/amgad/heketi.txt", this makes
Warning: an empty POST.
Invalid API key

I did paste one with heketi.log – issue 1708 in title and pressed create – it did, but didn’t return any address or pointer!!!

I tried https://paste.centos.org/api/recent but got “Invalid API key”

Do I need permission? Can I attach the file to the email?

Regards,
Amgad

**Comment by phlogistonjohn** [comment]
> 
> Thanks John
> 
> At https://paste.centos.org there’s an option “Create Shorturl - Create a shorter url that redirects to your paste?”
> But it’s not allowing me to choose it.
> 

You don't need that. The regular one it should generate is fine.

> Also tried the command line
> 
> curl -d private=1 -d name=Amgad --data-urlencode text@/u/amgad/heketi.txt<mailto:text@/u/amgad/heketi.txt> https://paste.centos.org/api/create
> Warning: Couldn't read data from file "text@/u/amgad/heketi.txt", this makes
> Warning: an empty POST.
> Invalid API key
> 
> I did paste one with heketi.log – issue 1708 in title and pressed create – it did, but didn’t return any address or pointer!!!
> 
> I tried https://paste.centos.org/api/recent but got “Invalid API key”
> Do I need permission? 

I really don't know what the issue is, sorry. 


> Can I attach the file to the email?
> 

If you mean emailing me, it would not be my first choice. For one thing, it would mean no-one else could help you with your queries since I'd be the only one with a copy of your logs.

If you have to use email, you could try emailing the [heketi list](https://lists.gluster.org/mailman/listinfo/heketi-devel) at [heketi-devel@gluster.org](mailto:heketi-devel@gluster.org).

**Comment by amgads** [comment]
Sent “heketi.tgz file that include the heketi.log to heketi-devel@gluster.org<mailto:heketi-devel@gluster.org>

**Comment by amgads** [comment]
Sent “heketi.tgz file that include the heketi.log to heketi-devel@gluster.org

**Comment by amgads** [comment]
I got back the following email




-----Original Message-----
From: heketi-devel-bounces@gluster.org <heketi-devel-bounces@gluster.org>
Sent: Monday, April 13, 2020 10:36 AM
To: Saleh, Amgad (Nokia - US/Naperville) <amgad.saleh@nokia.com>
Subject: Your message to heketi-devel awaits moderator approval



Your mail to 'heketi-devel' with the subject



    heketi issue # 1708 -- heketi.log



Is being held until the list moderator can review it for approval.



The reason it is being held:



    Post by non-member to a members-only list



Either the message will get posted to the list, or you will receive notification of the moderator's decision.  If you would like to cancel this posting, please visit the following URL:



    https://lists.gluster.org/mailman/confirm/heketi-devel/3a8de98a1c4d18986dcc738db459378655f5d845

**Comment by amgads** [comment]
Hi John -- Have you had an opportunity to take a look at the logs?

**Comment by phlogistonjohn** [comment]
No, to the best of my knowledge the message never made it to the list. if it is stuck in moderation I will personally ping some people who may be moderators of that list. I am not.

**Comment by amgads** [comment]
would you kindly help!

**Comment by raghavendra-talur** [comment]
@amgads @phlogistonjohn and I both don't have rights to the email moderation queue for the mailing list and we haven't got the logs yet.

@amgads If you cannot use the browser to provide logs at paste.centos.org, please refer to https://blog.centos.org/2018/09/new-centos-pastebin-instance/ to do it from the command line.

Without the logs, we would not be able to help much.

**Comment by amgads** [comment]
Followed the link and did the paste, still getiing an error
# cpaste ./heketi.txt
Successfully pastebined to: Error: Missing paste text

**Comment by phlogistonjohn** [comment]
I got in contact with one of the list moderators who released the mail to the list.

Looking at the logs what first jumps out at me are sections like the following:
```
22:20:36 docker_entrypoint.sh: LOG:info [cmdexec] ERROR 2020/04/10 03:50:36 heketi/pkg/remoteexec/ssh/ssh.go:194:ssh.(*SshExec).ExecCommands: Timeout on command [/bin/bash -c 'sudo lvremove --autobackup=n -f vg_aba17068a4f57abbd92d74872613c85d/brick_3e3bf1ae14c7960cdcf7eb4afec1338a'] on emerald-cw01:22: Err[<nil>]: Stdout []: Stderr [  Failed to set up async io, using sync io.
22:20:36 docker_entrypoint.sh: LOG:info ]
22:20:36 docker_entrypoint.sh: LOG:info [heketi] ERROR 2020/04/10 03:50:36 heketi/apps/glusterfs/brick_create.go:95:glusterfs.brickHostMap.destroy.func1: error destroying brick 3e3bf1ae14c7960cdcf7eb4afec1338a: SSH command timeout
22:20:36 docker_entrypoint.sh: LOG:info [heketi] ERROR 2020/04/10 03:50:36 heketi/apps/glusterfs/brick_create.go:110:glusterfs.brickHostMap.destroy: SSH command timeout
22:20:36 docker_entrypoint.sh: LOG:info [heketi] WARNING 2020/04/10 03:50:36 Clean phase of operation 819369ae89f27cb695ba5ac190738d08 encountered error: SSH command timeout
22:20:36 docker_entrypoint.sh: LOG:info [heketi] WARNING 2020/04/10 03:50:36 Unable to clean operation 819369ae89f27cb695ba5ac190738d08: SSH command timeout
```

There are a number of these timeouts in the log and all of them appear to occur on host named "emerald-cw01". I suspect that something is not right with the lvm state on that host.

I would check to see if there are any running lvm commands that are not exiting. You can do this by running normal lvm  commands (`lvs` for example) and seeing if it can acquire a lock. Also, look at your ps output for other lvm commands that are long lived.

As a quick fix you might also consider rebooting that particular node if you have >=3 nodes and the other 2 are healthy gluster-wise.

**Comment by amgads** [comment]
Thanks al lot John -- will take a look at the application server! Hope They didn't reboot at least to see what would cause lvm command problems

**Comment by amgads** [comment]
The application has rebooted the node and things were cleared -- so couldn't see lvm commads issues -- will do that when it re-occurs. For now you can close the ticket. Thanks for your support!

**Comment by phlogistonjohn** [comment]
Thanks. Good to hear.
