### ISSUE TITLE
Travis CI s390 builds are rather flaky

### ISSUE THREAD

**Issue by phlogistonjohn** [heketi/heketi#1711]
Travis CI jobs were added for the s390 architecture in PR #1689 and things were all good for a while. However in the past week or so the jobs, specifically the Go 1.13 job on s390 started failing almost every run.

For now I've commented out the Go 1.13 job on s390. Because the current maintenance team is not familiar  with s390 and its apparently not a "set it and forget it" thing but need more care and maintenance. I'm inclined to disable s390 in our travis ci.

@sangitanalkar since you added the jobs I'm @-ing you so you are aware. If you care to keep s390 enabled here in heketi could you please investigate what is going on with these jobs. "go get" is crashing before heketi is even built.

If you don't have the time to work on this I will just disable the jobs. I think I will make my decision in roughly a week.

Thanks.

**Comment by sangitanalkar** [comment]
Hi @phlogistonjohn , sure I will investigate and let you know.

**Comment by sangitanalkar** [comment]
Hi @phlogistonjohn, as mentioned in contributing document for heketi ([link](https://github.com/heketi/heketi/blob/master/docs/contributing.md)) , updated travis.yml file to use latest go v1.14 for s390x and raised PR "https://github.com/heketi/heketi/pull/1715"

**Comment by phlogistonjohn** [comment]
Thank you for the assistance. I think this is all set now. Closing issue.
