### ISSUE TITLE
how  do delete  the brick 

### ISSUE THREAD

**Issue by yhz1985** [heketi/heketi#1716]
I deploy the gluster+heketi in k8s
recently,i find the brick that don't bind any volume when I use the "heketi-cli topology info" 
and these bricks cannot be found too while I use "gluster volume info " in gluster'pod 

so, What do I need to do to delete these bricks

![image](https://user-images.githubusercontent.com/19431363/80368035-ab75a880-88be-11ea-90a8-e6ec09c2bf6e.png)

**Comment by phlogistonjohn** [comment]
Stale issue. If you can still reproduce the problem on Heketi v10.0.0 or later, feel free to reopen this issue.
