### ISSUE TITLE
how to change volume type?

### ISSUE THREAD

**Issue by shiune123** [heketi/heketi#1717]
### Kind of issue
Feature request

 ### Observed behavior
I deployed heketi and glusterfs in k8s.
When I wanted to modify the volume type of glusterfs, I didn't find how to modify the API of the volume type.

 ### Expected/desired behavior
Is there a function to modify the volume type, if not, can it be provided？

**Comment by phlogistonjohn** [comment]
> Is there a function to modify the volume type, if not, can it be provided？

Could you perhaps elaborate more on what you mean by volume type? Like like replicate vs. disperse?

It's probably not something we'd pursue but we'd consider contributions in that area.

**Comment by shiune123** [comment]
Yes, the volume type I am talking about is what you call distributed, replicated. The function I want to talk about is the change of this volume type. For example, if I have a volume that is a distributed type, I want to turn it into a replicated. I need a heketi command to change this volume type.

**Comment by shiune123** [comment]
Can this function be implemented in v10?

**Comment by phlogistonjohn** [comment]
v10 is now out but we certainly will continue to consider new contributions. However the current maintenance team does not expect to implement. If you don't plan to implement it yourself (or directly or indirectly) may I request that we close this issue? If it sits undone for another month or so I'll probably close it as well. Thanks!

**Comment by phlogistonjohn** [comment]
As heketi is now in maintenance mode, and only accepting major bug and security related fixes, we do not expect to implement this change.
