### ISSUE TITLE
What's the safest commit on master branch to build for deployment?

### ISSUE THREAD

**Issue by amgads** [heketi/heketi#1719]
Currently we have deployments using v9.0.0. As I understand difficulty to commit for v10 release time-frame.  What's the safest "commit" to use if we have to build it privately for a deployment? unless release v10 is coming in the next 2-weeks

your urgent answer is highly appreciated?

**Comment by phlogistonjohn** [comment]
Do you need a particular feature / improvement that is only in master right now?
Generally you could examine the patches that are on master only (git log v9.0.0..master) and then pick one that a) not in the middle of a patch series b) >a month or so old.
One reason this project has troubles cutting releases is the very problem of knowing when a feature is both needed and done and solid, which is similar to the criteria I'd need to use to suggest a particular patch id.

**Comment by amgads** [comment]
Thanks John -- so for b) criteria, if I build today
either "Commits on Mar 24, 2020" or "Commits or Mar 24, 2020" should be safe assuming they cover the features I'm looking for. right?

**Comment by amgads** [comment]
A different question -- is there an compatibility issues between v9.0.0 and Gluster 7.5?

**Comment by phlogistonjohn** [comment]
I know of no issues running that combination.

**Comment by amgads** [comment]
Thanks John!

**Comment by phlogistonjohn** [comment]
Should not be an issue anymore now that v10.0.0 is released. HTH.
