### ISSUE TITLE
Need to update help in scripts tests/functional/run.sh

### ISSUE THREAD

**Issue by iamniting** [heketi/heketi#1721]
### Kind of issue
> enhancement

### Observed behavior
--help is incomplete for the tests/functional/run.sh
It is not showing "--tests-dir" option

### Expected/desired behavior
-- help should show "--tests-dir" option as well.

### Details on how to reproduce (minimal and precise)
sh tests/functional/run.sh --help

### Link to file
https://github.com/heketi/heketi/blob/master/tests/functional/run.sh#L5

**Comment by phlogistonjohn** [comment]
Good point. Could you please file a PR for this? Thanks!

**Comment by iamniting** [comment]
Yes, I will raise PR for this. Are there any guidelines for commit messages?

**Comment by phlogistonjohn** [comment]
Indeed there are! Generally, we do a style like:
```
<topic>: <short-descriptoin>

<details>

<signed-off-by>
```

Where topic is a functional area such as "apps" or "api", or in this case "functional tests" (abbreviations are OK, so "func tests" would also be fine).

**Comment by iamniting** [comment]
PR is in place. look like travis CI is running on it.

**Comment by iamniting** [comment]
Closing the issue as PR is merged.
