### ISSUE TITLE
heketi-server, no tty present and no ask program specified when doing status check on glusterfs

### ISSUE THREAD

**Issue by 5331k** [heketi/heketi#1729]
### Kind of issue

> Bug

### Observed behavior
I have executed heket server as a systemd service but it is unable to execute properly and through following error message whenever it tries to check glusterd status:
![image](https://user-images.githubusercontent.com/4569634/81911182-3ea42300-95cd-11ea-868b-ac1b9f8083ec.png)

### Expected/desired behavior
heketi server should be able to execute properly and able to check status of gluster without any issue.

### Details on how to reproduce (minimal and precise)
problem is not common, however i set up heketi using following steps:
https://wiki.myhypervisor.ca/books/linux/page/glusterfs-heketi-ubuntu-1804

### Information about the environment:

- Heketi v9.0.0
- cent OS 7 
-  direct install: 

### Other useful information

ssh i configured properly between gluster nodes, as i can easily switch from one gluster node to another via ssh

**Comment by phlogistonjohn** [comment]
You need to configure heketi such that sudo will run without asking for a password. Typically you do this by creating a a specific user for heketi to ssh with and then make that user not require a password in sudo. You may also want to whitelist the commands that heketi runs but unfortunately we don't have a comprehensive list for that and you basically need to read the source.

**Comment by phlogistonjohn** [comment]
Stale issue. If you can still reproduce the problem on Heketi v10.0.0 or later, feel free to reopen this issue.
