### ISSUE TITLE
Has the K8S support for TLS changed?

### ISSUE THREAD

**Issue by amgads** [heketi/heketi#1737]
I'm referring to issue # 1467 "Help needed to configure tls certs in heketi"

It says "However it seems K8s glusterfs plugin does not call NewClientTLS() but NewClient(). You could submit PR to K8S to enhance glusterfs plugin to support TLS option"

I wonder if this has changed. and if not, how to support TLS using heketi?

**Comment by amgads** [comment]
I used v9.0.0 -- and was able to create the storageclass -- curl -g https://<heketi-server>:8080/hello works file.
When creating the PVC, it showed pending.
I described the PVC and got the following message:
----
[root@control-01]# kubectl describe pvc stobench-data-stobench-0
Name:          stobench-data-stobench-0
Namespace:     default
StorageClass:  glusterfs-storageclass-arbiter
Status:        Pending
Volume:        
Labels:        app=stobench
Annotations:   volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/glusterfs
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Mounted By:    stobench-0
Events:
  Type     Reason              Age                    From                         Message
  ----     ------              ----                   ----                         -------
  Warning  ProvisioningFailed  100s (x10 over 7m37s)  persistentvolume-controller  Failed to provision volume with StorageClass "glusterfs-storageclass-arbiter": failed to create volume: failed to create volume: Post https://10.254.0.101:8080/volumes: x509: certificate signed by unknown authority
[root@csto-bcmt-2003-control-01 amgad]# 

I used cert-manager to create/sign the cert.
Any suggestion? is the message still related to k8s? 
I'm running on v1.17.4

**Comment by phlogistonjohn** [comment]
To the best of my knowledge nothing has changed in this area for quite some time.
You can try to get TLS working in both heketi and k8s, but it may require tinkering with the cert stores that the k8s code uses, this would most likely be the TLS cert configuration on all the nodes that can issue HTTPS requests to heketi.

**Comment by amgads** [comment]
Thanks John -- any pointer to what modify?

**Comment by phlogistonjohn** [comment]
Not really no. I don't even know what cert store it uses, you might want to search around for that first. Alternatively, you may be able to try with a cert signed by a well-known CA.

**Comment by amgads** [comment]
The cert I tried is created and signed using cert-manager tightly coupled with k8s. Any suggestion for well known CA from k8s standpoint?

**Comment by phlogistonjohn** [comment]
Hopefully you were able to resolve the issue but it seems out of hekti's control, and this issue is stale. Therefore I'm closing it.

**Comment by amgads** [comment]
The issue was not resolved and k8s have not done any changes -- yet. So looks like can't use Heketi with TLS
