### ISSUE TITLE
My heketi not available

### ISSUE THREAD

**Issue by zhouweiw** [heketi/heketi#1742]
### Kind of issue
 my heketi working mode with replication:2 "sdb", I find one node what "sdb" and "sdc" exchanged  when I extend storage ”sdc“;
now this node "sdc" added。  how can I do?

heketi-cli -v 
 v7.0.0

> Uncomment only one of these:
> 
> Bug
> Feature request

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): 
- Operating system used: 
- Heketi compiled from sources, as a package (rpm/deb), or container: 
- If container, which container image: 
- Using kubernetes, openshift, or direct install: 
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: 
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom):

**Comment by iamniting** [comment]
Can you please elaborate issue. 

PS. I will recommend you to upgrade your heketi as most of the issues were fixed in newer releases.

**Comment by phlogistonjohn** [comment]
A tad stale wrt replying to @iamniting qusetion, plus you're using a very very old version of heketi. As v10 was just released I can only suggest that you upgrade to the newest version and then try again. If you can reproduce this issue on v10.0.0 or later feel free to reopen this issue.
