### ISSUE TITLE
Heketi-cli fails to find lvm

### ISSUE THREAD

**Issue by amehub** [heketi/heketi#1743]
### Kind of issue

> Uncomment only one of these:
> 
> Feature request

### Observed behavior
Running heketi in a docker container.
Loading the topology throws errors because lvm is not in /usr/sbin.

[cmdexec] ERROR 2020/07/06 09:18:08 heketi/pkg/remoteexec/log/commandlog.go:56:log.(*CommandLogger).Error: Failed to run command [/usr/sbin/lvm pvs -o pv_name,pv_uuid,vg_name --reportformat=json /dev/sdc] on [store-test-sto01:22]:
Err[Process exited with status 1]: Stdout []: Stderr [sudo: /usr/sbin/lvm: command not found

lvm is installed in /sbin.

### Expected/desired behavior
Expect heketi to find lvm in PATH on each gluster node and execute.

### Details on how to reproduce (minimal and precise)
Install gluster nodes
Install heketi as Docker container
Exec into heketi container and execute

heketi-cli topology load --user admin --secret <REDACTED> --json=/etc/heketi/topology.json

Review the heketi container log.

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): 

heketi-cli v9.0.0

- Operating system used: 

Ubuntu 18,.04

- Heketi compiled from sources, as a package (rpm/deb), or container: 
container
- If container, which container image: 
heketi:dev
- Using kubernetes, openshift, or direct install:
Docker direct 
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: 
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): 

### Other useful information
Is there way to over ride the path /usr/sbin?

**Comment by nixpanic** [comment]
In the container there would be a symlink `/sbin -> /usr/sbin`, so there the command should be able to found. However, if you enabled the lvm-wrapper option (enabled by default), it will try to execute `/usr/sbin/lvm` on the host. I do not know if Ubuntu has a symlink for like Fedora or CentOS distributions. In case it does not have the symlink, you could copy (or maybe symlink?) the executable from `/sbin/lvm` to `/usr/sbin` and things should work.

I am not aware of an option to change the path for the LVM executable within Heketi. The script that Heketi uses within the [Gluster containers is called `exec-on-host.sh`](https://github.com/gluster/gluster-containers/tree/master/CentOS).

You could disable the lvm-wrapper option, but in that case there might be incompatibilities between the version in the Gluster container and on the host, causing undefined behaviour (like hangs or missing bricks).

**Comment by amehub** [comment]
Hi 

Thanks for reply.

>  The script that Heketi uses within the Gluster containers is called exec-on-host.sh.
I have no gluster containers.  The gluster nodes are physical boxes.  It is only heketi that is running in a container.

Yes there is a symlink /sbin -> /usr/sbin in the heketi docker container.  However, on my gluster nodes (physical boxes) /sbin and /usr/sbin are separate directories.    So it looks like heketi is ssh'ing to the gluster nodes and executing /usr/sbin/lvm which does not exist on the gluster nodes :-(   I could mess around copying lvm commands to /usr//sbin but if heketi.   Not a very clean solution.

**Comment by nixpanic** [comment]
the `/usr/sbin/lvm` command is hardcoded in `executors/cmdexec/cmdexec.go:lvmCommand()`. If you want this configurable to that `/sbin/lvm` can be used on systems that do not have the modern `/sbin -> /usr/sbin` symlink, you could send a PR.

@iamniting what do you think?

**Comment by amehub** [comment]
Thanks.  Yes, I had noticed the path is hardcoded and I do think it would be useful not to hardcode it.  To workaround the hardcoding I have created the symlink 

/usr/sbin/lvm -> /sbin/lvm

on the gluster nodes and it looks like heketi is working now.   So long as heketi does not try expect to use any other LVM commands from /usr/sbin/lvm things should continue to work.    I would be happy to send a PR if I understood the code sufficiently.   Golang is very new to me so for now I am unable to contribute.   Once again thanks for getting back to me.

**Comment by iamniting** [comment]
> the `/usr/sbin/lvm` command is hardcoded in `executors/cmdexec/cmdexec.go:lvmCommand()`. If you want this configurable to that `/sbin/lvm` can be used on systems that do not have the modern `/sbin -> /usr/sbin` symlink, you could send a PR.
> 
> @iamniting what do you think?

I think creating a symlink is a perfect workaround for the issue. There should not be any hidden side effects as well. Moreover, the setup is an independent mode setup So there is no extra work that needs to be done except creating symlink.

**Comment by nixpanic** [comment]
Heketi only executes `/usr/sbin/lvm` which is the main `lvm` executable. All other LVM commands are passed like `/usr/sbin/lvm pvcreate ...`. I agree that the workaround with the symlink should be sufficient.
