### ISSUE TITLE
Heketi Creates a volume but the Pvc fails to bind in Kubernetes

### ISSUE THREAD

**Issue by armindocachada** [heketi/heketi#1746]
### Kind of issue

> Bug

### Observed behavior
I have provisioned a GlusterFS cluster on Kubernetes and I am using Heketi to create the Heketi volumes. 
For some reason when I create a PVC in kubernetes the PVC stays in Pending and it fails.

When I look at the Heketi logs I can see that the volume itself was created.
And worse of all, it keeps creating volumes until it runs out of space.

Steps to reproduce:

**Step 1: Create PVC with following content:**

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: gluster-pvc
 annotations:
   volume.beta.kubernetes.io/storage-class: gluster-heketi
spec:
 accessModes:
  - ReadWriteMany
 resources:
   requests:
     storage: 1Gi

**Step 2:** 

kubectl apply -f pvc.yaml 
persistentvolumeclaim/gluster-pvc created

**Step 3: Check status of PVC**

#kubectl get pvc

NAME          STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS     AGE
gluster-pvc   Pending                                      gluster-heketi   10s

#kubectl describe pvc gluster-pvc

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: gluster-pvc
 annotations:
   volume.beta.kubernetes.io/storage-class: gluster-heketi
spec:
 accessModes:
  - ReadWriteMany
 resources:
   requests:
     storage: 1Gi
[root@avengers ~]# kubectl describe pvc gluster-pvc
Name:          gluster-pvc
Namespace:     default
StorageClass:  gluster-heketi
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-class: gluster-heketi
               volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/glusterfs
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Mounted By:    <none>
Events:
  Type     Reason              Age                From                         Message
  ----     ------              ----               ----                         -------
  Warning  ProvisioningFailed  0s (x8 over 3m3s)  persistentvolume-controller  Failed to provision volume with StorageClass "gluster-heketi": failed to create volume: failed to create volume: see kube-controller-manager.log for details

**Step 4: Check volume list in Heketi**

kubectl exec -it heketi-7dfd85655b-mpd78 -- heketi-cli --user admin --secret admin  volume list

Id:0442dc34436427c60e6ef1e2a3ad9c62    Cluster:81bbe73e37a9a06c77f1fe51335210c2    Name:vol_0442dc34436427c60e6ef1e2a3ad9c62
Id:0509d233f6fc3221ed2301e8e1ee21a2    Cluster:81bbe73e37a9a06c77f1fe51335210c2    
....
Name:vol_d773ea0c6a0248a17059c1a02f6292ff
Id:ea46df4e8fabeaab0522c32f9e3e67b9    Cluster:81bbe73e37a9a06c77f1fe51335210c2    Name:vol_ea46df4e8fabeaab0522c32f9e3e67b9
Id:ec69bbc9c475db5b78d5d91af7bd5b54    Cluster:81bbe73e37a9a06c77f1fe51335210c2    Name:vol_ec69bbc9c475db5b78d5d91af7bd5b54
Id:ece0e312d3e0f9e1065af3d41c1f5ac3    Cluster:81bbe73e37a9a06c77f1fe51335210c2    Name:heketidbstorage
Id:f1b90afdaff6723ce999eca5827cfea3    Cluster:81bbe73e37a9a06c77f1fe51335210c2    Name:vol_f1b90afdaff6723ce999eca5827cfea3

### Expected/desired behavior

The volume should be created and the PVC should show as Bound

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): 

heketi-cli v9.0.0-1-g57a5f356-release-9

Which as the same result

**- Operating system used:** 

Centos 7

- Heketi compiled from sources, as a package (rpm/deb), or container: 
Used docker
- If container, which container image: 
Docker image heketi/heketi:9
I also tried previously running the docker image heketi:dev

- Using kubernetes, openshift, or direct install: 
Kubernetes
- If kubernetes/direct, is gluster running inside kubernetes/openshift or outside: 

Cluster  is running inside kubernetes

- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom):

**Comment by phlogistonjohn** [comment]
It sounds like the error might be on the provisioning side, basically after k8s calls heketi but after heketi has created the volume. I would carefully inspect the k8s logs (kubelet, kube-controller-manager.log, etc) and check the state of the pvc (kubectl describe, etc) to see if you can determine why the volume is getting created by heketi but rejected by k8s.

**Comment by armindocachada** [comment]
Hi John,
I have searched the logs for a few days now. And all I can see is a repeat of the message given by kubectl describe pvc...
How does Heketi tell Kubernetes that the volume was created? Is it Async?

Note aside, I tried to create a PV directly and that seemed to have worked. I.e. without the PVC.

**Comment by phlogistonjohn** [comment]
> Hi John,
> I have searched the logs for a few days now. And all I can see is a repeat of the message given by kubectl describe pvc...

That's unfortunate. I would have hoped the provisioner would log any errors.

> How does Heketi tell Kubernetes that the volume was created? Is it Async?
> 

kubernetes acts as a heketi client and embeds the heketi libraries for this purpose. The API is async but the client libraries internally poll the server so that is seems synchronous to the caller. The response to the volume create api ought to have enough information for the provisioner to act upon it, but the k8s code can and may make additional calls to the heketi api. Heketi server has no control over this part, that's all on the k8s side. The server can only respond with the information it has.


> Note aside, I tried to create a PV directly and that seemed to have worked. I.e. without the PVC.

Interesting. More hinting that the provisioner may be having an issue.
I remember an issue long ago somewhat similar to this that was triggered by the length of the volume name. Are you using the default naming scheme or something customized?

**Comment by armindocachada** [comment]
I am using the default namespace and running gluster on kubernetes directly.

**Comment by phlogistonjohn** [comment]
This is really tough to say w/o logs. I can only suggest you look to see if you can increase the logging level in k8s and look again. I know heketi well, but not the provisioning side in k8s.
We have also just released heketi v10.0.0. You may want to try an upgrade and see if that makes any difference.

**Comment by armindocachada** [comment]
Hi John,
Thanks for following up.
I have tried quite a few times to deploy Heketi on Kubernetes, and every time I faced the issue where the pvc was pending forever. I almost lost my hair over it. I couldn't figure out from the logs what the issue was, so I have given up.
I ended up setting OpenEBS. Do you want to close this ticket?

**Comment by phlogistonjohn** [comment]
That's unfortunate, but I understand your frustration. If you no no longer plan on attempting this I will close the issue. If you try again and are able to get more logs please feel free to reopen this issue.
