### ISSUE TITLE
How to build from source?

### ISSUE THREAD

**Issue by huangyingw** [heketi/heketi#1753]
I use following command to install the deps, and tried to build with make
````
wget -nc https://glide.sh/get | sh
apt-get install -y mercurial
glide install
make
````

but I got following error:
````
[0;32m[INFO]	[mRemoving nested vendor and Godeps/_workspace directories...
go build  -ldflags "-X main.HEKETI_VERSION=v10.0.0-7-g30a2d99f-dev -extldflags '-z relro -z now'" -o heketi
main.go:29:2: cannot find package "github.com/heketi/heketi/apps/glusterfs" in any of:
	/usr/local/go/src/github.com/heketi/heketi/apps/glusterfs (from $GOROOT)
	/root/go/src/github.com/heketi/heketi/apps/glusterfs (from $GOPATH)
main.go:30:2: cannot find package "github.com/heketi/heketi/middleware" in any of:
	/usr/local/go/src/github.com/heketi/heketi/middleware (from $GOROOT)
	/root/go/src/github.com/heketi/heketi/middleware (from $GOPATH)
main.go:31:2: cannot find package "github.com/heketi/heketi/pkg/metrics" in any of:
	/usr/local/go/src/github.com/heketi/heketi/pkg/metrics (from $GOROOT)
	/root/go/src/github.com/heketi/heketi/pkg/metrics (from $GOPATH)
main.go:32:2: cannot find package "github.com/heketi/heketi/server/admin" in any of:
	/usr/local/go/src/github.com/heketi/heketi/server/admin (from $GOROOT)
	/root/go/src/github.com/heketi/heketi/server/admin (from $GOPATH)
main.go:33:2: cannot find package "github.com/heketi/heketi/server/config" in any of:
	/usr/local/go/src/github.com/heketi/heketi/server/config (from $GOROOT)
	/root/go/src/github.com/heketi/heketi/server/config (from $GOPATH)
main.go:34:2: cannot find package "github.com/heketi/heketi/server/profiling" in any of:
	/usr/local/go/src/github.com/heketi/heketi/server/profiling (from $GOROOT)
	/root/go/src/github.com/heketi/heketi/server/profiling (from $GOPATH)
main.go:25:2: cannot find package "github.com/spf13/cobra" in any of:
	/usr/local/go/src/github.com/spf13/cobra (from $GOROOT)
	/root/go/src/github.com/spf13/cobra (from $GOPATH)
main.go:26:2: cannot find package "github.com/urfave/negroni" in any of:
	/usr/local/go/src/github.com/urfave/negroni (from $GOROOT)
	/root/go/src/github.com/urfave/negroni (from $GOPATH)
main.go:27:2: cannot find package "k8s.io/client-go/rest" in any of:
	/usr/local/go/src/k8s.io/client-go/rest (from $GOROOT)
	/root/go/src/k8s.io/client-go/rest (from $GOPATH)
make: *** [Makefile:67: heketi] Error 1
````
did I miss anything?

**Comment by iamniting** [comment]
As per my knowledge, you are getting these errors because your heketi repo is not cloned at the correct place. It should be cloned under $GOPATH/src/github.com/heketi/
Give a try and let us know.

**Comment by huangyingw** [comment]
ohh, yes, thank u for ur guidance.

**Comment by huangyingw** [comment]
I use following command to build and install heketi.
````
wget -nc https://glide.sh/get | sh
apt-get install -y mercurial
glide install
make
cp -fv ./heketi /usr/local/bin 
cp -fv ./client/cli/go/heketi-cli /usr/local/bin 
heketi --version
heketi-cli --version
````

when I run `heketi-cli topology load --json=/etc/heketi/topology.json`
I got following error `Error: Unable to get topology information: Invalid JWT token: Token missing iss claim`

so, I made following change, try to debug the `Token missing iss claim` issue
````
diff --git a/middleware/jwt.go b/middleware/jwt.go
index 7cef039b..4a3e5f9e 100644
--- ./middleware/jwt.go
+++ ./middleware/jwt.go
@@ -147,6 +147,7 @@ func (j *JwtAuth) ServeHTTP(w http.ResponseWriter, r *http.Request, next http.Ha
 		}
 
 		claims = token.Claims.(*HeketiJwtClaims)
+        logger.Info("fdfdfdfdfdsfweiijdfsdfdfclaims --> %v", claims)
 
 		// Get claims
 		if "" != claims.Issuer {
@@ -160,7 +161,7 @@ func (j *JwtAuth) ServeHTTP(w http.ResponseWriter, r *http.Request, next http.Ha
 			}
 		}
 
-		return nil, errors.New("Token missing iss claim")
+		return nil, errors.New("jffeedfsdfrwd rijfdsfwedsfweffssk")
 	})
 	if err != nil {
 		errmsg := fmt.Sprintf("Invalid JWT token: %s", err)

````

but after I build and install with above command, and re-run `heketi-cli topology load --json=/etc/heketi/topology.json`
I still got the same error `Error: Unable to get topology information: Invalid JWT token: Token missing iss claim`.


that means, my change in `middleware/jwt.go` was not compiled correctly. Most probably, sth wrong in my build install command.

could anyone help me with this?

**Comment by iamniting** [comment]
You don't need to change the code to make it work. I think you need to edit your heketi config file, the one you pass to the heketi server.
https://github.com/heketi/heketi/blob/master/etc/heketi.json#L18.

**Comment by huangyingw** [comment]
> You don't need to change the code to make it work. I think you need to edit your heketi config file, the one you pass to the heketi server.
> https://github.com/heketi/heketi/blob/master/etc/heketi.json#L18.

thanks for pointing this out. 
Still, I would like to debug and fix it myself, so, knowing how to build and install from source would be very helpful

**Comment by phlogistonjohn** [comment]
> > You don't need to change the code to make it work. I think you need to edit your heketi config file, the one you pass to the heketi server.
> > https://github.com/heketi/heketi/blob/master/etc/heketi.json#L18.
> 
> thanks for pointing this out.
> Still, I would like to debug and fix it myself, so, knowing how to build and install from source would be very helpful

Understood, that's nice to hear.
There are a couple of things to be aware of when building and testing, the first depends on how you plan to run the server binary. If you run heketi within a container you need to build the entire container and then run that using docker/podman/kubernetes/etc. If you plan on just running the server binary you need to decide if you are running as a system service, like a systemd service or just running the binary from a script, like our functional test framework does.

The last case is the easiest, as long as you point your script or command line at the heketi binary that was built it should run the compiled version of whatever you have. However, if you are running a service you need to be aware of the paths that the service file uses. For example, the sample systemd unit file in our tree has `ExecStart=/usr/bin/heketi --config=/etc/heketi/heketi.json` as a line in the file. This means that it only runs the heketi binary found at /usr/bin/heketi, and only uses the heketi config file located at /etc/heketi/heketi.json. You can choose to either modify the service file to point at other locations, or you can copy the binaries you built to /usr/bin/.  I lean toward the former as it allows you to more rapidly iterate w/o needing to sudo every time you want to compile and test.

However, if you're looking simply to mess around with heketi, just launching it from a script from w/in your source tree is easiest, that's how I often test it.

Also be aware that heketi builds two binaries `heketi` and `heketi-cli`. As I discussed about that's all about the server binary, "heketi". The heketi-cli just provides the command line interface for interacting with the server in a convenient manner. Most of the logic of heketi resides in the server.

**Comment by huangyingw** [comment]
> > > You don't need to change the code to make it work. I think you need to edit your heketi config file, the one you pass to the heketi server.
> > > https://github.com/heketi/heketi/blob/master/etc/heketi.json#L18.
> > 
> > 
> > thanks for pointing this out.
> > Still, I would like to debug and fix it myself, so, knowing how to build and install from source would be very helpful
> 
> Understood, that's nice to hear.
> There are a couple of things to be aware of when building and testing, the first depends on how you plan to run the server binary. If you run heketi within a container you need to build the entire container and then run that using docker/podman/kubernetes/etc. If you plan on just running the server binary you need to decide if you are running as a system service, like a systemd service or just running the binary from a script, like our functional test framework does.
> 
> The last case is the easiest, as long as you point your script or command line at the heketi binary that was built it should run the compiled version of whatever you have. However, if you are running a service you need to be aware of the paths that the service file uses. For example, the sample systemd unit file in our tree has `ExecStart=/usr/bin/heketi --config=/etc/heketi/heketi.json` as a line in the file. This means that it only runs the heketi binary found at /usr/bin/heketi, and only uses the heketi config file located at /etc/heketi/heketi.json. You can choose to either modify the service file to point at other locations, or you can copy the binaries you built to /usr/bin/. I lean toward the former as it allows you to more rapidly iterate w/o needing to sudo every time you want to compile and test.
> 
> However, if you're looking simply to mess around with heketi, just launching it from a script from w/in your source tree is easiest, that's how I often test it.
> 
> Also be aware that heketi builds two binaries `heketi` and `heketi-cli`. As I discussed about that's all about the server binary, "heketi". The heketi-cli just provides the command line interface for interacting with the server in a convenient manner. Most of the logic of heketi resides in the server.

thanks for your explanation. 
Finally, I found why I could not see my change.
I did copy to the right file, but I need to restart it with 
`systemctl restart heketi`
