### ISSUE TITLE
Heketi 10 - Expand Volume Question

### ISSUE THREAD

**Issue by amehub** [heketi/heketi#1754]
### Kind of issue

> Feature request

Does heketi 10 include support for expanding a gluster volume such that the underlying logical volume is  expanded?  At the moment if I expand a volume under the covers heketi/gluster adds a brick and I am restricted to max file size of the maximum brick size in my volume.   I prefer to expand a volume and be able to expand a file to the total size of my volume.

### Observed behavior
Max file size is restricted to volume max brick size.

### Expected/desired behavior
Desired - expand volume, expand file to max size of volume.

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): 9
- Operating system used:  Ubuntu
- Heketi compiled from sources, as a package (rpm/deb), or container: 
- If container, which container image: 
- Using kubernetes, openshift, or direct install: 
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: 
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom):

**Comment by phlogistonjohn** [comment]
No, heketi does not expand LVM LVs it only creates new LVs + file systems and adds them as distribute brick sets to gluster.
If you really need this feature someone, either yourself or someone outside the current maintenance team would need to contribute support for this. The current team would be happy to assist with the design and code review but we would not be able to do this for you.

**Comment by phlogistonjohn** [comment]
As heketi is now in maintenance mode, and only accepting major bug and security related fixes, we do not expect to implement this change.
