### ISSUE TITLE
cate

### ISSUE THREAD

**Issue by Lelik13a** [heketi/heketi#1755]
### Kind of issue

> Uncomment only one of these:
> 
> Bug
> Feature request

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): 
- Operating system used: 
- Heketi compiled from sources, as a package (rpm/deb), or container: 
- If container, which container image: 
- Using kubernetes, openshift, or direct install: 
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: 
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom):

**Comment by phlogistonjohn** [comment]
Hi there, perhaps you didn't mean to submit this issue in this form but there's pretty much no information here for use to do anything with. Thus I'm closing this issue. If you have an issue you wish to file feel free to update & reopen this with a readable title and a well formed description of the problem(s) you're having. Thanks.
