### ISSUE TITLE
Error Removing Dead Node 

### ISSUE THREAD

**Issue by iwalmsley** [heketi/heketi#1756]
### Kind of issue
Unsure - perhaps a Bug? (This is a continuation of #1744)

### Observed behavior

We're seeing a scenario where within a 3 node glusterfs cluster one node has become corrupt/unreachable. At which point we have provisioned a new node (to temporarily make a 4 node gluster cluster) and are trying to remove the corrupt node in order to migrate the bricks to the new node to acheive a 3-replica cluster again (currently all volumes have only 2 bricks). This is failing with the following error indicating that it's trying to SSH to the dead node (IP Address = 192.168.3.25) in order to remove the bricks that are being deleted, the issue is that this would never work as the node is down and won't be back up, so we need it to skip this step and simply create the brick on the new 4th node instead.

heketi-cli node remove 0ac9ed991748d6eeb8659db6b40e7094

```
[cmdexec] WARNING 2020/07/27 09:57:12 Failed to create SSH connection to 192.168.3.25:22: dial tcp 192.168.3.25:22: connect: no route to host
[heketi] ERROR 2020/07/27 09:57:12 heketi/apps/glusterfs/operations_device.go:661:glusterfs.(*BrickEvictOperation).Clean: Unable to get volume info from gluster node 192.168.3.25 for volume vol_0371ee52c589f64b27fa942a289d17b8: Unable to get volume info of volume name: vol_0371ee52c589f64b27fa942a289d17b8
[heketi] ERROR 2020/07/27 09:57:12 heketi/apps/glusterfs/operations_manage.go:270:glusterfs.rollbackViaClean: error running Clean in rollback for Remove Brick from Device: Unable to get volume info of volume name: vol_0371ee52c589f64b27fa942a289d17b8
[heketi] ERROR 2020/07/27 09:57:12 heketi/apps/glusterfs/operations_manage.go:175:glusterfs.runOperationAfterBuild: Remove Brick from Device Rollback error: Unable to get volume info of volume name: vol_0371ee52c589f64b27fa942a289d17b8
[heketi] ERROR 2020/07/27 09:57:12 heketi/apps/glusterfs/operations_manage.go:251:glusterfs.RunOperation.func1: Error in Remove Brick from Device: Error destroying old brick: dial tcp 192.168.3.25:22: connect: no route to host
[heketi] ERROR 2020/07/27 09:57:12 heketi/apps/glusterfs/operations_manage.go:167:glusterfs.runOperationAfterBuild: Remove Device Failed: Error destroying old brick: dial tcp 192.168.3.25:22: connect: no route to host
[heketi] INFO 2020/07/27 09:57:12 need to clean child [1cafcc6644680acd8c4f37ce6e719283] of Remove Device [9ad79dd9f9cd802ef2fffc62ce93a78b]
[heketi] INFO 2020/07/27 09:57:12 Starting Clean for Evict Brick op:1cafcc6644680acd8c4f37ce6e719283
[heketi] INFO 2020/07/27 09:57:12 found brick to be replaced: 1836f4f73ffd968b68e00fe04129b470
[heketi] INFO 2020/07/27 09:57:12 this is a child op of: 9ad79dd9f9cd802ef2fffc62ce93a78b
[heketi] INFO 2020/07/27 09:57:12 found replacement brick: 727e9b05d75eaac0c264380cdbd1f516
[negroni] 2020-07-27T09:57:12Z | 200 |   133.782µs | localhost:8080 | GET /queue/a9a244c0ca8c2bfe357409f6f754393f
[negroni] 2020-07-27T09:57:12Z | 200 |   172.284µs | localhost:8080 | GET /queue/a9a244c0ca8c2bfe357409f6f754393f
[negroni] 2020-07-27T09:57:13Z | 200 |   83.151µs | localhost:8080 | GET /queue/a9a244c0ca8c2bfe357409f6f754393f
[negroni] 2020-07-27T09:57:13Z | 200 |   146.811µs | localhost:8080 | GET /queue/a9a244c0ca8c2bfe357409f6f754393f
[negroni] 2020-07-27T09:57:13Z | 200 |   139.907µs | localhost:8080 | GET /queue/a9a244c0ca8c2bfe357409f6f754393f
[negroni] 2020-07-27T09:57:14Z | 200 |   126.986µs | localhost:8080 | GET /queue/a9a244c0ca8c2bfe357409f6f754393f
[negroni] 2020-07-27T09:57:14Z | 200 |   193.893µs | localhost:8080 | GET /queue/a9a244c0ca8c2bfe357409f6f754393f
[negroni] 2020-07-27T09:57:15Z | 200 |   146.202µs | localhost:8080 | GET /queue/a9a244c0ca8c2bfe357409f6f754393f
[cmdexec] WARNING 2020/07/27 09:57:15 Failed to create SSH connection to 192.168.3.25:22: dial tcp 192.168.3.25:22: connect: no route to host
[heketi] ERROR 2020/07/27 09:57:15 heketi/apps/glusterfs/operations_device.go:661:glusterfs.(*BrickEvictOperation).Clean: Unable to get volume info from gluster node 192.168.3.25 for volume vol_0371ee52c589f64b27fa942a289d17b8: Unable to get volume info of volume name: vol_0371ee52c589f64b27fa942a289d17b8
[heketi] ERROR 2020/07/27 09:57:15 heketi/apps/glusterfs/operations_manage.go:270:glusterfs.rollbackViaClean: error running Clean in rollback for Remove Device: Unable to get volume info of volume name: vol_0371ee52c589f64b27fa942a289d17b8
[heketi] ERROR 2020/07/27 09:57:15 heketi/apps/glusterfs/operations_manage.go:175:glusterfs.runOperationAfterBuild: Remove Device Rollback error: Unable to get volume info of $olume name: vol_0371ee52c589f64b27fa942a289d17b8
```

### Expected/desired behavior

It shouldn't bother deleting the bricks on a node that is being removed as it could be down. In our case as it's corrupt/inaccessible we can't migrate the bricks to the new node/remove the node.

### Details on how to reproduce (minimal and precise)

As with the previous issue (#1744), we have tried to replicate this issue in another heketi/gluster instance but it seemed to work fine - we shut down one node in the cluster and did a node delete to force migration of the bricks onto another node which worked without issue. I don't know if this behavior is something that has been introduced in recent releases or is expected.

### Information about the environment:

- Heketi version used  (e.g. v6.0.0 or master): v9.0.0-204-gd23f5303
- Operating system used: Gluster Cluster - Ubuntu 18.04, Heketi via Docker image
- Heketi compiled from sources, as a package (rpm/deb), or container: Container
- If container, which container image: heketi/heketi:dev 
- Using kubernetes, openshift, or direct install: Kubernetes
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: Outside
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): gk-deploy 

Again any help pointing in the right direction would be very helpful.

**Comment by phlogistonjohn** [comment]
This looks like it could be another case where we tried to make the code more reliable and report all error conditions but that causes problems for the missing-node case.

Old code:
```golang
spaceReclaimed, err := oldBrickEntry.Destroy(db, executor)
if err != nil {
    logger.LogError("Error destroying old brick: %v", err)
}
```

New code:
```golang
beo.reclaimed, err = old.bhmap().destroy(executor)
if err != nil {
    return logger.LogError("Error destroying old brick: %v", err)
}
```

Note that the old code does not return. It only logs the error and keeps going. I suspect that difference it why this is failing for you.  However, unlike the other issue I'm not as confident just copying the old approach is the right thing here, because in this case not checking for errors is only correct in the case where the node is truly dead and gone and heketi doesn't really know that's the case in all situations. We need to think about this some more.

**Comment by iwalmsley** [comment]
Thank you for the quick response, I understand the dilemma. It looks like it may require some kind of flag when specifically removing a dead node but understand that probably won't be a rapid change.
 
Do you know if there an older version (ideally Docker image) we can temporarily revert to to apply this operation? Or else the commit reference these changes were made under so we can look at compiling a version just to get past this error as it's an operational system we want to bring back to full capacity ASAP.

**Comment by iamniting** [comment]
Hi @iwalmsley,

Can you pls run the brick evict command for one of the brick and give us whole logs for that time frame. That will be very helpful to debug it.

I will also try to reproduce it on my setup side by side.

**Comment by phlogistonjohn** [comment]
> Thank you for the quick response, I understand the dilemma. It looks like it may require some kind of flag when specifically removing a dead node but understand that probably won't be a rapid change.
> 
> Do you know if there an older version (ideally Docker image) we can temporarily revert to to apply this operation? Or else the commit reference these changes were made under so we can look at compiling a version just to get past this error as it's an operational system we want to bring back to full capacity ASAP.

Unfortunately, it is not safe to run older versions of the heketi code with newer versions of the db. Every time heketi starts it will update the db structures as needed, but it's not designed to go in reverse and trying to do so could mess up the db contents.

If you truly need a quick hack, fetching from source (either "master" or "release/10" branch) and then editing out the "return" statement from the example code block above (file "apps/glusterfs/operations_device.go") and building an image from that might fix the issue for you.

**Comment by iwalmsley** [comment]
Thanks for the heads up about the older DB version. Just been having a look at the linked ticket that seems promising, do you still need logs from us for brick eviction etc? In which case to confirm we should try evicting a brick from the node that is down?

**Comment by iamniting** [comment]
> Thanks for the heads up about the older DB version. Just been having a look at the linked ticket that seems promising, do you still need logs from us for brick eviction etc? In which case to confirm we should try evicting a brick from the node that is down?

I think logs are not required now.

**Comment by phlogistonjohn** [comment]
FWIW PR #1757 should be fairly complete as we've performed more practical testing on our side. If you wish you can try building right from that branch, otherwise we ought to be able to review, finish testing, and merge within a few days.

**Comment by iamniting** [comment]
Hi @iwalmsley The PR is merged in master, you should be able to remove a dead node now after using binary build from master branch.

**Comment by iwalmsley** [comment]
That's brilliant thank you so much for the quick response. We'll test & deploy this later today.

**Comment by iwalmsley** [comment]
Just to note that this worked fine, though we had to make use of the flag here  #1747  extensively as the majority of the bricks (at least over half) were timing out so we had to remove all of these first using the flag before removing the node. Thanks very much for the help @phlogistonjohn @iamniting .

**Comment by iamniting** [comment]
> Just to note that this worked fine, though we had to make use of the flag here #1747 extensively as the majority of the bricks (at least over half) were timing out so we had to remove all of these first using the flag before removing the node. Thanks very much for the help @phlogistonjohn @iamniting .

It is good to hear that it worked @iwalmsley. You are welcome
