### ISSUE TITLE
Glusterfs node restarts /etc/fstab in relation to heketi Volume to detect a startup timeout

### ISSUE THREAD

**Issue by qiang93** [heketi/heketi#1760]
heketi version:  Heketi v9.0.0-137-g7340ee40
gluster version: glusterfs 7.5

![11](https://user-images.githubusercontent.com/26239197/89023863-d278c600-d356-11ea-84e4-bfc62776f1a4.png)

**Comment by iamniting** [comment]
According to the screenshot, the device did not come up during restart. IMO this is not a heketi related issue. You should find out why the device gets a timeout. 

PS. Can you provide us the details of the environment So we can point you in the right direction?

**Comment by phlogistonjohn** [comment]
Stale issue. Closing.
