### ISSUE TITLE
Ability to set cluster flags on v5.0.0

### ISSUE THREAD

**Issue by NicoForce** [heketi/heketi#1763]
### Observed behavior
Not able to set file and block flags on heketi-cli 5.0.0.
Api for flag set returns *404*, and theres so such cli option as *heketi-cli cluster set*.

### Expected/desired behavior
Able to change flags using either the api or cli in version 5.0.0

### Details on how to reproduce (minimal and precise)
The following command does not exist on version 5.0.0:

heketi-cli cluster set --file=true --block=true

The following API returns 404:

http://localhost:8080/clusters/{id}/flags

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master):  v5.0.0
- Operating system used: RHEL 7
- Heketi compiled from sources, as a package (rpm/deb), or container: container
- If container, which container image: rhgs3/rhgs-volmanager-rhel7:latest
- Using kubernetes, openshift, or direct install: openshift
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: outside
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): openshift-ansible

**Comment by iamniting** [comment]
You are using very old heketi. You should update it.

**Comment by phlogistonjohn** [comment]
> You are using very old heketi. You should update it to get that feature.

Agreed. You really need to upgrade. The current version is v10.0.

**Comment by NicoForce** [comment]
I know the version is old.

So you are telling me there's no way to do it with v5.0.0?

@phlogistonjohn @iamniting

**Comment by phlogistonjohn** [comment]
> I know the version is old.
> 
> So you are telling me there's no way to do it with v5.0.0?
> 

That's correct.

**Comment by NicoForce** [comment]
Is there any chance of changing just these 2 values with topology load?

![image](https://user-images.githubusercontent.com/32383958/90065612-2b7b1f00-dcb2-11ea-8fe5-8865270eccad.png)

**Comment by NicoForce** [comment]
Well, I spent some time looking through the code and saw that indeed, topology load does not change anything cluster related.

https://github.com/heketi/heketi/blob/e0ec337aa22a2ddbd89a5e2338280f621c371755/client/cli/go/cmds/topology.go#L93

I guess there's no other way than updating.

Do you know which process needs to be followed in order to update heketi-cli on openshift?

**Comment by iamniting** [comment]
You just need to update heketi container image in the `deployment config`. Which can be done via the below steps.

`# oc get dc`
`# oc edit dc <heketi-dc>`
and change the image version and save it. Before doing that make sure that heketi is not doing anything like PVC creation, deletion

**Comment by NicoForce** [comment]
Got it, then I'll close this issue and give it my best try to update the container image.

Thanks for your help.
