### ISSUE TITLE
Heketi Docker container seems to be missing lsof

### ISSUE THREAD

**Issue by kanadaj** [heketi/heketi#1765]
### Kind of issue

> Uncomment only one of these:
> 
Bug
> Feature request

### Observed behavior

Heketi tries to use `lsof` to scan whether a volume is in use, but `lsof` isn't actually installed in the container. Since an error is expected here, this doesn't seem to cause any severe issues, but this isn't the expected behaviour I assume

### Expected/desired behavior

I'm fairly sure the image should come with lsof but doesn't.

### Details on how to reproduce (minimal and precise)

Pull and configure heketi/heketi:latest for a simple Gluster cluster
Check the logs for `ERROR` entries such as:
```log
[kubeexec] ERROR 2020/08/15 20:46:16 heketi/pkg/remoteexec/log/commandlog.go:56:log.(*CommandLogger).Error: Failed to run command [lsof /var/lib/heketi/mounts/vg_5f5d00ce7da942b7b0fd1155cd42626d/brick_b791629fd8e6502bb6d3c11f0add8235] on [pod:glusterfs-storage-4pkpz c:glusterfs ns:app-storage (from host:kubemaster1 selector:glusterfs-node)]: Err[command terminated with exit code 127]: Stdout []: Stderr [bash: lsof: command not found
--
```

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): docker.io/heketi/heketi:latest (Heketi v10.0.0-2-g7a6610da-release-10)
- Operating system used: Docker container, I assume CentOS
- Heketi compiled from sources, as a package (rpm/deb), or container: container
- If container, which container image: latest as of today, sha256:7b9e9a11e47a8b45c79b2d7df6fc8e29d036bedf27da3edce7e2bda88e48812e
- Using kubernetes, openshift, or direct install: OKD, but not the vanilla OKD install - shouldn't matter for this issue
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: inside
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): custom

### Other useful information

Running `yum install lsof -y` works and fixes the problem, so it's a simple Dockerfile update - though it warrants an extra check to make sure fixing the error doesn't cause all the bugs to come out crawling :)

**Comment by phlogistonjohn** [comment]
Thanks for the report.

For heketi to make use of lsof it needs to be on the gluster storage nodes that heketi is managing. If these are standalone gluster nodes managed with rpms/debs/whatnot that is the administrators responsibility. 

For containerized gluster that's something that needs to be part of the container image. The heketi projects makes use of containerized gluster when so configured, and there's overlap between contributors to both projects but heketi doesn't control what is in those images. Heketi should give extra debugging information if `lsof` is available but nothing bad should happen if it is not there.

If you are using containerized gluster, could you please file a corresponding issue in the gluster/gluster-containers project? Feel free to link this issue there for awareness.

**Comment by kanadaj** [comment]
Ah so it's a different project. It's a bit confusing when things are in so many places. But yes, containerized gluster. Will do!

**Comment by phlogistonjohn** [comment]
Stale issue. Hope you were able to resolve it on your side. Closing.
