### ISSUE TITLE
How to migrate data using heketi?

### ISSUE THREAD

**Issue by shining-snail** [heketi/heketi#1766]
I have a cluster within three nodes  managed by heketi. Recently ,the old node servers will be out of service , it is necessary to replace them with new servers. The gluster commands supports replacing the old brick with new brick on new nodes, but I don't how to use heketi to  achieve this goal. If I use gluster commands to migrate the data, heketi database will lost the true state of cluster. How to use heketi to migrate data?

**Comment by iamniting** [comment]
1. You need to Add new nodes in heketi via heketi-cli and required space (device) on new nodes.
2. Then you can remove the older nodes, when you will remove the older nodes heketi will migrate bricks itself in the newer nodes.

```
$ ./client/cli/go/heketi-cli node --help
Heketi Node Management

Usage:
  heketi-cli node [command]

Available Commands:
  add         Add new node to be managed by Heketi
  delete      Deletes a node from Heketi management
  disable     Disallow usage of a node by placing it offline
  enable      Allows node to go online
  info        Retrieves information about the node
  list        List all nodes in cluster
  remove      Removes a node and all its associated devices from Heketi
  rmtags      Removes tags from a node
  settags     Sets tags on a node
```

**Comment by phlogistonjohn** [comment]
You're right, doing it with gluster would cause the systems to go out of sync. Heketi does have the ability to help here. 

Depending on what version of heketi you are using you will either want to use the `heketi-cli device remove` or `heketi-cli node remove` or `heketi-client brick evict` command. The latter is only available in the newest release and only removes a single brick from a volume.
The two other commands will try to remove all the bricks from a single device or all devices on a node respectively.

Be aware that you must add new storage, of a capacity greater than or equal two what is currently being used, before removing the devices/nodes. This would be true even if you used the gluster commands directly.

Typically the procedure might go something like this:
* Disable all old nodes so no new bricks will be created. Example: `for n in ${OLD_NODES}: do heketi-cli node disable $n; done`
* Add new node N+1 to heketi; add the node's new devices
* Remove first Old Node. Example: `heketi-cli node remove $ID`
* Add new node N+2 to heketi
* Remove 2nd old node
* Add new noode N+3 to heketi
* Remove 3rd old node

Once this is done you've now cycled out all 3 old nodes for new ones.

**Comment by shining-snail** [comment]
Thanks for all of you! It works quite well, but I also find some problem during removing action. When the target brick is being used, the action will fail and I can not remove the device any more. The heketi will show "ID not found" error. We found that umount failed with the filesystem of the error brick. When we manaully umount the filesystem, heketi can continue working and the pending action will be released. Does this self-healing fuction always work? If other facts prevent heketi from removing device, will heketi run in an unrecoverable state and I could never finish the removing work? 
Another problem is that one of the node's statistic info goes wrong .The capacity used shown in heketi is different from the true capacity used on the node server ,but I did not use any gluster command on the server. When I removed this node ,the info on new node shown in heketi is correct. I was really puzzled...

**Comment by phlogistonjohn** [comment]
> Thanks for all of you! It works quite well, but I also find some problem during removing action. When the target brick is being used, the action will fail and I can not remove the device any more.

I'm not sure what you mean by this. I don't know how you're determining a brick is in use. Logs or log snippets would probably help a lot here.

> The heketi will show "ID not found" error. We found that umount failed with the filesystem of the error brick. 

This sounds somewhat familiar. What versions of heketi and gluster are you using?

> When we manaully umount the filesystem, heketi can continue working and the pending action will be released. 

How are you manually unmounting? Normally, heketi can do anything you can do so I'd like to know better how you are working around the issue.

> Does this self-healing fuction always work? If other facts prevent heketi from removing device, will heketi run in an unrecoverable state and I could never finish the removing work?

I'm sorry, but I don't understand the questions here.


> Another problem is that one of the node's statistic info goes wrong .The capacity used shown in heketi is different from the true capacity used on the node server ,but I did not use any gluster command on the server. 

Older versions of heketi suffered from many bugs related to keeping the used/free size of devices correct. Its improved in recent versions but I can't guarantee it is perfect. It also doesn't automatically fix itself, so any issues on old nodes will simply persist.

> When I removed this node ,the info on new node shown in heketi is correct. I was really puzzled...

I'm not sure why, when you add a new node it will add new devices and any bricks that are added to the new node are done based on the initial values, which I would assume to be correct. It doesn't implicitly "take over" the old node's state.  If I'm misunderstanding you, please elaborate.

**Comment by phlogistonjohn** [comment]
Sounds like a good plan, IMO. If this issue sits idle for a while (usually its a month + whenever I review open issues) I might close it but never hesitate to open an issue you created if you reproduce the problem!

**Comment by phlogistonjohn** [comment]
Stale issue. Closing
