### ISSUE TITLE
How to increase volume replicate:2 to replicate:3

### ISSUE THREAD

**Issue by amehub** [heketi/heketi#1767]
### Kind of issue

Question

### Observed behavior

Two glusters nodes and want to add a third gluster node.  I have Kubernetes storage class that uses the glusterfs provisioner and volumetype "replicate:2"   Adding the third node is straightforward.  How do I get the existing volumes that are replicate:2 to replicate to the third gluster node?   I will delete and recreate the storage class and change replicate:2 to replicate:3 and new PVCs are created replicate:3 as expected but I would like all existing PVC persistent volumes to also replicate:3.   Any easy way to achieve this?

### Expected/desired behavior

Desired behaviour - a way to change the "properties" of existing replicate:2 volumes to replicate:3 so that they add bricks onto nodes to achieve replicate:3.

### Details on how to reproduce (minimal and precise)

N/A

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): 
- Operating system used:  Ubuntu 18.04
- Heketi compiled from sources, as a package (rpm/deb), or container:  Docker Container (outside of Kubernetes) 
- If container, which container image: 
- Using kubernetes, openshift, or direct install:    Gluster Direct Install Bare Metal
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: 
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom):

**Comment by iamniting** [comment]
You can not change the replica count of the existing volumes, Only the new ones will be a replica 3. If there are few volumes as a workaround you can add bricks via gluster CLI directly. But there will be a mismatch b/w gluster and heketi. You need to clean up as well once you delete the PVC.

I won't recommend you to delete the existing storage class. Instead, create a new one with replica 3.

**Comment by phlogistonjohn** [comment]
> You can not change the replica count of the existing volumes, Only the new ones will be a replica 3. 

>If there are few volumes as a workaround you can add bricks via gluster CLI directly. But there will be a mismatch b/w gluster and heketi. You need to clean up as well once you delete the PVC.
> 

I don't recommend doing this as heketi will no longer be able to delete or manage the volumes properly. In theory, you can edit the db to match, but that's a very complex and difficult procedure without a lot of expertise in the heketi db structure.

Far simpler would be to create new volumes and just migrate the date over. Then delete the old replica 2 volumes.

**Comment by amehub** [comment]
Thank you.  Both confirmed my suspicions.  I have a working solution to migrate pvc data to new replicate:3 volume so will likely go with that.

**Comment by phlogistonjohn** [comment]
Issue sounds resolved. Closing.
