### ISSUE TITLE
Question about topology.json

### ISSUE THREAD

**Issue by amehub** [heketi/heketi#1776]
Question 

### Observed behavior
Is the topology.json file and all fields documented anywhere?  Reason for question is I have heketi running in a docker container on a VM.   The gluster storage pool is on separate physical nodes.  I have two networks; management and storage.  The VM has access to the management network  but does not have access to the storage network.   My k8s storage classes can provision volumes on gluster via heketi and heketi "hands back" the correct storage end points to k8s.   So everything appears to work ok.

However, does heketi communicate on the storage address (see below example) or does it just use it to "hand back" to k8s?  I want to avoid any unexpected future impact if heketi cannot reach the storage address.  Maybe heketi does noyt need to reach the storage address.

{
    "clusters": [
               {
                  "nodes": [
                                {
                        "node": {
                            "hostnames": {
                                "manage": [
                                    "node1.example.com"     ## << in my case consider this one of my gluster nodes on management networkl
                                ],
                                "storage": [
                                    "192.168.121.168"         ## consider this a different address than node1 above. Does heketi need to communicate with this address?
                                 ]
                             },
                             "zone": 1
                         },
..
..
..

- Heketi version used (e.g. v6.0.0 or master):  v9
- Operating system used:  ubuntu 18.04
- Heketi compiled from sources, as a package (rpm/deb), or container:  docker container
- Using kubernetes, openshift, or direct install:   Direct  

Gluster runs outside of k8s.

**Comment by phlogistonjohn** [comment]
Unfortunately, your best bet is probably the source code. The maintenance team does not have resources to significantly  expend on documentation of this type, but doc contributions (as opposed to code changes) may still be considered in maintenance mode. Otherwise, you'll probably have to live with the state of things as they are.
