### ISSUE TITLE
Wrong topology info output.

### ISSUE THREAD

**Issue by khounish** [heketi/heketi#1778]
### Kind of issue

After cleaning up.  lvs, ,rsyncing device, orphaned bricks are  are still visible.
> Uncomment only one of these:
> 
> Bug
> Feature request

### Observed behavior
heketi-cli topology info shows, below 
Devices:
                Id:8015c217909d51109e2c8a2bb72b3bb8   Name:/dev/vdc            State:online    Size (GiB):99      Used (GiB):5       Free** (GiB):94
                        Bricks:
                                Id:3dd55589484114236a3274501c322442   **Size (GiB):31**      Path: /var/lib/heketi/mounts/vg_8015c217909d51109e2c8a2bb72b3bb8/brick_3dd55589484114236a3274501c322442/brick
                                Id:4583ffb9aaa7906d874a62f0cdb7e6d8   **Size (GiB):31**      Path: /var/lib/heketi/mounts/vg_8015c217909d51109e2c8a2bb72b3bb8/brick_4583ffb9aaa7906d874a62f0cdb7e6d8/brick
                                Id:6ad7881e1d979bd950d66055624354da   **Size (GiB):31**      Path: /var/lib/heketi/mounts/vg_8015c217909d51109e2c8a2bb72b3bb8/brick_6ad7881e1d979bd950d66055624354da/brick
                                Id:7b28489440e7d9b97c6ec1692ac400d3   **Size (GiB):5**       Path: /var/lib/heketi/mounts/vg_8015c217909d51109e2c8a2bb72b3bb8/brick_7b28489440e7d9b97c6ec1692ac400d3/brick
### Expected/desired behavior
heketi-cli topology info should not  be showing deleted  bricks  from lvm. even if i resynv , its releasing the  space, but it still shows bricks are occupying space.(marled bold above)
 Id:8015c217909d51109e2c8a2bb72b3bb8   Name:/dev/vdc            State:online    Size (GiB):99      Used (GiB):5       Free** (GiB):94
                        Bricks:

                                Id:7b28489440e7d9b97c6ec1692ac400d3   **Size (GiB):5**       Path: /var/lib/heketi/mounts/vg_8015c217909d51109e2c8a2bb72b3bb8/brick_7b28489440e7d9b97c6ec1692ac400d3/brick

### Information about the environment:

- Heketi version used (e.g. v6,7,8.0.0 or master): 
- Operating system used:  ubuntu 
- Heketi compiled from sources, as a package (rpm/deb), or container: container
- If container, which container image: heketi:6 or 7 or 8
- Using kubernetes, openshift, or direct install: 
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: 
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom):

**Comment by iamniting** [comment]
From the information, it is clear which version of heketi are you using, We have fixed many bugs in older heketi versions. I would recommend you to use the latest (master branch) heketi and try it. If you still see the issue let us know.

**Comment by khounish** [comment]
I tried in If container, which container image: heketi:dev ,6 or 7 or 8 , same issue. gluster version is 7.1 .

**Comment by iamniting** [comment]
I would recommend you to use [1] This is on top of the master branch and the latest among all.

[1] https://hub.docker.com/layers/heketi/heketi/dev/images/sha256-d63285bd87abfa63c01bff0533a132f6742b3781f852b9390941b61e120a0866?context=explore

**Comment by khounish** [comment]
I just tried the same ,  heketi-cli --version
heketi-cli v10.0.0-22-g631afd21

Issue persists.( **below italic part should not be there)**

 Devices:
                Id:8015c217909d51109e2c8a2bb72b3bb8   State:online    Size (GiB):99      Used (GiB):5       Free **(GiB):94**
                        Known Paths: /dev/vdc

                        Bricks:
                                _Id:3dd55589484114236a3274501c322442   Size (GiB):31      Path: /var/lib/heketi/mounts/vg_8015c217909d51109e2c8a2bb72b3bb8/brick_3dd55589484114236a3274501c322442/brick
                                Id:4583ffb9aaa7906d874a62f0cdb7e6d8   Size (GiB):31      Path: /var/lib/heketi/mounts/vg_8015c217909d51109e2c8a2bb72b3bb8/brick_4583ffb9aaa7906d874a62f0cdb7e6d8/brick
                                Id:6ad7881e1d979bd950d66055624354da   Size (GiB):31      Path: /var/lib/heketi/mounts/vg_8015c217909d51109e2c8a2bb72b3bb8/brick_6ad7881e1d979bd950d66055624354da/brick_
                                Id:7b28489440e7d9b97c6ec1692ac400d3   Size (GiB):5       Path: /var/lib/heketi/mounts/vg_8015c217909d51109e2c8a2bb72b3bb8/brick_7b28489440e7d9b97c6ec1692ac400d3/brick

**Comment by phlogistonjohn** [comment]
Depending on the state of the system heketi may not understand that those bricks are deleted. It all depends on (a) what version of heketi initiated the change and (b) what the current state of the db is.
Since you have tried this with multiple versions I'll assume that (a) was with v6 or lower.
We can only determine (b) with a dump of the db. If you're willing, you can get a db dump in json by running `heketi-cli db dump` and redirecting that to a file. Share that file with us.

Also, please list exactly what brick IDs you think should not be present.


As a side note, since you've tried multiple versions of the software I want to warn you that it is not safe to use an older version now. This was always true but older versions did not check. This is because each version of heketi makes changes to the db on initial startup and these changes are not understood by older versions. Just a word of warning.

**Comment by khounish** [comment]
[dump-heketi.txt](https://github.com/heketi/heketi/files/5189664/dump-heketi.txt)

**Comment by phlogistonjohn** [comment]
As heketi is now in maintenance mode, and only accepting major bug and security related fixes, we do not expect to implement this change.
