### ISSUE TITLE
 Failed to upgrade db for brick entries: Id not found

### ISSUE THREAD

**Issue by khounish** [heketi/heketi#1779]
### Kind of issue

> Uncomment only one of these:
> 
> Bug
> Feature request

### Observed behavior
                   0/1       Error     1          12s
heketi crashloopback with below error  for version 6?
Setting up heketi database
  File: /var/lib/heketi/heketi.db
  Size: 2097152         Blocks: 3592       IO Block: 131072 regular file
Device: c3h/195d        Inode: 12392949510043181358  Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-02-25 21:02:29.240905426 +0000
Modify: 2020-09-02 03:52:55.871322330 +0000
Change: 2020-09-02 03:52:55.875322331 +0000
 Birth: -
Heketi v6.0.0-196-gf31ad28
[heketi] INFO 2020/09/08 16:43:16 Loaded kubernetes executor
[heketi] ERROR 2020/09/08 16:43:16 /src/github.com/heketi/heketi/apps/glusterfs/dbcommon.go:121: Failed to upgrade db for brick entries: Id not found
[heketi] ERROR 2020/09/08 16:43:16 /src/github.com/heketi/heketi/apps/glusterfs/app.go:152: Unable to Upgrade Changes
[heketi] ERROR 2020/09/08 16:43:16 /src/github.com/heketi/heketi/apps/glusterfs/app.go:160: Id not found
ERROR: Unable to start application

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): 
- Operating system used: 
- Heketi compiled from sources, as a package (rpm/deb), or container: 
- If container, which container image: 
- Using kubernetes, openshift, or direct install: 
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: 
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom):

**Comment by khounish** [comment]
I tried upgrading it to latest  7,8,9,10 

7 SHOWS SAME Error. Howeververt 8,9,10 shows below error.

Setting up heketi database
  File: /var/lib/heketi/heketi.db
  Size: 2097152         Blocks: 3592       IO Block: 131072 regular file
Device: 83h/131d        Inode: 12392949510043181358  Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-02-25 21:02:29.240905426 +0000
Modify: 2020-09-02 03:52:55.871322330 +0000
Change: 2020-09-02 03:52:55.875322331 +0000
 Birth: -
[heketi] ERROR 2020/09/08 16:26:53 heketi/apps/glusterfs/dbentry.go:142:glusterfs.EntryLoad: failed to unmarshal db entry at VOLUME/8560a1daf02272c1556e5949def58517: gob: wrong type (int) for received field BrickInfo.Size
failed to dump db: Could not construct dump from DB: Could not construct dump from DB: failed to unmarshal db entry at VOLUME/8560a1daf02272c1556e5949def58517: gob: wrong type (int) for received field BrickInfo.Size
error: Unable to export db. DB contents may not be valid
Heketi v10.0.0-22-g631afd21
[heketi] INFO 2020/09/08 16:26:53 Loaded kubernetes executor
[heketi] ERROR 2020/09/08 16:26:53 heketi/apps/glusterfs/dbentry.go:142:glusterfs.EntryLoad: failed to unmarshal db entry at VOLUME/8560a1daf02272c1556e5949def58517: gob: wrong type (int) for received field BrickInfo.Size
[heketi] ERROR 2020/09/08 16:26:53 heketi/apps/glusterfs/dbcommon.go:153:glusterfs.UpgradeDB: Failed to upgrade db for brick entries: failed to unmarshal db entry at VOLUME/8560a1daf02272c1556e5949def58517: gob: wrong type (int) for received field BrickInfo.Size
[heketi] ERROR 2020/09/08 16:26:53 heketi/apps/glusterfs/app.go:241:glusterfs.(*App).initDB.func1: Unable to Upgrade DB: failed to unmarshal db entry at VOLUME/8560a1daf02272c1556e5949def58517: gob: wrong type (int) for received field BrickInfo.Size
[heketi] ERROR 2020/09/08 16:26:53 heketi/apps/glusterfs/app.go:170:glusterfs.(*App).setup: Unable to Upgrade DB: failed to unmarshal db entry at VOLUME/8560a1daf02272c1556e5949def58517: gob: wrong type (int) for received field BrickInfo.Size
ERROR: Unable to start application: Unable to Upgrade DB: failed to unmarshal db entry at VOLUME/8560a1daf02272c1556e5949def58517: gob: wrong type (int) for received field BrickInfo.Size

**Comment by phlogistonjohn** [comment]
Your db may be damaged due to bolt issues or perhaps going back and forth between old and new versions of heketi. As this issue is somewhat stale I am closing it but you can reopen if needed.
