### ISSUE TITLE
Can heketi remove the need for disk restrictions

### ISSUE THREAD

**Issue by shiune** [heketi/heketi#1780]
I think heketi needs each glusterfs node to provide disks for heketi. Can this restriction be cancelled?

**Comment by phlogistonjohn** [comment]
I'm sorry, but your question is not clear to me. When you write "provide disks for heketi" do you refer to storage for bricks in general or do you mean something like the "heketidbstorage" volume that can be used to host the heketi db on replicated storage?

**Comment by shiune** [comment]
It is not block storage, it is the storage volume of file storage and heketistoragedb. I will describe my current environment. Currently, there is no disk on the server to create lv for heketi. Is it possible to create lv without disk, without creating vg and lv, but directly using the system disk directory to create glusterfs storage

**Comment by phlogistonjohn** [comment]
Ah. I understand. No, there is no way to point heketi at an existing lvm vg or a directory. The team doesn't have plans to relax this restriction.

As a workaround, you could try creating a loopback device or using nested lvm (manually create an LV and then point heketi at that to create a vg on) on a system disk. I know the former works and I think the latter works, I think I played with that two years ago.

**Comment by shiune** [comment]
Ok i will try it, thank you

**Comment by phlogistonjohn** [comment]
As heketi is now in maintenance mode, and only accepting major bug and security related fixes, we do not expect to implement this change.
