### ISSUE TITLE
Topology: using DNS instead of IPs for storage how to mount PVCs?

### ISSUE THREAD

**Issue by GeraldWodni** [heketi/heketi#1781]
### Question: How to mount a filesystem per using DNS instead of IPs in topology-storage?

The [API Add-Node Documentation](https://github.com/heketi/heketi/blob/master/docs/api/api.md#add-node) states
> storage: array of strings, List of node storage network hostnames. These storage network addresses will be used to create and access the volume. It is __highly recommended to use hostnames instead of IP addresses__.

I have the gluster containers and the heketi container up and running. All of them can talk to each other and manual commands on the host work. Mounting a PVC into a pod yields the following error:

```
Failed to provision volume with StorageClass "gluster": failed to create volume: failed to get cluster nodes for volume Name: vol_5e85aa1b50a46c0f8c2d5ff16446d541
Size: 1
Volume Id: 5e85aa1b50a46c0f8c2d5ff16446d541
Cluster Id: dc92ed285b9d01574ee382d8117cf9fe
Mount: glusterfs-carme-0.service-carme.glusterfs.svc.cluster.local:vol_5e85aa1b50a46c0f8c2d5ff16446d541
Mount Options: backup-volfile-servers=glusterfs-metis-0.service-metis.glusterfs.svc.cluster.local
Block: false
Free Size: 0
Reserved Size: 0
Block Hosting Restriction: (none)
Block Volumes: []
Durability Type: replicate
Distributed+Replica: 2
Snapshot Factor: 1.00
: glusterfs server node ip address glusterfs-carme-0.service-carme.glusterfs.svc.cluster.local must be a valid IP address, (e.g. 10.9.8.7)
```
What irritates me is __glusterfs server node ip address glusterfs-carme-0.service-carme.glusterfs.svc.cluster.local must be a valid IP address, (e.g. 10.9.8.7)__

The volume is created by heketi and I can mount it with the exact values from the error message just fine on the hosts(nodes):
```
mount -t glusterfs -o backup-volfile-servers=glusterfs-metis-0.service-metis.glusterfs.svc.cluster.local glusterfs-carme-0.service-carme.glusterfs.svc.cluster.local:vol_5e85aa1b50a46c0f8c2d5ff16446d541 /mnt
```

DNS resolution works fine on the hosts, this seems to be a common mistake in other issues which I also fell into first.

### Information about the environment:
- Heketi version used (e.g. v6.0.0 or master): 
v10.0.0-22-g631afd21
- Operating system used: 
debian buster (10) / kubernetes 1.17
- Heketi compiled from sources, as a package (rpm/deb), or container: 
container
- If container, which container image: 
heketi/heketi:dev
- Using kubernetes, openshift, or direct install: 
kubernetes
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: 
inside
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): 
custom

**Comment by raghavendra-talur** [comment]
> ### Question: How to mount a filesystem per using DNS instead of IPs in topology-storage?
> The [API Add-Node Documentation](https://github.com/heketi/heketi/blob/master/docs/api/api.md#add-node) states
> 
> > storage: array of strings, List of node storage network hostnames. These storage network addresses will be used to create and access the volume. It is **highly recommended to use hostnames instead of IP addresses**.

This advice in the api doc is too general. It does not apply when running under Kubernetes. Thank you for bringing this to our attention, we may remove this line.

> 
> I have the gluster containers and the heketi container up and running. All of them can talk to each other and manual commands on the host work. Mounting a PVC into a pod yields the following error:
> 
> ```
> Failed to provision volume with StorageClass "gluster": failed to create volume: failed to get cluster nodes for volume Name: vol_5e85aa1b50a46c0f8c2d5ff16446d541
> Size: 1
> Volume Id: 5e85aa1b50a46c0f8c2d5ff16446d541
> Cluster Id: dc92ed285b9d01574ee382d8117cf9fe
> Mount: glusterfs-carme-0.service-carme.glusterfs.svc.cluster.local:vol_5e85aa1b50a46c0f8c2d5ff16446d541
> Mount Options: backup-volfile-servers=glusterfs-metis-0.service-metis.glusterfs.svc.cluster.local
> Block: false
> Free Size: 0
> Reserved Size: 0
> Block Hosting Restriction: (none)
> Block Volumes: []
> Durability Type: replicate
> Distributed+Replica: 2
> Snapshot Factor: 1.00
> : glusterfs server node ip address glusterfs-carme-0.service-carme.glusterfs.svc.cluster.local must be a valid IP address, (e.g. 10.9.8.7)
> ```
> 
> What irritates me is **glusterfs server node ip address glusterfs-carme-0.service-carme.glusterfs.svc.cluster.local must be a valid IP address, (e.g. 10.9.8.7)**

This error does not come from heketi, it comes from the kuberentes in-tree gluster volume provisioner. It fails to parse the Mount: section of the output into valid IPs. This component only understands IP addresses. 

> 
> The volume is created by heketi and I can mount it with the exact values from the error message just fine on the hosts(nodes):
> 
> ```
> mount -t glusterfs -o backup-volfile-servers=glusterfs-metis-0.service-metis.glusterfs.svc.cluster.local glusterfs-carme-0.service-carme.glusterfs.svc.cluster.local:vol_5e85aa1b50a46c0f8c2d5ff16446d541 /mnt
> ```
> 
> DNS resolution works fine on the hosts, this seems to be a common mistake in other issues which I also fell into first.


Yes, the DNS resolution works and mounting is also possible. Gluster and heketi both understand and can use hostnames but Kubernetes cannot.

Quoting from the recent Openshift documentation which uses heketi, gluster and kubernetes similarly:

```
StorageHostname: It is the IP address that is used by other OpenShift nodes to communicate with the node. 
Storage data traffic will use the interface attached to this IP. 
This must be the IP address and not the hostname because, in an OpenShift environment, Heketi considers this to be the endpoint too.
```
As you can see, Kubernetes cannot use DNS names as endpoint and therefore it is necessary that the StorageHostname are IPs in the topology when you are using heketi for Kubernetes dynamic provisioning.

**Comment by raghavendra-talur** [comment]
We made the change in the kubernetes design doc but missed out make the change in the API doc. Here is the doc link https://github.com/heketi/heketi/blob/master/docs/design/kubernetes-integration.md#example-kubernetes-deployment

**Comment by GeraldWodni** [comment]
@raghavendra-talur thanks for such a detailed answer. I will switch back from DNS resolution to IP.

I am however not sure what IP is meant by the [doc-link](https://github.com/heketi/heketi/blob/master/docs/design/kubernetes-integration.md#example-kubernetes-deployment) you kindly provided:
> Make sure that hostnames/manage points to the exact name as shown under kubectl get nodes, and hostnames/storage is the ip address of the storage network.

What is my __ip address of the storage network__ in that regard? If this is a service's ClusterIP or the gluster-pod's IP, it can change on restart which means I have to update the topology, which I guess would cause issues with mounted PVCs? This is what left me puzzled at the start and made me switch to DNS upon finding the API documentation.

Can you elaborate on what object's IP to use and if a topology update is required upon change?

**Comment by phlogistonjohn** [comment]
Unless you are using an unusual setup, the gluster server containers should be running with host networking. The gluster cointainers will share the node's IP adderess. You can double check this by via the pod's spec.
If the nodes have more than one IP choose one set of addresses that is reachable by all the other nodes that will run pods that need to access the volumes and that you'd prefer to have the traffic flow over.

**Comment by GeraldWodni** [comment]
@phlogistonjohn thank you very much for pointing out host networking, I was chasing after the IP of a pod/service instead. As `            hostNetwork: true` exposes gluster also on the node's public IP, I added the following iptables rules (maybe this will help a future googler):

```
iptables -N GLUSTERFS
iptables -A GLUSTERFS -i eno1 -p tcp --dport 2222  -j DROP
iptables -A GLUSTERFS -i eno1 -p tcp --dport 24007 -j DROP
iptables -A GLUSTERFS -i eno1 -p tcp --dport 24008 -j DROP
iptables -A GLUSTERFS -i eno1 -p tcp -m multiport --dports 49152:49251 -j DROP
iptables -A INPUT -j GLUSTERFS
```

Summary: beside the above @raghavendra-talur pointed out that kubernetes requires IPs to mount glusterfs, so altough StatefulSets seem like a nice solution in combination with outside-of-cluster-dns (I just created a DaemonSet which wrote the IPs to the node's `/etc/hosts`), it will not work.

Thanks again to both of you, I now have an operational gluster ;)
