### ISSUE TITLE
How to trigger movement of bricks from failed device to new device?

### ISSUE THREAD

**Issue by howels** [heketi/heketi#1782]
### Kind of issue

Feature request

### Observed behavior

Function exists https://github.com/heketi/heketi/blob/v10.0.0/apps/glusterfs/device_entry.go#L442 to remove bricks from a failed device and allocate onto unused devices but cannot see how to trigger this from heketi-cli or API.

### Expected/desired behavior

Trigger `removeBricksFromDevice` via heketi-cli or API so it is possible to "drain" a failed device by moving those failed bricks to point to new bricks on other available devices - either by replacing a disk or adding an entire new server to the cluster.

### Details on how to reproduce (minimal and precise)

Currently the delete/disable code is not working (https://github.com/heketi/heketi/issues/953) and older issues. Our team is experiencing issues replacing nodes because of this. We are considering DB export, manual fixup with gluster command, DB edit and DB re-import to resolve these. Clearly that is not a long-term solution.

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): v10.0
- Operating system used: CentOS 7
- Heketi compiled from sources, as a package (rpm/deb), or container: RPM from v10.
- If container, which container image: 
- Using kubernetes, openshift, or direct install: Direct install.
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: Outside.
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): Custom Ansible-based.

### Other useful information

Device or Node recovery seems neglected but it's a quality of life item for end-users and would make Heketi much more useful for the entire storage lifecycle and avoid complex work-around which can themselves threaten the integrity of the Heketi DB.

**Comment by iamniting** [comment]
Let me correct you, the failed device should not have any bricks, You can remove bricks from the offline device. The way you can remove bricks from the device is as written below:

1. move the device to offline state from online state
# heketi-cli device disable <device-id>
2. move the bricks from the device
# heketi-cli device remove <device-id>

Note: To perform 2nd command you should have required space in another device on the same node or another node where the other bricks of the same volumes are not present.

**Comment by phlogistonjohn** [comment]
my pr linked above adds documentation for this and similar scenarios. I would appreciate feedback on the pr.

**Comment by howels** [comment]
Thanks, we are struggling with replacing entire nodes. That seems to be the crux of the issue. While we can replace single disks the replacement of an entire node isn't going through. Reaching out to a colleague who should have up to date logs reflecting this.
