### ISSUE TITLE
Expanded K8S PVC.  How does heketi/gluster decide file placement?

### ISSUE THREAD

**Issue by amehub** [heketi/heketi#1786]
### Kind of issue

Question

### Observed behavior

In Kubernetes.
Create a storage class with volume expansion enabled, volumetype replicate:3
Create a 5GB PVC using the storage class
Edit the PVC and expand it to 15GB
Under the covers heketi creates a new 10GB LVM logical volume and brick (heketi does not expand the original 5GB LVM logical volume) 
If I try to create an 11GB file this will fail because not enough space on the 5GB  or 10GB LVs
If I try to create a 6GB  file will heketi/gluster ensure that the file is written to the 10GB LV or is there no guantee that this will happen? 
How does heketi/gluster decide which brick a file is placed on in an expanded replicate PVC?

### Expected/desired behavior
If I create a file it will always get created on a LV/brick that has adequate free space to accomodate the file.

### Details on how to reproduce (minimal and precise)
See observed behaviour.

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master):  10
- Operating system used:  Ubuntu 18.04
- Heketi compiled from sources, as a package (rpm/deb), or container:   container
- If container, which container image:  10 latest
- Using kubernetes, openshift, or direct install:   Kubernetes -> Heketi (outside K8S) -> Gluster (outside K8S)
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside:   
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom):

**Comment by iamniting** [comment]
I think you should ask this question in gluster project. That is the correct place for this. Playing with files (creation/deletion etc) is gluster responsibility not heket.

**Comment by amehub** [comment]
Makes sense.  Will look into that.
