### ISSUE TITLE
pvc  pending  Cannot create disk

### ISSUE THREAD

**Issue by misteruly** [heketi/heketi#1787]
Failed to provision volume with StorageClass "glusterfs": failed to create volume: failed to create volume: Post http://10.96.213.38:8080/volumes

but

[root@master2 gluster-heketi]# curl   http://10.96.213.38:8080/hello
Hello from Heketi[root@master2 gluster-heketi]# 

NAME                                  READY   STATUS    RESTARTS   AGE   IP                NODE      NOMINATED NODE   READINESS GATES
deploy-heketi-6b9cddcf74-bbmcj        1/1     Running   0          8h    172.168.166.219   node1     <none>           <none>
glusterfs-84csb                       1/1     Running   0          9h    192.168.1.113     node2     <none>           <none>
glusterfs-bqx2w                       1/1     Running   0          9h    192.168.1.111     master2   <none>           <none>
glusterfs-srrlh                       1/1     Running   0          9h    192.168.1.112     node1     <none>           <none>
tomcat-docker-mirr-645ddb5db8-xq242   1/1     Running   0          21h   172.168.166.254   node1     <none>           <none>

[root@master2 gluster-heketi]# 
[root@master2 gluster-heketi]# ping 172.168.166.219
PING 172.168.166.219 (172.168.166.219) 56(84) bytes of data.
64 bytes from 172.168.166.219: icmp_seq=1 ttl=63 time=0.357 ms
64 bytes from 172.168.166.219: icmp_seq=2 ttl=63 time=0.234 ms
64 bytes from 172.168.166.219: icmp_seq=3 ttl=63 time=0.206 ms
64 bytes from 172.168.166.219: icmp_seq=4 ttl=63 time=0.251 ms

Don't know what the problem is  ???

**Comment by monaminor** [comment]
hi , did you got solution?

**Comment by phlogistonjohn** [comment]
This issue lacks detail that would allow us to help you with your issue. Since the original report is a bit stale I'm closing this item. But please feel free to reopen and provide sufficient level of detail if you still want help.
