### ISSUE TITLE
Replace Failed Node - Files not copied to bricks, Gluster still has failed node

### ISSUE THREAD

**Issue by amehub** [heketi/heketi#1788]
### Issue

Attempting to take a 3 node gluster with replicate:3 volume and shutdown one node to simulate a failure.  Follow the docs  [https://github.com/heketi/heketi/pull/1783/files#diff-3d3eaf95d0ff274456c8ddd18ebba12bR213
](https://github.com/heketi/heketi/pull/1783/files#diff-3d3eaf95d0ff274456c8ddd18ebba12bR213
) to replace the failed node

gluster-01 )
gluster-02 )   a replicate:3 volume on these three nodes
gluster-03 )  
gluster-04  - this will replace gluster-03 after gluster-03 has been shutdown

### Observed behavior
The gluster has 4 nodes even after deleting the stopped node from heketi.  I can remove it from gluster but I assumed

`heketi-cli node delete <node_id> `

 would issue the gluster commands to remove the node from gluster.
The replacement node gluster-04 appears to have the correct bricks but none of the files that are on the 01 and 02 nodes have been sysn'd to the replacement nodes bricks. 

### Expected/desired behavior
3 node gluster; gluster-01, gluster-02, gluster-04
All files that are on gluster-01 and 02 sync'd to gluster-04

### Details on how to reproduce (minimal and precise)
Create 3 node gluster
gluster-01
gluster-02
gluster-03

Create heketi docker container from [https://hub.docker.com/layers/heketi/heketi/dev/images/sha256-d63285bd87abfa63c01bff0533a132f6742b3781f852b9390941b61e120a0866?context=explore](https://hub.docker.com/layers/heketi/heketi/dev/images/sha256-d63285bd87abfa63c01bff0533a132f6742b3781f852b9390941b61e120a0866?context=explore)

In k8s - create storage class with replicate:3 pointing to the heketi
Create replicate:3 pvc in K8s
Create a pod and mount the PVC
Write some files to the PVC volume

Shutdown node gluster-03

Follow the steps to replace a node including deleting the node from heketi.

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master):  latest dev 
- Operating system used:  Ubuntu 18.04
- Heketi compiled from sources, as a package (rpm/deb), or container: Container 
- If container, which container image:  https://hub.docker.com/layers/heketi/heketi/dev/images/sha256-d63285bd87abfa63c01bff0533a132f6742b3781f852b9390941b61e120a0866?context=explore
- Using kubernetes, openshift, or direct install:  Direct.  
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: 
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom):

**Comment by phlogistonjohn** [comment]
I'm triaging issues. Sorry that we were unable to provide help in a timely manner. Because this issue is rather old I'm going to close this issue.
