### ISSUE TITLE
secured password

### ISSUE THREAD

**Issue by amgads** [heketi/heketi#1791]
### Kind of issue

> Uncomment only one of these: 
Feature request

### Observed behavior

In the heketi json configuration file, passwords are given and this is not secure. Is there a way to make this more secure?
Also it is read only one time at the startup or every command heketi issues?

{
  "port": "8080",
  "use_auth": true,

  "jwt": {
    "admin": {
      "key": "q16AGbBc"
    },
    "user": {
      "key": "MtbodzAX"
    }
  },

  "glusterfs": {
    "executor": "ssh",
    "sshexec": {
      "keyfile": "/etc/heketi/gluster_user_private_key",
      "user": "gluster-user",
      "port": "22",
      "fstab": "/etc/fstab",
      "sudo": true
    },

    "max_inflight_operations": 64,
    "operation_retry_limits": { "volume_create": 8 },
    "db": "/var/lib/heketi/heketi.db",
    "loglevel" : "warning"
  }
}

### Expected/desired behavior
Password should be secure and not written in clear text or even base64

### Details on how to reproduce (minimal and precise)
Install heketi pod and cat the heketi config file

### Information about the environment:

- Heketi version used (e.g. v9.0.0 or master): all (but interested in v9 or v10
- Operating system used: Linux
- Heketi compiled from sources, as a package (rpm/deb), or container: container
- If container, which container image: private container using the heketi tgz file
- Using kubernetes, openshift, or direct install: K8S
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: inside
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): ansible

**Comment by amgads** [comment]
Any suggestions?

**Comment by iamniting** [comment]
> Any suggestions?

Hi @amgads as of today there is no way I am aware of and we don't have such plans to enhance it. Moreover only those ones can see it who has access to the container or heketi deployment which everyone should not have in my opinion.

**Comment by amgads** [comment]
Thanks @iamniting . How about the other question:

1) **Is the config file read only one time at the startup or every command heketi issues?**
2) Can the passwords be encrypted as well?

Regards,
Amgad

**Comment by iamniting** [comment]
The config file gets read by heketi at startup only. Heketi has some default values in its codebase which gets replaced by your config file and then env variables in the container.

**Comment by amgads** [comment]
Thanks @iamniting 
when heketi reads the config file at the startup -- I asume admin "key" is one of the parameters it reads. Is there a way to retreive that "key" to use when calling a heketi-cli, without being stored in a file if needs to

**Comment by iamniting** [comment]
I am not sure which file are you talking about. Either you can export it as env variables or pass via cli.
```
--secret string          
	Secret key for specified user.  Can also be
	set using the environment variable HEKETI_CLI_KEY

--server string          
	Heketi server. Can also be set using the
	environment variable HEKETI_CLI_SERVER (the default one is http://localhost:8080)

--user string            
	Heketi user.  Can also be set using the
	environment variable HEKETI_CLI_USER
```

**Comment by amgads** [comment]
I mean the "HEKETI_CLI_KEY". If I delete the config file after running heketi --config <config-file>, is there a way to retrieve it from the heketi process to use with the heketi-cli

**Comment by iamniting** [comment]
I don't think so is there any way around, and you should not delete the config file as it will be required at the next start or restart.

**Comment by amgads** [comment]
I do have a solution for the restart using the secrets during initialization, but the problem is when using the heketi-cli. Thanks!

**Comment by amgads** [comment]
I guess the request here is, since heketi starts with a configuration that has the keys (admin/user), heketi-cli should have that knowledge and should not need to pass the keys(password) on the command line or as an env variable. That's a security leak

**Comment by iamniting** [comment]
> I guess the request here is, since heketi starts with a configuration that has the keys (admin/user), heketi-cli should have that knowledge and should not need to pass the keys(password) on the command line or as an env variable. That's a security leak

This observation is not right in my opinion. You are not the only one who can run heketi-cli. Everyone who can communicate with the node can run heketi-cli. If heketi-cli will now that information everyone will be able to send a request to your heketi server. Moreover, it is not necessary that you need to request via heketi-cli only. You can request with any of the API client eg. curl. So in that case how you will be able to request if you don't know that user and password.

**Comment by amgads** [comment]
Exposing clear text passwords should not be the case. That's what all our customers require.

**Comment by phlogistonjohn** [comment]
As heketi is now in maintenance mode, and only accepting major bug and security related fixes, we do not expect to implement this change.
