### ISSUE TITLE
Can't create volume: "Error: Failed to allocate new volume: No space"

### ISSUE THREAD

**Issue by handrea2009** [heketi/heketi#1794]
### Kind of issue

Can't create volume

### Observed behavior

On a 3 nodes cluster I can't create volume with size 139Gb and replicate count 3, it return the following error

Error: Failed to allocate new volume: No space

All nodes are up&running, and the topology info shows 142GB free space on each node

### Expected/desired behavior

The volume creation should succeed or shows the max volume size that can be created.
I would need an easy way to know the maximum volume size creation that would succeed.

### Details on how to reproduce (minimal and precise)

Set up a 3 nodes heketi cluster, each node have 2 disks with size 50Gb and 100Gb
Create 3 volumes with size 1, 2 and 3Gb (replica count 3), it succeed
The topology info shows 142GB free space on each node
Create a volume with size 139Gb (replica count 3), it fails
Create a volume with size 126Gb (replica count 3), it succeed.
If I set the max_bricks_per_volume to 300, then then 139Gb volume creation succeed.

### Information about the environment:

- Heketi version used: Heketi v10.0.0-32-g068acc4b 
- Heketi and Gluster are running in kubernetes pods
- Heketi pod image: heketi/heketi:dev
- Gluster pod image: gluster/gluster-centos:latest
- Operating system used: Kubernets nodes running centos-release-8.2-2.2004.0.1.el8.x86_64

**Comment by iamniting** [comment]
heketi does the calculation of metadata and extent size while creating volume, You will be not able to give the whole free size. You need to keep some buffer. That is the reason you are not able to create a volume of 139 GB.

**Comment by handrea2009** [comment]
The free size was 142Gb and I could create volume up to 126Gb size, that would mean heketi needs 16Gb of metadata/exent size of 139Gb, I can't believe that.
Moreover, If it's so, then why when I set max_bricks_per_volume to 300 it works?
Do you know if there's a way to know in advance the maximum volume size creation that would succeed?

**Comment by iamniting** [comment]
So there are 2 factors while creating a brick set for volume. one is metadata and another one is a brick size or in other words max_bricks_per_volume.

So what happens sometimes heketi is not able to meet the below requirement. Because of which volume creation fails. and when you set the max bricks per volume to too high it was able to meet the below requirement.

| max bricks per volume | replica count | max bricks per node | volume size | brick size |
| ----------- | ----------- | ----------- | ----------- | ----------- |
| 3 | 3 | 3 / 3 = 1 | 139 | 139 / 1 = 139 |
| 6 | 3 | 6 / 3 = 2 | 139 | 139 / 2 = 69.5 |
| 9 | 3 | 9 / 3 = 3 | 139 | 139 / 3 = 46.3 |
| 12 | 3 | 12 / 3 = 4 | 139 | 139 / 4 = 34.75 |
| ... | ... | ... | ... | ... | ... |

All of the above will fail as they will be not able to create `max bricks per node` bricks on all nodes of size `brick size`

**Comment by handrea2009** [comment]
Thank for the explanation, but it's still not clear to me.
My understanding is that the defaults are:

max_bricks_per_volume 32
brick_min_size_gb 1Gb
brick_max_size_gb 4Tb

So: 32/3 = 10, 139/10=13.9Gb

So the brick size is 13.9Gb, which is in the range, then it should have succeeded with the default values.
The actual brick size when creating a volume I guess it's decided by heketi, so it seems to me that the actual brick size is not calculated currently and so it can't fit in the max_bricks_per_volume.
No that the same volume creation flailed also when I set max_bricks_per_volume to 100.

**Comment by handrea2009** [comment]
I believe the problem occurs cause I have disks with different free space (see topology below) and the brick size is the same for all the disks.
In the disk with 48Gb free I can fit up to 3 bricks 13.9 size, and in the disk with 94Gb free I can fit up to 6 bricks 13.9 size.
So 9*13.9 = 125 which is not the 139Gb requested

    Nodes:

        Node Id: 800520373729afe6104e42a4a1ea5d13
        State: online
        Cluster Id: a5e1abb2e3f4c8013b35063b86888c1b
        Zone: 1
        Management Hostnames: andrea3
        Storage Hostnames: 10.130.42.84
        Devices:
                Id:783007f1aab592393e2ef573233f2cf2   Name:/dev/sdb            State:online    Size (GiB):99      Used (GiB):5       Free (GiB):94
                        Bricks:
                                Id:0d9b600003df363fa9e1edfa4364e6de   Size (GiB):2       Path: /var/lib/heketi/mounts/vg_783007f1aab592393e2ef573233f2cf2/brick_0d9b600003df363fa9e1edfa4364e6de/brick
                                Id:12a8a334a05b2c40371ddc828756d2c4   Size (GiB):3       Path: /var/lib/heketi/mounts/vg_783007f1aab592393e2ef573233f2cf2/brick_12a8a334a05b2c40371ddc828756d2c4/brick
                Id:c137ae9202f0858ebb8539acb3f99aab   Name:/dev/sdc            State:online    Size (GiB):49      Used (GiB):1       Free (GiB):48
                        Bricks:
                                Id:0e068d5bb428b4f19d8040980d06a9c7   Size (GiB):1       Path: /var/lib/heketi/mounts/vg_c137ae9202f0858ebb8539acb3f99aab/brick_0e068d5bb428b4f19d8040980d06a9c7/brick

        Node Id: 8a7e6f7e23d8fd63eba2a9db1db7507b
        State: online
        Cluster Id: a5e1abb2e3f4c8013b35063b86888c1b
        Zone: 1
        Management Hostnames: andrea2
        Storage Hostnames: 10.130.42.179
        Devices:
                Id:ad3bc6e68aae40f0df02444d34f8f698   Name:/dev/sdc            State:online    Size (GiB):49      Used (GiB):3       Free (GiB):46
                        Bricks:
                                Id:af4e32922008152cceac0811724040bb   Size (GiB):3       Path: /var/lib/heketi/mounts/vg_ad3bc6e68aae40f0df02444d34f8f698/brick_af4e32922008152cceac0811724040bb/brick
                Id:dfa7de7bee87361d2e5c8abc548fa50d   Name:/dev/sdb            State:online    Size (GiB):99      Used (GiB):3       Free (GiB):96
                        Bricks:
                                Id:a524de078a08245458af6d47e4ddc9d9   Size (GiB):1       Path: /var/lib/heketi/mounts/vg_dfa7de7bee87361d2e5c8abc548fa50d/brick_a524de078a08245458af6d47e4ddc9d9/brick
                                Id:b737039a62b21eb0086453fabbe936fa   Size (GiB):2       Path: /var/lib/heketi/mounts/vg_dfa7de7bee87361d2e5c8abc548fa50d/brick_b737039a62b21eb0086453fabbe936fa/brick

        Node Id: aa442be22831cb1d7341658add46e628
        State: online
        Cluster Id: a5e1abb2e3f4c8013b35063b86888c1b
        Zone: 1
        Management Hostnames: andrea1
        Storage Hostnames: 10.130.42.223
        Devices:
                Id:56d0ffd8a2188db6547ccb9137a65a1b   Name:/dev/sdc            State:online    Size (GiB):49      Used (GiB):4       Free (GiB):45
                        Bricks:
                                Id:5cf96b88d6fbbef313bf99c5424027c9   Size (GiB):1       Path: /var/lib/heketi/mounts/vg_56d0ffd8a2188db6547ccb9137a65a1b/brick_5cf96b88d6fbbef313bf99c5424027c9/brick
                                Id:c985865f444d32e9c75f5a53ed45526d   Size (GiB):3       Path: /var/lib/heketi/mounts/vg_56d0ffd8a2188db6547ccb9137a65a1b/brick_c985865f444d32e9c75f5a53ed45526d/brick
                Id:7912271215f549e5dbf7bcc43d68e4ae   Name:/dev/sdb            State:online    Size (GiB):99      Used (GiB):2       Free (GiB):97
                        Bricks:
                                Id:e656c4015e16a4c329d2f925668eb6d3   Size (GiB):2       Path: /var/lib/heketi/mounts/vg_7912271215f549e5dbf7bcc43d68e4ae/brick_e656c4015e16a4c329d2f925668eb6d3/brick

**Comment by handrea2009** [comment]
yes, I believe it's almost all clear.
Is there an easy way to know in advance the maximum volume size that can be created based on the current topology?

**Comment by handrea2009** [comment]
Anyway, even using that math it should have been able to create volume of 134Gb or less, but it succeeded only at 126Gb

**Comment by iamniting** [comment]
As I told you before there are two factors, you can not rely on this above math calculation only it requires metadata calculation as well. I am not able to find where that piece of code is. If I find that I will link here.

**Comment by handrea2009** [comment]
I would need an easy way that allow me to estimate the maximum value size that will succeed.
Even a statement like use only the 90% of free space available would be acceptable.

**Comment by handrea2009** [comment]
I tried on a system with 140Tb of free space in the topology and the maximum volume I could create was 60Tb

**Comment by iamniting** [comment]
I don't think we have ever tested that big size. Probably it will get a timeout. I have never seen someone creating a volume of that much size.

**Comment by handrea2009** [comment]
By setting the max_bricks_per_volume to 1000, I could create a 138Tb volume (of 140TB available).
Heketi created about 65 bricks of size 2156GiB.

**Comment by handrea2009** [comment]
Do you have any suggestions on how I should set max_bricks_per_volume and brick_max_size_gb depending on the disks free space, volume size, etc ?

**Comment by iamniting** [comment]
I myself have not played with this area a lot. So I don't think I will be able to help you much here. I Just can say try it and set it whatever suits you the best.

**Comment by phlogistonjohn** [comment]
As heketi is now in maintenance mode, and only accepting major bug and security related fixes, we do not expect to implement this change.

**Comment by manisha-tanwar** [comment]
Hi I'm trying to set restrictions on maximum value size as 100G, When I use these settings for replica:3 I'm able to achieve it.
```
        "brick_max_size_gb" : 50,
        "brick_min_size_gb" : 1,
        "max_bricks_per_volume" : 10,
```
For 100G volume, it creates 2 bricks of 50G each, if that good approach?
