### ISSUE TITLE
Can't create or delete volume with heketi-cli

### ISSUE THREAD

**Issue by luciferhs** [heketi/heketi#1797]
When I use heketi cli to create volume, an error will be reported, as follows

[root@beehive7 apps]# heketi-cli volume create --size=1
Error: Server busy. Retry operation later.

heketi logs as follow：
[heketi] DEBUG 2020/10/26 16:34:43 heketi/apps/glusterfs/volume_entry.go:118:glusterfs.NewVolumeEntryFromRequest: [809a885d066b0c18acfbf02c3c74a736] Distributed
[heketi] WARNING 2020/10/26 16:34:43 operations in-flight (8) exceeds limit (8)
[negroni] 2020-10-26T16:34:43+08:00 | 429 | 	 482.23µs | 10.50.105.17:18080 | POST /volumes

heketi and glusterfs version as follows：
[root@beehive7 apps]# heketi-cli --version
heketi-cli v9.0.0
[root@beehive7 apps]# gluster  --version
glusterfs 7.5

But I can manually create and delete volumes through glusterfs。 As follow
[root@beehive7 apps]# gluster volume create new 10.50.105.18:/mnt/test force
volume create: new: success: please start the volume to access data

I also tried to restart heketi, and the problem is the same。

please help me！ thanks！！！！

**Comment by iamniting** [comment]
It is because your heketi server is busy and can not take more requests. Maybe you have sent too many requests to heketi.

You can check the same via `heketi-cli server operations list`

**Comment by phlogistonjohn** [comment]
Stale issue. Closing.
