### ISSUE TITLE
heketi.db File corruption

### ISSUE THREAD

**Issue by lixiaopengxiya** [heketi/heketi#1798]
about heketi.db File corruption problem I want to know how it happened?

The problems are as follows:
````
[root@fra-vka-testl2 ~]# kubectl logs pods/heketi-8d85f8d-g96fq -n kube-system
Setting up heketi database
File: /var/lib/heketi/heketi.db
Size: 262144 Blocks: 296 IO Block: 131072 regular file
Device: c8h/200d Inode: 12847849052084580490 Links: 1
Access: (0644/-rw-r--r--) Uid: ( 0/ root) Gid: ( 0/ root)
Access: 2020-01-09 17:44:46.722449960 +0000
Modify: 2020-01-24 00:03:20.084589416 +0000
Change: 2020-01-24 00:03:20.084589416 +0000
Birth: -
Heketi v9.0.0-1-g57a5f356-release-9
[heketi] INFO 2020/01/24 11:12:11 Loaded kubernetes executor
ERROR: Unable to start application: invalid page type: 18: 10
````
This problem occurs after the heketi container is restarted

**Comment by iamniting** [comment]
We use boltdb [1] for the heketi database. They will be able to answer this question better. However, they have marked the repo archived. But you can still look into existing issues maybe you will be able to find something simillar.

[1] https://github.com/boltdb/bolt

**Comment by phlogistonjohn** [comment]
Stale issue. Closing.
