### ISSUE TITLE
Heketi Systemd service

### ISSUE THREAD

**Issue by lpabon** [heketi/heketi#18]
Setup heketi as a systemd service

**Comment by sidcarter** [comment]
Never worked with Heketi or Fedora, but work with CentOS a lot. Happy to provide my cycles to help with this.

**Comment by lpabon** [comment]
Excellent!  I'm currently working on #17 .  This would be greatly appreciated.  We need a simple systemd file which would start up the service `heketi`.  The default configuration file will be placed in `/etc/heketi/heketi.json`.  The program should be started using the following command:  `/usr/bin/heketi -config=/etc/heketi.json` . 

Note that Heketi RPM spec file is still in progress, so you will need to place the `heketi.json` configuration file in `/etc/heketi` and place the `heketi` binary in `/usr/bin` by hand to work on this.

You should base the systemd service on `etcd` which is another service written in Go.

**Comment by sidcarter** [comment]
Got it going, I think. But getting errors, probably cause I don't have glusterfs installed. Will test a bit more. The errors:

```
Oct 12 21:29:04 ip-10-158-134-179 heketi: Heketi (dev)
Oct 12 21:29:04 ip-10-158-134-179 heketi: [heketi] INFO 2015/10/12 21:29:04 Loaded mock executor
Oct 12 21:29:04 ip-10-158-134-179 heketi: [heketi] ERROR 2015/10/12 21:29:04 /home/sidcarter/golang/src/github.com/heketi/heketi/apps/glusterfs/app.go:97: Unable to open database
Oct 12 21:29:04 ip-10-158-134-179 heketi: panic: runtime error: invalid memory address or nil pointer dereference
Oct 12 21:29:04 ip-10-158-134-179 heketi: [signal 0xb code=0x1 addr=0x0 pc=0x486b3b]
Oct 12 21:29:04 ip-10-158-134-179 heketi: goroutine 1 [running]:
Oct 12 21:29:04 ip-10-158-134-179 heketi: github.com/heketi/heketi/apps/glusterfs.(*App).SetRoutes(0x0, 0xc20800d090, 0x0, 0x0)
Oct 12 21:29:04 ip-10-158-134-179 heketi: /home/sidcarter/golang/src/github.com/heketi/heketi/apps/glusterfs/app.go:180 +0x12b
Oct 12 21:29:04 ip-10-158-134-179 heketi: main.main()
Oct 12 21:29:04 ip-10-158-134-179 heketi: /home/sidcarter/golang/src/github.com/heketi/heketi/main.go:104 +0x90c
Oct 12 21:29:04 ip-10-158-134-179 heketi: goroutine 2 [runnable]:
Oct 12 21:29:04 ip-10-158-134-179 heketi: runtime.forcegchelper()
Oct 12 21:29:04 ip-10-158-134-179 heketi: /usr/lib/golang/src/runtime/proc.go:90
Oct 12 21:29:04 ip-10-158-134-179 heketi: runtime.goexit()
Oct 12 21:29:04 ip-10-158-134-179 heketi: /usr/lib/golang/src/runtime/asm_amd64.s:2232 +0x1
Oct 12 21:29:04 ip-10-158-134-179 heketi: goroutine 3 [runnable]:
Oct 12 21:29:04 ip-10-158-134-179 heketi: runtime.bgsweep()
Oct 12 21:29:04 ip-10-158-134-179 heketi: /usr/lib/golang/src/runtime/mgc0.go:82
Oct 12 21:29:04 ip-10-158-134-179 heketi: runtime.goexit()
Oct 12 21:29:04 ip-10-158-134-179 heketi: /usr/lib/golang/src/runtime/asm_amd64.s:2232 +0x1
Oct 12 21:29:04 ip-10-158-134-179 heketi: goroutine 4 [runnable]:
Oct 12 21:29:04 ip-10-158-134-179 heketi: runtime.runfinq()
Oct 12 21:29:04 ip-10-158-134-179 heketi: /usr/lib/golang/src/runtime/malloc.go:712
Oct 12 21:29:04 ip-10-158-134-179 heketi: runtime.goexit()
Oct 12 21:29:04 ip-10-158-134-179 heketi: /usr/lib/golang/src/runtime/asm_amd64.s:2232 +0x1
Oct 12 21:29:04 ip-10-158-134-179 heketi: goroutine 5 [runnable]:
Oct 12 21:29:04 ip-10-158-134-179 heketi: os/signal.loop()
Oct 12 21:29:04 ip-10-158-134-179 heketi: /usr/lib/golang/src/os/signal/signal_unix.go:19
Oct 12 21:29:04 ip-10-158-134-179 heketi: created by os/signal.init·1
Oct 12 21:29:04 ip-10-158-134-179 heketi: /usr/lib/golang/src/os/signal/signal_unix.go:27 +0x35
Oct 12 21:29:04 ip-10-158-134-179 systemd: heketi.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Oct 12 21:29:04 ip-10-158-134-179 systemd: Unit heketi.service entered failed state.
Oct 12 21:29:04 ip-10-158-134-179 systemd: heketi.service holdoff time over, scheduling restart.
Oct 12 21:29:04 ip-10-158-134-179 systemd: Stopping Heketi Service...
Oct 12 21:29:04 ip-10-158-134-179 systemd: Starting Heketi Service...
Oct 12 21:29:04 ip-10-158-134-179 systemd: heketi.service start request repeated too quickly, refusing to start.
Oct 12 21:29:04 ip-10-158-134-179 systemd: Failed to start Heketi Service.
Oct 12 21:29:04 ip-10-158-134-179 systemd: Unit heketi.service entered failed state.
```

And here's the service file https://github.com/sidcarter/heketi/blob/heketi_systemd/heketi.service

**Comment by lpabon** [comment]
Of course! My bad.

The database will be placed in `/var/lib/heketi/heketi.db`.  The file `/etc/heketi/heketi.json` needs to be edited to change the value of https://github.com/heketi/heketi/blob/master/etc/heketi.json#L27 from `heketi.db` to `/var/lib/heketi/heketi.db`.

You will also need to create the directory /var/lib/heketi.

Question for you:
I'm guessing (I have not thought of this yet), that there will be a user and group called `heketi`.  Most likely the service and `/var/lib/heketi` must be part of user and group `heketi`. Is that the correct way to deploy the service?

**Comment by lpabon** [comment]
FYI thanks for finding a bug :smile:

**Comment by sidcarter** [comment]
Re: user and group. I think if `heketi` server is running as a service and since it doesn't use any port 1024, it's better to run it as user `heketi` and group `heketi`, definitely. A good practice, generally.

I can add the other conditions and edit `heketi.json` and `heketi.service` accordingly. 

yay! more testing ahead...

**Comment by sidcarter** [comment]
Looks like I have working heketi service with changes to `heketi.json` and `heketi.service`:

```
Oct 13 04:21:34 ip-10-158-134-179 heketi: [heketi] INFO 2015/10/13 04:21:34 Loaded mock executor
Oct 13 04:21:34 ip-10-158-134-179 heketi: [heketi] INFO 2015/10/13 04:21:34 Loaded simple allocator
Oct 13 04:21:34 ip-10-158-134-179 heketi: [heketi] INFO 2015/10/13 04:21:34 GlusterFS Application Loaded
```

I had to create /var/lib/heketi and change the ownership on that folder to `heketi` user and group. That worked.

Will submit the PR shortly.
