### ISSUE TITLE
Device info has different output for raw and json format

### ISSUE THREAD

**Issue by amgads** [heketi/heketi#1802]
### Kind of issue
Bug

### Observed behavior
When running device info, the State field value is "removed" and the key is "State" with capital "S"
while when using --json, the value is "failed" and the key is "state" with lower case "s"

bash-4.4# heketi_cli.py device info 32167f65f0e3fbaa03d28e755f23c7ac
Device Id: 32167f65f0e3fbaa03d28e755f23c7ac
**State: removed**
Size (GiB): 24
Used (GiB): 0
Free (GiB): 24
Create Path: /dev/vdd
Physical Volume UUID: za2Wp9-cbfr-sg01-4JOr-57mN-NNB8-RRq4zs
Known Paths: /dev/vdd
Bricks:

bash-4.4# heketi_cli.py device info 32167f65f0e3fbaa03d28e755f23c7ac --json
{"name":"/dev/vdd","storage":{"total":26079232,"free":26079232,"used":0},"id":"32167f65f0e3fbaa03d28e755f23c7ac","paths":["/dev/vdd"],"pv_uuid":"za2Wp9-cbfr-sg01-4JOr-57mN-NNB8-RRq4zs",**"state":"failed"**,"bricks":[]}
bash-4.4# 

### Expected/desired behavior
Field name and value should be the same, whether the output is raw or in json format

### Details on how to reproduce (minimal and precise)
run heketi-cli device info <device-id>
And
run heketi-cli device info <device-id> --json

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): v10.1.0
- Operating system used: CentOS8
- Heketi compiled from sources, as a package (rpm/deb), or container: container
- If container, which container image: custom
- Using kubernetes, openshift, or direct install:  k8s
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: inside on VMs
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): other

**Comment by iamniting** [comment]
You are seeing two different things, but in actual they are not different. In JSON format client directly prints the response from the server otherwise, the heketi-client will format the string in its own way. Which you can see in [1] and [2].

If you are using wrappers around it I would recommend you use JSON as you can parse it very easily and show it in your own way. even though you can create your own API client as well.

[1] https://github.com/heketi/heketi/blob/master/client/cli/go/cmds/device.go#L239
[2] https://github.com/heketi/heketi/blob/9573600fca32a944c03770525afc270eefa5f3dd/client/cli/go/cmds/utils.go#L115

**Comment by amgads** [comment]
I do use the json format. The point is that status is different in both output " failed" vs "removed". They should be the same.
Also key name "State" vs "state". 
When you run for instance a kubectl command in k8s, the values are the same when you run the command with different output options, json, yaml, or just raw output

**Comment by iamniting** [comment]
> I do use the json format. The point is that status is different in both output " failed" vs "removed". They should be the same.
> Also key name "State" vs "state".

We can think of fixing the value in this particular case, But keys I really don't think so. As the raw format is a more human-readable format and should not be used for any other purposes. Moreover 'state' vs 'State' really should not matter much when we are just reading the text.

> When you run for instance a kubectl command in k8s, the values are the same when you run the command with different output options, json, yaml, or just raw output

It is possible that they are doing the formatting in other ways, Which is keeping the same output even in raw format.

**Comment by amgads** [comment]
I’d care about the values more.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by phlogistonjohn** [comment]
The json reflects the internal state of the system. The non-json CLI was changed in the past to produce clearer output for humans reading it. This is not going to change.
