### ISSUE TITLE
heketiv10.0.0: I can change the fstab option or not

### ISSUE THREAD

**Issue by httaotao** [heketi/heketi#1805]
Hi everyone,when heketi setup the fstab,  I can change the option for fstab or not. For example, I want to add some options like "x-systemd.automount,noauto" and so on, But I can't find how to do that, thanks.

**Comment by iamniting** [comment]
I don't think you can change the options, The only thing you can change is the file location for your fstab entries.

https://github.com/heketi/heketi/blob/master/etc/heketi.json#L56

**Comment by httaotao** [comment]
> I don't think you can change the options, The only thing you can change is the file location for your fstab entries.
> 
> https://github.com/heketi/heketi/blob/master/etc/heketi.json#L56

yes, I can use shell script to do that ,but it is not a good way. so it is provide some option to change the fstab file or not in the future. thanks.

**Comment by iamniting** [comment]
We are not considering/focusing on such requests pls refer https://github.com/heketi/heketi#important-notice

**Comment by phlogistonjohn** [comment]
Mount options can be passed into heketi via the environment variable `HEKETI_MOUNT_OPTS` or via the config file parameter `mountopts` in the "sshexec" or "kubeexec" subsections under "glusterfs".
Do note that these are uniform across all fstab entries heketi creates, but does not retroactively change fstab entries already stored on disk.

FWIW the default options are: ""rw,inode64,noatime,nouuid". You must include these in the config file along with the additional options you want. Please note that once you start changing this you're on your own to make sure they get correctly mounted and that  gluster can consume the bricks correctly.

I hope this answers the question.

**Comment by iamniting** [comment]
Good to know it, I was not aware of this. Thaks John.

**Comment by httaotao** [comment]
> Mount options can be passed into heketi via the environment variable `HEKETI_MOUNT_OPTS` or via the config file parameter `mountopts` in the "sshexec" or "kubeexec" subsections under "glusterfs".
> Do note that these are uniform across all fstab entries heketi creates, but does not retroactively change fstab entries already stored on disk.
> 
> FWIW the default options are: ""rw,inode64,noatime,nouuid". You must include these in the config file along with the additional options you want. Please note that once you start changing this you're on your own to make sure they get correctly mounted and that gluster can consume the bricks correctly.
> 
> I hope this answers the question.

sorry, when I test it ,it doesn't matter, I don't know the reason. First, I make the env`HEKETI_MOUNT_OPTS: rw,inode64,noatime,nouuid,noauto,x-systemd.automount` for heketi pod, and then I also set the heketi.json like that:
```
root@shell:/srv/ops-kubeconfig# kubectl -n project-ops-heketi exec -it heketi-0  -- /bin/bash
[root@heketi-0 /]# cat /etc/heketi/heketi.json 
{
	"_port_comment": "Heketi Server Port Number",
	"port" : "8080",

	"_use_auth": "Enable JWT authorization. Please enable for deployment",
	"use_auth" : false,

	"_jwt" : "Private keys for access",
	"jwt" : {
		"_admin" : "Admin has access to all APIs",
		"admin" : {
			"key" : "My Secret"
		},
		"_user" : "User only has access to /volumes endpoint",
		"user" : { 
			"key" : "My Secret"
		}
	},

	"_glusterfs_comment": "GlusterFS Configuration",
	"glusterfs" : {

		"_executor_comment": "Execute plugin. Possible choices: mock, ssh",
		"executor" : "mock",

		"_db_comment": "Database file name",
		"db" : "/var/lib/heketi/heketi.db",
             
                "_sshexec_comment": "SSH username and private key file information",
                "sshexec":{
                    "mountopts": "rw,inode64,noatime,nouuid,noauto,x-systemd.automount"
                 }
	}
}
[root@heketi-0 /]# echo $HEKETI_MOUNT_OPTS
rw,inode64,noatime,nouuid,noauto,x-systemd.automount
```

and then I apply a pvc,but  in the heketi logs, I can't see the fstab option to set.so which steps I make mistakes? thanks

**Comment by iamniting** [comment]
Your config file does not look right to me. First of all, you need to change your executor, and you need to fill most of the data in sshexec https://github.com/heketi/heketi/blob/master/etc/heketi.json#L52

**Comment by httaotao** [comment]
> Your config file does not look right to me. First of all, you need to change your executor, and you need to fill most of the data in sshexec https://github.com/heketi/heketi/blob/master/etc/heketi.json#L52

sorry I made some mistakes, the heketi version is `v9.0.0-137-g7340ee40`, but when I update the version , it made some mistakes , I made a new issue to record ,thanks.

**Comment by httaotao** [comment]
> Your config file does not look right to me. First of all, you need to change your executor, and you need to fill most of the data in sshexec https://github.com/heketi/heketi/blob/master/etc/heketi.json#L52

I success when update the heketi  version into `v10.0.0-38-g1177ffc5`,  the docker version is `heketi/hekti:dev`, thanks !!!
