### ISSUE TITLE
heketi10.0.0: when zfs block device size change ,heketi can't know 

### ISSUE THREAD

**Issue by httaotao** [heketi/heketi#1809]
hi everyone, I use the zfs to create a block device for heketi.  the block  device  creating command shows that:

```
$sudo zfs create -V 10G  -o compression=on gpool/DATA/glusterfs/k8s-cicd-test-heketi-10G
```
then I use the block device for heketi topology.
```
{
    "clusters": [
        {
            "nodes": [
                {
                    "node": {
                        "hostnames": {
                            "manage": [
                                  "10.3.xx.xx"
                            ],
                            "storage": [
                                "10.3.xx.xx"
                            ]
                        },
                        "zone": 1
                    },
                    "devices": [
    			 "/dev/zvol/gpool/DATA/glusterfs/k8s-cicd-test-heketi-10G"
                    ]
                },
                {
                    "node": {
                        "hostnames": {
                            "manage": [
                                "10.3.xx.xx"
                            ],
                            "storage": [
                                "10.3.xx.xx"
                            ]
                        },
                        "zone": 2
                    },
                    "devices": [
                        "/dev/zvol/gpool/DATA/glusterfs/k8s-cicd-test-heketi-10G"
			
                    ]
                }
               ．．．
            ]
        }
    ]
}

```
Today, when I want to expand the block size ,I use this command to expand the zfs block device.
```
$ sudo zfs get volsize  gpool/DATA/glusterfs/k8s-cicd-test-heketi-10G
NAME                                           PROPERTY  VALUE    SOURCE
gpool/DATA/glusterfs/k8s-cicd-test-heketi-10G  volsize   10G      local
$ sudo zfs set volsize=30GB  gpool/DATA/glusterfs/k8s-cicd-test-heketi-10G
$ sudo zfs get volsize  gpool/DATA/glusterfs/k8s-cicd-test-heketi-10G
NAME                                           PROPERTY  VALUE    SOURCE
gpool/DATA/glusterfs/k8s-cicd-test-heketi-10G  volsize   30G      local
```
But  heketi could not konw the block'size changing. when I want to apply some volume, it showed
```
[heketi] ERROR 2020/11/30 10:18:39 heketi/apps/glusterfs/volume_entry_allocate.go:37:glusterfs.(*VolumeEntry).allocBricksInCluster: Minimum brick size limit reached.  Out of space.
[heketi] ERROR 2020/11/30 10:18:39 heketi/apps/glusterfs/operations_manage.go:220:glusterfs.AsyncHttpOperation: Create Volume Build Failed: No space
[negroni] 2020-11-30T10:18:39Z | 500 | 	 436.4334ms | cicd-test-ops-heketi.deeproute.ai | POST /volumes
```
so could you provide some command to reload the size of block size in the future? thanks.

**Comment by iamniting** [comment]
If I understood correctly you want to change the size of the device which you already have in heketi. `device sync` command might help you here. But I personally never tried it. You can give it a try.

**Comment by httaotao** [comment]
> If I understood correctly you want to change the size of the device which you already have in heketi. `device sync` command might help you here. But I personally never tried it. You can give it a try.

sorry, it doesn't matter.
```
$ sudo fdisk  -l /dev/zvol/gpool/DATA/glusterfs/k8s-cicd-test-heketi-10G
Disk /dev/zvol/gpool/DATA/glusterfs/k8s-cicd-test-heketi-10G: 60 GiB, 64424509440 bytes, 125829120 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 8192 bytes
I/O size (minimum/optimal): 8192 bytes / 8192 bytes

```
then resync device info 
```
$ hekectl-cli-cicd-test cluster list 
Clusters:
Id:c00fc72497a7d98969f7414caa3c00cd [file][block]

$ hekectl-cli-cicd-test device resync c00fc72497a7d98969f7414caa3c00cd

$ hekectl-cli-cicd-test topology info

Cluster Id: c00fc72497a7d98969f7414caa3c00cd

    File:  true
    Block: true

    Volumes:

	  .....

    Nodes:

	Node Id: 87626dc988c4bd567cd9af65dbc150f9
	State: online
	Cluster Id: c00fc72497a7d98969f7414caa3c00cd
	Zone: 2
	Management Hostnames: 10.3.2.32
	Storage Hostnames: 10.3.2.32
	Devices:
	
			Bricks:
		Id:e049c82a8b4a22bd9c1351b3c5da749c   State:online    Size (GiB):9       Used (GiB):8       Free (GiB):1       
			Known Paths: /dev/gpool/DATA/glusterfs/k8s-cicd-test-heketi-10G /dev/zvol/gpool/DATA/glusterfs/k8s-cicd-test-heketi-10G

```

**Comment by iamniting** [comment]
> sorry, it doesn't matter.

I am not sure what are you trying to say. From the statement, it looks like you don't care anymore, But from output, it looks like it did work.

**Comment by httaotao** [comment]
> > sorry, it doesn't matter.
> 
> I am not sure what are you trying to say. From the statement, it looks like you don't care anymore, But from output, it looks like it did work.

I'm sorry, maybe I didn't express it clearly. In each nodes ,I use command `zfs set volsize xxx` to change the block device size. then it can show the size by command `fdisk -l `. and then I use heketi cli command "device resync "to resync storage information about the device with operation system.Actually,  after that use the command `topology info`, you can see the node's info ` Size (GiB):9       Used (GiB):8       Free (GiB):1 `, it shows that the command doesn't resync the info about the device with operation system.

Not matter what size I set to the block device,  the topology info doesn't change.

**Comment by iamniting** [comment]
If `device resync` does not work here then I don't think so you can do that. What you can do is, instead of expanding the same device you can create a new partition and add a new device in heketi on the same nodes.

**Comment by httaotao** [comment]
> If `device resync` does not work here then I don't think so you can do that. What you can do is, instead of expanding the same device you can create a new partition and add a new device in heketi on the same nodes.

yes, I can create a new partition to deal with. maybe I will check the source code to find out the reason. thanks
