### ISSUE TITLE
heketi docker image bug: Create Volume Rollback error 

### ISSUE THREAD

**Issue by httaotao** [heketi/heketi#1811]
hi everyone,  before when I want to update the heketi docker image into latest version, it made some mistakes.  It couldn't create volume ,the heketi logs showed:
```
[heketi] ERROR 2020/12/02 09:14:14 heketi/apps/glusterfs/operations_manage.go:175:glusterfs.runOperationAfterBuild: Create Volume Rollback error: /bin/bash: /usr/sbin/lvm: No such file or directory
```
I have been tried such docker version:
```
 heketi/heketi:dev
 heketi/heketi:latest
 heketi/heketi:10
```
They all made the same mistakes, the glusterfs os version is  `Ubuntu 18.04.5 LTS \n \l`, 
and  glusterfs version is `glusterfs 7.5`
But when I use the version 
```
# heketi -v
Heketi v9.0.0-137-g7340ee40
```
it is ok. thanks

**Comment by iamniting** [comment]
Pls, refer to https://github.com/heketi/heketi/issues/1743.
