### ISSUE TITLE
how does heketi config env "debug_umount_failures"   work?

### ISSUE THREAD

**Issue by httaotao** [heketi/heketi#1812]
hi everyone, these day, I found that the pod mounting point somtime will umount, but the pod can't check the error in k8s. then I found the heketi config env "debug_umount_failures". then function  shows that:
```
debug_umount_failures: _bool_, Enable to capture more details in case brick unmounting fails. Can be overridden by the HEKETI_DEBUG_UMOUNT_FAILURES
```
when I set the env for true, I don't know how to check the logs message when the volume make mistakes.

By the way,  I can't find the logs in the pod.

Finally, this is some other infor.
```
# heketi -v 
Heketi v10.0.0-38-g1177ffc5

# kubectl  version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.9", GitCommit:"2e808b7cb054ee242b68e62455323aa783991f03", GitTreeState:"clean", BuildDate:"2020-01-18T23:33:14Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.12", GitCommit:"5ec472285121eb6c451e515bc0a7201413872fa3", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:12Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

$ sudo gluster --version
glusterfs 7.5
Repository revision: git://git.gluster.org/glusterfs.git
Copyright (c) 2006-2016 Red Hat, Inc. <https://www.gluster.org/>
GlusterFS comes with ABSOLUTELY NO WARRANTY.
It is licensed to you under your choice of the GNU Lesser
General Public License, version 3 or any later version (LGPLv3
or later), or the GNU General Public License, version 2 (GPLv2),
in all cases as published by the Free Software Foundation.
```
thanks.

**Comment by iamniting** [comment]
I think `debug_umount_failures` comes into the picture while deleting gluster volume. Sometimes heketi is not able to umount bricks for any reason. In that case, if the variable is set then heketi will run some debug commands.

You can check your heketi logs via `kubectl logs <heketi-pod-name>`

**Comment by httaotao** [comment]
> I think `debug_umount_failures` comes into the picture while deleting gluster volume. Sometimes heketi is not able to umount bricks for any reason. In that case, if the variable is set then heketi will run some debug commands.
> 
> You can check your heketi logs via `kubectl logs <heketi-pod-name>`

Oh, I'm really sorry that I think wrong. I want to find out some way to check the volume mounting status. but this param is not this function. thanks.

**Comment by phlogistonjohn** [comment]
In case someone else finds this thread in the future:

To be specific what this option does is request the executor to run a function `checkUnmountStatus` if-and-only-if heketi is unable to unmount a brick fs during volume delete. This function runs `lsof` on the brick mount path. The lsof command lists any open files on the brick mount. This is useful to help debug two scenarios we were hitting frequently for a while. (1) there were bugs in some gluster translators that failed to close open fds. lsof would indicate gluster was the process with open files so then we could ask users hitting this to work with the gluster team to debug why gluster still have open fds after `stop` and `delete` were issued for said volume. (2) sometimes people would log into gluster nodes and cd into brick paths. this would show up in lsof too.

The reason this is behind a config option was that it is not required to have lsof on nodes for proper functioning of heketi+gluster in normal operation. lsof can also be a bit expensive to run, so this was all made optional.

**Comment by httaotao** [comment]
> In case someone else finds this thread in the future:
> 
> To be specific what this option does is request the executor to run a function `checkUnmountStatus` if-and-only-if heketi is unable to unmount a brick fs during volume delete. This function runs `lsof` on the brick mount path. The lsof command lists any open files on the brick mount. This is useful to help debug two scenarios we were hitting frequently for a while. (1) there were bugs in some gluster translators that failed to close open fds. lsof would indicate gluster was the process with open files so then we could ask users hitting this to work with the gluster team to debug why gluster still have open fds after `stop` and `delete` were issued for said volume. (2) sometimes people would log into gluster nodes and cd into brick paths. this would show up in lsof too.
> 
> The reason this is behind a config option was that it is not required to have lsof on nodes for proper functioning of heketi+gluster in normal operation. lsof can also be a bit expensive to run, so this was all made optional.

thanks for answer. I have a confused mind why not use command `gluster volume info xxx` to check the status of volume?  thanks.

**Comment by phlogistonjohn** [comment]
> thanks for answer. I have a confused mind why not use command `gluster volume info xxx` to check the status of volume? thanks.

I'm not sure what that would accomplish. Heketi has a more encompassing view of what a volume entails so querying gluster wouldn't give us any information as to why a brick fs failed to unmount - gluster doesn't track that state at all.
