### ISSUE TITLE
how to delete heketi-cli volume metadata info ?

### ISSUE THREAD

**Issue by httaotao** [heketi/heketi#1817]
hello everyone, today I use heketi-cli  to delete volume. the volume was deleted by gluster cluster, but the volume info in heketi-cli is still here.
```
$ hekectl-cli volume list 
Id:17f6159d63f9f7b43e0dd3769b43021d    Cluster:84398eef10523458ba62aabacd5bb3ce    Name:vol_17f6159d63f9f7b43e0dd3769b43021d
Id:caa9fe2948dda397ca9501ee7755d5d8    Cluster:84398eef10523458ba62aabacd5bb3ce    Name:vol_caa9fe2948dda397ca9501ee7755d5d8

$ sudo gluster volume info vol_17f6159d63f9f7b43e0dd3769b43021d
Volume vol_17f6159d63f9f7b43e0dd3769b43021d does not exist

$ sudo gluster volume info vol_caa9fe2948dda397ca9501ee7755d5d8
Volume vol_caa9fe2948dda397ca9501ee7755d5d8 does not exist
```
So could I delete the heketi-cli volume metadata info? thanks.

version info:
```
$ hekectl-cli   --version
heketi-cli v10.0.0

glusterfs: 7.5

k8s: v.17.9
```
thanks.

**Comment by iamniting** [comment]
Just deleting volume from heketi should work.

BTW I really do not understand why do you guys play with gluster, when heketi is there you should not do that. All operations should be done via heketi itself.

**Comment by httaotao** [comment]
> Just deleting volume from heketi should work.
> 
> BTW I really do not understand why do you guys play with gluster, when heketi is there you should not do that. All operations should be done via heketi itself.

ye,Firstly, I use `heketi-cli volume delete` to delete volume with env `HEKETI_GLUSTER_CLI_TIMEOUT: 60`, after a long time , time was up and it returned
```
Error: server did not provide a message (status 500: Internal Server Error)
```
In fact, the volume did not exist in the gluster cluster and the heketi-cli does not delete the metadata info. so I want to delete it by myself, thanks.

**Comment by phlogistonjohn** [comment]
I think the empty response problem has been fixed. Plus, as heketi is now in maintenance mode I don't think anything  more to do here. Therefore I'm closing this. Feel free to reopen if more discussion is needed.
