### ISSUE TITLE
[Feature request] Evict brick - specify target node or device

### ISSUE THREAD

**Issue by mtz29** [heketi/heketi#1823]
Would it be possible to extend the evict brick functionality by adding target node or device, where brick should be moved to?

**Comment by iamniting** [comment]
Nope pls refer https://github.com/heketi/heketi#important-notice

**Comment by phlogistonjohn** [comment]
I'm triaging issues. As noted by @iamniting previously we're not adding new features to heketi. I hope you understand. Closing issue.
