### ISSUE TITLE
heketi-cli cannot delete volume

### ISSUE THREAD

**Issue by lagougou** [heketi/heketi#1824]
### Kind of issue

> Uncomment only one of these:
> 
> Bug
> Feature request

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): 
- Operating system used: 
- Heketi compiled from sources, as a package (rpm/deb), or container: 
- If container, which container image: 
- Using kubernetes, openshift, or direct install: 
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: 
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): 

### Other useful information
when i use heketi-cli delete a volume, get a error tip.
```
heketi-cli volume delete 6a99047ae0430595b1c6278aba4fbb30
Error: All 2 hosts: Unable to delete volume vol_6a99047ae0430595b1c6278aba4fbb30: volume delete: vol_6a99047ae0430595b1c6278aba4fbb30: failed: Some of the peers are down
```

**Comment by iamniting** [comment]
Gluster does not allow you to delete volume when any of the gluster node is down, in another word all gluster server needs to be up in order to delete the volume. The error also indicates the same `Some of the peers are down`

**Comment by manisha-tanwar** [comment]
@lagougou this might be useful
[https://access.redhat.com/solutions/4007671](https://access.redhat.com/solutions/4007671) --> Heketi fails to remove node and its devices in an event of deprecating a glusterfs node

**Comment by phlogistonjohn** [comment]
I'm triaging issues. The last conversation comment was many months old, so I will be closing this issue.
