### ISSUE TITLE
failed to start heketi service

### ISSUE THREAD

**Issue by monaminor** [heketi/heketi#1826]
Loaded: loaded (/etc/systemd/system/heketi.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2020-12-31 11:40:18 UTC; 31min ago
  Process: 7122 ExecStart=/usr/local/bin/heketi --config=/etc/heketi/heketi.json (code=exited, status=1/FAILURE)
 Main PID: 7122 (code=exited, status=1/FAILURE)

Dec 31 11:40:18 heketi systemd[1]: heketi.service: Main process exited, code=exited, status=1/FAILURE
Dec 31 11:40:18 heketi systemd[1]: heketi.service: Failed with result 'exit-code'.
Dec 31 11:40:18 heketi systemd[1]: heketi.service: Service RestartSec=100ms expired, scheduling restart.
Dec 31 11:40:18 heketi systemd[1]: heketi.service: Scheduled restart job, restart counter is at 5.
Dec 31 11:40:18 heketi systemd[1]: Stopped Heketi Server.
Dec 31 11:40:18 heketi systemd[1]: heketi.service: Start request repeated too quickly.
Dec 31 11:40:18 heketi systemd[1]: heketi.service: Failed with result 'exit-code'.
Dec 31 11:40:18 heketi systemd[1]: Failed to start Heketi Server.

**Comment by monaminor** [comment]
why i am getting this error

**Comment by monaminor** [comment]
$sudo /usr/local/bin/heketi --config=/etc/heketi/heketi.json

Heketi v10.2.0
2020/12/31 12:12:35 no SSH_KNOWN_HOSTS specified, skipping ssh host verification
[heketi] INFO 2020/12/31 12:12:35 Loaded ssh executor
[heketi] INFO 2020/12/31 12:12:35 Adv: Max bricks per volume set to 33
[heketi] INFO 2020/12/31 12:12:35 Adv: Max brick size 1024 GB
[heketi] INFO 2020/12/31 12:12:35 Adv: Min brick size 1 GB
[heketi] INFO 2020/12/31 12:12:35 Volumes per cluster limit is set to default value of 1000
[heketi] INFO 2020/12/31 12:12:35 Block: Auto Create Block Hosting Volume set to true
[heketi] INFO 2020/12/31 12:12:35 Block: New Block Hosting Volume size 500 GB
[heketi] INFO 2020/12/31 12:12:35 Block: New Block Hosting Volume Options: group gluster-block
[heketi] INFO 2020/12/31 12:12:35 GlusterFS Application Loaded
[heketi] INFO 2020/12/31 12:12:35 Started Node Health Cache Monitor
[heketi] INFO 2020/12/31 12:12:35 Started background pending operations cleaner
Listening on port 8080
[heketi] INFO 2020/12/31 12:12:45 Starting Node Health Status refresh
[heketi] INFO 2020/12/31 12:12:45 Cleaned 0 nodes from health cache

**Comment by iamniting** [comment]
Closing this as I see that this worked later after using sudo. Feel free to reopen it if still have the issue.
