### ISSUE TITLE
MountVolume.SetUp failed for volume "heketi-storage"

### ISSUE THREAD

**Issue by monaminor** [heketi/heketi#1828]
### Kind of issue

> Uncomment only one of these:
> 
> Bug
> Feature request

### Information about the environment:

Events:
  Type     Reason       Age    From               Message
  ----     ------       ----   ----               -------
  Normal   Scheduled    2m37s  default-scheduler  Successfully assigned default/heketi-storage-copy-job-g5wx6 to aks-agentpool-13701380-vmss000002
  Warning  FailedMount  2m36s  kubelet            MountVolume.SetUp failed for volume "heketi-storage" : mount failed: mount failed: exit status 1
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/bd727ff4-9b6c-485d-a283-a9d68f991099/volumes/kubernetes.io~glusterfs/heketi-storage --scope -- mount -t glusterfs -o auto_unmount,backup-volfile-servers=10.5.0.4:10.5.0.115:10.5.0.226,log-file=/var/lib/kubelet/plugins/kubernetes.io/glusterfs/heketi-storage/heketi-storage-copy-job-g5wx6-glusterfs.log,log-level=ERROR 10.5.0.115:heketidbstorage /var/lib/kubelet/pods/bd727ff4-9b6c-485d-a283-a9d68f991099/volumes/kubernetes.io~glusterfs/heketi-storage
Output: Running scope as unit: run-r12cffef4377b4a249fb282566ea0f867.scope
Mount failed. Please check the log file for more details.
, the following error information was pulled from the glusterfs log to help diagnose this issue:
[2021-01-02 17:57:09.320856] E [MSGID: 100026] [glusterfsd.c:2403:glusterfs_process_volfp] 0-: failed to construct the graph
[2021-01-02 17:57:09.321034] E [graph.c:1102:glusterfs_graph_destroy] (-->/usr/sbin/glusterfs(mgmt_getspec_cbk+0x537) [0x557b2cf5ae77] -->/usr/sbin/glusterfs(glusterfs_process_volfp+0x180) [0x557b2cf54ea0] -->/usr/lib/x86_64-linux-gnu/libglusterfs.so.0(glusterfs_graph_destroy+0x6b) [0x7fe6937cceab] ) 0-graph: invalid argument: graph [Invalid argument]
  Warning  FailedMount  2m35s  kubelet  MountVolume.SetUp failed for volume "heketi-storage" : mount failed: mount failed: exit status 1
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/bd727ff4-9b6c-485d-a283-a9d68f991099/volumes/kubernetes.io~glusterfs/heketi-storage --scope -- mount -t glusterfs -o auto_unmount,backup-volfile-servers=10.5.0.4:10.5.0.115:10.5.0.226,log-file=/var/lib/kubelet/plugins/kubernetes.io/glusterfs/heketi-storage/heketi-storage-copy-job-g5wx6-glusterfs.log,log-level=ERROR 10.5.0.115:heketidbstorage /var/lib/kubelet/pods/bd727ff4-9b6c-485d-a283-a9d68f991099/volumes/kubernetes.io~glusterfs/heketi-storage
Output: Running scope as unit: run-r7c40761dd8ea4eaaa46e409dc10a1211.scope
Mount failed. Please check the log file for more details.
, the following error information was pulled from the glusterfs log to help diagnose this issue:
[2021-01-02 17:57:10.000111] E [MSGID: 100026] [glusterfsd.c:2403:glusterfs_process_volfp] 0-: failed to construct the graph
[2021-01-02 17:57:10.000292] E [graph.c:1102:glusterfs_graph_destroy] (-->/usr/sbin/glusterfs(mgmt_getspec_cbk+0x537) [0x56451fbc7e77] -->/usr/sbin/glusterfs(glusterfs_process_volfp+0x180) [0x56451fbc1ea0] -->/usr/lib/x86_64-linux-gnu/libglusterfs.so.0(glusterfs_graph_destroy+0x6b) [0x7fc119bf0eab] ) 0-graph: invalid argument: graph [Invalid argument]
  Warning  FailedMount  2m34s  kubelet  MountVolume.SetUp failed for volume "heketi-storage" : mount failed: mount failed: exit status 1

**Comment by monaminor** [comment]
can any one help me in this, i am trying to run,

kubectl create -f heketi-storage.json

but the pod "heketi-storage" always i in containercreating mode.
kindly help me in resolving this

**Comment by iamniting** [comment]
I think this is a glusterfs issue. gluster folks will be able to help in the gluster project

**Comment by phlogistonjohn** [comment]
I'm triaging issues. The last comment on this issue is rather old, so I'll be closing this issue now.
