### ISSUE TITLE
Failed to provision volume with StorageClass "gluster-heketi-storage-class"

### ISSUE THREAD

**Issue by monaminor** [heketi/heketi#1829]
pvc is always be in pending state.
kindly help me in this

**Comment by monaminor** [comment]
$ kubectl get pvc
NAME       STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS     AGE
gluster1   Pending                                      gluster-heketi   4m33s

**Comment by iamniting** [comment]
We can't help without info, Whole info should be provided.

**Comment by phlogistonjohn** [comment]
I'm triaging issues. The last comments on this issue are rather old. Closing issue.
