### ISSUE TITLE
Support for external database

### ISSUE THREAD

**Issue by manisha-tanwar** [heketi/heketi#1832]
### Kind of issue

> Uncomment only one of these:
> 
> Bug
Feature request

### Observed behavior
Using this configuration setup we can only have heketi database with local file.
	"glusterfs" : {
                ...
		"db" : "/var/lib/heketi/heketi.db"
         "
### Expected/desired behavior
It would be nice if we can have support for any external database(posgres, mysql etc)
	"database" : {
                ...
		"hostname" : "postgres host"
		"db" : "postgres_db"
		"user" : "postgres_user"
		"password" : "postgres_password"
         "
### Other useful information

I'm trying to configure Heketi on multi DC setup and want to share the database without NFS. It would be great if we can have support to use external database.

**Comment by iamniting** [comment]
You can use the external file as the heketi database. It is not necessary to be on the same node where heketi is running. We are also doing the same while using heketi in container. Create a volume, place your heketi db on that volume and then mount the volume on the node where heketi is running.

**Comment by phlogistonjohn** [comment]
Heketi is in maintenance and adding new large features like supporting an SQL db are out of scope.
As @iamniting mentions the file system the boltdb is stored on does not need to be local, but you do mention NFS so I assume you are aware of this.
