### ISSUE TITLE
Recreating heketi database

### ISSUE THREAD

**Issue by QkiZMR** [heketi/heketi#1835]
I have an OKD cluster with GlusterFS as a storage class and Heketi as a frontend. Everything works fine till destroy of the Heketi database. Now I can't make any changes to the storage, I can't add new persistent volume or remove existing ones. GlusterFS still works fine serving existing persistent volumes to pods.
Question: is it possible to recreate the database from topology.json and existing data on glusterfs?

**Comment by iamniting** [comment]
> Question: is it possible to recreate the database from topology.json and existing data on glusterfs?

I don't think that's possible in an automated fashion. But you can create a database manually. Creating a database manually needs a good understanding of heketi DB.

You can not even create a new heketi cluster from the topology file until you destroy the older one Because heketi runs gluster peer commands before creating a DB from the topology file.

You should create a backup of heketi Db in an automated fashion so you can tweak the backup to create the original.

**Comment by QkiZMR** [comment]
I have an idea: I will add new disks to OKD VM's and add them to Heketi creating new database from topology. Then I will recreate persistent volumes and migrate data from old ones. But the question is if I create a new database is old Glusterfs volumes will be still accessible?

**Comment by iamniting** [comment]
you can not create a new database from the topology until you destroy the gluster cluster as I said above.

once you destroy the cluster you can not have old volumes.

**Comment by manisha-tanwar** [comment]
I'm also looking for option to reuse heketi db in case I loose my heketi server.
I tried copying heketi.db to other server and restart service but It doesn't work:

```
 systemd[1]: Started Heketi Server - ********.
 heketi[17074]: Heketi v10.2.0
 heketi[17074]: 2021/01/28 18:09:34 no SSH_KNOWN_HOSTS specified, skipping ssh host verification
 heketi[17074]: [heketi] INFO 2021/01/28 18:09:34 Loaded ssh executor
 heketi[17074]: [heketi] ERROR 2021/01/28 18:09:37 heketi/apps/glusterfs/dbcommon.go:226:glusterfs.OpenDB: Unable to open database: 
 heketi[17074]: [heketi] ERROR 2021/01/28 18:09:37 heketi/apps/glusterfs/app.go:211:glusterfs.(*App).initDB: Unable to open database read-
 heketi[17074]: [heketi] INFO 2021/01/28 18:09:37 Trying to open db in read only mode
```

How can I make it read-write from both server?

**Comment by manisha-tanwar** [comment]
The database can be used at 1 time. So when I stopped heketi server from 1st server, its working fine on 2nd node. 
But not sure if we lost database file how can I recover it.

**Comment by iamniting** [comment]
There is no way to recover it as far as I know, as I mentioned above consider taking nightly or weekly backups.

**Comment by QkiZMR** [comment]
I resolved my problem by making backup of data from glusterfs and then recreating cluster from scratch.

**Comment by manisha-tanwar** [comment]
@QkiZMR does heketi show old gluster nodes & bricks now in topology?

**Comment by QkiZMR** [comment]
After recreating? Yes.

**Comment by manisha-tanwar** [comment]
I just want to understand can u manage old volumes and bricks using heketi now(new db) ? Or these are kind of dangling & can only be managed directly from gluster?

**Comment by QkiZMR** [comment]
There are no old volumes and bricks anymore, disks with gluster LVM were wiped. First I copied data on the side storage, wipe disks and recreate gluster volumes and bricks from scratch using Heketi. At the end, I recreated gluster volumes (new ones but with the same names as old ones) and copy data back from side storage.

**Comment by phlogistonjohn** [comment]
I'm triaging issues. This conversation has appeared to have wound down. I'll be closing this issue
