### ISSUE TITLE
heketi-cli cannot delete device

### ISSUE THREAD

**Issue by 0panwang0** [heketi/heketi#1836]
I try to delete a device which state is removed 
![image](https://user-images.githubusercontent.com/32365314/106230688-0613aa80-622b-11eb-9854-c621c9b96530.png)
but 
![image](https://user-images.githubusercontent.com/32365314/106230623-de244700-622a-11eb-871c-770190fd3831.png)

**Comment by iamniting** [comment]
First of all, there is something wrong with your device as I see the size 0. Then you need to find the reason that why VG is not present, Did you deleted it yourself? Try to use the force-forget option it should work.

**Comment by 0panwang0** [comment]
thanks
