### ISSUE TITLE
Delete volume 

### ISSUE THREAD

**Issue by un1xman** [heketi/heketi#1839]
I delet pvc from Kubernetes and then i want delete volume from heketi.But when i run "heketi-cli delete volume $id i take this error

Error: umount: /var/lib/heketi/mounts/vg_1b90e268f362aebbc8a92bd3d1defb56/brick_8a349535ea662886d23c2eba5a974abc: target is busy.
        (In some cases useful info about processes that use
         the device is found by lsof(8) or fuser(1))
This volume seems busy.How can i delete this volume?

**Comment by iamniting** [comment]
heketi is not able to unmount a brick of a volume. Either glusterfs is having some lock on it or it is not able to release brick from the brick process. restarting glusterd should help you if you are running in standalone mode or restarting glusterfs container if containerised mode. We are not an expert of glusterfs, They will be able to help you better on this.

**Comment by phlogistonjohn** [comment]
Additionally, the 'lsof' command mentioned in the error message can tell you what process is preventing the brick filesystem from being unmounted. It could range from a gluster issue, as noted above, or some other process. I've seen cases where someone was debugging one issue and caused something like this by logging into the server and cd'ing into the brick mount dir.

**Comment by manisha-tanwar** [comment]
@un1xman check if PV still exists `kubectl get pv` 
if it does, deleting it should work. if it doesn't try lsof as suggested above.

**Comment by phlogistonjohn** [comment]
I'm triaging issues. The last comment on this issue is rather old so I'll be closing this item now.
