### ISSUE TITLE
heketi-cli cannot get the correct storage value

### ISSUE THREAD

**Issue by fei922** [heketi/heketi#1840]
### Kind of issue

> Bug

### Observed behavior
By executing the'heketi-cli topology info' command, you can see that the storage node has two disks vdc and vdd, and the available space is 0, but by calculating the size of the bricks, the storage only uses about 180G, why there is still space left , But it prompts that there is no more space available？

`
heketi-cli topology info
Cluster Id: b45429a01e18fe6adb49705494045020
    File:  true
    Block: true

    Volumes:

        Name: vol_017835213e1a4ca323d0ac1c0d36d480
        Size: 8
        Id: 017835213e1a4ca323d0ac1c0d36d480
        Cluster Id: b45429a01e18fe6adb49705494045020
        Mount: <nodeIP>:vol_017835213e1a4ca323d0ac1c0d36d480
        Mount Options: backup-volfile-servers=
        Durability Type: none
        Snapshot: Enabled
        Snapshot Factor: 1.00

                Bricks:
                        Id: dbd9d7c46f6972fcb0b07e2840b53acd
                        Path: /var/lib/heketi/mounts/vg_659d1825e5fa7e9cba5b5afc90f5f128/brick_dbd9d7c46f6972fcb0b07e2840b53acd/brick
                        Size (GiB): 8
                        Node: 29d9a1a08a31527a3e999a37fd10c47a
                        Device: 659d1825e5fa7e9cba5b5afc90f5f128

        <omit volumes>...
        
    Nodes:

        Node Id: 29d9a1a08a31527a3e999a37fd10c47a
        State: online
        Cluster Id: b45429a01e18fe6adb49705494045020
        Zone: 1
        Management Hostnames: <nodeIP>
        Storage Hostnames: <nodeIP>
        Devices:
                Id:1a96052dea2d8069a24e54b3b1045ba4   Name:/dev/vdc            State:online    Size (GiB):499     Used (GiB):499     Free (GiB):0
                        Bricks:
                                Id:08cdb338e91f9ded8aa4d5f415292e4d   Size (GiB):1       Path: /var/lib/heketi/mounts/vg_1a96052dea2d8069a24e54b3b1045ba4/brick_08cdb338e91f9ded8aa4d5f415292e4d/brick
                                Id:3820997c37bdbb7bcf70d225bec336b2   Size (GiB):5       Path: /var/lib/heketi/mounts/vg_1a96052dea2d8069a24e54b3b1045ba4/brick_3820997c37bdbb7bcf70d225bec336b2/brick
                                Id:3b7e52b961d64cd9300955f3423f2bc4   Size (GiB):1       Path: /var/lib/heketi/mounts/vg_1a96052dea2d8069a24e54b3b1045ba4/brick_3b7e52b961d64cd9300955f3423f2bc4/brick
                                Id:45d4aab880451283760b0d05b7aeb6b2   Size (GiB):10      Path: /var/lib/heketi/mounts/vg_1a96052dea2d8069a24e54b3b1045ba4/brick_45d4aab880451283760b0d05b7aeb6b2/brick
                                Id:4a9012d01f89708b3c8228ba95e8c7cb   Size (GiB):2       Path: /var/lib/heketi/mounts/vg_1a96052dea2d8069a24e54b3b1045ba4/brick_4a9012d01f89708b3c8228ba95e8c7cb/brick
                                Id:5bde8f34072454654d49fdd307b3f4e7   Size (GiB):1       Path: /var/lib/heketi/mounts/vg_1a96052dea2d8069a24e54b3b1045ba4/brick_5bde8f34072454654d49fdd307b3f4e7/brick
                                Id:73cbee9367883d62c088a7a9cbe81861   Size (GiB):2       Path: /var/lib/heketi/mounts/vg_1a96052dea2d8069a24e54b3b1045ba4/brick_73cbee9367883d62c088a7a9cbe81861/brick
                                Id:7a10749e2bc1a44e102f3d6f58a083f3   Size (GiB):3       Path: /var/lib/heketi/mounts/vg_1a96052dea2d8069a24e54b3b1045ba4/brick_7a10749e2bc1a44e102f3d6f58a083f3/brick
                                Id:883ce0398560c41c1b729919b8978238   Size (GiB):1       Path: /var/lib/heketi/mounts/vg_1a96052dea2d8069a24e54b3b1045ba4/brick_883ce0398560c41c1b729919b8978238/brick
                                Id:a83b2f7b7b8e258d56d8eece2994f42e   Size (GiB):1       Path: /var/lib/heketi/mounts/vg_1a96052dea2d8069a24e54b3b1045ba4/brick_a83b2f7b7b8e258d56d8eece2994f42e/brick
                                Id:b054ca78abb6a4b28c1e4f0797e167ff   Size (GiB):1       Path: /var/lib/heketi/mounts/vg_1a96052dea2d8069a24e54b3b1045ba4/brick_b054ca78abb6a4b28c1e4f0797e167ff/brick
                                Id:d801eb512bfebd7b8963ce663cdbc913   Size (GiB):3       Path: /var/lib/heketi/mounts/vg_1a96052dea2d8069a24e54b3b1045ba4/brick_d801eb512bfebd7b8963ce663cdbc913/brick
                                Id:e56d84f5c479d206e89f74ff56d44598   Size (GiB):1       Path: /var/lib/heketi/mounts/vg_1a96052dea2d8069a24e54b3b1045ba4/brick_e56d84f5c479d206e89f74ff56d44598/brick
                                Id:e7c618d1b0538171ce7cdce82ca269b1   Size (GiB):1       Path: /var/lib/heketi/mounts/vg_1a96052dea2d8069a24e54b3b1045ba4/brick_e7c618d1b0538171ce7cdce82ca269b1/brick
                                Id:f7b227549a0e227536049a649fe38540   Size (GiB):8       Path: /var/lib/heketi/mounts/vg_1a96052dea2d8069a24e54b3b1045ba4/brick_f7b227549a0e227536049a649fe38540/brick
                Id:659d1825e5fa7e9cba5b5afc90f5f128   Name:/dev/vdd            State:online    Size (GiB):499     Used (GiB):499     Free (GiB):0
                        Bricks:
                                Id:02d135e55d7edb84e252c505787e226a   Size (GiB):10      Path: /var/lib/heketi/mounts/vg_659d1825e5fa7e9cba5b5afc90f5f128/brick_02d135e55d7edb84e252c505787e226a/brick
                                Id:1457a2c762b8527690ea2d595afc4c90   Size (GiB):1       Path: /var/lib/heketi/mounts/vg_659d1825e5fa7e9cba5b5afc90f5f128/brick_1457a2c762b8527690ea2d595afc4c90/brick
                                Id:24d34b48896d81c5bf5ad8d1dc5e2136   Size (GiB):1       Path: /var/lib/heketi/mounts/vg_659d1825e5fa7e9cba5b5afc90f5f128/brick_24d34b48896d81c5bf5ad8d1dc5e2136/brick
                                Id:42d64408edad26f9487a54cde832bfeb   Size (GiB):20      Path: /var/lib/heketi/mounts/vg_659d1825e5fa7e9cba5b5afc90f5f128/brick_42d64408edad26f9487a54cde832bfeb/brick
                                Id:479ad50a74da2f94feec0802b1d89d9d   Size (GiB):10      Path: /var/lib/heketi/mounts/vg_659d1825e5fa7e9cba5b5afc90f5f128/brick_479ad50a74da2f94feec0802b1d89d9d/brick
                                Id:4d06b60baa180c9295a6ae84446bb9b3   Size (GiB):20      Path: /var/lib/heketi/mounts/vg_659d1825e5fa7e9cba5b5afc90f5f128/brick_4d06b60baa180c9295a6ae84446bb9b3/brick
                                Id:79cfb24b218ce0e7763a2fa972eb1ec6   Size (GiB):1       Path: /var/lib/heketi/mounts/vg_659d1825e5fa7e9cba5b5afc90f5f128/brick_79cfb24b218ce0e7763a2fa972eb1ec6/brick
                                Id:8c546b216de2fbe421c8a5aef63fe60d   Size (GiB):10      Path: /var/lib/heketi/mounts/vg_659d1825e5fa7e9cba5b5afc90f5f128/brick_8c546b216de2fbe421c8a5aef63fe60d/brick
                                Id:9c18874be99edeaaccfab9bf7776563f   Size (GiB):5       Path: /var/lib/heketi/mounts/vg_659d1825e5fa7e9cba5b5afc90f5f128/brick_9c18874be99edeaaccfab9bf7776563f/brick
                                Id:ba33d2eb53bb8ce71131c17b6cc1989e   Size (GiB):2       Path: /var/lib/heketi/mounts/vg_659d1825e5fa7e9cba5b5afc90f5f128/brick_ba33d2eb53bb8ce71131c17b6cc1989e/brick
                                Id:c988888b0252dd835d407974dc216e3d   Size (GiB):1       Path: /var/lib/heketi/mounts/vg_659d1825e5fa7e9cba5b5afc90f5f128/brick_c988888b0252dd835d407974dc216e3d/brick
                                Id:ce72d3ac14df57bbf8e95cf7618b0b63   Size (GiB):1       Path: /var/lib/heketi/mounts/vg_659d1825e5fa7e9cba5b5afc90f5f128/brick_ce72d3ac14df57bbf8e95cf7618b0b63/brick
                                Id:d22db0c218fe2dea567f844946e169fd   Size (GiB):5       Path: /var/lib/heketi/mounts/vg_659d1825e5fa7e9cba5b5afc90f5f128/brick_d22db0c218fe2dea567f844946e169fd/brick
                                Id:d38cefcf84c914457493f40769f35b12   Size (GiB):5       Path: /var/lib/heketi/mounts/vg_659d1825e5fa7e9cba5b5afc90f5f128/brick_d38cefcf84c914457493f40769f35b12/brick
                                Id:dbb6406293e5e8f4b9dd38044072808d   Size (GiB):1       Path: /var/lib/heketi/mounts/vg_659d1825e5fa7e9cba5b5afc90f5f128/brick_dbb6406293e5e8f4b9dd38044072808d/brick
                                Id:dbd9d7c46f6972fcb0b07e2840b53acd   Size (GiB):8       Path: /var/lib/heketi/mounts/vg_659d1825e5fa7e9cba5b5afc90f5f128/brick_dbd9d7c46f6972fcb0b07e2840b53acd/brick
                                Id:e7d0e82a977b6c91bbd90c34ed5727e2   Size (GiB):30      Path: /var/lib/heketi/mounts/vg_659d1825e5fa7e9cba5b5afc90f5f128/brick_e7d0e82a977b6c91bbd90c34ed5727e2/brick
                                Id:e8a53bc69e4d7a891b429ea9ce4b79b0   Size (GiB):5       Path: /var/lib/heketi/mounts/vg_659d1825e5fa7e9cba5b5afc90f5f128/brick_e8a53bc69e4d7a891b429ea9ce4b79b0/brick
                                Id:e98cf2c70a76af4ff5e7bc28a0c91348   Size (GiB):2       Path: /var/lib/heketi/mounts/vg_659d1825e5fa7e9cba5b5afc90f5f128/brick_e98cf2c70a76af4ff5e7bc28a0c91348/brick
`
### Expected/desired behavior
Execute the command ‘heketi-cli topology info’ to see the correct remaining space instead of 0

### Information about the environment:

- Heketi version used:  v6.0.0
- Operating system used:  CentOS Linux release 7.6.1810 (Core)
- Heketi compiled from sources, as a package (rpm/deb), or container:  Binary package

**Comment by phlogistonjohn** [comment]
I'm triaging issues.  I'm sorry that we were not able to respond in a timely manner. I can only recommend retrying with a more recent version. Due to the age of this issue I'll be closing it now.
