### ISSUE TITLE
如何创建Heketi集群

### ISSUE THREAD

**Issue by qinaichen** [heketi/heketi#1842]
如何创建一个Heketi集群，可以达到高可用的效果，即多个heketi服务访问同一份heketi.db数据

**Comment by phlogistonjohn** [comment]
Could you please restate your inquiry in English? Thanks.

**Comment by qinaichen** [comment]
how to make heketi cluster?

**Comment by phlogistonjohn** [comment]
There are some docs on installation that are linked off our [admin docs page](https://github.com/heketi/heketi/tree/master/docs/admin) they're fairly low level. Note that the exact steps are going to vary a bit depending on if you plan on running gluster in containers or directly on nodes.

I used to be able to recommend the gluster-kubernetes project for some install scenarios, but that project is no longer maintained. You could however look it its sources for ideas.

Do note that heketi is in maintenance mode and no new features are being added at this time.

**Comment by 20100507** [comment]
@phlogistonjohn After our test, as long as the clone operation is performed, there will be data inconsistencies. This makes us very confused and basically can’t use heketi

**Comment by phlogistonjohn** [comment]
I'm unclear what you mean by clone operation. Could you please elaborate? Thanks.

Also, I'm not sure if this is part of the original request that started this issue. If it is, no problem, if not, perhaps you may be better off creating a new issue. Thanks.

**Comment by 20100507** [comment]
@phlogistonjohn  this is issue https://github.com/heketi/heketi/issues/1843   when I exec heketi-cli volume clone volume-id operation.

**Comment by phlogistonjohn** [comment]
I'm triaging issues. This conversation has wound down so I'll be closing this issue now.
