### ISSUE TITLE
heketi db consistencies when exec clone

### ISSUE THREAD

**Issue by 20100507** [heketi/heketi#1843]
After our test, as long as the clone operation is performed, there will be data inconsistencies. This makes us very confused and basically can’t use heketi.

When I execute the db check command, it returns

`{
    "clusters": {
        "total": 1,
        "pending": 0,
        "ok": 0,
        "notok": 1,
        "inconsistencies": [
            "Cluster 4220dbe8d8398a6e6eeb81db6ef00b07 unknown volume 9f197f301351d1b3a4e0a91c0281abe8"
        ]
    },
    "volumes": {
        "total": 4,
        "pending": 0,
        "ok": 4,
        "notok": 0,
        "inconsistencies": null
    },
    "bricks": {
        "total": 7,
        "pending": 1,
        "ok": 4,
        "notok": 3,
        "inconsistencies": [
            "Brick 341d95f2c8ad9eaf317b0d0013143a0a marked pending but no pending op f0f7038785f344c66cd38ea1f851d937",
            "Brick 341d95f2c8ad9eaf317b0d0013143a0a unknown volume 9f197f301351d1b3a4e0a91c0281abe8",
            "Brick 11d48b0e2a75b48959bc04392fb48d07 no link back to brick from volume a9628dd64781fc3abf83e298ddcd2bf8",
            "Brick 1a79220c362e6a4b0cb9db9e4c70c213 no link back to brick from volume a9628dd64781fc3abf83e298ddcd2bf8"
        ]
    },
    "nodes": {
        "total": 5,
        "pending": 0,
        "ok": 5,
        "notok": 0,
        "inconsistencies": null
    },
    "devices": {
        "total": 35,
        "pending": 0,
        "ok": 34,
        "notok": 1,
        "inconsistencies": [
            "Device d23b5e47da5a982fc002d8df877cecca size values differ Used(12648448) != aggregateBricksSize(37945344)"
        ]
    },
    "blockvolumes": {
        "total": 0,
        "pending": 0,
        "ok": 0,
        "notok": 0,
        "inconsistencies": null
    },
    "dbattributes": {
        "total": 0,
        "pending": 0,
        "ok": 0,
        "notok": 0,
        "inconsistencies": null
    },
    "pendingoperations": {
        "total": 0,
        "pending": 0,
        "ok": 0,
        "notok": 0,
        "inconsistencies": null
    },
    "totalinconsistencies": 6
}`
Now I can't create the volume again, I can only view the volume.if I create vloume, it will be return.
**Error: Failed to allocate new volume: Id not found**

heketi version: release 10.02
opertion system: centos7.5
glusterfs version: 6.1
package type: Binary package from github.

This problem has troubled me for a long time. How can I quickly fix this problem? Don't affect the creation of the volume.

I exec heketi-cli --server http://xxxxx:8098 --user admin --secret xxxxxx server operations cleanup
The result has no effect. Still unable to create volume.

please help me~ thank you very much!!!

**Comment by phlogistonjohn** [comment]
OK, volume clone was never a well supported / fully complete feature but it shouldn't make the db inconsistent.

The db doesn't go inconsistent due to the operation alone in the test suite AFAICT.  Could you please do a heketi-cli db dump (to json)  before and after running the commands? Comparing the before and after state of the db may help determine what the issue is. Thanks.

**Comment by 20100507** [comment]
We no longer choose heketi, because he is very unstable, I closed this issue.
