### ISSUE TITLE
use localhost suc ,  use ip fail with 404.

### ISSUE THREAD

**Issue by dulm** [heketi/heketi#1844]
### Kind of issue

> Uncomment only one of these:
> 
Bug
> Feature request

### Observed behavior
when use localhost, it works fine.
```
[root@i-qoy2h7fd heketi]# curl http://localhost:8080/hello
Hello from Heketi
```

when use hostip or fqn, it fail.  but can `telnet server1 8080` suc.
```
[root@i-qoy2h7fd heketi]# curl http://server1:8080/hello
404 page not found
```

```
[root@i-qoy2h7fd heketi]# netstat -antp|grep 8080
tcp        0      0 10.42.0.1:52576         10.42.0.42:8080         TIME_WAIT   -                   
tcp        0      0 192.168.0.4:37590       10.43.6.21:8080         ESTABLISHED 21110/pushprox-clie 
tcp        0      0 192.168.0.4:54604       10.43.6.21:8080         ESTABLISHED 21110/pushprox-clie 
tcp        0      0 10.42.0.1:36196         10.42.0.72:8080         TIME_WAIT   -                   
tcp6       0      0 :::8080                 :::*                    LISTEN      972/heketi
```

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master):  Heketi v10.2.0
- Operating system used:  centos8
- Heketi compiled from sources, as a package (rpm/deb), or container:  https://github.com/heketi/heketi/releases/tag/v10.2.0
- If container, which container image:   
- Using kubernetes, openshift, or direct install:  direct install
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: 
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom):

**Comment by dulm** [comment]
i change  port from 8080 to 8083, then both url works fine!

**Comment by phlogistonjohn** [comment]
Odd, I see from that netstat that the server is binding to all interfaces on the port. So, normally you would expect that localhost or all other addresses on that host to behave the same way. If it didn't bind, I would then expect a TCP connections failure, not a 404 error. One thing that might be worth trying, to get additional information is to run the curl command with `-v` option so we can see headers, etc.

The only other guess I have is that either the node is redirecting packets from one port to a different service or the dns name is not actually resolving the way you expect it to. In both cases the -v option to curl could still help in the investigation.

PS. I was briefly confused by the term "suc" but I think you're using it as a shorthand for "success". If I'm wrong, please correct me.

**Comment by phlogistonjohn** [comment]
I'm triaging issues. I hope the last response was helpful. Due to the age of the issue I'm closing it now.
