### ISSUE TITLE
Questions about lvm volume provisoning 

### ISSUE THREAD

**Issue by kannanvr** [heketi/heketi#1847]
Hi
 we have created the lvm from device.  is it possible to provison the volume on lvm?

sdb            8:16   0   50G  0 disk
└─test-data 253:2    0   40G  0 lvm

we have added the device /dev/sdb. we created the vg as test and created the lvm as data
now we have created the glusterfs cluster with heketi as a provisoner. we have mentioned device as /dev/test/data and provisoned the heketi. now we are able to create the pvc and push the data.
but when we rebooted the node. it seems all the mounts were getting lost.

we have given as a lv path to provison the volume. but heketi is creating the vg on lvm and it is creating the volume. 
is it correct to provison the volume on lv rather than device.?
please provide your comments.

Thanks,
Kannan V

**Comment by phlogistonjohn** [comment]
> Hi
> we have created the lvm from device. is it possible to provison the volume on lvm?
> 

You might be able to finagle it to work, but we don't recommend it.


> sdb 8:16 0 50G 0 disk
> └─test-data 253:2 0 40G 0 lvm
> 
> we have added the device /dev/sdb. we created the vg as test and created the lvm as data
> now we have created the glusterfs cluster with heketi as a provisoner. we have mentioned device as /dev/test/data and provisoned the heketi. now we are able to create the pvc and push the data.
> but when we rebooted the node. it seems all the mounts were getting lost.
> 

As you note here, Heketi itself doesn't have an issue creating new logical volumes even if given an lv. The issue you're seeing is likely related to the OS boot process & lvm itself not handling "nested" lvm well. In theory, you could try to ensure that the "outer" LVs are activated by lvm and then ensure the "inner" LVs are activated after. But none of that's anything that heketi has any control over. It boils down to needing to ensure the entries that heketi adds to the mounts file are activated, started, and mounted before gluster does.


> we have given as a lv path to provison the volume. but heketi is creating the vg on lvm and it is creating the volume.
> is it correct to provison the volume on lv rather than device.?
> please provide your comments.
> 
> Thanks,
> Kannan V

Given all the above, I certainly don't recommend using an existing LVM lv if you can. Just give heketi an empty raw block device. Heketi always creates thin lvs on a device which is set as a vg, there is no other mode.

**Comment by kannanvr** [comment]
@phlogistonjohn , Thanks for your reply.  one last question..
Is it recommended to use loopback-device  ?

i have below command to create the loopback-device 

```
#!/bin/sh
mkdir -p /opt/glusterfs
truncate -s 80G /opt/glusterfs/backenddisk
losetup /dev/loop0 /opt/glusterfs/backenddisk
```

**Comment by phlogistonjohn** [comment]
It will be somewhat similar to the lvm case depending on how your OS/distro mounts volumes from fstab. Assuming it's systemd, there's a mount target responsible for reading from /etc/fstab and mounting everything. If the loopback file is not available already, for example its on a file system that is not yet mounted, its possible it will fail to mount all the gluster bricks.

You are really better off a standard locally attached block device (disk). We never tested with anything else. 

FWIW, There is a config parameter "mountopts" (aka HEKETI_MOUNT_OPTS env var) you can use to customize the mount options saved into fstab. However, I have not experimented much with that personally. It could allow you to pass args to the mount subsystem to control ordering, but I can only say ithat its not heavily tested so you use it at your own risk.

**Comment by phlogistonjohn** [comment]
I'm triaging issues.  It appears that this conversation has wound down, and due to the age of this issue I'll be closing it now.
