### ISSUE TITLE
Equivalent heketi-cli command for gluster volume status <vol> clients

### ISSUE THREAD

**Issue by manisha-tanwar** [heketi/heketi#1849]
### Kind of issue

> Uncomment only one of these:
> 
> Bug
> Feature request

### Observed behavior
 `heketi-cli volume clients`
There's not such heketi-cli command. 

and heketi-cli volume info doesn't show what all clients are connected to it.

### Expected/desired behavior
There should be some command like `heketi-cli volume clients` equivalent to `gluster volume status <vol> clients`

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): v10.2.0
- Operating system used: CentOS
- Heketi compiled from sources, as a package (rpm/deb), or container: container
- If container, which container image: heketi:dev
- Using kubernetes, openshift, or direct install: Kubernetes
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: outside
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): gk-deploy

### Other useful information
It would be very useful if this command can be made available if it's not yet.

**Comment by phlogistonjohn** [comment]
I appreciate your interest in heketi, however heketi is in maintenance mode and not accepting new features.
