### ISSUE TITLE
Invalid qsh claim in token

### ISSUE THREAD

**Issue by manisha-tanwar** [heketi/heketi#1853]
### Kind of issue
Bug

### Observed behavior
heketi-cli works fine and everything working as expected but when I try to follow this https://github.com/heketi/heketi/blob/master/docs/api/api.md#python-example to use API call, I get below error:
```
curl -sk -H "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJhZG1pbiIsImlhdCI6MTYyMDM4MjgzMCwiZXhwIjoxNjIwMzgzMTMwLCJxc2giOiJjMTYyYWNjOTAyNDI3MjEyMGJhY2ZmZjc3MDljOTMyY2MyNTIzMzdkMGEzMGZhMTViMDI1MDEwMDY2NjYyYmVhIn0.-z9AmbFdau4tkzzAqQbHXx4caGV6ZcUtvNiI8t9OqNc" https://heketi.io.local
Invalid qsh claim in token
```

However I can decode above token using https://jwt.io/ and `jwt.decode`

### Expected/desired behavior
curl command should return volume list

### Details on how to reproduce (minimal and precise)
Setup heketi & generate token following https://github.com/heketi/heketi/blob/master/docs/api/api.md#python-example
```
  ~ $ cat heketi_token.py
import jwt
import datetime
import hashlib

method = 'GET'
uri = '/volumes'
secret = 'SOME_PASSWORD'

claims = {}

# Issuer
claims['iss'] = 'admin'

# Issued at time
claims['iat'] = datetime.datetime.utcnow()

# Expiration time
claims['exp'] = datetime.datetime.utcnow() \
	+ datetime.timedelta(minutes=5)

# URI tampering protection
claims['qsh'] = hashlib.sha256((method + '&' + uri).encode('utf-8')).hexdigest()

print(jwt.encode(claims, secret, algorithm='HS256'))
#jw_en = jwt.encode(claims, secret, algorithm='HS256')
#print(jwt.decode(jw_en,'SOME_PASSWORD'))
```

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): Heketi v10.0.0-57-g69b52677
- Operating system used:
- Heketi compiled from sources, as a package (rpm/deb), or container: container
- If container, which container image: heketi:dev
- Using kubernetes, openshift, or direct install: kubernetes
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: outside
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): gk-deploy

### Other useful information
I'd to change `claims['qsh'] = hashlib.sha256(method + '&' + uri).hexdigest()` to `claims['qsh'] = hashlib.sha256((method + '&' + uri).encode('utf-8')).hexdigest()` as it was giving error:
```
Traceback (most recent call last):
  File "heketi_token.py", line 22, in <module>
    claims['qsh'] = hashlib.sha256(method + '&' + uri).hexdigest()
TypeError: Unicode-objects must be encoded before hashing
```

Am I missing anything here? Do I need to enable to use API:
```
"_use_auth": "Enable JWT authorization. Please enable for deployment",
"use_auth": false,
```

**Comment by phlogistonjohn** [comment]
I am guessing this example is out of date. I didn't even realize it was there. We have python libraries in the tree. Could you you try the code in `client/api/python`?  Thanks.

**Comment by phlogistonjohn** [comment]
"use_auth" does nothing in recentish verisons of heketi

**Comment by phlogistonjohn** [comment]
Good to hear, thanks. I think I shall remove the misleading documentation so that others don't get tripped up by it in the future.

**Comment by manisha-tanwar** [comment]
@phlogistonjohn unfortunately it doesn't work with python3
