### ISSUE TITLE
The process of heketi has a high CPU usage

### ISSUE THREAD

**Issue by shiune** [heketi/heketi#1856]
### Observed behavior
The environment is containerized deployment of heketi and glusterfs. Use the top command to view the process of heketi. The value of %CPU appears once in about 2 minutes. The value of %CPU is 4000 and above, which occupies more than 40 cores of CPU.

### Information about the environment:

The environment is containerized deployment of heketi and glusterfs.

### Other useful information
Regularly check whether the glusterd service may cause this problem. From the point of time, most of them are before and after checking the status of glusterd

**Comment by phlogistonjohn** [comment]
I'm triaging issues. I'm sorry that we were unable to reply to this in a timely manner. However, due to the age of this issue I'll be closing it now.
