### ISSUE TITLE
TypeError: can't concat str to bytes using python3 

### ISSUE THREAD

**Issue by manisha-tanwar** [heketi/heketi#1858]
### Kind of issue
 Bug

### Observed behavior
Not able to use python api client with v3.

Works fine with python2.
```
python volume_create.py
Creating a volume
('Volume created successfully:\n', 'id: ', u'71855f28a2a1e3844ff5241c6ff8a05f', '\n', 'name: ', u'test', '\n', 'size: ', 1, 'G\n', 'mount_path:', u'10.12.51.67:test', ', backup-volfile-servers: ', u'10.12.51.66,10.12.51.65')
.
----------------------------------------------------------------------
Ran 1 test in 4.538s

OK
```

While it gives error with python3
```
~ # python3 volume_create.py
Creating a volume
E
======================================================================
ERROR: test_volume (__main__.test_heketi)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "volume_create.py", line 62, in test_volume
    volume = c.volume_create(volume_req)
  File "/usr/local/lib/python3.6/site-packages/heketi_driver-0.0.0-py3.6.egg/heketi/heketi.py", line 231, in volume_create
    req = self._make_request('POST', uri, volume_options)
  File "/usr/local/lib/python3.6/site-packages/heketi_driver-0.0.0-py3.6.egg/heketi/heketi.py", line 76, in _make_request
    headers.update(self._set_token_in_header(method, uri))
  File "/usr/local/lib/python3.6/site-packages/heketi_driver-0.0.0-py3.6.egg/heketi/heketi.py", line 58, in _set_token_in_header
    headers['Authorization'] = b'bearer ' + token
TypeError: can't concat str to bytes

----------------------------------------------------------------------
Ran 1 test in 0.004s

FAILED (errors=1)
```

### Expected/desired behavior
volume created with python3 

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): Heketi v10.0.0-57-g69b52677
- Operating system used:
- Heketi compiled from sources, as a package (rpm/deb), or container: container
- If container, which container image: heketi:dev
- Using kubernetes, openshift, or direct install: kubernetes
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: outside
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): gk-deploy

### Other useful information

This is my python code:
```
~ # grep -v ^# volume_create.py
import unittest
import requests
import heketi
from heketi import HeketiClient

TEST_ADMIN_KEY = "SOME_PASSWORD"
TEST_SERVER = "<Heketi-Server>"

class test_heketi(unittest.TestCase):

    def test_volume(self):
        # Create cluster
        c = HeketiClient(TEST_SERVER, "admin", TEST_ADMIN_KEY)
        self.assertEqual(True, c != '')

        # Create a volume
        print ("Creating a volume")
        cluster = 'ad45b304f171b9d0831bd6efe02fee00'
        volume_req = {}
        volume_req['size'] = 1
        volume_req['name'] = 'vol_test'
        volume_req['clusters'] = [cluster]
        volume = c.volume_create(volume_req)

        print('Volume created successfully:\n','id: ',volume['id'],'\n','name: ',volume['name'],'\n','size: ',volume['size'],'G\n','mount_path:',volume['mount']['glusterfs']['device'], ', backup-volfile-servers: ',volume['mount']['glusterfs']['options']['backup-volfile-servers'])


if __name__ == '__main__':
    unittest.main()
```

**Comment by manisha-tanwar** [comment]
Also I installed `python-heketi` package for python2 where heketi.py file is different and seems like using steps mentioned in old api doc and modified in this PR:

https://github.com/heketi/heketi/pull/930/files#diff-8de60fa0556fc695724dce431a33e14ccbe38e3f91136a42d496dba5fd3944f5

**Comment by phlogistonjohn** [comment]
I think that we don't support all versions of the jwt library. I think @iamniting may remember what versions we support as I think he fixed it in our test suite.

**Comment by iamniting** [comment]
Here is a PR which locks jwt to "pyjwt >= 1.4.0, < 2.0.0" 
https://github.com/heketi/heketi/pull/1830

We do not support pyjwt 3**

**Comment by manisha-tanwar** [comment]
Hi, 
I converted token to bytes and replaced `verify='False'` to `verify='/etc/ssl/certs/ca-certificates.crt' in heketi/heketi.py. 
And that resolved the issue.
Is there anything wrong with this approach?

**Comment by iamniting** [comment]
I don't think that you need to replace `verify` flag as when I was fixing tests on py3 just converting token worked for me. 

I have not really explored a pyclient so no idea if it can break something or not.

**Comment by manisha-tanwar** [comment]
Idk I was getting errors like this, if I don't mention it. 
```
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:877)
```

Also I didn't install pyjwt or any other jwt package.
