### ISSUE TITLE
Error: Failed to allocate new volume: No space

### ISSUE THREAD

**Issue by handrea2009** [heketi/heketi#1860]
### Kind of issue
Bug

### Observed behavior
Creation of volume fails immediately returning "No space", although there's plenty of free space in the topology

kubectl exec -it heketi-58f8f8686b-hwnm7 -- heketi-cli --user admin --secret fVF6DkOh089B volume create --name=cache --size=97000 --gluster-volume-options="performance.write-behind off","performance.open-behind off" --replica=3
Error: Failed to allocate new volume: No space

I can successfully create volume 89000Gb, but in this case one of the available disk in the topology is not used
It's a 3 node cluster and I have 9 disks per node, 11175Gb of free space on each disk, so it has enough space to create a 97000Gb volume.

The "max_bricks_per_volume" is set to 60, and "brick_max_size_gb" is set to 20240
The logs are pretty useless:

[heketi] INFO 2021/05/24 13:11:30 Allocating brick set #0
[heketi] INFO 2021/05/24 13:11:30 Allocating brick set #0
[heketi] INFO 2021/05/24 13:11:30 Allocating brick set #1
[heketi] INFO 2021/05/24 13:11:30 Allocating brick set #2
[heketi] INFO 2021/05/24 13:11:30 Allocating brick set #3
[heketi] INFO 2021/05/24 13:11:30 Allocating brick set #4
[heketi] INFO 2021/05/24 13:11:30 Allocating brick set #5
[heketi] INFO 2021/05/24 13:11:30 Allocating brick set #6
[heketi] INFO 2021/05/24 13:11:30 Allocating brick set #7
[heketi] INFO 2021/05/24 13:11:30 Allocating brick set #8
[heketi] INFO 2021/05/24 13:11:30 Allocating brick set #9
[heketi] ERROR 2021/05/24 13:11:30 heketi/apps/glusterfs/operations_manage.go:220:glusterfs.AsyncHttpOperation: Create Volume Build Failed: No space

Below my topology info:

Cluster Id: 45acc01abb97cd46447db2ded3f82b98

    File:  true
    Block: true

    Volumes:

        Name: heketidbstorage
        Size: 2
        Id: 2b6d63d36a9167e82f7ccae8b2dfd698
        Cluster Id: 45acc01abb97cd46447db2ded3f82b98
        Mount: 10.50.50.51:heketidbstorage
        Mount Options: backup-volfile-servers=10.50.50.52,10.50.50.53
        Durability Type: replicate
        Replica: 3
        Snapshot: Disabled

                Bricks:
                        Id: b08b606820a8a71adea8e06a286426ba
                        Path: /var/lib/heketi/mounts/vg_e81f8293056b6061fdabcc9400b449b6/brick_b08b606820a8a71adea8e06a286426ba/brick
                        Size (GiB): 2
                        Node: 9247fe9b635dbd2d67255adf4387f619
                        Device: e81f8293056b6061fdabcc9400b449b6

                        Id: c033d38579aa6df1deb48896cb73df11
                        Path: /var/lib/heketi/mounts/vg_e3eff70a82ac4fbe9dbde4ec76e2a209/brick_c033d38579aa6df1deb48896cb73df11/brick
                        Size (GiB): 2
                        Node: c95293424d0bf4d919f7c95e88e43080
                        Device: e3eff70a82ac4fbe9dbde4ec76e2a209

                        Id: c3c98b5fd02c1d89f18f01119a0cb96c
                        Path: /var/lib/heketi/mounts/vg_fe47eccdfee986574995c1912e50c0b8/brick_c3c98b5fd02c1d89f18f01119a0cb96c/brick
                        Size (GiB): 2
                        Node: 206c0fafc55e509d9e762e1d3af4028e
                        Device: fe47eccdfee986574995c1912e50c0b8

    Nodes:

        Node Id: 206c0fafc55e509d9e762e1d3af4028e
        State: online
        Cluster Id: 45acc01abb97cd46447db2ded3f82b98
        Zone: 1
        Management Hostnames: appliance1
        Storage Hostnames: 10.50.50.51
        Devices:
                Id:37b9f6bc6bc05975d33dfea25d0743d7   Name:/dev/sdk            State:online    Size (GiB):11175   Used (GiB):0       Free (GiB):11175
                        Bricks:
                Id:73ca484d04de8149d2276da5499cd460   Name:/dev/sdi            State:online    Size (GiB):11175   Used (GiB):0       Free (GiB):11175
                        Bricks:
                Id:8a5ab1c89a18e33bfd90fbd90201ab62   Name:/dev/sdf            State:online    Size (GiB):11175   Used (GiB):0       Free (GiB):11175
                        Bricks:
                Id:9db5302583d8ed09b8aa4c1d37bcb447   Name:/dev/sdg            State:online    Size (GiB):11175   Used (GiB):0       Free (GiB):11175
                        Bricks:
                Id:c05aa2bd1a0779c1943b59d11ec92b16   Name:/dev/sdj            State:online    Size (GiB):11175   Used (GiB):0       Free (GiB):11175
                        Bricks:
                Id:e0fc2f9b433ef625d51286bc9beb8a5a   Name:/dev/sdd            State:online    Size (GiB):11175   Used (GiB):0       Free (GiB):11175
                        Bricks:
                Id:e8adbae2e0c10ae575d5834dc3fefa37   Name:/dev/sdc            State:online    Size (GiB):11175   Used (GiB):0       Free (GiB):11175
                        Bricks:
                Id:fa0364b5cba2904d6a12dab7f735e14a   Name:/dev/sde            State:online    Size (GiB):11175   Used (GiB):0       Free (GiB):11175
                        Bricks:
                Id:fe47eccdfee986574995c1912e50c0b8   Name:/dev/sdh            State:online    Size (GiB):11175   Used (GiB):2       Free (GiB):11173
                        Bricks:
                                Id:c3c98b5fd02c1d89f18f01119a0cb96c   Size (GiB):2       Path: /var/lib/heketi/mounts/vg_fe47eccdfee986574995c1912e50c0b8/brick_c3c98b5fd02c1d89f18f01119a0cb96c/brick

        Node Id: 9247fe9b635dbd2d67255adf4387f619
        State: online
        Cluster Id: 45acc01abb97cd46447db2ded3f82b98
        Zone: 1
        Management Hostnames: appliance2
        Storage Hostnames: 10.50.50.52
        Devices:
                Id:06b076a698ad1fd5d9b0e984eb728c5a   Name:/dev/sde            State:online    Size (GiB):11175   Used (GiB):0       Free (GiB):11175
                        Bricks:
                Id:2bedfd2b3ea51d5bdd1e066c8dc06aa3   Name:/dev/sdf            State:online    Size (GiB):11175   Used (GiB):0       Free (GiB):11175
                        Bricks:
                Id:7ea019ebc4a1d145a96dd2cec9ab70f7   Name:/dev/sdk            State:online    Size (GiB):11175   Used (GiB):0       Free (GiB):11175
                        Bricks:
                Id:95b3a58ea38133358ea90fcf457b6021   Name:/dev/sdd            State:online    Size (GiB):11175   Used (GiB):0       Free (GiB):11175
                        Bricks:
                Id:b7ff92c609f0175661cf8f0d052bd0f6   Name:/dev/sdh            State:online    Size (GiB):11175   Used (GiB):0       Free (GiB):11175
                        Bricks:
                Id:bda3a69ffab1c38a48c265a91ac9bbfa   Name:/dev/sdj            State:online    Size (GiB):11175   Used (GiB):0       Free (GiB):11175
                        Bricks:
                Id:bdfa416ee360d6fc9ef724aadeb442b0   Name:/dev/sdi            State:online    Size (GiB):11175   Used (GiB):0       Free (GiB):11175
                        Bricks:
                Id:d1caffa4356c6802bc684ffd03271fc7   Name:/dev/sdc            State:online    Size (GiB):11175   Used (GiB):0       Free (GiB):11175
                        Bricks:
                Id:e81f8293056b6061fdabcc9400b449b6   Name:/dev/sdg            State:online    Size (GiB):11175   Used (GiB):2       Free (GiB):11173
                        Bricks:
                                Id:b08b606820a8a71adea8e06a286426ba   Size (GiB):2       Path: /var/lib/heketi/mounts/vg_e81f8293056b6061fdabcc9400b449b6/brick_b08b606820a8a71adea8e06a286426ba/brick

        Node Id: c95293424d0bf4d919f7c95e88e43080
        State: online
        Cluster Id: 45acc01abb97cd46447db2ded3f82b98
        Zone: 1
        Management Hostnames: appliance3
        Storage Hostnames: 10.50.50.53
        Devices:
                Id:1500eb46b7d30f50dff840c936132bbb   Name:/dev/sdk            State:online    Size (GiB):11175   Used (GiB):0       Free (GiB):11175
                        Bricks:
                Id:1e9545f3ee21fb6c059bf01ac70c54d2   Name:/dev/sdc            State:online    Size (GiB):11175   Used (GiB):0       Free (GiB):11175
                        Bricks:
                Id:33ffd8f81dfce54518351baa35daf100   Name:/dev/sdh            State:online    Size (GiB):11175   Used (GiB):0       Free (GiB):11175
                        Bricks:
                Id:44f5387e8a66c1ff222ccde3d90f0972   Name:/dev/sde            State:online    Size (GiB):11175   Used (GiB):0       Free (GiB):11175
                        Bricks:
                Id:8bfaf318962b34a28819cc5cbf1cfd7d   Name:/dev/sdf            State:online    Size (GiB):11175   Used (GiB):0       Free (GiB):11175
                        Bricks:
                Id:9ce4f4f1e4fe70ef71edf6b3a1bcf2b4   Name:/dev/sdg            State:online    Size (GiB):11175   Used (GiB):0       Free (GiB):11175
                        Bricks:
                Id:b9281750153f3ba7c8ea00522acaf455   Name:/dev/sdi            State:online    Size (GiB):11175   Used (GiB):0       Free (GiB):11175
                        Bricks:
                Id:dfb1b70126255d76c3c29651ee34a795   Name:/dev/sdd            State:online    Size (GiB):11175   Used (GiB):0       Free (GiB):11175
                        Bricks:
                Id:e3eff70a82ac4fbe9dbde4ec76e2a209   Name:/dev/sdj            State:online    Size (GiB):11175   Used (GiB):2       Free (GiB):11173
                        Bricks:
                                Id:c033d38579aa6df1deb48896cb73df11   Size (GiB):2       Path: /var/lib/heketi/mounts/vg_e3eff70a82ac4fbe9dbde4ec76e2a209/brick_c033d38579aa6df1deb48896cb73df11/brick

### Information about the environment:

- Heketi version  v10.0.0-57
- Operating system used: Ubuntu 20.04
- Heketi  run in container
- Kubernetes 
- Gluster is running as a daemon-set

**Comment by handrea2009** [comment]
I have enabled the debug log_level, and it seems evident what it's trying:

1st attempt: num_bricks = 24, so the brick size is 12713984000=12125Gb, which can't fit in the 11175Gb disk free space 
2nd attempt: num_bricks = 48, so the brick size is  6356992000 = 6062.5Gb, and it can't fit two of such bricks in the 11175Gb disk free space
3rd attempt: num_bricks = 96, which fail cause "max_bricks_per_volume" is set to 60

So question is: how is selected the num_bricks for the first an next attempts?

[heketi] DEBUG 2021/05/24 14:56:36 heketi/apps/glusterfs/volume_entry.go:605:glusterfs.(*VolumeEntry).createVolumeComponents: Using the following clusters: [45acc01abb97cd46447db2ded3f82b98]
[heketi] DEBUG 2021/05/24 14:56:36 heketi/apps/glusterfs/volume_entry_allocate.go:43:glusterfs.(*VolumeEntry).allocBricksInCluster: brick_size = 12713984000
[heketi] DEBUG 2021/05/24 14:56:36 heketi/apps/glusterfs/volume_entry_allocate.go:44:glusterfs.(*VolumeEntry).allocBricksInCluster: sets = 8
[heketi] DEBUG 2021/05/24 14:56:36 heketi/apps/glusterfs/volume_entry_allocate.go:45:glusterfs.(*VolumeEntry).allocBricksInCluster: num_bricks = 24
[heketi] INFO 2021/05/24 14:56:36 Allocating brick set #0
[heketi] DEBUG 2021/05/24 14:56:36 heketi/apps/glusterfs/brick_allocate.go:250:glusterfs.populateBrickSet: 0 / 3
[heketi] DEBUG 2021/05/24 14:56:36 heketi/apps/glusterfs/device_entry.go:378:glusterfs.(*DeviceEntry).SpaceNeeded: expected space needed for amount=12713984000 snapFactor=1 : 12730761216
[heketi] DEBUG 2021/05/24 14:56:36 heketi/apps/glusterfs/device_entry.go:335:glusterfs.(*DeviceEntry).NewBrickEntry: device e8adbae2e0c10ae575d5834dc3fefa37[11718750208] > required size [12730761216] 

[heketi] DEBUG 2021/05/24 14:56:36 heketi/apps/glusterfs/volume_entry_allocate.go:56:glusterfs.(*VolumeEntry).allocBricksInCluster: No space, re-trying with smaller brick size
[heketi] DEBUG 2021/05/24 14:56:36 heketi/apps/glusterfs/volume_entry_allocate.go:43:glusterfs.(*VolumeEntry).allocBricksInCluster: brick_size = 6356992000
[heketi] DEBUG 2021/05/24 14:56:36 heketi/apps/glusterfs/volume_entry_allocate.go:44:glusterfs.(*VolumeEntry).allocBricksInCluster: sets = 16
[heketi] DEBUG 2021/05/24 14:56:36 heketi/apps/glusterfs/volume_entry_allocate.go:45:glusterfs.(*VolumeEntry).allocBricksInCluster: num_bricks = 48
[heketi] INFO 2021/05/24 14:56:36 Allocating brick set #0
[heketi] DEBUG 2021/05/24 14:56:36 heketi/apps/glusterfs/brick_allocate.go:250:glusterfs.populateBrickSet: 0 / 3
[heketi] DEBUG 2021/05/24 14:56:36 heketi/apps/glusterfs/device_entry.go:378:glusterfs.(*DeviceEntry).SpaceNeeded: expected space needed for amount=6356992000 snapFactor=1 : 6373769216
[heketi] DEBUG 2021/05/24 14:56:36 heketi/apps/glusterfs/device_entry.go:335:glusterfs.(*DeviceEntry).NewBrickEntry: device d1caffa4356c6802bc684ffd03271fc7[11718750208] > required size [6373769216] ?
[heketi] DEBUG 2021/05/24 14:56:36 heketi/apps/glusterfs/brick_allocate.go:250:glusterfs.populateBrickSet: 1 / 3
[heketi] DEBUG 2021/05/24 14:56:36 heketi/apps/glusterfs/device_entry.go:378:glusterfs.(*DeviceEntry).SpaceNeeded: expected space needed for amount=6356992000 snapFactor=1 : 6373769216
[heketi] DEBUG 2021/05/24 14:56:36 heketi/apps/glusterfs/device_entry.go:335:glusterfs.(*DeviceEntry).NewBrickEntry: device dfb1b70126255d76c3c29651ee34a795[11718750208] > required size [6373769216] ?
[heketi] DEBUG 2021/05/24 14:56:36 heketi/apps/glusterfs/brick_allocate.go:250:glusterfs.populateBrickSet: 2 / 3
[heketi] DEBUG 2021/05/24 14:56:36 heketi/apps/glusterfs/device_entry.go:378:glusterfs.(*DeviceEntry).SpaceNeeded: expected space needed for amount=6356992000 snapFactor=1 : 6373769216
[heketi] DEBUG 2021/05/24 14:56:36 heketi/apps/glusterfs/device_entry.go:335:glusterfs.(*DeviceEntry).NewBrickEntry: device fa0364b5cba2904d6a12dab7f735e14a[11718750208] > required size [6373769216] ?
[heketi] INFO 2021/05/24 14:56:36 Allocating brick set #1
[heketi] DEBUG 2021/05/24 14:56:36 heketi/apps/glusterfs/brick_allocate.go:250:glusterfs.populateBrickSet: 0 / 3
[heketi] DEBUG 2021/05/24 14:56:36 heketi/apps/glusterfs/device_entry.go:378:glusterfs.(*DeviceEntry).SpaceNeeded: expected space needed for amount=6356992000 snapFactor=1 : 6373769216
[heketi] DEBUG 2021/05/24 14:56:36 heketi/apps/glusterfs/device_entry.go:335:glusterfs.(*DeviceEntry).NewBrickEntry: device d1caffa4356c6802bc684ffd03271fc7[5344980992] > required size [6373769216] ?
[heketi] DEBUG 2021/05/24 14:56:36 heketi/apps/glusterfs/brick_allocate.go:203:glusterfs.tryAllocateBrickOnDevice: Unable to place a brick of size 6356992000 & factor 1 on device d1caffa4356c6802bc684ffd03271fc7

[heketi] DEBUG 2021/05/24 14:56:36 heketi/apps/glusterfs/volume_entry_allocate.go:502:glusterfs.(*VolumeEntry).allocBricks.func1: Error detected.  Cleaning up volume 374fa68824a3aa60f5f7a539e7b3fc15: Len(0)
[heketi] DEBUG 2021/05/24 14:56:36 heketi/apps/glusterfs/volume_entry_allocate.go:56:glusterfs.(*VolumeEntry).allocBricksInCluster: No space, re-trying with smaller brick size
[heketi] DEBUG 2021/05/24 14:56:36 heketi/apps/glusterfs/volume_entry_allocate.go:43:glusterfs.(*VolumeEntry).allocBricksInCluster: brick_size = 3178496000
[heketi] DEBUG 2021/05/24 14:56:36 heketi/apps/glusterfs/volume_entry_allocate.go:44:glusterfs.(*VolumeEntry).allocBricksInCluster: sets = 32
[heketi] DEBUG 2021/05/24 14:56:36 heketi/apps/glusterfs/volume_entry_allocate.go:45:glusterfs.(*VolumeEntry).allocBricksInCluster: num_bricks = 96
[heketi] DEBUG 2021/05/24 14:56:36 heketi/apps/glusterfs/volume_entry_allocate.go:49:glusterfs.(*VolumeEntry).allocBricksInCluster: Maximum number of bricks reached
[heketi] DEBUG 2021/05/24 14:56:36 heketi/apps/glusterfs/volume_entry.go:488:glusterfs.(*VolumeEntry).tryAllocateBricks: Cluster 45acc01abb97cd46447db2ded3f82b98 can not accommodate volume (Maximum number of bricks reached.), trying next cluster
[heketi] ERROR 2021/05/24 14:56:36 heketi/apps/glusterfs/operations_manage.go:220:glusterfs.AsyncHttpOperation: Create Volume Build Failed: No space
[negroni] 2021-05-24T14:56:36Z | 500 |   49.94611ms | localhost:8080 | POST /volumes

**Comment by handrea2009** [comment]
I had a look ate source code and it seems it uses sequence of *2 (that is 2, 4, 8,...)
In my disks topology unfortunately the best config would have been  num_bricks = 27, which is not tried at all

**Comment by phlogistonjohn** [comment]
I'm triaging issues. I'm sorry we were unable to respond in a timely manner, but heketi is in maintenance status. Due to the age of this issue I'll be closing it now.
