### ISSUE TITLE
Migrating to travis-ci.com

### ISSUE THREAD

**Issue by pooja0805** [heketi/heketi#1862]
As shown on [travis-ci.org](http://travis-ci.org/), no new builds are running since June 15th, 2021. Do we have any plans to migrate the repository to [travis-ci.com](http://travis-ci.com/)? This is important for architectures like s390x which have CI support through Travis only.

**Comment by phlogistonjohn** [comment]
I personally have no plans to set up any replacement to travis ci. I appreciate your interest in this architecture but I do not think the team has the ability to do any more than maintain the existing centos ci and github actions, both are x86.

We would certainly consider contributions in this area, but I don't think the maintenance team has the time to chase the changes at travis or maintain a 3rd CI.

**Comment by pooja0805** [comment]
@phlogistonjohn Thank you for your response. We are ready to help in keeping the s390x builds running in the CI. If needed, only s390x can run on Travis. 
We will need your help to migrate to travis-ci.com though. Migration can be finished quickly, these links are helpful: [1](https://docs.travis-ci.com/user/migrate/open-source-repository-migration#the-migration-steps), [2](https://travis-ci.community/t/how-to-migrate-from-org-to-com-in-the-light-of-org-shutting-down/10566)

Please let us know if we can help in any way.

**Comment by pooja0805** [comment]
@phlogistonjohn Any updates on this?

**Comment by phlogistonjohn** [comment]
Hi, unfortunately the heketi maintenance team doesn't really have the bandwidth to manage more CI infrastructure. My suggestion is that you create a new github (or any hosting site you prefer) repo to integrate with a CI that supports s390. Then your repo would be set up to run scripts/tests based on heketi repo - but not within the heketi repo.

I hope you understand.

**Comment by pooja0805** [comment]
@phlogistonjohn Thanks for responding. We understand your concern.

**Comment by pooja0805** [comment]
@phlogistonjohn While we explore more on the approach you suggested above, we were also exploring we can add s390x builders to existing CentOS CI. The issue link is https://github.com/heketi/heketi/issues/1866
