### ISSUE TITLE
Error: Failed to allocate new volume: Cluster does not support requested volume type

### ISSUE THREAD

**Issue by yingjunxu** [heketi/heketi#1865]
### Kind of issue
> Bug

### Observed behavior
[root@csvz13-nrgl72 ~]# heketi-cli --user admin --secret admin --server http://20.26.208.81:8080 volume create --name=xyj --replica=2 --size=1 --clusters=d03c49ceeea31aed3b48bb4b51f3b092
Error: Failed to allocate new volume: Cluster does not support requested volume type

### Expected/desired behavior
volume create success

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): heketi-cli 9.0.0
- Operating system used: CentOS Linux release 7.6.1810 (Core) 
- Heketi compiled from sources, as a package (rpm/deb), or container:  sources (yum install)
- If container, which container image: 
- Using kubernetes, openshift, or direct install: 
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: 
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): 

### Other useful information

[root@csvz13-nrgl72 ~]# heketi-cli --user admin --secret admin --server http://20.26.208.81:8080 topology info

Cluster Id: d03c49ceeea31aed3b48bb4b51f3b092

    File:  false
    Block: true

    Volumes:

    Nodes:

        Node Id: 0d5f62a8d96f8bb49d9aa734150b8275
        State: online
        Cluster Id: d03c49ceeea31aed3b48bb4b51f3b092
        Zone: 1
        Management Hostnames: 20.26.208.82
        Storage Hostnames: 20.26.208.82
        Devices:
                Id:5cc74a3076bedc3db7b2514ab4179e50   Name:/dev/sdc            State:online    Size (GiB):99      Used (GiB):0       Free (GiB):99      
                        Bricks:

        Node Id: 8b86f52ada48cc3f753adc81b2e990ca
        State: online
        Cluster Id: d03c49ceeea31aed3b48bb4b51f3b092
        Zone: 1
        Management Hostnames: 20.26.208.81
        Storage Hostnames: 20.26.208.81
        Devices:
                Id:ec4fc6a6f019901f717e99fe2d17e6a9   Name:/dev/sdc            State:online    Size (GiB):99      Used (GiB):0       Free (GiB):99      
                        Bricks:

========================
20.26.208.81:/dev/sdc,and 20.26.208.82:/dev/sdc is glusterfs cluster.
/dev/sdc operation:
mkfs.xfs  -i size=512 /dev/sdc
pvcreate --metadatasize=128M --dataalignment=256K '/dev/sdc'

**Comment by yingjunxu** [comment]
[root@csvz13-nrgl72 ~]# heketi-cli --user admin --secret admin --server http://20.26.208.81:8080 node list
Id:0d5f62a8d96f8bb49d9aa734150b8275     Cluster:d03c49ceeea31aed3b48bb4b51f3b092
Id:8b86f52ada48cc3f753adc81b2e990ca     Cluster:d03c49ceeea31aed3b48bb4b51f3b092
[root@csvz13-nrgl72 ~]# heketi-cli --user admin --secret admin --server http://20.26.208.81:8080 node info 0d5f62a8d96f8bb49d9aa734150b8275
Node Id: 0d5f62a8d96f8bb49d9aa734150b8275
State: online
Cluster Id: d03c49ceeea31aed3b48bb4b51f3b092
Zone: 1
Management Hostname: 20.26.208.82
Storage Hostname: 20.26.208.82
Devices:
Id:5cc74a3076bedc3db7b2514ab4179e50   Name:/dev/sdc            State:online    Size (GiB):99      Used (GiB):0       Free (GiB):99      Bricks:0       
[root@csvz13-nrgl72 ~]# heketi-cli --user admin --secret admin --server http://20.26.208.81:8080 node info 8b86f52ada48cc3f753adc81b2e990ca 
Node Id: 8b86f52ada48cc3f753adc81b2e990ca
State: online
Cluster Id: d03c49ceeea31aed3b48bb4b51f3b092
Zone: 1
Management Hostname: 20.26.208.81
Storage Hostname: 20.26.208.81
Devices:
Id:ec4fc6a6f019901f717e99fe2d17e6a9   Name:/dev/sdc            State:online    Size (GiB):99      Used (GiB):0       Free (GiB):99      Bricks:0

**Comment by tanzwut2525** [comment]
I have the same problem when, I try to perform command: "heketi-cli --user admin --secret admin123 -s http://10.244.6.2:8080 setup-openshift-heketi-storage" and got this msg: "Error: Failed to allocate new volume: Cluster has disabled all volume types"

**Comment by phlogistonjohn** [comment]
@yingjunxu  your problem is shown at the top of your topology info output:
```
File:  false
Block: true
```

The cluster has enabled block volume support but not file volume support. However, the command you issue requests a file volume. Thus the cluster is rejecting the request with the ""Cluster does not support requested volume type" error. If this is a mistake you can use the `heketi-cli cluster set` command to change this.

@tanzwut2525 your error is probably similar but you'd probably see both "File" and "Block" show "false" in the topology info. AFIACT that's the only place in the code that returns that error.

**Comment by tanzwut2525** [comment]
Hello @yingjunxu !
I've fixed my problem, it was related to RBAC inside Kubernetes cluster. 
Sorry for disturbing you

**Comment by phlogistonjohn** [comment]
I'm triaging issues. I hope our previous comments were helpful. In order to not leave a lot of lingering issues open I'll be closing this now.
