### ISSUE TITLE
Adding s390x support for CentOS CI

### ISSUE THREAD

**Issue by pooja0805** [heketi/heketi#1866]
We are interested in adding s390x support in the CentOS CI. Can someone please guide us in achieving this?

**Comment by pooja0805** [comment]
Can someone have a look?

**Comment by pooja0805** [comment]
@phlogistonjohn Please share any insights if you have any on this.

**Comment by phlogistonjohn** [comment]
If centos ci already supports s390 then I have no issue updating our scripts to make use of it. However, as the interested party you'll have to do the research and propose the patches to make it happen. I'm happy to advise and provide background on how the scripts currently work, as well as review patches, but neither I nor othe other maintainers have the bandwith to support this niche architecture ourselves. I hope you understand.

**Comment by pooja0805** [comment]
@phlogistonjohn Thank you for your response. I will investigate the feasibility. Closing this issue for now.
