### ISSUE TITLE
I cannot create storage with heketi.

### ISSUE THREAD

**Issue by yangyuanpeng525** [heketi/heketi#1880]
### Kind of issue

> Uncomment only one of these:
> 
> Bug
> Feature request

### Details on how to reproduce (minimal and precise)
I did it manually---gluster volume add-brick/replace-brick

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master):  Heketi v9.0.0-1-g57a5f356-release-9
- Operating system used:  centos7.7
- Heketi compiled from sources, as a package (rpm/deb), or container: k8s
- If container, which container image:  
- Using kubernetes, openshift, or direct install: 
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside:  inside
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): 

### Other useful information
[root@heketi-86c85dfb56-7b2d7 /]#  heketi-cli --user admin --secret   admin123 --server http://localhost:8080topology info
Error: Id not found

[root@heketi-86c85dfb56-sfxbl /]# heketi-cli --user admin --secret   admin123 --server http://localhost:8080 volume  create --size 1 --name test
Error: Failed to allocate new volume: Id not found

How do I solve this?

**Comment by phlogistonjohn** [comment]
> I did it manually---gluster volume add-brick/replace-brick

I'm not clear on what you were trying to accomplish.

> [root@heketi-86c85dfb56-7b2d7 /]# heketi-cli --user admin --secret admin123 --server http://localhost:8080topology info
Error: Id not found

This is usually a sign that the heketi db is internally inconsistent (the structure of the db is OK, but certain important references are broken).  Since you're also running gluster commands "manually" did you try to manipulate the db? If not, you may need to manually repair your db. Unfortunately, this is a difficult and involved activity. 

Generally, you shouldn't try to make changes to gluster or heketi db directly. However, if you post a db dump (heketi-cli db dump) we can take a look and I can tell you how difficult it may be to repair the db.

**Comment by yangyuanpeng525** [comment]
Yes, I think I should explain my requirements. 
My requirements are: I use volme of two copies created by heketi, and these two copies (bricks) are on different disks. 
If one of the disks (bricks) is damaged, how can I recover to two usable copies? 
I didn't find the command to use heketi-cli to modify the number of copies of the created volme, but only found the command line operation of glustfs. Therefore, I tried to use the command line of glustfs to operate glustfs directly. 
Therefore, how to directly use heketi-cli to expand or shrink the copy number of volme (currently only for replication mode), so as to solve the problem of restoring the original available copy number after a certain disk (brick) is damaged in replication mode in production environment. 
Thank you very much for taking the time to reply to me.

**Comment by pwxwmm** [comment]
> > I did it manually---gluster volume add-brick/replace-brick
> 
> I'm not clear on what you were trying to accomplish.
> 
> > [root@heketi-86c85dfb56-7b2d7 /]# heketi-cli --user admin --secret admin123 --server http://localhost:8080topology info
> > Error: Id not found
> 
> This is usually a sign that the heketi db is internally inconsistent (the structure of the db is OK, but certain important references are broken). Since you're also running gluster commands "manually" did you try to manipulate the db? If not, you may need to manually repair your db. Unfortunately, this is a difficult and involved activity.
> 
> Generally, you shouldn't try to make changes to gluster or heketi db directly. However, if you post a db dump (heketi-cli db dump) we can take a look and I can tell you how difficult it may be to repair the db.

Hi, My heketi service is often down, I now have the dump DB file, Obtained by executing this command "heketi db export --dbfile=/etc/heketi/heketi.db  --jsonfile=/opt/heketi.json" . How can I repair it? My heketi version is 7.0.0 and I have a lot of pending operations in my files "/opt/heketi.json", I plan to upgrade version to 9.0.0, I don't know if I can solve this pending problem,In fact, I wonder if there is another solution,.There is currently a discrepancy between the number of volumes in my GlusterFS service and Heketi service layer. As a matter of fact, The number of volumes in Glusterfs is 400 and the number of volumes in Heketi is 500, Also, invalid volumes in heketi cannot be deleted.Thanks

**Comment by pwxwmm** [comment]
> > I did it manually---gluster volume add-brick/replace-brick
> 
> I'm not clear on what you were trying to accomplish.
> 
> > [root@heketi-86c85dfb56-7b2d7 /]# heketi-cli --user admin --secret admin123 --server http://localhost:8080topology info
> > Error: Id not found
> 
> This is usually a sign that the heketi db is internally inconsistent (the structure of the db is OK, but certain important references are broken). Since you're also running gluster commands "manually" did you try to manipulate the db? If not, you may need to manually repair your db. Unfortunately, this is a difficult and involved activity.
> 
> Generally, you shouldn't try to make changes to gluster or heketi db directly. However, if you post a db dump (heketi-cli db dump) we can take a look and I can tell you how difficult it may be to repair the db.

Hi, My heketi service is often down, I now have the dump DB file, Obtained by executing this command "heketi db export --dbfile=/etc/heketi/heketi.db  --jsonfile=/opt/heketi.json" . How can I repair it? My heketi version is 7.0.0 and I have a lot of pending operations in my files "/opt/heketi.json", I plan to upgrade version to 9.0.0, I don't know if I can solve this pending problem,In fact, I wonder if there is another solution,.There is currently a discrepancy between the number of volumes in my GlusterFS service and Heketi service layer. As a matter of fact, The number of volumes in Glusterfs is 400 and the number of volumes in Heketi is 500, Also, invalid volumes in heketi cannot be deleted.Thanks

**Comment by phlogistonjohn** [comment]
This issue has gone stale and I think there's a mixing of unrelated problems in some of the follow up comments. Please feel free to file _new_ issues related to issues you are having. Do note that with heketi in deep maintenance mode we are often very slow  to reply and I am discouraging people from making new installs with heketi. Thanks.
