### ISSUE TITLE
Error: Cannot replace brick <brick-id> as it is source brick for data to be healed

### ISSUE THREAD

**Issue by manisha-tanwar** [heketi/heketi#1881]
### Kind of issue

> Uncomment only one of these:
> 
Bug
> Feature request

### Observed behavior
`heketi-cli device remove debb40009c2f3069bfef17d0357a70bf` fails with error 

> Error: Cannot replace brick c5109f758f26743b1ccd5254ef2d8685 as it is source brick for data to be healed

### Expected/desired behavior
Device <id> is now removed

### Details on how to reproduce (minimal and precise)

I'm using heketi for kubernetes pvc with replicate:3 with 2 disks. 
`heketi-cli  device disable <device-id>`
 `heketi-cli device remove <device-id>`
device from 1 out of 3 node removed successfully.

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): master
- Operating system used: K8
- Heketi compiled from sources, as a package (rpm/deb), or container: container
- If container, which container image: heketi:dev
- Using kubernetes, openshift, or direct install: kubernetes
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: inside kubernetes
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): gk-deploy

### Other useful information
I'm running it on production server and need help urgent, thanks!

**Comment by manisha-tanwar** [comment]
I enabled device and disable it again. Then device remove worked fine. 
Is there anything I could take care of in future please.
Thanks!

**Comment by phlogistonjohn** [comment]
> ### Kind of issue
> 
> > Uncomment only one of these:
> 
> Bug
> 
> > Feature request
> 
> ### Observed behavior
> 
> `heketi-cli device remove debb40009c2f3069bfef17d0357a70bf` fails with error
> 
> > Error: Cannot replace brick c5109f758f26743b1ccd5254ef2d8685 as it is source brick for data to be healed
> 

This error is showing you the issue at hand: you're trying to remove a brick that has the only copy of some data at gluster. Therefore heketi is blocking you from removing it because its needed as the source for gluster heal.



> ### Expected/desired behavior
> 
> Device is now removed
> ### Details on how to reproduce (minimal and precise)
> 
> I'm using heketi for kubernetes pvc with replicate:3 with 2 disks.
> `heketi-cli device disable <device-id>`
> `heketi-cli device remove <device-id>`
> device from 1 out of 3 node removed successfully.

Replica 3 with two disks doesn't make a lot of sense to me.


> ### Information about the environment:
> 
>     * Heketi version used (e.g. v6.0.0 or master): master
> 
>     * Operating system used: K8
> 
>     * Heketi compiled from sources, as a package (rpm/deb), or container: container
> 
>     * If container, which container image: heketi:dev
> 

I highly recommend *not* using `heketi:dev` that tag doesn't track released code and not regularly updated. If you can I suggest switching to the `10` tag.


>     * Using kubernetes, openshift, or direct install: kubernetes
> 
>     * If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: inside kubernetes
> 
>     * If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): gk-deploy
> 
> 
> ### Other useful information
> 
> I'm running it on production server and need help urgent, thanks!

**Comment by manisha-tanwar** [comment]
Thanks @phlogistonjohn will change the version, do you have any idea about the error, it might be related to gluster really but if I can fox it for next time, it would be great.

**Comment by manisha-tanwar** [comment]
So I again faced same issue, disable enable didn't work so I waited for some time & rerun remove command. It worked 😄

**Comment by pwxwmm** [comment]
> I enabled device and disable it again. Then device remove worked fine. Is there anything I could take care of in future please. Thanks!

haha, I also reported the above error, but I performed two consecutive remove operation, it unexpectedly succeeded!

**Comment by phlogistonjohn** [comment]
I hope you were able to work around your issue. As this issue has gone idle, I am going to close it, but you can reopen it if you feel that's necessary.
