### ISSUE TITLE
Unable to create cluster

### ISSUE THREAD

**Issue by meysamfarazmand** [heketi/heketi#1883]
### Kind of issue

> Uncomment only one of these:
> 
> Bug
> Feature request

### Observed behavior
**user@af-dev-glsr01:~$ sudo heketi-cli topology load --user admin --secret vyqfsRVYP6U2GXmgvKA2mpLJTU7KZzPQSXSThqzt2fxTkpvjqzFYdPLMcyAUAS6G --json=/etc/heketi/topology.json**

Creating cluster ... ID: 1d0f2722f0ec12fcf63b7a88227db668
        Allowing file volumes on cluster.
        Allowing block volumes on cluster.
        Creating node af-dev-glsr01 ... ID: b2f6474020ec148fa97cfb920f6c57ee
                Adding device /dev/sdc ... Unable to add device: Initializing device /dev/sdc failed (already initialized or contains data?):   Size requires number argument.
  Invalid argument for --dataalignment: Optional:
  Error during parsing of command line.
        Creating node af-dev-glsr02 ... ID: ec84b9fcc76dd59ec8be48af15b76569
                Adding device /dev/sdc ... Unable to add device: Initializing device /dev/sdc failed (already initialized or contains data?):   Size requires number argument.
  Invalid argument for --dataalignment: Optional:
  Error during parsing of command line.
        Creating node af-dev-glsr03 ... ID: b920f5fa7e0c7915af67b84b69db88e7
                Adding device /dev/sdc ... Unable to add device: Initializing device /dev/sdc failed (already initialized or contains data?):   Size requires number argument.
  Invalid argument for --dataalignment: Optional:
  Error during parsing of command line.

### Expected/desired behavior
**user@af-dev-glsr01:~$ sudo heketi-cli topology load --user admin --secret vyqfsRVYP6U2GXmgvKA2mpLJTU7KZzPQSXSThqzt2fxTkpvjqzFYdPLMcyAUAS6G --json=/etc/heketi/topology.json**

Creating cluster ... ID: 1d0f2722f0ec12fcf63b7a88227db668
        Allowing file volumes on cluster.
        Allowing block volumes on cluster.
        Creating node af-dev-glsr01 ... ID: b2f6474020ec148fa97cfb920f6c57ee
		Adding device /dev/sdc ... OK
        Creating node af-dev-glsr02 ... ID: ec84b9fcc76dd59ec8be48af15b76569
		Adding device /dev/sdc ... OK
        Creating node af-dev-glsr03 ... ID: b920f5fa7e0c7915af67b84b69db88e7
		Adding device /dev/sdc ... OK

### Details on how to reproduce (minimal and precise)
1- attach a raw disk to VM
2- Change device name to new raw disk in topology file
3- Run topolgy command

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master):  **Heketi v10.4.0-release-10 (using go: go1.15.14)**
- Operating system used: **Ubuntu 20.04**
- Heketi compiled from sources, as a package (rpm/deb), or container: **compiled from sources**
- If container, which container image: 
- Using kubernetes, openshift, or direct install: **direct install**
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: 
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): 

### Other useful information
I have set "executor": "ssh" in Heketi config file

**Comment by phlogistonjohn** [comment]
The error you see is lvm trying to protect you from clobbering disks with data on them. If you're very certain that the disks really are empty of data you want you need to remove any metadata from them that makes lvm think there's something there. Look into tools like `wipefs` or `dd` (to write zeros to the disk).

Beware: I can't help you if you do clobber real data on those disks, so do please be careful.

Lastly, do note that heketi is in maintenance only mode - I personally do not recommend using it for new systems unless you're already fairly familiar with it.

**Comment by prologic** [comment]
@phlogistonjohn Can we open up the Discussions section of this repo despite ti being in maintenance mode? We can then turn off Issues if you like. I'm _actually_ considering forking this project and doing some work on it.

**Comment by phlogistonjohn** [comment]
I'm sorry but no I do not think we'll be enabling discussions. Feel free to fork the project as needed though. I hope you understand.
