### ISSUE TITLE
Does heketi create volume group for every device added or does it create one volume group per node irrespective of number of devices added to that node?

### ISSUE THREAD

**Issue by srivatsagowda** [heketi/heketi#1886]
Hi all

sorry for putting this up under issues. I could not find any discussion area.
 
 I'm struggling to understand the working of heketi and how it creates lvm for dynamic provisioning. My doubt is if heketi creates volume group for every device added or does it create one volume group per node irrespective of number of devices added to that node?
I would be grateful if anyone could explain how it works.
Thank You.

**Comment by phlogistonjohn** [comment]
We hope our responses were useful.
