### ISSUE TITLE
Heketi does not manage endpoints on host/device deletion risks connecting to wrong servers for config

### ISSUE THREAD

**Issue by bdowling** [heketi/heketi#1888]
### Kind of issue

Bug

### Observed behavior

Upon deletion of hosts/devices any existing Endpoints in k8s are not managed.

### Expected/desired behavior

Heketi should be aware and adaptive to the changes host and device management will have on existing k8s PVCs and their respective endpoints.

### Details on how to reproduce (minimal and precise)

Install heketi on a multi-node cluster and delete devices/nodes from the environment.

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): Heketi v8.0.0-1-g082b556-release-8
- Operating system used: 
- Heketi compiled from sources, as a package (rpm/deb), or container: heketi/heketi:8
- If container, which container image:  heketi/heketi:8
- Using kubernetes, openshift, or direct install: k8s
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: inside
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): gk-deploy

### Other useful information

I know this project is in maintenance mode, but I just thought I'd record this issue here in case anyone else runs into it.

I had an opportunity recently to manage a heketi instance that was installed with gk-deploy.   There was a need to split the existing cluster into two different k8s/glusterfs groups, so existing nodes/devices were removed from the existing install and new k8s/gluster cluster was deployed on the reallocated hosts (using the same IPs).  

What happened in this scenario that was unrealized until later was that the original cluster had `EndPoints` that remained to reference ALL of the original IPs of the cluster.  This manifested itself when heketi was restarted on the OLD cluster and was attempting to mount the `heketi-storage-endpoints` pvc from the NEW cluster.  When it succeeded to this, it obviously was confused about what nodes it could see and the volumes that should exist.  It took some time to identify that this is exactly what occurred, but once it was recognized, it was clear that the fix was to adjust all of the `EndPoints` to not contain any of the IP Addresses of the nodes from the new cluster.

Additionally, the topology in the cm was also not updated by heketi management, so that added to the confusion and initially was thought to be why heketi was reaching the new cluster.

Whatever replacement/follow-on work comes down the line, this perhaps should be remedied.  One additional thought/workaround is that heketi install via gk-deploy should perhaps not use a static volume name, but instead use a unique UUID based name that is pointed to from a configmap, so this type of conflict can additionally be avoided in shared, non-hyperconverged glusterfs environments.

NB: I'm guessing node additions, or other adjustments to exisitng volumes may have similar problems.

**Comment by phlogistonjohn** [comment]
Thank you for the feedback. As you noted the project is in maintenance and thus not taking new changes along the suggested lines. As such, I'll be closing the issue but  your text should still be reachable through github search  & search engines and thus useful to others.
