### ISSUE TITLE
Cannot add device with KVM virtual disk

### ISSUE THREAD

**Issue by jav333** [heketi/heketi#1889]
### Kind of issue

> Uncomment only one of these:
> 
> Bug
> Feature request

### Observed behavior
Please see below link, thanks

https://github.com/justmeandopensource/kubernetes/issues/88

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): 
- Operating system used: 
- Heketi compiled from sources, as a package (rpm/deb), or container: 
- If container, which container image: 
- Using kubernetes, openshift, or direct install: 
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: 
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom):

**Comment by jav333** [comment]
Can someone help?

**Comment by phlogistonjohn** [comment]
It's a bit odd that you created a issue in another project and expect us to follow that link.

The error is telling you that "/usr/bin/lvm" doesn't exist. Heketi requires LVM on the nodes it manages.  If you have LVM but the path is not typical, you could try to use the HEKETI_LVM_WRAPPER env variable to customize how heketi accesses lvm on your nodes, but note that we won't go out of our way to support this. If you choose this option you're on your own.

Finally, I'll take a moment to note that heketi is is deep maintenance status and I do not encourage people to do new installs with heketi - especially if you are unfamiliar with it. Thanks.

**Comment by jav333** [comment]
Hi @phlogistonjohn ,

Sorry, I don't understand why lvm group is in /usr/bin/lvm? not in /dev ?

Thanks

**Comment by phlogistonjohn** [comment]
In the screenshot in the issue you linked the last part of the error message is:
```
/bin/bash: /usr/sbin/lvm: No such file or directory
```

This is most likely caused by the lvm binary not existing on your system (most likely) or not existing at the path /usr/sbin/lvm. Heketi needs this command to create & delete lvm logical volumes that will host gluster brick filesystems.

The command makes use of special files in /dev but just having the kernel parts of lvm available is not sufficient.

I don't know what group you're referring to.

**Comment by phlogistonjohn** [comment]
I'm sorry but the maintenance team doesn't have the capability to assist with heketi issues any more. For future issues your best best is consult the heketi source code.
