### ISSUE TITLE
Unable to create PVC,   device-mapper: reload ioctl on  (253:71) failed: Cannot allocate memory

### ISSUE THREAD

**Issue by manisha-tanwar** [heketi/heketi#1891]
### Kind of issue

> Uncomment only one of these:
> 
 Bug
> Feature request

### Observed behavior
[heketi] ERROR 2022/01/17 23:47:39 heketi/apps/glusterfs/operations_volume.go:118:glusterfs.(*VolumeCreateOperation).Exec: Error executing create volume:   WARNING: This metadata update is NOT backed up.
  device-mapper: reload ioctl on  (253:67) failed: Cannot allocate memory
  Failed to activate new LV.
  Internal error: Removing still active LV vg_cbe5a791ddb343c15666d1ee72ed88ee/tp_08af7cd4f3f2f9503ced9f672ddc92e5_tmeta.
  Manual intervention may be required to remove abandoned LV(s) before retrying.
[heketi] ERROR 2022/01/17 23:47:39 heketi/apps/glusterfs/operations_manage.go:167:glusterfs.runOperationAfterBuild: Create Volume Failed: Operation Should Be Retried; Error:   WARNING: This metadata update is NOT backed up.
  device-mapper: reload ioctl on  (253:67) failed: Cannot allocate memory
  Failed to activate new LV.
  Internal error: Removing still active LV vg_cbe5a791ddb343c15666d1ee72ed88ee/tp_08af7cd4f3f2f9503ced9f672ddc92e5_tmeta.
  Manual intervention may be required to remove abandoned LV(s) before retrying.
[heketi] INFO 2022/01/17 23:47:39 Starting Clean for Create Volume op:8f67b98ae9e2c9d51f5d5ae9202f4b28
[heketi] INFO 2022/01/17 23:47:39 preparing to remove volume 3f73b5f853e1efd8b2752ef9b9d46df2 in op:8f67b98ae9e2c9d51f5d5ae9202f4b28
[heketi] INFO 2022/01/17 23:47:39 executing removal of volume 3f73b5f853e1efd8b2752ef9b9d46df2 in op:8f67b98ae9e2c9d51f5d5ae9202f4b28
[cmdexec] DEBUG 2022/01/17 23:47:39 heketi/pkg/remoteexec/log/commandlog.go:34:log.(*CommandLogger).Before: Will run command [rmdir /var/lib/heketi/mounts/vg_39b86834729252ebdc0921fe2c05d24d/brick_f7ff42abef0195bc1d5cb5e89459d51d] on [gb1-li-feunitygluster-006:22]
[cmdexec] DEBUG 2022/01/17 23:47:39 heketi/pkg/remoteexec/log/commandlog.go:34:log.(*CommandLogger).Before: Will run command [sed -i.save "/brick_0c2f9d83e97d98bbf8c7202684f635dd/d" /etc/fstab] on [gb1-li-feunitygluster-005:22]
[cmdexec] ERROR 2022/01/17 23:47:39 heketi/pkg/remoteexec/log/commandlog.go:56:log.(*CommandLogger).Error: Failed to run command [/usr/sbin/lvm lvremove --autobackup=n -f vg_cbe5a791ddb343c15666d1ee72ed88ee/tp_138c7f65705d27b7802a646ec1482ac7] on [gb1-li-feunitygluster-004:22]: Err[Process exited with status 5]: Stdout []: Stderr [  Failed to find logical volume "vg_cbe5a791ddb343c15666d1ee72ed88ee/tp_138c7f65705d27b7802a646ec1482ac7"
]
[cmdexec] WARNING 2022/01/17 23:47:39 did not delete missing thin pool: vg_cbe5a791ddb343c15666d1ee72ed88ee/tp_138c7f65705d27b7802a646ec1482ac7
[cmdexec] ERROR 2022/01/17 23:47:39 heketi/pkg/remoteexec/log/commandlog.go:56:log.(*CommandLogger).Error: Failed to run command [rmdir /var/lib/heketi/mounts/vg_39b86834729252ebdc0921fe2c05d24d/brick_f7ff42abef0195bc1d5cb5e89459d51d] on [gb1-li-feunitygluster-006:22]: Err[Process exited with status 1]: Stdout []: Stderr [rmdir: failed to remove ‘/var/lib/heketi/mounts/vg_39b86834729252ebdc0921fe2c05d24d/brick_f7ff42abef0195bc1d5cb5e89459d51d’: No such file or directory
]
[cmdexec] ERROR 2022/01/17 23:47:39 heketi/executors/cmdexec/brick.go:277:cmdexec.(*CmdExecutor).BrickDestroy: rmdir: failed to remove ‘/var/lib/heketi/mounts/vg_39b86834729252ebdc0921fe2c05d24d/brick_f7ff42abef0195bc1d5cb5e89459d51d’: No such file or directory
[cmdexec] WARNING 2022/01/17 23:47:36 unable to count lvs in missing thin pool: vg_39b86834729252ebdc0921fe2c05d24d/tp_2d6f3e8106297587811e2b79b7756303
[cmdexec] ERROR 2022/01/17 23:47:36 heketi/pkg/remoteexec/log/commandlog.go:56:log.(*CommandLogger).Error: Failed to run command [gluster --mode=script --timeout=600 volume stop vol_2d3c0e507d4a0fe1c4220206c3fe54b9 force] on [gb1-li-feunitygluster-005:22]: Err[Process exited with status 1]: Stdout []: Stderr [volume stop: vol_2d3c0e507d4a0fe1c4220206c3fe54b9: failed: Volume vol_2d3c0e507d4a0fe1c4220206c3fe54b9 does not exist
]
[cmdexec] ERROR 2022/01/17 23:47:36 heketi/executors/cmdexec/volume.go:150:cmdexec.(*CmdExecutor).VolumeDestroy: Unable to stop volume vol_2d3c0e507d4a0fe1c4220206c3fe54b9: volume stop: vol_2d3c0e507d4a0fe1c4220206c3fe54b9: failed: Volume vol_2d3c0e507d4a0fe1c4220206c3fe54b9 does not exist

### Expected/desired behavior
should create pvc

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): v10
- Operating system used: kubernetes
- Heketi compiled from sources, as a package (rpm/deb), or container: container
- If container, which container image: heketi: master
- Using kubernetes, openshift, or direct install: kubernetes
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: inside
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): gk-deploy

**Comment by manisha-tanwar** [comment]
Is there a way to clean up heketi. I already tried device resync but no luck.

**Comment by phlogistonjohn** [comment]
I'm sorry but the maintenance team doesn't have the capability to assist with heketi issues any more. You're most likely hitting issues with regards to LVM, which is out of scope for the heketi team. For future issues your best best is consult the heketi source code.
