### ISSUE TITLE
mount hosts list is not same as list of all nodes of the cluster

### ISSUE THREAD

**Issue by IAdi82** [heketi/heketi#1893]
###
We attempted to recover a node- remove it from heketi and add it back. 
At the end of a successful procedure we see this in db check:

Volume 1d0a232eafc4ae081b053740febeb67a mount hosts list([10.75.202.60 10.75.202.48]) is not same as list of all nodes of the cluster([afabd55d73e3cd05a61da1ffc0119544 ba86961f7b1f4ab4ec6a589c25a1bd35 c2ebc25ba7159270d198769b3688bb2e])",
"Volume d820ab0880ee06bc67d21984677171bd mount hosts list([10.75.202.60 10.75.202.48]) is not same as list of all nodes of the cluster([afabd55d73e3cd05a61da1ffc0119544 ba86961f7b1f4ab4ec6a589c25a1bd35 c2ebc25ba7159270d198769b3688bb2e])",
....

3 peers are connected: 10.75.202.48, 10.75.202.47, 10.75.202.60. 
We're not sure it is an actual issue as the hosts can mount new bricks, but why do we get this message...
###

### Kind of issue

> Bug

### Observed behavior
we get inconsistency in the heketi db as mention above but its seems harmless, we can add new pvcs and mount bricks. 
The nodes id list is the same not like mentioned in the inconsistency message:
"is not same as list of all nodes of the cluster"

### Expected/desired behavior
No inconsistency message after a successful node recovery 

### Details on how to reproduce (minimal and precise)
scale in a node (remove a device, then the node, then detach the peer)
scale out a node (attach a peer, add a node, add device)

### Information about the environment:

- Heketi version v10.2.0
- Operating system used:  4.18.0-348.7.1.2201051124.el7_9.emrs.ulnx.x86_64
- Heketi compiled from sources
- direct install: 
- kubernetes/openshift, gluster running outside
-Kubernetes v1.21.6
[heketi.log](https://github.com/heketi/heketi/files/7998251/heketi.log)

**Comment by IAdi82** [comment]
btw, from the heketi log we added the udevadm to the gluster-user commands in the sudoers but the "inconsistencies" still there

**Comment by phlogistonjohn** [comment]
I'm sorry but the maintenance team doesn't have the capability to assist with heketi issues any more. Your best best is to check the source code to determine what values the db check is comparing to understand the error.
