### ISSUE TITLE
go mod download github.com/heketi/heketi@v10.4.0 fails

### ISSUE THREAD

**Issue by slaskawi** [heketi/heketi#1897]
### Kind of issue
 
Bug

### Observed behavior

`go mod download github.com/heketi/heketi@v10.4.0` fails with the following message:

```
$ go mod download github.com/heketi/heketi@v10.4.0
go: github.com/heketi/heketi@v10.4.0+incompatible: invalid version: module contains a go.mod file, so module path must match major version ("github.com/heketi/heketi/v10")
```

### Expected/desired behavior

Kubernetes script for updating dependencies uses `go mod download` command and the v10.4.0 prevents us from upgrading. Please note, that the previous version worked fine:

```
$ go mod download github.com/heketi/heketi@v10.3.0
$ echo $?
0
```

### Details on how to reproduce (minimal and precise)

```
$ go mod download github.com/heketi/heketi@v10.4.0
go: github.com/heketi/heketi@v10.4.0+incompatible: invalid version: module contains a go.mod file, so module path must match major version ("github.com/heketi/heketi/v10")
```

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): v10.4.0
- Operating system used: Linux
- Heketi compiled from sources, as a package (rpm/deb), or container: referenced from Kubernetes repo
- Using kubernetes, openshift, or direct install: Kubernetes repo, see https://github.com/kubernetes/kubernetes/issues/104007
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: 
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): 

### Other useful information

xref: https://github.com/kubernetes/kubernetes/issues/104007

**Comment by slaskawi** [comment]
xref: https://kubernetes.slack.com/archives/C09QZFCE5/p1650437188540879

**Comment by pohly** [comment]
See https://github.com/heketi/heketi/pull/1867/files#r853806978

**Comment by humblec** [comment]
@raghavendra-talur @phlogistonjohn can you please check on this issue and PR ?
