### ISSUE TITLE
Volume bricks removed when dedicated server reboots

### ISSUE THREAD

**Issue by Karthik-PlantSense** [heketi/heketi#1902]
### Kind of issue

Hi, I have two servers one is a dedicated server. In that server, I'm running heketi and glusterfs.
On the other server, I'm running Kubernetes. When I rebooted the dedicated server it is removed volume bricks

### Observed behaviour
remove volume bricks when the server reboot

### Expected/desired behaviour
start volume without removing bricks

### Details on how to reproduce (minimal and precise)

- install heketi and glusterfs 8 on the dedicated server
- create a heketi cluster, node and device
- create volume from Kubernetes storageclass
- try to reboot the dedicated server

### Information about the environment:

- Heketi version: 10.1.0
- Operating system used: ubuntu 20.4
- Heketi compiled from source
- Using direct installation

**Comment by phlogistonjohn** [comment]
Please note that heketi is now a "deep maintenance" project (and has been for quite a few months). The maintenance team is not actively assisting with issues and we're focused only on major faults and security issues. We plan on ending maintenance around midyear 2023.
