### ISSUE TITLE
We find some bricks in topology info but not in device

### ISSUE THREAD

**Issue by whaifang** [heketi/heketi#1906]
Hi Team.

Good Day~~)

Environment:
Glusterfs: glusterfs-9.0-1.el7
heketi:     9.0.0

1. Command:”heketi-cli topology info“ in Node section are full of **599G**
2. Command "df -h”  are **490G**, this matchs the volume size summary in volume section(show in topology info command ).
3. We fail to create/delete volume, error:Error: sed: couldn’t open temporary file /etc/sedGN9DoO: No space left on device
4. We actually **only used 490G**, but in topology info we used **599G**. Some birck records in topology  info Node section can't been found in volume section.

	Node Id: ##############
	State: online
	Cluster Id: ##############
	Zone: 1
	Management Hostnames: ##############
	Storage Hostnames: ##############
	Devices:
		Id:##############   Name:/dev/###            State:online    Size (GiB):599     Used (GiB):598     Free (GiB):1       
			Bricks:
				Id:016ace522########22d60c197   Size (GiB):2       Path: /var/lib/heketi/mounts/vg_f95abfb3735a#########d6e195d65/brick_016ace5229701406#########d60c197/brick
				Id:03148aa0d########19f8da9b7   Size (GiB):5       Path: /var/lib/heketi/mounts/vg_f95abfb3735a#########d6e195d65/brick_03148aa0d00f898f#########f8da9b7/brick
				Id:03acbe4f7########337202706   Size (GiB):4       Path: /var/lib/heketi/mounts/vg_f95abfb3735a#########d6e195d65/brick_03acbe4f7f9c7da7#########7202706/brick
				Id:051e3fe64########5ebf6487b   Size (GiB):2       Path: /var/lib/heketi/mounts/vg_f95abfb3735a#########d6e195d65/brick_051e3fe64a60d83c#########bf6487b/brick
				Id:07fe71d61########0b2e67a4c   Size (GiB):5       Path: /var/lib/heketi/mounts/vg_f95abfb3735a#########d6e195d65/brick_07fe71d619bf73f9#########2e67a4c/brick
				Id:0961f454b########3a471dc9f   Size (GiB):3       Path: /var/lib/heketi/mounts/vg_f95abfb3735a#########d6e195d65/brick_0961f454bf9fbeb6#########471dc9f/brick
				Id:0c4dc45d7########e5868a5e7   Size (GiB):2       Path: /var/lib/heketi/mounts/vg_f95abfb3735a#########d6e195d65/brick_0c4dc45d7b917ca7#########868a5e7/brick
				Id:0dcf8b1cb########b41b70a95   Size (GiB):2       Path: /var/lib/heketi/mounts/vg_f95abfb3735a#########d6e195d65/brick_0dcf8b1cb9a7b288#########1b70a95/brick
				Id:0de7afbe7########c661c0858   Size (GiB):2       Path: /var/lib/heketi/mounts/vg_f95abfb3735a#########d6e195d65/brick_0de7afbe70687bf4#########61c0858/brick
				Id:1261f5cfa########be28fe760   Size (GiB):2       Path: /var/lib/heketi/mounts/vg_f95abfb3735a#########d6e195d65/brick_1261f5cfa01f0926#########28fe760/brick
				Id:14ef89cd2########d80c5e02c   Size (GiB):2       Path: /var/lib/heketi/mounts/vg_f95abfb3735a#########d6e195d65/brick_14ef89cd2165363f#########0c5e02c/brick
				Id:15cc99f0e########4e0f0577d   Size (GiB):2       Path: /var/lib/heketi/mounts/vg_f95abfb3735a#########d6e195d65/brick_15cc99f0e6c5b433#########0f0577d/brick
				Id:1717282d1########cc564fbd1   Size (GiB):2       Path: /var/lib/heketi/mounts/vg_f95abfb3735a#########d6e195d65/brick_1717282d1711ff3c#########564fbd1/brick
				Id:180bd127f########7ced480c8   Size (GiB):4       Path: /var/lib/heketi/mounts/vg_f95abfb3735a#########d6e195d65/brick_180bd127f4f0d9b2#########ed480c8/brick
				Id:1b561dfe2########b9424406a   Size (GiB):5       Path: /var/lib/heketi/mounts/vg_f95abfb3735a#########d6e195d65/brick_1b561dfe2b836f22#########424406a/brick
				Id:1c2925eba########781b6ef66   Size (GiB):2       Path: /var/lib/heketi/mounts/vg_f95abfb3735a#########d6e195d65/brick_1c2925eba1eae9cd#########1b6ef66/brick
				Id:1f0ae9547########9c5a1509c   Size (GiB):1       Path: /var/lib/heketi/mounts/vg_f95abfb3735a#########d6e195d65/brick_1f0ae9547daa5399#########5a1509c/brick
				Id:22bb6a9b5########58ce1cc38   Size (GiB):8       Path: /var/lib/heketi/mounts/vg_f95abfb3735a#########d6e195d65/brick_22bb6a9b596b22c7#########ce1cc38/brick
                              #######################################################
                              #######################################################

**Comment by whaifang** [comment]
Hi Team.

Where should we get log for this exception brick?

**Comment by whaifang** [comment]
HI Team.

Any update for this?

**Comment by whaifang** [comment]
HI Team.

Any update for this?

**Comment by phlogistonjohn** [comment]
As noted for a long time in the project readme:
> The Heketi project is now in deep maintenance status. This means that only critical bugs or security defects are being considered for inclusion by the project maintenance team. Expect the project to be archived soon. Expect slow replies to issues.

The only reason heketi project has not been archived yet is that there remain a few commercial users and in the unlikely chance those customers hit a critical bug and need a fix we've left the repo "live".
Please consider this a suggestion to migrate away from heketi as soon as you can. We have no bandwith any more to help with community issues.  I hope you understand.
