### ISSUE TITLE
heketi-cli topology load failed 

### ISSUE THREAD

**Issue by linpanru** [heketi/heketi#1912]
### Kind of issue

> Uncomment only one of these:
> 
> Bug
> Feature request

### Observed behavior
![image](https://user-images.githubusercontent.com/56077231/231744271-bd384627-8f76-45ff-9639-03646d0afdd1.png)

![image](https://user-images.githubusercontent.com/56077231/231674747-c30f3708-a9d5-4ced-81bf-6cf6362356f4.png)

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): V1.0
- Operating system used: openeuler
- Heketi compiled from sources, as a package (rpm/deb), or container:  rpm 
- If container, which container image: 
- Using kubernetes, openshift, or direct install:  Virtual machine
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: 
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom):

**Comment by phlogistonjohn** [comment]
As noted for a long time in the project readme:
> The Heketi project is now in deep maintenance status. This means that only critical bugs or security defects are being considered for inclusion by the project maintenance team. Expect the project to be archived soon. Expect slow replies to issues.

The only reason heketi project has not been archived yet is that there remain a few commercial users and in the unlikely chance those customers hit a critical bug and need a fix we've left the repo "live".
Please consider this a suggestion to migrate away from heketi as soon as you can. We have no bandwith any more to help with community issues.  I hope you understand.
