### ISSUE TITLE
When creating a volume check clusters in a round robin fashion

### ISSUE THREAD

**Issue by lpabon** [heketi/heketi#198]
Currently, when a volume is created, it checks all nodes and disks in a cluster until space is found.  This would mean that bricks may need to be broken to small ones until space is found in the current cluster.  Instead it could try to allocate large bricks in all clusters, and when that fails, break down the brick size and try again.

**Comment by phlogistonjohn** [comment]
This issue has not had any activity in years. If someone still desires this behavior please reopen or file a new issue. Closing.
