### ISSUE TITLE
Heketi doesn't allow deleting nodes with drives missing/inaccessible 

### ISSUE THREAD

**Issue by anushshetty** [heketi/heketi#232]
Description of problem: When drives are unreachable/missing from a node where volumes existed, heketi has no provision to delete the node from the cluster. Hence even the cluster it belongs to cannot be deleted without removing the db file. Volumes associated with the node can be deleted though. 

Version-Release number of selected component (if applicable): 1.0.0 

How reproducible: Always

Steps to Reproduce:
1. Create a cluster and then create a heketi volume
2. On one of the nodes, disable the drives (shutdown the machine)
3. Try deleting the node

Actual results:

Node deletion fails.

**Comment by lpabon** [comment]
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1273868
