### ISSUE TITLE
Investigate using pacemaker for Heketi

### ISSUE THREAD

**Issue by lpabon** [heketi/heketi#253]
I am not sure it's even possible, but it would be great to have someone investigate if this is even a possible way to add HA to Heketi

**Comment by lpabon** [comment]
Ref: http://clusterlabs.org/

**Comment by anushshetty** [comment]
Something like this? 
http://www.cloudera.com/content/www/en-us/documentation/enterprise/latest/topics/admin_cm_ha_failover.html

**Comment by lpabon** [comment]
Not needed.
