### ISSUE TITLE
topology device variant documentation

### ISSUE THREAD

**Issue by msirovy** [heketi/heketi#258]
Hi,
it is realy hard to use it without documentation. Example of topology don't show how to use directory as device and another options. when I create volume, over heketi-cli, how can I specify location of node and number of replicas?

**Comment by lpabon** [comment]
Hi @msirovy, please take a look at the wiki for all documentation.  On the question of how to setup a directory as device, Heketi requires raw access to a device, so it cannot use a directory.  Heketi's job is to dynamically create the required thin pools to setup the XFS volumes.

The goal of Heketi is not not specify the location of a node when you create a volume.  You just need to ask "I want a 10G volume" and it figures it out for you.  Check out the video demo for more information.

On the [API](https://github.com/heketi/heketi/wiki/API#volume_create) and heketi-cli you can set the durability type and the replica number.

Type `heketi-cli volume create -h` for more information.

Let me know if this helps.

**Comment by lpabon** [comment]
Also, here is the documentation on the topology file. https://github.com/heketi/heketi/wiki/Setting-up-the-topology

Please keep in mind that Heketi is designed to be used by a service, and not from a user point of view.  I am working with the GlusterFS team to determine if gdeploy could be a service to use Heketi.  See http://www.spinics.net/lists/gluster-devel/msg17510.html
