### ISSUE TITLE
Heketi 1.0.2 JWT weird qsh issue

### ISSUE THREAD

**Issue by csabahenk** [heketi/heketi#263]
Setup:
- Heketi 1.0.2 Linux 64 binary downloaded from website
- JWT enabled with key *My Secret*.

We try to create a node. Here is the HTTP traffic:

```
2 ('post', ('http://localhost:8080/nodes',), {'headers': {'Authorization': 'bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhZG1pbiIsImlhdCI6MTQ1NjkwMDI5OSwicXNoIjoiMDNiYzU5MTUyMTllYzYwYjMzMTI1Y2UxNmFkODkyNmY4OGQ5MTgxMDY5NDFiZWRiMDQ0OTE4ZjE0MTBiOTI3MSIsImV4cCI6MTQ1NjkwMDU5OX0.tphTXVUUeA8MPKXcCRnhOQtig4toGvapYnFcNgsfKzc'}, 'json': {'cluster': u'5641fc1536e1509beaf3ddedec32cb7c', 'hostnames': {'manage': ['172.16.53.6'], 'storage': ['172.16.53.6']}, 'zone': 1}})
<Response [202]> {'date': 'Wed, 02 Mar 2016 06:31:39 GMT', 'content-length': '0', 'content-type': 'text/plain; charset=utf-8', 'location': '/queue/d4c9b69e3062cef1be7c8dd8a76b25ea'} 
3 ('get', ('http://localhost:8080/queue/d4c9b69e3062cef1be7c8dd8a76b25ea',), {'headers': {'Authorization': 'bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhZG1pbiIsImlhdCI6MTQ1NjkwMDI5OSwicXNoIjoiMzNkOTk0MzhjMDYxZDhlYTQ5NzgxMjJiYzNhNDQ0ZmMyMjcxMTAwNGQ1M2I2ZWQ3YTQ3ZjMwMTU0MjI5ZjY4MCIsImV4cCI6MTQ1NjkwMDU5OX0.U5WO-zEjEkF6LIO0-qowA95F0auEHcC_1IAwsdeAMQM'}})
<Response [200]> {'date': 'Wed, 02 Mar 2016 06:31:39 GMT', 'content-length': '0', 'x-pending': 'true', 'content-type': 'text/plain; charset=utf-8'} 
4 ('get', ('http://localhost:8080/queue/d4c9b69e3062cef1be7c8dd8a76b25ea',), {'headers': {'Authorization': 'bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhZG1pbiIsImlhdCI6MTQ1NjkwMDMwMCwicXNoIjoiMzNkOTk0MzhjMDYxZDhlYTQ5NzgxMjJiYzNhNDQ0ZmMyMjcxMTAwNGQ1M2I2ZWQ3YTQ3ZjMwMTU0MjI5ZjY4MCIsImV4cCI6MTQ1NjkwMDYwMH0.7rMZwN5vq0HCES3iX12Hu7q1R0zVAlASNoVZp27zgu4'}})
<Response [401]> {'date': 'Wed, 02 Mar 2016 06:31:40 GMT', 'content-length': '27', 'content-type': 'text/plain; charset=utf-8', 'x-content-type-options': 'nosniff'} Invalid qsh claim in token
```

So we end up with a trouble about *Invalid qsh claim*. However, if we decode the JWT tokens of the last two requests (GETs on the same queue url) on jwt.io, the qsh value is *33d99438c061d8ea4978122bc3a444fc22711004d53b6ed7a47f30154229f680* with both requests (which is nothing else but *SHA256("GET&/queue/d4c9b69e3062cef1be7c8dd8a76b25ea")*).

**Comment by lpabon** [comment]
Hi @csabahenk, this is confusing because according to the logs above, `2`, `3`, and `4` all have the same payload data eyJpc3MiOiJhZG1pbiIsImlhdCI6MTQ1NjkwMDI5OSwicXNoIjoiMzNkOTk0MzhjMDYxZDhlYTQ5NzgxMjJiYzNhNDQ0ZmMyMjcxMTAwNGQ1M2I2ZWQ3YTQ3ZjMwMTU0MjI5ZjY4MCIsImV4cCI6MTQ1NjkwMDU5OX0 which should not be possible if they have the qsh setup correctly.  Only `2` and `3` should have the same qsh.

**Comment by lpabon** [comment]
@csabahenk Still an issue?

**Comment by csabahenk** [comment]
I'm hoping to have time to check it on Wednesday. If not, then around
Easter.

**Comment by csabahenk** [comment]
Luis, I think you misread my report. The payloads are *not* identical across the three log lines (the one you quote occurs exactly in `3`).

* * *

Anyway, here is how to reproduce.

I'm running Heketi against a local gluster cluster (i.e gluster cluster = { localhost} ). (It does not have importance, just for sake of simplicty). I use a config based on the one that comes with the distributed tarball, just enabled auth (so key is "My Secret") and use ssh executor with root user (for which I have ssh key auth set up). So precisely, this is the config delta:

```diff
--- a/heketi.json
+++ b/heketi-local.json
@@ -3,7 +3,7 @@
        "port" : "8080",

        "_use_auth": "Enable JWT authorization. Please enable for deployment",
-       "use_auth" : false,
+       "use_auth" : true,

        "_jwt" : "Private keys for access",
        "jwt" : {
@@ -21,9 +21,15 @@
        "glusterfs" : {

                "_executor_comment": "Execute plugin. Possible choices: mock, ssh",
-               "executor" : "mock",
+               "executor" : "ssh",

                "_db_comment": "Database file name",
-               "db" : "heketi.db"
+               "db" : "heketi.db",
+
+               "sshexec": {
+                       "user": "root"
+               },
+               "brick_min_size_gb": 1
+
        }
 }
```

Then I run the attached *heketisetup.py* script ([heketisetup.py.zip](https://github.com/heketi/heketi/files/203523/heketisetup.py.zip)) that creates loop devices and sets up Heketi clusters / nodes / devices with them as follows:

```
$ ./heketisetup.py -n1 -s 1T -c new -v -D -u root --root -j 'My Secret' `hostname`
```

which can be interpreted as: "create a single 1 TB loop device for Heketi, create a new cluster, on that a node for localhost, add the device to it,  be verbose and print a debug log too; ssh as root, assume that the account ssh'd to is privlleged, use JWT with 'My Secret' as key".

It will fail with a similar error to the one in the original report. (It works fine if we turn JWT off.)

**Comment by lpabon** [comment]
Thanks for finding this @csabahenk .  I'll definitely take a look.

**Comment by csabahenk** [comment]
It turned out that the issue was of my *heketisetup.py* script, not Heketi. The fix is as follows:

```diff
diff --git a/heketisetup.py b/heketisetup.py
index eefc108..4acad6b 100755
--- a/heketisetup.py
+++ b/heketisetup.py
@@ -143,7 +143,7 @@ class HeketiClient(object):
             ) % {'method': method.upper(), 'status': resp.status_code})
         queue = resp.headers['location']
         while True:
-            resp = self.get(queue)
+            resp = self.get(queue, allow_redirects=False)
             if resp.status_code == 204:
                 return resp
             elif resp.status_code == 303:
 ```

Ie. when making HTTP requests to Heketi with [requests](https://github.com/kennethreitz/requests), [allow_redirects=False](http://docs.python-requests.org/en/master/user/quickstart/#redirection-and-history) has to be specified, at least in the case of waiting for the result of an [asynchronous operation](https://github.com/heketi/heketi/wiki/API#async), so that the client can have complete control over the request made to the redirect target, in particular to be able to customize the JWT data according to the redirect target url.

**Comment by lpabon** [comment]
This is great information.  I really appreciate the work you did here @csabahenk .  Thank you very much for the help.
