### ISSUE TITLE
heketi-cli should use Linux style flags

### ISSUE THREAD

**Issue by lpabon** [heketi/heketi#267]
Currently, heketi-cli uses Golang flags package.  Instead it should use a package which provides the same Linux flags style as all other programs.  Kubectl uses a package which could be used here also.

**Comment by lpabon** [comment]
Kubernetes uses https://github.com/spf13/cobra as shown in [cmd.go#28](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/cmd.go#L28).  In [cmd.go#161](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/cmd.go#L161) it shows an example of adding subcommands.  In this example it added [NewCmdGet](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/get.go#L73).

We should mimic the same behavior.

**Comment by lpabon** [comment]
I can see how the [Run](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/get.go#L89) function pointer could map instead to an anonymous function calling [Exec](https://github.com/heketi/heketi/blob/master/client/cli/go/commands/device_add.go#L68).

**Comment by MohamedAshiqrh** [comment]
Using pflag has [https://github.com/spf13/pflag/issues/70](issue) with sub-command help command.

**Comment by lpabon** [comment]
Solved by #283
