### ISSUE TITLE
Implement topology view for heketi-cli command

### ISSUE THREAD

**Issue by humblec** [heketi/heketi#276]
There should be a topology view which dumps to standard out the entire topology of the system either in json format (yml format in future releases).  This will enable the administrator to easily view all GlusterFS clusters, nodes, and devices using a single command.

**Comment by humblec** [comment]
afaict, we dont need a 'route of topology' and it can be client specific, can u please confirm ?

**Comment by lpabon** [comment]
Here is an example output in JSON format:

```json
{ "clusters" : [
		{
			"id" : "asdf",
			"nodes" : [
				{
					"id": "asdfasdf",
					"devices" : [
						{
							"id" : "asdfasdf"
						}
					]
				}
			]
		}
	]	
}
```

Here is its possible Go structs

```go
type Node struct {

}

type Nodes struct {
	Nodes []Node
}

type Cluster struct {
	Id string `json:"id"`
	NodeList Nodes `json:"nodes"`
}

type Topo struct {
	ClusterList []Cluster `json:"clusters"`
}
```

**Comment by lpabon** [comment]
Also, we need to push down "load" into "topology load...", and then to view the topology, we can type "topology view".. or "topology info"..
