### ISSUE TITLE
Make ssh port configurable 

### ISSUE THREAD

**Issue by humblec** [heketi/heketi#287]
Make ssh port configurable in heketi instead of hard coded 22 port, so that admin can use that option if needed

**Comment by lpabon** [comment]
This should bet set using the [Node Add API](https://github.com/heketi/heketi/wiki/API#node_add) where a new key called _ssh_ should have another key named _port_ which takes an _int_.  If you need some help with the code and design let me know.

**Comment by lpabon** [comment]
@humblec Do you mind providing a small paragraph on how you plan on implementing?  Just an idea of the workflow would be great.

**Comment by humblec** [comment]
@lpabon Considering the possibility that, the ssh configuration will be consistent in an environment , we could make it configurable in 'sshexec ' section in heketi configuration file as you can see here  https://github.com/heketi/heketi/pull/288 . What do you think?

**Comment by lpabon** [comment]
Closed by #288
