### ISSUE TITLE
Configure if sudo should be used in SSH

### ISSUE THREAD

**Issue by lpabon** [heketi/heketi#289]
Ssh exec should check if "sudo" : true .  If it is, it will use sudo to execute commands.

**Comment by lpabon** [comment]
Some systems do not have sudo installed.

**Comment by humblec** [comment]
@lpabon I dont think thats the right approach. I have a different workflow in mind. I will update it here soon.

**Comment by humblec** [comment]
@lpabon here it is https://github.com/heketi/heketi/pull/299
