### ISSUE TITLE
Topology load command should not add first node if gluster rpms are not installed.

### ISSUE THREAD

**Issue by NehaRawat** [heketi/heketi#290]
heketi-cli load doesn't check if nodes have gluster rpms. It will add first node successfully even system does not have gluster.

It will only fail for second node i.e "gluster peer probe command"
gluster: command not found

**Comment by lpabon** [comment]
Hi Neha,
  Gluster should have been setup before using Heketi, it is a requirement.  See [Requirements](https://github.com/heketi/heketi/wiki/Usage-Guide#requirements).

**Comment by lpabon** [comment]
And one more thing, we will be most likely removing the requirement on `sudo`.  See #289 .
