### ISSUE TITLE
Heketi-cli volume create redundancy should be taking a string

### ISSUE THREAD

**Issue by lpabon** [heketi/heketi#311]
Currently it says:

```
  --redundancy int          
        Optional: Redundancy value for durability type 'disperse'.
        Default is 2 (default 2)
```

Please see previous heketi-cli argument which used a string value

**Comment by MohamedAshiqrh** [comment]
@lpabon By "previous" do you mean previous heketi-cli, If so it did have redundancy as integer.
https://github.com/heketi/heketi/blob/7a6cf957b623da73297d45d7d193c6a9231f6767/client/cli/go/commands/volume_create.go#L65
