### ISSUE TITLE
Heketi-cli: Error handling 

### ISSUE THREAD

**Issue by NehaRawat** [heketi/heketi#327]
Currently Heketi-cli doesn't provide proper error messages for most of the options

For example

heketi-cli volume create --name=testvol --size=10 --durability="replicate"  --replica=2
Error: Process exited with: 1. Reason was:  ()

Heketi-logs:

Err[Process exited with: 1. Reason was:  ()]: Stdout []: Stderr [volume create: testvol: failed: Volume testvol already exists
]

**Comment by lpabon** [comment]
Yeah I agree, they are terrible messages :smile: .

Duplicate of #171

**Comment by lpabon** [comment]
Closed by #366
