### ISSUE TITLE
When deleting a volume, check if it exists

### ISSUE THREAD

**Issue by lpabon** [heketi/heketi#33]
Check if the glusterfs volume is running in the cluster.  Return an error accordingly if it **was** in the db but **not** in the cluster.

**Comment by gaurav36** [comment]
@lpabon  while deleting a volume, in VolumeDelete function you are already checking whether volume exists or not by using volume id. 
if v, ok := m.db.volumes[id]; ok {
        volume = v
        delete(m.db.volumes, id)
} else {
        return errors.New("Volume id not found")
}


can you tell something more about this issue.

**Comment by lpabon** [comment]
Yes, good point.  I should have placed more information.  I meant that it should check that the glusterfs volume still exists, not just on the db but also in the cluster.

**Comment by lpabon** [comment]
This is not needed
