### ISSUE TITLE
No space error if creating replica 3 volume on two node cluster

### ISSUE THREAD

**Issue by NehaRawat** [heketi/heketi#331]
Try to create volume with default replica configuration on two node cluster, it will fail with "No space" error though disks have enough space.

heketi-cli volume create --name=vol3 --size=10 
Error: No space

```
May 18 11:12:28 hostname heketi: [heketi] ERROR 2016/05/18 11:12:28 /src/github.com/heketi/heketi/apps/glusterfs/volume_entry_allocate.go:41: Minimum brick size limit reached.  Out of space.
May 18 11:12:28 hostname heketi: [heketi] ERROR 2016/05/18 11:12:28 /src/github.com/heketi/heketi/apps/glusterfs/app_volume.go:128: Failed to create volume: No space

```

if not wrong its  allocBricks function which is returning this error if there is no device found.

 // No devices found
      return ErrNoSpace

There is no functional issue as heketi will not create two replica bricks on same node/device. But it should print proper error message.

**Comment by lpabon** [comment]
Interesting.  Do you mind describing the topology you used?  Also, fyi, try not to use `--name=`, it could create issues.  I'm almost thinking about removing it.

**Comment by NehaRawat** [comment]
* docker exec heketi heketi-cli --server http://localhost:8080 topology info

Cluster Id: 46d613cf778d1a11ab2f36a2dd3dc803

    Volumes:

    Nodes:

	Node Id: 53bb0c58ceaa2042c5088377de9c872f
	Cluster Id: 46d613cf778d1a11ab2f36a2dd3dc803
	Zone: 1
	Management Hostname: 10.70.43.225
	Storage Hostname: 10.70.43.225
	Devices:
		Id:77fddc8c8ed815ab09965095941cf899   Name:/dev/sde            Size (GiB):499     Used (GiB):0       Free (GiB):499     
			Bricks:

	Node Id: d3502d07f469ce0eef1e1a11b16d3756
	Cluster Id: 46d613cf778d1a11ab2f36a2dd3dc803
	Zone: 1
	Management Hostname: 10.70.43.245
	Storage Hostname: 10.70.43.245
	Devices:
		Id:c84bd8d40a04a6e08058bc4a97cccafe   Name:/dev/sdc            Size (GiB):499     Used (GiB):0       Free (GiB):499     
			Bricks:

* docker exec heketi heketi-cli --server http://localhost:8080 volume create --size=10
Error: No space

**Comment by lpabon** [comment]
Ok, I understand, it was trying to create a replica 3 volume but it only has two nodes.  In a way, yes it is true, there is no space, but the error can be better.

**Comment by humblec** [comment]
@lpabon I think we can keep the name option for volume create command. it can be handy in some scenarios. May be we can work on a quick fix on this issue similar to https://github.com/heketi/heketi/pull/336

**Comment by obnoxxx** [comment]
Interestingly, when running the four node vagrant-heketi standalone setup, i also get this error, but only if I specify *too small*: 

```
[vagrant@storage0 ~]$ heketi-cli volume create --size=10
Name: vol_90faf69d33adeb4dae171b8b54c51f22
Size: 10
Volume Id: 90faf69d33adeb4dae171b8b54c51f22
Cluster Id: bac92e2f4adf87159d193576acf7667a
Mount: 192.168.10.100:vol_90faf69d33adeb4dae171b8b54c51f22
Mount Options: backup-volfile-servers=192.168.10.101,192.168.10.102
Durability Type: replicate
Distributed+Replica: 3

[vagrant@storage0 ~]$ heketi-cli volume create --size=1
Error: No space
```

**Comment by humblec** [comment]
Yeah , I have seen the ssh executor fails if the volume size is less than 10G. This limit has to be lifted . I have opened an issue here https://github.com/heketi/heketi/issues/466 
@lpabon in k8s/openshift there can be requests for less than 10G, so we have to allow volume creation of <10G .

**Comment by lpabon** [comment]
@humblec AFAIK, there is no product reason to support volumes of 10G or less.  We will be supporting these in future releases with block support.

**Comment by obnoxxx** [comment]
@humblec I was wondering if this issue and the one you newly raised are actually the same. Or if there is really some corner case that makes replica 3 in a 2-node cluster any special.

After all, in @NehaRawat 's original description, --size=10 failed as well ...  I'd like to know whether bigger sizes also fail on the 2-node system.

**Comment by obnoxxx** [comment]
@lpabon Trying to understand '*there is no product reason to support volumes of 10G or less*': I'd say if supporting <10G volumes requires a lot of extra work, I agree. But from 10 miles above it seems like an artificial limitation. I'd say there is no reason _not_ to support <10G volumes, unless it requires extra effort.

So is the limitation intrinsic to gluster ? or heketi ? (still looking through the heketi code for size checks ...)

**Comment by humblec** [comment]
@obnoxxx there are various places where heketi just returns ErrNoSpace. One of them is replica 3 in 2 node setup. One of the other scenario is "<10G" volume creation..etc. This return definitely has to be improved any way, it cannot be just ENOSPC always without proper reason.  @lpabon Even I dont understand what you mean by 'product' requirement.  More or less,  I still dont understand why it cant support <10G volumes ?

**Comment by obnoxxx** [comment]
This may be an improvement here:

https://github.com/obnoxxx/heketi/commit/df19766fe8d3cec20d590c92ebfa155c2e7c177f

https://github.com/obnoxxx/heketi/tree/error-propagation

**Comment by lpabon** [comment]
If the admin *really* wants to allow for this, all they need to do is set the advanced settings.

See: https://github.com/heketi/heketi/wiki/Running-the-server#advanced-options

**Comment by humblec** [comment]
@lpabon I have seen that limit settings when we were limiting the distribution limit to "32" from "100". However I am still not able to map how the volume limit comes to "8G" when we have BrickMinSize mentioned as (uint64(4 * GB))   https://github.com/heketi/heketi/blob/master/apps/glusterfs/limits.go#L21 .  Is there any parameters taken into account when creating Volumes? I still have to look deeper into the volumecreation code though

**Comment by lpabon** [comment]
@humblec if you want a 5 GB volume, then the brick size should be half of that or at least 2 GB... You can even change it to the minimum which is 1GB:

```
brick_min_size_gb : 1
```

**Comment by humblec** [comment]
@lpabon regardless of error propagation, we have to document this . Because there is no way for a user to know what is the minimum volume size and how the "min_brick_size" is affecting the minimum volume size.

**Comment by bcg62** [comment]
is there a way around this with 2 nodes, or must you have 3?
