### ISSUE TITLE
heketi-cli: Add force option to `cluster delete`

### ISSUE THREAD

**Issue by NehaRawat** [heketi/heketi#343]
With current functionality it is not possible to delete cluster without deleting nodes, devices and volumes.

heketi-cli cluster delete 1a88997bccb170a0a3d8e846d656c746
Error: Conflict

Logs:
[negroni] Started DELETE /clusters/1a88997bccb170a0a3d8e846d656c746
[heketi] WARNING 2016/05/23 09:45:30 Unable to delete cluster [1a88997bccb170a0a3d8e846d656c746] because it contains volumes and/or nodes
[negroni] Completed 409 Conflict in 11.957814ms

Add functionality to delete cluster with "force" option.

**Comment by lpabon** [comment]
Hi Neha,  This works as designed. A --force which is done by mistake could be extremely catastrophic.  Instead, --force is normally used for testing/dev/qe, therefore a small python script using the heketi-python library can do this.

**Comment by NehaRawat** [comment]
Agree Luis. I have created this issue as an enhancement for easy cleanup  but yes we can use API script to achieve this.

**Comment by lpabon** [comment]
If you want, you can create a python script/program to do this and submit it to this repo under a `hack/` directory?  Kubernetes has something like this also here:  https://github.com/kubernetes/kubernetes/tree/master/hack

**Comment by lpabon** [comment]
@NehaRawat ^^

**Comment by NehaRawat** [comment]
@lpabon sure can do that.
