### ISSUE TITLE
heketi-cli: proper error message for cluster/node/device delete

### ISSUE THREAD

**Issue by NehaRawat** [heketi/heketi#355]
It is not possible to delete cluster without deleting nodes, devices and volumes.  

=> docker exec heketi heketi-cli --server http://localhost:8080 cluster delete 46d613cf778d1a11ab2f36a2dd3dc803
Error: Conflict

Logs:
[negroni] Started DELETE /clusters/46d613cf778d1a11ab2f36a2dd3dc803
[heketi] WARNING 2016/05/27 12:01:01 Unable to delete cluster [46d613cf778d1a11ab2f36a2dd3dc803] because it contains volumes and/or nodes
[negroni] Completed 409 Conflict in 466.033µs

=>docker exec heketi heketi-cli --server http://localhost:8080 node delete 53bb0c58ceaa2042c5088377de9c872f
Error: Conflict

Logs:
[negroni] Started DELETE /nodes/53bb0c58ceaa2042c5088377de9c872f
[negroni] Completed 409 Conflict in 323.013µs

=> docker exec heketi heketi-cli --server http://localhost:8080 device delete 77fddc8c8ed815ab09965095941cf899
Error: Conflict

Logs:
[negroni] Started DELETE /devices/77fddc8c8ed815ab09965095941cf899
[negroni] Completed 409 Conflict in 368.05µs

Should display proper error message to STDOUT.
For nodes and devices it doesn't log proper message in logs too. Creating a new issue to track it because if not wrong https://github.com/heketi/utils/commit/34e5a97154d1d016635ad6ce436a68fdc8a75876 will not fix this one.

**Comment by lpabon** [comment]
Good point. This should be fixed.
