### ISSUE TITLE
Need information on Ring

### ISSUE THREAD

**Issue by kshlm** [heketi/heketi#37]
@lpabon Can you add some documentation on how you plan to use Swift's ring? From what I read about, ring seems to be Swift specific. How will heketi be hooking into it?

**Comment by lpabon** [comment]
Hi @kshlm, you can find information about the Swift rings here:  

http://docs.openstack.org/developer/swift/overview_ring.html

I will also be adding some documentation to the wiki on the algorithms used to determine brick placement in the cluster.

**Comment by kshlm** [comment]
@lpabon Thanks for the document, it's helpful. But it is not clear to me how Swift ring is going to be used in heketi. Are we going to be using Swift's rings as-is or as a library or, is it being used as an inspiration to build the algorithms you mentioned?

**Comment by lpabon** [comment]
@kshlm You are correct, I still will be adding a document in the wiki on how we plan on using the ring

**Comment by lpabon** [comment]
Took a while, but finally documented the algorithm:  https://github.com/heketi/heketi/wiki/Simple-Ring-Allocator
