### ISSUE TITLE
[RFE] Cluster should support a metadata that describe the tier of storage it contains

### ISSUE THREAD

**Issue by pcuzner** [heketi/heketi#379]
At this point all PV's in OSE 3.2 are treated equally, which means all gluster trusted pools would be made from the same spindle type. In order to improve allocation logic between the developer's pvc and the storage layer, the gluster trusted pools should have a "storage class" attribute which describes the type of physical media the cluster contains. 

the storage class could simply be a represented by gold/silver/bronze ; 
gold = iops centric...SSD's, NVMe
silver = general workload...10k drives
bronze = file archive or low iops demands...7k drives

With this storage class in place, pvc's could be directed to the most appropriate cluster when dynamic provisioning is later implemented.

**Comment by humblec** [comment]
@pcuzner atm, mainly we have provisioner parameters in the storage class. When we have  more QoS like iops, grouping of similar disks..etc  in gluster and also when we have support for different type of volumes..etc , I will add those as storage class parameters in the provisioner.  We also need Heketi's support to implement when we create volumes.

**Comment by MohamedAshiqrh** [comment]
I think this is added upstream kubernetes now by @humblec. Please add appropriate link to doc for future reference @heketi/dev .

**Comment by phlogistonjohn** [comment]
See also:    https://github.com/heketi/heketi/blob/master/docs/design/tag-matching.md

**Comment by phlogistonjohn** [comment]
Mostly implemented. Please open new issues if the feature on master falls short in your use cases.
