### ISSUE TITLE
Minimum brick size errors

### ISSUE THREAD

**Issue by NehaRawat** [heketi/heketi#380]
Current error message for minimum size brick

heketi-cli volume create --size=1
Error: No space

[heketi] ERROR 2016/06/14 02:41:06 /src/github.com/heketi/heketi/apps/glusterfs/volume_entry_allocate.go:41: Minimum brick size limit reached.  Out of space.
[negroni] Started GET /queue/8d662515743827d44875d9bf146d0f19
[negroni] Completed 200 OK in 73.023µs

Should be somewhat similar to logs "Minimum brick size limit reached" instead of "No space"

**Comment by lpabon** [comment]
No, you are viewing this from a GlusterFS point of view.  From a "volume" point of view, however it is implemented, there is no space.

**Comment by obnoxxx** [comment]
```
[vagrant@storage0 ~]$ heketi-cli volume create --size=1
Error: Requested volume size (1 GB) is smaller than the minimum supported volume size (4194304)
```

So this is a duplicate of #506 
(or rather the other way around)
