### ISSUE TITLE
[RFE] Enhance output of cluster info

### ISSUE THREAD

**Issue by NehaRawat** [heketi/heketi#381]
Current cluster info output:

heketi-cli cluster info d3c3e4bbaead43798c265d820c990977
Cluster id: d3c3e4bbaead43798c265d820c990977
Nodes:
410b2c68b6df188f88a69003cb8a757b
87be2837feda3dbe0f2dacd5806828bb
e0862a9ea3988cc24856377d08ab4b2c
Volumes:
050f0bfea5f18b84a1939e3941d58860
0806256a343fd367347ca99e8df0fbaf
15adf7ba1c23263d1d797236f9742aec
15e07377a8d9d1d57d66bf2af17f1202
1db29ec2d38ca04fc3c337d3a58d2078

It would be good if we can display "hostname/IP" with nodes and if possible "volume name" with volume ids to make it more readable.

**Comment by lpabon** [comment]
Topology info handles all this information
