### ISSUE TITLE
topology info: "ID not found" error when running concurrently with volume creation.

### ISSUE THREAD

**Issue by NehaRawat** [heketi/heketi#382]
heketi-cli topology info
Error: Id not found

Logs:
[negroni] Started GET /volumes/1819834f5be2c3dce81b36e14ea440c0
[negroni] Completed 200 OK in 761.725µs
[negroni] Started GET /nodes/410b2c68b6df188f88a69003cb8a757b
[negroni] Completed 500 Internal Server Error in 6.36837ms

500 when fetching node information. As of now not sure why it's failing when running parallely.

**Comment by lpabon** [comment]
If at all possible.  Save the heketi.db and attach it to this bug.  If it is in a container, you may need to attach a new host volume, then rsh into the container and copy the /var/lib/heketi/heketi.db to that host volume.

**Comment by lpabon** [comment]
@NehaRawat Sounds like the test was concurrently creating and deleting volumes while you ran `heketi-cli topology info`.  Is that correct?

**Comment by NehaRawat** [comment]
@lpabon I hit this issue during volume creation. Will not hit this issue if we just try to create a single volume as it returns quickly. 

Easily reproducible If we try to create volume in loop say 5-10 volumes and then run "topology info" in another terminal.

**Comment by lpabon** [comment]
@NehaRawat ok, but in the loop, did you delete the volumes or just create.

**Comment by NehaRawat** [comment]
@lpabon just create.

**Comment by lpabon** [comment]
Great, thanks @NehaRawat

**Comment by lpabon** [comment]
[BZ 1346621](https://bugzilla.redhat.com/show_bug.cgi?id=1346621)

**Comment by MohamedAshiqrh** [comment]
For some reason 

DB is not returning any value, only in case of nodeId while volume create is in progress.
This is where we are hitting but not sure why we are hitting when volume create.
https://github.com/heketi/heketi/blob/master/apps/glusterfs/dbentry.go#L137

Now looking into volume create to find more...Will keep updating.

**Comment by MohamedAshiqrh** [comment]
Node Info and Device Info are returning "Id not found" for valid id's, when volume create is in progress. Have created an easier setup to try out heketi code changes as pod on openshift. Not able to find anything suspicious yet.

**Comment by MohamedAshiqrh** [comment]
https://github.com/MohamedAshiqrh/heketi/tree/ninfo

This is where all the test code progresses. If anyone is interested.

**Comment by MohamedAshiqrh** [comment]
https://github.com/heketi/heketi/pull/575
