### ISSUE TITLE
Make it possible to run the functional tests with nightly Gluster builds

### ISSUE THREAD

**Issue by nixpanic** [heketi/heketi#396]
Gluster provides nightly builds for different stable versions. It would be most welcome if there is an option to run the functional tests with the nightly builds. Different `.repo` files for yum are available from the [artifacts server](http://artifacts.ci.centos.org/gluster/nightly/).

**Comment by lpabon** [comment]
Passed functional tests

**Comment by nixpanic** [comment]
This request is different from the merged change. I'd like to be able to run the functional tests with either an environment variable or a commandline parameter that causes it to use a different (in addition to) the standard centos-release-gluster package/repository. The packages by default are only glusterfs-3.7.x (atm), not packages from the master branch. It would be beneficial to test with the upstream GlusterFS master branch. Incompatible changes in Gluster can get caught early that way.

**Comment by lpabon** [comment]
This is really cool.  Do you need anything from us @nixpanic ?

**Comment by nixpanic** [comment]
@MohamedAshiqrh could you have a look at this?

**Comment by phlogistonjohn** [comment]
Very stale issue. Closing.
