### ISSUE TITLE
[RFE] Add "node list" option in heketi-cli

### ISSUE THREAD

**Issue by NehaRawat** [heketi/heketi#405]

**Comment by raghavendra-talur** [comment]
In Progress, I have a WIP commit at https://github.com/raghavendra-talur/heketi/commit/7c568db82494cdf94c7d69546ac2f36114316479 .

Will test and create a pull request.

**Comment by obnoxxx** [comment]
@raghavendra-talur see a few rather superficial comments on the wip patch

**Comment by lpabon** [comment]
@raghavendra-talur Hi, there is no need to add a new API for this.  This is a CLI request, not an API one.  

From the CLI, you can achieve the same by using the following algorithm:

```go

clusters := ClusterList()
for c in clusters {
    clusterInfo := ClusterInfo(c)
    for node in clusterInfo.Nodes {
        print "Cluster:%s     Node:%s", clusterInfo.Id, NodeInfo.Id
    }
}
```
