### ISSUE TITLE
volume info does not give correct info about "volume Type"

### ISSUE THREAD

**Issue by NehaRawat** [heketi/heketi#406]
by default heketi creates [2x3] dist-rep volume. 

from backend 
gluster v info heketidbstorage

Volume Name: heketidbstorage
Type: Distributed-Replicate
Volume ID: 0e7454d6-8480-439f-aece-24cc9bbb7f73
Status: Started
Number of Bricks: 2 x 3 = 6

 heketi-cli volume info 957e45607f971726a2047cfbc31d1bd0
Name: heketidbstorage
Size: 32
Volume Id: 957e45607f971726a2047cfbc31d1bd0
Cluster Id: 7c8a051e52a7be6624b4bea1825eab82
.......................................................................................
Durability Type: replicate
Replica: 3
Snapshot: Disabled

**Comment by obnoxxx** [comment]
Is this really an issue?

I think the complaint is that gluster says: "Type: Distributed-Replicate" while heketi-cli says " Durability Type: replicate". @NehaRawat are you missing the 'Distributed' here?

But note that heketi-cli does not claim to list the exact gluster volume-type but the durability type! This is replicate, no matter how many bricksets we have. Also, heketi does not give any guarantees as to how many bricksets it will give. For instance PR #482 makes it possible to create 1x3 volumes if the drives are big enough. For a 1x3 volume the durabilty type is replica. The same is true for a 10x3 volume.

So I'd say that heketi is correct.
But you could request an enhancement that heketi-cli also print out the exact gluster volume type.

**Comment by lpabon** [comment]
@obnoxxx I agree with your statement.

**Comment by NehaRawat** [comment]
@obnoxxx @lpabon agree we can have it as a enhancement as heketi only supports distributed volumes.  
we can close this and create new issue to avoid confusion ?

**Comment by obnoxxx** [comment]
@NehaRawat I'd be fine with rewording the issue title. But note that PR #482 would introduce potential support for non-distribute but replicate volumes if pushed. And note that heketi is really kind of indifferent about the distribute part. - Only the replicate part really counts.

**Comment by lpabon** [comment]
@NehaRawat @obnoxxx I think we should just remove "Volume Type" from the CI output, and reduce confusion.  It already has "number of bricks"

**Comment by obnoxxx** [comment]
@lpabon I don't think there is Volume Type in the output of heketi? I personally don't yet understand that we have an issue at all. Just a different expectation from someone coming from the Gluster side? 

The paste above with the distribute-replicated is the "gluster volume info" command, not from heketi.

**Comment by obnoxxx** [comment]
closing. this is not a but, but a misunderstanding.
