### ISSUE TITLE
Snapshot management

### ISSUE THREAD

**Issue by lpabon** [heketi/heketi#413]
Heketi should have a snapshot management API

**Comment by lpabon** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1351450

**Comment by nixpanic** [comment]
The [external-storage snapshot user-guide](https://github.com/kubernetes-incubator/external-storage/blob/master/snapshot/doc/user-guide.md) describes the common functionality:

- create snapshot from a PV
- promote snapshot to PV (sortof PV cloning functionality)
- restore a PV from a snapshot
- delete snapshot

**Comment by humblec** [comment]
Yes, it would be good to implement snapshot functionality in heketi so that it can be plugged with the controller. WIP patch is available for kube side of things @https://github.com/humblec/external-storage/commit/1ee96627f14fb092575d6b0f89e50aba87755944

**Comment by akram** [comment]
@humblec snpashot is an offline operation, how does the k8s volume plugin manage it ?

**Comment by MartinForReal** [comment]
@akram I think the user scenario is clearly stated in external-storage snapshot user-guide.

**Comment by phlogistonjohn** [comment]
I do not think we will pursue this item. Closing issue. Please reopen if this is still relevant.
