### ISSUE TITLE
heketi-cli should display help, when invoked

### ISSUE THREAD

**Issue by lpabon** [heketi/heketi#415]
heketi-cli should at least display help, when invoked.

Presently, you get nothing in the o/p, should give usage/help.

```
[root@dhcp42-41 ~]# heketi-cli 
[root@dhcp42-41 ~]#
```

**Comment by MohamedAshiqrh** [comment]
PR : https://github.com/heketi/heketi/pull/410

**Comment by lpabon** [comment]
@MohamedAshiqrh What is the status on this issue?

**Comment by MohamedAshiqrh** [comment]
I do not think we will be able to do this with cobra. Cobra command without [run func](https://github.com/heketi/heketi/blob/master/client/cli/go/cmds/cluster.go#L41) returns help(Usage) when called. In this case, we have [run](https://github.com/heketi/heketi/blob/master/client/cli/go/cmds/root.go#L47) to display version. As we have run function, [initconfig](https://github.com/heketi/heketi/blob/master/client/cli/go/cmds/root.go#L72) runs before the run function which checks for the server name. So,

if server name is provided It will work.
Or
If we make version a separate command, we can achieve what we are trying for. As we dont need run function for heketi-cli.

What do you think @lpabon ?

**Comment by obnoxxx** [comment]
could this be a possible fix?

https://github.com/obnoxxx/heketi/commit/b89bb1830cf48453d6a4299a4d62d8e194cd7af7

https://github.com/obnoxxx/heketi/tree/cli-print-root-usage

(ignoring the case of server not set in env var , which I think is a separate issue)

**Comment by obnoxxx** [comment]
I need to learn how to compile and test it... :-)

**Comment by lpabon** [comment]
@obnoxxx Maybe!  Definitely good opportunity to compile and test.

Go to the top of the tree and type: `make`.

This will build the server and the cli.  From one terminal type:

```
$ cp etc/heketi.json heketi.json
$ vi heketi.json  <--- Change "db" to --> "db": "heketi.db",
$ ./heketi -config=heketi.json
Heketi v2.1.0-dev-2-gcb07059
[heketi] INFO 2016/09/02 11:52:09 Loaded mock executor
[heketi] INFO 2016/09/02 11:52:09 Loaded simple allocator
[heketi] INFO 2016/09/02 11:52:09 GlusterFS Application Loaded
Listening on port 8080
```

On another terminal:

```
$ export HEKETI_CLI_SERVER=http://localhost:8080
$ cd client/cli/go
$ ./heketi-cli cluster list
...
```

**Comment by lpabon** [comment]
FYI, i added this to https://github.com/heketi/heketi/wiki/Development-Guide#trying-out-your-code

**Comment by obnoxxx** [comment]
Just created PR #477  with an alternative (modified) patch to PR #410.
