### ISSUE TITLE
Heketi should have a configurable value for setting up max number of snapshots in a volume

### ISSUE THREAD

**Issue by lpabon** [heketi/heketi#419]
There needs to be a configurable value in the config file and in the environment variable which will be able to set the max number of snapshots in a volume

**Comment by MohamedAshiqrh** [comment]
@lpabon Hey, can I know where this value been used or set.

I can not find the place it sets the value on gluster snapshot

**Comment by MohamedAshiqrh** [comment]
I can see from the [PR](https://github.com/heketi/heketi/issues/437) that sshexec has the snapshot limit setting but when using kubeexec. There is not a place where we set this limit. Let me know If I am wrong.
