### ISSUE TITLE
Deploy-heketi template needs a setting for max snapshots

### ISSUE THREAD

**Issue by lpabon** [heketi/heketi#446]
See: https://github.com/heketi/heketi/blob/master/extras/openshift/templates/heketi-template.json#L116

**Comment by MohamedAshiqrh** [comment]
https://github.com/heketi/heketi/pull/447

**Comment by lpabon** [comment]
@MohamedAshiqrh Do you mind creating a backport to release/2 branch?

**Comment by lpabon** [comment]
@MohamedAshiqrh Do not worry about backport.  We will release 3 at the end of this month.  Hopefully :-D

**Comment by lpabon** [comment]
Closed by #447
