### ISSUE TITLE
Installer for OpenShift

### ISSUE THREAD

**Issue by lpabon** [heketi/heketi#451]
Need a method (ansible or script) to install Heketi and Gluster containers in OpenShift

**Comment by obnoxxx** [comment]
@jarrpa assigning to you based on our discussion.

**Comment by jarrpa** [comment]
This has evolved to become https://github.com/gluster/gluster-kubernetes . :)

**Comment by obnoxxx** [comment]
done by gk-deploy in https://github.com/gluster/gluster-kubernetes
