### ISSUE TITLE
Godep restore fails ..

### ISSUE THREAD

**Issue by humblec** [heketi/heketi#455]
```
# cd .; git clone https://code.google.com/p/go-decimal-inf.exp /home/user/gocode/work/src/speter.net/go/exp/math/dec/inf
Cloning into '/home/user/gocode/work/src/speter.net/go/exp/math/dec/inf'...
fatal: repository 'https://code.google.com/p/go-decimal-inf.exp/' not found
godep: error downloading dep (speter.net/go/exp/math/dec/inf): exit status 128
godep: Error downloading some deps. Aborting restore and check.
```

**Comment by humblec** [comment]
@lpabon have u seen this failure recently? Looks like the repo has been moved.

**Comment by lpabon** [comment]
Do you need to run godep restore?  OpenShift's godep uses repo commits from its own repos with names for generic repos.  For example, kubernetes commit hashes for the hashes for github.com/openshift/kubernetes, even though they use them for k8s.io/kubernetes

**Comment by humblec** [comment]
@lpabon I was trying to point out the godep restore failure especially with the https://code.google.com/p/go-decimal-inf.exp repo.  Eventhough I dont really want this, it should work seemlessly, Isnt it ?.

**Comment by lpabon** [comment]
I agree it should if openshift did the right thing, but they don't.  Checkout https://github.com/openshift/origin/blob/master/hack/godep-save.sh

**Comment by lpabon** [comment]
Maybe we could create a `hack/godep-save.sh` just like them.

**Comment by lpabon** [comment]
Here is another: https://github.com/openshift/origin/blob/master/hack/godep-restore.sh

**Comment by humblec** [comment]
@lpabon yeah, may be a hack/godep-save.sh is required in heketi. Because now heketi's dependency chain (heketi->openshift->k8s..etc)  is really heavy and difficult to manage :).

**Comment by ramkrsna** [comment]
Do we have to check the dependency from Heketi -> OpenShift -> Kubernetes, or just the openshift < - > Heketi would suffice ?

**Comment by lpabon** [comment]
@ramkrsna openshift to Heketi is enough, because openshift has a dep on Kube.

**Comment by ramkrsna** [comment]
@heketi/dev @obnoxxx Could we explore the option of vendorizing heketi . i.e  As of Go 1.6, it will first look at the dependancies in the .vendor folder, if it does not find dependencies  in there, then it will look for the source directories in the GOPATH

**Comment by lpabon** [comment]
@ramkrsna I'm not sure what you mean, but that is what we do today.  The issue highlighted here is how we update that vendor directory, which is complicated due to openshift's kubernetes own repo acting as the kubernetes real repo.
