### ISSUE TITLE
Need to check if we have unit tests to test cluster resizing

### ISSUE THREAD

**Issue by lpabon** [heketi/heketi#461]
We need to check if we have unit tests which test increasing available Heketi storage by adding devices, nodes, and/or clusters.

**Comment by lpabon** [comment]
Unit tests should test https://github.com/heketi/heketi/wiki/Managing-your-clusters

**Comment by ramkrsna** [comment]
## Testing Specification for Increasing Available Nodes :: 
---------------------------------------------------------------------
### -  Adding a Devices
1. CLI - test argument, to check valid parameters 
2. API -> AddDevice -> RESTFUl API | POST
3. topology.json -> test rerun mock

### -  Adding Nodes or Increase Cluster Size 
-----------------------------------------------------
1. CLI - add node + register device to the added node 
2. API - /nodes POST
3. topology.json -> mock test to Add Node information after existing ones, test function in heketi to figure out the cluster on which node
### 
-  Adding Clusters i.e Adding an Entire New Cluster
-----------------------------------------------------------------  
1. CLI
2. API
3. topology.json file object

### - Reduce Storage Capacity
----------------------------------
1. CLI
2. API  

user roles 
-------------
role :: admin  :: Manage -> Single Gluster Cluster
role :: admin  :: Manage ->  Multiple Cluster

**Comment by lpabon** [comment]
@ramkrsna For the unit tests, only concentrate on the API, do not use the cli or topology file.  @MohamedAshiqrh will be working on a ci system for the cli in the future.  This will make it easier.

For functional tests, you can (after this fix) look at `tests/functional/...` and create a new functional test which checks the heketi-cli and topology file.

**Comment by ramkrsna** [comment]
https://github.com/ramkrsna/heketi/tree/issue461.  Its failing to trigger a test. 
 godep go test -v -run TestVolumeClusterResizeByAddingNodes
=== RUN   TestVolumeClusterResizeByAddingNodes
--- PASS: TestVolumeClusterResizeByAddingNodes (0.03s)
PASS
ok  	github.com/heketi/heketi/apps/glusterfs	0.047s

**Comment by lpabon** [comment]
@ramkrsna I'm not sure what you mean, but after looking at https://github.com/heketi/heketi/compare/master...ramkrsna:issue461 it looks like you didn't create a volume to use the entire storage on [line  1064](https://github.com/heketi/heketi/compare/master...ramkrsna:issue461#diff-909cb6f9e5abeccc6c4e18978e220fd0R1064).  It should consume all storage, then try to create a volume and expect failure.  Then add more storage.  Then create a volume and use all storage, expect success. Then create another volume and expect failure.

**Comment by ramkrsna** [comment]
#532 After adding the nodes and registering the devices to that nodes. I have followed the above suggestion. @heketi/dev could you review the patch

**Comment by ramkrsna** [comment]
@obnoxxx I'm reworking on the unit tests will send a fresh patch for this particular unittest by end of this week.

**Comment by phlogistonjohn** [comment]
Issue has not seen any real activity in more than almost two years. Unit test coverage has changed significantly since last comment. Closing.
