### ISSUE TITLE
GlusterFS adapter updates in Kubernetes

### ISSUE THREAD

**Issue by lpabon** [heketi/heketi#465]
* https://github.com/kubernetes/kubernetes/pull/31869
* https://github.com/kubernetes/kubernetes/pull/31854
* https://github.com/kubernetes/kubernetes/issues/31871

**Comment by lpabon** [comment]
Endpoints: https://github.com/kubernetes/kubernetes/issues/28791

**Comment by humblec** [comment]
secret patch https://github.com/humblec/kubernetes/commit/6cf2fa7058241f0a86d83db8e829755f731b73e6 is part of above PR now.

**Comment by lpabon** [comment]
@humblec awesome

**Comment by lpabon** [comment]
https://github.com/kubernetes/kubernetes/pull/31616 - Making servers list an additional option for GlusterVolumeSource

**Comment by lpabon** [comment]
Kubernetes Issue for Endpoints: https://github.com/kubernetes/kubernetes/issues/28791 - Jul 11

**Comment by lpabon** [comment]
All issues described here have been closed
