### ISSUE TITLE
Allow <10G volume creation in Heketi

### ISSUE THREAD

**Issue by humblec** [heketi/heketi#466]
At present, if we try to create volumes < 10G , the user get 'NoSpace' error. We have to remove this limitation as there can be volume creation requests of small size in Openshift/Kubernetes.

**Comment by obnoxxx** [comment]
It seems 8G is the magic threshold in my 4-node vagrant-heketi test setup:

```
[vagrant@storage0 ~]$ heketi-cli volume create --size=2
Error: No space

[vagrant@storage0 ~]$ heketi-cli volume create --size=3
Error: No space

[vagrant@storage0 ~]$ heketi-cli volume create --size=4
Error: No space

[vagrant@storage0 ~]$ heketi-cli volume create --size=5
Error: No space

[vagrant@storage0 ~]$ heketi-cli volume create --size=6
Error: No space

[vagrant@storage0 ~]$ heketi-cli volume create --size=7
Error: No space

[vagrant@storage0 ~]$ heketi-cli volume create --size=8
Name: vol_c76ed273f064db70ba44256fd6d83e4f
Size: 8
Volume Id: c76ed273f064db70ba44256fd6d83e4f
Cluster Id: bac92e2f4adf87159d193576acf7667a
Mount: 192.168.10.100:vol_c76ed273f064db70ba44256fd6d83e4f
Mount Options: backup-volfile-servers=192.168.10.101,192.168.10.103
Durability Type: replicate
Distributed+Replica: 3
[vagrant@storage0 ~]$ 
```

**Comment by humblec** [comment]
Yep, even I was able to create 8G volume at times, but not always. But I never got success in <8G

**Comment by obnoxxx** [comment]
Better error propagation may already help here?

https://github.com/obnoxxx/heketi/commit/df19766fe8d3cec20d590c92ebfa155c2e7c177f

https://github.com/obnoxxx/heketi/tree/error-propagation

**Comment by lpabon** [comment]
See #331

**Comment by humblec** [comment]
@obnoxxx @lpabon regardless of error propagation, we have to document this . Because there is no way for a user to know what is the minimum volume size and how the "min_brick_size" is affectging the minimum volume size.
