### ISSUE TITLE
Create troubleshooting guide in Wiki

### ISSUE THREAD

**Issue by lpabon** [heketi/heketi#478]
We need to create a troubleshooting guide based on the BZs, and any other information we can provide to users.

**Comment by lpabon** [comment]
Please fill in this page: https://github.com/heketi/heketi/wiki/Troubleshooting-Guide

**Comment by phlogistonjohn** [comment]
There is now a troubleshooting doc in the heketi docs dir. As always, docs of this type need more attention, but it exists and has some content. More specific issues and PRs for that document can be opened.

This issue has not had any activity for over a year. Closing.
