### ISSUE TITLE
Kubernetes Dynamic Provisioner needs unit tests

### ISSUE THREAD

**Issue by lpabon** [heketi/heketi#489]
The Kubernetes provisioner needs to have unit tests so that it can be tested with a running Heketi server.

See Heketi Go Client API unit tests as example.

**Comment by humblec** [comment]
It is WIP.

**Comment by lpabon** [comment]
@humblec please attach the PR when ready.

**Comment by phlogistonjohn** [comment]
This issue has not seen any activity in about two years. Closing issue.
