### ISSUE TITLE
Kubernetes dynamic provisioner does not use Replica 3

### ISSUE THREAD

**Issue by lpabon** [heketi/heketi#494]
The current implementation of Kubernetes provisioner sets up a distributed volume, but not a Distributed-Replica 3 volume.  The API request for a volume must specify the durability type and amount.  See image:

![dp](https://cloud.githubusercontent.com/assets/3880001/18500307/73770d28-7a14-11e6-8096-68bcd643aa62.png)

I used [minikube](http://bit.ly/2cFfaue) to setup and test.

**Comment by humblec** [comment]
@lpabon IMO, the server has to set the 'default volume type' ( same as the cli command does `heketi-cli volume create --size=100 ...` )  if client dont fill it. Can you share your thoughts?

**Comment by obnoxxx** [comment]
@humblec @lpabon My thoughts (after discussing with humble):

* we should first put reasonable defaults into the kubernetes provisioner, i.e. replica 3, (so that result does not change when heketi changes)
* then we can separately discuss changing default in heketi
* later we can think about exposing choice of volume type to kubernets end user

my 2 cents

**Comment by obnoxxx** [comment]
Note that the defaults for replica 3 as created from the heketi-cli are also in the client code, not in the server : `client/cli/go/cmds/volume.go:60--66`

**Comment by humblec** [comment]
@lpabon @obnoxxx Is distribute-replica(3) volumes we always recommend/suggest?

**Comment by lpabon** [comment]
There is a big difference between a human interface (CLI) and an API.  The CLI will have defaults and try to make things simple for the human.  The API is a contract between two software components. 

There are no defaults in the API.  It will act on the requests as instructed.  A Replica of 0 is no replication as documented in the API page.

**Comment by lpabon** [comment]
Awesome.  Issue has been merged.
