### ISSUE TITLE
heketi-cli device add fails with "Error: Unable to execute command on gluster-1:   Device /mnt not found (or ignored by filtering)"

### ISSUE THREAD

**Issue by sofo110111e** [heketi/heketi#501]
Hello,

I am trying to add a device in gluster-1 pod but I am getting "Unable to execute command on gluster-1:   Device /mnt not found (or ignored by filtering)". How could I resolve this issue

**Comment by MohamedAshiqrh** [comment]
Hi @sofo110111e ,

Can you Update more about your setup? and also the exact command which throw this error. so that it will be easy to debug the issue. 

# oc get node --show-labels 
or if you are using kube 
# kubectl get node --show-labels

and exact heketi-cli device add command.

**Comment by MohamedAshiqrh** [comment]
I think what you are trying to do is 
# heketi-cli device add /mnt

heketi can use only raw devices.

**Comment by MohamedAshiqrh** [comment]
I tried the same and got the same error.
```
$ heketi-cli device add --node=8ff6dfa0adb462cec426a7c52cf35c03 --name=/mnt
Error: Unable to execute command on glusterfs-dc-192.168.10.101-1-gzyuw:   Device /mnt not found (or ignored by filtering).
```

**Comment by sofo110111e** [comment]
Hi,

This is the information you asked:

kubectl get node --show-labels
NAME        STATUS    AGE       LABELS
127.0.0.1   Ready     21d       kubernetes.io/hostname=127.0.0.1

heketi-cli device add --name=/mnt --node=3b501e264a1aa3bfe5533464af4d9cc6

**Comment by MohamedAshiqrh** [comment]
@sofo110111e yeah, so you can not use "/mnt" because /mnt is not a device and heketi can make use of clean(empty) raw devices. Refer the [link](https://github.com/heketi/heketi/wiki/Managing-your-clusters#newdevices).

**Comment by sofo110111e** [comment]
@MohamedAshiqrh 
What is so the device I have to add for my gluster running in a pod?

How can I test it?  I do not know what device to add.

**Comment by MohamedAshiqrh** [comment]
@sofo110111e 
You need Three gluster pods and minimum one device per pod. Lets see if you have any devices, can you exec into the pods and do` # pvs ` they will list the devices available.

**Comment by MohamedAshiqrh** [comment]
`# pvs
  PV         VG                     Fmt  Attr PSize  PFree
  /dev/vda2  fedora_fedora22-server lvm2 a--  19.51g    0 `

It will print something like above.

**Comment by lpabon** [comment]
Hi @sofo110111e, like @MohamedAshiqrh pointed out, the storage provided to Heketi is raw block storage, not file systems.  If you want to try out Heketi and become more familiar with it, try out the demos at:

https://github.com/heketi/vagrant-heketi

**Comment by lpabon** [comment]
I also updated the wiki to explicitly document the use of raw block storage:

https://github.com/heketi/heketi/wiki/Setting-up-the-topology#loading-a-topology-with-heketi-cli

Thank you @sofo110111e for pointing it out.
