### ISSUE TITLE
heketi-cli volume create fails Error No space (volume_entry_allocate.go (66) Id not found

### ISSUE THREAD

**Issue by sofo110111e** [heketi/heketi#507]
Hello,

While running heketi-cli volume create --size=11 --replica=1 --redundancy=1  --durability=none --persistent-volume-endpoint=10.0.2.15 --clusters=7b377075af001357f34c748df02d1ebc

... I get the error below. 
Please be more specific how to create volume in gluster kubernetes pods. Is it the existence of a raw device a prerequisite? Can you describe the steps one by one how could someone use heketi-cli volume create for a glusterfs pod? What should look like the ep, pv, pvc, svc and gluster pod manifest files (yaml or Json no matter). It is nowhere clear of the exact steps except for ssh cases without kubernetes but this is not my case.

Sep 20 19:54:47 localhost.localdomain heketi[722]: [asynchttp] INFO 2016/09/20 19:54:47 Started job 62022beb0b0525afbe1fcf827f30a693
Sep 20 19:54:47 localhost.localdomain heketi[722]: [heketi] INFO 2016/09/20 19:54:47 Creating volume 28c3a6c13145ae86faf75a6de1f54102
Sep 20 19:54:47 localhost.localdomain heketi[722]: [heketi] DEBUG 2016/09/20 19:54:47 /src/github.com/heketi/heketi/apps/glusterfs/volume_entry.go:255: Using the following clusters: []
Sep 20 19:54:47 localhost.localdomain heketi[722]: [heketi] DEBUG 2016/09/20 19:54:47 /src/github.com/heketi/heketi/apps/glusterfs/volume_entry_allocate.go:44: brick_size = 5767168
Sep 20 19:54:47 localhost.localdomain heketi[722]: [heketi] DEBUG 2016/09/20 19:54:47 /src/github.com/heketi/heketi/apps/glusterfs/volume_entry_allocate.go:48: sets = 2
Sep 20 19:54:47 localhost.localdomain heketi[722]: [heketi] INFO 2016/09/20 19:54:47 brick_num: 0
Sep 20 19:54:47 localhost.localdomain heketi[722]: [heketi] ERROR 2016/09/20 19:54:47 /src/github.com/heketi/heketi/apps/glusterfs/allocator_simple.go:164: Unknown cluster id requested: 7b377075af0
Sep 20 19:54:47 localhost.localdomain heketi[722]: [heketi] DEBUG 2016/09/20 19:54:47 /src/github.com/heketi/heketi/apps/glusterfs/volume_entry_allocate.go:120: 0 / 1
Sep 20 19:54:47 localhost.localdomain heketi[722]: [heketi] DEBUG 2016/09/20 19:54:47 /src/github.com/heketi/heketi/apps/glusterfs/volume_entry_allocate.go:87: Error detected.  Cleaning up volume 2
Sep 20 19:54:47 localhost.localdomain heketi[722]: [negroni] Started GET /queue/62022beb0b0525afbe1fcf827f30a693
Sep 20 19:54:47 localhost.localdomain heketi[722]: [negroni] Completed 200 OK in 41.255µs
Sep 20 19:54:47 localhost.localdomain heketi[722]: [heketi] ERROR 2016/09/20 19:54:47 /src/github.com/heketi/heketi/apps/glusterfs/volume_entry_allocate.go:66: Id not found
Sep 20 19:54:47 localhost.localdomain heketi[722]: [heketi] ERROR 2016/09/20 19:54:47 /src/github.com/heketi/heketi/apps/glusterfs/app_volume.go:131: Failed to create volume: No space
Sep 20 19:54:47 localhost.localdomain heketi[722]: [asynchttp] INFO 2016/09/20 19:54:47 Completed job 62022beb0b0525afbe1fcf827f30a693 in 14.522612ms
Sep 20 19:54:48 localhost.localdomain heketi[722]: [negroni] Started GET /queue/62022beb0b0525afbe1fcf827f30a693
Sep 20 19:54:48 localhost.localdomain heketi[722]: [negroni] Completed 500 Internal Server Error in 38.979µs

**Comment by lpabon** [comment]
Hi @sofo110111e , just  a couple of things I see from the command above.

The command should be for Heketi cli to create a 11g volume.  You could do the following:

```
$ heketi-cli --size=11 --persistent-volume-file=gluster-pv.json
```
This will create a Distributed-Replica 3 11 G volume.  Then edit `gluster-pv.json` and add the _name_ of the endpoints.  To get the name, you can do:

```
$ kubectl get endpoints
```

More information is available here:  https://docs.openshift.com/enterprise/3.2/install_config/persistent_storage/persistent_storage_glusterfs.html#creating-gluster-endpoints

Also, I am not sure if you have seen the demo, but that is available here:
https://youtu.be/gmEUnOmDziQ

**Comment by sofo110111e** [comment]
Hi,

Thank you for your prompt feedback. I tried and still getting the same error. My question is why I am getting this error. Is it because no device was found? Topology info shows no devices. Instead of raw devices which are not applicable for pods should I use block devices?
Does heketi-cli supports creation of block storage devices? If yes where from should I download it? For example in my case I cannot add in my pod a raw device. My pod coexists in the same node with the kube-master. What should I do in order to add a device? Pvcreate /dev/sda fails in the gluster pod during the execution of the heketi-cli device add ....

Thank you!

**Comment by lpabon** [comment]
Hi @sofo110111e, those are a lot of questions... Let me see if I can answer them:

* Why I am getting this error. Is it because no device was found?
    * I would need more information.  For example `heketi-cli topology info` shows the entire topology.  We would also need to see what commands you executed.
    * We would also need to determine the environment.  Is this Kubernetes, OpenShift, or something else?  Is Gluster deployed as containers?

* Topology info shows no devices.
    * We need to see the topology info.

* Instead of raw devices which are not applicable for pods should I use block devices?
    * The Gluster containers need access to the raw devices on the node they are running on according to the documentation in the [WIki](https://github.com/heketi/heketi/wiki/OpenShift-Integration---Project-Aplo).  Also they must be running on _host-net_ and as _privileged_ containers.  These things are handled automatically by the [OpenShift template](https://github.com/heketi/heketi/tree/master/extras/openshift/templates).

* Does heketi-cli supports creation of block storage devices?
    * No, not yet.  Probably in Release 4 or 5.

* For example in my case I cannot add in my pod a raw device. My pod coexists in the same node with the kube-master. What should I do in order to add a device? Pvcreate /dev/sda fails in the gluster pod during the execution of the heketi-cli device add ....
    * I'm guessing that `/dev/sda` is where your operating system is.  You definitely do not want to do that.

I highly suggest trying out the [vagrant-demo](https://github.com/heketi/vagrant-heketi) before deploying your own.

I hope this helps

**Comment by lpabon** [comment]
@heketi/dev @heketi/qe FYI

**Comment by sofo110111e** [comment]
Hi @lpabon ,

Thank you for your prompt feedback. My apologies for the so many questions. I am actually trying to find the way out.

1. Regarding my topology info please see below:

[root@localhost ~]# heketi-cli topology info

Cluster Id: 7b377075af001357f34c748df02d1ebc

    Volumes:

    Nodes:

        Node Id: 45e872242a55a6ec4f17ec09ea996bba
        State: online
        Cluster Id: 7b377075af001357f34c748df02d1ebc
        Zone: 1
        Management Hostname: 10.0.2.15
        Storage Hostname: 10.0.2.15
        Devices:


2. The glusterfs has been deployed as pod
kubectl get pods gluster-1
NAME        READY     STATUS    RESTARTS   AGE
gluster-1   1/1       Running   3          1d

3. in local VM pvdisplay shows:


  --- Physical volume ---
  PV Name               /dev/sda2

4. I am not using openshift. This is only Kubernetes.  Is there a solution without openshift?
As far as I understand Heketi is independent of the underlying orchestrator.

Thank you!

**Comment by MohamedAshiqrh** [comment]
@sofo110111e yes, heketi is independent of underlying orchestrator(kubernetes or openshift). The problem is not based on the orchestrator. you need a (new or empty) raw device which can be used by heketi. Here you do not have a (new or empty) raw device.

**Comment by lpabon** [comment]
@sofo110111e You are also using only one Gluster node.  Are you doing this for testing purposes only?  If so, I would highly recommend instead to use the [vagrant-heketi demo](https://github.com/heketi/vagrant-heketi)

**Comment by sofo110111e** [comment]
@lpabon 
According to demo each node needs 500G. I do not have such a capacity.

However in my opinion it is a cons that heketi-cli requires raw devices. It should give the capability to manage Gluster without adding raw device. For example it should read the existing pod topology (volumes etc....) without setting as a prerequisite to add a raw device.
 
Kubernetes allows to create persistent volume without requiring raw device

Regards!

**Comment by MohamedAshiqrh** [comment]
@sofo110111e you can edit the capacity in vagrantfile. I would suggest 50 GB.

**Comment by lpabon** [comment]
@sofo110111e The 500G drives are not really 500G.  They are managed by libvirt, and are called "dynamic volumes".  KVM/QEMU pretend that they are 500G, when on the host, they only take up about 15MB.

**Comment by lpabon** [comment]
Here is an example of the actual space consumed on the QEMU/KVM host:

```
-rwxr--r-- 1 qemu qemu  384K Sep 20 22:05 origin-disk-0-0.disk
-rwxr--r-- 1 qemu qemu  384K Sep 20 22:05 origin-disk-0-1.disk
-rwxr--r-- 1 qemu qemu   26M Sep 21 10:01 origin-disk-0-2.disk
-rwxr--r-- 1 qemu qemu  384K Sep 20 22:05 origin-disk-1-0.disk
-rwxr--r-- 1 qemu qemu  384K Sep 20 22:05 origin-disk-1-1.disk
-rwxr--r-- 1 qemu qemu   26M Sep 21 10:01 origin-disk-1-2.disk
-rwxr--r-- 1 qemu qemu  384K Sep 20 22:05 origin-disk-2-0.disk
-rwxr--r-- 1 qemu qemu  384K Sep 20 22:05 origin-disk-2-1.disk
-rwxr--r-- 1 qemu qemu   26M Sep 21 10:01 origin-disk-2-2.disk
```

Each of these _files_ are represented on the virtual machines as 500G drives.

**Comment by sofo110111e** [comment]
Hi @lpabon 

By adding raw device (vmdk via vbox) I managed to add the device successfully to my gluster pod. But still volume create fails as follows:

Sep 21 17:55:45 localhost.localdomain heketi[751]: Aborting. Failed to wipe start of new LV.
Sep 21 17:55:45 localhost.localdomain heketi[751]: ]
Sep 21 17:55:45 localhost.localdomain kubelet[2409]: E0921 17:55:45.716779    2409 server.go:611] Error executing command in container: Error executing in Docker Container: 32
Sep 21 17:55:45 localhost.localdomain heketi[751]: [kubeexec] ERROR 2016/09/21 17:55:45 /src/github.com/heketi/heketi/executors/kubeexec/kubeexec.go:295: Failed to run command [umoun
Sep 21 17:55:45 localhost.localdomain heketi[751]: ]
Sep 21 17:55:45 localhost.localdomain heketi[751]: [sshexec] ERROR 2016/09/21 17:55:45 /src/github.com/heketi/heketi/executors/sshexec/brick.go:129: Unable to execute command on glus
Sep 21 17:55:45 localhost.localdomain kubelet[2409]: E0921 17:55:45.824696    2409 server.go:611] Error executing command in container: Error executing in Docker Container: 5
Sep 21 17:55:45 localhost.localdomain heketi[751]: [kubeexec] ERROR 2016/09/21 17:55:45 /src/github.com/heketi/heketi/executors/kubeexec/kubeexec.go:295: Failed to run command [lvrem
Sep 21 17:55:45 localhost.localdomain heketi[751]: ]
Sep 21 17:55:45 localhost.localdomain heketi[751]: [sshexec] ERROR 2016/09/21 17:55:45 /src/github.com/heketi/heketi/executors/sshexec/brick.go:138: Unable to execute command on glus
Sep 21 17:55:45 localhost.localdomain heketi[751]: [kubeexec] DEBUG 2016/09/21 17:55:45 /src/github.com/heketi/heketi/executors/kubeexec/kubeexec.go:298: Host: gluster-1 Command: rmd
Sep 21 17:55:45 localhost.localdomain heketi[751]: Result:
Sep 21 17:55:46 localhost.localdomain heketi[751]: [kubeexec] DEBUG 2016/09/21 17:55:46 /src/github.com/heketi/heketi/executors/kubeexec/kubeexec.go:298: Host: gluster-1 Command: sed
Sep 21 17:55:46 localhost.localdomain heketi[751]: Result:
Sep 21 17:55:46 localhost.localdomain heketi[751]: [heketi] ERROR 2016/09/21 17:55:46 /src/github.com/heketi/heketi/apps/glusterfs/brick_create.go:56: Unable to execute command on gl
Sep 21 17:55:46 localhost.localdomain heketi[751]: Aborting. Failed to wipe start of new LV.
Sep 21 17:55:46 localhost.localdomain heketi[751]: [heketi] INFO 2016/09/21 17:55:46 Deleting brick 99fce0afeab3ef91d6f0c983fd513994
Sep 21 17:55:46 localhost.localdomain heketi[751]: [heketi] INFO 2016/09/21 17:55:46 Deleting brick e80415db0d87f848bd8df75d34891ec7
Sep 21 17:55:46 localhost.localdomain kubelet[2409]: E0921 17:55:46.183614    2409 server.go:611] Error executing command in container: Error executing in Docker Container: 32
Sep 21 17:55:46 localhost.localdomain heketi[751]: [kubeexec] ERROR 2016/09/21 17:55:46 /src/github.com/heketi/heketi/executors/kubeexec/kubeexec.go:295: Failed to run command [umoun
Sep 21 17:55:46 localhost.localdomain heketi[751]: ]
Sep 21 17:55:46 localhost.localdomain heketi[751]: [sshexec] ERROR 2016/09/21 17:55:46 /src/github.com/heketi/heketi/executors/sshexec/brick.go:129: Unable to execute command on glus
Sep 21 17:55:46 localhost.localdomain kubelet[2409]: E0921 17:55:46.256853    2409 server.go:611] Error executing command in container: Error executing in Docker Container: 5
Sep 21 17:55:46 localhost.localdomain heketi[751]: [kubeexec] ERROR 2016/09/21 17:55:46 /src/github.com/heketi/heketi/executors/kubeexec/kubeexec.go:295: Failed to run command [lvrem
Sep 21 17:55:46 localhost.localdomain heketi[751]: ]


Possibly any idea for?

Regards!

**Comment by sofo110111e** [comment]
Hi,

Is there any update?

Regards!

**Comment by MohamedAshiqrh** [comment]
Hi @sofo110111e,

I am setting up kubernetes and trying to hit same issue, will update soon.

**Comment by sofo110111e** [comment]
Hi @MohamedAshiqrh ,

Thank you in advance for your effort

Waiting for your updates

**Comment by sofo110111e** [comment]
Hi @MohamedAshiqrh,

Just let me know if you need anything from my setup

Regards!

**Comment by MohamedAshiqrh** [comment]
Hi @sofo110111e ,

I am sorry for the delay, My facing few issues bringing it up in a proper way. If you can try few things in your setup then we can see whats that actually you are facing. so `#heketi-cli topology info`

**Comment by sofo110111e** [comment]
Hi @MohamedAshiqrh ,

Cluster Id: 7d9767b18cd3c57595562e069c72ab43

    Volumes:

    Nodes:

        Node Id: 1473b20aff28132d71ca241168645692
        State: online
        Cluster Id: 7d9767b18cd3c57595562e069c72ab43
        Zone: 1
        Management Hostname: 10.0.2.15
        Storage Hostname: 10.0.2.15
        Devices:
                Id:f584f09c122f3feb6926247abb3f7818   Name: /dev/sdb           State:online    Size (GiB):12      Used (GiB):0       Free (GiB):12
                        Bricks:
Regards!!

**Comment by MohamedAshiqrh** [comment]
Hi @sofo110111e,

can you exec into the gluster pod, Try listing the lv's in the gluster pod.

**Comment by MohamedAshiqrh** [comment]
can you also make sure your pod is running as privileged. Creating lv's in contianer needs privileged permission. Also check `systemctl status glusterd`.

**Comment by sofo110111e** [comment]
Hi @MohamedAshiqrh ,

My pod is running as privileged that is why sees the /dev/sdb raw device.
Below the glusterd systemctl status


[root@localhost /]# systemctl status glusterd -l
● glusterd.service - GlusterFS, a clustered file-system server
   Loaded: loaded (/usr/lib/systemd/system/glusterd.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2016-09-23 09:50:03 UTC; 4h 45min ago
  Process: 56 ExecStart=/usr/sbin/glusterd -p /var/run/glusterd.pid --log-level $LOG_LEVEL $GLUSTERD_OPTIONS (code=exited, status=0/SUCCESS)
 Main PID: 57 (glusterd)
   CGroup: /docker/d15d82f53fcdfb4c00ffb5e877ecaf3f6737f463d1f36039e21beba6ac8aa451/system.slice/glusterd.service
           ├─ 57 /usr/sbin/glusterd -p /var/run/glusterd.pid --log-level INFO
           ├─227 /usr/sbin/glusterfsd -s 10.0.2.15 --volfile-id newvol.10.0.2.15.mnt-brick1-newvol -p /var/lib/glusterd/vols/newvol/run/10.0.2.15-mnt-brick1-newvol.pid -S /var/run/gluster/864a36e5d67091862f7aa31b9dbd3374.socket --brick-name /mnt/brick1/newvol -l /var/log/glusterfs/bricks/mnt-brick1-newvol.log --xlator-option *-posix.glusterd-uuid=a106e020-ad5a-444d-a87d-127de14e61ee --brick-port 49152 --xlator-option newvol-server.listen-port=49152
           ├─232 /usr/sbin/glusterfs -s localhost --volfile-id gluster/nfs -p /var/lib/glusterd/nfs/run/nfs.pid -l /var/log/glusterfs/nfs.log -S /var/run/gluster/7459912627a949b7d3f6917032b72004.socket
           └─254 /sbin/rpc.statd

Sep 23 09:49:53 localhost.localdomain systemd[1]: Starting GlusterFS, a clustered file-system server...
Sep 23 09:50:03 localhost.localdomain systemd[1]: Started GlusterFS, a clustered file-system server.
Sep 23 09:50:05 localhost.localdomain rpc.statd[254]: Version 1.3.0 starting
Sep 23 09:50:05 localhost.localdomain rpc.statd[254]: Initializing NSM state

...are you asking me for lvdisplay?
It shows nothing.

**Comment by sofo110111e** [comment]
Hi @MohamedAshiqrh ,

Any updates?

Regards!

**Comment by lpabon** [comment]
Hi @sofo110111e .  We have a solution for the issue.  @MohamedAshiqrh Will be updating the issue with the issue and solution we investigated and will be proposing shortly.

**Comment by zhaorendong** [comment]
What is the detail solution for the issue?

**Comment by Ghostwritten** [comment]
请问怎么解决的？

**Comment by Vishal-Gaur** [comment]
Hii guys,
what was the next step after the following :
# heketi-cli topology info

Cluster Id: 97792e56c42b32fa67f01d699171cabd

    Volumes:

    Nodes:

	Node Id: 66c83ccfa95f220300bc5a8670c092ea
	State: online
	Cluster Id: 97792e56c42b32fa67f01d699171cabd
	Zone: 1
	Management Hostname: gfs1
	Storage Hostname: 192.168.122.156
	Devices:
		Id:eff499c06bc82f438467bdf7d08fde67   Name:/dev/vdb            State:online    Size (GiB):24      Used (GiB):0       Free (GiB):24      
			Bricks:

	Node Id: bfd1cf57ab8ee1aaca907a99adc33cd6
	State: online
	Cluster Id: 97792e56c42b32fa67f01d699171cabd
	Zone: 2
	Management Hostname: gfs2
	Storage Hostname: 192.168.122.73
	Devices:
		Id:1c212f670cd06797c2abd6ec2d37056f   Name:/dev/vdb            State:online    Size (GiB):24      Used (GiB):0       Free (GiB):24      
			Bricks:

**Comment by Asgoret** [comment]
@lpabon hi, i have strange error. Heketi think my /dev/sdb have 500GB, and i don'` know how to fix it. It doesn`t create vg groups for openshift or him self. can you recommend something?
