### ISSUE TITLE
Add Heketi metadata to Kubernetes objects

### ISSUE THREAD

**Issue by lpabon** [heketi/heketi#511]
As requested by a user, it would be great to have certain labels placed in Kubernetes objects which save Heketi metadata information.

For example, a PV could add `heketi.io/id` where the value would be the volume id.  It could also add `heketi.io/cluster` where the value would be the cluster id.

This needs to be added to both clients: heketi-cli and Kubernetes provisioner.

**Comment by humblec** [comment]
I can add these 'extra' metadata in the provisioner, but what advantage it brings? As per me, we should expose less information to the user as these volumes are  meant to be handled by the provisioner and not the user.

**Comment by lpabon** [comment]
@humblec These are not for the user, that would be in the PVC.  These are for the administrator which has access to the PV.  They would link back to the Heketi systems they are managing

**Comment by lpabon** [comment]
@t0ffel Suggested this

**Comment by humblec** [comment]
@lpabon @t0ffel working on it.

**Comment by ravishivt** [comment]
I was going to raise a separate issue but I think this might be the underlying issue.  I would like to be able to leverage more options from heketi's volume API when creating a PVC in kubernetes including specifying a volume name and choosing the volume's durability type.  Please correct me if this issue doesn't cover these requests.

**Comment by phlogistonjohn** [comment]
Very stale issue. Closing.
