### ISSUE TITLE
Create demo for vagrant-heketi based on Kubernetes

### ISSUE THREAD

**Issue by lpabon** [heketi/heketi#518]
This depends on #449

**Comment by lpabon** [comment]
Depends on #527.  Moved to Release 4.

**Comment by jarrpa** [comment]
Updated https://github.com/heketi/heketi/wiki/Kubernetes-Integration to have pointers to the gluster-kubernetes repo, in particular having a link to the README which includes a Quickstart guide on how to spin up a Kubernetes cluster for deploying heketi and GlusterFS in vagrant.
