### ISSUE TITLE
Kubernetes deployment documentation

### ISSUE THREAD

**Issue by lpabon** [heketi/heketi#519]
We need a wiki page describing how to setup Kubernetes and containerized storage.

May need #518 and #449

**Comment by aga20** [comment]
+1

**Comment by lpabon** [comment]
This will be completed when #527 is merged.  We plan on releasing Release 3 early next week.

**Comment by lpabon** [comment]
Now that PR #544 is in the code, let's try to have this by the end of this week.

**Comment by obnoxxx** [comment]
@MohamedAshiqrh any progress on this? :-)

**Comment by MohamedAshiqrh** [comment]
@heketi/dev 

https://github.com/heketi/heketi/wiki/Kubernetes-Integration

This document is needs reviews.
