### ISSUE TITLE
Support for binding volumes with labels in openshift

### ISSUE THREAD

**Issue by MohamedAshiqrh** [heketi/heketi#520]
In openshift, pv is selected for pvc by checking accessmode and capacity. now they have a label which can be mentioned in pv and used by pvc for claim. In heketi the pv json file does not have this option now. we have to add it similar to the endpoints option.

Ref: https://docs.openshift.org/latest/install_config/persistent_storage/selector_label_binding.html#selector-label-volume-define

Ref: https://docs.openshift.org/latest/install_config/storage_examples/binding_pv_by_label.html

**Comment by MohamedAshiqrh** [comment]
This will not be required if dynamic provisioner comes in but I feel its good to support manually too.

**Comment by lpabon** [comment]
@MohamedAshiqrh Afaik, there is nothing we need to do here in Heketi.  What do you propose is the change required?

**Comment by humblec** [comment]
@MohamedAshiqrh as @lpabon said, there is nothing to do it from Heketi side. This extra data has to be put from the provisioner. This issue is tracked @https://github.com/heketi/heketi/issues/511
