### ISSUE TITLE
Topology load/Node add: always succeeds on the first node.

### ISSUE THREAD

**Issue by MohamedAshiqrh** [heketi/heketi#522]
First Node add always succeeds which can be avoided.

**Comment by lpabon** [comment]
@MohamedAshiqrh Do you mind providing more explanation.  What is the expected result and what is the actual result?  Is the actual one incorrect?

**Comment by MohamedAshiqrh** [comment]
In case of kubeexecutor, we do not check the loaded username, password and namespace are valid. So on the first node add we should be able to atleast do a small validation of checking like glusterd service check. so that only after confirmation we add this entry to the db. now only on second node add( in-case of heketi-cli) or device add we check.
