### ISSUE TITLE
No space error with erasure coded (dispersed) volume create

### ISSUE THREAD

**Issue by madcatsu** [heketi/heketi#524]
Currently reporting an issue with creating a dispersed volume with the command issued as:

`heketi-cli volume create --size=100 --durability=disperse --disperse-data=4 --redundancy=2`

Current setup is within the Virtualbox demo environment which has been edited to create 3 storage nodes each with 13 disks. Base OS is deployed to /dev/sda and remaining volumes /dev/sd[b-n] are thin provisioned/empty.

I edited the Vagrant file to reduce nodes to 3 and increase disks to 13 to create these automatically on 'vagrant up'. Prior to deploying the cluster, I've edited the topology_virtualbox JSON to reflect fewer nodes and more volumes.

Topology output as follows:

`[vagrant@storage0 ~]$ heketi-cli topology info`

Cluster Id: 44bfe5c7b0a41f41461f4914b53a01a0

```
Volumes:

Nodes:

Node Id: 4a6da7cd7ef78b7d39fb394b9d9e93ce
State: online
Cluster Id: 44bfe5c7b0a41f41461f4914b53a01a0
Zone: 2
Management Hostname: 192.168.10.101
Storage Hostname: 192.168.10.101
Devices:
    Id:4c72f7864ba91181ba0d2fb688d9a3d7   Name:/dev/sdd            State:online    Size (GiB):499     Used (GiB):0       Free (GiB):499     
        Bricks:
    Id:568e7cfb0ac50e4827e0caf7f7240413   Name:/dev/sdg            State:online    Size (GiB):499     Used (GiB):0       Free (GiB):499     
        Bricks:
    Id:666dd58d15d2f55eda69a1db0db9073d   Name:/dev/sdc            State:online    Size (GiB):499     Used (GiB):0       Free (GiB):499     
        Bricks:
    Id:6b94596eebaf18a4873cfef59911d2ba   Name:/dev/sdi            State:online    Size (GiB):499     Used (GiB):0       Free (GiB):499     
        Bricks:
    Id:76f9f209a4ec0bc8a246c7e0be34f428   Name:/dev/sdf            State:online    Size (GiB):499     Used (GiB):0       Free (GiB):499     
        Bricks:
    Id:7cf9ad4b6f350713d42504163bac670e   Name:/dev/sdj            State:online    Size (GiB):499     Used (GiB):0       Free (GiB):499     
        Bricks:
    Id:8be4ea8b7cabfd1791b8dde79b11e3c9   Name:/dev/sde            State:online    Size (GiB):499     Used (GiB):0       Free (GiB):499     
        Bricks:
    Id:a455659c13ddecac0f01e595358eec3b   Name:/dev/sdh            State:online    Size (GiB):499     Used (GiB):0       Free (GiB):499     
        Bricks:
    Id:a8e9e9f09aad04280dbff605bbf8d7d0   Name:/dev/sdb            State:online    Size (GiB):499     Used (GiB):0       Free (GiB):499     
        Bricks:
    Id:e2bf0ec2a81b2ba490f58fa29f15bc96   Name:/dev/sdn            State:online    Size (GiB):499     Used (GiB):0       Free (GiB):499     
        Bricks:
    Id:e712efed3d8e876e51298a98d17506f0   Name:/dev/sdl            State:online    Size (GiB):499     Used (GiB):0       Free (GiB):499     
        Bricks:
    Id:f0e4a9d152971a58ceee93f383448eea   Name:/dev/sdm            State:online    Size (GiB):499     Used (GiB):0       Free (GiB):499     
        Bricks:
    Id:f68955a48a72d284b0ff334c5fd9aa4d   Name:/dev/sdk            State:online    Size (GiB):499     Used (GiB):0       Free (GiB):499     
        Bricks:

Node Id: c8c143e415b6f89b41ad3285733875dd
State: online
Cluster Id: 44bfe5c7b0a41f41461f4914b53a01a0
Zone: 1
Management Hostname: 192.168.10.100
Storage Hostname: 192.168.10.100
Devices:
    Id:490e0b909423e20fba0e78fd4cc08883   Name:/dev/sdi            State:online    Size (GiB):499     Used (GiB):0       Free (GiB):499     
        Bricks:
    Id:4990bf8edf604bad59f0133716db64f1   Name:/dev/sde            State:online    Size (GiB):499     Used (GiB):0       Free (GiB):499     
        Bricks:
    Id:5a56547a2c3a099a29cb3a0db8e00667   Name:/dev/sdf            State:online    Size (GiB):499     Used (GiB):0       Free (GiB):499     
        Bricks:
    Id:5ae870396b61a7b14134a56905c08eca   Name:/dev/sdn            State:online    Size (GiB):499     Used (GiB):0       Free (GiB):499     
        Bricks:
    Id:65095690ce0f2cb3943080f5aa4a73ab   Name:/dev/sdd            State:online    Size (GiB):499     Used (GiB):0       Free (GiB):499     
        Bricks:
    Id:7ff636c493c62ce4079756cd4fb827c8   Name:/dev/sdj            State:online    Size (GiB):499     Used (GiB):0       Free (GiB):499     
        Bricks:
    Id:813a78d75af982c0dfe086d34789bf5f   Name:/dev/sdh            State:online    Size (GiB):499     Used (GiB):0       Free (GiB):499     
        Bricks:
    Id:83f91cda311de1adced5995e9bd66767   Name:/dev/sdc            State:online    Size (GiB):499     Used (GiB):0       Free (GiB):499     
        Bricks:
    Id:8e7ac6f3aeea75e8c92c79c4084a7531   Name:/dev/sdb            State:online    Size (GiB):499     Used (GiB):0       Free (GiB):499     
        Bricks:
    Id:9fff6e3e6008d19783f55616fea94a63   Name:/dev/sdm            State:online    Size (GiB):499     Used (GiB):0       Free (GiB):499     
        Bricks:
    Id:ba806042a9328e69a68bff9c30bd52e1   Name:/dev/sdg            State:online    Size (GiB):499     Used (GiB):0       Free (GiB):499     
        Bricks:
    Id:c02a902082a8dee1359abbe62790bd72   Name:/dev/sdl            State:online    Size (GiB):499     Used (GiB):0       Free (GiB):499     
        Bricks:
    Id:e9aa75cc3e6d3e7f9d471237fd35f945   Name:/dev/sdk            State:online    Size (GiB):499     Used (GiB):0       Free (GiB):499     
        Bricks:

Node Id: f70b052835232fe4d3728a8784e0d130
State: online
Cluster Id: 44bfe5c7b0a41f41461f4914b53a01a0
Zone: 1
Management Hostname: 192.168.10.102
Storage Hostname: 192.168.10.102
Devices:
    Id:005db88b98636955d19a36750c7ed49a   Name:/dev/sdf            State:online    Size (GiB):499     Used (GiB):0       Free (GiB):499     
        Bricks:
    Id:087dd682211cfbe43ccdecca1e7d02d4   Name:/dev/sdc            State:online    Size (GiB):499     Used (GiB):0       Free (GiB):499     
        Bricks:
    Id:097748739c283613ee314d9df42d7c0a   Name:/dev/sdg            State:online    Size (GiB):499     Used (GiB):0       Free (GiB):499     
        Bricks:
    Id:42098842cf47f50a8bf8b6941061c743   Name:/dev/sdd            State:online    Size (GiB):499     Used (GiB):0       Free (GiB):499     
        Bricks:
    Id:52e40e606547cb4a753068c07309c980   Name:/dev/sdl            State:online    Size (GiB):499     Used (GiB):0       Free (GiB):499     
        Bricks:
    Id:567f9e71f796b0778b74a443d7d6f0ab   Name:/dev/sde            State:online    Size (GiB):499     Used (GiB):0       Free (GiB):499     
        Bricks:
    Id:73c7c089e67cd04d687b75c3876fedb0   Name:/dev/sdb            State:online    Size (GiB):499     Used (GiB):0       Free (GiB):499     
        Bricks:
    Id:86d7034ed7d1992b2dc88978963329e4   Name:/dev/sdj            State:online    Size (GiB):499     Used (GiB):0       Free (GiB):499     
        Bricks:
    Id:8bb1040c9b3d76a9a3b16434565f1554   Name:/dev/sdh            State:online    Size (GiB):499     Used (GiB):0       Free (GiB):499     
        Bricks:
    Id:9b9dee5974bc325cbc1ee239a77164f8   Name:/dev/sdk            State:online    Size (GiB):499     Used (GiB):0       Free (GiB):499     
        Bricks:
    Id:aa3d4e8f532811cacd4d5856f22aac1b   Name:/dev/sdi            State:online    Size (GiB):499     Used (GiB):0       Free (GiB):499     
        Bricks:
    Id:aa7b1b97a76d320ea408fd638e8b9e07   Name:/dev/sdm            State:online    Size (GiB):499     Used (GiB):0       Free (GiB):499     
        Bricks:
    Id:b815b4c512b3d22f83ef217ab3e7f7f6   Name:/dev/sdn            State:online    Size (GiB):499     Used (GiB):0       Free (GiB):499     
        Bricks:`
```

According to standard Gluster EC best practices, I should be able to establish a 3 node cluster with 36 spindles and create an EC protected volume with 4+2 dispersal/redundancy.

I can see from the output of 'sudo journalctl -r' (saved me paging through all the journal entries) that it tried to create 0 bricks with the command submitted to the server. Snippet follows:

`Sep 24 00:38:01 storage0 heketi[14119]: [negroni] Completed 500 Internal Server Error in 52.672µs
Sep 24 00:38:01 storage0 heketi[14119]: [negroni] Started GET /queue/3cfa2973b56603d2617cc110537f9016
Sep 24 00:38:00 storage0 heketi[14119]: [asynchttp] INFO 2016/09/24 00:38:00 Completed job 3cfa2973b56603d2617cc110537f9016 in 10.858284ms
Sep 24 00:38:00 storage0 heketi[14119]: [heketi] ERROR 2016/09/24 00:38:00 /src/github.com/heketi/heketi/apps/glusterfs/app_volume.go:131: Failed to create volume: No space
Sep 24 00:38:00 storage0 heketi[14119]: [heketi] ERROR 2016/09/24 00:38:00 /src/github.com/heketi/heketi/apps/glusterfs/volume_entry_allocate.go:41: Minimum brick size limit reached.  Out of space.
Sep 24 00:38:00 storage0 heketi[14119]: [negroni] Completed 200 OK in 20.998µs
Sep 24 00:38:00 storage0 heketi[14119]: [negroni] Started GET /queue/3cfa2973b56603d2617cc110537f9016
Sep 24 00:38:00 storage0 heketi[14119]: [heketi] INFO 2016/09/24 00:38:00 brick_num: 0
Sep 24 00:38:00 storage0 heketi[14119]: [heketi] INFO 2016/09/24 00:38:00 Creating volume 5832424d66fd5665ceadb1f91558d1b9
Sep 24 00:38:00 storage0 heketi[14119]: [asynchttp] INFO 2016/09/24 00:38:00 Started job 3cfa2973b56603d2617cc110537f9016
Sep 24 00:38:00 storage0 heketi[14119]: [negroni] Completed 202 Accepted in 259.701µs
Sep 24 00:38:00 storage0 heketi[14119]: [negroni] Started POST /volumes`

As you can see, brick_num: 0 is probably not what we want here :)

**Comment by MohamedAshiqrh** [comment]
Hi @madcatsu,

By default disperse is 4+2, you do not have to actually mention it. --durability=disperse will be sufficient. This volume needs a six node setup to be successful. @lpabon can give better explanation.

**Comment by madcatsu** [comment]
Thanks @MohamedAshiqrh - I refer to this document specifically as I'm looking to deploy GlusterFS across initially 3 physical nodes and not in a container/virtual ecosystem: [https://access.redhat.com/documentation/en-US/Red_Hat_Storage/3.1/html/Administration_Guide/chap-Recommended-Configuration_Dispersed.html](https://access.redhat.com/documentation/en-US/Red_Hat_Storage/3.1/html/Administration_Guide/chap-Recommended-Configuration_Dispersed.html)

This would then scale out later on by 3 nodes at a time. Something to discuss offline with @lpabon I suppose.

Ideally the current Heketi supported volume configurations should be documented a little more clearly to elaborate on the 6 node requirement. And +1 for supporting a 3 node config for people who want to start small and grow as capacity demands require.

**Comment by braun1928** [comment]
I hit this problem today, in my OpenShift Enterprise deployment. Is this issue in the roadmap to be changed anytime, so the deployment with 3 nodes (as in the docs pointed out above) would work?

**Comment by PeterGrace** [comment]
I also have a 3 node cluster and have run into this issue today, using Heketi v6.0.0-146-g7deba54.
Can this issue get some attention?  RedHat seems to believe that you can do 4+2 disperse in a 3 node environment successfully.

**Comment by howels** [comment]
Same issue here. The Red Hat recommended configuration for dispersed volumes cannot be built using Heketi, as Heketi refuses to allow multiple bricks to reside on the same node for a disperse volume.
https://access.redhat.com/documentation/en-us/red_hat_gluster_storage/3.1/html/administration_guide/chap-recommended-configuration_dispersed

We are attempting to build a 4+2 disperse volume across 3 nodes, each with multiple disks. This is impossible with ```heketi-cli``` but fine using ```gluster volume create```.   Heketi only allows a 2+1 disperse config with 3 nodes, which goes against Red Hat recommendations.

Please fix this issue and allow for correct usage of disperse volume types.

**Comment by howels** [comment]
Is 2*(2+1) different from 1*(4+2) in the underlying xlator code?

**Comment by phlogistonjohn** [comment]
No updates in a few months. Closing. Please reopen if this issue is still relevant to you.
