### ISSUE TITLE
Heketi mock executor simulate failure scenarios

### ISSUE THREAD

**Issue by r0h4n** [heketi/heketi#538]
New developer here, I was going through the mock executor and figured if we have any sort of failure injection happening there.

eg: Try create volume via the mock executor, inject failure and see the behaviour (logging, retry create volume etc)

**Comment by MohamedAshiqrh** [comment]
Hey @r0h4n,

Mock executor is a way to test code changes for developers, as it just mocks all values and entries. I did not understand your question clearly though.

**Comment by MohamedAshiqrh** [comment]
Are you asking, does mock executor simulates failure scenarios then yeah it does.

**Comment by lpabon** [comment]
@r0h4n I think there is a way to simulate errors from external project unit tests.  Let me see what I can do, I'll get back to you.

**Comment by phlogistonjohn** [comment]
PR #1196 is the start of my attempt at solving this issue.

**Comment by phlogistonjohn** [comment]
The "injectexec" excecutor does error injection now. It is used in error handling funcitonal tests. Closing.
