### ISSUE TITLE
RFC: Remove JSON format from heketi-cli

### ISSUE THREAD

**Issue by lpabon** [heketi/heketi#540]
The JSON API made sense on the heketi-cli when the cli was a reference Heketi client application implementation.  Now that heketi-cli is becoming a more mature application, there is no need to print the information in JSON.  Instead, if callers want data in JSON format, they should use the API, go client, or python client.

**Comment by lpabon** [comment]
@heketi/dev What do guys think?

**Comment by obnoxxx** [comment]
I agree :+1:

**Comment by webwurst** [comment]
For me it's often nice to also get `json` from cli tools for simple scripting. Of course this could also be done via `curl` against the API, but always needs some more reading and fiddling with authentication headers and such. Just sayin' :)

**Comment by jarrpa** [comment]
I like it being there. I always find it useful to have a way to dump as close to raw data as is still human-readable. As an example, I use the "-o json" from kubectl all the time to inspect structure and details.

**Comment by jarrpa** [comment]
Unless we hear other comments in the next four days (so 14 days from the last comment) I say we close this issue and leave the JSON output as-is.

**Comment by lpabon** [comment]
If we do, I think we need to make sure to let users know that the JSON output is the API output and not equal to the one from the cli.  As long as that is shown in the Help screen, I am fine with keeping it, but it will still be confusing to new users.

**Comment by jarrpa** [comment]
Sounds fair!

**Comment by phlogistonjohn** [comment]
From my reading, I think all topics raised in this issue have been resolved. In addition, the last activity on this issue occurred over a year ago. Please reopen if needed. Closing.
