### ISSUE TITLE
Add Heketi python client library to Pip

### ISSUE THREAD

**Issue by lpabon** [heketi/heketi#542]
We should make it possible to easily install the python library in systems which are not rpm bas sed.

**Comment by ramkrsna** [comment]
I get this error . 
Uploading heketi-1.2.0-py2.py3-none-any.whl
[================================] 8300/8300 - 00:00:01
HTTPError: 400 Client Error: classifiers: 'Development Status :: 5 - Production/StableIntended Audience :: Information TechnologyIntended Audience :: System AdministratorsLicense :: OSI Approved :: Apache Software LicenseOperating System :: POSIX :: LinuxProgramming Language :: PythonProgramming Language :: Python :: 2.7' is not a valid choice for this field for url: https://upload.pypi.org/legacy/

The following is my setup.py file ::
`
from setuptools import setup, find_packages

setup(
    name='heketi',
    version='1.2.0',
    description='Python client library for Heketi',
    long_description=open('README.rst').read(),
    license='Apache License (2.0)',
    author='Luis Pabon',
    author_email='lpabon@redhat.com',
    url='https://github.com/heketi/heketi/tree/master/client/api/python',
    packages=find_packages(exclude=['test', 'bin']),
    test_suite='nose.collector',
    install_requires=['pyjwt', 'requests'],
    classifiers=[
        'Development Status :: 5 - Production/Stable'
        'Intended Audience :: Information Technology'
        'Intended Audience :: System Administrators'
        'License :: OSI Approved :: Apache Software License'
        'Operating System :: POSIX :: Linux'
        'Programming Language :: Python'
        'Programming Language :: Python :: 2.7'
    ],
)

`

**Comment by ramkrsna** [comment]
The root cause of this issue is due to an invalid classifier . Will work on the patch for the right classifier in setup file. https://pypi.python.org/pypi?%3Aaction=submit_form I have been able to generate the egg files locally. 

```
(python) [ramky@scrambler python]$ pip install dist/heketi-3.0.0.tar.gz 
Processing ./dist/heketi-3.0.0.tar.gz
Collecting pyjwt (from heketi==3.0.0)
  Using cached PyJWT-1.4.2-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): requests in ./lib/python2.7/site-packages (from heketi==3.0.0)
Building wheels for collected packages: heketi
  Running setup.py bdist_wheel for heketi ... done
  Stored in directory: /home/ramky/.cache/pip/wheels/02/17/d1/0b1f1efb3b8caa1056e4721875959de34bdadb60a9755e19f1
Successfully built heketi
Installing collected packages: pyjwt, heketi
Successfully installed heketi-3.0.0 pyjwt-1.4.2
```




Invalid classifier "Development Status :: 5 - Production/StableIntended Audience :: Information TechnologyIntended Audience :: System AdministratorsLicense :: OSI Approved :: Apache Software LicenseOperating System :: POSIX :: LinuxProgramming Language :: PythonProgramming Language :: Python :: 2.7"
