### ISSUE TITLE
[RFE] add capacity information to the heketi-cli

### ISSUE THREAD

**Issue by lpabon** [heketi/heketi#547]
[BZ 1356758](https://bugzilla.redhat.com/show_bug.cgi?id=1356758)

Managing one or multiple clusters with heketi would benefit from more information presented to the admin from the cli. Understanding the environment is a obviously a key deliverable of the solution, and providing a basic awareness of the capacity under the control of heketi would be a great start.

This RFE requests the following data is exposed
1. Each cluster should provide a roll-up summary consisting of the following fields;
2. number of nodes in the cluster
3. number of disks managed
4. raw capacity managed
5. raw capacity used
6. raw %used
7. number of volumes allocated
8. The topology view dumps all clusters, so a rollup of the cluster numbers would give a deployment wide view of the site
9. total number of clusters managed
10. total nodes
11. total raw
12. total raw used %
13. total number of volumes allocated

By making this information available the admin will be able to
a) understand capacity utilisation
b) plan for more clusters or upgrades in timely manner (instead of encountering allocation failures and impacting the service offered to the business)

I would suggest that this information is added to the topology subcommand. From a usability perspective, I would also suggest that the topology info command is updated to include 
a) --cluster ... to limit topology and summary data to the specified cluster
b) --summary ... to limit the topology output to only the rollup data

**Comment by lpabon** [comment]
It would be great to have this as part of the API not the cli.  That way any caller can get this information as a consistent view of the storage topology.

**Comment by phlogistonjohn** [comment]
Heketi provides prometheus compatible metrics for the data it tracks/uses.
More volume level data can be provided by gluster prometheus tools.
Very stale issue. Closing.
