### ISSUE TITLE
Volume expansion does not set GID on new bricks

### ISSUE THREAD

**Issue by lpabon** [heketi/heketi#558]
Volume expansion sets the new added bricks to GID 0.  Instead it should figure out the GID on the current bricks and permission flags and apply those accordingly.  Heketi should not save the GID it used to create the volume since it may have changed since its creation.

**Comment by lpabon** [comment]
@heketi/dev FYI

**Comment by lpabon** [comment]
Thanks to @zeichenanonym for finding this issue

**Comment by zeichenanonym** [comment]
I think this will be solved by https://bugzilla.redhat.com/show_bug.cgi?id=1294035

**Comment by lpabon** [comment]
oh cool, thanks @zeichenanonym .  We'll try it out and if it fixes it they we will close this.  That makes it really easy! :+1:

**Comment by raghavendra-talur** [comment]
The above mentioned bug in bugzilla would fix it only if storage.uid or storage.gid is used. If an explicit chown is used as in Heketi currently then we need to do what @lpabon mentioned in comment 1.
