### ISSUE TITLE
Use configmaps in heketi deployment instead of long env vars

### ISSUE THREAD

**Issue by humblec** [heketi/heketi#580]
Instead of passing long environment variables in heketi pod configuration we could make use of configmaps https://docs.openshift.org/latest/dev_guide/configmaps.html . This will bring more user friendly deployment options on Heketi.

**Comment by ant31** [comment]
Currently I mount the topology in as a configmap, and use a side-car pod with with the server to load it. 

it looks like: 
```
pod: 
   container1: heketi-server
   container2: heketi-cli load topology --json=/configmap/topology.json  --server=localhost:8080
```

**Comment by phlogistonjohn** [comment]
Hi @humblec do you think this is still a relevant enhancement? It's been nearly two years since you first proposed the idea.

**Comment by phlogistonjohn** [comment]
Very stale issue. Closing.
