### ISSUE TITLE
heketi-cli: --log-flush-frequency is a zombie flag

### ISSUE THREAD

**Issue by MohamedAshiqrh** [heketi/heketi#585]
heketi-cli --log-flush-frequency 10s

--log-flush-frequency is a flag which is listed in heketi-cli --help as a global flag. But interestingly we do not have a flag in the heketi-cli code path(Atleast I couldn't find it). This flag prints the help output which means this flag is not available.

**Comment by MohamedAshiqrh** [comment]
@heketi/dev This is really weird.

**Comment by lpabon** [comment]
This is a duplicate of #318 .

**Comment by MohamedAshiqrh** [comment]
@lpabon yeah It does looks like duplicate. Do you have any idea of approach to solve this problem.

**Comment by MohamedAshiqrh** [comment]
Closing, As this is duplicate of #318 which was fixed by #670.
