### ISSUE TITLE
pointers to help folks set up gluster with Kubernetes ready for heketi

### ISSUE THREAD

**Issue by rawlingsj** [heketi/heketi#587]
The docs for heketi are great however for folks that know little of gluster or storage it can be a little hard to get going still.  I dont have an infrastructure background but I do know Kubernetes.  Would it be possible to add a brief section or point to a doc that helps folks set up nodes with gluster which will then be used by heketi?  

taken from https://github.com/heketi/heketi/wiki/Kubernetes-Integration
> Topologies primarily specify what Kubernetes Nodes the GlusterFS containers are to run on as well as the corresponding available raw block device for each of the nodes. Modify the topology file to reflect the choices you have made

I'm not sure how the setup of the `raw block device for each of the nodes` is done and at what point heketi takes over.

The example topology json that I've found all have multiple `devices` listed for the nodes so I'm wondering if I need to create say three infra kubernetes nodes with large root or mounted ephemeral disk?  Then do they need to be partitioned or formatted?  

Probably basic questions but I'm a little clueless so any help would be appreciated as I think once the filesystem is set up correctly the existing awesome docs will see me through.

**Comment by ramkrsna** [comment]
@rawlingsj https://github.com/gluster/gluster-kubernetes .  Thank you for the pointers, will cross reference the documentation . 

- https://github.com/gluster/gluster-kubernetes/blob/master/docs/setup-guide.md
- https://github.com/gluster/gluster-kubernetes/tree/master/deploy

**Comment by rawlingsj** [comment]
Thanks for the links @ramkrsna!  I'd hadn't seen the repo https://github.com/gluster/gluster-kubernetes 

I did look at the docs and try out the quickstart, there was an issue https://github.com/gluster/gluster-kubernetes/issues/31 in precisely the area I'm trying to understand more about.  

I still think this heketi repo could benefit from having some steps of how to set up a kubernetes node with the device paths that are defined in the topology.json for example `/dev/vdb` `/dev/vdc` and `/dev/vdd`.

As it stands I'm trying to work out what I need to do to my custom cluster that was created using the official Kubernetes Heat templates so that heketi can work.  Can the steps be described in this repo rather that trying to figure it out by looking at a vagrant quickstart?

I think the main bit that I'm missing is what I need to do to each Kubernetes node host machine so that we get the volumes `/dev/vdb` `/dev/vdc` and `/dev/vdd` as an example.  

Again it's probably basic infra stuff but it's not familiar coming from a dev background.

**Comment by jarrpa** [comment]
The heketi wiki needs to be updated, however this portion of the https://github.com/heketi/heketi/wiki/Kubernetes-Integration#infrastructure-requirements page is still relevant:

> A running Kubernetes cluster with at least three Kubernetes worker nodes that each have an available raw block device attached (like an EBS Volume or a local disk).

It is intentionally left vague because any number of installations can meet these requirements. The `/dev/vd*` devices are specific to virtual drives in libvirt, and thus can not be guaranteed outside that deployment scenario. I can do my best to update the documentation over at gluster-kubernetes as it pertains to kube or the vagrant deployment specifically. :)

Overall, though, some level of systems background and understanding is required to understand and use heketi. As a RESTful API and provisioner specifically for GlusterFS storage volumes, we can't work around that in any general sense. I think the best we can manage is to better update our front-facing documentation with appropriate warnings (e.g. move that note from the Kubernetes wiki page into the main README).

**Comment by sheerun** [comment]
@ramkrsna @jarrpa How about securing client connection (i/o and management) from kubernetes, when glusterfs is configured to use TLS: https://kshlm.in/post/network-encryption-in-glusterfs/

Is it possible? How to configure it?

**Comment by MohamedAshiqrh** [comment]
@sheerun I am currently looking into this. We want to support it from the kube secrets[WIP]. 
For now you can bind mount the /etc/ssl from host to gluster container. Then set the volume options. 

1)Certs to be generated from host.
2)Bind mount /etc/ssl to gluster container in /etc/ssl as ReadOnly.
3)Then follow the blog.

This should work let me know us know if you face some issues.

**Comment by sheerun** [comment]
@MohamedAshiqrh But there are no gluster containers to start on kubernetes side. I just configure storageclass, add persistent volume claim, and start a pod with specific "persistentVolumeClaim " configured as volume. Similarly to how it's documented here: https://docs.openshift.org/latest/install_config/storage_examples/gluster_dynamic_example.html

Any hints to setup storageclass to support TLS?

**Comment by MohamedAshiqrh** [comment]
@sheerun You will find the gluster DaemonSet in your openshift setup. you have to add the changes to the daemonset file and this will restart the daemonset which will intern have the certs which is created on the hosts where the gluster pods are running.

**Comment by phlogistonjohn** [comment]
The last activity on this issue is over a year old. In addition the gluster-kubernetes project takes care of most of these details. Closing issue. Please reopen if additional discussion is needed.
