### ISSUE TITLE
Issue with mounting volumes created via heketi-cli

### ISSUE THREAD

**Issue by pravege** [heketi/heketi#593]
Faced with issues while trying to create a volume using the heketi-cli. The infra is a cluster with single node to host the volume. When the volume is created using the heketi cli, it successfully returns. When the same volume is mounted using the glusterfs command, its returning error "glusterfs: failed to get the 'volume file' from server".
  
  The gluster volume list command also does not return any volume.
  
  While creating the topology for the heketi, the IP address of the host where the device is residing was added and there were no errors
  From the heketi-cli, the node, device, volume all could be retrieved successfully. The following bricks are also created successfully.
  
  Versions used are - heketi         3.0.0
                      gluster        3.7.17
					  gluster client 3.7.6
  
  Any specific version combination required for this to work.
  
  Device Id: 1c99da82cb2f96a2c7eff089fb6d3715
  Name: /glusterVolume
  Size (GiB): 500
  Used (GiB): 22
  Free (GiB): 477
  Bricks:
  Id:633c9f97fc547aa970853bf9ef2c9b4d   Size (GiB):11      Path: /mockpath
  Id:f7f12a3d8fcff8bb1cf5e509831d208d   Size (GiB):11      Path: /mockpath  
  
  
  Logs from gluster:
  
  glusterd-mgmt.c:1980:glusterd_mgmt_v3_initiate_all_phases] 0-management: Failed to build payload for operation 'Volume Start'
  
  
  Docker log output from heketi container:
  
  [asynchttp] INFO 2016/11/30 06:27:57 Started job 53b074cc49924193e5809f41e705c4e7
  [heketi] INFO 2016/11/30 06:27:57 Creating volume 0a77118e975c1a3705d9aedec94e6c94
  [heketi] INFO 2016/11/30 06:27:57 brick_num: 0
  [negroni] Started GET /queue/53b074cc49924193e5809f41e705c4e7
  [negroni] Completed 200 OK in 79.614µs
  [heketi] INFO 2016/11/30 06:27:57 Creating brick f7f12a3d8fcff8bb1cf5e509831d208d
  [heketi] INFO 2016/11/30 06:27:57 Created volume 0a77118e975c1a3705d9aedec94e6c94
  [asynchttp] INFO 2016/11/30 06:27:57 Completed job 53b074cc49924193e5809f41e705c4e7 in 8.885821ms
  [negroni] Started GET /queue/53b074cc49924193e5809f41e705c4e7
  [negroni] Completed 303 See Other in 222.957µs
  [negroni] Started GET /volumes/0a77118e975c1a3705d9aedec94e6c94
  [negroni] Completed 200 OK in 511.347µs
  
  Topology file :
  
  {
    "clusters": [
        {
            "nodes": [
                {
                    "node": {
                        "hostnames": {
                            "manage": [
                                "IP of the server"
                            ],
                            "storage": [
                                "IP of the server"
                            ]
                        },
                        "zone": 1
                    },
                    "devices": [
                        "/glusterVolume"
                    ]
                }
            ]
        }
    ]
  }

**Comment by swordboy** [comment]
same issue.anybody solved?

**Comment by swordboy** [comment]
in my case./etc/heketi/heketi.json executor is default to mock.that is heketi will really call glusterfs to create volume.so can't mount

**Comment by MohamedAshiqrh** [comment]
@pravege @swordboy Which environment are you trying is it kubernetes/openshift where gluster is running as container or just in vm running gluster. you have to change the config file according to the [doc](https://github.com/heketi/heketi/wiki/Running-the-server#config-file). Then try again. Mock is used for development purposes and is the initial config in configuration file which has to be changed.

**Comment by xiaomage008** [comment]
I also get the same issue, executor mode is "mock", i have created volume via heketi, but client can not mount(log:0-glusterfs: failed to get the 'volume file' from server). And when use gluster volume info, it is nothing. Does it has relationship with "mock" mode? How can i fix it? Thanks a log.

**Comment by Madhu-1** [comment]
@xiaomage008 mock is used for unit testing. either you need to use ssh executor or kube executor to create volumes.
you need to edit heketi.json like below

if you are running heketi and gluster in OCP or kubernetes 
```
"executor": "kube"
````
if you are using kube executor edit below configuration in heketi.json

```
 "kubeexec": {
      "host" :"https://kubernetes.host:8443",
      "cert" : "/path/to/crt.file",
      "insecure": false,
      "user": "kubernetes username",
      "password": "password for kubernetes user",
      "namespace": "OpenShift project or Kubernetes namespace",
      "fstab": "Optional: Specify fstab file on node.  Default is /etc/fstab",
      "backup_lvm_metadata": false
    }
```
if you are running in stand alone enviroment use ssh executor

```
 "executor": "ssh",
 
```
if you are using ssh executor need to edit below configuration in heketi.json

```

    "_sshexec_comment": "SSH username and private key file information",
    "sshexec": {
      "keyfile": "path/to/private_key",
      "user": "sshuser",
      "port": "Optional: ssh port.  Default is 22",
      "fstab": "Optional: Specify fstab file on node.  Default is /etc/fstab",
      "backup_lvm_metadata": false
    }
```

**Comment by xiaomage008** [comment]
@Madhu-1 , Hi, I encountered one issue. I have three nodes in heketi. After one node down, heketi can not work. So i have a concern, is there an HA for heketi? From my understanding, once one node down, another two node can still provide storage function for user, why one node down makes heketi down. It seems does not math the HA idea for heketi.

**Comment by phlogistonjohn** [comment]
As @Madhu-1 noted, there is no reason to use the "mock" executor in a real deployment of heketi. As for HA, Heketi only needs HA for the database which in turn is provided by glusterfs (in a typical deployment). Gluster itself has some additional constraints about what operations can be performed, such as creating volumes, when fewer than 3 peers are active.
Does this answer the outstanding questions?

**Comment by phlogistonjohn** [comment]
Stale issue. Closing.
