### ISSUE TITLE
Improve error message when encountering initialized devices

### ISSUE THREAD

**Issue by jarrpa** [heketi/heketi#595]
heketi expects to be able to fully partition and format any devices it's handed. Currently when we encounter a device that's already been initialized we provide the following error message:

```
Unable to add device: Unable to execute command on <node>:   Can't initialize physical volume "<device>" of volume group "<vg>" without -ff
```

We should provide a clearer error message to let the user know why we're failing and/or what they could do to fix it. Something like:

```
Unable to add device: Device "<device>" is already initialized or contains data.
```

The changes would likely need to go in `executor/.../device.go`.

**Comment by jianzi123** [comment]
I met the same problem... How is it going

**Comment by raghavendra-talur** [comment]
@jianzi123 the issue filed here is only to improve the error message. If you are facing same error then the real fix is to ensure that the disk is not partitioned already.
