### ISSUE TITLE
Allow etcd3 backend store for heketi DB

### ISSUE THREAD

**Issue by jarrpa** [heketi/heketi#599]
With the availability now of transactions in etcd3, we should implement the ability to use an etcd3 cluster to store our database. For all use cases this would grant us an increased reliability, and it would greatly simplify our Kubernetes deployment scenario.

Per discussion with @lpabon, this should be relatively straightforward to implement via shim layer that translates our BoltDB calls to etcd3 by using [this client](https://github.com/coreos/etcd/tree/master/clientv3). Note that etcd3 relies on BoltDB underneath. Along with this shim layer, we would also need to implement the ability to select this functionality as an optional feature as well as provide the etcd cluster information.

**Comment by wattsteve** [comment]
Heketi is meant to be able to provision volumes from standalone traditional GlusterFS clusters as well as ones that are containerized and running in Kubernetes. Whichever path we pick going forward we need to make sure that it works for the traditional GlusterFS clusters as well.

**Comment by jarrpa** [comment]
@wattsteve Agreed, and certainly keeping that in mind. We would be agnostic to how the etcd3 cluster is deployed, and only care that it exists, but make sure to keep functional parity between etcd3 and direct BoltDB backends.

**Comment by joejulian** [comment]
As of kubernetes 1.6, the suggested store is configmap instead of going directly to etcd3.

**Comment by jarrpa** [comment]
This is mostly obsolete since heketi implemented the ability to backup to a Secret. Closing.
