### ISSUE TITLE
Tuning Volume Options

### ISSUE THREAD

**Issue by rushtehrani** [heketi/heketi#605]
Correct me if I'm wrong but I looked around and I don't see a way to [tune volume options](https://gluster.readthedocs.io/en/latest/Administrator%20Guide/Managing%20Volumes/#tuning-options) with Heketi.

For example, I am looking for a way to restrict access to volumes via the `auth.allow` option.  This will also be pretty important for [small file performance tuning](http://blog.gluster.org/2016/10/gluster-tiering-and-small-file-performance/)

**Comment by lpabon** [comment]
Once Heketi creates the volume, you can go ahead and set any of those values in the volume.  Currently Heketi does not allow settings these values, but may be a future a release we may be able to accommodate the request.

**Comment by MohamedAshiqrh** [comment]
https://github.com/heketi/heketi/pull/751

This might help this case.

**Comment by phlogistonjohn** [comment]
The last comment on this issue was over a year old. Recent versions of Heketi and the glusterfs volume provisioner do support passing gluster volume options. Closing issue. If you think additional discussion is needed please reopen the issue.
