### ISSUE TITLE
Logging: Heketi logs advancement 

### ISSUE THREAD

**Issue by MohamedAshiqrh** [heketi/heketi#606]
This is a proposal on few important logs which heketi has to be doing as we are making the log [persistent](https://github.com/heketi/heketi/issues/552). 

* All the http.Error must also be logged (using logger).
* Mention error messages more readable(For Eg: "Id not found" is returned for all the Id, Better to mention which Id like nodeId,deviceId,etc).
* Also log more(like db_op, request to executors from app) to find the flow of code more easily. Also makes debugging from logs easy as we are approaching more users.

**Comment by phlogistonjohn** [comment]
All good points but mostly covered by other issues or existing code. Closing issue.
