### ISSUE TITLE
Integrate with gluster-kubernetes

### ISSUE THREAD

**Issue by jarrpa** [heketi/heketi#624]
With https://github.com/gluster/gluster-kubernetes now also hosting files for creating Kubernetes and OpenShift resources, we should figure out how to go about integrating with that project to have a single place where the Kubernetes and OpenShift files live. This should come hand-in-hand with creating a reliable, programmatic method for importing the gluster-kubernetes project so that heketi can take advantage of it in its functional testing and possibly also provide a place for Ci for the project.

**Comment by lpabon** [comment]
+1

**Comment by phlogistonjohn** [comment]
This sorta-kinda mostly happened, although the test coverage could probably have been better. I don't see much value in keeping this issue open any longer. Please reopen and discuss if you feel differently.
