### ISSUE TITLE
Release binaries for other architectures (e.g. aarch64, aarch32)

### ISSUE THREAD

**Issue by ravishivt** [heketi/heketi#627]
v3.1 is missing the linux and darwin binaries.

Additionally, I would love to see aarch64 and aarch32 binaries for ARM users.

**Comment by lpabon** [comment]
This is a great idea and a great opportunity to change our release binaries to be built using [goxc](https://github.com/laher/goxc).

**Comment by sheerun** [comment]
cheering! :)

**Comment by ravishivt** [comment]
I see the 3.1 binaries have been released.  👍   I'll change this issue's title to be for the multi-architecture support.

**Comment by lpabon** [comment]
I'm going to take a look at https://github.com/laher/goxc

**Comment by sheerun** [comment]
There's also https://github.com/mitchellh/gox

**Comment by ravishivt** [comment]
While we're on the subject, it would be great if along with heketi binary releases, we also pushed multi-platform docker images to docker hub.  Then users can do something similar to the [recommended approach](https://github.com/luxas/kubernetes-on-arm) for installing flannel or kubernetes-dashboard on arm/arm64 boards:

`curl -sSL https://rawgit.com/coreos/flannel/master/Documentation/kube-flannel.yml | sed "s/amd64/arm64/g" | sudo kubectl create -f -`

**Comment by ravishivt** [comment]
A good reference for `gox` cross-compile may be [helm's Makefile](https://github.com/kubernetes/helm/blob/master/Makefile).  ARM support was added in https://github.com/kubernetes/helm/pull/1722 although it's missing the `linux/arm64` target.

**Comment by lpabon** [comment]
nice. I just created kubernetes raspberry pi 3 cluster out of three of them.  I will definitely try to make heketi for arm.

**Comment by lpabon** [comment]
![kube](https://cloud.githubusercontent.com/assets/3880001/22164413/260d4ee6-df25-11e6-8225-33aa1c30f16e.jpg)

:smile:

**Comment by ravishivt** [comment]
Nice.  My stack is very similar but using Odroid C2 boards instead of RPIs.  I also found a gigabit switch that runs off 5V so my USB power adapter can power everything.

Now we just need some USB sticks and the heketi/glusterfs ARM images built and we'd have a pretty awesome personal cluster.  Also great for demos.

**Comment by lpabon** [comment]
@ravishivt Do you mind looking at #658 ?

**Comment by robdewit** [comment]
@ravishivt I feel kind of stupid, but where can I find the v3.1 server binaries? I gather you found them, but on the releases page there is just links to sources and the client binaries.

**Comment by lpabon** [comment]
@robdewit The version 3.1 of the server is available as a container `heketi/heketi:3` or as `heketi/heketi:latest`.  Are you looking to install as a package instead of as a container?

**Comment by robdewit** [comment]
I was indeed looking for a server-tarball, but a docker image will do also. Thanks!

**Comment by lpabon** [comment]
Closed by #658

**Comment by GarethOates** [comment]
Is there an arm compatible docker images available for heketi?  I'm struggling to find one on Dockerhub.

**Comment by phlogistonjohn** [comment]
@GarethOates I don't believe there is. To the best of my knowledge none of the current heketi deployments use anything other than x86. If this is something you want or if you wish to discuss this topic further please open a new issue as this one had been closed for around a year.

**Comment by nixpanic** [comment]
Heketi is part of the standard Fedora repositories, and those are provided for several architectures. It should be possible to build containers for these architectures, but I do not know which container registry service offers building for multiple architectures (maybe quay.io?). Building the image yourself is probably the easiest, there is a [`Dockerfile` for testing](https://github.com/heketi/heketi/tree/master/extras/docker/fromsource)(this is used for [Docker Hub](https://hub.docker.com/r/heketi/heketi/)) and [one for CentOS](https://github.com/heketi/heketi/tree/master/extras/docker/centos)(for [the CentOS Registry](https://registry.centos.org/gluster/storagesig-heketi)). Changing the 2nd for Fedora should be simple enough, just use a Fedora image as base, replace `yum` with `dnf` and remove `centos-release-gluster`.
