### ISSUE TITLE
Endpoint changes with k8s 1.5

### ISSUE THREAD

**Issue by ravishivt** [heketi/heketi#628]
In kubernetes 1.5, the glusterfs plugin automatically creates the endpoints when a PVC is added. As per https://github.com/kubernetes/kubernetes/pull/34705:

> When the persistent volumes are dynamically provisioned, the Gluster plugin automatically create an endpoint and a headless service in the name `gluster-dynamic-`

The `setup-openshift-heketi-storage` command should therefore no longer create the "heketi-storage-endpoints" Endpoint or Service as it's unnecessary.

**Comment by lpabon** [comment]
@ravishivt Hi, setup-openshift-heketi-storage (which the name now should change to something more kubernetes based) does not create a PVC.  Instead it refers to the volume directly.  That is why it needs the endpoints.

**Comment by phlogistonjohn** [comment]
Last activity on this bug is nearly two years old. Closing issue. If this is still a problem please feel free to reopen and discuss.
