### ISSUE TITLE
Deploy heketi in a single step/command

### ISSUE THREAD

**Issue by ant31** [heketi/heketi#631]
I've worked a little on this topic, only few changes are required to be able to deploy heketi in a single step. 
related to:  https://github.com/gluster/gluster-kubernetes/issues/39
The following description is up to discussion / changes but the main idea is we start the heketi-server and let it wait for the pvc to be bound/initialized and topology is loaded automatically from a configmap.

To deploy in one step heketi/glusterfs on kubernetes we can do the following steps:

Deploy kubernetes resources:
-> topology-configmap.yaml
-> heketi-pvc.yaml
-> heketi-service-account.yaml
-> heketi-svc.yaml
-> heketi-glusterfs-daemonset.yaml
-> heketi-deployment.yaml
-> heketi-init-job.yaml

The only file the user must edit is the topology-configmap.yaml, other resources can have working defaults.

In details:

The heketi-deployment.yaml, is the heketi-server:

It mounts the heketi-pvc, because the pvc is not bound, the pod can't be scheduled it waits.
It has an init-container that mounts also heketi-pvc, and wait for a heketi.db file exists to exist
The heketi-init-job.yaml is a job that does:

- mount the topology configmap
- start a heketi-server with emptyDir to store the db
- run heketi-cli --load topology:
- the job can have 2 container in the pod: 1 server | 1 client
- Create a the heketidbstorage glusterfs-volume, the glusterfs-endpoints
- Create a secret from the heketi.db
- Create the persistentvolume heketi-pv.yaml resource.
-> After this job, the heketi-db-secret is created and the pv/pvc are created too, so the heketi-server pod can start. The init container (or the job) mount the secret and copy it if does not exist in /var/lib/heketi

**Comment by lpabon** [comment]
@ant31 Thanks!

**Comment by obnoxxx** [comment]
I wasn't able to follow up earlier, but better late than never...

how does this relate to the https://github.com/gluster/gluster-kubernetes/ and its gk-deploy tool? Its (achieved) purpose is to deploy heketi and gluster in a single command. You only have to edit a topology file. Sounds similar to the above, but with a different approach?! ...

**Comment by ant31** [comment]
@obnoxxx yes, this is different. In short, the target here is to have actions easy enough so no extra script is required. 

You can script the a multi-step process, here the goal is to deploy in one command so we can take advantages and consolidate experience in deploying application on kubernetes with tools like helm or plain kubectl.

**Comment by pcm32** [comment]
Hi! Is there anything in terms of helm chart that someone has developed that we could try along these lines? I mean, to deploy Heketi through a helm install call.

Thanks!

**Comment by manisha-tanwar** [comment]
Hi @pcm32 were you able to install it using Helm?
