### ISSUE TITLE
question the need of own state database

### ISSUE THREAD

**Issue by vasu1124** [heketi/heketi#632]
Is it actually really necessary to do your own state management (be it boltdb or etcd)?
I understand the need for an initial topology file. But it could also be inferred from labels of the nodes, which would make it dynamic.
The alternative approach of managing own state would be to read the state from gluster itself.
This way, a restart (or periodic resync) of heketi would read the real state (volume, configs, bricks, ...) from gluster itself (thus no potential for inconsistencies). Also, If an admin "interferes" using gluster cli tools (maybe for advanced failure handling), there would be no need to rectify heketi state.

Could you shed some light on your thinking on the points
a) read topology from labels on nodes
b) sync state from gluster, rather than own state management?

Thanks!

**Comment by obnoxxx** [comment]
Thanks for raising this issue! You are fully correct. There is a lot of state that heketi keeps in duplication of gluster's internal state. The only aspects that gluster does not have are:

- heketi can manage multiple gluster clusters, not just one
- heketi keeps track of the raw disk devices, not just bricks, and picks storage space from those.

All that being said, we are already planning to move towards what we call 'stateless heketi' which will be more tightly integrated with gluster and will not have it's own duplicated state for those items that reside in gluster.

**Comment by lpabon** [comment]
@vasu1124 This is a tough one to answer.  When Heketi was created, Kubernetes did not exist.  Also, although possible to read enough information about the cluster from Kubernetes, Heketi also supports non-kubernetes based deployments.  Even then, not all information may be taken from Kubernetes (disks, storage networks, etc).  Also it may take some time for Gluster to maintain such state across a _single_ cluster, but multicluster state needs to be kept somewhere also.

At least in the near term, things will not change until we find a way that satisfies the requirements in Kube and non-Kube deployments.

@obnoxxx I'm not sure what 'stateless heketi' is, but I will definitely check it out.

**Comment by obnoxxx** [comment]
@lpabon I don't think this question is about Kubernetes deoployment in the first place. I think it is about the relationship between Heketi and Gluster. One of the fundamental problems of the current design of heketi is that it maintains the complete state of nodes, bricks, volumes in its own database, thereby duplicating the state that is also present in gluster. This leads to discrepancies between the feature-set of gluster-cli and heketi-cli, i.e. you can not use gluster-cli for volume operations without rendering heketi's db invalid. In particular some features that gluster itself supports are currently not available with heketi, and their implementation requires quite an effort replicating logic that is in gluster. We have been discussing this problem between a couple of engineers and came up with the plan of removing as much as possible from heketi's db, using gluster's state as much as possible. (Keeping the notion of the various clusters it maintains and likely the disk devices.) This not fully designed yet, but the idea is what we called **stateless heketi** to give this project a name. I still need to write to heketi-devel about these (still rather vague) plans.

**Comment by lpabon** [comment]
@obnoxxx np, I think it @vasu1124 meant Kube because it says ` But it could also be inferred from labels of the nodes, which would make it dynamic.`.  I completely agree that a feedback system is needed to remove any inconsistencies.  I look forward to the proposal.

**Comment by vasu1124** [comment]
Sorry for the long pause.
Yes, my comments came form an exercise with K8s, but I would argue that (besides the topology read from labels) the question on the necessity of having to sync states is generic.

In light of having to upgrade my test cluster (with heketi) from 1.5 to 1.6, I am again painfully reminded of the indirect proposal in this issue. Looking forward to "stateless heketi" on the roadmap :-)

**Comment by phlogistonjohn** [comment]
While a valid criticism of the Heketi design, changing this in any major way is probably outside the expected lifespan of Heketi. In addition the last comment on this issue was over a year ago. Closing issue.
