### ISSUE TITLE
Use Case: identify the failing disk from a failing brick

### ISSUE THREAD

**Issue by portante** [heketi/heketi#634]
Operationally, if I find that errors are reported from a brick, perhaps one brick of many on a physical disk, I'd like to be able to have Heketi flag the falling bricks and their underlying disks for replacement.

Having a Heketi dashboard that shows the health of the nodes, their bricks, and disks would be very powerful.

Ideally, such an interface could be visually represented, and then have automated replacement actions.

Further, it would be powerful to describe to Heketi a replacement pool of disks that can be used for replacements to help automate the process, so that long term as an administrator I am working to just keep a proper number of replacement drives available rather than dealing with the failures directly.

**Comment by obnoxxx** [comment]
Thanks for reporting the issue. Here is a related issue:

https://github.com/heketi/heketi/issues/161

**Comment by MohamedAshiqrh** [comment]
https://github.com/heketi/heketi/pull/676

Will update the PR.

**Comment by phlogistonjohn** [comment]
While perhaps not optimal this information is available in one single command of heketi-cli topology info, finding the brick in question and scrolling up to the associated device line.

In addition, the last comment on this issue was over a year old. Closing issue. If you think additional discussion is needed please reopen the issue.

**Comment by portante** [comment]
It seems this is all about usability.  @phlogistonjohn, if the decision is going to be that a user has to pour through topology info output to find failing bricks, do we all feel this is a good direction for usability of Heketi?

Based on our experience with Heketi, it is currently a large support problem for us, so we are moving away from it.

**Comment by phlogistonjohn** [comment]
Perhaps I did not understand your use case well enough. I think it's important that we have a good understanding of the challenges you are facing maintaining your cluster. This applies to both Heketi and any potential work we may want to contribute to GlusterD2, which is the longer term direction for gluster volume and brick management.

Could you please outline the current steps that you take when you encounter issues like this and where you encounter the most difficulties? Is it primarily determining the right device id for a given brick, or are there additional issues like knowing what to do next?
