### ISSUE TITLE
Use Case: removing a node from Heketi

### ISSUE THREAD

**Issue by portante** [heketi/heketi#636]
Over time, I'd like to be able to remove a node from participation in Heketi, and in turn, from its participation in any gluster volumes.

The Wiki page seems to describe that ability, see https://github.com/heketi/heketi/wiki/Managing-your-clusters#reducing-storage-capacity.

However, as described, it is incumbent upon the administrator to perform the proper steps to ensure all devices are first deleted before the node is deleted.

Does Heketi warn of node deletion before all devices are deleted?

When a device is deleted, is a new replacement device created it to take its place somewhere else in the cluster?

Are the existing GlusterFS volumes able to remain active during a device delete?

**Comment by obnoxxx** [comment]
Related to https://github.com/heketi/heketi/issues/635 -- replace a node in the cluster.

The problem I see is that simply removing a node with disks that are in use in volumes will render the cluster and volumes in a bad state. 

The gluster documentation for replacing bricks is somewhat involved.

https://gluster.readthedocs.io/en/latest/Administrator%20Guide/Managing%20Volumes/#replace-brick

Need to find out whether it is possible to first just remove a brick and then later add a different brick...

**Comment by obnoxxx** [comment]
https://gluster.readthedocs.io/en/latest/Administrator%20Guide/Storage%20Pools/

Adding/removing nodes.

**Comment by MohamedAshiqrh** [comment]
https://github.com/heketi/heketi/pull/752

This does the remove device operation.

**Comment by MohamedAshiqrh** [comment]
This issue is fixed. @obnoxxx @lpabon can we close this?

**Comment by obnoxxx** [comment]
@MohamedAshiqrh right. Closing

@portante , if you feel it's not fixed, please re-open.
