### ISSUE TITLE
Authentication failing with "Token used before issued"

### ISSUE THREAD

**Issue by think01** [heketi/heketi#646]
We have a Kubernetes cluster on 3 Vagrant/VirtualBox nodes and we deployed Heketi to manage GlusterFS volumes provisioning.

All worked well, but when we activated authentication (setting users and secrets in heketi.json) heketi-cli often doesn't work, returning the error "Token used before issued".

We digged a bit into Heketi code and found that this error originates from file heketi/vendor/github.com/dgrijalva/jwt-go/claims.go
For what we can understand, at line 111:

    func verifyIat(iat int64, now int64, required bool) bool {
    	if iat == 0 {
    		return !required
    	}
    	return now >= iat
    }

the iat timestamp (that is, the client's time) is compared with the server timestamp. That is very easy to randomly fail if client and server run on different nodes. If we call heketi-cli from the same node where Heketi is running on, everything works fine.

Are we missing something? Maybe the time compare is by design and it requires the JWT client to issue calls in a controlled way?

Thanks for any feedback.

**Comment by think01** [comment]
Thx for your answer, @lpabon 
By default, Vagrant/VirtualBox machines get their clocks synchronized with the physical host, so since we're running them on the same PC, they should have the exact same time.
Anyway, we also tried to set up the NTP service, nothing changed.

Thing is that the authentication set up that way, with the strict check on now >= iat, seems to us doomed to fail sometimes, because the clock sync cannot be always perfect (clock skews happen).

Is anybody able to use successfully Heketi authentication?

**Comment by lpabon** [comment]
Yes, we use it successfully on all our functional tests (available under `tests/functional`).  Let me think about it more to see how to make this more reliable

**Comment by kongyibjcn** [comment]
Hi 

How about the finial solution to fix this issue?  I met the same issue " Error: Token used before issued", I see some one mentioned that we can config iat and exact same time in heketi.json. Does anyone knows how to do that ?

**Comment by kongyibjcn** [comment]
Hi 
How about the finial solution to fix this issue?  I met the same issue " Error: Token used before issued", I see some one mentioned that we can config iat and exact same time in heketi.json. Does anyone knows how to do that ?

**Comment by jmencak** [comment]
Hitting the same issue it seems.

**Comment by jmencak** [comment]
For me, getting the clocks in sync on all machines fixed this problem.

**Comment by DanyC97** [comment]
@jarrpa any chance you have seen this issue in latest heketi version (v5) ? my entire OpenShift cluster is synced and only few nodes are being drifted by few seconds, yet i do still see the issue ....

**Comment by DanyC97** [comment]
and after i've bounced the whole cluster, things works ....s'thing is fishy here ...

**Comment by DanyC97** [comment]
@raghavendra-talur @phlogistonjohn any chance you might be able to help me please? i'm stuck and unable to progress .. thx in advance !

**Comment by raghavendra-talur** [comment]
In most of the cases, you would see this error if the time on all machines is not synced. For an exception where it is seen due to clock skew I have raised a PR #1223
