### ISSUE TITLE
Option to set uid/gid on volume create

### ISSUE THREAD

**Issue by barnzdan** [heketi/heketi#647]
Seems all volumes created are owned by root:root. There plans to implement set options on the volume that would allow for this? 

ie, 
gluster volume set <volume> storage.owner-uid <uid>
gluster volume set <volume> storage.owner-gid <gid>

**Comment by obnoxxx** [comment]
heketi supports gid security.
this can be used with heketi-cli:

```
heketi-cli volume create --gid <GID> ...
```

**Comment by barnzdan** [comment]
Which version of heketi-cli supports gid security?

% heketi-cli --version
heketi-cli v2.0.6

% heketi-cli -s $HEKETI_DEV volume create --size=10 \
--persistent-volume \
--persistent-volume-endpoint=heketi-endpoints \
--gid 1002 > heketi-pv.yaml
Error: unknown flag: --gid

**Comment by barnzdan** [comment]
Thanks I was using an old version.

**Comment by obnoxxx** [comment]
Right, heketi version >= 3 should have the --gid parameter.
Thanks for using heketi! :-)
