### ISSUE TITLE
Dynamic volume provisioning with --gid support

### ISSUE THREAD

**Issue by alikhajeh1** [heketi/heketi#657]
We're using Heketi with OpenShift and restricted Security Context Constraints for user projects. Our current flow is:
1. User creates PVC
2. OpenShift creates the PV dynamically with Heketi (using a predefined default Kubernetes storageclass)
3. We manually run `chown` and `chmod` on the brick dir of on all gluster storage nodes so the user's pod has the correct permissions to read/write to the volume files.

Do you know if there's a way to automate step 3 such that Heketi fetches the user's project's openshift.io/sa.scc.supplemental-groups minimum ID and uses that as the `--gid` parameter when creating the volume? This would remove the need for the manual step 3.

**Comment by ravishivt** [comment]
Seems like #511 may cover this request, although I might not be fully understanding #511.

**Comment by alikhajeh1** [comment]
@ravishivt can you please elaborate on how you seem them as being related? No new metadata is needed, we just need a way for heketi to do step 3 - the information it needs is already in the user's project's openshift.io/sa.scc.supplemental-groups field.

**Comment by ravishivt** [comment]
Understood, I had thought you wanted to specifically set the GID in the PVC's definition.  Instead, you want heketi to automatically use a default which is indeed different than #511.

**Comment by lpabon** [comment]
CC: @heketi/dev

**Comment by alikhajeh1** [comment]
I'm going to close this issue as OpenShift 1.4.1 has addressed this issue :)
