### ISSUE TITLE
Where are the v3 server binaries?

### ISSUE THREAD

**Issue by robdewit** [heketi/heketi#659]
I can download the **client** binaries from https://github.com/heketi/heketi/releases
Is there no tarball for the **server** binaries? The documentation mentions installation through other means than yum and dnf (https://github.com/heketi/heketi/wiki/Running-the-server).

**Comment by lpabon** [comment]
You can download it as a container. Are you looking for the binaries themselves?

**Comment by robdewit** [comment]
I assumed there was a server-tarball just like the client one, but a docker image will do. Thanks!

**Comment by lpabon** [comment]
FYI We now have Heketi 4 server and client binaries, while we also have containers available
