### ISSUE TITLE
License change

### ISSUE THREAD

**Issue by tamalsaha** [heketi/heketi#662]
Hi,
We are exploring the idea of using Heketi with our [GlusterFS controller for Kubernetes](https://github.com/appscode/glusterfs). Our controller uses leader election process to automatically apply recovery process in case of split. I noticed that the license for heketi was changed from Apache 2.0 to a mix mode GPL/Apache combination. I did not find any issue that explained any reasoning behind that. We would prefer an full Apache license support. Do you mind giving some background on license change?

Thanks.

**Comment by TamalSaha** [comment]
Also from CNCF:
https://www.cncf.io/blog/2017/02/01/cncf-recommends-aslv2

**Comment by lpabon** [comment]
The Heketi server itself is in LGPL3/GPL2 but the client is in Apache2.  Is the server license a concern?  Wouldn't that also mean that running GlusterFS (LGPL3/GPL2) would also be a concern?

cc: @obnoxxx

**Comment by TamalSaha** [comment]
"Concer" may be too strong of a word. I am using curious why it changed. Why not also license the server under Apache 2?

**Comment by lpabon** [comment]
Ah ok.  LGPL3 and GPL2 creates a better community model because code must be shared back if the Heketi server has changed, and thus everyone benefits. :tada: 

We also chose LGPL3 in case anyone wants to include source pkg from Heketi server they can and will not interfere since LGPL3 allows linking not just dynamically but also in source.

**Comment by obnoxxx** [comment]
Also the core logic pieces are mot a part of gluster than of any golang/apache world consumer. That's why we changed it. The parts that a consumer needs to cpmpile in are all under Apache.

Closing this for now. Please reopen if there is more to discuss.

Thanks!

**Comment by obnoxxx** [comment]
Also the core logic pieces are mot a part of gluster than of any golang/apache world consumer. That's why we changed it. The parts that a consumer needs to cpmpile in are all under Apache.

Closing this for now. Please reopen if there is more to discuss.

Thanks!
