### ISSUE TITLE
Documentation for creating volumes

### ISSUE THREAD

**Issue by harryge00** [heketi/heketi#673]
The wiki seems a bit simple. More details can be added such as how to use different parameters for `heketi-cli volume create`
https://github.com/heketi/heketi/wiki/Create-a-volume

**Comment by lpabon** [comment]
True. Heketi's main goal is to serve as a service to other APIs, but it would be nice to provide better documentation for the heketi-cli.  Please feel free to edit the wiki.  Let me know if you need access.

**Comment by phlogistonjohn** [comment]
Last activity on this issue was over a year ago. Documentation is now kept as markdown files within the docs directory in the tree. Everyone is welcome to file PRs to update/improve the documentation.

Closing. Please reopen if additional discussion is needed.
