### ISSUE TITLE
Heketi should provide a way to copy the existing db to the secret 

### ISSUE THREAD

**Issue by MohamedAshiqrh** [heketi/heketi#683]
This issue is mainly for the backward compatibility. Fix could be just a copy job from gluster volume to secret.

**Comment by MohamedAshiqrh** [comment]
@lpabon share your thoughts.

**Comment by lpabon** [comment]
@MohamedAshiqrh I do not think this is the responsibility of Heketi.  I think, as you point out, that a job would be best for this.
