### ISSUE TITLE
Openshift Origin: scaling heketi for multiple replicas not working

### ISSUE THREAD

**Issue by aliscott** [heketi/heketi#685]
Using OpenShift Origin 1.4.1 and heketi-cli v4.0.0, I'm trying to scale up the heketi deployment config so it is highly available.

After following https://github.com/heketi/heketi/wiki/OpenShift-Integration---Project-Aplo I run:
```
oc scale --replicas=2 dc/heketi
```

The new heketi pod will fail to get to the `Ready` state with the following errors:
```
  5m		17s		7	{kubelet master1}	spec.containers{heketi}	Warning		Unhealthy	Liveness probe failed: Get http://10.128.0.70:8080/hello: dial tcp 10.128.0.70:8080: getsockopt: connection refused
  5m		7s		36	{kubelet master1}	spec.containers{heketi}	Warning		Unhealthy	Readiness probe failed: Get http://10.128.0.70:8080/hello: dial tcp 10.128.0.70:8080: getsockopt: connection refused
```

**Comment by lpabon** [comment]
Heketi only supports a single replica because it must have exclusive access to the db.

**Comment by aliscott** [comment]
This also causes an issue when the single heketi pod is recreated.

Since the old pod is still terminating when the new one is created, the new pod opens the db in read-only mode, with this warning:
```
Unable to open database.  Retrying using read only mode
```

To get round this I've added `terminationGracePeriodSeconds: 0` to the heketi deployment config.

**Comment by lpabon** [comment]
@aliscott Thanks!  This also will not be necessary in Heketi 4 since it backs up the database to a secret and no longer uses the glusterfs volume for the db.

**Comment by aliscott** [comment]
@lpabon thanks! Will the new secret implementation for the database work with OpenShift? I see it is already in the deployment yaml for Kubernetes, but not OpenShift yet.

**Comment by MohamedAshiqrh** [comment]
@aliscott We have deployment of the same in https://github.com/gluster/gluster-kubernetes. I can add the openshift content here too but I feel it is unnecessary. if @heketi/maintainers  @heketi/dev feel we should maintain here too then I can send a PR for this.

**Comment by phlogistonjohn** [comment]
Last activity on this issue was over a year ago. Closing. Please reopen if additional discussion is needed.
