### ISSUE TITLE
no api to get the free or used size of a volume

### ISSUE THREAD

**Issue by 18025341316** [heketi/heketi#687]
When use heketi to dynamicly provide storage for kubernetes pod,there is a need to know the free size of a volume so we can explode the volume size on need.

**Comment by lpabon** [comment]
Correct. Heketi deals more with devices and the cluster.  To get volume information you will need to get information from GlusterFS.

**Comment by 18025341316** [comment]
yes,we can get the free or used size of a volume from GlusterFS,but heketi already has a api to get the volume information,why not include the free or used size?

**Comment by lpabon** [comment]
@18025341316 Ah, good question.  The thing is that Heketi is not a RESTful interface for GlusterFS volumes, it is more of a 'pool' manager.  Once the volume is created, all calls must now go to the volume to get the latest information.

**Comment by 18025341316** [comment]
@Lpabon,is thare some api to get the free size of volume besides gluster command line?

**Comment by lpabon** [comment]
I know that the glusterd 2.0 project is supposed to provide a REST interface, but I am not sure how far they are in that project.

**Comment by 18025341316** [comment]
@lpabon TKS.Do you have some idea about montioring gluster volume so case when volume is full We can expland volume on demand?

**Comment by phlogistonjohn** [comment]
Last activity on this issue was over a year ago. Closing. Please reopen if additional discussion is needed.
