### ISSUE TITLE
Support for hybrid deployments

### ISSUE THREAD

**Issue by sheerun** [heketi/heketi#691]
Does heketi supports deployments across multiple clusters of different types?

I'd like to setup a cluster bare centos machines with glusterfs (as a safety measure), and then only attach to it kubernetes clusters that participate in glusterfs cluster, but that I can also safely teardown at any time (I'll never teardown cluster of bare centos machines).

Prove me wrong, but from I see heketi doesn't support using multiple executors for managing custers, as only one type is chosen and pinned during startup: https://github.com/heketi/heketi/blob/master/apps/glusterfs/app.go#L74

Could heketi support using different executors per-host?

**Comment by lpabon** [comment]
Correct, but this is something we could do for a future release.

@heketi/dev

**Comment by lpabon** [comment]
We'll take a look at it and decide if it will be for Rel 5 or 6

**Comment by MohamedAshiqrh** [comment]
@lpabon @sheerun This will be a good feature to have. As it can manage multiple gluster cluster in any environment it may be.

**Comment by phlogistonjohn** [comment]
I agree with @obnoxxx that this seems out of scope for the expected lifespan of heketi. Closing issue. Please reopen if additional discussion is needed.
