### ISSUE TITLE
Misleading error message

### ISSUE THREAD

**Issue by sheerun** [heketi/heketi#695]
It seems that I dont' have enough glusterfs nodes to support given nomber of replicas, as following succeeds:

```
heketi-cli volume create --size=10 --replica=1 --durability=none
```

but following fails:

```
heketi-cli volume create --size=10 --replica=2 --durability=none
```

Unfortunately heketi fails with message "Error: No space" instead of "Error: Not enough replicas"

Could you fix this error message?

**Comment by lpabon** [comment]
@heketi/dev

**Comment by phlogistonjohn** [comment]
Very stale issue. Closing.
