### ISSUE TITLE
No space to backup in kubernetes secrets

### ISSUE THREAD

**Issue by sheerun** [heketi/heketi#697]
[heketi] ERROR 2017/03/01 04:14:32 /src/github.com/heketi/heketi/apps/glusterfs/app_middleware.go:69: Unable to backup database to kubernetes secret: Unable to create database secret: Secret "heketi-db-backup" is invalid: data: Too long: must have at most 1048576 characters

I have no idea what it tries to save and why it is that long. Please let me know if I can help debug this.

**Comment by lpabon** [comment]
Heketi 4.0 saves the database to a Kubernetes secret.  Seems that the max secret size is small.  I'll take a look at this.

**Comment by lpabon** [comment]
Bummer, seems that the secret max [size is only 1MB](https://kubernetes.io/docs/user-guide/secrets/).  I thought it was 16MB.  We'll have to look at how to fix this issue.

**Comment by lpabon** [comment]
@heketi/dev

**Comment by sheerun** [comment]
1mb seems like a lot, though :) maybe you keep unnecessary things in the db

**Comment by lpabon** [comment]
seems like we could zip it, that should be easy

**Comment by lpabon** [comment]
@sheerun do you mind providing the size of the db?  You can run  `kubectl exec -ti <heketi pod name> /bin/bash` then run `ls -al` under `/var/lib/heketi`

**Comment by sheerun** [comment]
Unfortunately I've re-deployed heketi from this cluster since I've published this issue, and the database seems to have only 24KB now: 

```
-rw-r--r--  1 root root  24K Mar  2 08:35 heketi.db
```

I imagine something went wrong with heketi and it saved to database more than it should. Unfortunately I cannot assist you any more what happened exactly. I'd think what heketi saves to database, and if it's possible that due some bug it can write a lot more than it should.

**Comment by obnoxxx** [comment]
First of all, what this issue teaches me is that the introduction of backup to kubernetes secret was incomplete, in that it was unconditional. I would like us to introduce a switch first of all to enable (or disable) this feature. Then we can still think about how to reduce the size of the db itself. But we should make it switchable-off asap, imho.
