### ISSUE TITLE
Unable to remove volume created with just one replica

### ISSUE THREAD

**Issue by sheerun** [heketi/heketi#698]
Sorry for that many issues today, just one more. I get following error when trying to delete volume:

```
Error: Cannot delete thin pool tp_d8b3c3abeca1c7a1545b3c0cbad8bf99 on k8s-agent-50e6fac2-0 because it is used by [-1] snapshot(s) or cloned volume(s)
```

I think I've created this volume with:

```
heketi-cli volume create --size=10 --replica=1 --durability=none
```

and then added two more nodes to the heketi cluster (it turned out 1 is too low for kubernetes)

**Comment by obnoxxx** [comment]
@sheerun thanks for reporting all this. 
This looks weird and needs to be investigated.
Which operations did you do with the volume before trying to delete?

**Comment by sheerun** [comment]
I think none except creating it and adding nodes to cluster. It might but not have to be connected to creating volume with replica count less than number of servers in cluster, and then resizing cluster size, and then manipulating volumes some more..

**Comment by pashok2398** [comment]
Hi, facing the same error:
Error: Cannot delete thin pool tp_9cd39e2df0df6d227e3ce5a8117bb2f4 on dev-minion-3.openstack.domain.com because it is used by [-1] snapshot(s) or cloned volume(s).
Running on k8s using the deployment script, everything looks working fine except this.
The machines are vm's (3) on openstack with additional volume.

**Comment by fascinatedcow** [comment]
I also have this problem, but I have not resized my cluster. I do have something slightly weird though; I'm running with `volumetype: disperse:2:1` See https://github.com/heketi/heketi/pull/787 for more information about that.

**Comment by phlogistonjohn** [comment]
Last activity on this issue was over a year ago. I also have reason to believe this is no longer possible on Heketi v8.0.0. Closing. Please reopen if additional discussion is needed.
