### ISSUE TITLE
LVM umount

### ISSUE THREAD

**Issue by corlettb** [heketi/heketi#699]
I had an issue with heketi/gluster/lvm last week.

Environment Info

OS: Ubuntu 16.04
Heketi: 3.1.0 
Kubernetes: 1.5.3

1xHeketi server
3xGlusterfs servers
2xebs volumes on each glusterfs server.

Essentially what happened is a volume was created (10g) and some kubernetes pods kicked off which were writing a lot of data to the volume.

Once the volume got quite full. Maybe around the 80%-90% range the following happened (from the syslog)

```
Feb 23 18:18:25 k8s-np-glusterfs-a-3 lvm[8283]: WARNING: Device for PV Aqy91y-F6BL-xCq4-tDhd-noq6-H98s-gH2xvf not found or rejected by a filter.
Feb 23 18:18:25 k8s-np-glusterfs-a-3 lvm[8283]: Cannot change VG vg_c47c679f88eba8c62c1cb6ee60eeac6f while PVs are missing.
Feb 23 18:18:25 k8s-np-glusterfs-a-3 lvm[8283]: Consider vgreduce --removemissing.
Feb 23 18:18:25 k8s-np-glusterfs-a-3 lvm[8283]: Failed to extend thin pool vg_c47c679f88eba8c62c1cb6ee60eeac6f-tp_3ccadb8af20ddda40ec57b28b55fe560-tpool.
```

Unfortunately rather than blocking further writes this caused the os to umount the logical volume.

Maybe this was down to glusterfs using that space for snapshots? Maybe there are lvm settings to prevent this?

I did notice the following from your github:

RUN sed -i.save -e "s#udev_sync = 1#udev_sync = 0#" -e "s#use_lvmetad = 1#use_lvmetad = 0#" /etc/lvm/lvm.conf

Glusterfs, was unaware of this and it just started to write files to the root file system rather than the logical volume. 

This then caused the root file systems to fill up on some of the glusterfs nodes. Which is what alerted me to the issue.

As the root filesystems on the glusterfs nodes started to fill up one at a time, this caused further provisioning/deprovisioning problems for heketi.

Sadly this caused heketi to "corrupt" its own database. The structs stored in the boltdb DEVICE bucket were referring to Bricks that did not exist in the BRICK bucket. 

This prevented any topology commands from working. All returned "ID not found" as it tried to load the device.

I hacked the code to ignore missing buckets, and hacked the code to create non-sparse lvm volumes for future provisions (yes this will probably prevent gluster snapshots).

**Comment by lpabon** [comment]
Great debugging @corlettb .  @heketi/dev  please take a look.

**Comment by MohamedAshiqrh** [comment]
@lpabon Will take a look soon. @humblec FYI.

**Comment by ursuad** [comment]
Any updates on this?

**Comment by max8899** [comment]
Any updates? @lpabon @MohamedAshiqrh @corlettb  ?  Is this problem solve? Hesitated while using this in product design .

**Comment by jarrpa** [comment]
lpabon and ashiq are no longer working on this project.

@raghavendra-talur @phlogistonjohn @obnoxxx Is this something that still needs to be looked at or can it be closed?

**Comment by phlogistonjohn** [comment]
I think @nixpanic was that last person I communicated with who has seen a similar issue. Any thoughts @nixpanic ?

**Comment by nixpanic** [comment]
I expect that gluster/gluster-containers#104 improves some of the LVM handling.

However that is not directly related to thin provisioning... When thin provisioning is used, it is **very** important to monitor usage and prevent running out of space. Resizing the almost out of space LVs is not trivial in most cases. @raghavendra-talur looked into something like this last week iirc.

**Comment by phlogistonjohn** [comment]
Stale issue. Closing.
