### ISSUE TITLE
Cleaning up setup-openshift-heketi-storage path

### ISSUE THREAD

**Issue by MohamedAshiqrh** [heketi/heketi#702]
@lpabon @obnoxxx @humblec @jarrpa @ramkrsna @raghavendra-talur 

Hi,
I think we should cleanup the setup-openshift-heketi-storage path as we do not require it anymore. Also as DB is Moved to secret the heketidbvolume should be able to delete. The check from stopping the volume to be delete should be removed. Share your thoughts?

**Comment by lpabon** [comment]
@MohamedAshiqrh  I think that is a great idea, but we really need to have more coverage on the secret support before we make a full change.  Take a look at #697 . Two things are interesting about that.  One is that we can use gzip from golang and compress the db.  That is easy.

The second is that for some reason the db over 1M in size.  That seems really weird and big to me.  Need to investigate if the db size increases with changes or updates even though no new keys are added.  This investigation is needed.

**Comment by humblec** [comment]
Indeed this is good thought. but as @lpabon mentioned, the heketi db size and the data we store in the DB need to be closely analyzed as we have 1M limit for secret.

**Comment by MohamedAshiqrh** [comment]
@lpabon @humblec  @heketi/dev 

The heketi db sizes to 1M with 3 nodes and 6 devices with 140 1 GB volume in Mock which I think is little. They will hit the issue faster if they multiple cluster managed by heketi.

Let me know if the information helped. I can also verify with just some operations if the db size is increased. 
@lpabon can you tell me just in what cases do you have in mind where no new keys are added but db is updated? I can give it a try and see what we can do. I like the gzip plan. When we mount the secret, we have to unzip the db and copy it to /var/lib/heketi.
