### ISSUE TITLE
volume create request should have a volume option field with it.

### ISSUE THREAD

**Issue by humblec** [heketi/heketi#711]
At the moment, heketi dont have a field for specifying gluster volume options. Its good to have a new member so that the client or caller can pass volume options in the request.

**Comment by obnoxxx** [comment]
I think this is not necessarily the right apporach:
One of heketi's principles is that it shields the lower level details from the caller.
Handing out low-level volume options to the caller of heketi seems to be against these principles. (similar to allowing to specifiy an explicit cluster ID.)

We might think about having some higher level options that call out for optimizing a volume config for certain workloads (small file  / large file / etc).

@humblec can you elaborate on why you would want a volume options field?

**Comment by humblec** [comment]
@obnoxxx u r fast :) .  I completely agree on the optimization or QOS based setting done by heketi its own. I am mainly looking for volume options like `client.ssl ` , `server.ssl` ..etc which has to be set on volumes to support encryption. What we can do here is, kind of whitelisted volume options in heketi and enable it if the user request comes in for those and discard the option if it does not belong to the allowed list of options.

**Comment by obnoxxx** [comment]
Ok, that makes sense. But we should still think about wrapping the gluster-options into some higher-level settings in heketi. like 'encryptable' or 'encrypted', etc. not sure what's the best approach here, just requesting to think about whether the path of least resistance is right...

**Comment by jarrpa** [comment]
@obnoxxx I actually agree with @humblec on this one. If we try to wrap everything, it becomes heketi's job to keep pace with any changes to Gluster's options. I see nothing wrong with allowing an advanced user access to the lower-level functionality, and in fact think it's regressive to block it entirely.

**Comment by obnoxxx** [comment]
I withdraw my concerns raised before.
Exposing the options to the outside still seems like a small layer violation, but it will allow us to quickly reach certain effects without further code changes.

**Comment by alikhajeh1** [comment]
I've seen https://github.com/heketi/heketi/issues/711 and just wondering how (or if) you guys see Heketi integrating into Openshift/K8 to allow users to define the volume options via labels on PVCs. I'm not sure if cluster admins would want users to edit all options, so maybe they can define a whitelist of options that can be changed by users.

Our use case is for ElasticSearch, which requires `cluster.consistent-metadata on` on a gluster volume. As it stands, we're asking users to add a label to their PVC at the time of creation, then have to watch for the labels and use `oc exec gluster_pod` to update that gluster volume option after it's been created.

**Comment by alikhajeh1** [comment]
hmm seems like cluster admins can define the volume options using StorageClasses and users just pick the class, right?
https://github.com/kubernetes/kubernetes/commit/ebf24c14a916adebc37023be69f112d2c97759a9

**Comment by humblec** [comment]
@alikhajeh1 Correct. More information is available here http://www.humblec.com/glusterfs-dynamic-provisioner-set-glusterfs-volume-options-via-storageclass-parameter/

**Comment by humblec** [comment]
Closing this issue as now heketi allows volume options in the create request.!
