### ISSUE TITLE
 Need a better error message when a cluster id with no bricks is provided

### ISSUE THREAD

**Issue by kramdoss** [heketi/heketi#712]
When a cluster is created manually without any nodes or bricks and when such a cluster id is defined as part of storage class, pvc creation fails with 'Error calling v.allocBricksInCluster: Id not found'. Looks like we just return the error received from the function. A better error message should be provided.

ProvisioningFailed	Failed to provision volume with StorageClass "voltypenegative": glusterfs: create volume err: error creating volume Error calling v.allocBricksInCluster: Id not found.

**Comment by MohamedAshiqrh** [comment]
@kramdoss This is error message fix. Thanks. @heketi/dev fyi

**Comment by raghavendra-talur** [comment]
How to reproduce:

Don't load a topology file. Just create a cluster and try creating a volume. The error should not be Id not found.

**Comment by nixpanic** [comment]
@kramdoss the current version (master branch) returns this when there is no topology loaded:

```
[root@localhost ~]# ./heketi-cli cluster create 
Cluster id: 3973d1fe77521a91b4e676531e4ec37f
[root@localhost ~]# ./heketi-cli volume create --size=2
Error: No space
```

The `Error calling v.allocBricksInCluster: Id not found.` does not seem to happen anymore. I think `no space` is an appropriate message. Can this be closed, or should we improve it further?

**Comment by phlogistonjohn** [comment]
I think that if a specific cluster is requested and it is empty we could easily give an even better error message like "cluster has no nodes".

If we wanted to, we could try to get fancier with the error messages when we probe multiple clusters and return something like:
```
Unable to create volume on any cluster:
Cluster 3973d1fe77521a91b4e676531e4ec37f: No space
Cluster 22e7753973d1fe77521a91b4e6744f4f: Cluster has no nodes
```

But that might be overkill for this issue. I don't think this would be difficult. Thoughts?
