### ISSUE TITLE
Determine brick sets during heketi startup instead of doing it while removing device

### ISSUE THREAD

**Issue by raghavendra-talur** [heketi/heketi#717]
Refer to Upgrade() function to get more details.

**Comment by phlogistonjohn** [comment]
@raghavendra-talur do you still think this is something that the system should do? I feel that the current approach is good enough. I'd rather not slow heketi startup by scanning lots of gluster volume status. The current approach is lazy and only incurs activity when that info is needed.

**Comment by phlogistonjohn** [comment]
Stale issue. Closing.
