### ISSUE TITLE
RFE - Manage External glusterfs cluster from heketi on Openshift

### ISSUE THREAD

**Issue by mjudeikis** [heketi/heketi#721]
As a possible use-case, I want to run my gluster outside Openshift and still use storageclasses via heketi.

I could install heketi on separate server externally, but current heketi implementation uses boltDB as a storage, this means - no resilience. 

I want to be able to generate:
heketi setup-openshift-heketi-storage and get my external cluster details, and redeploy this in OCP so it just managed those either via Services/endpoints OR directly to IP addresses outside my cluster. 

Current heketi assumes cluster is running in openshift when you try provision using client running in OCP and config/DB loaded from the external cluster. 

In the end this might not be valid implementation, as it requires sshd on the heketi image and ssh keys or other auth method to the gluster nodes.

Other option would be to use LibKV and move to use something like etcd, consul as database, so we could have external resilient heketi deployment. 
(didnt went through code yet, maybe its possible already) 

 
```
[kubeexec] ERROR 2017/03/19 17:45:03 /src/github.com/heketi/heketi/executors/kubeexec/kubeexec.go:272: User "system:serviceaccount:storage-project:default" cannot list pods in project "aplo"
[sshexec] ERROR 2017/03/19 17:45:03 /src/github.com/heketi/heketi/executors/sshexec/brick.go:152: Failed to get list of pods
[kubeexec] ERROR 2017/03/19 17:45:04 /src/github.com/heketi/heketi/executors/kubeexec/kubeexec.go:272: User "system:serviceaccount:storage-project:default" cannot list pods in project "aplo"
[sshexec] ERROR 2017/03/19 17:45:04 /src/github.com/heketi/heketi/executors/sshexec/brick.go:163: Failed to get list of pods
[kubeexec] ERROR 2017/03/19 17:45:04 /src/github.com/heketi/heketi/executors/kubeexec/kubeexec.go:272: User "system:serviceaccount:storage-project:default" cannot list pods in project "aplo"
[sshexec] ERROR 2017/03/19 17:45:04 /src/github.com/heketi/heketi/executors/sshexec/brick.go:163: Failed to get list of pods
[kubeexec] ERROR 2017/03/19 17:45:04 /src/github.com/heketi/heketi/executors/kubeexec/kubeexec.go:272: User "system:serviceaccount:storage-project:default" cannot list pods in project "aplo"
[sshexec] ERROR 2017/03/19 17:45:04 /src/github.com/heketi/heketi/executors/sshexec/brick.go:163: Failed to get list of pods
[asynchttp] INFO 2017/03/19 17:45:04 Completed job 39b6213b6e4e7c37cf5645f26077eab2 in 1.746329802s
[heketi] ERROR 2017/03/19 17:45:04 /src/github.com/heketi/heketi/apps/glusterfs/app_volume.go:148: Failed to create volume: Failed to get list of pods
```

**Comment by mangirdaz** [comment]
Something like this:
https://github.com/heketi/heketi/pull/726

**Comment by MohamedAshiqrh** [comment]
This will also help #691 . Nice work.

**Comment by obnoxxx** [comment]
With the HEKETI_EXECUTOR environment variable (set to ssh), you can tell a heketi running in a pod in openshift to manage a gluster that is residing outside of openshift. This was added as a mode of deployment to gk-deploy in https://github.com/gluster/gluster-kubernetes/pull/281 .

Closing this. Please reopen if there's more to it.
