### ISSUE TITLE
Unable to open database

### ISSUE THREAD

**Issue by madchap** [heketi/heketi#722]
Hi,

heketi v4, installed on centos/7 vagrant, from the tarball. First time trying it.

Doing a cluster list, output is it can't open database. Running strace, it doesn't seem to open the database file at all:

```
[vagrant@heketi ~]$ strace -e open heketi cluster list --config=/etc/heketi/heketi.json
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
open("/lib64/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 3
open("/lib64/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
open("/etc/nsswitch.conf", O_RDONLY|O_CLOEXEC) = 3
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
open("/lib64/libnss_files.so.2", O_RDONLY|O_CLOEXEC) = 3
open("/etc/passwd", O_RDONLY|O_CLOEXEC) = 3
Heketi v4.0.0
[heketi] INFO 2017/03/19 19:52:01 Loaded ssh executor
[heketi] WARNING 2017/03/19 19:52:04 Unable to open database.  Retrying using read only mode
^CProcess 13315 detached
[vagrant@heketi ~]$
```

My heketi database is located under /var/lib/heketi/heketi.db as per the "usual", and as specified in my json config file.

```
[...]
"_sshexec_comment": "SSH username and private key file information",
    "sshexec": {
      "keyfile": "/etc/heketi/heketi_key",
      "user": "heketi",
      "port": "22",
      "fstab": "/etc/fstab"
    },

"_db_comment": "Database file name",
    "db": "/var/lib/heketi/heketi.db",

[...]
```

Anything I may be doing wrong? Thanks.

**Comment by raghavendra-talur** [comment]
@madchap do you still see this error? Could you strace for creat calls too.
Also, attach Gluster logs from all the nodes, we would know if the creat/open calls reached gluster.

**Comment by madchap** [comment]
I am attaching the output of a full strace including children processes. FYI, heketi can create my gluster volumes just fine through kubernetes, just this list is causing problems -- which is not a blocker for me.

[strace.txt](https://github.com/heketi/heketi/files/907455/strace.txt)

**Comment by madchap** [comment]
Some additional info.

Selinux enforced, however, same behavior when set to permissive.

```
[root@heketi vagrant]# ls -lZ /var/lib/ |grep hek
drwxr-x---. heketi  heketi  unconfined_u:object_r:var_lib_t:s0 heketi
```

```
-bash-4.2$ ls -lZ /var/lib/heketi/heketi.db
-rw-------. heketi heketi system_u:object_r:var_lib_t:s0   /var/lib/heketi/heketi.db
```

**Comment by phlogistonjohn** [comment]
Last activity on this issue was over a year ago. Closing. Please reopen if additional discussion is needed.
