### ISSUE TITLE
Cannot add node, empty error message

### ISSUE THREAD

**Issue by cjyar** [heketi/heketi#727]
I have a Kubernetes cluster of 3 nodes, each of which is a member of a GlusterFS/heketi cluster. I added a new Kubernetes node, and I want to add it to GlusterFS also.

```
[root@heketi-2429414201-3m9nl /]# heketi-cli node add --zone 1 \
> --cluster <cluster_id> \
> --management-host-name <new_host_hostname> \
> --storage-host-name <new_host_ip>
Error:

```

Not only does the operation fail; but there's no useful diagnostic output to tell me what's wrong. This is what I see in the heketi log:

```
[negroni] Started POST /nodes
[negroni] Completed 0  in 219.876µs
```

**Environment:**
- Kubernetes 1.5.2+coreos.0
- GlusterFS 3.8.9
- Heketi v4.0.0-46-g8e58761
- Using https://github.com/gluster/gluster-kubernetes

**Comment by MohamedAshiqrh** [comment]
@cjyar can you check if the other operations are happening in heketi. like get node,device,cluster list/info. If all worked can you give a try again. I am not sure what has happened. Can you give a try again and share the complete log of heketi and also your daemonset details?

**Comment by cjyar** [comment]
@MohamedAshiqrh Thank you for your reply. That problem was almost two months ago; my system looks very different now. I have different versions of Kubernetes and GlusterFS, and it's configured differently. In the new config, it's working. I don't remember all of the things I changed, so I don't know which change might have fixed it.
