### ISSUE TITLE
empty database secret on fresh install following kubernetes manual

### ISSUE THREAD

**Issue by lwolf** [heketi/heketi#728]
I followed [kubernetes integration manual](https://github.com/heketi/heketi/wiki/Kubernetes-Integration) on the latest version.

Everything works fine until the last step when we are deleting deploy-stuff and creating the real deployment. 
Before this step, if I run `heketi-cli topology info` I can see all information.
After this step, it returns nothing.

I tracked down the problem to the empty `heketi.db` in `heketi-db-backup` secret.
If I edit secret manually and set heketi.db value from generated `heketi-storage.json` everything works.

**Comment by MohamedAshiqrh** [comment]
if you did 
# kubectl create -f heketi-storage.json

then you found an empty secret then it is a kubernetes bug. If you missed the above step, Heketi does create an empty secret in some cases which is expected as there is no secret or gluster volume to hold db.

**Comment by phlogistonjohn** [comment]
Last activity on this issue was over a year ago. Closing. Please reopen if additional discussion is needed.
