### ISSUE TITLE
Unable to open database permission denied

### ISSUE THREAD

**Issue by jamstar** [heketi/heketi#731]
im having an issue similar to #722 .  I also am running in centos7 vagrant. were both running in vagrant with centos7.  I am using the gluster/kubernetes install script(gk-deploy).  when it is creating the heketi pod, its encountering  an issue with not able to open the database.  no idea what to fix since its just using the container.  i included the describe and logs from the pod. the image im using is heketi:dev but  i will try using 4.0 latter today.    Any help is appreciated since im not able to move forward.

## gk-deploy
Checking status of pods matching 'job-name=heketi-storage-copy-job':
Timed out waiting for pods matching 'job-name=heketi-storage-copy-job'.
service "deploy-heketi" deleted
job "heketi-storage-copy-job" deleted
deployment "deploy-heketi" deleted
secret "heketi-storage-secret" deleted
service "heketi" created
deployment "heketi" created
Waiting for heketi pod to start ... 
Checking status of pods matching 'glusterfs=heketi-pod':
deploy-heketi-966143893-6dsjz   1/1       Terminating   0         2m
heketi-1348222432-5nrv6   0/1       CrashLoopBackOff   5         5m
Timed out waiting for pods matching 'glusterfs=heketi-pod'.
OK

## Pod Describe
[vagrant@kuberHAMaster-1 kube-templates]$ kubectl describe pod heketi-1348222432-dg0gw
Name:		heketi-1348222432-dg0gw
Namespace:	default
Node:		192.168.61.91/192.168.61.91
Start Time:	Thu, 30 Mar 2017 14:44:52 +0000
Labels:		glusterfs=heketi-pod
		pod-template-hash=1348222432
Status:		Running
IP:		10.10.45.4
Controllers:	ReplicaSet/heketi-1348222432
Containers:
  heketi:
    Container ID:	docker://f5975611f249830d1334be8735a38973aa328b90eaf82621102537a8ff248a7a
    Image:		heketi/heketi:dev
    Image ID:		docker-pullable://docker.io/heketi/heketi@sha256:5e912c022ef31070fe1127fcf9b5285154426d7d510dbfb0639b40016f8454b9
    Port:		8080/TCP
    State:		Waiting
      Reason:		CrashLoopBackOff
    Last State:		Terminated
      Reason:		Error
      Exit Code:	1
      Started:		Thu, 30 Mar 2017 14:45:44 +0000
      Finished:		Thu, 30 Mar 2017 14:45:44 +0000
    Ready:		False
    Restart Count:	3
    Liveness:		http-get http://:8080/hello delay=30s timeout=3s period=10s #success=1 #failure=3
    Readiness:		http-get http://:8080/hello delay=3s timeout=3s period=10s #success=1 #failure=3
    Volume Mounts:
      /var/lib/heketi from db (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from heketi-service-account-token-zxl49 (ro)
    Environment Variables:
      HEKETI_EXECUTOR:			kubernetes
      HEKETI_FSTAB:			/var/lib/heketi/fstab
      HEKETI_SNAPSHOT_LIMIT:		14
      HEKETI_KUBE_GLUSTER_DAEMONSET:	y
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	False 
  PodScheduled 	True 
Volumes:
  db:
    Type:		Glusterfs (a Glusterfs mount on the host that shares a pod's lifetime)
    EndpointsName:	heketi-storage-endpoints
    Path:		heketidbstorage
    ReadOnly:		false
  heketi-service-account-token-zxl49:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	heketi-service-account-token-zxl49
QoS Class:	BestEffort
Tolerations:	<none>
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath		Type		Reason		Message
  ---------	--------	-----	----			-------------		--------	------		-------
  1m		1m		1	{default-scheduler }				Normal		Scheduled	Successfully assigned heketi-1348222432-dg0gw to 192.168.61.91
  1m		1m		1	{kubelet 192.168.61.91}	spec.containers{heketi}	Normal		Created		Created container with docker id f4e46ac47f67; Security:[seccomp=unconfined]
  1m		1m		1	{kubelet 192.168.61.91}	spec.containers{heketi}	Normal		Started		Started container with docker id f4e46ac47f67
  1m		1m		1	{kubelet 192.168.61.91}	spec.containers{heketi}	Normal		Started		Started container with docker id e1746aaa1e51
  1m		1m		1	{kubelet 192.168.61.91}	spec.containers{heketi}	Normal		Created		Created container with docker id e1746aaa1e51; Security:[seccomp=unconfined]
  1m		1m		2	{kubelet 192.168.61.91}				Warning		FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "heketi" with CrashLoopBackOff: "Back-off 10s restarting failed container=heketi pod=heketi-1348222432-dg0gw_default(6eb1275f-1557-11e7-a1e0-5254001fdbb7)"

  52s	52s	1	{kubelet 192.168.61.91}	spec.containers{heketi}	Normal	Created		Created container with docker id ee268f2b80f8; Security:[seccomp=unconfined]
  52s	52s	1	{kubelet 192.168.61.91}	spec.containers{heketi}	Normal	Started		Started container with docker id ee268f2b80f8
  51s	35s	3	{kubelet 192.168.61.91}				Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "heketi" with CrashLoopBackOff: "Back-off 20s restarting failed container=heketi pod=heketi-1348222432-dg0gw_default(6eb1275f-1557-11e7-a1e0-5254001fdbb7)"

  19s	19s	1	{kubelet 192.168.61.91}	spec.containers{heketi}	Normal	Started		Started container with docker id f5975611f249
  1m	19s	4	{kubelet 192.168.61.91}	spec.containers{heketi}	Normal	Pulled		Container image "heketi/heketi:dev" already present on machine
  19s	19s	1	{kubelet 192.168.61.91}	spec.containers{heketi}	Normal	Created		Created container with docker id f5975611f249; Security:[seccomp=unconfined]
  1m	11s	7	{kubelet 192.168.61.91}	spec.containers{heketi}	Warning	BackOff		Back-off restarting failed docker container
  18s	11s	2	{kubelet 192.168.61.91}				Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "heketi" with CrashLoopBackOff: "Back-off 40s restarting failed container=heketi pod=heketi-1348222432-dg0gw_default(6eb1275f-1557-11e7-a1e0-5254001fdbb7)"

## Pod Log
kubectl logs heketi-1348222432-dg0gw
Heketi v4.0.0-46-g8e58761
[heketi] INFO 2017/03/30 14:45:44 Loaded kubernetes executor
[heketi] WARNING 2017/03/30 14:45:44 Unable to open database.  Retrying using read only mode
[heketi] ERROR 2017/03/30 14:45:44 /src/github.com/heketi/heketi/apps/glusterfs/app.go:105: Unable to open database: open /var/lib/heketi/heketi.db: permission denied
ERROR: Unable to start application

**Comment by mangirdaz** [comment]
Try scale down, wait some time and scale up. because current version uses BoltDB (file based DB) you might still have filelock for writes because k8s/ocp still keeping mounts from previous deployment.

**Comment by jamstar** [comment]
i scaled it down then waited an hour and the scaled it back up. same result.  any other suggestions i should look at?  Also i tried using 4.0 and got the same result.

**Comment by jamstar** [comment]
so changing the mount worked since when its launching in the container, it creating a new location in the container. I pulled a new container to a different machine and  I see the existing one (/var/lib/heketi/heketi.db)already exists in the container. the question i have is why is it there already?  should it be there already?

**Comment by raghavendra-talur** [comment]
@jamstar We would need more info to debug this. Please attach gluster logs(/var/log/glusterfs) from all three nodes.

**Comment by jamstar** [comment]
ill attach them hopefully latter this week. since i currently have it working currently, i need to finish up my gluster install and config before i break it again.

so looking in  /var/log/glusterfs, i see a number of different files.  i see a etc-glusterfs-glusterd.vol.log and a glustershd.log which do you need?

**Comment by jamstar** [comment]
after further understanding of how gluster and k8s play together, i don think this is an heketi issue specifically.  im closing this for now. i will reopen in the future if needed.
