### ISSUE TITLE
Heketi support for security context to ensure for correct permissions on the volume?

### ISSUE THREAD

**Issue by vasu1124** [heketi/heketi#732]
For a K8s cluster with v1.5.4, I set up gluster + heketi and tried to deploy the incubator/zookeeper chart. The dynamic storage provisioning worked as designed, but I ran into https://github.com/kubernetes/charts/issues/869.

The pod securityContext requires that the volume shall be mounted with proper permissions for that user/group:
```
securityContext:
        runAsUser: 1000
        fsGroup: 1000
```
Seems that the gluster/heketi provisioner does not adhere to this part of the contract.

**Comment by MohamedAshiqrh** [comment]
@humblec Can you take a look?

**Comment by bxrbxr** [comment]
+1 ... I am running in to a similar issue with deploying postgres using dynamic storage.

**Comment by humblec** [comment]
@vasu1124 @bxrbxr  Is there any specifc importance for this userID ie `1000` ? Can you use `gidMin` and `gidMax` values in Storage class and create a claim?. This ensures that you got a `gid` set on the volume. Then you can use it in supplemental group in pod spec.

**Comment by bxrbxr** [comment]
Thanks.  Here is bit more of the detailed context.

When the postgres container starts it tries to create some files and fails
>> 2017-05-22T19:10:26.642131246Z + mkdir -p /pgdata/pgset-1
>> 2017-05-22T19:10:26.650497948Z mkdir: cannot create directory '/pgdata/pgset-1': Permission denied

The permissions of the mounted volume (from the postgres container) is
>> drwxr-xr-x   3 root     root        24 May 22 19:10 pgdata

mounted on
>>10.xx.xx.xx:vol_c2ed1513c4afb6059a1289d45e14667f   1045376    33408   1011968   4% /pgdata

I tried setting the gidMin & gidMax and the provisioning of the PV failed.

I tried setting supplementalGroups as follows:

"securityContext": {
                "supplementalGroups": [26]
         },
where 26 is the uid:gid of  postgres. 

Same error.

The storage class works fine in other circumstances

**Comment by phlogistonjohn** [comment]
The last activity on this issue was over a year ago. Closing. Please reopen if additional discussion is needed.
