### ISSUE TITLE
heketi cannot recover from nodes which are crashed

### ISSUE THREAD

**Issue by dmesser** [heketi/heketi#734]
When dealing with a situation where a node of a heketi cluster failed and is not recoverable heketi cannot remove/delete that devices in order to recover on another available brick. This is because heketi needs the node to be reachable in order to delete devices, which is related to #733 .

Furthermore there should be a logic implemented in remove device that upon supplying a switch like --delete-volumes removes all devices on the node in question first in order to replace failed bricks after the node has been disabled. A --force switch would propagate down to the device remove command as described in #733 in order to handle situations where the node is not online anymore.

**Comment by MohamedAshiqrh** [comment]
https://github.com/heketi/heketi/pull/735 

This will fix the issue.

**Comment by MohamedAshiqrh** [comment]
This is fixed we can close this. @lpabon @obnoxxx

**Comment by obnoxxx** [comment]
fixed by PR #735
