### ISSUE TITLE
How can I specify parameter -replica=2 (or 1) to kubernetes PVC

### ISSUE THREAD

**Issue by andersla** [heketi/heketi#738]
On the command line this seem to be the syntax for specifying replication factor: ```heketi-cli volume create -name=testvol -size=40 -durability="replicate" -replica=2```
How can this be achieved when running heketi in kubernetes?

**Comment by harryge00** [comment]
Duplicate as https://github.com/heketi/heketi/issues/739

**Comment by MohamedAshiqrh** [comment]
https://github.com/heketi/heketi/issues/739#issuecomment-293309244 answers the issue. We can close this issue. @lpabon @obnoxxx @andersla If there is nothing else.

**Comment by humblec** [comment]
@lpabon this issue can be closed.
