### ISSUE TITLE
How to create the type of Volume I want

### ISSUE THREAD

**Issue by zhaorendong** [heketi/heketi#739]
When I create PVC,Kubernetes will be triggered by resturl in Heketi StorageClass.
Then Heketi began to create PVC application disk space, from the creation of PV, create VG, create LV, mkfs to create the file system, and then to create a glusterfs volume。But the type of volume is not I want,How to create the type of Volume I want when I create PVC?

**Comment by harryge00** [comment]
https://github.com/kubernetes/kubernetes/blob/7028abc5fcb41e7975b98f0900d5765afc48f464/examples/persistent-volume-provisioning/README.md

**Comment by andersla** [comment]
That's super!
I guess kubernetes docs are outdated at: https://kubernetes.io/docs/concepts/storage/persistent-volumes/

**Comment by harryge00** [comment]
@andersla  Yes. You are right. I have just made a pull request:  https://github.com/kubernetes/kubernetes.github.io/pull/3324

**Comment by zhaorendong** [comment]
Thanks！

**Comment by MohamedAshiqrh** [comment]
@harryge00 Thanks for the information.

**Comment by humblec** [comment]
@lpabon This issue can be closed.
