### ISSUE TITLE
Single node with 3 drives

### ISSUE THREAD

**Issue by kristiandrucker** [heketi/heketi#742]
Hi, I own a single server that has 3 drives. Could I run heketi with glusterfs on kubernetes on that single server?

**Comment by MohamedAshiqrh** [comment]
@kristiandrucker Technically you could only problem is that the heketi creates a replica three glusterfs volume to save its own db. This will fail. you can change your heketi dc file to store the heketidb on the host as you have single host and use the same. Remember if you have more than one node and heketi migrates to some other place the haketidb will be not present on that host so heketi will not start with the content it supposed to start.

**Comment by lpabon** [comment]
@kristiandrucker Sorry, no. GlusterFS does not support that unless you _force_ it to do it.
