### ISSUE TITLE
Minimum brick size limit reached.  Out of space.

### ISSUE THREAD

**Issue by zhaorendong** [heketi/heketi#743]
When I create StorageClass with volumetype: "disperse:4:2",then I create a PVC,the heketi logs : 
[negroni] Completed 202 Accepted in 416.044μs
[asynchttp] INFO 2017/04/14 03:59:22 Started job 978a6b559b415153d386e4d8380ddf99
[heketi] INFO 2017/04/14 03:59:22 Creating volume 5fdecbf43cf001f018a1884a5de2ae46
[negroni] Started GET /queue/978a6b559b415153d386e4d8380ddf99
[heketi] INFO 2017/04/14 03:59:22 brick_num: 0
[negroni] Completed 200 OK in 55.278μs
[heketi] ERROR 2017/04/14 03:59:22 /src/github.com/heketi/heketi/apps/glusterfs/volume_entry_allocate.go:38: Minimum brick size limit reached.  Out of space.
[asynchttp] INFO 2017/04/14 03:59:22 Completed job 978a6b559b415153d386e4d8380ddf99 in 6.213807ms
[heketi] ERROR 2017/04/14 03:59:22 /src/github.com/heketi/heketi/apps/glusterfs/app_volume.go:148: Failed to create volume: No space
[negroni] Started GET /queue/978a6b559b415153d386e4d8380ddf99
[negroni] Completed 500 Internal Server Error in 90.139μs

My StorageClass yaml is : 
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gluster-heketi
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://193.168.1.2:8080"
  restauthenabled: "false"
  volumetype: "disperse:4:2"

My PersistentVolumeClaim yaml is
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-gluster-heketi-1
  namespace: base2
spec:
  storageClassName: gluster-heketi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi

Why?

**Comment by MohamedAshiqrh** [comment]
@zhaorendong can you share the topology output? then we can share more details on what you are facing.

**Comment by obnoxxx** [comment]
@zhaorendong Heketi has a certain minimum brick size configured. The lower limit (and default value) for this is currently 1GB.

It seems heketi had to split down to brick sizes smaller than 1GB.

What is the size of your disk devices?

**Comment by zhaorendong** [comment]
There are 3 nodes and 6 disk devices per node, and the size of disk device is 837Gi.

**Comment by phlogistonjohn** [comment]
The last activity on this issue was over a year ago. Closing. Please reopen if additional discussion is needed.
