### ISSUE TITLE
Error: No space with heketi-3.0.0-1.el7.x86_64 in Centos 7 

### ISSUE THREAD

**Issue by SaravanaPunith** [heketi/heketi#746]
I was facing No space error while using heketi as part of setting up CNS environment. 

Refer here for details:
https://github.com/gluster/gluster-kubernetes/issues/253

It is better if heketi is updated with these fixes..means to have updated rpms in Centos environment.

**Comment by MohamedAshiqrh** [comment]
@lpabon @obnoxxx we need to build new rpm for centos. Do we have a document that I can follow If I want to build?

**Comment by lpabon** [comment]
@MohamedAshiqrh Definitely talk to @jarrpa and @nixpanic. They have the information.

**Comment by jarrpa** [comment]
Since this is a request to update the CentOS repo, I suggest we close this Issue and follow the conversation in #750.
