### ISSUE TITLE
the readme.md in extras/kubernetes/ is  not correspond to real

### ISSUE THREAD

**Issue by 4admin2root** [heketi/heketi#748]
for example 
there is no file named gluster-daemonset.json
and where is deploy-heketi-deployment.json

**Comment by MohamedAshiqrh** [comment]
@4admin2root hey we have a [repo](https://github.com/gluster/gluster-kubernetes) which is more preferable for the kubernetes and openshift deployments as we have mentioned in the heketi [wiki](https://github.com/heketi/heketi/wiki/Kubernetes-Integration#overview).

**Comment by lpabon** [comment]
Duplicate of #755
