### ISSUE TITLE
Kubernetes deployment failing because of inexistent serviceAccountName

### ISSUE THREAD

**Issue by juanwolf** [heketi/heketi#749]
Hi,

I was experiencing an issue installing heketi on top of kubernetes from the instructions you provided.

After the `kubectl create -f heketi-deployment.json`, the deployment stayed unavailable. 
I've got it working running `journalctl -xe` : 

```
Apr 21 14:09:45 kubernetes00 kube-controller-manager[10121]: E0421 14:09:45.516061   10121 replica_set.go:504] unable to create pods: pods "heketi-80199834-" is forbidden: service account default/heketi-service-account was not found, retry after the service account is created
```
And set up the `serviceAccountName` value in the `heketi-deployment.json` to `default`. 

I was just wondering if I missed something in the installation or if the "Service Account" is missing into the heketi-deployment.json file? If so, I don't mind to create a PR.

**Comment by MohamedAshiqrh** [comment]
@juanwolf Can you follow document in https://github.com/gluster/gluster-kubernetes ? We have made a tool for deployment and setting up is really simple with it. I am not sure what the issue is.

**Comment by juanwolf** [comment]
@MohamedAshiqrh Thanks for the reply! Using this template: https://github.com/gluster/gluster-kubernetes/blob/master/deploy/kube-templates/heketi-deployment.yaml the deployment failed because of the inexistant `heketi-service-account` service account. I was just wondering if I missed anything. I will close the issue anyway as it's was just a question rather than a proper issue.
