### ISSUE TITLE
Service account and clusterrolebinding missing from docs

### ISSUE THREAD

**Issue by rafagsiqueira** [heketi/heketi#755]
I have just spend some time figuring out that in order for things to work, that these two steps are needed for things to work:

`kubectl -n <namespace> create -f https://raw.githubusercontent.com/gluster/gluster-kubernetes/master/deploy/kube-templates/heketi-service-account.yaml`
`kubectl create clusterrolebinding heketi-sa-view --clusterrole=edit --serviceaccount=<namespace>:heketi-service-account`

Perhaps it helps someone.

**Comment by MohamedAshiqrh** [comment]
Hi @rafagsiqueira, We have [gk-deploy](https://github.com/gluster/gluster-kubernetes/blob/master/docs/setup-guide.md) for all the deployment requirement which covers this too. Thanks for pointing this out. Will add this step in heketi wiki.

**Comment by lpabon** [comment]
@MohamedAshiqrh Do you mind adding this or cleaning it up for Release 5?

**Comment by lpabon** [comment]
See https://github.com/heketi/heketi/pull/762
