### ISSUE TITLE
Device size not updated if disk is expanded

### ISSUE THREAD

**Issue by ae-dg** [heketi/heketi#756]
When using VMs for the gluster nodes drive sizes can be changed. For example in RHEV it is possible to expand the drive without even restarting the virtual machine.

After increasing the size of the virtual disk and running pvresize on the virtual disk the volume group shows an increase in the free space.  However heketi doesn't notice and still shows the original size of the drives when requesting the device info. As a result it is not possible to create a volume that is larger than what heketi thinks is the size of the device even if the device actually has enough space.

Can a "device rescan" API call be created to get heketi to update it's internal information to match the actual disk size?

**Comment by lpabon** [comment]
@ae-dg Wow, that would be cool, but that doesn't happen normally. Instead new disks, nodes, or clusters are normally added to Heketi to increase capacity.

If you feel you would like to add this support, PRs are welcomed :-D

**Comment by hakanisaksson** [comment]
This feature is very much need for production clusters.
