### ISSUE TITLE
Re-create deleted endpoints/services

### ISSUE THREAD

**Issue by cjyar** [heketi/heketi#757]
Several times now, I've had my users delete the `glusterfs-dynamic-xxx` endpoint and/or service that Kubernetes depends on in order to mount a GlusterFS volume. The next time their pod restarts, it's unable to mount its PVC.

In keeping with general Kubernetes practices, it would good for heketi to re-create the service and endpoint if they get deleted.

**Comment by lpabon** [comment]
@humblec What do you think is happening here?

cc @heketi/dev

**Comment by humblec** [comment]
@cjyar those endpoints or services belong to the PVCs, so should not delete as long as the PVC is existing. First of all, I dont know why the users are deleting those endpoints and services?. Do they have ( or need) any special permissions of cluster admin to delete these endpoints/services ?  If yes, you could remove those permissions from them.  Even if its statically provisioned PVs ( without heketi) , if the endpont/service is deleted, we need to recreate it for successful glusterfs mount.  Keeping track of all the volumes from heketi and recreating these ep/svcs will be very difficult/not possible as it requires extra monitoring from different layers.

**Comment by cjyar** [comment]
@humblec The users have access to create and delete services in their applications' respective namespaces. They need that access in order to deploy applications, because the applications use services to communicate. As to why they deleted them, I think sometimes people make mistakes.

I'm sorry to hear that it's impossible to monitor and re-create objects in Kubernetes.

**Comment by humblec** [comment]
@cjyar here is the good news :) . I did quite amount of refactoring of code and made it possible from the provisioner. The patch is merged in upstream and from 1.7 onwards, it will reattempt and create endpoint if it got wiped in between !

**Comment by MohamedAshiqrh** [comment]
@humblec awesome. Thanks this indeed is a good news.

**Comment by cjyar** [comment]
@humblec Thank you! For some reason, my users keep making this mistake. It'll save them a lot of grief.

**Comment by humblec** [comment]
@lpabon this issue can be closed.

**Comment by lpabon** [comment]
Thanks @humblec
