### ISSUE TITLE
The Heketi API has an error.

### ISSUE THREAD

**Issue by zhaorendong** [heketi/heketi#770]
When I use the  Volume Information of Heketi API  (### Volume Information * **Method:** _GET_ * **Endpoint**:`/volume/{id}` * **Response HTTP Status Code**: 200 ), it response Invalid path or request.But I had a try "/volumes/{id}" that right.For example:

http://192.168.18.3:1144/volume/daafd4d4d37ed5f5596c313343042887"

Invalid path or request

http://192.168.18.3:1144/volumes/daafd4d4d37ed5f5596c313343042887

{"size":1,"name":"vol_daafd4d4d37ed5f5596c313343042887","durability":{"type":"replicate","replicate":{"replica":3},"disperse":{}},"snapshot":{"enable":false,"factor":1},"id":"daafd4d4d37ed5f5596c313343042887","cluster":"c71adcbaf202425a35a4c8f0cafc69cd","mount":{"glusterfs":{"hosts":["192.168.18.3","192.168.18.4","192.168.18.5"],"device":"192.168.18.3:vol_daafd4d4d37ed5f5596c313343042887","options":{"backup-volfile-servers":"192.168.18.4,192.168.18.5"}}},"bricks":[{"id":"703c37d5bd5be227b37f63c31706cd85","path":"/var/lib/heketi/mounts/vg_ac732d06feab5f76642f9dcb69592a0b/brick_703c37d5bd5be227b37f63c31706cd85/brick","device":"ac732d06feab5f76642f9dcb69592a0b","node":"56293409a0d1afc2544aba4c03c917ef","size":1048576},{"id":"bcb6ef56a820361b51d67de39f852230","path":"/var/lib/heketi/mounts/vg_42e77943cd6ef30a8ac0befe71bd9842/brick_bcb6ef56a820361b51d67de39f852230/brick","device":"42e77943cd6ef30a8ac0befe71bd9842","node":"84db505984f37baaa31b2a75003fce4a","size":1048576},{"id":"c8350fefba643f9f036f63825852fe3a","path":"/var/lib/heketi/mounts/vg_d82b9539301e2b235030acc394258e9b/brick_c8350fefba643f9f036f63825852fe3a/brick","device":"d82b9539301e2b235030acc394258e9b","node":"972ed2c2cbd95b8171d3d134f4cbc225","size":1048576}]}

**Comment by MohamedAshiqrh** [comment]
Thanks a lot fixed it. 

https://github.com/heketi/heketi/wiki/API/4024612e8b1c39b2dea85f4ce85bb5133d8c6348

**Comment by MohamedAshiqrh** [comment]
@lpabon @obnoxxx We can close this fixed the doc.
