### ISSUE TITLE
[IMP] Don't use docker image heketi/gluster

### ISSUE THREAD

**Issue by adarshaj** [heketi/heketi#773]
The docker build for this image has been failing for over 11 months on the docker hub, hence the fixes in the current master is not really available on the docker image. The latest correct docker image is at `gluster/gluster-centos:latest` as noted in https://github.com/gluster/gluster-kubernetes/blob/master/deploy/kube-templates/glusterfs-daemonset.yaml

**Comment by lpabon** [comment]
@adarshaj Do you mind sending a PR to fix that?

**Comment by lpabon** [comment]
cc @jarrpa

**Comment by obnoxxx** [comment]
The template has been fixed meanwhile and the docker image removed. closing...
