### ISSUE TITLE
usr sbin thin_check no such file or directory

### ISSUE THREAD

**Issue by Hcindy** [heketi/heketi#775]
ubuntu 16.04
apt-get install lvm2
heketi-v4.0.0.linux.amd64.tar.gz  standalone installation
When I create a volume failed, the log showing "/usr/sbin/thin_check: no such file or directory"
I checked the directory of "/usr/sbin", there isn't "thin_check"
I haven't any knowledge about lvm
How can I solve the problem? thanks a lot

**Comment by rajasaur** [comment]
Had the same problem, it seems ubuntu only recommends thin-provisioning-tools, and not require it.

Installing thin-provisioning-tools on all the nodes solves this problem for me.

**Comment by lpabon** [comment]
@rajasaur Thanks! @Hcindy please let me know if this solves your issue.

**Comment by lpabon** [comment]
Closing the issue, but please feel free to re-open if it doesn't fix your issue.

**Comment by Hcindy** [comment]
@rajasaur Thanks!
@lpabon I solves some problems:
vmware10 install ubuntu 16.04, add 2 disk, apt-get install thin-provisioning-tools lvm2 xfsprogs
heketi-v4.0.0.linux.amd64.tar.gz standalone installation
Then using heketi create clusters nodes and devices. When I create volume, the console showing something about wipe offset 1080 y/n and choosing n default. I must execute pvcreate /dev/sdb /dev/sdc and choose y by myself. Now the volume can be created.
And I find heketi-cli can't let replicate volume: X in one node and X disk even if I add "force" (API no param about force)
