### ISSUE TITLE
Allow for smaller size BrickMinSize

### ISSUE THREAD

**Issue by alfredo-quiroga** [heketi/heketi#782]
In apps/glusterfs/app_config.go, allow for a smaller minimum size. Either a new variable such as:

BrickMinSizeInMb

or 

Allow for a ```float``` instead of ```int```

```
type GlusterFSConfig struct {
        DBfile     string              `json:"db"`
        Executor   string              `json:"executor"`
        Allocator  string              `json:"allocator"`
        SshConfig  sshexec.SshConfig   `json:"sshexec"`
        KubeConfig kubeexec.KubeConfig `json:"kubeexec"`
        Loglevel   string              `json:"loglevel"`

        // advanced settings
        BrickMaxSize int `json:"brick_max_size_gb"`
        BrickMinSize int `json:"brick_min_size_gb"`
        BrickMaxNum  int `json:"max_bricks_per_volume"`
}
```

**Comment by lpabon** [comment]
Hi @alfredo-quiroga , is there a reason for this? We like to keep things as simple as possible for the average use case. Is creating volumes less than 1GB really necessary?

**Comment by alfredo-quiroga** [comment]
Hi @lpabon appreciate the response. 

Yes, We have customers asking us for smaller sizes.

Thank you in advance.

Alfredo

**Comment by lpabon** [comment]
@alfredo-quiroga There is a work to have "block" on a gluster for Kubernetes. See: https://github.com/gluster/gluster-kubernetes/pull/268 . I think this may help instead.

**Comment by obnoxxx** [comment]
@alfredo-quiroga Thanks for the request. We are in fact planning to allow for smaller brick, and volume sizes in heketi. The GB unit is only used on the outer layer (cli/api). Internally, all sizes are converted to KB. Several people have requested support for smaller sizes. While this seems weird at disks in the terabyte size, it becomes much more plausible when you're using e.g. an all-flash SAN array as backend storage, and wasting > 90% of your storage is just not acceptable.

**Comment by alfredo-quiroga** [comment]
Thank you, appreciate it.

**Comment by SaravanaStorageNetwork** [comment]
I will look into this

**Comment by phlogistonjohn** [comment]
Closing this in favor of #1260
