### ISSUE TITLE
Error:Unable to find a GLusterFS pod on host 192.168.175.129 with a label key glusterfs-node

### ISSUE THREAD

**Issue by zhaorendong** [heketi/heketi#786]
When I add the secend Node by "heketi-cli -s http://localhost:8080 node add --zone=1 --cluster=XXXXX --management-host-name=192.168.175.129 --storage-host-name=192.168.175.129",the Heketi response "Error:Unable to find a GLusterFS pod on host 192.168.175.129 with a label key glusterfs-node". Why?

**Comment by lpabon** [comment]
The management host name _must_ be the kubernetes node name, and the storage-host-name must be the IP of that node. See: https://github.com/gluster/gluster-kubernetes/blob/master/docs/setup-guide.md#1-create-a-topology-file

**Comment by lpabon** [comment]
I agree that the documentation should be changed :)
