### ISSUE TITLE
how to use pprof to profile heketi binaries 

### ISSUE THREAD

**Issue by ekuric** [heketi/heketi#799]
Are there instructions how to profile heketi binaries with pprof? As far as I can see in heketi code pprof is not included

**Comment by nixpanic** [comment]
@ekuric, could you check the posted patch and let me know if that is what you are expecting?

**Comment by phlogistonjohn** [comment]
@nixpanic is this something you're still interested in?  If so, how large a task do you think it would be to bring to completion?

**Comment by phlogistonjohn** [comment]
Ideally, we'd have some simple test case to verify that it is functioning as designed. I can work with you to get something under the functional tests dir for this purpose.

**Comment by nixpanic** [comment]
@ekuric I have rebased the change and triggered a build of the container. You can find it in my [personal Quay repository](https://quay.io/repository/nixpanic/heketi?tab=builds) with tag `:wip_pprof`.

```
docker pull quay.io/nixpanic/heketi:wip_pprof
```

Care to test its functionality?
