### ISSUE TITLE
Heketi/Gluster on openshift. Volume create fails with unhelpful error message...

### ISSUE THREAD

**Issue by kristvanbesien** [heketi/heketi#800]
I am stepping through the manual steps for setting up a "Container Native Storage" gluster cluster on OCP 3.5. (This to figure out why cns-deploy doesn't work...)

Creating the gluster and heketi pods works. And loading the topology afterwards is successfull:

```
$ heketi-cli topology load --json=topology.json
	Found node storage-1.lab on cluster 396457df6501cb112d11dc0ab204722e
		Adding device /dev/vdb ... OK
		Adding device /dev/vdc ... OK
	Found node storage-2.lab on cluster 396457df6501cb112d11dc0ab204722e
		Adding device /dev/vdb ... OK
		Adding device /dev/vdc ... OK
	Found node storage-3.lab on cluster 396457df6501cb112d11dc0ab204722e
		Adding device /dev/vdb ... OK
		Adding device /dev/vdc ... OK
```

I checked inside the pods, and the pvs and vgs have been created. 

Then just to test, I tried to create a volume:

```
$ heketi-cli volume create --size=10
Error: Unable to execute command on glusterfs-8198p:
```

And this is where I am stuck. I get an error that says that heketi was unable to execute a command. Now, since the topology load worked, I asume that heketi can execute command on the nodes, but that in this case the command threw an error. However, it is not telling me which command threw an error, or what the error was.

So I would expect in such a case to at least have a more helpfull error message.

What can I do to debug this?

**Comment by lpabon** [comment]
@kristvanbesien  Is RBAC on? The Heketi pod may not have permission to execute the command. Would you mind also attaching the logs from the heketi pod?

**Comment by raghavendra-talur** [comment]
@kristvanbesien also, this error appears if the Gluster service is down for some reason. Is gluster pod up and does it Gluster running?

**Comment by kristvanbesien** [comment]
I found out that the manual (on the RH site) omitted an important command that you need to do. (has been corrected now it appears. 

oc adm policy add-scc-to-user privileged -z heketi-service-account
oc policy add-role-to-user edit -z heketi-service-account

**Comment by obnoxxx** [comment]
@kristvanbesien thanks for your feed-back! Does the last comment mean that it's working for you now?
Can we close the issue?

**Comment by kristvanbesien** [comment]
It's working now. You can close.

**Comment by obnoxxx** [comment]
thanks for confirming, @kristvanbesien
