### ISSUE TITLE
Unable to open database.  Retrying using read only mode

### ISSUE THREAD

**Issue by john-deng** [heketi/heketi#804]
@lpabon I deployed heketi on openshift, it works for several weeks, but it unable to  open database now, how could I solve this issue? where do I start to find the root cause? any advice?

Here is the log,
```
Heketi v4.0.0-74-g0c21b4d
--
  | [heketi] INFO 2017/07/11 09:51:26 Loaded kubernetes executor
  | [heketi] WARNING 2017/07/11 09:51:29 Unable to open database.  Retrying using read only mode
  | [heketi] INFO 2017/07/11 09:51:29 Loaded simple allocator
  | [heketi] INFO 2017/07/11 09:51:29 GlusterFS Application Loaded
  | Authorization loaded
  | Listening on port 8080
```

**Comment by lpabon** [comment]
@john-deng Sounds like the volume where the database is saved is running with only one replica out of three. Check the gluster volume.

**Comment by john-deng** [comment]
@lpabon Thank you for the quick reply! just found the solution from [here](https://github.com/gluster/gluster-kubernetes/issues/257) by @saidimu commented on Jun 2, this issue appeared from time to time, do you have any idea to solve it permanently?

**Comment by lpabon** [comment]
@john-deng I think backing up to a secret will solve this issue. I will take a note to add documentation on how to do this. Set the environment variable HEKETI_BACKUP_DB_TO_KUBE_SECRET to "y" and make sure you are running the latest dev build.

**Comment by john-deng** [comment]
@lpabon heketi become ready only again after I added HEKETI_BACKUP_DB_TO_KUBE_SECRET to "y", how to solve this issue?

**Comment by john-deng** [comment]
| Heketi v4.0.0-74-g0c21b4d
-- | --
  | [heketi] INFO 2017/08/25 20:54:57 Loaded kubernetes executor
  | [heketi] WARNING 2017/08/25 20:55:00 Unable to open database.  Retrying using read only mode

**Comment by john-deng** [comment]
@lpabon please help, I used heketi in production, but it's keeping read only failure.

**Comment by john-deng** [comment]
Here is the log:

Heketi v5.0.0-28-gae7d007
--
  | [heketi] INFO 2017/08/25 21:26:16 Loaded kubernetes executor
  | unexpected fault address 0x7f4f9c012000
  | fatal error: fault
  | [signal SIGBUS: bus error code=0x2 addr=0x7f4f9c012000 pc=0x6e6ef0]
  |  
  | goroutine 1 [running]:
  | runtime.throw(0x1805f21, 0x5)
  | /usr/lib/golang/src/runtime/panic.go:596 +0x95 fp=0xc4206079d8 sp=0xc4206079b8
  | runtime.sigpanic()
  | /usr/lib/golang/src/runtime/signal_unix.go:287 +0xf4 fp=0xc420607a28 sp=0xc4206079d8
  | github.com/heketi/heketi/vendor/github.com/boltdb/bolt.(*DB).mmap(0xc4201c6b40, 0x0, 0x0, 0x0)
  | /build/golang/src/github.com/heketi/heketi/vendor/github.com/boltdb/bolt/db.go:282 +0x250 fp=0xc420607ab0 sp=0xc420607a28
  | github.com/heketi/heketi/vendor/github.com/boltdb/bolt.Open(0xc420193f40, 0x19, 0x180, 0xc420607be8, 0x1, 0x1, 0x0)
  | /build/golang/src/github.com/heketi/heketi/vendor/github.com/boltdb/bolt/db.go:230 +0x2ff fp=0xc420607b80 sp=0xc420607ab0
  | github.com/heketi/heketi/apps/glusterfs.NewApp(0x23b2d20, 0xc42000e0c0, 0x0)
  | /build/golang/src/github.com/heketi/heketi/apps/glusterfs/app.go:96 +0x3de fp=0xc420607c90 sp=0xc420607b80
  | main.main()
  | /build/golang/src/github.com/heketi/heketi/main.go:139 +0x47d fp=0xc420607f88 sp=0xc420607c90
  | runtime.main()
  | /usr/lib/golang/src/runtime/proc.go:185 +0x20a fp=0xc420607fe0 sp=0xc420607f88
  | runtime.goexit()
  | /usr/lib/golang/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420607fe8 sp=0xc420607fe0
  |  
  | goroutine 17 [syscall, locked to thread]:
  | runtime.goexit()
  | /usr/lib/golang/src/runtime/asm_amd64.s:2197 +0x1
  |  
  | goroutine 7 [chan receive]:
  | github.com/heketi/heketi/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x2423100)
  | /build/golang/src/github.com/heketi/heketi/vendor/github.com/golang/glog/glog.go:879 +0x7a
  | created by github.com/heketi/heketi/vendor/github.com/golang/glog.init.1
  | /build/golang/src/github.com/heketi/heketi/vendor/github.com/golang/glog/glog.go:410 +0x21d
  |  
  | goroutine 9 [syscall]:
  | os/signal.signal_recv(0x0)
  | /usr/lib/golang/src/runtime/sigqueue.go:116 +0x104
  | os/signal.loop()
  | /usr/lib/golang/src/os/signal/signal_unix.go:22 +0x22
  | created by os/signal.init.1
  | /usr/lib/golang/src/os/signal/signal_unix.go:28 +0x41

**Comment by john-deng** [comment]
I tried to cp db, it report an error,

sh-4.3# cp heketi.db heketi.db-1708252131                                       
cp: error reading 'heketi.db': Input/output error

**Comment by john-deng** [comment]
Recovered the database from secrets backup (by HEKETI_BACKUP_DB_TO_KUBE_SECRET), still don't know why the database file is broken.

**Comment by pjanuario** [comment]
> @john-deng Sounds like the volume where the database is saved is running with only one replica out of three. Check the gluster volume.

FYI This also worked for me.
