### ISSUE TITLE
Kubernetes pod/PVC cleanup leads to pod stuck in termination

### ISSUE THREAD

**Issue by justicel** [heketi/heketi#806]
It appears that at least the latest heketi dev release, when paired with gluster-kubernetes, causes issues with pods becoming stuck in termination status. If you delete a PVC and pod pairing (say you have both in a yaml file) the volume appears to be deleted by heketi immediately and this causes the back-end node that the pod is attached to, to lose access to the IP based gluster mount.

This means that the pod is stuck in terminating status for all time unless you go to the kubernetes node, manually run an 'umount' on the lost volume and then delete the location from the kubelet volumes path for the pod. This should be easy to re-create with any created PVC and pod.

**Comment by lpabon** [comment]
@jarrpa @MohamedAshiqrh Could you guys take a look at this?

**Comment by MohamedAshiqrh** [comment]
@justicel Yeah This is possible from the gluster mount point of view. The gluster-plugin in kube umount's when the pod is down which is using the pvc. gluster-provisioner deletes the pvc dynamically on request(which is delete's pv, endpoints, service, gluster volume and the lv's associated with it.). If the pv is gone then the gluster-plugin doesn't have data to umount the volume. 

I understand this from code. @humblec worked on code so he will be able to correct me If I am wrong.

**Comment by justicel** [comment]
Okay, got it. Where should I open a bug report then? With Gluster core?
This essentially makes pod upgrades also unusable as it has the same
behavior.

**Comment by phlogistonjohn** [comment]
The last activity on this issue was over a year ago. This was not really a direct heketi issue. Closing. Please reopen if additional discussion is needed.
