### ISSUE TITLE
No deploy-heketi-deployment.json

### ISSUE THREAD

**Issue by Lazarus404** [heketi/heketi#807]
I'm following the Kubernetes integration docs, but have found there is no `deploy-heketi-deployment.json` file.  Where might I get it?  Is the integration docs out of date?

Thanks

**Comment by raghavendra-talur** [comment]
Are you looking for this file? https://github.com/gluster/gluster-kubernetes/blob/master/deploy/kube-templates/deploy-heketi-deployment.yaml

**Comment by Lazarus404** [comment]
I thought that, but was following a blog post and the getting started guide that both said the file should already be in extras/kubernetes in this repo, so wasn't certain.

**Comment by huguesalary** [comment]
Same here. I've been following the instructions here https://github.com/heketi/heketi/wiki/Kubernetes-Integration and they mention the  `deploy-heketi-deployment.yaml` file, which indeed does not exist in `extras/`. Although the file does exist at the location @raghavendra-talur pointed out, it'd be great to update the wiki and/or the `extras/` folder.

There's also conflicting information between the `README.md` in `https://github.com/heketi/heketi/tree/master/extras/kubernetes` and `https://github.com/heketi/heketi/wiki/Kubernetes-Integration`.

One mentions using `glusterfs-daemonset.json` but not the other, and most of the steps in `https://github.com/heketi/heketi/tree/master/extras/kubernetes/README.md` are missing. Removing a set of instructions and consolidating the doc in 1 single place would be helpful.

**Comment by amolsh** [comment]
@raghavendra-talur  As you said , i used https://github.com/gluster/gluster-kubernetes/blob/master/deploy/kube-templates/deploy-heketi-deployment.yaml

But, it did not create required pod. As per documentation, it creates one running pod.

Looks like documentation is all messy. Any idea where can I find its proper installation steps

**Comment by prapdm** [comment]
+1

**Comment by wernergillmer** [comment]
Trying to use the deploy-heketi-deployment.yaml file pointed out by @raghavendra-talur but it's using a secret, that I don't have, and I don't see where it get's created. What should be in the secret? Anyone got some documentation that's up to date?

**Comment by obnoxxx** [comment]
Please refer to the documentation and tools in the github.com/gluster/gluster-kubernetes repository for instructions, artifacts, and tools to deploy heketi and gluster into kubernetes.

There are several duplicates of this issue, including #873.

**Comment by obnoxxx** [comment]
The kubernetes related documentation in this repo is outdated  and needs to be updated/fixed/removed.

**Comment by phlogistonjohn** [comment]
Last updates to this issue were nearly a year ago. In addition the preferred way for those not planning on hacking on heketi is to install via gluster-kubernetes. Closing issue. Reopen if you feel additional discussion is needed.
