### ISSUE TITLE
docker image heketi/gluster not build since May(!)

### ISSUE THREAD

**Issue by LarsKumbier** [heketi/heketi#808]
The [heketi/gluster-image](https://hub.docker.com/r/heketi/gluster/) has not been built since [May 2017](https://hub.docker.com/r/heketi/gluster/builds/bcls8kwft4zjgcrdmntg6ba/) due to an error on systemctl

**Comment by LarsKumbier** [comment]
So, I investigated a bit. The problem is the mounting of `/dev` as a volume, which breaks the lookup of any binary. Removing `/dev` from the volumes list makes the problem go away, but I'll have to check if everything still runs.

**Comment by raghavendra-talur** [comment]
the command that failed is RUN systemctl disable nfs-server.service

Possibly the latest centos images(after may 2017) don't have a nfs-server unit file in them.

**Comment by LarsKumbier** [comment]
The failure happens because systemctl is not found anymore - as is any
binary after mounting the /dev volume. Try by running an echo moo after the
volume command, it'll fail as well.

von mobil gesendet

Am 17.07.2017 8:44 nachm. schrieb "Raghavendra Talur" <
notifications@github.com>:

**Comment by lpabon** [comment]
@LarsKumbier I should remove that image. You should use the official gluster Docker image.

**Comment by LarsKumbier** [comment]
please do - the default image setting should also be changed in the documentation and adjacent scripts.

**Comment by obnoxxx** [comment]
I removed the repo from dockerhub.
