### ISSUE TITLE
when device is removed then snapshots are lost

### ISSUE THREAD

**Issue by raghavendra-talur** [heketi/heketi#809]
When a device is removed , we migrate all the bricks using replace-brick function of gluster. But we don't check for existing snapshots on the thin pool. We should either fail the remove op or make it clear that snapshots are going to be lost.

**Comment by phlogistonjohn** [comment]
@raghavendra-talur in a general sense, how would you do either of the two suggested approaches?. This could be very relevant given PR #1259

**Comment by phlogistonjohn** [comment]
I do not think we will pursue this item. Closing issue. Please reopen if this is still relevant.
