### ISSUE TITLE
glusterfs: create volume err: error creating volume .

### ISSUE THREAD

**Issue by th3penguinwhisperer** [heketi/heketi#817]
Hi,

I'm trying to use dynamic provisioning with openshift and glusterfs however my claims stay in state pending. I used the gk-deploy script and I'm using Openshift Origin 1.5.1.
It seems the gluster pods are running and the heketi pod as well. The endpoints, ... are all available.

The gluster cluster is put in the default namespace.

```
glusterfs: got gid [2000] for PVC test18
glusterfs: create volume of size: 1073741824 bytes and configuration {url:http://172.30.206.46:8080/ user:admin userKey: secretNamespace:default secretName:heketi-secret secretValue:mypassword clusterId: gidMin:2000 gidMax:2147483647 volumeType:{Type:replicate Replicate:{Replica:3} Disperse:{Data:0 Redundancy:0}}}
glusterfs: error creating volume
glusterfs.go:664] glusterfs: create volume err: error creating volume .
pv_controller.go:1306] failed to provision volume for claim "default/test18" with StorageClass "gluster-container": glusterfs: create volume err: error creating volume .
...
glusterfs: create volume of size: 1073741824 bytes and configuration {url:http://172.30.206.46:8080/ user:admin userKey: secretNamespace:default secretName:heketi-secret secretValue:mypassword clusterId: gidMin:2000 gidMax:2147483647 volumeType:{Type:replicate Replicate:{Replica:3} Disperse:{Data:0 Redundancy:0}}}
```

As you see I don't get an empty error message from heketi which is rather unhelpful :)
When I go on a gluster pod and do gluster volume info I see one volume heketidbstorage.
I believe it's also using this volume:
192.168.178.33:heketidbstorage on /var/lib/heketi type fuse.glusterfs (rw,relatime,user_id=0,group_id=0,default_permissions,allow_other,max_read=131072)

Might this have to do with version differences? This is openshift 1.5.1 and the gluster pods seem to be gluster/gluster-centos:latest (nothing I did manually here AFAIK).

Storageclass is:

```
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  creationTimestamp: 2017-07-24T18:09:35Z
  name: gluster-container
  resourceVersion: "59215"
  selfLink: /apis/storage.k8s.io/v1beta1/storageclassesgluster-container
  uid: 402a3d21-709b-11e7-840b-525400548fa6
parameters:
  resturl: http://172.30.206.46:8080/
  restuser: admin
  secretName: heketi-secret
  secretNamespace: default
provisioner: kubernetes.io/glusterfs
```

Does someone have a clue what's going on here? There doesn't seem to be logging for heketi :s

Thanks in advance.

**Comment by th3penguinwhisperer** [comment]
I seem to get this error when I use the http://xyz without a trailing slash in the storageclass. I could capture it with tcpdump. Not sure if this is actually my problem or just because I've been fiddling so much.

```
HTTP/1.1 500 Internal Server Error
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Mon, 24 Jul 2017 19:35:53 GMT
Content-Length: 68
Set-Cookie: ff1a8205a9a2f52921c45408892389cf=d6838f12e85f29239853163010fa57a7; path=/; HttpOnly
```

Error calling v.allocBricksInCluster: database is in read-only mode

Error: Error calling v.allocBricksInCluster: database is in read-only mode

**Comment by th3penguinwhisperer** [comment]
So I can recreate the same error empty error message:

[root@openshift-master ~]# heketi-cli --json=true --user admin --secret mypassword -s http://heketi-default.cloud.xyz volume create --size=1 --persistent-volume-file=pv001.json 
Error: Error calling v.allocBricksInCluster: database is in read-only mode
[root@openshift-master ~]# heketi-cli --json=true --user admin --secret mypassword -s http://heketi-default.cloud.xyz/ volume create --size=1 --persistent-volume-file=pv001.json 
Error:

**Comment by th3penguinwhisperer** [comment]
So my question now is if this could be an RFE so that the error message is still shown even if a trailing slash is used for resturl (which seems to be in most of the documentation/blogs/...).

Another thing would be: what's a good way to prevent this from happening and perhaps have a small delay or retrying instead of immediately opening read-only.

**Comment by phlogistonjohn** [comment]
The last activity on this issue was over a year ago. Closing. Please reopen if additional discussion is needed.
