### ISSUE TITLE
update documentation for kubernetes

### ISSUE THREAD

**Issue by roffe** [heketi/heketi#820]
The documentation is faulty:

https://github.com/heketi/heketi/wiki/Kubernetes-Integration

deploy-heketi-deployment.json  <-- Where does this file come from, it's not in your repo.

**Comment by roffe** [comment]
i used heketi-deployment.json in the first step as the file you are pointing to is missing.

**Comment by roffe** [comment]
so it turns out i found the file in the heketi-cli release package and not a github repo as you state in the documentation. 

also it's in a openshift folder and not kubernetes.

**Comment by roffe** [comment]
New try today. This time even more fail:

```
Creating cluster ... ID: b279a7477e4f22f3749c896484f22e0f
	Creating node 10.1.201.181 ... ID: e75a1d0facd9e8a19c929714e181eb5d
		Adding device /dev/sdb ... Unable to add device: No pods with the label 'glusterfs-node=10.1.201.181' were found
	Creating node 10.1.201.182 ... Unable to create node: No pods with the label 'glusterfs-node=10.1.201.181' were found
	Creating node 10.1.201.183 ... Unable to create node: No pods with the label 'glusterfs-node=10.1.201.181' were found
```

```
➜  heketi git:(master) ✗ kc get po -o wide
NAME                             READY     STATUS    RESTARTS   AGE       IP             NODE
deploy-heketi-4120581439-h88k0   1/1       Running   0          4m        10.10.7.44     10.1.201.204
glusterfs-5bb82                  1/1       Running   0          6m        10.1.201.181   10.1.201.181
glusterfs-6wd3w                  1/1       Running   0          6m        10.1.201.183   10.1.201.183
glusterfs-w0pd7                  1/1       Running   0          6m        10.1.201.182   10.1.201.182
```

**Comment by roffe** [comment]
the glusterf daemonset is installed from glusterfs-daemonset.json provided by heketi

Please update your docs page with a big warning that HEKETI is currently broken and cannot be deployed on kubernetes to prevent more people from wastng their time until your docs examples are up to speed and working again

**Comment by wileeam** [comment]
@roffe Maybe you want to be more explicit in your problem and if the documentation is that faulty a PR can help you and everyone else.
I am actually running GlusterFS+Heketi in a cluster of two nodes (and not three) following mostly the  documentation available here and debugging the errors on the way (because you are right that the documentation is not exact).
I'll be happy to contribute with a PR for a better documentation (and particularly for the case of less than three nodes as there is some hardcoding of a minimum number of replicas in the CLI that actually halts the deployment in k8s).

**Comment by jtuthehien** [comment]
You need to set the environment variable HEKETI_KUBE_GLUSTER_DAEMONSET to 'y' for heketi to resolve pod name

**Comment by obnoxxx** [comment]
You guys are right! The wiki documentation and the templates in this repo are outdated. The current instructions, artifacts, and tools for deploying heketi and gluster in the kubernetes world can be found in the github.com/gluster/gluster-kubernetes repository. We need to update this repo....

**Comment by phlogistonjohn** [comment]
Very stale issue. Closing.
