### ISSUE TITLE
tests: Fix error with TestHeketiVolumeCreateWithOptions

### ISSUE THREAD

**Issue by lpabon** [heketi/heketi#829]
#828 needed to adjust the test to remove this error:

```
[heketi] ERROR 2017/08/05 04:13:30 /src/github.com/heketi/heketi/apps/glusterfs/app_volume.go:149: Failed to create volume: volume set: failed: option : performance.nl-cache-positive-entry does not exist
Did you mean performance.md-cache-timeout?
```
Creating an issue to see if we want to fix TestHeketiVolumeCreateWithOptions

**Comment by obnoxxx** [comment]
The point of that patch is to test *some* gluster volume options. The original test used an nl-cache options, which was added to gluster very recently. This choice was probably a little bit arbitrary. I don't yet know why, but now this nl-cache option does not seem to exist any more in the test env. (Are different images used now?) 

So by removing the setting and check of the nl-cache option, as you did, the test is still valid.
Hence we don't need to fix it, but we can improve the test by adding some more (established) options.

**Comment by obnoxxx** [comment]
Since there was no opposition to the above point, I'm closing this issue. The test is not broken but still valid, it just tests fewer options. Could expand it in the future if we want.

**Comment by humblec** [comment]
Sorry for being late, yeah, that options were picked up from `man page`, so yeah, could be really old option.
