### ISSUE TITLE
Error: Id not found when running volume create

### ISSUE THREAD

**Issue by barnzdan** [heketi/heketi#837]
**heketi-cli version**:  v4.0.0
**Heketi v4.0.0-8-g9372c22-release-4

**Gluster RPMs on heketi node**:
python2-gluster-3.10.1-1.el7.x86_64
glusterfs-geo-replication-3.10.1-1.el7.x86_64
centos-release-gluster310-1.0-1.el7.centos.noarch
glusterfs-3.10.1-1.el7.x86_64
glusterfs-api-3.10.1-1.el7.x86_64
glusterfs-server-3.10.1-1.el7.x86_64
glusterfs-libs-3.10.1-1.el7.x86_64
glusterfs-client-xlators-3.10.1-1.el7.x86_64
glusterfs-fuse-3.10.1-1.el7.x86_64
glusterfs-cli-3.10.1-1.el7.x86_64

**Container**:
docker.io/heketi/gluster                           latest              d22cfe32c3f8        3 months ago        332 MB

**Architecture**:
3 gluster nodes containerized with heketi RESTful API

---------

Im having trouble with one of my heketi clusters. Im able to query the cluster for information, and heketi responds, ie `heketi-cli volume list`, `heketi-cli topology info` however, any time I attempt to create a volume, I get the arbitrary:    Error: Id not found

` heketi-cli volume create --size=2`
`Error: Id not found`

**Comment by barnzdan** [comment]
I see this in the logs of one out of 3 of the heketi pods:

```[heketi] INFO 2017/08/16 15:54:44 Loaded kubernetes executor
[heketi] WARNING 2017/08/16 15:54:47 Unable to open database. Retrying using read only mode```

**Comment by 4admin2root** [comment]
when using pvc in kubernetes, I get errors as follow:
E0817 02:58:59.891612       1 glusterfs.go:754] glusterfs: error creating volume Error calling v.allocBricksInCluster: Id not found 
E0817 02:58:59.891638       1 glusterfs.go:684] glusterfs: create volume err: error creating volume Error calling v.allocBricksInCluster: Id not found.

**Comment by barnzdan** [comment]
I was able to resolve by scaling the replica count down to 1, then removing the last pod and letting it rebuild. This effectively removed the lock that was held on heketi.db. Up and running again. @4admin2root maybe try the same?

**Comment by ghoul008** [comment]
same question，how to solve it，thx

**Comment by ghoul008** [comment]
@4admin2root same question，how to solve it，thx
