### ISSUE TITLE
OpenShift Container Platform: heketi database read-only when evacuating a node

### ISSUE THREAD

**Issue by dmesser** [heketi/heketi#843]
Similar to #685 I get the following error message when the heketi pod is running on a node that is evacuated:

`Heketi 4.0.0

[heketi] INFO 2017/09/06 11:43:41 Loaded kubernetes executor

[heketi] WARNING 2017/09/06 11:43:44 Unable to open database.  Retrying using read only mode

[heketi] INFO 2017/09/06 11:43:58 Loaded simple allocator

[heketi] INFO 2017/09/06 11:43:58 GlusterFS Application Loaded

Authorization loaded

Listening on port 8080`

The evacuation of the node is done in OpenShift with the following command:

`oadm manage-node node04.internal --evacuate`

The behaviour is also seen when updating the DeploymentConfig in OpenShift and and subsequent rollout replaces the old pod with a new one.

Setting the terminationGracePeriod to 0 like suggested in the other issue does *not* help.

**Comment by ttindell2** [comment]
+1
