### ISSUE TITLE
Building the topology: will never stop

### ISSUE THREAD

**Issue by koalalorenzo** [heketi/heketi#844]
Hello!
I am creating a glusterfs cluster on k8s, and I am setting up some a device with `losetup` as follow:
```
$ fallocate -l 32GB /data.img
$ chmod 600 /data.img
$ mkfs.xfs -i size=512 -n size=8192 /data.img -f
$ losetup /dev/loop0 /data.img
$ echo "losetup /dev/loop0 /data.img" >> /etc/rc.local # just in case for reboot
```
after deploying glusterfs on each node of the network, and heketi as a pod, I am trying to set it up, but when I run:
`heketi-cli -s http://127.0.0.1:30525 topology load --json=/tmp/heketi.topology.json`
I get this message, and the command never exit:
```
Found node eu1.supercluster.com on cluster 13c7a8c984c7ee4b28a4f2944d3a9176
		Adding device /dev/loop0 ... 
```
The logs of all the glusterfs pods in k8s are not showing any details about `/dev/loop0`.

What am I doing wrong?

**Comment by koalalorenzo** [comment]
The topology file is:
```
{
  "clusters": [
    {"nodes":
      [{
          "node": {
            "hostnames": {
              "manage": [ "eu1.supercluster.com" ],
              "storage": [ "192.168.0.11" ]
            },
            "zone": 1
          },
          "devices": ["/dev/loop0"]
        },{
          "node": {
            "hostnames": {
              "manage": [ "eu2.supercluster.com" ],
              "storage": [ "192.168.0.13" ]
            },
            "zone": 1
          },
          "devices": ["/dev/loop0"]
        }]
    }
  ]
}
```

**Comment by obnoxxx** [comment]
@koalalorenzo thanks for your report.

I am not sure yet what's going on.
Are you running glusterfs on the hosts or in containers?
Where are you creating the loop device? (on each node? how does gluster get hold of it?)

heketi assumes raw block devices not file systems for provisioning volumes.

You usually need 3 gluster nodes at least (3-way replica is the default volume
type).

That does not explain the hang yet.
Can you provide the heketi logs, ideally at high level?

**Comment by obnoxxx** [comment]
And do you know the gluster-kubernetes project: https://github.com/gluster/gluster-kubernetes ?
it provides easy deployment for gluster+heketi into kubernetes.

**Comment by koalalorenzo** [comment]
yes, but somehow it was not working. After several tentatives I decided to switch to rook.io and that works... for now.

Meanwhile: yes my cluster was using 3 nodes + 1 master. (I was using just an example). But somehow it was hanging. I had Heketi logs saying something about a queue being executed, but I don't remember anything else...

**Comment by obnoxxx** [comment]
@koalalorenzo if you want to continue on this issue, could you somehow get us the logs? Otherwise, we could close it for now, and reopen (or open a new one) if you want to pick up again.

**Comment by koalalorenzo** [comment]
Lost the logs as I have re-created the cluster.
Sorry, I would suggest to keep it open if somebody runs into the same problem.

**Comment by ntfs32** [comment]
the same problem:
```bash
Waiting for GlusterFS pods to start ... OK
secret "heketi-config-secret" created
secret "heketi-config-secret" labeled
service "deploy-heketi" created
route "deploy-heketi" created
deploymentconfig "deploy-heketi" created
Waiting for deploy-heketi pod to start ... OK
Creating cluster ... ID: 668a701c8873ac137f6d64e23ce8b200
Allowing file volumes on cluster.
Allowing block volumes on cluster.
Creating node wx-bdh-05 ... ID: 23c52eca476f11b8fdb5f70ffd03e24f
```
install with `./gk-deploy  -n kube-system -g -y` createing node and never stop...

**Comment by obnoxxx** [comment]
@ntfs32 we would need description of the environment (kubernetes/...). And then logs from heketi.

**Comment by phlogistonjohn** [comment]
Very stale issue. Closing.
