### ISSUE TITLE
topology info: "ID not found"

### ISSUE THREAD

**Issue by hakanisaksson** [heketi/heketi#847]
Error: Can't list topology information
# heketi-cli topology info
Error: Id not found
also the same error if running:
heketi-cli node info <id>

Heketi version:
heketi-3.1.0
running standalone, on a gluster cluster with 3 nodes.

Log from console:
..
negroni] Completed 200 OK in 437.791µs
[negroni] Started GET /volumes/f2edda5947f4f2bb1831fef5899ca135
[negroni] Completed 200 OK in 609.455µs
[negroni] Started GET /nodes/17f054938f70e91cfc303bad4c132ed3
[negroni] Completed 500 Internal Server Error in 359.361µs

Other commands that still work:
heketi-cli node list
heketi-cli cluster list
heketi-cli volume

This happened after one of the gluster nodes in the cluster had crashed.
Questions: Is the heketi.db coprrupt? Can we fix it?
Found a possibly related bug? https://github.com/heketi/heketi/issues/382

**Comment by hakanisaksson** [comment]
Link to heketi.db.tar.gz http://ge.tt/7MN4zVm2

**Comment by obnoxxx** [comment]
@hakanisaksson thanks for your feed-back!

The referenced BZ was a concurrency problem that was fixed (in #579).
If you experienced a crash, this might likely have led to a corrupted DB indeed.
We'll need to investigate the db for clues...

@raghavendra-talur has experience with analyzing corrupted DBs.

**Comment by hakanisaksson** [comment]
Ok. thanks for the response! I solved the immediate problem with the db by restoring backup, only issue with that is that backups don't match the exact reality, i.e. volumes have been deleted/added in the meantime, and it's a pain to recreate gluster volumes manually to match the heketi db. Hoping something like the cli dump of https://github.com/heketi/heketi/pull/754 will make it's way into the main branch soon. Will upgrade to a newer version.

**Comment by obnoxxx** [comment]
@hakanisaksson sorry for the delay. Given the above statement, I assume I can close this issue. Please reopen if anything remains to be done here. The db dump tool is tracked separately.
