### ISSUE TITLE
newest heketi/heketi:dev container on docker hub doesn't allow to create openshift config

### ISSUE THREAD

**Issue by cbrand** [heketi/heketi#857]
I tried with the newest container on docker hub `heketi/heketi:dev` to create a new cluster. Loading the topology worked, but I ran into an issue when executing the `setup-openshift-heketi-storage`.

```
heketi-cli setup-openshift-heketi-storage 
Error: No space
```

The log of the heketi container included:
```
[heketi] ERROR 2017/09/19 14:50:28 /src/github.com/heketi/heketi/apps/glusterfs/volume_entry.go:290: Volume being ask to be created, but there are no clusters configured
```

This led me to the following code piece which might have an error in the most current version:
https://github.com/heketi/heketi/blob/9d2ef4bbaf547f5b86055e935f1d583196a069f1/apps/glusterfs/volume_entry.go#L265

I guess (but am not adapted enough in the inner workings of heketi) that the checks there always filter out all cluster candidates in the current version. I am also unable to create a volume via `heketi-cli`.

Switching back to the version `5` container did resolve the issue.

**Comment by yeyus** [comment]
@cbrand seeing the same problem using ```heketi/heketi:dev```. Also failing during regular volume creation:

```
heketi-cli volume create --size=10
Error: No space
```

**Comment by pblaas** [comment]
I'm starting seeing this too on a new kubernetes clusters on Container Linux. 

I've tried multiple k8s versions with same result. There are 3 glusterfs pods deployed by the ds and the glusterfs instances are able to see each other.

```[negroni] Started GET /clusters
[negroni] Completed 200 OK in 90.631µs
[negroni] Started GET /clusters/8985734c6f561332322abfde5910df13
[negroni] Completed 200 OK in 199.515µs
[negroni] Started POST /volumes
[negroni] Completed 202 Accepted in 118.344µs
[asynchttp] INFO 2017/09/26 23:54:30 asynchttp.go:125: Started job f25503a0307f3a5e8c6e3cd614c5d821
[heketi] INFO 2017/09/26 23:54:30 Creating volume bc8c413282053f23c5b2ace31b96c461
[heketi] ERROR 2017/09/26 23:54:30 /src/github.com/heketi/heketi/apps/glusterfs/volume_entry.go:290: Volume being ask to be created, but there are no clusters configured
[heketi] ERROR 2017/09/26 23:54:30 /src/github.com/heketi/heketi/apps/glusterfs/app_volume.go:149: Failed to create volume: No space
[asynchttp] INFO 2017/09/26 23:54:30 asynchttp.go:129: Completed job f25503a0307f3a5e8c6e3cd614c5d821 in 1.475459ms
```

**Comment by obnoxxx** [comment]
Which heketi-cli are you using? I guess it's an older one and not the one shipped with the master version?

I guess this is the same as #880.

**Comment by cbrand** [comment]
I tried reproducable it with the following. All had the same result:
* Compile `heketi-cli` myself with the then current master branch.
* Use the `heketi-cli` executable in the docker container which also executed the server.

**Comment by obnoxxx** [comment]
> I tried reproducable it with the following. All had the same result:
> 
> * Compile heketi-cli myself with the then current master branch.
> * Use the heketi-cli executable in the docker container which also executed the server.

Now that is really weird. When running locally from master, the heketi-cli is up-to date and everything works nicely... :-o

**Comment by cbrand** [comment]
Sorry, I should have been more specific: I tested it back when I originally opened the issue. I'll try it with the most current versions again once I initialize a new gluster cluster.

**Comment by patrickstjohn** [comment]
Running into this bug as well. Any ideas on a workaround? Or is moving back to version 5 with the 5.0 cli the correct move?

**Comment by chmod666org** [comment]
Same here. Any news ?

**Comment by nick-scoutbee** [comment]
Have the same problem
https://github.com/heketi/heketi/issues/948

**Comment by pjanuario** [comment]
Having the same problem and using heketi 5 and heketi-cli 5

**Comment by grantcurell** [comment]
I'm also at a loss. Fresh cluster, nothing on it whatsoever, listing cluster status shows the entire thing empty, getting error 255 No space with heketi:latest.

**Comment by collins-b** [comment]
Heketi cli v6.0.0 and server latest, results to no space error too.

**Comment by phlogistonjohn** [comment]
Stale issue. Closing.
