### ISSUE TITLE
Create a `make deps` target in the main project

### ISSUE THREAD

**Issue by purpleidea** [heketi/heketi#859]
We need this so that there's *one* safe way to add all the deps we need.

In `Makefile`:

```
deps:
  ./misc/make-deps.sh
```

in `misc/make-deps.sh`:
```
go get -d ./...
```
in `.travis.yaml`:
```
install:
- make deps
```

in centos-ci run make deps as well.
dangerous things should NOT go there.
So installing of glide should go outside of that.
A user should feel safe running it.

Assigned to @obnox

**Comment by purpleidea** [comment]
This way future users can *safely* add things to misc/make-deps.sh without having to patch centos, travis, and everything else...

**Comment by obnoxxx** [comment]
I will think about and hopefully eventually address this...  But I will still need to learn more about what is the real problem. And what is the right way to solve it...

**Comment by phlogistonjohn** [comment]
Very stale issue. Closing.
