### ISSUE TITLE
fail to create volume;

### ISSUE THREAD

**Issue by ZhengRongTan** [heketi/heketi#867]
@obnoxxx 
fail to create volume;
![image](https://user-images.githubusercontent.com/8637734/30790890-71df00e2-a1e1-11e7-9c55-0bf51275cc0c.png)

topology info
![image](https://user-images.githubusercontent.com/8637734/30790932-af37ea1c-a1e1-11e7-9e31-0745b1d7841c.png)
 
glusterfs info
![image](https://user-images.githubusercontent.com/8637734/30790964-e1a89f6e-a1e1-11e7-8d5e-3b98d9d6e998.png)

I run the below command 
lvcreate -L 50G -n LVtest VolGroup00
![image](https://user-images.githubusercontent.com/8637734/30790983-1319b402-a1e2-11e7-9174-2bc09ca36693.png)

**Comment by obnoxxx** [comment]
@ZhengRongTan thanks for your report. And sorry for the delay...

* What commands did you run to set up your environment (heketi / gluster)?
* Why do you run lvcreate? You should not (need to) do anything like this, since heketi takes care of setting up pvs/vgs/lvs...
