### ISSUE TITLE
Error: cannot get replicationcontrollers in project

### ISSUE THREAD

**Issue by ntfs32** [heketi/heketi#868]
when create glusterfs in openshift v3.6
```bash
oc process glusterfs -p GLUSTERFS_NODE=node01.xxx.com| oc create -f -
```
get some error:
```
error: couldn't get deployment glusterfs-dc-node01.yilia.me-1: User "system:serviceaccount:kube-system:deployer" cannot get replicationcontrollers in project "kube-system"
```
what should i do for this?

**Comment by obnoxxx** [comment]
Hi @ntfs32, this seems somewhat unrelated to the actual actual heketi project. The deployment tools and artifacts for deploying heketi and gluster in kubernetes have been moved to the github.com/gluster/gluster-kubernetes project. Please see up-to date instructions, templates and tools there. The gk-deploy tool in that repo has the current commands to run to successfully to deploy gluster.

**Comment by phlogistonjohn** [comment]
The last activity on this issue was nearly a year old. Closing issue. If you think additional discussion is needed please reopen the issue.
