### ISSUE TITLE
No Documentation for --image flag on heketi-cli setup-openshift-heketi-storage 

### ISSUE THREAD

**Issue by ttindell2** [heketi/heketi#870]
There is no documentation for the --image flag for heketi-cli setup-openshift-heketi-storage. This is needed for deployments where docker hub will be unavailable. Documentation is needed somewhere.

Openshift Ansible script is being updated to use this flag:

https://github.com/openshift/openshift-ansible/pull/5562

**Comment by raghavendra-talur** [comment]
@ttindell2 

This is currently documented in command --help option

```
heketi-cli setup-openshift-heketi-storage --help
Creates a dedicated GlusterFS volume for Heketi.
Once the volume is created, a Kubernetes/OpenShift
list object is created to configure the volume.

Usage:
  heketi-cli setup-openshift-heketi-storage [flags]

Flags:
  -h, --help              help for setup-openshift-heketi-storage
      --image string      container image to run this job (default "heketi/heketi:dev")
      --listfile string   Filename to contain list of objects (default "heketi-storage.json")
```
Are you looking for its documentation somewhere here is repo?

**Comment by ttindell2** [comment]
I didnt realize it was in the commandline help, though it would still be good to have better documentation in the repo

**Comment by obnoxxx** [comment]
The manpage needs updating.
What other place of documentation needs update?

**Comment by ttindell2** [comment]
I would imagine it should also be documented on the github wiki also.

**Comment by phlogistonjohn** [comment]
Very stale issue. Closing.
