### ISSUE TITLE
 deploy-heketi-deployment.json is missing when you do git clone

### ISSUE THREAD

**Issue by dimthe** [heketi/heketi#873]
Hello i am trying to get heketi/glusterfs to work on a kube cluster deployed with kubespray on centos 7.3 and docker 1.13.1 , kubectl 1.7.4

i found the missing file from here 
/master/deploy/kube-templates/deploy-heketi-deployment.yaml

i changed the version heketi:tag to heketi:latest and although the yaml seems to be working 
```
kubectl create -f deploy-heketi-deployment.yaml
service "deploy-heketi" created
deployment "deploy-heketi" created
```
it does not create a heketi pod

 ```
kubectl get pods
NAME              READY     STATUS    RESTARTS   AGE
glusterfs-2jnkx   1/1       Running   0          23m
glusterfs-352wm   1/1       Running   0          23m
glusterfs-gt2qx   1/1       Running   0          23m
glusterfs-tf5pj   1/1       Running   0          23m
```

i have manually done a docker pull heketi/heketi:latest and i see the image
```
docker images | grep heketi
heketi/heketi
```

having the image , i deleted the above deployment and re run kubectl create -f hoping it would work but i still see no heketi pod

is there a fix ? thanks

**Comment by obnoxxx** [comment]
As mentioned in issue #881, have you had a look at https://github.com/gluster/gluster-kubernetes ?

**Comment by obnoxxx** [comment]
@dimthe , any luck with gluster-kubernetes?

**Comment by phlogistonjohn** [comment]
Last comment was made nearly a year ago. Unless you want to hack on heketi directly it is recommended to deploy via gluster-kubernetes. Feel free to reopen if you wish to discuss further.
