### ISSUE TITLE
Brick creation failed with "device not properly aligned"

### ISSUE THREAD

**Issue by florent-souliere-smile** [heketi/heketi#876]
During the Gluster brick creation by Heketi (func `BrickCreate()` in `bricks.go`), it fails during call to `mkfs.xfs`.

Context:

- OpenShift template for Heketi. In this template, I tried default Heketi version image "dev", but also "4" and "5" with no success.
- Host OS is CentOS 7.4
- Host storage for Gluster is an iSCSI volume exposed by VMware as a physical disk. So that the storage device has a logical block size of 512 bytes and a physical block size of 4096 kbytes
- The storage device is given to Heketi in its whole (no partition, just plain disk. e.g. /dev/sdb). I also tried to create and give Heketi a partition (/dev/sdb1), with no success.
- During the execution of `heketi-cli -s http://deploy-heketi-glusterfs.openshift.local --user admin setup-openshift-heketi-storage`, there is the following error message:

`Error: Unable to execute command on glusterfs-9zmq6: warning: device is not properly aligned /dev/mapper/vg_3793d4187128d1efe9266b09fa908bc4-brick_c636c9bdf62932fb2e010166bfa05a3e
Use -f to force usage of a misaligned device`

After inspecting `BrickCreate()` function, I notice that some of the parameters for `mkfs.xfs` are hardcoded:

`fmt.Sprintf("mkfs.xfs -i size=512 -n size=8192 %v", s.devnode(brick)),`

Is Heketi currently not compatible with storage devices having sector size different than 512 bytes?

**Comment by raghavendra-talur** [comment]
@florent-souliere-smile , the way alignment seems to work is we fetch the extent size from Logical volume manager and then create a brick of size which is a multiple of the extent size.(Refer to code in https://github.com/heketi/heketi/blob/8e587614d95094c83b7b9e67f89aba9de0f4bd8c/apps/glusterfs/device_entry.go#L386 )

Now, we fetch the extent size in https://github.com/heketi/heketi/blob/71c8789e61ec838b3bfd5e8f9a52debb07e4e0c7/executors/sshexec/device.go#L128

If you still have the setup, please give the complete logs and also the output of 
vgdisplay -c volumegroupName

**Comment by florent-souliere-smile** [comment]
@raghavendra-talur Here is an extract of the logs collected on the OpenShift master host (I use the Heketi+Gluster deployment in OpenShift):

`
Oct  9 12:07:58 opendraft1 journal: [kubeexec] DEBUG 2017/10/09 10:07:58 /src/github.com/heketi/heketi/executors/kubeexec/kubeexec.go:250: Host: opendraft3 Pod: glusterfs-hpl4k Command: pvcreate --metadatasize=128M --dataalignment=256K /dev/sdb
Oct  9 12:07:58 opendraft1 journal: Result:   Physical volume "/dev/sdb" successfully created.
Oct  9 12:07:58 opendraft1 journal: [kubeexec] DEBUG 2017/10/09 10:07:58 /src/github.com/heketi/heketi/executors/kubeexec/kubeexec.go:250: Host: opendraft3 Pod: glusterfs-hpl4k Command: vgcreate vg_3d78afad225b70bf0c40c9c827b57982 /dev/sdb
Oct  9 12:07:58 opendraft1 journal: Result:   Volume group "vg_3d78afad225b70bf0c40c9c827b57982" successfully created
Oct  9 12:07:58 opendraft1 journal: [kubeexec] DEBUG 2017/10/09 10:07:58 /src/github.com/heketi/heketi/executors/kubeexec/kubeexec.go:250: Host: opendraft3 Pod: glusterfs-hpl4k Command: vgdisplay -c vg_3d78afad225b70bf0c40c9c827b57982
Oct  9 12:07:58 opendraft1 journal: Result:   vg_3d78afad225b70bf0c40c9c827b57982:r/w:772:-1:0:0:0:-1:0:1:1:1073606656:4096:262111:0:262111:a0K7FX-lN1g-EeP6-yQoJ-84tX-dUkf-7hww7G
...
Oct  9 12:08:05 opendraft1 journal: [kubeexec] DEBUG 2017/10/09 10:08:05 /src/github.com/heketi/heketi/executors/kubeexec/kubeexec.go:250: Host: opendraft1 Pod: glusterfs-jrd7p Command: lvcreate --poolmetadatasize 12288K -c 256K -L 2097152K -T vg_320301571b4d4a6afdfba4d189f614ca/tp_fb33a1aedd66585f125a0bb2930095c1 -V 2097152K -n brick_fb33a1aedd66585f125a0bb2930095c1
Oct  9 12:08:05 opendraft1 journal: Result:   Using default stripesize 64.00 KiB.
Oct  9 12:08:05 opendraft1 journal:  Logical volume "brick_fb33a1aedd66585f125a0bb2930095c1" created.
Oct  9 12:08:05 opendraft1 journal: [kubeexec] ERROR 2017/10/09 10:08:05 /src/github.com/heketi/heketi/executors/kubeexec/kubeexec.go:247: Failed to run command [mkfs.xfs -i size=512 -n size=8192 /dev/mapper/vg_320301571b4d4a6afdfba4d189f614ca-brick_fb33a1aedd66585f125a0bb2930095c1] on glusterfs-jrd7p: Err[command terminated with exit code 1]: Stdout []: Stderr [warning: device is not properly aligned /dev/mapper/vg_320301571b4d4a6afdfba4d189f614ca-brick_fb33a1aedd66585f125a0bb2930095c1
Oct  9 12:08:05 opendraft1 journal: Use -f to force usage of a misaligned device
Oct  9 12:08:05 opendraft1 journal: ]
`

Besides that, the storage device's logical block size is 512, and its physical block size is 4096.

After some trials and errors, the operation becomes successful when I patch Heketi to add option `--dataalignmentoffset 256`. But it was not the result of a calculation I would have made.

**Comment by obnoxxx** [comment]
@florent-souliere-smile fyi, I edited your comment to use triple backticks for quoting the multi-line log snippet. this way, line-breaks are displayed correctly...

**Comment by k-troska** [comment]
I had the same problem, worked around this in OpenShift installation by recreating vg by myself after creating topology (by putting pause in ansible after topology call).

The main issue is here:
https://github.com/heketi/heketi/blob/9e8e5bbda5e45cee059e4649d8f42d23945a4296/executors/sshexec/device.go#L37
It forces alignment when creating pv, if created without those parameters it will work without problems, lvm will use defaults depending on system lvm config file.

**Comment by florent-souliere-smile** [comment]
@k-troska Your idea actually works! But instead of patching heketi to remove the hardcoded `dataalignment` option, I choosed to customize `pvcreate` in order to filter this out.

I still wonder why `dataalignment` is hardcoded in Heketi...

**Comment by obnoxxx** [comment]
@mkrull @k-troska I don't really know why `dataalignment` is hard-coded in heketi. It was introduced in #202, and all I can see for arguments is issue #187, which just says that the seetings recommended by the gluster community for lvm should be implemented... 

@nixpanic do you know have more background?

**Comment by phlogistonjohn** [comment]
The dataalignment (and other) formatting parameters were made configurable in PR #1463. I think that should be sufficient to close this issue as it no longer requires users to recompile heketi. If better defaults are needed let's file a separate new issue for that.

**Comment by Davidrjx** [comment]
> The dataalignment (and other) formatting parameters were made configurable in PR #1463. I think that should be sufficient to close this issue as it no longer requires users to recompile heketi. If better defaults are needed let's file a separate new issue for that.



> The dataalignment (and other) formatting parameters were made configurable in PR #1463. I think that should be sufficient to close this issue as it no longer requires users to recompile heketi. If better defaults are needed let's file a separate new issue for that.

seems not ok, heketi.json looks like
```
{
        "_port_comment": "Heketi Server Port Number",
        "port" : "8080",

        "_use_auth": "Enable JWT authorization. Please enable for deployment",
        "use_auth" : false,

        "_jwt" : "Private keys for access",
        "jwt" : {
                "_admin" : "Admin has access to all APIs",
                "admin" : {
                        "key" : ""
                },
                "_user" : "User only has access to /volumes endpoint",
                "user" : {
                        "key" : ""
                }
        },

        "_glusterfs_comment": "GlusterFS Configuration",
        "glusterfs" : {

                "_executor_comment": "Execute plugin. Possible choices: mock, kubernetes, ssh",
                "executor" : "kubernetes",

                "_db_comment": "Database file name",
                "db" : "/var/lib/heketi/heketi.db",

                "kubeexec" : {
                        "rebalance_on_expansion": true,
                        "pv_data_alignment": "256"
                },

                "sshexec" : {
                        "rebalance_on_expansion": true,
                        "keyfile" : "/etc/heketi/private_key",
                        "port" : "22",
                        "user" : "root",
                        "sudo" : false
                }
        },

        "backup_db_to_kube_secret": false
}
```

**Comment by Davidrjx** [comment]
> The dataalignment (and other) formatting parameters were made configurable in PR #1463. I think that should be sufficient to close this issue as it no longer requires users to recompile heketi. If better defaults are needed let's file a separate new issue for that.



> The dataalignment (and other) formatting parameters were made configurable in PR #1463. I think that should be sufficient to close this issue as it no longer requires users to recompile heketi. If better defaults are needed let's file a separate new issue for that.

seems not ok, heketi.json looks like
```
{
        "_port_comment": "Heketi Server Port Number",
        "port" : "8080",

        "_use_auth": "Enable JWT authorization. Please enable for deployment",
        "use_auth" : false,

        "_jwt" : "Private keys for access",
        "jwt" : {
                "_admin" : "Admin has access to all APIs",
                "admin" : {
                        "key" : ""
                },
                "_user" : "User only has access to /volumes endpoint",
                "user" : {
                        "key" : ""
                }
        },

        "_glusterfs_comment": "GlusterFS Configuration",
        "glusterfs" : {

                "_executor_comment": "Execute plugin. Possible choices: mock, kubernetes, ssh",
                "executor" : "kubernetes",

                "_db_comment": "Database file name",
                "db" : "/var/lib/heketi/heketi.db",

                "kubeexec" : {
                        "rebalance_on_expansion": true,
                        "pv_data_alignment": "256"
                },

                "sshexec" : {
                        "rebalance_on_expansion": true,
                        "keyfile" : "/etc/heketi/private_key",
                        "port" : "22",
                        "user" : "root",
                        "sudo" : false
                }
        },

        "backup_db_to_kube_secret": false
}
```

**Comment by Davidrjx** [comment]
> @k-troska Your idea actually works! But instead of patching heketi to remove the hardcoded `dataalignment` option, I choosed to customize `pvcreate` in order to filter this out.
> 
> I still wonder why `dataalignment` is hardcoded in Heketi...



> @k-troska Your idea actually works! But instead of patching heketi to remove the hardcoded `dataalignment` option, I choosed to customize `pvcreate` in order to filter this out.
> 
> I still wonder why `dataalignment` is hardcoded in Heketi...

how to customise heketi instead of patching

**Comment by Davidrjx** [comment]
> @k-troska Your idea actually works! But instead of patching heketi to remove the hardcoded `dataalignment` option, I choosed to customize `pvcreate` in order to filter this out.
> 
> I still wonder why `dataalignment` is hardcoded in Heketi...



> @k-troska Your idea actually works! But instead of patching heketi to remove the hardcoded `dataalignment` option, I choosed to customize `pvcreate` in order to filter this out.
> 
> I still wonder why `dataalignment` is hardcoded in Heketi...

how to customise heketi instead of patching
