### ISSUE TITLE
Lost topology information

### ISSUE THREAD

**Issue by wernergillmer** [heketi/heketi#877]
Hi

Running on Kubernetes (1.7.0) the node that my heketi pod runs on died, and the heketi pod got rescheduled to another node.
Problem now is, using `heketi-cli topology info` shows nothing, there does not seem to be a cluster etc. However, all my bounded pvc's in Kubernetes is up and working. All my Glusterfs pods is good, but I cannot bound new pvc's to the storageClass I created, that poinds to Heketi. How can I get heketi to know the state of my storage again? Should I reload the topology.json file and the generated heketi-storage.json file? Had a look in the documentation, and I don't see this scenario discussed anywhere.

**Comment by raghavendra-talur** [comment]
@wernergillmer How did you deploy heketi? Heketi maintains all the information in a database file located in /var/lib/heketi/heketi.db by default. If you used gk-deploy from https://github.com/gluster/gluster-kubernetes project then it would have created a gluster volume and bind mounted to /var/lib/heketi such that you have same data available on pod migration. 

Let us know how you deployed and we can help further.

**Comment by wernergillmer** [comment]
Managed to get it working, by following the gk-deploy route, rather than the instructions in this git repo.
