### ISSUE TITLE
go-client is not up-to-date

### ISSUE THREAD

**Issue by pkutishch** [heketi/heketi#878]
Release-5 client-go doesn't contains VolumeOptions for new feature which has been released in latest release.

**Comment by raghavendra-talur** [comment]
@pkutishch You are right. However, it wasn't supposed to be in release-5. It is likely that the changelog is wrong, @obnoxxx ?

**Comment by pkutishch** [comment]
@raghavendra-talur are you going to stop maintaining go-client? as i could see it in use inside kubernetes glusterfs dynamic provisioner.

**Comment by obnoxxx** [comment]
@pkutishch we are of course not stopping maintenance of the client!

@pkutishch , @raghavendra-talur : what is the concrete problem? What is missing?

**Comment by obnoxxx** [comment]
ping @pkutishch , @raghavendra-talur - any explanation what the problem actually is?

**Comment by phlogistonjohn** [comment]
Issue has been idle for nearly a year. Heketi version 8 was recently released. Please reopen this issue if you think there is still a problem with the API support in Heketi v8.0.0.
