### ISSUE TITLE
Add a way to create test coverage reports to heketi.

### ISSUE THREAD

**Issue by obnoxxx** [heketi/heketi#888]

**Comment by phlogistonjohn** [comment]
I have some preliminary work in this area in my fork. I meant to assign this to myself but it seems github doesn't allow that. (Even though I'm a member/dev?)

**Comment by phlogistonjohn** [comment]
This has been implemented for a while now AFAICT. You can run `make test TESTOPTIONS="-vchtml` which will generate an html file per-module that can be viewed locally. In addition tests run via travis are submitting reports to coveralls @ https://coveralls.io/github/heketi/heketi

If this is not sufficient we should open a new issue with more detail about what kind of behaviors we want from our coverage reports.
