### ISSUE TITLE
Docker image heketi/gluster:latest is not accessible on Docker Hub

### ISSUE THREAD

**Issue by jciniburk** [heketi/heketi#894]
Hi.
I was trying to run GlusterFS in my Kubernetes. 
When I executed 

`kubectl create -f gluster-daemonset.json`
It ends up producing error:
`Failed to pull image "heketi/gluster:latest": rpc error: code = Unknown desc = Error: image heketi/gluster:latest not found
Error syncing pod`

Then I checked the docker hub and the image is not present there.
https://hub.docker.com/r/heketi/gluster/

Thx

**Comment by renich** [comment]
Same problem here.

**Comment by lorec0re** [comment]
same here

**Comment by cameron-scrace** [comment]
same issue here, openshift storage currently down because the image is no longer available.

**Comment by raghavendra-talur** [comment]
@jciniburk @renich @lorec0re @cameron-scrace There have been many changes in the daemonset template. Please refer to https://github.com/gluster/gluster-kubernetes/blob/master/deploy/kube-templates/glusterfs-daemonset.yaml for the latest template and use https://hub.docker.com/r/gluster/gluster-centos/ as the gluster image.

**Comment by phlogistonjohn** [comment]
As @raghavendra-talur noted the Heketi project does not provide gluster container images directly. The images provided by the overall gluster project should be used. Closing issue as it has been idle for quite some time.
