### ISSUE TITLE
Need test for issue #789

### ISSUE THREAD

**Issue by obnoxxx** [heketi/heketi#895]
PR #850 fixed issue #789. But we still need a test for this.
This test does not need to be at the http/REST api layer,
much rather I suggest testing this at the layer of our internal
functions.

**Comment by obnoxxx** [comment]
@purpleidea fyi. happy to sit down with you hacking on this at some point.

**Comment by purpleidea** [comment]
(Notes for later)

Repro:

# SETUP:

cd ~/code/heketi/heketi
rm tmp/var/heketi.db ; ./heketi --config heketi.json  # mock

cd ~/code/heketi/heketi/client/cli/go
./heketi-cli topology load --json=topology-sample.json

# BUG1:
./heketi-cli volume create --size 100


[negroni] Started POST /clusters
[negroni] Completed 201 Created in 9.973816ms
[negroni] Started GET /clusters/a3a2e405a7c1da73b0b8583d54a9fe22
[negroni] Completed 200 OK in 292.978µs

[negroni] Started DELETE /clusters/a3a2e405a7c1da73b0b8583d54a9fe22
[heketi] ERROR 2017/09/10 00:42:46 /src/github.com/heketi/heketi/apps/glusterfs/allocator_simple.go:142: Unknown cluster id requested: a3a2e405a7c1da73b0b8583d54a9fe22
[heketi] INFO 2017/09/10 00:42:46 Deleted cluster [a3a2e405a7c1da73b0b8583d54a9fe22]
[negroni] Completed 200 OK in 17.812273ms

**Comment by purpleidea** [comment]
(Notes for later)

Repro:

# SETUP:

cd ~/code/heketi/heketi
rm tmp/var/heketi.db ; ./heketi --config heketi.json  # mock

cd ~/code/heketi/heketi/client/cli/go
./heketi-cli topology load --json=topology-sample.json

# BUG1:
./heketi-cli volume create --size 100


[negroni] Started POST /clusters
[negroni] Completed 201 Created in 9.973816ms
[negroni] Started GET /clusters/a3a2e405a7c1da73b0b8583d54a9fe22
[negroni] Completed 200 OK in 292.978µs

[negroni] Started DELETE /clusters/a3a2e405a7c1da73b0b8583d54a9fe22
[heketi] ERROR 2017/09/10 00:42:46 /src/github.com/heketi/heketi/apps/glusterfs/allocator_simple.go:142: Unknown cluster id requested: a3a2e405a7c1da73b0b8583d54a9fe22
[heketi] INFO 2017/09/10 00:42:46 Deleted cluster [a3a2e405a7c1da73b0b8583d54a9fe22]
[negroni] Completed 200 OK in 17.812273ms

**Comment by purpleidea** [comment]
(Notes for later)

Repro:

# SETUP:

cd ~/code/heketi/heketi
rm tmp/var/heketi.db ; ./heketi --config heketi.json  # mock

cd ~/code/heketi/heketi/client/cli/go
./heketi-cli topology load --json=topology-sample.json

# BUG1:
./heketi-cli volume create --size 100


[negroni] Started POST /clusters
[negroni] Completed 201 Created in 9.973816ms
[negroni] Started GET /clusters/a3a2e405a7c1da73b0b8583d54a9fe22
[negroni] Completed 200 OK in 292.978µs

[negroni] Started DELETE /clusters/a3a2e405a7c1da73b0b8583d54a9fe22
[heketi] ERROR 2017/09/10 00:42:46 /src/github.com/heketi/heketi/apps/glusterfs/allocator_simple.go:142: Unknown cluster id requested: a3a2e405a7c1da73b0b8583d54a9fe22
[heketi] INFO 2017/09/10 00:42:46 Deleted cluster [a3a2e405a7c1da73b0b8583d54a9fe22]
[negroni] Completed 200 OK in 17.812273ms

**Comment by raghavendra-talur** [comment]
Also, loading a topology file throws some errors:

```
[heketi] ERROR 2017/11/21 00:42:17 /src/github.com/heketi/heketi/apps/glusterfs/allocator_simple.go:149: cluster id 5e589e5079b99986ccacc7f174aa2421 already exists
```

This seems to be because of AddCluster() being called multiple times for the same cluster id.

**Comment by phlogistonjohn** [comment]
I'm triaging issues. Calling this a "wontfix"
