### ISSUE TITLE
Build fails with git version < 2.7.0

### ISSUE THREAD

**Issue by rishubhjain** [heketi/heketi#902]
https://github.com/heketi/heketi/blob/master/Makefile#L12 throws error if git version is below 2.7.1.
Git version required for building hekeit must be either specified or the exception should be handled.

**Comment by rishubhjain** [comment]
cc: @raghavendra-talur

**Comment by raghavendra-talur** [comment]
Yes, this is because sort=creatorder is not available in git version below 2.7.1. I don't think sorting is required in this particular case, will send a patch.

**Comment by obnoxxx** [comment]
should be fixed with PR #907, which is now merged.
