### ISSUE TITLE
Add support for getting volume ID from volume name.

### ISSUE THREAD

**Issue by humblec** [heketi/heketi#908]
Currently there is no way in heketi to get volume ID from volume name either via cli or api. This is a must requirement at certain scenarios and there should be a way to resolve ID from volume name.

**Comment by humblec** [comment]
@raghavendra-talur @phlogistonjohn @obnoxxx thoughts?

**Comment by raghavendra-talur** [comment]
@humblec This is doable but a hard problem. A volume name is not guaranteed to be unique from heketi's perspective. It is unique for a gluster cluster and heketi might be managing multiple gluster clusters.

So it is possible that you get multiple vol IDs for the same name. 

It is a searching problem and I don't think we need to solve it.

**Comment by purpleidea** [comment]
@humblec Can you give us more details about why this is needed, and (I hate to say it) but a specific use case please?

**Comment by raghavendra-talur** [comment]
In my comment above, I just meant we should not do it in server. But I still like this idea and would like to do it in heketi-cli using existing REST URLs.

**Comment by humblec** [comment]
@raghavendra-talur @purpleidea if /adminI know heketi volume name and if we want to delete that volume, currently its very tedious process. The only option now is ,

Send volume list then grep or search for the volume name in output and retrieve ID. Once you have the ID send volume delete() with  ID as its arg. 

Admin know the volume name he created, but to delete he has to follow above process and there are also scenarios where we only have volume name and have to delete the volume .

**Comment by obnoxxx** [comment]
@raghavendra-talur how does "doable but a hard problem" and the "good first issue" label fit together? :-)

**Comment by raghavendra-talur** [comment]
@obnoxxx my comments are not clear because I had more context from @humblec on the requirement.

To delete a volume by volume name as asked in the above comment is hard. It is performing a change in state and by using volume name(an entity that is not a primary value).

To just display all possible volume ids that have volume name as required in cli is a very easy read and grep operation.

If we agree to do the cli thing, it is a easyfix.

**Comment by obnoxxx** [comment]
@raghavendra-talur sure, I know. I was just trying to tease you...

Also, deleting a volume by name is with the current design not "doable but hard". Instead it's theoretically simply impossible. :-)

The best approximation could be to do the deletion if and only if the name specified belongs to a single volume only. In the other case we could print an error similar to "this name fits multiple volumes ..." That would probably cover most real world use cases.

The cli for getting the volume ids for a given name might be useful, but it would make the actual request for deleting by name just marginally simpler:

Without the cli enhancement:
```
heketi-cli volume list | grep " Name:${NAME}"
# ==> tell whether it's a single ID, if so use it for:
heketi-cli volume delete ID
```

with the cli enhancement
```
heketi-cli volume list --name="${NAME}"
# ==> tell whether it's a single ID, if so use it for: 
heketi-cli voume delete ID
```

Probably worth doing but really just marginal benefit imho.

**Comment by obnoxxx** [comment]
It seems I was wrong. We do name checking, and we do enforce a name to be unique in a cluster:

```
$ ./client/cli/go/heketi-cli volume create --size 1 --name OBNOX                                                                    
Name: OBNOX                                
Size: 1                                    
Volume Id: cd8cbf487e88452bbc109caaf6e9ce53                                            
Cluster Id: 23a9865fa0dd8f98f39a3b9a3096efa9                                           
Mount: 192.168.10.100:OBNOX                
Mount Options: backup-volfile-servers=192.168.10.101,192.168.10.102,192.168.10.103     
Block: false                               
Free Size: 0                               
Block Volumes: []                          
Durability Type: replicate                 
Distributed+Replica: 3                     
$  ./client/cli/go/heketi-cli volume create --size 1 --name OBNOX                                                                    
Error: Name OBNOX is already in use in all available clusters
$ 
```

**Comment by obnoxxx** [comment]
That means we can in fact do the by-name operations if needed!

**Comment by humblec** [comment]
Thanks @obnoxxx , in my vague memory it didnt allow me to create volume with same name again, but got confused when I heard name is not unique :). Any way thanks for confirming it.

**Comment by phlogistonjohn** [comment]
Stale issue. Closing.
