### ISSUE TITLE
heketi hangs in delete volume

### ISSUE THREAD

**Issue by yu-yang2** [heketi/heketi#914]
My heketi-cli hangs in delete volume, and heketi sever didn't show any error logs, how to debug?

**Comment by raghavendra-talur** [comment]
@yu-yang2 do other commands work? Set server to debug logs and see if the request reaches the server.

**Comment by yu-yang2** [comment]
@raghavendra-talur other commands work, after restart heketi server, volumes can be deleted now, thanks
