### ISSUE TITLE
login shell and commands not found with ssh executor

### ISSUE THREAD

**Issue by jd-daniels** [heketi/heketi#918]
I'm attempting to load topology on an empty gluster cluster and I'm getting path errors related to no login shell.
This is heketi from EPEL. 4.0.0-2.el7, RHEL7.3, 3.10.0-514.26.2.el7.x86_64. I couldn't seem to find any reference to this issue besides something similar with a vagrant user. The fix, adding the sudo config option, doesn't seem to work in this case.

```
[~]# heketi-cli topology load --json=json.json 
	Found node 10.30.12.100 on cluster d7257973294192096f81131ce97ee2ab
		Adding device /dev/sdb ... Unable to add device: /bin/bash: pvcreate: command not found
	Creating node 10.30.12.101 ... Unable to create node: /bin/bash: gluster: command not found

```
If I do 'which gluster' or 'which pvcreate' from root or from the heketi user, I find the commands.

This is my executor:

```
    "_sshexec_comment": "SSH username and private key file information",
    "sshexec": {
      "keyfile": "/var/lib/heketi/.ssh/id_rsa",
      "user": "heketi",
      "port": "22",
      "fstab": "/etc/fstab",
      "sudo": true
    },
```
Thanks!

**Comment by tlopo** [comment]
What was the resolution for this issue @jd-daniels  ?

**Comment by jd-daniels** [comment]
@tlopo 

So its been a while, forgive me if this is a bit vague. I looked back at my bash history and pieced this together, it seems it was that the user running the heketi service didn't have an RSA key in the correct spot with the correct permissions. The user running the service needs to be able to ssh with keys to the nodes. Specifically I created a key, moved id_rsa to /var/lib/heketi/id_rsa, set 600 on it. Then ensured the 'keyfile' field in /etc/heketi/heketi.json pointed to it.

Further, you've got to make sure it doesn't get caught accepting the host identifier. So test the passwordless ssh manually yourself by su-ing/sudoing to the user and sshing with the id_rsa key so you can answer the prompt and accept the identifier into known_hosts for the service account. You need to have that working for all the nodes.
