### ISSUE TITLE
Replace node/device with same hostname/IP

### ISSUE THREAD

**Issue by dhain** [heketi/heketi#922]
If a node fails, and I can get the node back online with gluster running at the same host/IP, but in a fresh state (ie. not part of a trusted pool, has no devices/bricks), then Heketi won't let me recover from this situation. If I try to disable/remove the device while the fresh gluster is running, this is what happens:

    dhain@bonsai2:~$ kubectl exec -it heketi-6965dd57cb-w6vrm -- /bin/sh
    sh-4.4# heketi-cli device remove b0d6bd8906ef3a6f3f840f6c944aa240
    command terminated with exit code 137
    dhain@bonsai2:~$

I get dropped all the way back to my host shell (not the kubectl exec'd shell) for some reason.

If I stop gluster on the replaced node first, I don't get the crash, but I get this:

    Error: Failed to remove device, error: No Replacement was found for resource requested to be removed

I can't add the replaced node as a new node, because Heketi then complains:

    Error: Hostname bonsai4 already used by node with id 19f2db7d6fec3805debd8ffc1af8db7e

Presumably I could rename the node and then add it as a new node, then remove the device, but this is impractical due to other services running on the node. Is there any way around this? Is a proper "replace node" function planned?

**Comment by vigevenoj** [comment]
Hello, I think I'm having the same problem and I have some additional details (it's not clear if this issue was resolved elsewhere).    
I have a three-node kubernetes cluster where all the nodes are storage nodes, and one node failed and was brought back online with a completely new operating system, but with the storage volume (a block device) attached and with data available. When I try to remove the node via heketi-cli, I get the termination message above, and the heketi pod logs the following:

```negroni] Started GET /nodes/7178c662bd4b0dc8402515dece3c2afb
[negroni] Completed 200 OK in 2.188411ms
[negroni] Started POST /nodes/7178c662bd4b0dc8402515dece3c2afb/state
[negroni] Completed 202 Accepted in 1.577351ms
[asynchttp] INFO 2018/02/15 05:56:08 asynchttp.go:125: Started job 38b82da06a84eee0de6187845edd12c4
[heketi] INFO 2018/02/15 05:56:08 Loaded simple allocator
[asynchttp] INFO 2018/02/15 05:56:08 asynchttp.go:129: Completed job 38b82da06a84eee0de6187845edd12c4 in 1.703469ms
[negroni] Started GET /queue/38b82da06a84eee0de6187845edd12c4
[negroni] Completed 204 No Content in 78.874µs
[negroni] Started POST /nodes/7178c662bd4b0dc8402515dece3c2afb/state
[negroni] Completed 202 Accepted in 1.228169ms
[asynchttp] INFO 2018/02/15 05:56:14 asynchttp.go:125: Started job d4f8136a8299d8f3117cbc26fe13720d
[heketi] INFO 2018/02/15 05:56:14 Loaded simple allocator
[heketi] INFO 2018/02/15 05:56:14 Replacing brick 19d4191be3f3be19aa98cd155fefa9db on device 974889cdd7351bedfbcaf9d454a1905f on node 7178c662bd4b0dc8402515dece3c2afb
[cmdexec] INFO 2018/02/15 05:56:14 Check Glusterd service status in node robot-ghost-poop-3.xn--9q8h2cq1m.ws
[negroni] Started GET /queue/d4f8136a8299d8f3117cbc26fe13720d
[negroni] Completed 200 OK in 77.344µs
[kubeexec] DEBUG 2018/02/15 05:56:15 /src/github.com/heketi/heketi/executors/kubeexec/kubeexec.go:249: Host: robot-ghost-poop-3.xn--9q8h2cq1m.ws Pod: glusterfs-sf8h7 Command: systemctl status glusterd
Result: ● glusterd.service - GlusterFS, a clustered file-system server
   Loaded: loaded (/usr/lib/systemd/system/glusterd.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2018-02-13 22:37:25 UTC; 1 day 7h ago
  Process: 220 ExecStart=/usr/sbin/glusterd -p /var/run/glusterd.pid --log-level $LOG_LEVEL $GLUSTERD_OPTIONS (code=exited, status=0/SUCCESS)
 Main PID: 222 (glusterd)
   CGroup: /kubepods/burstable/pod74d7c55c-110e-11e8-a13a-c248480c7213/0c14f6ba1e271b1f52e94e8395d9bc26cc7cdfe660c68d1237d6a71014f7905e/system.slice/glusterd.service
           └─222 /usr/sbin/glusterd -p /var/run/glusterd.pid --log-level INFO

Feb 13 22:37:23 robot-ghost-poop-3.xn--9q8h2cq1m.ws systemd[1]: Starting GlusterFS, a clustered file-system server...
Feb 13 22:37:25 robot-ghost-poop-3.xn--9q8h2cq1m.ws systemd[1]: Started GlusterFS, a clustered file-system server.
[negroni] Started GET /queue/d4f8136a8299d8f3117cbc26fe13720d
[negroni] Completed 200 OK in 153.963µs
[kubeexec] DEBUG 2018/02/15 05:56:15 /src/github.com/heketi/heketi/executors/kubeexec/kubeexec.go:249: Host: robot-ghost-poop-3.xn--9q8h2cq1m.ws Pod: glusterfs-sf8h7 Command: gluster --mode=script volume info vol_395feae936784e02e8631eb288d4921f --xml
Result: <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<cliOutput>
  <opRet>-1</opRet>
  <opErrno>30806</opErrno>
  <opErrstr>Volume does not exist</opErrstr>
  <volInfo>
    <volumes>
      <count>0</count>
    </volumes>
  </volInfo>
</cliOutput>
[cmdexec] DEBUG 2018/02/15 05:56:15 /src/github.com/heketi/heketi/executors/cmdexec/volume.go:261: {OpRet:-1 OpErrno:30806 OpErrStr:Volume does not exist VolInfo:{XMLName:{Space: Local:volInfo} Volumes:{XMLName:{Space: Local:volumes} Count:0 VolumeList:[]}}}
panic: runtime error: index out of range

goroutine 152 [running]:
github.com/heketi/heketi/executors/cmdexec.(*CmdExecutor).VolumeInfo(0xc420127650, 0xc4201ca240, 0x23, 0xc42029baa0, 0x24, 0x0, 0x0, 0x0)
	/build/golang/src/github.com/heketi/heketi/executors/cmdexec/volume.go:262 +0x57b
github.com/heketi/heketi/apps/glusterfs.(*VolumeEntry).replaceBrickInVolume(0xc42038e000, 0x2434f00, 0xc4202223c0, 0x2449aa0, 0xc420127650, 0x24466c0, 0xc42019e140, 0xc420350f20, 0x20, 0xc420020070, ...)
	/build/golang/src/github.com/heketi/heketi/apps/glusterfs/volume_entry_allocate.go:146 +0x30e
github.com/heketi/heketi/apps/glusterfs.(*DeviceEntry).Remove(0xc420347800, 0x2434f00, 0xc4202223c0, 0x2449aa0, 0xc420127650, 0x24466c0, 0xc42019e140, 0x2, 0xc4203d9bc0)
	/build/golang/src/github.com/heketi/heketi/apps/glusterfs/device_entry.go:436 +0x373
github.com/heketi/heketi/apps/glusterfs.(*NodeEntry).SetState(0xc42030d980, 0x2434f00, 0xc4202223c0, 0x2449aa0, 0xc420127650, 0x24466c0, 0xc42019e140, 0xc420491360, 0x6, 0x1337fee10147e685, ...)
	/build/golang/src/github.com/heketi/heketi/apps/glusterfs/node_entry.go:355 +0xa38
github.com/heketi/heketi/apps/glusterfs.(*App).NodeSetState.func2(0xbe99661f9337fee1, 0x4ca5d0f722, 0x24aa220, 0xc420026790)
	/build/golang/src/github.com/heketi/heketi/apps/glusterfs/app_node.go:376 +0xc3
github.com/heketi/heketi/vendor/github.com/heketi/rest.(*AsyncHttpManager).AsyncHttpRedirectFunc.func1(0xc420310d80, 0xc42013b410)
	/build/golang/src/github.com/heketi/heketi/vendor/github.com/heketi/rest/asynchttp.go:128 +0xf6
created by github.com/heketi/heketi/vendor/github.com/heketi/rest.(*AsyncHttpManager).AsyncHttpRedirectFunc
	/build/golang/src/github.com/heketi/heketi/vendor/github.com/heketi/rest/asynchttp.go:124 +0x60
```

I assume heketi expects there to be volumes to drop from this host, but this host doesn't have any gluster volumes according to its gluster output. I read through #635 and the linked issues in the gluster-kubernetes repo, but I am not sure if they're applicable here.

**Comment by gokulpch** [comment]
@dhain Is there any update on this issue or do you guys have figured out a better way to remove and add the node back with the same hostname and IP? As mentioned in the post this needs the user to change the Hostname and IP every-time a node fails in a HA scenario which is not acceptable in most of the production topologies.

**Comment by phlogistonjohn** [comment]
Hi @gokulpch,
Generally, we do not support "reinstating" an existing node from scratch. What you need to do is to add a new node to your cluster and then one you are in a 3 (or more) working and 1 failed state, you can remove the failed node.
I'm a bit unclear on what "change the Hostname and IP every-time a node fails" means to you. Are you somehow forced to recycle the previous node names and IPs?

**Comment by gokulpch** [comment]
@phlogistonjohn appreciate your prompt and detailed response. 
To make it clear regarding  "change the Hostname and IP every-time a node fails", we have a situation where we had to re-image and re-provision a host in a Kubernetes_HA environment having GlusterFS as hyper-converged (All three Masters comprise GlusterFS) because of a kernel issue. In this scenario if we are trying to add the re-imaged host with the same hostname and IP heketi is unable to delete the previous entry of the host which in-turn creates an issue while adding the host back using heketi-cli 
```
"Error: Hostname kube-k3 already used by node with id 55f5d99619d0cf7003fe4be2991c2e42"
```
and as you specified above there should be a replacement node before deleting one of the three nodes answers the other concern. that is related to:
```
"Error: Failed to remove device, error: No Replacement was found for resource requested to be removed"
```

**Comment by phlogistonjohn** [comment]
Stale issue. Closing.
