### ISSUE TITLE
Consider publishing a protobuf spec instead of json

### ISSUE THREAD

**Issue by cholcombe973** [heketi/heketi#928]
I'm trying to implement something that talks to heketi and unfortunately the API docs not in alignment with what the code is doing.  This picture illustrates exactly what I'm experiencing: https://codeclimate.com/blog/choose-protocol-buffers.   A potential solution for this is to publish a [protobuf](https://developers.google.com/protocol-buffers/) specification and have heketi compile against that.  Any outside clients can also compile against that with 100% assurance that they will be able to correctly communicate with heketi.  It would make developing your protocol even easier than json and more safe.  Consider: https://github.com/Comcast/Bynar/blob/master/api/protos/service.proto as an example of an easy to read API that is documented.  Also consider this: http://seriot.ch/parsing_json.php.  Golang has excellent support for protobuf!  Hardly much changes on your client and server and you gain much more assurance that you're getting something correct from the client and passing back what the client expects.

**Comment by phlogistonjohn** [comment]
I do not think the project will be converting to different serialization formats at this time. While the published documentation may be inaccurate I do not think changing format will aid us much here. Additionally, this issue has been idle for a number of months. I'm closing this issue, but if you wish to discuss further please repoen.
