### ISSUE TITLE
Need help - Adding new node succeeded in Openshift but endpoints did not update new node IP

### ISSUE THREAD

**Issue by davistran86** [heketi/heketi#929]
Hi guys, I'm trying to add new node with new device to existing gluster cluster in Openshift. I have succeeded adding new node by editing topology file. But I saw that heketi-storage-endpoints and glusterfs-dynamic-registry-glusterfs-claim did not update new IP of new node. How do I update the new node IP to those ? beacuse I think if it's not update with new node then there no repilcate data storing on it.

I was using gk-deploy (gluster-kubernetes) to deploy the gluster cluster in Openshift.

**Comment by phlogistonjohn** [comment]
Extremely stale issue. Closing.
