### ISSUE TITLE
kubernetes documentation is seriously outdated or wrong

### ISSUE THREAD

**Issue by metal3d** [heketi/heketi#931]
Hi,
Glade to use heketi on OpenShift, it seems that it's a bit more complicated to deploy heketi on kubernetes with the provided documentation.

I followed https://github.com/heketi/heketi/blob/master/doc/admin/install-kubernetes.md and see some problems:

1. https://github.com/heketi/heketi/tree/master/extras/kubernetes => there is no `deploy-heketi-deployment.json` file, only a one deployment. So that, there is no way to know how to add secret and client name. At this time, installation worked with the provided deployment, but there is only one
2. daemonset are wrong for glusterfs pods, we need to use gluster/gluster-centos:latest
3. we also need to change :dev to :latest on heketi images in deployment
2. it is not explained how to add rolebinding to let heketi list pods, I did it to finalize installaiton:
   ```
    # change gluster:heketi-service-account to YOUR_NAMESPACE:heketi-service-account
    kubectl create clusterrolebinding gluster-role-binding \
    --clusterrole=cluster-admin \
    --serviceaccount=gluster:heketi-service-account
   ```
3. maybe an example of storageClass could be nice (at this time, without any user/secret I've got some problems)

I am not here to criticize the work, I am impressed by all that is proposed in this repository and I thank you for this service which greatly helps to make volume claims work in Kubernetes and Openshift.

I'm just a bit confused now that I've got installed everything and that I'm not able to know if I finished installation as expected :)

I'm ok to adapt documentation and maybe to change yaml files, but I'm not sure that the install process is ok on my own cluster.

**Comment by phlogistonjohn** [comment]
Thank you for the feedback! I recently converted a bunch of wiki pages to these documentation files so I am not shocked to find they're outdated or have errors. Off the top of my head I know that your item 2 is correct because the old container images were recently removed and that generated other bug reports.

In addition to improving this documentation, are you aware of the [gluster-kubernetes project](https://github.com/gluster/gluster-kubernetes)? The deployment bits there are more up to date than this documentation AFAIK. The documentation there also goes over creating a storageClass, pvc, and so forth. Look over the readme, quickstart guide, and hello world example there for more info.

That said, I do want to improve this documentation but I also don't want you to be blocked on whatever you are working on.

**Comment by metal3d** [comment]
I've forgotten that repo. 
I used it to create ansible playbook to install heketi on OpenShift when official repository didn't provide it :)

Ok so, maybe we should remove the current kubernetes installation documentation and link to that repo ?

What I made was to expose heketi service and create storageClass. I can propose a PR with my own install notes - but I didn't set user/secret so...

**Comment by phlogistonjohn** [comment]
> Ok so, maybe we should remove the current kubernetes installation documentation and link to that repo ?

I'd rather fix it to the point where it's useful as an "educational" document about how these components work together. I have certainly learned a lot going through it and hitting all these issues you mentioned (and some additional ones too). I wouldn't use it as a guide to building a production setup. I'd leave that to the higher level tooling in gluster-kubernetes.

> What I made was to expose heketi service and create storageClass. I can propose a PR with my own install notes - but I didn't set user/secret so...

Feel free to provide feedback either here or in the form of a PR. I have spent some time looking into fixes and improvements on a local branch but have not got all the steps working cleanly so I did not file a PR yet myself. If you don't feel like messing around with the structure and wording of the document you can just drop your notes here in a comment and I will try to incorporate them into the doc. Either way the more useful we can make this doc the better!

**Comment by phlogistonjohn** [comment]
Stale issue. Docs point at gluster-kubernetes now. Closing.
