### ISSUE TITLE
Heketi only shows 500GB of storage when adding a raw block device of size 1.8TB

### ISSUE THREAD

**Issue by srinivasdesiraju** [heketi/heketi#932]
I am trying to add a raw block device (1.8 TB size) from a node using heketi-cli, the device gets added but when I check the info it shows the free space as 500GB. Am i missing something. Excuse me if this is something basic, I am trying to look at heketi + glusterfs combination for PV for kubernetes cluster setup at my organization.

**Comment by srinivasdesiraju** [comment]
More Info: So i have 3 nodes each with a seperate 1.8TB disk. I am trying to cluster these 3 disks using heketi. The devices are raw and i have used wipefs to make sure of it. I just added the devices to the cluster and when checked the info it just shows 500GB of available storage for each.

**Comment by raghavendra-talur** [comment]
@srinivasdesiraju please provide output of heketi-cli topology info

**Comment by srinivasdesiraju** [comment]
Here is the formatted output.

{  
   "clusters":[  
      {  
         "volumes":[  

         ],
         "nodes":[  
            {  
               "zone":1,
               "hostnames":{  
                  "manage":[  
                     "mining-cluster-worker2"
                  ],
                  "storage":[  
                     "mining-cluster-worker2"
                  ]
               },
               "cluster":"58268295ed7caf33f332844f9eee66f7",
               "id":"349aa0646c2bbd3dc86fda5e818d8a64",
               "state":"online",
               "devices":[  
                  {  
                     "name":"/dev/sdb",
                     "storage":{  
                        "total":524288000,
                        "free":524288000,
                        "used":0
                     },
                     "id":"2c481da514623335bd75988b1a7e61e9",
                     "state":"online",
                     "bricks":[  

                     ]
                  }
               ]
            },
            {  
               "zone":1,
               "hostnames":{  
                  "manage":[  
                     "mining-cluster-worker1"
                  ],
                  "storage":[  
                     "mining-cluster-worker1"
                  ]
               },
               "cluster":"58268295ed7caf33f332844f9eee66f7",
               "id":"901fff5bb1cecc79a2c06c7a9a89e2fa",
               "state":"online",
               "devices":[  
                  {  
                     "name":"/dev/sdb",
                     "storage":{  
                        "total":524288000,
                        "free":524288000,
                        "used":0
                     },
                     "id":"737697a682362d0ae332ef21740d1f98",
                     "state":"online",
                     "bricks":[  

                     ]
                  }
               ]
            }
         ],
         "id":"58268295ed7caf33f332844f9eee66f7"
      }
   ]
}

**Comment by raghavendra-talur** [comment]
@srinivasdesiraju, how did you deploy heketi?

If you deployed not by the method prescribed in gluster/gluster-kubernetes then I suspect that you are running heketi in mock mode.

To confirm, show `vgs` output of the gluster node or pod.

**Comment by phlogistonjohn** [comment]
The last activity on this issue was nearly a year ago. Closing issue. If you feel that the issue needs additional discussion please reopen it.

**Comment by kanghuzai** [comment]
# heketi-cli topology info | grep dev | grep 161738e724d85be070eb717cf241f3bc
                Id:161738e724d85be070eb717cf241f3bc   Name:/dev/sda6           State:online    Size (GiB):495     Used (GiB):491     Free (GiB):3

# heketi-cli device resync 161738e724d85be070eb717cf241f3bc
Device 161738e724d85be070eb717cf241f3bc updated

# heketi-cli topology info | grep dev | grep 161738e724d85be070eb717cf241f3bc
                Id:161738e724d85be070eb717cf241f3bc   Name:/dev/sda6           State:online    Size (GiB):495     Used (GiB):430     Free (GiB):65

**Comment by phlogistonjohn** [comment]
Please do not reply to old closed issues.
Do note that heketi is now a "deep maintenance" project. The maintenance team is not actively assisting with issues and we're focused only on major faults and security issues. We plan on ending maintenance around midyear 2023.
