### ISSUE TITLE
Secure Heketi with TLS

### ISSUE THREAD

**Issue by sosiouxme** [heketi/heketi#934]
Given growing concerns about wiretapping and multitenancy, many service providers expect to secure even internal networks. Could Heketi provide configuration to secure the connection with TLS? Otherwise it requires setting up a secure reverse proxy in front just for this purpose.

/cc @jarrpa

**Comment by f0o** [comment]
Even with a reverseproxy you run into different issues though...

I'm working my way around this one now:
```
Failed to provision volume with StorageClass "glusterfs": failed to create volume: failed to create volume: Post https://10.x.x.x/volumes: x509: failed to load system roots and no roots provided
```

All kube components have the root-certificate/s loaded so now I'm a bit lost which component is left that needs it...

**Comment by phlogistonjohn** [comment]
Hi, please refer to PR #1108 and PR #1159 the first adds support for TLS to the server and the latter aims to make it easier to use with the clients. Please experiment with it and provide any feedback that you may have.

**Comment by phlogistonjohn** [comment]
Closing this. Issue is stale and heketi supports TLS. Gluster TLS configuration should be tracked separately.
