### ISSUE TITLE
Allow smaller brick size that 1GB

### ISSUE THREAD

**Issue by mr-falken** [heketi/heketi#937]
Hi,
  I have heketi / glusterfs setup in my OpenShift env, but can't find a way to allow my users to provide volumes smaller than 1GB.
Am I missing something or is it intended ?

Thks!

**Comment by obnoxxx** [comment]
@mr-falken thanks for reaching out!
Heketi currently only supports volume sizes of 1GiB and bigger.
This is due to the size unit on the api and cli being hard-coded to 1GiB.
We intend to make it more flexible.
Let's take this issue as an RFE.

**Comment by phlogistonjohn** [comment]
This is the same request as issues #782 and #1260, as both those issues have more discussion in them I'm closing this issue as a duplicate.
