### ISSUE TITLE
Complete documentation on topology.json

### ISSUE THREAD

**Issue by bateau84** [heketi/heketi#939]
Im having problems finding any documentation on the fields available in topology.json.
It would be nice with a reference page (complete with all fields and explaining the fields) for topology.json in the docs in addition to examples.

**Comment by raghavendra-talur** [comment]
@bateau84 Thanks for filing the issue. Working on it, will add doc explaining fields soon.

**Comment by phlogistonjohn** [comment]
Very stale issue. Closing.
