### ISSUE TITLE
create volume error: error creating volume No space

### ISSUE THREAD

**Issue by zhaorendong** [heketi/heketi#947]
I had builded gluster cluster by heketi. There are 8 nodes, then I had already created volume. But one node Crashed, then I would create  a volume,but the heketi responsed :create volume error: error creating volume No space. What should I do?
create pvc error following:

Name:          pvc-ftphajd
Namespace:     hajid-ftp
StorageClass:  pvc-ftphajd
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner=kubernetes.io/glusterfs
Capacity:      
Access Modes:  
Events:
  Type     Reason              Age                From                         Message
  ----     ------              ----               ----                         -------
  Warning  ProvisioningFailed  2m (x342 over 1h)  persistentvolume-controller  Failed to provision volume with StorageClass "pvc-ftphajd": create volume error: error creating volume No space

**Comment by amiga23** [comment]
I have the same issue. RHEL 7.4 and CentOS crash during lvm operations (kernel panic).
Heketi has an own database in which it stores the devices (lvm: pv) and bricks (lvm: logical volumes)
If something fails during creation heketi just stores the bricks in the db.
When it tries to create again, heketi tries to create a new brick. It only takes information from it‘s own database and does not check real availability in LVM volume group. So after some retries heketi thinks there is no space in the VG.
Solution for kernel panics seems to be kernel upgrade to kernel-lt from elrepo.
Heketi needs a resync feature or at least a possibility to manually delete bricks.
Also with this current implementation it is not possible to over-commit the storage.

**Comment by nick-scoutbee** [comment]
Greetings!
I have the same problem but I'm using Ubuntu Server 16.04.3 LTS. 

/usr/bin/kubectl -n default exec -i deploy-heketi-5c45f969bd-rn2zr -- heketi-cli -s http://localhost:8080 topology info

Cluster Id: aac3b4d3a8e247203329d59d6fa53ed6

    File:  true
    Block: true

    Volumes:

    Nodes:

        Node Id: 6cc5c079ee5c7d265e3af204c67b5ebe
        State: online
        Cluster Id: aac3b4d3a8e247203329d59d6fa53ed6
        Zone: 1
        Management Hostnames: k8b-slv-02
        Storage Hostnames: 10.10.8.4
        Devices:
                Id:81083222995414f6dd5d712326de4c96   Name:/dev/sdc            State:online    Size (GiB):79      Used (GiB):0       Free (GiB):79
                        Bricks:

        Node Id: 849a992d13a720ac9d2d32bb99ad2f4b
        State: online
        Cluster Id: aac3b4d3a8e247203329d59d6fa53ed6
        Zone: 1
        Management Hostnames: k8b-slv-01
        Storage Hostnames: 10.10.8.5
        Devices:
                Id:2a8c08eb718467a47779d43b42e39632   Name:/dev/sdc            State:online    Size (GiB):79      Used (GiB):0       Free (GiB):79
                        Bricks:

When, I trying to run -  /usr/bin/kubectl -n default exec -i deploy-heketi-5c45f969bd-rn2zr -- heketi-cli -s http://localhost:8080  setup-openshift-heketi-storage
I see the next message: 
Error: No space
command terminated with exit code 255

**Comment by pjanuario** [comment]
I am facing the same problem and cli version is 5.0.1 and image version 5, tried to wipe the devices and recreate the topology and the problem persists.

**Comment by pjanuario** [comment]
I am having this error and I was running a cluster with 2 worker nodes, I think in my case the error is related with the volume replication factor being hardcoded to 3.

https://github.com/heketi/heketi/blob/master/client/cli/go/cmds/heketi_storage.go#L117

**Comment by donnydavis** [comment]
Just go to the container and run the setup script with replica=2. This was my workaround 

@pjanuario is correct

**Comment by pjanuario** [comment]
@donnydavis In my case I needed to extend the cluster anyway, so I added one more node and didnt had problems.

**Comment by zhaorendong** [comment]
The problem is that I can't delete the node crashed by heketi, and I can't create new volumes.

**Comment by phlogistonjohn** [comment]
This issue seems to report multiple related but independent problems.
I'd ask anyone who commented on this issue with a problem to retest their scenario on the recently released Heketi v8.0.0. If you still encounter an issue please file a _new_ issue as that will help us distinguish which error case you are hitting.
