### ISSUE TITLE
gk-deploy. Failed on setup openshift heketi storage

### ISSUE THREAD

**Issue by nick-scoutbee** [heketi/heketi#948]
I have Kubernetes cluster version 1.8.5
Also, I have tried the next Heketi versions: 4 and 5 (5==latest)
Heketi Topology file:

 {
  "clusters": [
    {
      "nodes": [
         {
           "node": {
            "hostnames": {
              "manage": [
                "qa-k8b-slv-01"
              ],
              "storage": [
                "10.10.8.5"
              ]
            },
            "zone": 1
          },
          "devices": [
            "/dev/sdc"
          ]
        },         {
           "node": {
            "hostnames": {
              "manage": [
                "qa-k8b-slv-02"
              ],
              "storage": [
                "10.10.8.4"
              ]
            },
            "zone": 1
          },
          "devices": [
            "/dev/sdc"
          ]
        }       ]
    }
  ]
}

#######################################################################
gk-deploy script output on fresh Kubernetes installation. 

./gk-deploy -gvy 
Using Kubernetes CLI.

Checking status of namespace matching 'default':
default   Active    3h
Using namespace "default".
Checking for pre-existing resources...
  GlusterFS pods ...
Checking status of pods matching '--selector=glusterfs=pod':

Timed out waiting for pods matching '--selector=glusterfs=pod'.
not found.
  deploy-heketi pod ...
Checking status of pods matching '--selector=deploy-heketi=pod':

Timed out waiting for pods matching '--selector=deploy-heketi=pod'.
not found.
  heketi pod ...
Checking status of pods matching '--selector=heketi=pod':

Timed out waiting for pods matching '--selector=heketi=pod'.
not found.
  gluster-s3 pod ...
Checking status of pods matching '--selector=glusterfs=s3-pod':

Timed out waiting for pods matching '--selector=glusterfs=s3-pod'.
not found.
Creating initial resources ... /usr/bin/kubectl -n default create -f /opt/gluster-kubernetes/deploy/kube-templates/heketi-service-account.yaml 2>&1
serviceaccount "heketi-service-account" created
/usr/bin/kubectl -n default create clusterrolebinding heketi-sa-view --clusterrole=edit --serviceaccount=default:heketi-service-account 2>&1
clusterrolebinding "heketi-sa-view" created
/usr/bin/kubectl -n default label --overwrite clusterrolebinding heketi-sa-view glusterfs=heketi-sa-view heketi=sa-view
clusterrolebinding "heketi-sa-view" labeled
OK
Marking 'qa-k8b-slv-01' as a GlusterFS node.
/usr/bin/kubectl -n default label nodes qa-k8b-slv-01 storagenode=glusterfs --overwrite 2>&1
node "qa-k8b-slv-01" labeled
Marking 'qa-k8b-slv-02' as a GlusterFS node.
/usr/bin/kubectl -n default label nodes qa-k8b-slv-02 storagenode=glusterfs --overwrite 2>&1
node "qa-k8b-slv-02" labeled
Deploying GlusterFS pods.
sed -e 's/storagenode\: glusterfs/storagenode\: 'glusterfs'/g' /opt/gluster-kubernetes/deploy/kube-templates/glusterfs-daemonset.yaml | /usr/bin/kubectl -n default create -f - 2>&1
daemonset "glusterfs" created
Waiting for GlusterFS pods to start ...
Checking status of pods matching '--selector=glusterfs=pod':
glusterfs-5kjtt   1/1       Running   0         1m
glusterfs-lhd75   1/1       Running   0         1m
OK
/usr/bin/kubectl -n default create secret generic heketi-config-secret --from-file=private_key=/dev/null --from-file=./heketi.json --from-file=topology.json=topology.json
secret "heketi-config-secret" created
/usr/bin/kubectl -n default label --overwrite secret heketi-config-secret glusterfs=heketi-config-secret heketi=config-secret
secret "heketi-config-secret" labeled
sed -e 's/\${HEKETI_EXECUTOR}/kubernetes/' -e 's#\${HEKETI_FSTAB}#/var/lib/heketi/fstab#' -e 's/\${HEKETI_ADMIN_KEY}//' -e 's/\${HEKETI_USER_KEY}//' /opt/gluster-kubernetes/deploy/kube-templates/deploy-heketi-deployment.yaml | /usr/bin/kubectl -n default create -f - 2>&1
service "deploy-heketi" created
deployment "deploy-heketi" created
Waiting for deploy-heketi pod to start ...
Checking status of pods matching '--selector=deploy-heketi=pod':
deploy-heketi-558878559f-whjcb   1/1       Running   0         31s
OK
Determining heketi service URL ... OK
/usr/bin/kubectl -n default exec -i deploy-heketi-558878559f-whjcb -- heketi-cli -s http://localhost:8080 --user admin --secret '' topology load --json=/etc/heketi/topology.json 2>&1
Creating cluster ... ID: cf70caf0c6ebb8d93bdeb191c310abd6
Creating node qa-k8b-slv-01 ... ID: 2a88d822817a468e0606f969d7393d65
Adding device /dev/sdc ... OK
Creating node qa-k8b-slv-02 ... ID: 90cc4d1bef83e9b77ab57664ce8bae43
Adding device /dev/sdc ... OK
heketi topology loaded.
/usr/bin/kubectl -n default exec -i deploy-heketi-558878559f-whjcb -- heketi-cli -s http://localhost:8080 --user admin --secret '' setup-openshift-heketi-storage --listfile=/tmp/heketi-storage.json 2>&1
Error: No space
command terminated with exit code 255
Failed on setup openshift heketi storage
This may indicate that the storage must be wiped and the GlusterFS nodes must be reset.
#######################################################################
Heketi server logs:
[heketi] INFO 2017/12/26 11:16:58 brick_num: 0
[heketi] ERROR 2017/12/26 11:16:58 /src/github.com/heketi/heketi/apps/glusterfs/volume_entry_allocate.go:34: Minimum brick size limit reached.  Out of space.
[asynchttp] INFO 2017/12/26 11:16:58 Completed job e21ffdae8fe81e30adfc78ce7202fde6 in 153.710488ms
[heketi] ERROR 2017/12/26 11:16:58 /src/github.com/heketi/heketi/apps/glusterfs/app_volume.go:154: Failed to create volume: No space
[negroni] Started GET /queue/e21ffdae8fe81e30adfc78ce7202fde6
[negroni] Completed 500 Internal Server Error in 52.2µs
########################################################################
Heketi topology info:
/usr/bin/kubectl -n default exec -i deploy-heketi-558878559f-whjcb -- heketi-cli -s http://10.244.2.4:8080 topology info

Cluster Id: cf70caf0c6ebb8d93bdeb191c310abd6

    Volumes:

    Nodes:

        Node Id: 2a88d822817a468e0606f969d7393d65
        State: online
        Cluster Id: cf70caf0c6ebb8d93bdeb191c310abd6
        Zone: 1
        Management Hostname: qa-k8b-slv-01
        Storage Hostname: 10.10.8.5
        Devices:
                Id:f0b1e71b184aead2da332166e77e0fbb   Name:/dev/sdc            State:online    Size (GiB):79      Used (GiB):0       Free (GiB):79
                        Bricks:

        Node Id: 90cc4d1bef83e9b77ab57664ce8bae43
        State: online
        Cluster Id: cf70caf0c6ebb8d93bdeb191c310abd6
        Zone: 1
        Management Hostname: qa-k8b-slv-02
        Storage Hostname: 10.10.8.4
        Devices:
                Id:1777e3c7dc5e607dab4a0cd558103b35   Name:/dev/sdc            State:online    Size (GiB):79      Used (GiB):0       Free (GiB):79
                        Bricks:
#############################################################################
Summary:
1. script cannot perform this step: 
/usr/bin/kubectl -n default exec -i deploy-heketi-558878559f-whjcb -- heketi-cli -s http://localhost:8080 --user admin --secret '' setup-openshift-heketi-storage --listfile=/tmp/heketi-storage.json 2>&1
Error: No space
command terminated with exit code 255

2. Same result in manual mode. 

Could you please help me or provide any advice.
Thanks!

**Comment by anshulvermapatel** [comment]
facing the same issue, can someone guide on this please

**Comment by nixpanic** [comment]
Please make sure that the right kernel modules are loaded on the host. A temporary solution is mentioned in [issue 434](https://github.com/gluster/gluster-kubernetes/issues/434#issuecomment-365978125) with more suggestions in gluster/gluster-containers#75.

**Comment by anshulvermapatel** [comment]
@nixpanic , Problem solved actually the glusterfs nodes were not able to communicate with each other because of aws security settings.

**Comment by nixpanic** [comment]
@anshulvermapatel thanks for coming back with the info! In case of further issues, just open a new issue.
