### ISSUE TITLE
How can I backup the Kubernetes secret "heketi-db-backup" to the heketi database?

### ISSUE THREAD

**Issue by zhaorendong** [heketi/heketi#949]
I had builded a gluster cluster by heketi and made "backup_db_to_kube_secret": true. Then the heketi created a secret "heketi-db-backup" in Kubernetes.But when the heketi pod restarted, the database of heketi pod "/var/lib/heketi/heketi.db" is a new database  that no original data. How can I backup the Kubernetes secret "heketi-db-backup" to the heketi database?

**Comment by zhaorendong** [comment]
Is there any solution?

**Comment by phlogistonjohn** [comment]
Hi @zhaorendong I've experienced what I can only describe as a similar issue in testing but unfortunately do not know the cause. I suspect there's an order of operations issue where an empty db is saved to the secret, you populate the db with data, but that does not properly get saved to the secret, and then when the pod moves or is restarted it restores the empty db. I'm sorry to say I don't have a solution for your problem ATM.

On the plus side the new release of Heketi comes with a feature to manually export the db to a json file via the heketi-cli. If you're willing to skip the secret approach and use the heketi cli directly this might be a useful approach to backing up the db. (Note that you'll still want to use the internal hosting volume to deal with pod restarts... this suggestion is truly for backup)

See the help for "heketi-cli db dump" for more details. For the restore side look at the help of "heketi db import".

**Comment by fritchie** [comment]
what would be the proper method to restore heketi.db fro a backup taken with "heketi-cli db dump"?

**Comment by phlogistonjohn** [comment]
Stale issue. Closing.

**Comment by hetii** [comment]
This issue still occure and should not be closed.
Btw do we need kubeexec configuration to have this mechanism functional?
