### ISSUE TITLE
Enhancement: the heketi image is hardcoded in the heketi-cli binary

### ISSUE THREAD

**Issue by jiaqingw** [heketi/heketi#950]
Here at the line https://github.com/heketi/heketi/blob/master/client/cli/go/cmds/heketi_storage.go#L56

the docker image name is heketi/heketi:dev is hardcoded. This does not allow for custom image names to be provided. 

It would be better if we can have a command line option to override this.

**Comment by jiaqingw** [comment]
in tools such as https://github.com/gluster/gluster-kubernetes. we wanted to be able to automate the deployment sometimes in order to avoid internal firewall blockage issue to public internet. we have to re-publish the image to an internal docker registry, hence the need for a custom image name but the heketi-cli hardcoded this one make it impossible to override.

**Comment by DanyC97** [comment]
@raghavendra-talur by any chance do you have any history / reason why the need for the image to be hardcoded to "dev" tag ?

**Comment by phlogistonjohn** [comment]
Maybe my personal interpretation of the word "hardcoded" differs but it doesn't seem to me like it is hard-coded as much as defaulted to dev if you don't supply a different value to the option.
I can't speak for @raghavendra-talur  but looking at the change history indicates that when the option was added the default value used was the original image name for the job (which *was* hardcoded back then).

So as far as @jiaqingw originally requested to have an option to specify the image for the copy job, we have that. If there's no desire to change the default we ought to be able to close this issue.

I'll leave it open for a little while longer in case I've misinterpreted the request or if you all want to discuss further changes to the option.

**Comment by raghavendra-talur** [comment]
@DanyC97 @jiaqingw I don't know why the default it heketi:dev. It was like that even before I joined the project. 
As @phlogistonjohn points out, you do have an option of specifying it in the cli now. 
```
$ ./heketi-cli setup-openshift-heketi-storage --help
Creates a dedicated GlusterFS volume for Heketi.    
Once the volume is created, a Kubernetes/OpenShift  
list object is created to configure the volume.     

Usage:                    
  heketi-cli setup-openshift-heketi-storage [flags] 

Flags:                    
      --durability string                           
        Optional: Durability type. Values are:      
                none: No durability, for testing with single storage server environments.                
                replicate: (Default) Replica volume. (default "replicate")                               
  -h, --help                help for setup-openshift-heketi-storage                                      
      --image string        container image to run this job (default "heketi/heketi:dev") 
```

use `--image` to change it. 

If that is sufficient, we can close the issue.  I will also have a look at the release scripts to change it to match the version of the release. Thoughts?

**Comment by DanyC97** [comment]
okay @raghavendra-talur @phlogistonjohn fair point. I think we can close this one as fixed by `--image`

**Comment by phlogistonjohn** [comment]
Thanks! Closing.
