### ISSUE TITLE
Is heketi supposed to work with glusterfs 3.7?

### ISSUE THREAD

**Issue by bryanlarsen** [heketi/heketi#951]
I had a node fail and rebuilt it.   Now I'm trying to do a `heketi-cli device remove` to mirror the data onto devices that actually exist.

However, this crashes the heketi container.   As I was gathering info for a bug report, I realized that I was running glusterfs 3.7, and that's quite old, which is probably why it's crashing.

Now I think I have a chicken/egg problem:  I can't migrate the bricks from the broken node because I have an old version of glusterfs, and I can't switch to a later version of glusterfs because that I have some volumes with only a single valid instance of their bricks.   Suggestions?   Is it safe to use glusterfs administration techniques, or will that make my database out of sync?

**Comment by bryanlarsen** [comment]
I rebuilt the storage cluster with glusterfs 3.12, and as a test was able to use the heketi cli to remove a device that had bricks on it, and the bricks were successfully moved.

**Comment by phlogistonjohn** [comment]
@bryanlarsen it sounds like you were able to resolve the issue, so I'm going to close this issue.
If you feel the issue needs additional discussion please feel free to reopen.
