### ISSUE TITLE
Heketi operations not reflecting in glusterfs server

### ISSUE THREAD

**Issue by ghadimani21** [heketi/heketi#956]
Started the two glusterfs server and able to create and mount volumes in two servers.
I have built heketi for version 5.0.1. 
This is how I started the server from heketi after build.
```
cd $GOPATH/src/github.com/heketi/heketi/ 
cp etc/heketi.json heketi.json
./heketi --config=heketi.json 
```

The server started running on 8080
Now I am using the heketi client to interact with heketi server as follow
```
export HEKETI_CLI_SERVER=http://localhost:8080 
cd $GOPATH/src/github.com/heketi/heketi/client/cli/go
```
 Added the topology.json with data in glusterfs server and able to run the following commands
```
./heketi-cli topology load --json=./topology.json
 ./heketi-cli volume create --size=1 --replica=2 
./heketi-cli volume create --name=testvol --size=40 --durability="replicate" --replica=2
```

I am able to see the volumes created using heketi client. and also able to fetch all details of volume
But when I check the gluserfs server. I don't see any volumes created.

**Comment by obnoxxx** [comment]
@ghadimani21, thanks for reporting your issue!

The example config file `etc/heketi.json` configures the **mock** executor which does not send commands to gluster at all and is used for testing purposes.

Please change this setting to `ssh` or `kubernetes` whichever applies to you (I assume `ssh`). You also have to fill the details of how to reach the gluster server with ssh (the settings under `sshexec`).

Please reopen the issue if you still experience problems after making these changes.
