### ISSUE TITLE
blockvolume creation fails for size greater than 1024 GiB

### ISSUE THREAD

**Issue by raghavendra-talur** [heketi/heketi#957]
In a setup with 3 block hosting volumes of size 500GiB, 500GiB and 2048 GiB, if a blockvolume of size 1500GiB is requested it fails with "Error: Default Block Hosting Volume size is less than block volume requested"

This is because requested size is being compared with default(note: not max) size of block volumes.

**Comment by phlogistonjohn** [comment]
Seems fixed. Closing.
