### ISSUE TITLE
Facing issue while adding device

### ISSUE THREAD

**Issue by ravisalamani** [heketi/heketi#960]
I am able to do the following operations on glusterfs
Started the gluserfs using the command
$ glusterd

started creating volume as follow:
```
gluster> volume create demo1 server1:/test-volume force
volume create: demo1: success: please start the volume to access data
gluster> volume start demo1
volume start: demo1: success
gluster>exit
```
$ mkdir /demo1_mount
$ mount -t glusterfs in-ibmibm1034.persistent.co.in:/demo1 /demo1_mount
$ df -h
```
Filesystem                             Size  Used Avail Use% Mounted on
udev                                   2.0G     0  2.0G   0% /dev
tmpfs                                  396M   21M  375M   6% /run
/dev/mapper/ubuntu--vg-root             94G  7.8G   82G   9% /
tmpfs                                  2.0G  1.6M  2.0G   1% /dev/shm
tmpfs                                  5.0M     0  5.0M   0% /run/lock
tmpfs                                  2.0G     0  2.0G   0% /sys/fs/cgroup
/dev/vda1                              472M   57M  391M  13% /boot
none                                    94G  7.8G   82G   9% /var/lib/docker/aufs/mnt/e360f81133a393b05c0414c8628b80da23b00ae2fe1f05591b38e753a9709ecf
shm                                     64M     0   64M   0% /var/lib/docker/containers/6e8f1659893e6c5b44c07d94c1f76b789784dfee460e043a34a3dd8c33465f75/shm
tmpfs                                  396M     0  396M   0% /run/user/0
tmpfs                                  396M     0  396M   0% /run/user/1003
server1:/demo1   94G  7.8G   82G   9% /demo1_mount
```
With above commands I can say that the glusterfs is good. I am able to create and mount the volume.
I stoped and removed the volume demo1

Now I started the heketi sever to use ssh
I am trying interact with it using the heketi-client as follow:
```
$ heketi-cli cluster create mycluster
Cluster id: 6fb9a65d2df70b3652a39e8d2bdd4712
$ heketi-cli node add --cluster=6fb9a65d2df70b3652a39e8d2bdd4712 --zone=1 --management-host-name=server1 --storage-host-name=server1
Node information:
Id: 672e56fa7e6191e814e2abf948c2886e
State: online
Cluster Id: 6fb9a65d2df70b3652a39e8d2bdd4712
Zone: 1
Management Hostname server1
Storage Hostname server1
$ heketi-cli device add --name=/dev/vda5  --node=672e56fa7e6191e814e2abf948c2886e
Error: Can't initialize physical volume "/dev/vda5" of volume group "ubuntu-vg" without -ff
```

I have checked the physical devices and tried the wipefs.
Still not able to add the device.

$ pvscan
  PV /dev/vda5   VG ubuntu-vg       lvm2 [99.52 GiB / 0    free]
  Total: 1 [99.52 GiB] / in use: 1 [99.52 GiB] / in no VG: 0 [0   ]

$ wipefs -af /dev/vda5
/dev/vda5: 8 bytes were erased at offset 0x00000218 (LVM2_member): 4c 56 4d 32 20 30 30 31

Currently I am able to add and mount volume in glusterfs. What is to be done to achieve the same result using heketi-client?

**Comment by phlogistonjohn** [comment]
The recent release of heketi now provide a --destroy-existing-data flag when adding a device. If you are absolutely sure that your device is free of data you need you might consider testing that option (or its equivalent in the topology file).
Because this issue is a bit old and did not get much activity I'm closing it. If you find that the new version of Heketi or the option do not work for you please feel free to reopen this issue.
