### ISSUE TITLE
NewSimpleAllocatorFromDb always results in `nil` allocator being assigned to App 

### ISSUE THREAD

**Issue by gnanderson** [heketi/heketi#961]
Heketi daemon breaks for me with the following error - because there is no check for the error type returned from `AddCluster` inside `NewSimpleAllocatorFromDb`. This in turns makes the error result of the bolt transaction return `nil` to the App's allocator field.

Does the method signature really need to be this? (doesn't look like the error is really doing anything useful after being returned)

    func (s *SimpleAllocator) AddCluster(clusterId string) error

Maybe the meat of the AddCluster method should just be:

    if _, ok := s.rings[clusterId]; !ok {
        s.rings[clusterId] = NewSimpleAllocatorRing()
    }

    return

```
Setting up heketi database
  File: /var/lib/heketi/heketi.db
  Size: 45056     	Blocks: 88         IO Block: 131072 regular file
Device: 34h/52d	Inode: 11429731829863480122  Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2018-01-16 03:36:18.060184716 +0000
Modify: 2018-01-16 14:34:23.305478196 +0000
Change: 2018-01-16 14:34:23.349477530 +0000
 Birth: -
Heketi v5.0.0-164-gc4cb58d
[kubeexec] WARNING 2018/01/16 16:59:58 Rebalance on volume expansion has been enabled.  This is an EXPERIMENTAL feature
[heketi] INFO 2018/01/16 16:59:58 Loaded kubernetes executor
[heketi] ERROR 2018/01/16 16:59:58 /src/github.com/heketi/heketi/apps/glusterfs/allocator_simple.go:149: cluster id 605335e39dd9c7a4cfaff880da8daaab already exists
[heketi] ERROR 2018/01/16 16:59:58 /src/github.com/heketi/heketi/apps/glusterfs/allocator_simple.go:149: cluster id 605335e39dd9c7a4cfaff880da8daaab already exists
[heketi] ERROR 2018/01/16 16:59:58 /src/github.com/heketi/heketi/apps/glusterfs/allocator_simple.go:149: cluster id 605335e39dd9c7a4cfaff880da8daaab already exists
[heketi] INFO 2018/01/16 16:59:58 Loaded simple allocator
[heketi] INFO 2018/01/16 16:59:58 GlusterFS Application Loaded
Listening on port 8080
```

**Comment by obnoxxx** [comment]
@gnanderson Thanks for reporting!

I took the liberty to edit your post to properly format the heketi output/log with triple-backticks to insert code verbatim.

Your comment is valid. And the proposal is not bad. The whole code around the allocator is currently being refactored, so I'll think about it some more and will come back to you.

**Comment by obnoxxx** [comment]
@gnanderson, with the recent overhaul of the allocator code that has gone into master and just into v6.0.0 of heketi, this should be gone. Please reopen if problems persist, thanks!
