### ISSUE TITLE
Feature Request: adjust replication factor on existing volumes using heketi-cli

### ISSUE THREAD

**Issue by robdewit** [heketi/heketi#963]
Feature request/Missing functionality

How do I adjust the replication factor of existing volumes. Heketi provides functionality to add nodes to a cluster, but I can't find a way using heketi to add bricks with a new replication factor.

I could just create bricks and add those with new replication factor using 'gluster' cli utility. Then the volumes would be like I want them, but wouldn't that disturb the topology database Heketi keeps track of itself?

**Comment by obnoxxx** [comment]
Hi @robdewit , thanks for your request!
Currently this is not possible, but definitely something we'd want to look into implementing in the future.

**Comment by robdewit** [comment]
I have fixed it using the db editing functionality that has been added lately. I had to add the bricks using 'gluster' and then edit the database JSON file and re-import it. 

Still, I would prefer doing it with hekeit-cli.

**Comment by imranrazakhan** [comment]
Hi @obnoxxx any plan for implementation of this feature?

**Comment by phlogistonjohn** [comment]
Stale issue. Closing.
