### ISSUE TITLE
Howto create two clusters on the same nodes for two different types of disks (slow and fast)

### ISSUE THREAD

**Issue by adoerler** [heketi/heketi#976]
Hi,

I'm trying to accomplish the following setup:
* two storage nodes with one SSD and one HDD Softraid-Array in each server
* one spearate server running the heketi service
* to be able to claim either the fast or the slow storage, I've tried to setup a topology of two clusterIDs
* in Kubernetes there are two storage classes for each of those cluster IDs. This way it would be possible to claim either a fast or a slow storage depending on the application needs

My `topology.json` looks like:
```
{
    "clusters": [
        {
            "nodes": [
                {
                    "node": {
                        "hostnames": {
                            "manage": [
                                "node1.domain.local"
                            ],
                            "storage": [
                                "node1.domain.local"
                            ]
                        },
                        "zone": 1
                    },
                    "devices": [
                        "/dev/md2"
                    ]
                },
                {
                    "node": {
                        "hostnames": {
                            "manage": [
                                "node2.domain.local"
                            ],
                            "storage": [
                                "node2.domain.local"
                            ]
                        },
                        "zone": 2
                    },
                    "devices": [
                        "/dev/md2"
                    ]
                }
            ]
        },
        {
            "nodes": [
                {
                    "node": {
                        "hostnames": {
                            "manage": [
                                "node1.domain.local"
                            ],
                            "storage": [
                                "node1.domain.local"
                            ]
                        },
                        "zone": 1
                    },
                    "devices": [
                        "/dev/md3"
                    ]
                },
                {
                    "node": {
                        "hostnames": {
                            "manage": [
                                "node2.domain.local"
                            ],
                            "storage": [
                                "node2.domain.local"
                            ]
                        },
                        "zone": 2
                    },
                    "devices": [
                        "/dev/md3"
                    ]
                }
            ]
        }
    ]
}
```

Loading this topology in heketi leads to the following error:
```
heketi-cli topology load --json=/etc/heketi/topology.json
Creating cluster ... ID: 272e...
	Creating node node1.domain.local ... ID: 04ef...
		Adding device /dev/md2 ... OK
	Creating node node2.domain.local ... ID: 9909...
		Adding device /dev/md2 ... OK
Creating cluster ... ID: 9309...
	Creating node node1.domain.local ... Unable to create node: Hostname node1.doerler.local already used by node with id 04ef...
```

Can someone tell me, howto manage to types of disks on the same nodes?
As far as I've seen from Kubernetes side, the clusterID is the only chance for Heketi to distinguish which disks to use, therefor I need a way to get it running this way.

One workaround was to use additional hostnames to have different hostnames for the manage property of both clusters. This works, but when I do the first PVC claim from Kubernetes, Heketi get stuck in a loop (After starting the volume it gets destroyed immediatly), you can se this in the following log snippet (you can see the Dextroying volume message after a successfull volume start):
```
[sshexec] DEBUG 2018/01/23 08:31:35 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:176: Host: node2.domain.local:22 Command: sudo /bin/bash -c 'gluster
--mode=script volume start vol_f1b2b82f8e21ad6230259f270dc65d57'
Result: volume start: vol_f1b2b82f8e21ad6230259f270dc65d57: success
[heketi] INFO 2018/01/23 08:31:35 Created volume f1b2b82f8e21ad6230259f270dc65d57
[asynchttp] INFO 2018/01/23 08:31:35 asynchttp.go:129: Completed job 0ece8b28cd4f37566fe31b88efdb800f in 3.634543253s
[negroni] Started GET /queue/0ece8b28cd4f37566fe31b88efdb800f
[negroni] Completed 303 See Other in 123.562µs
[negroni] Started GET /volumes/f1b2b82f8e21ad6230259f270dc65d57
[negroni] Completed 200 OK in 1.462641ms
[negroni] Started GET /clusters/ed132ccd06d0eba867f248902666f3e1
[negroni] Completed 200 OK in 284.195µs
[negroni] Started GET /nodes/aa56b1b8d8ded22e417d624bf60851bd
[negroni] Completed 200 OK in 1.084885ms
[negroni] Started GET /nodes/f0a12b118c6b2ca82fdb30755867679c
[negroni] Completed 200 OK in 616.289µs
[negroni] Started DELETE /volumes/f1b2b82f8e21ad6230259f270dc65d57
[negroni] Completed 202 Accepted in 608.153µs
[asynchttp] INFO 2018/01/23 08:31:35 asynchttp.go:125: Started job 485c967005ae670c8dc840ef53d3f530
[heketi] INFO 2018/01/23 08:31:35 Destroying volume f1b2b82f8e21ad6230259f270dc65d57
[negroni] Started GET /queue/485c967005ae670c8dc840ef53d3f530
[negroni] Completed 200 OK in 126.425µs
```

Any help would be greatly appreciated.
Kind regards from Austria
Andreas

**Comment by adoerler** [comment]
Hello again,

after days of struggling it seems like k8s requires the storages to be IP addresses, not hostnames (see also #945).

I'm not really happy with this, but I could nod find another way to fix this problem.

My final topology.json looks like:
```
{
    "clusters": [
        {
            "nodes": [
                {
                    "node": {
                        "hostnames": {
                            "manage": [
                                "hkmgc1n1.domain.local"
                            ],
                            "storage": [
                                "192.168.192.1"
                            ]
                        },
                        "zone": 1
                    },
                    "devices": [
                        "/dev/md2"
                    ]
                },
                {
                    "node": {
                        "hostnames": {
                            "manage": [
                                "hkmgc1n2.domain.local"
                            ],
                            "storage": [
                                "192.168.192.3"
                            ]
                        },
                        "zone": 2
                    },
                    "devices": [
                        "/dev/md2"
                    ]
                }
            ]
        },
        {
            "nodes": [
                {
                    "node": {
                        "hostnames": {
                            "manage": [
                                "hkmgc2n1.domain.local"
                            ],
                            "storage": [
                                "192.168.192.2"
                            ]
                        },
                        "zone": 1
                    },
                    "devices": [
                        "/dev/md3"
                    ]
                },
                {
                    "node": {
                        "hostnames": {
                            "manage": [
                                "hkmgc2n2.domain.local"
                            ],
                            "storage": [
                                "192.168.192.4"
                            ]
                        },
                        "zone": 2
                    },
                    "devices": [
                        "/dev/md3"
                    ]
                }
            ]
        }
    ]
}
```

So if one needs different storage classes (i.e. different HEKETI cluster IDs) on the very same nodes a different hostname per HEKETI cluster ID is  required for the heketi managment:

Host file for two nodes cluster looks like:
```
# add alias names for heketi managment
172.20.26.20   node1.doerler.local hkmgc1n1.doerler.local hkmgc2n1.doerler.local node1
172.20.26.21   node2.doerler.local hkmgc1n2.doerler.local hkmgc2n2.doerler.local node2
```

Additionally you'll need a separate IP address for each HEKETI cluster ID, as kn8s requires "stroage" to be a valid IP address. (Remember: Heketi dokumentation states that one should use hostnames).

Kind regards
Andreas

**Comment by obnoxxx** [comment]
Hi @adoerler, thanks for reaching out!

It is correct that "storage" needs to be IP addresses while "manage" are dns names.

Are you running gluster in contiainers in kubernetes or outside of kubernetes?

If I get you right, the main objective is to treat different types of disks with one heketi instance. Currently you can do it only as you say by having 2 different clusters, one for each quality of disk, and point different storage classes to the different clusters. It is currently not possible to have multiple Gluster clusters spanning the same hosts, not even with containers in kubernetes, due to the way our gluster containers are currently built. So you would need to distribute the different types of disks across different hardware (or virtual) hosts.

We plan on implementing disk quality flags to disks and nodes/clusters in heketi, so that in the future it will be possible to select a certain disk quailty from heketi with flags in the volume create request from just a single cluster, too.

**Comment by adoerler** [comment]
Hi @obnoxxx,

thanks for your reponse!
I'm running gluster outside kubernetes.

I'm fine with using different clusters for different types of disks, thats totally okay.
My objective is, that you need separate hostnames (manage) for spinning up another HEKETI cluster on the same host, because HEKETI won't allow a cluster for an existing hostname used by a previously created cluster.

All in all HEKETI does a great job, it's easy to add a PVC and it's nice to see HEKETI doing all the hard work under the hood :)

---

Unfortunatelty it turned out in the last days that glusterfs itself has a pretty poor performance for our use case (e.g. running a WordPress Container with a glusterfs PVC is at least 10 times slower than running it outside of glusterfs. Even dbench shows a performance of about 6-7MB/s while doing the dbench on the disks under glusterfs would give about 60-70MB/s. (Nodes are connected with a 2x 10GBit Interface).
I know this is a non-HEKETI issue, but it would be great to hear what performance you are seeing on your systems, as it seems that I'm not the only one facing this issue.

Kind regards
Andreas

**Comment by eonar** [comment]
hi @obnoxxx 

wish to touchbase if the disk quality flag option has been implemented granted it has been almost 6 months since the last posting?

excerpts quoted below for easier references:
"...We plan on implementing disk quality flags to disks and nodes/clusters in heketi, so that in the future it will be possible to select a certain disk quailty from heketi with flags in the volume create request from just a single cluster, too..."

thank you
  yk

**Comment by phlogistonjohn** [comment]
Stale issue. Closing.

**Comment by holmesb** [comment]
> "It is currently not possible to have multiple Gluster clusters spanning the same hosts"

 @phlogistonjohn, I face the task of creating two sets of names and IP addresses for my nodes so that Heketi can create two clusters, one for each storage class: SSD & HD.  To my mind, this issue is very much active, not stale.

**Comment by phlogistonjohn** [comment]
This issue was considered stale due to inactivity. Staleness is not related to validity.

That said you might want to skip trying to do the two cluster thing, which was a terrible hack all along and take a look at the [tag matching design doc](/heketi/heketi/blob/master/docs/design/tag-matching.md). The vast majority of this plan has been implemented on master.

**Comment by Boran** [comment]
2.5 years later, the issue still seems valid to me.
As regards the suggestion with tags, that sound better, but it is only fully implemented in gluster v10?
When I tags with OKD v3.11 storage class to heketi/gluster v8, the tags are ignored.
