### ISSUE TITLE
heketi in k8s error namespace not found

### ISSUE THREAD

**Issue by zhaoyun006** [heketi/heketi#980]
I use default heketi-deployment.json and heketi.json create heketi in k8s, path is https://github.com/heketi/heketi/tree/master/extras/kubernetes/ 

use command 
1、 kubectl create secret generic heketi-config-secret --from-file=./heketi.json
2、kubectl create -f heketi-deployment.json
     service "heketi" created
    deployment "heketi" created

An error occurred

[root@k8s-test_1_55_114 glusterfs]#  kubectl get deploy
NAME      DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
heketi    1         1         1            0           5m

[root@k8s-test_1_55_114 glusterfs]# kubectl get pod
NAME                     READY     STATUS             RESTARTS   AGE
glusterfs-57vwx          1/1       Running            0          10h
glusterfs-7dn4k          1/1       Running            0          10h
glusterfs-cxv7w          1/1       Running            0          10h
glusterfs-fnlv2          1/1       Running            0          10h
glusterfs-h26dc          1/1       Running            0          10h
heketi-845d68854-bdctq   0/1       CrashLoopBackOff   4          4m

#kubectl logs  heketi-845d68854-bdctq
Heketi v4.0.0-8-g9372c22-release-4
[kubeexec] ERROR 2018/01/24 00:02:37 /src/github.com/heketi/heketi/executors/kubeexec/kubeexec.go:125: Namespace must be provided in configuration: File /var/run/secrets/kubernetes.io/serviceaccount/namespace not found
[heketi] ERROR 2018/01/24 00:02:37 /src/github.com/heketi/heketi/apps/glusterfs/app.go:85: Namespace must be provided in configuration: File /var/run/secrets/kubernetes.io/serviceaccount/namespace not found

Ask for help!

**Comment by zhaoyun006** [comment]
I mount config namespace    
Mounts:
      /etc/heketi from config (rw)
      /var/lib/heketi from db (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from heketi-namespace (rw)

heketi start error
I show logs:
  [root@k8s-test_1_55_114 kube-templates]# kubectl logs deploy-heketi-658d778d8f-4cn4g     --namespace=kube-system         
Setting up heketi database
  File: /var/lib/heketi/heketi.db
  Size: 0               Blocks: 0          IO Block: 4096   regular empty file
Device: fd00h/64768d    Inode: 168120368   Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2018-01-24 00:58:24.121832742 +0000
Modify: 2018-01-24 00:58:24.121832742 +0000
Change: 2018-01-24 00:58:24.121832742 +0000
 Birth: -
Heketi v5.0.0-181-ga60acdd
ERROR: Unable to start application

There is no more information

**Comment by phlogistonjohn** [comment]
Hi There,
Could you provide a bit more detail about how you are deploying and configuring heketi? Are you doing it all by hand?  What version of Kubernetes are you using?

The log line in your first message should only be emitted if you did not manually specify a namespace in the json config file and that heketi cannot successfully probe its own namespace.  Is there a /var/run/secrets/kubernetes.io/serviceaccount/namespace file available within the heketi container when it runs?

**Comment by zhaoyun006** [comment]
@phlogistonjohn 
I configure heketi.json file


    "kubeexec": {
      "rebalance_on_expansion": true,
      "namespace" : "default"
    },

start pod error

#kubectl logs heketi-794587b794-rcvcn 
Heketi v4.0.0-8-g9372c22-release-4
[kubeexec] ERROR 2018/01/25 00:27:41 /src/github.com/heketi/heketi/executors/kubeexec/kubeexec.go:133: Unable to create configuration for Kubernetes: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
[heketi] ERROR 2018/01/25 00:27:41 /src/github.com/heketi/heketi/apps/glusterfs/app.go:85: Unable to create configuration for Kubernetes: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
ERROR: Unable to start application

I don't know How to configure token

**Comment by phlogistonjohn** [comment]
It is probably not worth trying to manually provide all the Kubernetes executor configuration values manually. I would focus on debugging why Heketi can not automatically get this information from var/run/secrets/kubernetes.io/serviceaccount/  

What version of Kubernetes are you using?

What output do you get from the following commands?
* kubectl exec -it <heketipod> -- ls -l /var/run/secrets/kubernetes.io/serviceaccount/
* kubectl exec -it <heketipod> -- grep -n -RI '' /var/run/secrets/kubernetes.io/serviceaccount/

(Replace <heketipod> with the actual pod name)

**Comment by zhaoyun006** [comment]
kubernetes version is 1.8.2
I modify heketi container  Entrypoint , can start heketi container

I exec following commands
sh-4.3# ls  /var/run/secrets/kubernetes.io/serviceaccount/
ls: cannot access '/var/run/secrets/kubernetes.io/serviceaccount/': No such file or directory
sh-4.3# ls  /var/run/secrets/                             
ls: cannot access '/var/run/secrets/': No such file or directory

manually create dir

#mkdir /var/run/secrets/kubernetes.io/serviceaccount/ -p
#touch /var/run/secrets/kubernetes.io/serviceaccount/token

start heketi server ok

sh-4.3# heketi --config /etc/heketi/heketi.json 
Heketi v4.0.0-8-g9372c22-release-4
E0126 00:10:53.937425     106 config.go:275] Expected to load root CA config from /var/run/secrets/kubernetes.io/serviceaccount/ca.crt, but got err: open /var/run/secrets/kubernetes.io/serviceaccount/ca.crt: no such file or directory
[kubeexec] WARNING 2018/01/26 00:10:53 Rebalance on volume expansion has been enabled.  This is an EXPERIMENTAL feature
[heketi] INFO 2018/01/26 00:10:53 Loaded kubernetes executor
[heketi] INFO 2018/01/26 00:10:54 Loaded simple allocator
[heketi] INFO 2018/01/26 00:10:54 GlusterFS Application Loaded
E0126 00:10:54.222074     106 config.go:275] Expected to load root CA config from /var/run/secrets/kubernetes.io/serviceaccount/ca.crt, but got err: open /var/run/secrets/kubernetes.io/serviceaccount/ca.crt: no such file or directory
Listening on port 8080

I don't know How to configure token
What file content in  /var/run/secrets/kubernetes.io/serviceaccount/token  ?

**Comment by zhaoyun006** [comment]
@phlogistonjohn 
I now can run heketi server，thanks!

**Comment by zhaoyun006** [comment]
@phlogistonjohn 
I don't know How to configure token
What file content in /var/run/secrets/kubernetes.io/serviceaccount/token ?

can you help me?
