### ISSUE TITLE
[RFE] Heketi DB should have a Change Sequence Number

### ISSUE THREAD

**Issue by obnoxxx** [heketi/heketi#981]
For instance in order to be able to tell whether the allocator's ring structure cache is up to date, it would be good if our db had a Change Sequence Number that would be set to 0 upon DB creation and bumped (+1) automatically with every transaction (Update()).

For now, this would need to be implemented with a wrapper around boltdb, but I also put an RFE into Boltdb: https://github.com/boltdb/bolt/issues/741.

**Comment by obnoxxx** [comment]
As per suggestion in boltdb/bolt#741, this can be solved with grabbing Tx.ID() from within a db.View().

**Comment by phlogistonjohn** [comment]
Stale issue. Closing.
