### ISSUE TITLE
Heketi minimum volume size should be documented

### ISSUE THREAD

**Issue by SaravanaStorageNetwork** [heketi/heketi#987]
As per code minimum volume size supported is 2GB.
[heketi](https://github.com/heketi/heketi/blob/master/apps/glusterfs/app_volume_test.go#L218
)

But, this is not documented anywhere ( as I checked) . 
Can we add this as part of heketi-cli man page and as part of heketi documentation in github?  
Also, specific reason to have this restriction will be great.

User may have carved out 1GB bricks and try creating the volume and ends up with error. 
This will help to have early warning and size the bricks correctly.

**Comment by obnoxxx** [comment]
@SaravanaStorageNetwork This is ony this test: The min volume size is gated by the BrickMinSize which can be set to 1 (==1GiB) at minimum. This test sets it to 4, see https://github.com/heketi/heketi/blob/master/apps/glusterfs/app_volume_test.go#L178.

It can be configure.
You are right, that apparently this is not clearly documented...

**Comment by raghavendra-talur** [comment]
@SaravanaStorageNetwork search for "BrickMinSize" for the config variable which sets minimum brick size.

**Comment by obnoxxx** [comment]
The documentation has been added by PR #1017.
