### ISSUE TITLE
"Failed create pod sandbox" using heketi-bootstrap.json

### ISSUE THREAD

**Issue by jmogden** [heketi/heketi#997]
Sorry if this is a duplicate. 
I'm trying to set up a Kubernetes cluster using kubeadm and want to use heketi and glusterfs as ways to provision storage. Following the steps [here](https://github.com/heketi/heketi/blob/master/doc/admin/install-kubernetes.md), I get stuck on after I run kubectl create -f heketi-bootstrap.json When I run kubectl describe pods/deploy-heketi-pod, I get:

`Type   --    Reason     --                       Age   --                  From      --                       Message`

`Normal -- Scheduled     --                  33s      --                default-scheduler    --     Successfully assigned deploy-heketi-pod to jmogden-node1`

`Normal --   SuccessfulMountVolume -- 33s           --             kubelet, jmogden-node1  --MountVolume.SetUp succeeded for volume "db"`

`Normal --    SuccessfulMountVolume -- 33s        --                kubelet, jmogden-node1 --  MountVolume.SetUp succeeded for volume "heketi-service-account-token-b8qwn"`

`Normal --   SuccessfulMountVolume --  33s         --               kubelet, jmogden-node1  --MountVolume.SetUp succeeded for volume "config"`

`Warning --  FailedCreatePodSandBox -- 26s  (x7 over 32s) -- kubelet, jmogden-node1 -- Failed create pod sandbox.`

`Normal   -- SandboxChanged       --      26s  (x7 over 32s) --  kubelet, jmogden-node1 --  Pod sandbox changed, it will be killed and re-created.`
 
`Warning --  FailedSync    --                     26s  (x8 over 32s)   -- kubelet, jmogden-node1 -- Error syncing pod`

I have my master and worker nodes connected together using flannel. Not really sure what could be causing the failure. The node that the heketi-bootstrap is ran is is working fine and connected to the master node. Any help is appreciated in advanced.

*Sorry for the formatting

**Comment by raghavendra-talur** [comment]
@jmogden this is most likely a network config issue. The error about Sandbox comes from kubernetes. I have not used flannel but changing some settings should make it work.

**Comment by jmogden** [comment]
I'll look into it. Thanks for the quick response.

**Comment by jmogden** [comment]
So I did some looking around and I can't seem to find anything that makes sense. I looked at the iptables (sudo iptables -L) and ran ss -s and netstat -s to look at the network connections. I'm not really sure where else to look. Any ideas?

**Comment by jmogden** [comment]
I don't know if I should start a new ticket or not, but I tore down the cluster I was using and restarted from scratch. This resulted in not having the sandbox issue (don't know what changed) and instead the initial pod says that the Liveness and Readiness probe failed. I think it's trying to reach outside of the network that I set up for it to run on. Will investigate further.

**Comment by phlogistonjohn** [comment]
If you are still encountering this issue would you please try deploying via the [gluster-kubernetes project](https://github.com/gluster/gluster-kubernetes)? If that still fails please file an issue with that project. The templates in the heketi repos are more for demonstration purposes rather than production.

Hopefully my answer was satisfactory. I'm closing this issue now. If you feel the issue needs additional discussion please feel free to reopen.
